[[installation-in-opendaylight-release]]
== Installation in OpenDaylight Release

[[helium-release]]
=== Helium Release

* SNMP4SDN's feature is already packaged in the Zip package (please
download and unzip the Zip package
http://www.opendaylight.org/software/downloads[here]), and *_no further
installation steps are required_*.

[[hydrogen-release]]
=== Hydrogen Release

* SNMP4SDN's bundle is already packaged in the
link:Release/Hydrogen/Service Provider/Installation Guide[Hydrogen
Release Service Provider Edition]'s Zip package (please download and
unzip the
link:Release/Hydrogen/Service Provider/Installation_Guide#Getting_the_Zip_File[
Zip package]), and *_no further installation steps are required_*.

[[troubleshooting]]
== Troubleshooting

SNMP4SDN:User_Guide#Troubleshooting[ User Guide: Troubleshooting]

[[installation-from-source]]
== Installation from source

Steps overview: (details as below)

\1. SNMP4SDN:Installation_Guide#Pull_code_via_git_CLI[ Pull code via git
CLI]

\2. If one'd like to proceed automatic
SNMP4SDN:Installation_Guide#Unit_test[ unit test],
SNMP4SDN:Installation_Guide#Manual_modifications_to_the_code[ manual
modifications to the code] is required

\3. SNMP4SDN:Installation_Guide#Build_the_code[ Build the code]

\4. Install the bundle/feature

[[pull-code-via-git-cli]]
=== Pull code via git CLI

------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/snmp4sdn.git
------------------------------------------------------------------

or

------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/snmp4sdn.git
------------------------------------------------------------

[[build-the-code]]
=== Build the code

One may either build the code in console or using Eclipse, as follows.

[[build-the-code-in-console]]
==== Build the code in console

-----------------
cd snmp4sdn/
mvn clean install
-----------------

[[import-and-build-the-code-in-eclipse]]
==== Import and build the code in Eclipse

[[import-the-code]]
===== Import the code

Eclipse --> File --> Import --> Existing Maven Projects +
--> Root Directory: Browse to select the SNMP4SDN's directory +
--> Selects all the Project POMs found --> ... Done

[[build-the-code-1]]
===== Build the code

On the project "snmp4sdn" --> Debug As --> Maven build

[[install-the-bundlefeature]]
=== Install the bundle/feature

[[installuninstall-the-feature-in-karaf]]
==== Install/Uninstall the feature in Karaf

* Prerequisite

Karaf contains only artifacts of version Helium by default, as a result
if one'd like to build SNMP4SDN manually, the 'controller' has to be
built first so as to generate the needed dependencies of SNMP4SDN. +
To download and build 'controller':

--------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/controller.git
(or git clone https://git.opendaylight.org/gerrit/controller)
cd controller
mvn clean install
--------------------------------------------------------------------

* Get the OpenDayilght Helium Release

\1. Download http://www.opendaylight.org/software/downloads[Here] +
2. Unzip it (unzip to, for example, ~/distribution-karaf-xxx-Helium-xxx)

* Launch Karaf

----------------------------------------------------------------------------------------------------
cd <Helium_distribution's_directory>  (for example, by default, ~/distribution-karaf-xxx-Helium-xxx)
cd bin
./karaf
----------------------------------------------------------------------------------------------------

* Install

In Karaf console, replace the feature repo from Helium to your new one.
And then install the feature. +

--------------------------------------------------------------------------
feature:repo-list | grep snmp4sdn  (To see the version number of snmp4sdn)
--------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------------------------
feature:repo-remove mvn:org.opendaylight.snmp4sdn/x.x.x-Helium/xml/features  (x.x.x is as the version number shown in the previous command)
-------------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------
feature:repo-add mvn:org.opendaylight.snmp4sdn/y.y.y-SNAPSHOT/xml/features

  (y.y.y is as the version number of the snmp4sdn plugin manually built.
   The version number: refer to snmp4sdn's source code, ~/snmp4sdn/snmp4sdn/pom.xml, 
   find <artifactId>snmp4sdn</artifactId><version>y.y.y-SNAPSHOT</version>)
-------------------------------------------------------------------------------------

--------------------------------
feature:install odl-snmp4sdn-all
--------------------------------

* Uninstall

To completely uninstall SNMP4SDN plugin, uninstall the bundle as well as
the feature. 1. Firstly, list the install bundles of SNMP4SDN

-----------------------
bundle:list | grep snmp
-----------------------

There should list something like this:

------------------------------------
326       ACTIVATED   snmp4sdn
328       ACTIVATED   snmp4sdn-mdsal
------------------------------------

\2. Uninstall the bundles

--------------------------------------------------------------------------------------------
bundle:uninstall <snmp4sdn_bundle_id>  <snmp4sdn_shell_bundle_id> <snmp4sdn_mdsal_bundle_id>
--------------------------------------------------------------------------------------------

For example: bundle uninstall 326 327 328

\3. Remove the feature and feature-repo

---------------------------------------------------------------------------
feature:uninstall odl-snmp4sdn-snmp4sdn
feature:uninstall odl-snmp4sdn-all
feature:repo-remove mvn:org.opendaylight.snmp4sdn/0.1.3-Helium/xml/features
---------------------------------------------------------------------------

\4. Check over One may use "bundle:list" and "feature:list" commands to
examine whether the bundles and features are completely removed.

----------------------------
bundle:list | grep snmp4sdn
feature:list | grep snmp4sdn
----------------------------

[[install-the-bundle-in-osgi]]
==== Install the bundle in OSGi

Steps:

\1. After SNMP4SDN:Installation_Guide#Build_the_code[ building the
code], one may find the bundle here:
snmp4sdn/snmp4sdn/tartget/snmp4sdn-x.x.x-SNAPSHOT.jar.

\2. Copy the snmp4sdn-x.x.x-SNAPSHOT.jar to the controller's directory,
somewhere under the controller's directory:
.../distribution.opendaylight-osgipackage/opendaylight/plugins/. In this
way, the controller will automatically load and activate the bundle.

\3. Alternative to 2, one may load and activate the bundle by
himself/herself, in controller's OSGi console:

---------------------------------------------------------------------------------------------------------------------------------------------------
install file:<file path to snmp4sdn-x.x.x-SNAPSHOT.jar>
(note to use double slash in file path, for example: install file:///home//usersdn//controller//opendaylight//plugins//snmp4sdn-0.1.2-SNAPSHOT.jar)
---------------------------------------------------------------------------------------------------------------------------------------------------

\4. Then the BundleId would be shown (say, ###).

Then, activate the bundle:

---------
start ###
---------

\5. Using the command "ss snmp" to see whether the SNMP4SDN plugin has
been activated successfully. It should appear like this:

--------------------------------------------------------------
osgi> ss snmp
id        State       Bundle
326       ACTIVATED   org.opendaylight.snmp4sdn.snmp4sdn-0.1.2
--------------------------------------------------------------

[[test-the-code]]
== Test the code

* Hardware is required: a subnet consisting of real Ethernet switches.
* For the first time to test the code,
SNMP4SDN:Installation_Guide#Manual_modifications_to_the_code[ manual
modifications to the code] is required, then
SNMP4SDN:Installation_Guide#Unit_test[ unit test] will automatically
proceed when building the code, and plugin test

[[manual-modifications-to-the-code]]
=== Manual modifications to the code

\1. Edit the :File:SwitchDB.txt[switch_login_db.csv] (located at
snmp4sdn/snmp4sdn/src/test) for the Ethernet switches. (Note that the
first line is title and should not be removed)

\2. In CmethUtil.java, modify the file path to switch_login_db.csv.

\3. For all xxxTest.java files under the subdirectories of
snmp4sdn/snmp4sdn/src/test, remove the mark in front of "@Test" so that
the tests will proceed when building the code.

\4. In these xxxTest.java files, the MAC address given to input to
addNewSwitch() should be consistent with that in switch_login_db.csv,
otherwise the program cannot know the mapped IP address and so on.

(Finally, you may want to SNMP4SDN:Installation_Guide#Build_the_code[
rebuild the code])

[[unit-test]]
=== Unit test

Steps:

\0. SNMP4SDN:Installation_Guide#Manual_modifications_to_the_code[ manual
modifications to the code] is done

\1. SNMP4SDN:Installation_Guide#Build_the_code[ Build the code]

\2. Unit tests would show up during the building. The summary of test
results should appear like these:

* At the end of every module's unit tests:

--------------------------------------------------------------------------------------------------------------------------
Tests run: XX, Failures: XX, Errors: XX, Skipped: XX, Time elapsed: XX sec - in org.opendaylight.snmp4sdn.internal.XXXTest
--------------------------------------------------------------------------------------------------------------------------

* At the end of all modules' tests:

----------------------------------------------------
Tests run: XX, Failures: XX, Errors: XX, Skipped: XX
----------------------------------------------------

[[plugin-test]]
=== Plugin test

* All the SNMP4SDN plugin's features could be manually tested, please
refer to SNMP4SDN:User_Guide[ User Guide].

