[[meeting-summary]]
== Meeting Summary

* Sharon is going to lead the Data Collection POC.
* In the Data Collection POC, mininet is going to be used for simulating
and collecting Open Flow statistics.
* Sharon raised the concern of using ODL common persistence API.
Confirmation needs to be made so that the API provides the generic
interface for store and query data from persistence data store. Action
item is for YuLing to investigate and communicate with ODL common
persistence API to make sure it provides the APIs needed.
* YuLing mentioned that Project Creation/Checklist is 90% done.
** TSDR Jenkins job created
** Initial pom files being checked in
* Sharon confirmed that Data Collection POC could be demoed by Feb 5th.
* For TSDR design, no formal design doc is needed. We will create two
links under Design section on TSDR Main page: Data Collection and Data
Storage. Design owners will create Wiki pages under these two links.
* Mohnish mentioned that new testing resources will be added to TSDR
project.
* Mohnish suggested to add Data Storage POC as the next step task.
* YuLing mentioned that Trello pages for tracking the project creation
has been created. The team likes the idea to use this tool for project
tracking.
* Clustering discussion.
** To support MD-SAL multiple instances scenario, since the follower
nodes won't get notification when the data is replicated form the
master/lead, we won't be able to store the data into HBase single node
on followers.
** An enhancement has been logged so as to allow followers to generate
notification when data is replicated to the
followers:(https://bugs.opendaylight.org/show_bug.cgi?id=2139)
** We will post the request to clustering team to see if the
notification limitation enhancement to controller-dev, dev, and
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Lithium:Release_Plan#Requests_from_Other_Projects
** We would not do any coding for HBase single node deployment scenario
to support MD-SAL clustering.
** if the enhancement is beyond Lithium, we'll release note the
limitation in Lithium.

