[[introduction]]
= Introduction

This developer guide will help to understand the architecture and
development of Southbound plugin to the OpenContrail Platform.

[[opendaylight---southbound-plugin-to-the-opencontrail-platform-architecture]]
= OpenDaylight - Southbound plugin to the OpenContrail Platform
Architecture

For a deep dive into the ODL plugin2oc architecture please see the
following:

* Southbound plugin to the OpenContrail platform:Main[Architecture]
*
Project_Proposals:Southbound plugin to the OpenContrail platform[Project
Proposal]

[[openstack---opendaylight---southbound-plugin-to-the-opencontrail-platform-integration]]
= OpenStack - OpenDaylight - Southbound plugin to the OpenContrail
Platform Integration

Following links detail the procedure for installations and environmental
setup.

*
Southbound plugin to the OpenContrail platform:Environment Setup[Environment
Setup]
* Southbound Plugin to the OpenContrail Platform:User_Guide[User Guide]

[[getting-the-code]]
= Getting the Code

Download/Gerrit the plugin from the respository:

`git clone `https://git.opendaylight.org/gerrit/plugin2oc.git[`https://git.opendaylight.org/gerrit/plugin2oc.git`] +
`or` +
`git clone `ssh://[`ssh://`]`@git.opendaylight.org:29418/plugin2oc`

[[importing-the-code-in-to-eclipse]]
== Importing the Code in to Eclipse

Please check out link:Eclipse Setup[Eclipse Setup]

[[source-code-organization]]
== Source Code Organization

The plugin2oc project generates 2 x OSGi Bundles:

* *org.opendaylight.plugin2oc* is the plugin2oc Plugin and Library
* *org.opendaylight.plugin2oc.neutron* is the OpenStack Neutron
Integration

These correspond to the _plugin2oc_ and _neutron_ directories in the
source tree.

_commons_ contains the project's parent POM file for Maven which is used
to get consistency of settings across the project.

[[building-the-code]]
== Building the code

From the root of the project

`mvn clean install`

You may need to change your MAVEN_OPTS

`export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"`

[[running-the-distribution]]
== Running the Distribution

* Replace plugin2oc jar file - *plugin2oc.neutron-0.1.jar* into the
depolyment folder of the Base/Virtualization/SP edition i.e under the
directory location

`/root/controller/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage/opendaylight/plugins`

* Run the controller using the command ./run.sh

