[[opencontrail-single-installation---full-mode]]
== OpenContrail Single Installation - FULL MODE

\1. *Clone repository:* - Clone openContrail to your local repository:

`git clone -b test-m1-build  `https://github.com/shravani89/contrail-installer[`https://github.com/shravani89/contrail-installer`]`.`

\2. *localrc changes:* - Make the following changes in the localrc file:

`cd /home/stack/devstack` +
`vi localrc/` +
 +
`USE_SCREEN=True (to view the screens using screen -x contrail)` +
`CONTRAIL_REPO_PROTO=https (uncomment it so that repository is downloaded through https)` +
`CONTRAIL_BRANCH=test-m1-build (uncomment it so that the repo available in shravani89 will be downloaded or synced)` +
`OPENSTACK_IP=IP of openstack (to point to openstack with full mode)` +
`INSTALL_PROFILE=ALL (Full mode installation)`

\3. *Run Contrail build* - This is done so as to downloads the
dependencies and build the code

`Remove contrail-web-controller and contrail-web-core from /opt/stack/contrail/.repo/manifest.xml` +
`./contrail.sh build`

\4. *Run Contrail install* - This installs the contrail modules.

`./contrail.sh install`

\5. *Run Contrail configure* - It recreates the conf files.

`./contrail.sh configure `

\6. *Start contrail* - To start contrail

`./contrail.sh start`

\7. *Stop Contrail* - To stop contrail

`./contrail.sh stop`

Once the contrail controller is up and running, add the keystone
auth_host in /etc/contrail/* files to point to the OpenStack Controller
keystone for authentication.

[[openstack-controller-node-opendaylight-installation]]
== OpenStack CONTROLLER Node + OpenDaylight Installation

\1. Clone Repository as a stack user

`cd ~/ git clone `git://github.com/openstack-dev/devstack.git[`git://github.com/openstack-dev/devstack.git`] +
`cd devstack ` +
`git remote add opendaylight `https://github.com/CiscoSystems/devstack.git[`https://github.com/CiscoSystems/devstack.git`]` ` +
`git fetch opendaylight git checkout opendaylight`

\2. On the control node, your *local.conf* will look like the below:

`[local|localrc]` +
`LOGFILE=stack.sh.log ` +
`#SCREEN_LOGDIR=/opt/stack/data/log ` +
`#LOG_COLOR=False ` +
`OFFLINE=true ` +
`RECLONE=no ` +
 +
`#Only uncomment the below two lines if you are running on Fedora ` +
`#enable_service rabbit ` +
`#disable_service qpid ` +
`disable_service n-cpu ` +
`enable_service n-cond ` +
`disable_service n-net ` +
`enable_service q-svc ` +
`enable_service q-dhcp ` +
`enable_service q-l3 ` +
`enable_service q-meta ` +
`enable_service tempest ` +
`enable_service nova ` +
`enable_service n-novnc ` +
`enable_service quantum ` +
 +
`Q_HOST=$SERVICE_HOST ` +
`HOST_IP=10.10.10.2 ` +
 +
`MULTI_HOST=true ` +
 +
`Q_PLUGIN=ml2 ` +
`Q_ML2_PLUGIN_MECHANISM_DRIVERS=opendaylight,logger ` +
`ENABLE_TENANT_TUNNELS=True ` +
`NEUTRON_REPO=`https://github.com/CiscoSystems/neutron.git[`https://github.com/CiscoSystems/neutron.git`]` ` +
`NEUTRON_BRANCH=odl_ml2 ` +
 +
`VNCSERVER_PROXYCLIENT_ADDRESS=10.10.10.2 ` +
`VNCSERVER_LISTEN=0.0.0.0 ` +
 +
`HOST_NAME=tcs-VirtualBox ` +
`SERVICE_HOST_NAME=${HOST_NAME} ` +
`SERVICE_HOST=10.10.10.2 ` +
` ` +
`MYSQL_HOST=$SERVICE_HOST ` +
`RABBIT_HOST=$SERVICE_HOST ` +
`GLANCE_HOSTPORT=$SERVICE_HOST:9292 ` +
`KEYSTONE_AUTH_HOST=$SERVICE_HOST ` +
`KEYSTONE_SERVICE_HOST=$SERVICE_HOST ` +
 +
`MYSQL_PASSWORD=mysql ` +
`RABBIT_PASSWORD=rabbit ` +
`QPID_PASSWORD=rabbit ` +
`SERVICE_TOKEN=service ` +
`SERVICE_PASSWORD=admin ` +
`ADMIN_PASSWORD=admin ` +
 +
`[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]` +
`[agent] ` +
`minimize_polling=True ` +
 +
`[ml2_odl] ` +
`url=`http://10.10.10.6:8080/controller/nb/v2/neutron[`http://10.10.10.6:8080/controller/nb/v2/neutron`]` ` +
`username=admin ` +
`password=admin `

\3. You should note in the above you will want to change the following:

`* HOST_IP: This is the management IP of the control host itself. ` +
`* VNCSERVER_PROXYCLIENT_ADDRESS: The management IP address of the control node itself. ` +
`* HOST_NAME: The host name of the control node. ` +
`* SERVICE_HOST: The management IP of the control node. ` +
`* The "url" parameter in the ml2_odl section near the bottom: Make sure the url and credentials match your OpenDaylight configuration.` +
`  If you didn't change the default username password for ODL, you can leave those bits alone.` +

\5. Check for the ML2 configurations on the system in ml2_odl.conf file

[[openstack-compute-node-installation]]
== OpenStack COMPUTE Node installation:

\1. Clone Repository as a stack user

`cd ~/ git clone `git://github.com/openstack-dev/devstack.git[`git://github.com/openstack-dev/devstack.git`] +
`cd devstack `

\2. On the compute node, your *local.conf* will look like the below:

`[local|localrc]` +
`LOGFILE=stack.sh.log ` +
`SCREEN_LOGDIR=/opt/stack/data/log ` +
`LOG=True ` +
`DEBUG=True ` +
`OFFLINE=true ` +
 +
`SERVICE_HOST=10.10.10.2 ` +
`PHYSICAL_INTERACE=eth0 ` +
`Q_PLUGIN=contrail ` +
`STACK_DIR=$(cd $(dirname $0) && pwd) ` +
 +
`disable_all_services ` +
`enable_service neutron nova n-cpu n-novnc g-api rabbit q- ` +
 +
`PHYSICAL_NETWORK=default ` +
 +
`MYSQL_HOST=$SERVICE_HOST ` +
`RABBIT_HOST=$SERVICE_HOST ` +
`GLANCE_HOSTPORT=$SERVICE_HOST:9292 ` +
 +
`VNCSERVER_PROXYCLIENT_ADDRESS=10.10.10.1 ` +
`VNCSERVER_LISTEN=0.0.0.0 ` +
 +
`MYSQL_PASSWORD=mysql ` +
`RABBIT_PASSWORD=rabbit ` +
`SERVICE_TOKEN=service ` +
`SERVICE_PASSWORD=admin ` +
`ADMIN_PASSWORD=admin ` +
 +
`NEUTRON_REPO=`https://github.com/juniper/neutron.git[`https://github.com/juniper/neutron.git`]` ` +
`NEUTRON_BRANCH=contrail/havana ` +
 +
`# repo proto is https or (default) ssh. Leave commented for ssh ` +
`CONTRAIL_REPO_PROTO=https ` +
 +
`# proto for openstack bits. Use HTTPS if git is firewalled ` +
`# GIT_BASE=`https://git.openstack.org[`https://git.openstack.org`]` ` +
 +
`# use contrail VIF driver with NOVA ` +
`NOVA_VIF_DRIVER=nova_contrail_vif.contrailvif.VRouterVIFDriver `

\3. In the above you will want to change the following:

`* SERVICE_HOST: The management IP of the control node. ` +
`* VNCSERVER_PROXYCLIENT_ADDRESS: The management IP address of the compute node itself.`
