[[introduction]]
== Introduction

This user guide will help to setup and integrate Southbound plugin to
the OpenContrail Platform.

[[how-to-run]]
== How to run

* Download/Gerrit the following from the respository:

`   1. Opendaylight controller Base or SP edition` +

--------------------------------------------------------------
http://www.opendaylight.org/software/downloads 
OR
git clone https://git.opendaylight.org/gerrit/p/controller.git
--------------------------------------------------------------

`   2. Southbound plugin to the OpenContrail Platform` +
` `

---------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/plugin2oc.git
or
git clone ssh://<username>@git.opendaylight.org:29418/plugin2oc
---------------------------------------------------------------

* Replace plugin2oc related jar files into the depolyment folder of the
Base/Virtualization/SP edition i.e under the directory location

-------------------------------------------------------------------------------------------------------------------------
/root/controller/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage/opendaylight/plugins
-------------------------------------------------------------------------------------------------------------------------

* Run the controller using the command ./run.sh

[[configuration]]
== Configuration

* Initial Setup

Refer this link for inital setup of OpenDaylight controller
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Pulling,Hacking,_and_Pushing_the_Code_from_the_CLI.

* ODL-Southbound plugin to the OpenContrail Platform Deployment

`   Copy the following jar from plugin2oc into /root/controller/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage/opendaylight/plugins directory of OpenDaylight. `

-------------------------
plugin2oc.neutron-0.1.jar
-------------------------

* Configuration changes

`   Add the following parameters to config.ini file under the directory /root/controller/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage/opendaylight/plugins/configuration/config.ini`

-------------------------------------------------------------------------------------------------
plugin2oc.apiserver.port = 8082 //<By default API server runs on port 8082>
plugin2oc.apiserver.ipaddress = <IP Address of the node where OpenContrail API Server is running>
-------------------------------------------------------------------------------------------------

[[related-documents]]
== Related Documents

*
Project_Proposals:Southbound plugin to the OpenContrail platform[Project
Proposal]
*
Southbound plugin to the OpenContrail platform:Environment Setup[Environment
Setup]

