[[introduction]]
= Introduction

This chapter fully implements the RPC stubs in ToasterImpl which were
introduced in the previous chapter.

[[implementing-the-rpcs]]
= Implementing the RPCs

ToasterImpl.java - more additions to the code developed in chapter 5.

`   private final ExecutorService executor;` +
`   // The following holds the Future for the current make toast task.` +
`   // This is used to cancel the current toast.` +
`   private final AtomicReference``> currentMakeToastTask = new AtomicReference<>();` +
`   private final AtomicLong amountOfBreadInStock = new AtomicLong( 100 );` +
`   private final AtomicLong toastsMade = new AtomicLong(0);` +
`   // Thread safe holder for our darkness multiplier.` +
`   private final AtomicLong darknessFactor = new AtomicLong( 1000 );` +
`   public ToasterImpl() {` +
`       executor = Executors.newFixedThreadPool(1);` +
`   }`

`   /**************************************************************************` +
`    * AutoCloseable Method` +
`    *************************************************************************/` +
`   /**` +
`    * Called when MD-SAL closes the active session. Cleanup is performed, i.e.` +
`    * all active registrations with MD-SAL are closed,` +
`    */` +
`   @Override` +
`   public void close() throws Exception {` +
`       // When we close this service we need to shutdown our executor!` +
`       executor.shutdown();` +
`       // Delete toaster operational data from the MD-SAL data store` +
`       WriteTransaction tx = dataService.newWriteOnlyTransaction();` +
`       tx.delete(LogicalDatastoreType.OPERATIONAL,TOASTER_IID);` +
`       Futures.addCallback( tx.submit(), new FutureCallback``() {` +
`           @Override` +
`           public void onSuccess( final Void result ) {` +
`               LOG.debug( "Delete Toaster commit result: {}", result );` +
`           }` +
`           @Override` +
`           public void onFailure( final Throwable t ) {` +
`               LOG.error( "Delete of Toaster failed", t );` +
`           }` +
`       } );` +
`       ...` +
`   }` +
`   /**************************************************************************` +
`    * ToasterService Methods` +
`    *************************************************************************/` +
`   /**` +
`    * Restconf RPC call implemented from the ToasterService interface.` +
`    * Cancels the current toast.` +
`    * Implementation to be filled in a later chapter.` +
`    * in postman, `http://localhost:8181/restconf/operations/toaster:cancel-toast[`http://localhost:8181/restconf/operations/toaster:cancel-toast`] +
`    */` +
`   @Override` +
`   public Future``> cancelToast() {` +
`       LOG.info("cancelToast");` +
`       Future`` current = currentMakeToastTask.getAndSet( null );` +
`       if( current != null ) {` +
`           current.cancel( true );` +
`       }` +
`       // Always return success from the cancel toast call.` +
`       return Futures.immediateFuture( RpcResultBuilder.`` success().build() );` +
`   }` +
`   /**` +
`    * RestConf RPC call implemented from the ToasterService interface.` +
`    * Attempts to make toast.` +
`    * Implementation to be filled in a later chapter.` +
`    * in postman, `http://localhost:8181/restconf/operations/toaster:make-toast[`http://localhost:8181/restconf/operations/toaster:make-toast`] +
`    * { "input" : { "toaster:toasterDoneness" : "10", "toaster:toasterToastType":"wheat-bread" } }` +
`    */` +
`   @Override` +
`   public Future``> makeToast(final MakeToastInput input) {` +
`       LOG.info("makeToast: {}", input);` +
`       final SettableFuture``> futureResult = SettableFuture.create();` +
`       checkStatusAndMakeToast( input, futureResult, 2 );` +
`       LOG.info("makeToast returning...");` +
`       return futureResult;` +
`   }` +
`   /**` +
`    * RestConf RPC call implemented from the ToasterService interface.` +
`    * Restocks the bread for the toaster` +
`    * Implementation to be filled in a later chapter.` +
`    * in postman, `http://localhost:8181/restconf/operations/toaster:restock-toaster[`http://localhost:8181/restconf/operations/toaster:restock-toaster`] +
`    * { "input" : { "toaster:amountOfBreadToStock" : "3" } }` +
`    */` +
`   @Override` +
`   public Future``> restockToaster(final RestockToasterInput input) {` +
`       LOG.info( "restockToaster: {}", input );` +
`       amountOfBreadInStock.set( input.getAmountOfBreadToStock() );` +
`       if( amountOfBreadInStock.get() > 0 ) {` +
`           ToasterRestocked reStockedNotification = new ToasterRestockedBuilder()` +
`               .setAmountOfBread( input.getAmountOfBreadToStock() ).build();` +
`           notificationService.publish( reStockedNotification );` +
`       }` +
`       return Futures.immediateFuture( RpcResultBuilder.`` success().build() );` +
`   }` +
`   /**************************************************************************` +
`    * ToasterImpl Private Methods` +
`    *************************************************************************/` +
`   private RpcError makeToasterOutOfBreadError() {` +
`       return RpcResultBuilder.newError( ErrorType.APPLICATION, "resource-denied",` +
`               "Toaster is out of bread", "out-of-stock", null, null );` +
`   }` +
`   private RpcError makeToasterInUseError() {` +
`       return RpcResultBuilder.newWarning( ErrorType.APPLICATION, "in-use",` +
`               "Toaster is busy", null, null, null );` +
`   }` +
`   private Toaster buildToaster( final ToasterStatus status ) {` +
`       return new ToasterBuilder().setToasterManufacturer( TOASTER_MANUFACTURER )` +
`                                  .setToasterModelNumber( TOASTER_MODEL_NUMBER )` +
`                                  .setToasterStatus( status )` +
`                                  .build();` +
`   }` +
`   private void setToasterStatusUp( final Function`` resultCallback ) {` +
`       WriteTransaction tx = dataService.newWriteOnlyTransaction();` +
`       tx.put( LogicalDatastoreType.OPERATIONAL,TOASTER_IID, buildToaster( ToasterStatus.Up ) );` +
`       Futures.addCallback( tx.submit(), new FutureCallback``() {` +
`           @Override` +
`           public void onSuccess( final Void result ) {` +
`               notifyCallback( true );` +
`           }` +
`           @Override` +
`           public void onFailure( final Throwable t ) {` +
`               // We shouldn't get an OptimisticLockFailedException (or any ex) as no` +
`               // other component should be updating the operational state.` +
`               LOG.error( "Failed to update toaster status", t );` +
`               notifyCallback( false );` +
`           }` +
`           void notifyCallback( final boolean result ) {` +
`               if( resultCallback != null ) {` +
`                   resultCallback.apply( result );` +
`               }` +
`           }` +
`       } );` +
`   }` +
`   private boolean outOfBread()` +
`   {` +
`       return amountOfBreadInStock.get() == 0;` +
`   }` +
`   /**` +
`    * Read the ToasterStatus and, if currently Up, try to write the status to` +
`    * Down. If that succeeds, then we essentially have an exclusive lock and` +
`    * can proceed to make toast.` +
`    */` +
`   private void checkStatusAndMakeToast( final MakeToastInput input,` +
`           final SettableFuture``> futureResult,` +
`           final int tries ) {` +
`       LOG.info( "checkStatusAndMakeToast");` +
`       final ReadWriteTransaction tx = dataService.newReadWriteTransaction();` +
`       ListenableFuture``> readFuture =` +
`           tx.read( LogicalDatastoreType.OPERATIONAL, TOASTER_IID );` +
`       final ListenableFuture`` commitFuture =` +
`           Futures.transform( readFuture, new AsyncFunction``,Void>() {` +
`               @Override` +
`               public ListenableFuture`` apply(` +
`                       final Optional`` toasterData ) throws Exception {` +
`                   ToasterStatus toasterStatus = ToasterStatus.Up;` +
`                   if( toasterData.isPresent() ) {` +
`                       toasterStatus = toasterData.get().getToasterStatus();` +
`                   }` +
`                   LOG.debug( "Read toaster status: {}", toasterStatus );` +
`                   if( toasterStatus == ToasterStatus.Up ) {` +
`                       if( outOfBread() ) {` +
`                           LOG.debug( "Toaster is out of bread" );` +
`                           return Futures.immediateFailedCheckedFuture(` +
`                                   new TransactionCommitFailedException( "", makeToasterOutOfBreadError() ) );` +
`                       }` +
`                       LOG.debug( "Setting Toaster status to Down" );` +
`                       // We're not currently making toast - try to update the status to Down` +
`                       // to indicate we're going to make toast. This acts as a lock to prevent` +
`                       // concurrent toasting.` +
`                       tx.put( LogicalDatastoreType.OPERATIONAL, TOASTER_IID,` +
`                               buildToaster( ToasterStatus.Down ) );` +
`                       return tx.submit();` +
`                   }` +
`                   LOG.debug( "Oops - already making toast!" );` +
`                   // Return an error since we are already making toast. This will get` +
`                   // propagated to the commitFuture below which will interpret the null` +
`                   // TransactionStatus in the RpcResult as an error condition.` +
`                   return Futures.immediateFailedCheckedFuture(` +
`                           new TransactionCommitFailedException( "", makeToasterInUseError() ) );` +
`               }` +
`           } );` +
`       Futures.addCallback( commitFuture, new FutureCallback``() {` +
`           @Override` +
`           public void onSuccess( final Void result ) {` +
`               // OK to make toast` +
`               currentMakeToastTask.set( executor.submit( new MakeToastTask( input, futureResult ) ) );` +
`           }` +
`           @Override` +
`           public void onFailure( final Throwable ex ) {` +
`               if( ex instanceof OptimisticLockFailedException ) {` +
`                   // Another thread is likely trying to make toast simultaneously and updated the` +
`                   // status before us. Try reading the status again - if another make toast is` +
`                   // now in progress, we should get ToasterStatus.Down and fail.` +
`                   if( ( tries - 1 ) > 0 ) {` +
`                       LOG.debug( "Got OptimisticLockFailedException - trying again" );` +
`                       checkStatusAndMakeToast( input, futureResult, tries - 1 );` +
`                   }` +
`                   else {` +
`                       futureResult.set( RpcResultBuilder.`` failed()` +
`                               .withError( ErrorType.APPLICATION, ex.getMessage() ).build() );` +
`                   }` +
`               } else {` +
`                   LOG.debug( "Failed to commit Toaster status", ex );` +
`                   // Probably already making toast.` +
`                   futureResult.set( RpcResultBuilder.`` failed()` +
`                           .withRpcErrors( ((TransactionCommitFailedException)ex).getErrorList() )` +
`                           .build() );` +
`               }` +
`           }` +
`       } );` +
`   }` +
`   private class MakeToastTask implements Callable`` {` +
`       final MakeToastInput toastRequest;` +
`       final SettableFuture``> futureResult;` +
`       public MakeToastTask( final MakeToastInput toastRequest,` +
`                             final SettableFuture``> futureResult ) {` +
`           this.toastRequest = toastRequest;` +
`           this.futureResult = futureResult;` +
`       }` +
`       @Override` +
`       public Void call() {` +
`           try` +
`           {` +
`               // make toast just sleeps for n seconds per doneness level.` +
`               long darknessFactor = ToasterImpl.this.darknessFactor.get();` +
`               Thread.sleep(darknessFactor * toastRequest.getToasterDoneness());`

`           }` +
`           catch( InterruptedException e ) {` +
`               LOG.info( "Interrupted while making the toast" );` +
`           }` +
`           toastsMade.incrementAndGet();` +
`           amountOfBreadInStock.getAndDecrement();` +
`           if( outOfBread() ) {` +
`               LOG.info( "Toaster is out of bread!" );` +
`               notificationService.publish( new ToasterOutOfBreadBuilder().build() );` +
`           }` +
`           // Set the Toaster status back to up - this essentially releases the toasting lock.` +
`           // We can't clear the current toast task nor set the Future result until the` +
`           // update has been committed so we pass a callback to be notified on completion.` +
`           setToasterStatusUp( new Function``() {` +
`               @Override` +
`               public Void apply( final Boolean result ) {` +
`                   currentMakeToastTask.set( null );` +
`                   LOG.debug("Toast done");` +
`                   futureResult.set( RpcResultBuilder.``success().build() );` +
`                   return null;` +
`               }` +
`           } );` +
`           return null;` +
`       }` +
`   }`

[[building-and-testing]]
= Building and Testing

We build the Toaster Provider and the Service API just like we did in
the previous two chapters. In Chapter 6 top directory, run:

`mvn clean install`

Start the built Karaf distribution:

`> cd distribution-karaf/target/assembly/bin` +
`> ./karaf`

The system will initialize, and the toaster will too! To observe changes
to the karaf log file without having to type *> display* each time, use
the following command:

`> log:tail`

You should see messages similar to the following in the karaf log:

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
2015-01-21 21:03:02,949 | INFO  | config-pusher    | ToasterImplModule                | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | Performing custom validation
2015-01-21 21:03:02,960 | INFO  | config-pusher    | ToasterImplModule                | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | Creating a new Toaster instance
2015-01-21 21:03:02,964 | INFO  | config-pusher    | ToasterImplModule                | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | Provider: org.opendaylight.toaster.ToasterImpl@9d61d65
2015-01-21 21:03:03,045 | INFO  | config-pusher    | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | initToasterOperational: operational status populated: Toaster [_toasterManufacturer=DisplayString [_value=Opendaylight], _toasterModelNumber=DisplayString [_value=Model 1 - Binding Aware], _toasterStatus=Up, augmentation=[]]
2015-01-21 21:03:03,046 | INFO  | config-pusher    | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | initToasterConfiguration: default config populated: Toaster [_darknessFactor=1000, augmentation=[]]
2015-01-21 21:03:03,046 | INFO  | config-pusher    | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | onSessionInitiated: initialization done
2015-01-21 21:03:03,056 | INFO  | CommitFutures-0  | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | initToasterOperational: transaction succeeded
2015-01-21 21:03:03,058 | INFO  | CommitFutures-0  | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | initToasterConfiguration: transaction succeeded
2015-01-21 21:03:03,064 | INFO  | DOM-CFG-DCL-0    | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | onDataChanged - new Toaster config: Toaster{getDarknessFactor=1000, augmentations={}}
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In the log, these are the same messages as in the previous chapter but
included here so that you can see that the system initialized properly.

Try issuing an RPC service request:

`HTTP Method => POST` +
`URL => `http://localhost:8181/restconf/operations/toaster:make-toast[`http://localhost:8181/restconf/operations/toaster:make-toast`]` ` +
`Header =>   Content-Type: application/yang.data+json  ` +
`Body =>  ` +
`{` +
`  "input" :` +
`  {` +
`     "toaster:toasterDoneness" : "10",` +
`     "toaster:toasterToastType":"wheat-bread"` +
`  }` +
`}`

This is the cURL command:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
curl -H 'Content-Type: application/json' -X POST -d '{"input" : {"toaster:toasterDoneness" : "10","toaster:toasterToastType":"wheat-bread"}}' --verbose -u admin:admin http://localhost:8181/restconf/operations/toaster:make-toast
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

You should see the following in the karaf log:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
2015-01-21 23:08:01,626 | INFO  | qtp1747247942-64 | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | makeToast: MakeToastInput [_toasterDoneness=5, _toasterToastType=class org.opendaylight.yang.gen.v1.http.netconfcentral.org.ns.toaster.rev091120.WheatBread, augmentation=[]]
2015-01-21 23:08:01,626 | INFO  | qtp1747247942-64 | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | checkStatusAndMakeToast
2015-01-21 23:08:01,629 | INFO  | qtp1747247942-64 | ToasterImpl                      | 222 - org.opendaylight.toaster.impl - 0.0.1.SNAPSHOT | makeToast returning...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[under-the-hood]]
= Under the Hood
