All students and developers are welcome to participate in the
OpenDaylight Intern Program. Here are the instructions on how to
participate.

[[information-common-to-all-participants]]
== Information common to all participants

For 2015 the OpenDaylight Project has internships available through
three channels:

* https://www.google-melange.com/gsoc/homepage/google/gsoc2015[The
Google Summer of Code]. (Must be code development focused)
* http://gnome.org/opw[Outreach Program For Women] ( Coding, Design,
Documentation projects welcome - Must be female)
*
http://www.opendaylight.org/community/summer-intern-program[OpenDaylight
Project Internships] (Coding, Design, Documentation, Testing projects
welcome)

[[instructions-for-students]]
== Instructions for students

Students wishing to participate in any of the OpenDaylight internships
must realize this is more than a mere formality. You will be required to
finish your work for OpenDaylight in 3 months. You will also take some
resources from OpenDaylight developers, who will dedicate a portion of
their time to mentoring you. Therefore, we'd like to have candidates who
are committed to helping the OpenDaylight Project.

You don't have to be a proven developer -- in fact, this whole program
is meant to facilitate joining the OpenDaylight project and other Open
Source communities. However, experience in coding, Java, and/or
experience with networking concepts is welcome.

You should start familiarizing yourself with the components that you
plan on working on before the start date. OpenDaylight developers are
available on mailing lists and on IRC for help. Note that the timeline
for all three intern programs reserves a lot of time for bonding
periods: use those periods wisely.

[[recommended-steps]]
=== Recommended steps

1.  Read these instructions as well as the specific intern program to
which you will be applying
2.  Take a look at the InternProjects:Main[Intern Projects Page]
3.  Come up with project that you're interested in
4.  Write a first draft link:#Student_proposal_guidelines[proposal] and
get someone to review it for you
5.  Submit it using the specific intern program interface
* For http://www.google-melange.com/gsoc/homepage/google/gsoc2015[GSoC]
* For http://gnome.org/opw[Outreach Program For Women]
* For
http://www.opendaylight.org/community/summer-intern-program[OpenDaylight's
Internship Program]

Coming up with an interesting idea is probably the most difficult part
of all. It should be something interesting for OpenDaylight, for Open
Source in general and Software Defined Networking in particular and for
you. It also has to be something that you can realistically achieve in
the time available to you.

Finding out what the most pressing issues are in the projects you're
interested in is a good start. You can optionally join the mailing lists
for that project or go into its IRC channel: you can make acquaintance
with developers and your potential mentor, as well as start learning the
codebase. We recommend strongly doing that and we will look favorably on
applications from students who have started to act like members of the
OpenDaylight community.

* http://lists.opendaylight.org[OpenDaylight Mailing Lists]
* link:IRC[OpenDaylight IRC Channels]

[[student-proposal-guidelines]]
=== Student proposal guidelines

A project proposal is what you will be judged upon. So, as a general
recommendation, write a clear proposal on what you plan to do, what your
project is and what it is not, etc. Several websites now contain hints
and other useful information on writing up such proposals.

OpenDaylight does not require a specific format or specific list of
information, but here are some specific points that you should address
in your application:

* The project you are proposing.
* Why you’d like to execute on this particular project and the reason
you’re the best individual to do so.
* Details of your academic, industry and/or open source development
experience, as well as other details as you see fit.
* If you have worked on other open source projects, please provide
pointers to the code you worked on / contributed.
* An explanation of your development methodology.
* Your contact information.
* One or two references.
* Regardless of what you include in your proposal, we recommend you
speak to the OpenDaylight project and/or mentor you are applying to
about what they are looking for in a proposal to give you the best
chance of success in your proposal.
* Finally, please also include proof of current academic attendance
(transcript, copy of student ID).

After you have written your proposal, you should get it reviewed. Do not
rely on the OpenDaylight mentors to do it for you: they will only send
back a proposal if they find it lacking. Instead, ask a colleague or a
developer to do it for you.

[[hints]]
=== Hints

*Submit your proposal early*: early submissions get more attention from
developers for the simple fact that they have more time to dedicate to
reading them. The more people see it, the more it'll get known.

*Do not leave it all to the last minute*: Make sure you send your
application before the final rush. Also, note that the applications
submitted very late will get the least attention from mentors, so you
may get a low vote because of that.

*Keep it simple*: we don't need a 10-page essay on the project and on
you. You just need to be concise and precise.

*Know what you are talking about*: the last thing we need is for
students to submit ideas that cannot be accomplished realistically or
ideas that aren't even remotely related to OpenDaylight or SDN. If your
idea is unusual, be sure to explain why you have chosen OpenDaylight as
the best place to do your internship.

*Aim wide*: submit more than one proposal, to different areas of
OpenDaylight. You may also submit your proposal through more than one
intern program.

[[instructions-for-mentors]]
== Instructions for mentors

[[mentoring]]
=== Mentoring

If you're an OpenDaylight developer and you wish to participate as a
Mentor, the easiest is to make a proposal in the
InternProjects:Main[ideas page]. Take a look at what your OpenDaylight
project needs or what you feel OpenDaylight should have. Feel free to
submit ideas even if you cannot elaborate too much on them. However, the
more detail you can provide, the more likely your potential interns will
understand what you are looking for.

Your idea proposal should be a brief description of what the project is,
what the desired goals would be, what the student should know and your
email address for contact. The project ideas page has a template to aid
in the creation of your project idea. Please note, though, that the
students are not required to follow your idea to the letter, so regard
your proposal as just a suggestion.

if you would like to get an idea of what is involved in being a good
mentor, here are some excellent resources:

* http://flossmanuals.net/GSoCMentoring[Google Summer of Code Mentoring
Guide].
*
https://wiki.gnome.org/OutreachProgramForWomen/Admin/InfoForMentors[FOSS
Outreach Program Guide For Mentors]

Finally, know that we will never assign you to a project you do not want
to work on. We will not assign you more projects than you can/want to
take on either. And you will have a backup mentor, just in case
something unforeseen takes place.
