[[welcome-to-the-intern-project-page-for-opendaylight]]
= Welcome to the Intern Project Page for OpenDaylight

This page is meant to connect OpenDaylight Projects and their Mentors
with students interested in working on OpenDaylight.

Please see the InternProjects:Guidelines[Internship Guidelines] page for
additional information.

[[past-intern-programs]]
== Past Intern Programs

* InternProjects:Summer_2014[Summer of 2014]

[[guidelines-for-students]]
== Guidelines for Students

These ideas were contributed by our developers and users. They are
sometimes vague or incomplete. If you wish to submit a proposal based on
these ideas, you may wish to contact the developers and find out more
about the particular suggestion you're looking at.

Being accepted as an OpenDaylight Intern (either through the Google
Summer of Code program or other Internships available) is quite
competitive. Accepted students typically have thoroughly researched the
technologies of their proposed project and have been in frequent contact
with potential mentors. Simply copying and pasting an idea here will not
work. On the other hand, creating a completely new idea without first
consulting potential mentors is unlikely to work out as well.

If there is no specific contact given you can ask questions on the
general OpenDaylight development list dev@lists.opendaylight.org. See
the http://lists.opendaylight.org[OpenDaylight mailing lists page] for
information on available mailing lists and how to subscribe.

[[ideas]]
== Ideas

The following are running ideas for OpenDaylight Projects

[[md-sal-xmpp-jabber-bindings]]
=== MD-SAL XMPP (Jabber) Bindings

* *Title:* MD-SAL http://xmpp.org[XMPP] Bindings
* *Description:* The OpenDaylight controller is based on an MD-SAL
allows the modeling of data, rpcs, and notifications. Because of this
model basis, adding new northbound bindings northbound bindings to the
controller is simple, and everything modeled becomes exposed
automatically. Currently the MD-SAL has restconf NB bindings.
http://xmpp.org[XMPP (Jabber)] is an xml based messaging bus. This
project would involve adding http://xmpp.org[XMPP (Jabber)] bindings to
the MD-SAL, which would automatically make all MD-SAL APIs available via
that mechanism.
* *Additional Information:*
* *Desirable Skills:* Background in Java, Karaf, and XMPP would be
useful.
* *Expected Outcome:* A karaf feature that, when installed, exposed the
MD-SAL datatree, rpcs, and notifications via XMPP (Jabber).
* *Difficultly:* Medium
* *Mentors:* Ed Warnicke
* *Additional Contacts:* IRC: edwarnicke

[[md-sal-amqp-bindings]]
=== MD-SAL AMQP Bindings

* *Title:* MD-SAL http://www.amqp.org[AMQP] Bindings
* *Description:* The OpenDaylight controller is based on an MD-SAL
allows the modeling of data, rpcs, and notifications. Because of this
model basis, adding new northbound bindings northbound bindings to the
controller is simple, and everything modeled becomes exposed
automatically. Currently the MD-SAL has restconf NB bindings.
http://www.amqp.org[AMQP] is a messaging bus. This project would involve
adding http://www.amqp.org[AMQP] bindings to the MD-SAL, which would
automatically make all MD-SAL APIs available via that mechanism.
* *Additional Information:*
* *Desirable Skills:* Background in Java, Karaf, and
http://www.amqp.org[AMQP] would be useful.
* *Expected Outcome:* A karaf feature that, when installed, exposed the
MD-SAL datatree, rpcs, and notifications via AMQP.
* *Difficultly:* Medium
* *Mentors:* Ed Warnicke
* *Additional Contacts:* IRC: edwarnicke

[[improved-odl-meetbot]]
=== Improved ODL Meetbot

* *Title:* Extend the IRC meetbot to better meet ODL needs
* *Description:* Following most of the the other open source projects,
ODL runs many meetings via IRC and uses meetbot to take minutes. There
are several idiosyncrasies of how we use it that make it less effective
than we might like and thus lots of opportunities to Improve it. Some
ideas are:
1.  Add a new command for roll calls (#rollcall) to record who attended
the meetings. This is especially true for IRC meetings.
2.  Add timer support, e.g., for topics that sends warnings about when
we're running over time.
3.  Add a new command to put a #info (and maybe other commands) for the
last topic while we move on to the next topic.
4.  Add support for better tracking of action items across meetings,
also maybe the notion of recurring meetings.
* *Additional Information:* Provide links to bugzilla entries,
release-plan notes, and/or other web-references that would be helpful
information to potential interns.
** http://ci.openstack.org/meetbot.html[OpenStack Meetbot], which is
what we use
** https://wiki.debian.org/MeetBot[Debian Meetbot], which is what
OpenStack Meetbot is based on
* *Desirable Skills:*
** Python programming skills
** Experience with IRC
** Experience with DB tools, e.g., sqlite or others, to persist action
items and track recurring meetings
* *Expected Outcome:* A updated version of the meetbot which has new
commands, e.g., #rollcall, #lasttopic, #topic , etc.
* *Difficultly:* Easy
* *Mentors:* Colin Dixon
* *Additional Contacts:* #opendaylight-meeting, #opendaylight

[[dependency-and-version-tracking-tools]]
=== Dependency and Version Tracking Tools

* *Title:* Dependency and Version Tracking Tools
* *Description:* In OpenDaylight, projects depend on each other and
other third-party projects and depend on different versions of those
parts. Tracking who depends on what and what version and then
visualizing this in a way that helps us track cross-project issues will
be really helpful. This will likely include tasks like:
1.  Produce annotated dependency graphs at the project and bundle level
to understand what project depend on each other and how. Finding cycles,
especially new cycles as they come up, is one key part here.
2.  Track version skew. Understand when different projects or different
bundles are pulling in different versions of the same dependency. We
should be able have a report which says where this skew exists and maybe
even automatically periodically generates warnings for projects that are
lagging.
3.  Nice visualizations of this information (skew and dependency graphs)
would be amazing. Bonus points if we can provide a time slider to see
how things change over time.
* *Additional Information:*
** http://mojo.codehaus.org/versions-maven-plugin/[Maven Versions
Plugin], we've used this with mixed success in the past
* *Desirable Skills:*
** Java skills
** UI (likely web-based) skills to present the information
** Maven and pom file expertise
* *Expected Outcome:* Tools that provide dependency graph and version
skew information. Ideally in a nice web-based user interface.
* *Difficultly:* Medium
* *Mentors:* Colin Dixon
* *Additional Contacts:* Thanh Ha , Ed Warnicke

[[table-type-patterns-utilities]]
=== Table Type Patterns Utilities

* *Title:* Integrate the YANG model for Table Type Patterns with the
OpenFlow Plugin and Applications
* *Description:*
** Basically this project is to help make hardware OpenFlow support in
ODL actually work across different hardware without apps having to be
hard coded. So, you'd be working to make the original hardware OpenFlow
vision possible. For more vision, see
https://www.youtube.com/watch?v=bcaBS6w_k_o[this talk from the first ODL
summit].
** Currently the Table Type Patterns project provides support for
reading, writing and storing JSON- and XML-formatted descriptions of
switch functionality in the
https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/OpenFlow%20Table%20Type%20Patterns%20v1.0.pdf[Open
Networking Foundation's standard]. However, the project doesn't "do
anything" other than allow you to read in a TTP and associate it with a
switch. The next step is to flesh out APIs that make use of these Table
Type Patterns to do useful things. For example, automatic placement of
OpenFlow flows into the right tables based on the TTP and possibly
conversion between TTPs. Other examples are listed in this
https://docs.google.com/a/colindixon.com/document/d/1YwAvznNnU76ETMOpS7Z7b2qPvxExw0Mjnb3o0gqD8DA/edit[API
Sketch document].
* *Additional Information:*
**
https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/OpenFlow%20Table%20Type%20Patterns%20v1.0.pdf[ONF
TTP spec]
**
https://docs.google.com/a/colindixon.com/document/d/1YwAvznNnU76ETMOpS7Z7b2qPvxExw0Mjnb3o0gqD8DA/edit[API
Sketch]
**
https://git.opendaylight.org/gerrit/gitweb?p=ttp.git;a=blob;f=ttp-model/src/main/yang/ttp.yang;hb=HEAD[Current
YANG Model]
** https://www.youtube.com/watch?v=bcaBS6w_k_o[Talk giving some of the
vision]
** https://www.youtube.com/watch?v=3pR14Run9KM[Video Demo of what
currently works]
* *Desirable Skills:* An ideal candidate would have some experience with
these skills. However, ambitious candidates willing to learn will always
be considered.
** Java
** YANG
** OpenFlow
* *Expected Outcome:* Code commits to the the
Table Type Patterns:Main[TTP] and/or DIDM:Main[DIDM] projects providing
tools and APIs for applications to better leverage TTPs.
* *Difficultly:* Medium–Hard
* *Mentors:* Colin Dixon , Curt Beckmann
* *Additional Contacts:*

[[implement-a-secure-engineering-process-for-opendaylight]]
=== Implement a secure engineering process for OpenDaylight

* *Title:* Implement a secure engineering process for OpenDaylight
* *Description:* OpenDaylight has a security response team, able to
coordinate the release of patches for security issues that are
identified in the OpenDaylight code. However, no proactive measures to
minimize the number and extent of security issues in the code are in
place. This project involves implementing initial proactive security
measures for OpenDaylight. The community has already discussed this
problem and a clear plan for establishing a proactive secure engineering
process is available - you just need to execute it. The plan involves
the following key elements:
** Establish automated QE/CI jobs to catch security issues and
regressions. This will involve integrating the findsecbugs tool into
Gerrit/Jenkins.
** Establish automated QE/CI jobs to catch known-vulnerable
dependencies. This will involve integrating tools such as
dependency-check and victims into Gerrit/Jenkins.
** Document a threat model for OpenDaylight
** Improve documentation to capture security best practices at
installation and configuration time
* *Additional Information:*
**
https://wiki.opendaylight.org/images/8/8c/201501-ODL-Bay_Area_Meetup.pdf
**
https://lists.opendaylight.org/pipermail/discuss/2015-January/004172.html
** https://github.com/h3xstream/find-sec-bugs
** https://www.owasp.org/index.php/OWASP_Dependency_Check
** https://victi.ms/
* *Desirable Skills:* Solid Java programming, a background in security,
and an interest in automating security vulnerability detection. If you
have found and reported security issues in open source software this
experience would be highly regarded.
* *Expected Outcome:* It is expected that the key elements of the secure
engineering plan listed in the description section above will be
implemented.
* *Difficultly:* Medium
* *Mentors:* David Jorm , Arun Neelicattu
* *Additional Contacts:* OpenDaylight discuss mailing list

[[release-dashboard-for-opendaylight]]
=== Release Dashboard for Opendaylight

* *Title:* Release Dashboard for Opendaylight
* *Description:* Release dashboard uses RESTful API provided by
Bugzilla, Sonar, JaCoCo to collect dashboard information such as:
opening bugs, how many bugs closed weekly, bugs trend, unit test
coverage, system test status, the purpose is to give a glance of view of
project's quality.
* *Additional Information:*
** http://odlrelease.appspot.com/web/index# as prototype
* *Desirable Skills:* Java or Python programming, Web services, RESTful
experience, GAE and GWT will be desirable.
* *Expected Outcome:* Web service hosted in Linux Foundation and data
get updated in real time
* *Difficultly:* Medium
* *Mentors:* George Zhao , Luis Gomez
* *Additional Contacts:* Opendaylight integtration-dev mailing list.

[[spectrometer]]
=== Spectrometer

* *Title:* Work on Spectrometer project.
* *Description:* Help modify, beautify and generally maintain
Spectrometer. This is a project that is very important to the overall
ODL project as well as member companies in that it gives critical
visibility into who works on what in the project.
* *Additional Information:* This project is largely written in Python,
but also helps you learn Travis CI, integration testing and backend web
as well as the git/fork/commit paradigm.
* *Desirable Skills:* Python is a must.
* *Expected Outcome:* Improved Spectrometer service for ODL, improved
skill set for intern
* *Difficultly:* Medium
* *Mentor:* Thomas D. Nadeau

[[openflow-e2e-performance-test-for-opendaylight]]
=== OpenFlow E2E Performance test for OpenDaylight

* *Title:* Create OpenFlow E2E performance test that runs in CI
* *Description:* We already have some tool [1] to measure OpenDaylight
E2E performance, these scripts can be used to estimate maximum flows can
be programmed per second using Northbound REST interface, making sure
flows are properly installed in Southbound device. We are looking for a
test to run in Continuous Integration (~ 10 mins long) that uses these
scripts to estimate the max flows/sec and stores this value in a CSV
file that can be later plotted by Jenkins. Since no test like this has
been performed in CI in the past I would expect 2 phases in this
project:
** Measurement: Familiarize with perf scripts, measure controller
performance, find issues, file bugs, etc...
** Automation: Create a Jenkins job (JJB template) that runs the
OpenFlow E2E performance test and reports the max flows/sec
* *Additional Information:*
** [1]
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Performance_Tests#RESTCONF_Performance_.26_Scale_Tools_2[Flow
add/remove scripts]
* *Desirable Skills:* Python and shell scripting are a must. OpenFlow
protocol knowledge is desirable.
* *Expected Outcome:* OpenFlow E2E performance test running in
Continuous Integration
* *Difficultly:* Medium
* *Mentor:* Luis Gomez

[[longevity-test-for-opendaylight]]
=== Longevity test for OpenDaylight

* *Title:* Create longevity test for OpenDaylight
* *Description:* Today all our tests run in Continuous Integration which
means they do not take more than ~20 mins to pass. OpenDaylight needs a
test that runs for few hours or days to verify controller stability.
During the test we can try some controlled actions like adding removing
flows [1] but we can also use random events like [2]. Additionally we
should track things like CPU load, memory fill, controller logs, etc...
Since no test like this has been performed in the past I would expect 2
phases in this project:
** Measurement: Measure controller stability, find issues, file bugs,
etc...
** Automation: Program a longevity test that runs for few hours or days
and warns/reports on issues like CPU overload, memory full, logs errors,
flows not being programmed, etc...
* *Additional Information:*
** [1]
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Performance_Tests#RESTCONF_Performance_.26_Scale_Tools_2[Flow
add/remove scripts]
** [2] http://ucb-sts.github.io/sts/[Controller fuzz tool]
* *Desirable Skills:* Python is a must. OpenFlow protocol knowledge is
desirable.
* *Expected Outcome:* Longevity test running on OpenDaylight release
candidates
* *Difficultly:* Medium
* *Mentor:* Jamo Luhrsen Luis Gomez

[[dlux-automation-test-suite-using-selenium-and-robot-framework-for-opendaylight]]
=== DLUX Automation Test Suite Using Selenium and Robot framework for
OpenDaylight

* *Title:* Create Automation for DLUX for OpenDaylight
* *Description:* DLUX is the user interface for the Opendaylight
Controller and the interface for YangUI. DLUX test Automation needs to
be created to verify NETCONF actions originationg from DLUX. Written in
javascript and HTML, Test suites will use the Selenium2Library to
automate UI actions.
* *Desirable Skills:* Selenium, Robot Framework, HTML, Javascript.
knowledge of xpath and css is desirable.
* *Expected Outcome:* Automation test suite exercising the basic NETCONF
actions exposed via YangUI in DLUX.
* *Difficultly:* Medium
* *Mentor:* Carol Sanders

[[gui-support-for-network-overlay-provisioning-and-visualization-of-overlay-views]]
=== GUI Support for Network Overlay Provisioning and Visualization of
Overlay Views

* *Title:* Visualization of Network Overlay Views
* *Description:* OpenDaylight supports network overlay provisioning and
control. A GUI that simplifies provisioning, programming, and
visualization of network overlays in the form of independent views on
the network would help provide tenant-specific views of the network.
* *Additional Information:* Provide links to bugzilla entries,
release-plan notes, and/or other web-references that would be helpful
information to potential interns.
** https://wiki.opendaylight.org/view/OpenDaylight_dlux:Main[DLUX]
**
https://wiki.opendaylight.org/view/OpenDaylight_Lisp_Flow_Mapping:Main[LISP
FLow Mapping]
* *Desirable Skills:*
** Java
** JavaScript
** UI design and implementation skills
* *Expected Outcome:* A GUI based on DLUX for provisioning and
visualization of network overlays in ODL
* *Difficultly:* Medium
* *Mentors:* Lori Jakab , Vina Ermagan

[[jenkins-job-builder---improve-jenkins-plugins-support]]
=== Jenkins Job Builder - Improve Jenkins Plugins support

* *Title:* Enhance JJB support for Jenkins Plugins used by OpenDaylight
* *Description:* OpenDaylight uses Jenkins Job Builder to manage Jenkins
jobs. This project's purpose is to evaluate all plugins used by
OpenDaylight's Releng/Builder are up to date in regards to JJB's support
for them and is able to configure all the options available to those
Jenkins plugins. Evaluate which Jenkins plugins OpenDaylight will most
likely want to use in the future and add support for those plugins to
JJB. Should time permit add support to JJB for additional plugins that
are missing in JJB.
* *Additional Information:*
** http://ci.openstack.org/jenkins-job-builder/
** https://wiki.opendaylight.org/view/RelEng/Builder/Jenkins
* *Desirable Skills:*
** Python
* *Expected Outcome:* JJB support for Jenkins plugins are improved
overall.
* *Difficultly:* Easy
* *Mentors:* Thanh Ha , Andrew Grimberg
* *Additional Contacts:*
** dev@lists.opendaylight.org with topic [releng]
** 1.  opendaylight-releng @ irc.freenode.net
** 1.  openstack-infra @ irc.freenode.net

[[distributed-virtual-router-support-on-opendaylight-ovsdb-project]]
=== Distributed Virtual Router Support on OpenDaylight OVSDB Project

* *Title:* Provide support for Distributed Virtual Router in OVSDB
Opendaylight
* *Description:* OpenStack support legacy centralized routers and
distributed routers. The Opendaylight L3 driver today only supports
legacy routing service and not the distributed one. To be on par with
the OpenStack we need to include support for Distributed Routing. The
current challenge is to make the Distributed Virtual Router to work in
an agentless mode.
* *Additional Information:* Here is the documentation links to the
Openstack DVR implementation and how it works.
**
https://docs.google.com/document/d/1qmKoP4GVdjeEEVvqf3tYptVuvUzVIeQmJiTPWPoi_E0/edit[DVR
UseCase and Configuration guide]
* *Desirable Skills:* Java, Python and OpenFlow with working knowledge
of OpenStack Neutron and the principals behind SDN, Openflow, and
network overlays. Experience with mininet and wireshark will also be
very helpful.
* *Expected Outcome:* May be for the first release we can just target
the "East-West" Intra-Tenant network traffic. - expected.
* *Difficultly:* Medium-Hard
* *Mentors:* Swaminathan Vasudevan
* *Additional Contacts:* #opendaylight-ovsdb, #openstack-neutron. nick:
Swami

[[support-for-external-overlay-mapping-databases]]
=== Support for external Overlay Mapping Databases

* *Title:* Provisioning and use of external LISP mapping System
* *Description:* OpenDaylight currently supports an internal LISP
mapping system. This project enables provisioning and use of an external
mapping system, in cases that different scale or HA requirements demand
an alternative mapping system to the native one in ODL
* *Additional Information:*
**
https://wiki.opendaylight.org/view/OpenDaylight_Lisp_Flow_Mapping:Main[LISP
FLow Mapping]
* *Desirable Skills:*
** Java
** Familiar with overlay technologies
** NoSQL Databases
* *Expected Outcome:* Support in ODL to make use of an external mapping
database to store and retrieve overlay information.
* *Difficultly:* Medium
* *Mentors:* Lori Jakab , Vina Ermagan

[[documenting-core-opendaylight-use-cases]]
=== Documenting core OpenDaylight use-cases

* *Title:* Documenting core OpenDaylight use-cases
* *Description:* OpenDaylight can be used for many things, but there are
a few which are more common than others. We would like to improve the
documentation we provide to users for core use-cases like using
OpenDaylight with IaaS, managing OpenFlow devices with OpenDaylight, and
protecting networks from DDOS.
* *Additional Information:*
** https://wiki.opendaylight.org/view/User:Dneary[1]
* *Desirable Skills:*
** Familiarity with networking
** Good communication skills (written and spoken)
** Ability to find the right person in the community to answer questions
about technology issues
* *Expected Outcome:* A guide for one of the core OpenDaylight
use-cases, including installation and configuration documentation, and a
clear explanation of expected results, and how to diagnose and fix
issues if/when they arise.
* *Difficultly:* Medium
* *Mentors:* Dave Neary

[[developing-an-md-sal-dom-broker-tutorial]]
=== Developing an MD-SAL DOM Broker Tutorial

* *Title:* MD-SAL DOM Broker Tutorial
* *Description:* Develop and document a tutorial that demonstrates the
usage of the MD-SAL DOM Broker. The tutorial will help ODL developers to
use the MD-SAL Binding-Independent infrastructure. The tutorial will
contain code (a mini-app demonstrating DOM Broker APIs), a wiki page and
a YouTube video.
* *Additional Information:*
** Controller_Core_Functionality_Tutorials:Main
* *Desirable Skills:*
** Java coding
** Good communication skills (written and spoken)
** Optional: Python coding
* *Expected Outcome:* A tutorial project in core Tutorials, wiki page
and a video.
* *Difficultly:* Medium
* *Mentors:* Jan Medved

[[developing-an-openflow-tutorial]]
=== Developing an OpenFlow Tutorial

* *Title:* Tutorial: How to Use the OpenFlow Plugin
* *Description:* Develop and document a tutorial that demonstrates the
usage of the OpenFlow Plugin in ODL Java applications. The tutorial will
show ODL developers the use of the OF Plugin APIs, teach them about flow
control and also demonstrate how to design an application for
clustering. The tutorial will consist of code (a mini-app demonstrating
DOM Broker APIs), a wiki page and a YouTube video.
* *Additional Information:*
** Controller_Core_Functionality_Tutorials:Main
* *Desirable Skills:*
** Java coding
** Good communication skills (written and spoken)
** Optional: Python coding
* *Expected Outcome:* A tutorial project in core Tutorials, wiki page
and a video.
* *Difficultly:* Medium to hard
* *Mentors:* Jan Medved

[[templatesample]]
== Template/Sample

* *Title:* Provide a short but descriptive title of what the intern
project is
* *Description:* Provide at least two or three paragraphs describing the
task. Include the problem/opportunity in need of effort, as well as a
description of the task to fix the problem or realize the opportunity.
If there is a probable implementation path... "this will need steps X,
Y, and Z to be completed" please describe it. If part of the task is
evaluating one or more potential implementation paths and
selecting/executing on one of them, please describe the options and the
potential paths to be explored.
* *Additional Information:* Provide links to bugzilla entries,
release-plan notes, and/or other web-references that would be helpful
information to potential interns.
* *Desirable Skills:* List both the skills needed and the tools to be
used. ie. Java programing with working knowledge of OpenStack Neutron
and the principals behind SDN, Openflow, and network overlays.
Experience with mininet and wireshark will also be very helpful.
* *Expected Outcome:* List the deliverable(s)
(features/application(s)/report(s) etc.) expected
* *Difficultly:* Easy/Medium/Hard
* *Mentors:* John Doe , Jane Smith
* *Additional Contacts:* Identify the IRC channel(s) and mailing list(s)
where potential interns can ask questions and further interact with
members of OpenDaylight project they would be working with.

