[[welcome-to-the-intern-project-page-for-opendaylight]]
= Welcome to the Intern Project Page for OpenDaylight

This page is meant to connect OpenDaylight Projects and their Mentors
with students interested in working on OpenDaylight.

[[ideas]]
== Ideas

The following are running ideas for Projects

[[automated-cluster-testing]]
=== Automated Cluster Testing

* *Mentors:* Mathieu Lemay
* *Title:* Enhance current testing automation to add testing of various
multinode cluster configurations.
* *Description:* Working with the integration testing group, write
automated devops test for a variety of different cluster and deployment
configurations (1-N nodes) which includes a variety of
OpenStack+OpenDaylight configurations.
* *Desirable Skills:* Basic knowledge of DevOps tools like Puppet, Chef
or Ansible would be required. Some experience with Vagrant and/or Robot
Framework are welcome.
* *Difficulty:* Easy-Medium

[[tr-069-southbound-protocol]]
=== TR-069 Southbound Protocol

* *Mentors:* Mathieu Lemay
* *Title:* Implement a Southbound TR-069 protocol server used to
initially provision legacy CPE devices
* *Description:* Many DSL or FTTH CPE which are using IP are using
TR-069 for provisioning. Use the TR-069 Southbound will allow to
provision some legacy CPE that are not OpenFlow based.
* *Desirable Skills:* Good knowledge of XML and basic knowledge of
http://fr.wikipedia.org/wiki/TR-069, good knowledge of Java, OSGi and
Maven is a must.
* *Difficultly*: Medium-Hard

[[of-config-support-using-netconf-southbound]]
=== OF Config Support using Netconf Southbound

* *Mentors:* Mathieu Lemay
* *Title:* Implement good provisioning interactions via OF Config as an
alternative for OVSDB in some current scenarios
* *Description:* Working with the LINC, provision logical switches and
proper configuration using OFConfig southbound.
* *Desirable Skills:* Good knowledge of Netconf and XML, Java,, OSGi and
Maven is a must. Must have browsed OF_Config protocol specification.
Linux and Networking skills are recommended.
* *Difficultly*: Medium-Hard

'''Not sure about the state of OF Config support in Hydrogen, please
correct if wrong '''

[[consistencyclustering]]
=== Consistency/Clustering

* *Mentors:* Colin Dixon and Ryan Moats
* *Title:* Enhance OpenDaylight's Consistency/Clustering APIs and
Implementation
* *Description:* Explore options for providing enhanced scale-out,
clustering, and consistency features and implement them. At a high
level, this involves replacing or improving both the Infinispan-based
solution and IClustering contract we currently have.

[[better-host-tracking]]
=== Better Host Tracking

* *Mentors:* Colin Dixon
* *Title:* Create a Better Host Tracker
* *Description:* Improve learning of hosts and their locations to work
from traffic other than ARP. See D-E Proposal:Host Tracker Plan[this
page] for more details.

[[continuous-performance-testing]]
=== Continuous Performance Testing

* *Mentors:* Colin Dixon and Muthukumaran Kothandaraman
* *Title:* Add Test to Provide Continuous Feedback on Performance
* *Description:* See GettingStarted:Performance_Integration_Tests[this
page] for more details.

[[jquery-like-interface-for-md-sal]]
=== jQuery-like Interface for MD-SAL

* *Mentors:* Ryan Moats and Colin Dixon
* *Title:* Add jQuery-like Interface for MD-SAL
* *Description:* At its core, MD-SAL is a DOM generated from YANG
models. As such, an interface that provides jQuery-like features would
support more robust programming and wrapping than raw manipulation of
the underlying DOM.

[[templatesample]]
== Template/Sample

* *Title:* Provide a short but descriptive title of what the project is
* *Description:* Provide at least two or three paragraphs describing the
task. Include the problem/opportunity in need of effort, as well as a
description of the task to fix the problem or realize the opportunity.
If there is a probable implementation path... "this will need steps X,
Y, and Z to be completed" please describe it. If part of the task is
evaluating one or more potential implementation paths and
selecting/executing on one of them, please describe the options and the
potential paths to be explored.
* *Desirable Skills:* List both the skills needed and the tools to be
used. ie. Java programing with working knowledge of OpenStack Neutron
and the principals behind SDN, Openflow, and network overlays.
Experience with mininet and wireshark will also be very helpful.
* *Difficultly:* Easy/Medium/Hard
* *Mentors:* John Doe , Jane Smith

