[[introduction]]
== Introduction

The L2Switch project provides Layer2 switch functionality.

The L2Switch project has the following features/components:

* Packet Handler -- Decodes the packets coming to the controller, and
dispatches them appropriately
* Loop Remover -- Removes loops in the network
* Arp Handler -- Handles the decoded ARP packets
* Address Tracker -- Learns the Addresses (MAC and IP) of entities in
the network
* Host Tracker -- Tracks the locations of hosts in the network
* L2Switch Main -- Installs flows on each switch based on network
traffic

[[new-features-and-enhancements]]
== New Features and Enhancements

Helium is the first release of the L2Switch project; so all features are
new features.

[[deprecated-and-removed-features]]
== Deprecated and Removed Features

Helium is the first release of the L2Switch project; so, there are no
deprecated or removed features.

[[limitations]]
== Limitations

For larger topologies (higher number of switches and hosts), pingall
works when the configuration property of the ArpHandler,
"is-proactive-mode" is set to "true”. (This is the default
configuration.)

[[bugs]]
== Bugs

https://bugs.opendaylight.org/buglist.cgi?bug_status=__open__&list_id=16015&order=relevance%20desc&product=l2switch&query_format=specific

[[helium-stable-update-1]]
== Helium Stable Update 1

No changes have been made since the Helium release.
