[[lacp---integration]]
== LACP - Integration

[[code-name]]
=== Code Name

odl-lacp-plugin

[[description]]
=== Description

LACP Project within Open Daylight implements Link Aggregation Control
Protocol (LACP) as a MD-SAL service module and will be used to
auto-discover and aggregate multiple links between Opendaylight
controlled network and LACP enabled endpoints or switches, which are
external to Opendaylight controller. The result is the creation of
logical channel, which represents the aggregation of the links.Link
aggregation provides link resiliency and also provides bandwidth
aggregation.

https://wiki.opendaylight.org/view/Project_Proposals:Link_Aggregation_Control_Protocol[Overview
& Design Architecture]

*Bundles*

org.opendaylight.lacp

*Upstream Dependencies*

Not Applicable

*Downstream Dependencies*

No downstream dependencies so far.

*Incompatibilities*

No incompatibilities

*Network Intrusiveness*

None

*Recommended Karaf features*

None.There is no external user facing features/API

*Recommended features for karaf testing:*

odl-restconf-all

*How to test*

`'' Test Environment: External switch should be configured with bonded interface in lacp active-mode and long timeout''`

This feature deploys a lacp interface on top of the MD-SAL.

The tests have to include:

* Successful discovery of the topology with aggregation of
multiple-link.
* Verification LAG membership and respective flow table entries .
* Verification of Link failure/removal/resilience scenario.
* Verification of Link addition on existing LAG membership.
* Verification of LAG Port stats/counter .

With the test cases above,current release supports only with LACP
long-timeout and passive mode.

we will confirm that the lacp-aggregate interface conforms to LACP
protocol is released by IEEE Ethernet specification 802.3ad.

*Performance/Scalability Concerns*

Will publish performance/scalability results later
