[[intro]]
= Intro

This page is meant to provide a simple walkthrough of the config
subsystem using the openflowplugin config as the starting point. We
will:

1.  Walk through the openflow config file and what it means
2.  Walk through where the things mentioned in it are defined in
openflowplugin and openflowjava

[[the-openflow-plugin-config-file]]
= The OpenFlow Plugin Config file

openflowplugin has a sub module:
https://git.opendaylight.org/gerrit/gitweb?p=openflowplugin.git;a=tree;f=openflowplugin-controller-config;h=ba923b5683cea5fb4430da9249cf4f9641bbeff0;hb=HEAD[openflowplugin-controller-config].
This module simply is meant to contain the config file for
openflowplugin so that an initial config can be installed easily.

The config file is
https://git.opendaylight.org/gerrit/gitweb?p=openflowplugin.git;a=blob;f=openflowplugin-controller-config/src/main/resources/initial/42-openflowplugin.xml;h=7c9214518103ac371bc041e45c5ab7263b3b03f5;hb=HEAD[42-openflowplugin.xml]

Lets break down the *filename* first. In the controller distribution,
there is a subdir:

configuration/

which contains among other things the config.ini file.

The MD-SAL looks for its initial configuration in

configuration/initial

(when we get to Karaf it will be etc/initial/)

Where there are a list of files with ##-foo.xml that are processed in
the order of the numbers (much like /etc/init.d). So

42-openflowplugin.xml

would be processed after 01-foo.xml, or 41-bar.xml, but before
43-baz.xml or 99-oops.xml.

If you look at 42-openflowplugin.xml it's contents are:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
   2 <!-- vi: set et smarttab sw=4 tabstop=4: -->
   3 <!--
   4 Copyright (c) 2014 Cisco Systems, Inc. and others.  All rights reserved.
   5 
   6 This program and the accompanying materials are made available under the
   7 terms of the Eclipse Public License v1.0 which accompanies this distribution,
   8 and is available at http://www.eclipse.org/legal/epl-v10.html
   9 -->
  10 <snapshot>
  11   <required-capabilities>
  12     <!-- openflowjava -->
  13     <capability>urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl?module=openflow-switch-connection-provider-impl&amp;revision=2014-03-28</capability>
  14     <capability>urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider?module=openflow-switch-connection-provider&amp;revision=2014-03-28</capability>
  15     <!-- openflowplugin -->
  16     <capability>urn:opendaylight:params:xml:ns:yang:openflow:common:config:impl?module=openflow-provider-impl&amp;revision=2014-03-26</capability>
  17     <capability>urn:opendaylight:params:xml:ns:yang:openflow:common:config?module=openflow-provider&amp;revision=2014-03-26</capability>
  18     <!-- binding-broker-impl - provided -->
  19   </required-capabilities>
  20 
  21   <configuration>
  22 
  23     <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  24       <modules xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
  25         <!-- default OF-switch-connection-provider (port 6633) -->
  26         <module>
  27           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl">prefix:openflow-switch-connection-provider-impl</type>
  28           <name>openflow-switch-connection-provider-default-impl</name>
  29           <port>6633</port>
  30           <switch-idle-timeout>15000</switch-idle-timeout>
  31         </module>
  32         <!-- default OF-switch-connection-provider (port 6653) -->
  33         <module>
  34           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl">prefix:openflow-switch-connection-provider-impl</type>
  35           <name>openflow-switch-connection-provider-legacy-impl</name>
  36           <port>6653</port>
  37           <switch-idle-timeout>15000</switch-idle-timeout>
  38         </module>
  39 
  40 
  41         <module>
  42           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:common:config:impl">prefix:openflow-provider-impl</type>
  43           <name>openflow-provider-impl</name>
  44           
  45           <openflow-switch-connection-provider>
  46             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  47             <name>openflow-switch-connection-provider-default</name>
  48           </openflow-switch-connection-provider>
  49           <openflow-switch-connection-provider>
  50             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  51             <name>openflow-switch-connection-provider-legacy</name>
  52           </openflow-switch-connection-provider>
  53 
  54 
  55           <binding-aware-broker>
  56             <type xmlns:binding="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">binding:binding-broker-osgi-registry</type>
  57             <name>binding-osgi-broker</name>
  58           </binding-aware-broker>
  59         </module>
  60       </modules>
  61 
  62       <services xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
  63         <service>
  64           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">prefix:openflow-switch-connection-provider</type>
  65           <instance>
  66             <name>openflow-switch-connection-provider-default</name>
  67             <provider>/modules/module[type='openflow-switch-connection-provider-impl'][name='openflow-switch-connection-provider-default-impl']</provider>
  68           </instance>
  69           <instance>
  70             <name>openflow-switch-connection-provider-legacy</name>
  71             <provider>/modules/module[type='openflow-switch-connection-provider-impl'][name='openflow-switch-connection-provider-legacy-impl']</provider>
  72           </instance>
  73         </service>
  74 
  75         <service>
  76           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:common:config">prefix:openflow-provider</type>
  77           <instance>
  78             <name>openflow-provider</name>
  79             <provider>/modules/module[type='openflow-provider-impl'][name='openflow-provider-impl']</provider>
  80           </instance>
  81         </service>
  82       </services>
  83     </data>
  84 
  85   </configuration>
  86 </snapshot>
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

That's a lot to take in, so lets break it down:

[[section]]
==

 is just a container for this particular config

[[section-1]]
===

 contains a declaration of the capabilities the system must have in
order to apply the config.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  11   <required-capabilities>
  12     <!-- openflowjava -->
  13     <capability>urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl?module=openflow-switch-connection-provider-impl&amp;revision=2014-03-28</capability>
  14     <capability>urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider?module=openflow-switch-connection-provider&amp;revision=2014-03-28</capability>
  15     <!-- openflowplugin -->
  16     <capability>urn:opendaylight:params:xml:ns:yang:openflow:common:config:impl?module=openflow-provider-impl&amp;revision=2014-03-26</capability>
  17     <capability>urn:opendaylight:params:xml:ns:yang:openflow:common:config?module=openflow-provider&amp;revision=2014-03-26</capability>
  18     <!-- binding-broker-impl - provided -->
  19   </required-capabilities>
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[section-2]]
====

Each capability has a declaration:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<capability>urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl?module=openflow-switch-connection-provider-impl&amp;revision=2014-03-28</capability>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Indicates we need to have module
openflow-switch-connection-provider-impl as declared in
urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl
with revision 2014-03-28

So we can see this configuration requires capabilities:

1.  openflow-switch-connection-provider-impl
2.  openflow-switch-connection-provider
3.  openflow-provider-impl
4.  openflow-provider

We'll see later *where* these configs come from, and *why* they have the
urn:'s attached and revisions.

[[and]]
== and

These are just wrappers

[[section-3]]
==

 is a container for the declaration of the modules being configured in
this config file.

[[section-4]]
===

Each module is configured here in a

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
<!-- default OF-switch-connection-provider (port 6633) -->
  26         <module>
  27           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl">prefix:openflow-switch-connection-provider-impl</type>
  28           <name>openflow-switch-connection-provider-default-impl</name>
  29           <port>6633</port>
  30           <switch-idle-timeout>15000</switch-idle-timeout>
  31         </module>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

Lets break down the example above. Its a with attributes:

1.  - the type of the module - openflow-switch-connection-provider-impl
2.  - the name of the module to use for later reference in the config -
openflow-switch-connection-provider-default-impl
3.  - the port number to be configured for this module
4.  - how long before the switch times out - 15000 seconds

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 <!-- default OF-switch-connection-provider (port 6653) -->
  33         <module>
  34           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl">prefix:openflow-switch-connection-provider-impl</type>
  35           <name>openflow-switch-connection-provider-legacy-impl</name>
  36           <port>6653</port>
  37           <switch-idle-timeout>15000</switch-idle-timeout>
  38         </module>
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

The above config is essentially a second module of the same type,
openflow-switch-connection-provider-impl, but with a different
configuration, in this case using port 6653 and a different name -
openflow-switch-connection-provider-legacy-impl

If you wanted to add another openflow-switch-connection-provider-impl on
a different port, you'd add another module with a different name.

So as you can see... we can configure multiple modules of the same type
with different configurations.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
  41         <module>
  42           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:common:config:impl">prefix:openflow-provider-impl</type>
  43           <name>openflow-provider-impl</name>
  44           
  45           <openflow-switch-connection-provider>
  46             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  47             <name>openflow-switch-connection-provider-default</name>
  48           </openflow-switch-connection-provider>
  49           <openflow-switch-connection-provider>
  50             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  51             <name>openflow-switch-connection-provider-legacy</name>
  52           </openflow-switch-connection-provider>
  53 
  54 
  55           <binding-aware-broker>
  56             <type xmlns:binding="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">binding:binding-broker-osgi-registry</type>
  57             <name>binding-osgi-broker</name>
  58           </binding-aware-broker>
  59         </module>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

The above module is more complex and shows more of the power of the
config subsystem. It starts out familiar with

1.  - prefix:openflow-provider-impl
2.  - openflow-provider-impl

but then we have this section

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
  45           <openflow-switch-connection-provider>
  46             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  47             <name>openflow-switch-connection-provider-default</name>
  48           </openflow-switch-connection-provider>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

This section is injecting the openflow-switch-connection-provider with
name openflow-switch-connection-provider-default we had defined above
(the second module we defined) into the openflow-provider-impl.
Basically, its wiring the openflow-provider-impl up with an
openflow-switch-connection-provider that is listening on port 6653.

This is followed by:

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
  49           <openflow-switch-connection-provider>
  50             <type xmlns:ofSwitch="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">ofSwitch:openflow-switch-connection-provider</type>
  51             <name>openflow-switch-connection-provider-legacy</name>
  52           </openflow-switch-connection-provider>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

which is injecting the openflow-switch-connection-provider with name
openflow-switch-connection-provider-legacy we had defined above (the
first module we defined) into the openflow-provider-impl. Basically, its
wiring the openflow-provider-impl up with an
openflow-switch-connection-provider that is listening on port 6633. So
now the openflow-provider-impl has two
openflow-switch-connection-provider, one on port 6653 and one on port
6633. You could just as easily add a module declaration with a name like
openflow-switch-connection-provider-alternate listening on a port 6363
and wire it in as well. You can in fact wire in as many
openflow-switch-connection-providers as you would like.

This is followed by:

------------------------------------------------------------------------------------------------------------------------------------------------
  55           <binding-aware-broker>
  56             <type xmlns:binding="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">binding:binding-broker-osgi-registry</type>
  57             <name>binding-osgi-broker</name>
  58           </binding-aware-broker>
  59         </module>
------------------------------------------------------------------------------------------------------------------------------------------------

This one is a tricky one. You may have noticed we don't define a module
binding-aware-broker anywhere above. It is defined in 01-md-sal.xml. But
at its root this is just injecting a binding-aware-broker into the
openflow-provider-impl module. We will see later how this translates to
java classes.

[[section-5]]
===

Service defines which modules provide which services

---------------------------------------------------------------------------------------------------------------------------------------------------------------
  63        <service>
  64           <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider">prefix:openflow-switch-connection-provider</type>
  65           <instance>
  66             <name>openflow-switch-connection-provider-default</name>
  67             <provider>/modules/module[type='openflow-switch-connection-provider-impl'][name='openflow-switch-connection-provider-default-impl']</provider>
  68           </instance>
  69           <instance>
  70             <name>openflow-switch-connection-provider-legacy</name>
  71             <provider>/modules/module[type='openflow-switch-connection-provider-impl'][name='openflow-switch-connection-provider-legacy-impl']</provider>
  72           </instance>
  73         </service>
---------------------------------------------------------------------------------------------------------------------------------------------------------------

In the above section, we are defining a service of type
openflow-switch-connection-provider as you can see we define two
instances of it, by providing their name and an XPath string to select
their provider.

[[where-does-openflow-provider-come-from]]
== Where does openflow-provider come from?
