Here's how the oDMC went about using MOXy as the JAXB provider:

1.  Include a jaxb.properties file in the same directory as the classes
that need to use MOXy. The contents of the jaxb.properties file is the
following:
+
------------------------------------------------------------------------------
javax.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory
------------------------------------------------------------------------------
2.  Add an override of the getSingleton() method to the Activator class
of the Tomcat servlet. In this override allocate a new MOXyJsonProvider
instance and configure it:
+
______________________________________________________________________________
MOXyJsonProvider moxyJsonProvider = new MOXyJsonProvider(); +
 +
 moxyJsonProvider.setAttributePrefix("@"); +
 moxyJsonProvider.setFormattedOutput(true); +
 moxyJsonProvider.setIncludeRoot(false); // use Annotation +
 moxyJsonProvider.setMarshalEmptyCollections(true); // handle lists
properly +
 moxyJsonProvider.setValueWrapper("$"); +
 +
 Map namespacePrefixMapper = new HashMap(1); +
 namespacePrefixMapper.put("router", "router"); +
 namespacePrefixMapper.put("provider", "provider"); +
 moxyJsonProvider.setNamespacePrefixMapper(namespacePrefixMapper); +
 moxyJsonProvider.setNamespaceSeparator(':'); +
 +
 HashSet set = new HashSet(1); +
 set.add(moxyJsonProvider);
______________________________________________________________________________
3.  For the oDMC, MOXy is dependent on the following artifacts, (YMMV):
* org.eclipse.persistence.core
* org.eclipse.persistence.antlr
* org.eclipse.persistence.moxy

