[cols="^",]
|====================================================================
|*Guide Contents*
|OpenDaylight_Lisp_Flow_Mapping:Architecture[Architecture Overview] +
OpenDaylight_Lisp_Flow_Mapping:Java_API[Java API] +
OpenDaylight_Lisp_Flow_Mapping:REST_API[REST API] +
OpenDaylight_Lisp_Flow_Mapping:Main[Back to LISP Flow Mapping Main]
|====================================================================

[[release-notes]]
== Release Notes

[[major-features]]
=== Major Features

* Proactive Mapping System Pub/Sub: The mapping Service keeps a list of
subscriber xTRs per mapping record (auto-subscribe at mapping request).
When the mapping record is updated via NB API, mapping system sends SMR
message including the updated record to the subscribing xTRs.
* Map Request Non-Proxy Support: The mapping service supports receiving
non-proxy map requests, and forward them to the current xTR.
* Neutron API integration: Improved and expanded Neutron API support in
LISP Flow Mapping. When a new neutron subnet is created, the subnet is
added to mapping system with the Neutron net-ID as the key for the EID
(subnet) prefix.
* LISP SB plugin integration with Node Inventory and GUI: Enables status
integration of LISP dateplane nodes in AD-SAL node inventory and AD-SAL
GUI. Not included in Karaf.
* Integration with Service Function Chaining: The mapping Service
supports integration with Service Function Chaining.
* Port support for non proxy map request
* Key-value LCAF support
* Map-Reply in Map Request serialization. we now serialize the embedded
map reply record.
* Southbound xTR support. The southbound can now listen on another port
which is the xTR port, and send a notification with the received map
request.
* Adding another address format: a DistinguishedName with value ":"

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

* Languages used: Java
* Required: JRE

[[for-development]]
==== For Development

* JDK
* Maven

[[known-issues-and-limitations]]
=== Known Issues and Limitations

* LISP LCAFs are limited to only up to one level of recursion. For
instance in the case of a traffic engineering policy every hop can only
be a basic address (IPv4, IPv6, MAC, Dist. Name, AS Number), and can not
include combinations such as Segment ID, or list.
* Mappings are expired after 4 minutes from registration. Later versions
may provide support for overwriting or removing mappings as well as
differentiating between registrations from northbound vs southbound with
priority to allow for append/overwrite option.
* Testing methodology
** All modules have been unit tested. Integration tests have been
performed for all major features.
** Registering and retrieval of basic mappings have been tested more
thoroughly. More complicated mapping policies have gone through less
testing. Registering mappings via Northbound API with LCAF AFIs have not
been tested.

[[bugs-fixed-in-this-release]]
== Bugs Fixed in this Release

* The REST API has been improved with minor bug fixes.

[[compatibility-with-previous-releases]]
== Compatibility with Previous Releases

Compatible with Hydrogen release.
