[[current-tests]]
== CURRENT TESTS

[[mapregister]]
=== MapRegister

Send a MapRegister to the mapping service, wait for the MapNotify, and
check it is correct.

[[mapregister-and-maprequest]]
=== MapRegister and MapRequest

Send a MapRegister to the mapping service, wait for the MapNotify , and
check it is correct, and then send a MapRequest with the EID which was
registered and wait for the MapReply, and check that we got The RLOC we
registered.

[[maprequest-before-mapregister]]
=== MapRequest before MapRegister

Send a MapRequest, make sure that the MapReply has no RLOCs, send a
MapRegister for that EID, send the MapRequest again and make sure that
this time the MapReply contains the RLOC we registerd.

[[to-do]]
== TO DO

[[eid-prefix-lookups]]
=== EID prefix lookups

Register EIDs with different masks, and check that requests return
prefix matches.

[[password-prefix-configurations]]
=== Password prefix configurations

Configure different passwords for different prefixes, and make sure that
registers work only with their right password.

[[map-register-and-map-request-northbound]]
=== Map Register and Map Request northbound

Add a mapping using the northbound interface, retrieve that mapping
using the northbound interface, check that both mappings are equal.

[[map-register-northbound-and-map-request-southbound]]
=== Map Register northbound and Map Request southbound

Add a mapping using the northbound interface, send a Map Request to the
southbound and get the Map Reply, check that both mappings are equal.

[[map-register-southbound-and-map-request-northbound]]
=== Map Register southbound and Map Request northbound

Send a Map Register over the southbound interface, retrieve the mapping
using the northbound interface, check that both mappings are equal.

[[authentication-key-via-northbound-and-map-register-southbound]]
=== Authentication key via northbound and Map Register southbound

Add an authentication key (a password for a prefix) using the northbound
interface, send a Map Register over the southbound interface
authenticated with that key, check that the mapping is correctly stored.

Category:LISP Flow Mapping[Category:LISP Flow Mapping]
