[cols="^",]
|=======================================================================
|*Guide Contents*

|OpenDaylight_Lisp_Flow_Mapping:Architecture[Architecture Overview] +
OpenDaylight_Lisp_Flow_Mapping:Java_API[Java API] +
OpenDaylight_Lisp_Flow_Mapping:REST_API[REST API] +
OpenDaylight_Lisp_Flow_Mapping:SimultaneousReleasePlan2014[Helium
Release Plan] +
OpenDaylight_Lisp_Flow_Mapping:ReleasePlan2013_Detailed[Detailed Release
Plan (2013)] +
OpenDaylight_Lisp_Flow_Mapping:Hacking_Code_From_CLI[Hacking the Code
From CLI] +
OpenDaylight_Lisp_Flow_Mapping:Main[Back to LISP Flow Mapping Main]
|=======================================================================

This is a scratch page for future features and to do items.

To Do/Discuss Features:

[[in-progress-or-completed]]
== In Progress or Completed

* Delete Mappings: design and implement and NB API to delete mapping
feature per EID prefix. Options: default to overwrite with inclusion of
merge bit to add instead of overwrite, or use TTL = 0 to delete.
** So far, default to overwrite is enabled. Merge bit is not
implemented.
* SMR: Options: Feature and NB API to SMR a particular network (EID
prefix) with new mappings of a specific EID,
** Completed. add mapping from NB API will send an SMR to all subscribed
xTRs for the associated prefix, only if there is a change in the
mapping.

[[not-started]]
== Not Started

* Enable integration of LISP SB plugin with GUI and node database
* Associate key with Instance ID as well as EID
* Differentiate mappings installed from NB vs SB: The delete feature
with merge bit may be able to handle this case as well
* Store flows: This requires design or adoption of a flow LCAF

