__TOC__

[[overview]]
== Overview

Weekly meeting for the Persistence:Main[Persistence Store Service]
project.

Check Persistence:Weekly_Meeting#Canceled_Meetings[Canceled Meetings]
section for canceled meetings.

[[information]]
== Information

* Time: 9am-10am PST
* Date: Every Wednesday January 21, 2014 to no end date
* Topic: ODL - Weekly Persistence Project Meeting

*
https://meetings.webex.com/collabs/meetings/join?uuid=MALH0BTM0WALT9F31XVSIM8F4C-9VIB[Webex
meeting link]
* Meeting Number: 190 169 316
* Meeting Password: This meeting does not require a password
* Host(s): Fabiel Zuniga (fabiel.zuniga@hp.com)

* 1-855-244-8681 Call-in toll-free number (US/Canada)
* 1-650-479-3207 Call-in toll number (US/Canada)
* Access code: 190 169 316

* IRC: Freenode/#opendaylight-persistence
* http://webchat.freenode.net/?channels=opendaylight-persistence

[[regular-agenda]]
== Regular Agenda

* Status Update
* Suggested Topics
*
https://git.opendaylight.org/gerrit/#/q/status:open+project:persistence[Open
Reviews]
*
https://bugs.opendaylight.org/buglist.cgi?bug_status=__open__&order=Importance&product=persistence&query_format=specific[Open
Bugs]
* Questions

[[suggested-topics]]
== Suggested Topics

Modify this section to suggest topics for the next meeting or send an
e-mail to any of the Persistence:Main[Persistence Committers].

* JPA implementation Review
*

[[questions]]
== Questions

Modify this section to add questions to address in the next meeting or
send an e-mail to any of the Persistence:Main[Persistence Committers].

*

[[weekly-status-meeting-notes]]
== Weekly Status (Meeting Notes)

[[canceled-meetings]]
=== Canceled Meetings

[cols=",",options="header",]
|====================================================================
|Date |Reason
|01/28/2015 |One time conflict with an internal OpenDaylight training
|02/25/2015 |One of the presenters got an unexpected matter to attend
|03/11/2015 |Internal OpenDaylight training for new members
|03/18/2015 |Internal OpenDaylight training for new members
|====================================================================

[[lithium]]
=== Lithium

[[lithium-release-plan-review]]
==== 01/21/2015: Lithium Release Plan Review

*Agenda*

* Status Update
* Suggested Topics:
** Lithium Release Plan Review
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-01-21-17.04.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-01-21-17.04.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-01-21-17.04.log.html[Log]

*Resources*

*
https://meetings.webex.com/collabs/url/LVPWjgqxLvwIBccUoQLs_Cqvz9A1raV8grP07UKr8Fy00000[Webex
Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I0D8COAEZ3WVIBXJLPFVB9TLR2-9VIB[Meeting
Space (Only for registered users)]

[[backlog-review]]
==== 02/04/2015: Backlog Review

*Agenda*

* Status Update
* Suggested Topics:
** Backlog Review
** Identification of tasks and priorities for milestones in Lithium
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-04-17.05.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-04-17.05.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-04-17.05.log.html[Log]

*Resources*

*
https://meetings.webex.com/collabs/url/3t5pK8hRD4VSfD5g6VyzauFouC2TOwuqYw_XcSJ7pDW00000[Webex
Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I1R74JHY9QKLX1NCJVN22NR7N0-9VIB[Meeting
Space (Only for registered users)]

[[persistence-api-review-dao-api]]
==== 02/11/2015: Persistence API Review (DAO API)

*Agenda*

* Status Update
* Suggested Topics:
** Persistence API Review
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-11-17.05.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-11-17.05.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-02-11-17.05.log.html[Log]

*Resources*

* [ Webex Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I1WH8L3ZDPOZ5OS98M0TUUH0I4-9VIB[Meeting
Space (Only for registered users)]

[[reusable-queries-review]]
==== 02/18/2015: Reusable Queries Review

*Agenda*

* Status Update
* Suggested Topics:
** Reusable Queries Review
** DAO example Review (Partial review of a JPA-based DAO
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_2_18_2015/opendaylight-persistence-persistence_weekly_meeting_2_18_2015.2015-02-18-17.05.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_2_18_2015/opendaylight-persistence-persistence_weekly_meeting_2_18_2015.2015-02-18-17.05.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_2_18_2015/opendaylight-persistence-persistence_weekly_meeting_2_18_2015.2015-02-18-17.05.log.html[Log]

*Resources*

* [ Webex Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I1Z4CQ7FBQMMB16OB1UDSG9414-9VIB[Meeting
Space (Only for registered users)]

[[system-test-plan-and-object-store-api-review]]
==== 03/04/2015: System Test Plan and Object Store API Review

*Agenda*

* Suggested Topics:
** System Test Plan review
** Object Store API review
** Test application review
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-03-04-17.04.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-03-04-17.04.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting/opendaylight-persistence-persistence_weekly_meeting.2015-03-04-17.04.log.html[Log]

*Resources*

* [ Webex Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I24E5LQ6962YAYVSFNA3D8OSV7-9VIB[Meeting
Space (Only for registered users)]

[[persistence-weekly-meeting-process-overview]]
==== 03/25/2015: Persistence Weekly Meeting Process Overview

*Agenda*

* Meeting Process Overview
* Questions

*Minutes*

*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_process_overview/opendaylight-persistence-persistence_weekly_meeting_process_overview.2015-03-25-16.29.html[Minutes]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_process_overview/opendaylight-persistence-persistence_weekly_meeting_process_overview.2015-03-25-16.29.txt[Minutes
(text)]
*
http://meetings.opendaylight.org/opendaylight-persistence/2015/persistence_weekly_meeting_process_overview/opendaylight-persistence-persistence_weekly_meeting_process_overview.2015-03-25-16.29.log.html[Log]

*Resources*

* [ Webex Recording]
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I2715NOK2D1QD534ZV147W5SGA-9VIB[Meeting
Space (Only for registered users)]

[[templates]]
=== Templates

[[section]]
==== :

*Agenda*

* Status Update
* Suggested Topics:
**
* Questions

*Minutes*

* [ Minutes]
* [ Minutes (text)]
* [ Log]

*Resources*

* [ Webex Recording]
* [ Meeting Space (Only for registered users)]

[[section-1]]
==== :

*Agenda*

*

*Minutes*

*

*Action Items*

*

*Resources*

*
*

