[[description]]
= Description

This page describes the various configurable paramaters in VTN
Coordinator.

[[assumptions]]
= Assumptions

VTN Coordinator installation has been done from
OpenDaylight Virtual Tenant Network (VTN):Installation:VTN Coordinator[source]
or from
OpenDaylight Virtual Tenant Network (VTN):Installation:Virtualization Edition[Virtualization
Edition].

[[configurable-paramaters]]
= Configurable Paramaters

[[read_interval-for-physical-attributes]]
== read_interval for physical attributes

`   When a ODL Controller is added as controller to VTN Coordinator,` +
`   the latter will collect the physical network details from ODL on a timely basis.` +
`   This paramter will determine the frequency of this operation.`

File: /usr/local/vtn/modules/vtndrvintf.conf +
parameter: physical_attributes_read_interval +
Default: 40 seconds::

[[ping_interval]]
== ping_interval

`  When a ODL controller is added to VTN Coordinator,` +
`  the latter will try to retrieve version of the ODL controller on a timely basis` +
`  to ensure that the controller can accept configuration requests.`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: odcdrv_ping_interval +
Default value: 30 seconds::

[[odl-port]]
== ODL Port

`  The Port number in whichthe ODL can accpet requests`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: odc_port +
Default value: 8080::

[[odl-connect-timeout]]
== ODL connect timeout

` The upper limit of the time that VTN Coordinator will wait for ODL to accept the connection.`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: connect_time_out +
Default value: 30 seconds::

[[odl-request-time-out]]
== ODL Request Time Out

`  The upper limit of the time that VTN Coordinator will wait for ODL to respond to a request.`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: request_time_out +
Default value: 30 seconds::

[[odl-username]]
== ODL username

` The username to send any request to ODL`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: username +
Default value: admin::

[[odl-password]]
== ODL Password

` The password to send any request to ODL`

File: /usr/local/vtn/modules/odcdriver.conf +
Parameter: password +
Default value: admin::

