[[how-to-install-vtn-coordinator]]
== How to install VTN Coordinator?

*
OpenDaylight Virtual Tenant Network (VTN):Installation:VTN Coordinator[Install
coordinator from source]

[[after-executing-db_setup-you-have-encountered-the-error-failed-to-setup-database]]
== After executing db_setup, you have encountered the error "Failed to
setup database"?

The error could be due to the below reasons

* Access Restriction

` The user who owns /usr/local/vtn/ directory and installs VTN coordinator, can only start db_setup.` +
` Example : ` +
` The directory should appear as below (assuming the user as "vtn"):` +
` # ls -l /usr/local/` +
`   drwxr-xr-x. 12 vtn  vtn  4096 Mar 14 21:53 vtn` +
` If the user doesnot own /usr/local/vtn/ then, please run the below command (assuming the username as vtn),` +
`                chown -R vtn:vtn /usr/local/vtn`

* Postgres not Present

` 1.In case of Fedora/CentOS/RHEL, please check if /usr/pgsql/`` directory is present and also ensure the commands ` +
`   initdb, createdb,pg_ctl,psql are working. If, not please re-install postgres packages`

` 2.In case of Ubuntu, check if /usr/lib/postgres/`` directory is present and check for ` +
`   the commands as in the previous step.`

* Not enough space to create tables

`Please check df -k and ensure enough free space is available.` +
`     `

* If the above steps do not solve the problem, please refer to the log
file for the exact problem

`     /usr/local/vtn/var/dbm/unc_setup_db.log for the exact error.`

[[what-are-the-things-to-check-after-vtn_start]]
== What are the things to check after vtn_start?

* list of coordinator processes
* Run the below command ensure the Coordinator daemons are running.

`    Command:   /usr/local/vtn/bin/unc_dmctl status` +
`               Name         Type      IPC Channel      PID` +
`       -------------------- ------------ ---------------- --------` +
`            drvodcd       DRIVER          drvodcd    15972` +
`             lgcnwd      LOGICAL           lgcnwd    16010` +
`             phynwd     PHYSICAL           phynwd    15996`

* Issue the curl command to fetch version and ensure the process is able
to respond.

[[how-to-debug-a-startup-failure]]
== How to debug a startup failure?

The following activities take place in order during startup

* Database server is started after setting virtual memory to required
value

`    Any database startup errors will be reflected in any of the below logs` +
`   /usr/local/vtn/var/dbm/unc_db_script.log.` +
`   /usr/local/vtn/var/db/pg_log/postgresql-*.log (the pattern will have the date)`

* uncd daemon is kicked off, The daemon in turn kicks off the rest of
the daemons.

`    Any  uncd startup failures will be reflected in /usr/local/vtn/var/uncd/uncd_start.err.` +
`    please refer to the file for any errors.`

[[after-setting-up-the-apache-tomcat-server-what-are-the-aspects-that-should-be-checked.]]
== After setting up the apache tomcat server, what are the aspects that
should be checked.

`    Please check if catalina is running.`

`    The command ps -ef | grep catalina | grep -v grep should list a catalina process`

[[if-you-encounter-an-erroneous-situation-where-the-rest-api-is-always-failing.]]
== If you encounter an erroneous situation where the REST API is always
failing.

`   Please ensure the firewall settings for port:8080(Helium release) or port:8083(Post Helium release) and enable the same.`

[[how-to-debug-a-rest-api-returning-a-failure-message]]
== How to debug a REST API returning a failure message?

`  Please check the /usr/local/vtn/var/tomcat/log/core/core.log for failure details.`

[[rest-api-for-vtn-configuration-fails-how-to-debug]]
== REST API for VTN configuration fails, how to debug?

The default log level for all daemons is "INFO", to debug the situation
TRACE or DEBUG logs may be needed. To increase the log level for
individual daemons, please use the commands suggested below

`  /usr/local/vtn/bin/lgcnw_control loglevel trace -- upll daemon log ` +
`  /usr/local/vtn/bin/phynw_control loglevel trace -- uppl daemon log ` +
`  /usr/local/vtn/bin/unc_control loglevel trace -- uncd daemon log ` +
`  /usr/local/vtn/bin/drvodc_control loglevel trace -- Driver daemon log `

After setting the log levels, the operation can be repeated and the log
files can be referred for debugging.

[[problems-while-installing-postgresql-due-to-openssl]]
== Problems while Installing PostgreSQL due to openssl

Errors may occur when trying to install postgreSQL rpms. Recently
PostgreSQL has upgraded all their binaries to use the latest openssl
versions with fix for http://en.wikipedia.org/wiki/Heartbleed[heartbleed
bug]. Please upgrade the openssl package to the latest version and
re-install.

For RHEL 6.1/6.4 : If you have subscription, Please use the same and
update the rpms. The details are available in this
link:https://access.redhat.com/site/solutions/781793[ACCESS-REDHAT].

If you do not have subscription, Please use the Cent OS 6 yum
respository and update the openssl package.
http://mirrors.kernel.org/centos/6/os/x86_64/Packages[CentOS6]

`  rpm -Uvh `http://mirrors.kernel.org/centos/6/os/x86_64/Packages/openssl-1.0.1e-15.el6.x86_64.rpm[`http://mirrors.kernel.org/centos/6/os/x86_64/Packages/openssl-1.0.1e-15.el6.x86_64.rpm`] +
`  rpm -ivh `http://mirrors.kernel.org/centos/6/os/x86_64/Packages/openssl-devel-1.0.1e-15.el6.x86_64.rpm[`http://mirrors.kernel.org/centos/6/os/x86_64/Packages/openssl-devel-1.0.1e-15.el6.x86_64.rpm`]` `

For other linux platforms, Please do yum update, the public respositroes
will have the latest openssl, please install the same. +
 *Note*: VTN Coordinator support postgres version greater than 9.1 only
and currently tested with 9.1 and 9.3. Please ensure the postgres
version >=9.1 is installed.

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
