[[amazing-hackers-velocity-quality]]
== "Amazing hackers, velocity, quality"

"OpenDaylight is filled with amazing hackers, achieves amazing velocity,
and when a project is well managed, produces amazing quality". This was
the reaction when I asked Tom Nadeau, Chief Architect for Open Source at
Brocade, why they had chosen OpenDaylight as the basis for their Vyatta
SDN controller product.

Compared to the traditional standards approach which has been dominant
in the networking industry for decades, open source has completely
changed the dynamic - "by creating reference implementations which
result in de facto standards, open source development is making
traditional standardization efforts look slow and outdated". In the open
source community, pragmatism reigns: an early motto of IETF, "rough
consensus and running code", has been taken to heart by the project.

[[first-commercial-distribution-of-opendaylight]]
== First commercial distribution of OpenDaylight

Brocade Vyatta Controller, part of Brocade's Vyatta suite of networking
products, is, according to Nadeau, the first general-purpose commercial
distribution of "vanilla" OpenDaylight. The company takes the code
released by the community, and releases tested, hardened versions of
stable projects to customers with documentation and support. The only
changes which are added to the product are bug fixes, some experimental
projects and applications, and a branded UI. All changes then find their
way back “upstream” to OpenDaylight.

Customers can also get early access to future releases of the project
through the Brocade Developer Network, encouraging ISV partners and
customers to build on top of the platform early.

The team has been working on OpenDaylight since the creation of the
project, and has been ramping up their involvement over the last year.
Their top priority today is helping mature the upstream project and
stabilising what will become the Lithium release. Tom and his team are
active in multiple projects, including important shared tasks like
testing, integration and participation in the management structures of
the project, the board of directors and the TSC. In the past two release
cycles, they have done a lot of work on the core Model Driven service
abstraction layer (MD-SAL) to stabilise the core of the controller and
enable all OpenDaylight projects to adopt MD-SAL as their standard
architecture, and on the OpenFlow and OVSDB south-bound projects.

[[choosing-opendaylight]]
== Choosing OpenDaylight

As a founding member of the project, Brocade decided to engage very
early with OpenDaylight. The main reason was that sharing the effort on
a common base controller just made sense. "The world didn't need another
proprietary SDN controller", says Tom. The goal was to share the heavy
lifting of building a core platform, to enable innovation to happen on
top of the common base.

OpenDaylight is an open, participative community, with no one dominant
vendor. Individuals are not required to pay a membership fee to
participate, and "code is the coin of the realm" (or, as Tom paraphrased
it, "community-based, supported and developed code is the coin of the
realm") is a motto which is held dear. The project was designed from the
start to provide a solid core which would support multiple southbound
and northbound protocols - this enables everyone to work on what they
care about, without needing the permission of others who are potentially
competitors in the market, but who have a shared interest in providing a
solid, scalable model-driven abstraction for application development.

OpenDaylight is also important on a personal level to Tom. He started
working on OpenDaylight while still working for another founding member,
Juniper, and it was his first open source experience. The project has
affected him profoundly. He is an open source convert, and his passion
for community software development was obvious.

[[looking-forward]]
== Looking forward

What's next for OpenDaylight? "The project is maturing", says Tom.
Recently, the project's leadership has started an initiative to focus on
core projects and a small number of key use-cases, and to aggressively
pursue stability and functionality to satisfy those use-cases. The
result should allow the project to have a very strong position in the
coming years.

The project is constantly tweaking community processes and workflows for
the better. Continual improvement is a core value of OpenDaylight, and
each release has built on the lessons learned from previous efforts. The
ability to evaluate what is working and what is not, and to modify
processes as a community, is one of the strengths of the project,
according to Tom. "We have refined the way we behave", and the project
is getting better because of it.

Category:Case studies[Category:Case studies]
