[[user-and-community-case-studies]]
== User and community case studies

OpenDaylight has a growing community of people building on the
OpenDaylight platform and using the project for their network
virtualization needs. This page is a landing page for collecting those
stories of people building OpenDaylight based products and applications,
and deploying OpenDaylight in production.

* link:University of Luxembourg[University of Luxembourg] - The
Interdisciplinary Centre for Security, Reliability and Trust at the
University of Luxembourg uses OpenDaylight as a basis for multiple
research projects related to attack detection and network
troubleshooting.
* link:Cornell University[Cornell University] - Gates Hall in Cornell
has been successfully running a 100% OpenFlow network with OpenDaylight
since mid 2014.
* link:Packet Design[Packet Design] - Packet Design is using
OpenDaylight as part of their network traffic engineering product.
* link:Brocade Vyatta Controller[Brocade Vyatta Controller] - Brocade
Vyatta Controller is an OpenDaylight based SDN controller. Well known
OpenDaylight community member Tom Nadeau talked to us about how Brocade
builds a product on OpenDaylight?

Category:Case_studies
