[[what]]
== What

All current committers to the OpenDaylight Project are invited to join
the OpenDaylight non-profit organization as an Individual Committer
Member. The Individual Committer Members are a class of membership
within the OpenDaylight non-profit organization. In order to join the
OpenDaylight non-profit organization as an Individual Committer Member,
each Committer must fill out, and accept the
https://linuxfoundation.echosign.com/public/hostedForm?formid=AI3XA256U2H44Y[Committer
Member Application Form]

Two representatives of the OpenDaylight Individual Committer membership
class are elected to serve on the OpenDaylight Board Of Directors. There
are no term limits, an Individual Committer Member may stand for
election as often as desired. The role of the Individual Committer Board
members is to represent the over-all Individual Committer membership
class on the OpenDaylight Board of Directors.

[[who]]
== Who

This election and nomination process is limited to those individuals who
are members of the Individual Committer Membership Class of the
OpenDaylight non-profit organization. Any such member can nominate
themselves, and vote in the election for the Individual Committer Member
seats on the Board of Directors.

[[how]]
== How

The election process occurs in three phases; the Nomination phase, the
Nomination Review phase, and the Election phase.

[[nomination-phase]]
=== Nomination Phase

1.  An email is sent from the Election Coordinator (Phil Robb) to the
Individual-Committer-Members distribution list for OpenDaylight and the
subject line is tagged with the keywords [INDIVIDUAL COMMITTER MEMBER
BOARD OF DIRECTORS NOMINATION].
2.  Any Individual Committer Member may nominate themselves to stand for
election. Note that individuals cannot nominate another to run for
election. If an Individual Committer Member wants another individual to
run, they should express their support to that individual and suggest
that the other Individual Committer Member run for election.
3.  To submit a nomination, the Individual Committer Member must
reply-all to the original nomination email stating their interest to
stand for the election.
4.  The length of the Nomination phase is approximately 14 days. This
clock starts when the email described above is sent.

[[nomination-review-phase]]
=== Nomination Review Phase

Participating in the OpenDaylight non-profit organization as a member of
the Board is an activity that is above and beyond the work done by
committers within the OpenDaylight Open Source Community. Each member of
the Board has an obligation to lead the organization in a manner that is
consistent with the By-Laws. In addition, certain protections are made
available to members of the Board such as "Director and Officer" (D&O)
insurance.

* In order to ensure a cohesive and well-functioning Board of Directors
a Nomination Committee will review each Individual Committer Member
nominee (Media: Committer_Director_Criteria_10-31-14.pdf[Board Member
Criteria])
* The Nomination Committee will be comprised of the Executive Director,
and at least three current Board members.
* All nominees that are approved by the Nomination Committee will
proceed to the Election Phase of the process.
* The length of the Nomination Review phase is approximately 14 days.
This clock starts once the Nomination phase has concluded.

[[election-phase]]
=== Election Phase

1.  All Election Phase candidates are invited to publish their Picture,
Biography, and Statement of Intent on the election wiki page so that all
of the Individual Committer Members can learn more about the candidate
and their intentions for the role of Individual Committer Member Board
representative. The nominee ordering on the election wiki page will be
in ascending alphabetical order by last name.
2.  Immediately upon the close of the Nomination Review Phase, an email
will be sent from the Election Coordinator (Phil Robb) via the Condorcet
Internet Voting Service (CIVS) to each committer within OpenDaylight.
This email will have the subject line: “Poll: OpenDaylight Individual
Committer Member Board Of Directors Election”. This email acts as an
invitation by the CIVS for each committer to vote. This voting
invitation is only sent to the Individual Committer Members. Included in
this election invitation will be a pointer to the Election wiki page
which contains the names, pictures, biographies, and
statements-of-intent for each of the candidates. The email also has
instructions and a private URL where each Individual Committer Member is
sent to vote.
3.  At the CIVS-provided voting URL, each voter will rank the
candidates, where a smaller-numbered rank means that the voter prefers
that choice more. Once the ranking is complete, the voter will press the
“Submit ranking” button to complete the voting process.
4.  The Election Phase will remain open for approximately 14 days from
the time the invitation-to-vote email is sent by the CIVS.
5.  Once the Election Phase has completed, the results of the election
will be reviewed by the Election Coordinator, the OpenDaylight Executive
Director, and the Chairman of the OpenDaylight Board. The top two,
best-ranked individuals that come from separate, unaffiliated companies
will be designated as the winners of the election.
6.  Immediately after the Election Review, an email will be sent by the
Election Coordinator to the Individual-Committer-Members mailing list
indicating the winners of the election.

