[[overview]]
= Overview

This page provides information on how to run an election to choose your
Project's Leader (a.k.a. Project Technical Leader a.k.a. PTL). These are
guidelines intended to be helpful in running first-time project
elections. This is not a set of mandates.

[[step-1-self-nomination]]
= Step 1: Self Nomination

* Begin the voting process by soliciting all of the active committers to
self nominate if they would like to stand for the position of PTL. This
call-for-nominees should be sent to the $\{Project}-dev list. Helpful
information to include in this email :
** Subject: OpenDaylight $\{Project} - PTL Call For Nominations
** Duration of the Nomination Phase
** Duration of the Election/voting Phase
** How to Self Nominate - ie reply-all to this email
** Nominees must be committers on the project
* To self nominate, a candidate will need to reply-all with their
indication to stand for election
* Optionally, the nominees can either send their Biographies and a
Statment-of-Intent (for what they want to accomplish as the Project's
PTL) to the $\{Project}-dev list, or they may create a wiki page to hold
such information.
* The Self Nomination period should be at least one week in duration.

[[step-2-running-a-condorcet-internet-voting-system-civs-electronic-election]]
= Step 2: Running a Condorcet Internet Voting System (CIVS) electronic
election

1.  Go to the http://civs.cs.cornell.edu[Condorcet Internet Voting
System website]
2.  Select “Create a poll”
3.  Enter the Name of the poll (eg “$\{Project} PTL Election”)
4.  For “Name of Supervisor”, put your name
5.  For “E-mail address of supervisor”, put your email address
6.  For “Day and time you plan to stop your poll”, provide a day of the
week, date, and time (preferably midnight UTC/4:00pm PT) as we often use
that as an ending time
* E.g. “Wednesday, December 10th, 2014 at Midnight UTC/4:00pm PT
* The election should run for at least one week and not longer than two
weeks.
7.  For “Description of poll and available choices” enter a brief
description of the election.
* E.g. “This election is to choose a Project Technical Leader for the
Controller project within OpenDaylight for the next 12 months (until
December 9th, 2015). Please rank each of the candidates where a lower
number indicates that you prefer that candidate more.
8.  For the “Enter the names of all the choices (candidates) one per
line…” do just that.
9.  For entering email addresses, you have two choices. You can either
enter email addresses on the web form, 1 email address per line, or you
can provide a file that has email addresses one per line. ** Please
note, in my experience, any addition text other than the actual email
address (ie descriptive name/text) will cause the input of those email
addresses to fail.
10. For options I recommend the following:
* Make Poll Public – Do Not Select: The election is only open to
committers
* Make Poll a test poll – Do Not Select: This is not a test
* Make results available to only a limited set of users – Do Not Select:
All committers should be able to see the results
* Enable detailed ballot reporting – Select This Option: This option
will give you details on voting outcome for each candidate
** Once this option is selected, you will be presented with another
option:
*** "In detailed ballot report, also reveal the identity of the voter
for each ballot…" - Do Not Selection this option if you want to keep the
voting anonymous. If however your project would like full transparency
on the vote, then select this option.
* Allow voters to write in new choices – Do Not Select: PTLs are self
nominated and must be committers. Write in choices are not valid
* Present choices on voting page in exactly the give order – Do Not
Select: By not selecting this option the candidate names will appear in
random order on different ballots
* Allow voters to select “no opinion” – Do Not Select: To avoid
unpredictable results it is best to require all voters to rank all
candidates
* Enforce proportional representation – Do Not Select: This option is
not helpful or applicable to PTL elections
11. select the [Create poll] button
12. Next you will be informed by the CIVS system that the Poll has been
created and an email has been sent to you as the supervisor of the
voting. If you do not receive an email from “Condorcet Internet Voting
Service”, then you have probably mistyped your email address and will
need to begin again.
13. In the mail you receive will be a link to your voting page. Save
this mail for future reference and then click on the provided link. It
will take you to a page where you can start the election by pressing the
[Start poll] button. Once you press the [Start poll] button, and email
will be sent to each voter with an individualized link where to vote.
14. If you forget to include someone in the vote, you can add them to
the voting at the bottom of this page as well.
15. When the end of the voting window has arrived, go back to this same
page and select the [End poll] button. You, and all voters will be
emailed the result of the election.

