[[data-storage-service-poc-with-hbase]]
=== Data Storage Service POC with HBase

Data Storage Service POC wraps HBaseClient as features and deploy it on
Karaf. With HBase server installed on localhost, a bunch of mocked up
statistics data are stored in HBase tables.

[[data-storage-service-setup-instructions]]
=== Data Storage Service setup instructions

* Install HBase 0.90.5 by downloading the zip file and untar the tar
ball to /usr/lib/hbase directory on your local machine.

https://archive.apache.org/dist/hbase/hbase-0.90.5/

* Fetch the tsdr code from the above link:
https://git.opendaylight.org/gerrit/14655 [DRAFT]
* Compile tsdr project.
* Compile integration project.
* Start hbase from /usr/lib/hbase//bin
* Start hbase shell by running 'hbase shell' from the above directory.
* Create a FlowMetrics table:

hbase shell> create ‘FlowMetrics’, ‘c1’

* Start Karaf from integration project
* Install both hbase and odl-TSDR-datastorage features.
* You should see the data being populated in 'FlowMetrics' table.

Note: to trunctate the table for testing again: hbase shell> truncate
‘FlowMetrics’
