[[data-collection-poc]]
=== Data Collection POC

Data Collection POC demonstrates notification based data collection of
OpenFlow statistics using mininet. A notification listener is created to
capture the OpenFlow statistics published on MD-SAL and print out the
data on the console.

[[poc-setup-instructions]]
=== POC setup instructions

* Fetch the POC code from the above link:
https://git.opendaylight.org/gerrit/14655 [DRAFT]
* Install ODL and the needed Karaf features as follows:

feature:install odl-base-all odl-aaa-authn odl-restconf odl-nsf-all
odl-adsal-northbound odl-mdsal-apidocs odl-l2switch-switch odl-dlux-core

* Download VirtualBox and install it on your desktop/laptop
* Download the mininet VM from below link and extract the zip file.

https://github.com/mininet/mininet/wiki/Mininet-VM-Images

* When you launch VirtualBox, select "Import Appliances" from the file
menu and point it to the mininet extracted file, once it is finished
importing, edit the VM settings and select either Bridge Networking or
Host only networking, note that bridge networking will only work if you
are hard wire via ethernet to the network and via wifi.
* Start the VM and login using "mininet/mininet".

"sudo su -" to go to root.

* Execute the following command line to start the mininet switch:

mn --switch=ovsk,protocols=OpenFlow13 --controller=remote,ip=,port=6653
--topo=tree,3

It should connect to your controller running on your desktop/laptop.
