__TOC__

[[examples]]
= Examples

The goal of this page is to bring all of our getting started examples
into a single place to make it easier for new comers to find their way
to useful examples. The following wiki pages provide examples with
varying level of detail. Below we list each (known) example, along with
a brief description of what it demonstrates.

* Ping example - demonstrates code generate from a yang file, and how
you can use a customer northbound rest API.
* OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step[Toaster
Step-By-Step]

::
  Demonstrates how to create a singleton service inside of the
  controller which provides changing operational data, some
  configuration data, and RPC implementation. It also explains about the
  necessary changes to pom.xml files to generate source code
  automatically from the .yang files, and it touches on the config
  sub-system provided in the controller. Finally it discusses breifly
  how to interact with the singleton service via the generic RESTCONF
  interface.

* OpenDaylight_Controller:MD-SAL:L2_Switch[ L2 Switch Sample] - Provides
an example learning switch based on MD-SAL which optimizes how packets
are forwarded.
* link:Ping 2.0 - Discover and Model Plugin[Ping 2.0 - Discover and
Model Plugin] - An example MD-SAL application which demonstrates how to:
Create a singleton service, respond to RPC calls, create
Inventory:Nodes:Node , augment created nodes with additional attributes,
mount RPC calls and data readers onto a specific node, and listen for
changes in a tree and react accordingly.
* http://sdntutorials.com/category/md-sal/ - Small snippets of code
illustrating how to perform various small tasks.
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL#MD-SAL_and_ODL_App_Tutorials[MD-SAL
Apps & Tutorials]

If you know of more examples, please continue to expand this page!
