[[introduction]]
= Introduction

*git-review* is a command-line tool for Git / Gerrit. It makes it easier
to configure your git clone, to submit a change or to fetch an existing
one.

The upstream project is led by Openstack. Not to be confused with the
unrelated Facebook project.

[[installation]]
= Installation

Before you start, make sure you already have your account and SSH keys
set up in Gerrit. See OpenDaylight_Controller:Gerrit_Setup for
instructions.

To install git-review, please see the instructions
http://www.mediawiki.org/wiki/Gerrit/git-review#Installation[here]

[[workflow]]
= Workflow

[[initial-setup]]
== Initial Setup

Clone your git repository, and in the root directory enter the following

`git review -s`

This will set up your connection to Gerrit

[[submitting-patches]]
== Submitting Patches

Once you've added and committed your changes, you can use git-review to
publish to Gerrit

`git review`

Git-review will rebase your changes against the master branch in Gerrit
before pushing. It will also notify you of merge conflicts so you can
manually resolve them. You can disable the rebase by using the _-R_ or
_--no-rebase_ flags.

[[adding-a-topic]]
=== Adding a topic

By default, the Gerrit topic will be the name of your local branch. You
can change this using the _-t_ or _--topic_ flags.

`git review -t topic`

[[pushing-to-a-feature-branch]]
=== Pushing to a feature branch

To push to a branch other than master, just add the branch name.

`git review topic/schema` +
`git review stable/hydrogen`

[[pushing-a-draft]]
=== Pushing a draft

Pushing to drafts is easy:

`git review -D`

or

`git review --draft`

[[adding-a-dependency]]
=== Adding a dependency

To make your commit dependent upon another change...

`# ` +
`git review -d 6150` +
`# Create a new branch called foo` +
`git checkout -b foo` +
`git commit ` +
`git review`

[[updating-a-patch]]
=== Updating a Patch

Assuming you already have the local branch with your patch in, simply
make your changes...

`git commit --amend` +
`git review`

Alternatively you can checkout a patch to review use the *-d* flag
followed by the change number in Gerrit

`git review -d 6150`

Make your changes and resubmit to Gerrit.

`git commit --amend` +
`git review -t `` -f`

_-f_ will delete the local branch and checkout the master branch.

[[reviewing-patches]]
== Reviewing Patches

If you are downloading code to make changes or test functionality you
can do so as follows:

`git review -d 6150` +
`git commit --amend` +
`git review -t `` -f`

If you wish to diff between two patch sets you can do so using
git-review

`git review -m 6150,3`

Will diff between Patch Set 3 of change 6150 and the latest Patch Set.

[[further-reading]]
= Further Reading

The
http://www.mediawiki.org/wiki/Gerrit/git-review#Submitting_changes_with_git-review[git-review
wiki page] is a great resource.

[[appendix-a-why-gerrit-topics-are-awesome]]
= Appendix A: Why Gerrit Topics are Awesome!

Topics can be used as a search criteria in Gerrit by typing *topic:foo*.
This allows commits that are part of a feature to be easily tracked.

Category:Git and Gerrit[Category:Git and Gerrit]
