[[hackfest-agenda-october-13-2014-dusseldorf-germany]]
= HackFest Agenda: October 13, 2014 (Dusseldorf, Germany)

*IMPORTANT:* You must register for the HackFest (being held at the
LinuxCon/CloudOpen Europe) by clicking
[https://www.regonline.com/register/login.aspx?eventID=1585919&MethodId=0&EventsessionId=
here.]

[[location-and-logistics]]
== Location and Logistics

*Congress Centre Düsseldorf* Stockumer Kirchstraße 61, Düsseldorf,
Germany 40474 October 13th (Monday)

* 8:30am - 9:30am Breakfast available
* 9:30am - 5:30pm Hackfest (lunch included on-site)
* 6:00pm - 8:00pm Happy Hour

[[hackfest-agenda-march-26th---28th-2014]]
= HackFest Agenda: March 26th - 28th, 2014

""IMPORTANT:"" You must register for the HackFest ( being held at the
Linux Foundation Collaboration Summit) by doing the following:

* Go here to register:
https://www.regonline.com/linuxfoundationcollaborationsummit2014[Linux
Foundation Collaboration Summit Registration]
* Choose "Invitation Acceptance" as the registration type
* Provide the correct Access code depending on how many days you will be
attending
** If you plan to attend the Collaboration Summit Plenary Sessions on
March 26th, Use Access code: ODSINV
*** Go
http://events.linuxfoundation.org/events/collaboration-summit[here] for
more information on the Linux Foundation Collaboration Summit first day
agenda.
** If you plan on only attending the 2 day hackfest on March 27th and
28th, please use the Access Code: ODSINV2ON

[[agenda]]
== Agenda

* Thursday, March 27th
** More design focused, less hacking
** Discussion topics include:
*** Automating the Release Process
*** Performance test strategy and tools
*** Documentation Plans
*** OpenDaylight_Virtual_Tenant_Network_(VTN):Main[ VTN Project] Demo
**** Demonstrate integration of OVSDB plugin and VTN Manager for
Neutron.
*** NBI and Policy/Affinity architecture & IM discussion
*** Adding Auditing/Monitoring
*** High level model tree organization (ie, lets try to produce
guidelines for a sane organization in a multi-app world ;) ).
*** What should a 'Forge' for ODL look like?
*** MD-SAL Data Store requirements, Usage Patterns for Inventory,
Topology, Policy, Host Tracker etc..
*** ADD MORE HERE

* Friday, March 28th
** More Hacking Focused, less discussion
** Developing (with) the MD-SAL and YangTools
** Robot Framework hands-On - Write your own test!
** Learning switch enhancements to implement minimum spanning tree
** Port host tracker to MD-SAL
** Things that need to get done
*** ADD MORE HERE

[[vhackfest]]
== vHackfest

We will once again be running a vHackfest for those who cannot attend in
person. This will consist of:

1.  Ongoing participation on #opendaylight on Freenode IRC
2.  We will have a very nice video camera hooked up to a LiveStream
session. This camera will cover the room in general. The URL for the
Livestream will be published on the IRC channel during the HackFest.
1.  The LiveStream URL is:
https://new.livestream.com/accounts/5312056/events/2868611
3.  Five iPad Mini's will be set up on Webex sessions and hooked up to
good mic/speakers to allow participation remotely (click on link for
webex session below, password is 'default' for each of them).
1.  [ Singleton ] - MDSAL Hacking
* Meeting Number: 208026961
* Meeting Password: 123456
* Go to
https://cisco.webex.com/cisco/j.php?MTID=m8a7f97605797a412149c5ce12ffe6087

1.  1.  [ Proxy ] - Testing Activities and Automation
* Meeting Number: 201359036
* Meeting Password: 123456
* Go to
https://cisco.webex.com/cisco/j.php?MTID=mc447d814d291021829a409b0ce81d984 +

The webex sessions should allow folks to participate via audio, video,
and web share remotely :)

Since the Hackfest is run as an unconference, its not really knowable
ahead of time what will be going on at each Webex, but we will update on
IRC and here on this page as this ebb and flow so people can go to the
topics that interest them :)

[[ideas]]
== Ideas

* TBD

[[hackfest-agenda-september-10-11-2013]]
= HackFest Agenda: September 10-11, 2013

*IMPORTANT:* You must register for the HackFest by clicking
http://www.regonline.com/opendaylightseptemberhackfest[here].

September 10

* 8:30am - 9:30am Breakfast available
* 9:30am - 5:30pm Hackfest (lunch included on-site)
* 6:30pm - 8:00pm SDDC Symposium Happy Hour**

September 11

* 8:30am - 9:30am Breakfast available
* 9:30am - 5:30pm Hackfest (lunch included on-site)

All OpenDaylight HackFest attendees have been invited to join the
Software-Defined Data Center Symposium happy hour event on Tuesday
(9/10) from 6:30 - 8:00pm in Santa Clara (just a 10 minute drive from
the HackFest).

This event is free to attend (as OpenDaylight is a sponsor) and a great
way to meet people from the industry and end-user community who focus on
SDN, OpenFlow, software-defined storage, convergence, and the greater
software-defined future.

Please https://sddc13p.eventbrite.com[register now] if you plan on
attending. Please note, there will not be an evening reception at the
HackFest venue on 9/10 -- this SDDC Symposium happy hour is where
interested OpenDaylight attendees will meet.

[[vhackfest-1]]
== vHackfest

We will once again be running a vHackfest for those who cannot attend in
person. This will consist of:

1.  Ongoing participation on #opendaylight on Freenode IRC
2.  We will have a very nice video camera hooked up to a LiveStream
session. This camera will cover the room in general. The URL for the
Livestream will be published on the IRC channel during the HackFest.
1.  The LiveStream URL is:
https://new.livestream.com/accounts/5312056/events/2392784
3.  Five iPad Mini's will be set up on Webex sessions and hooked up to
good mic/speakers to allow participation remotely (click on link for
webex session below, password is 'default' for each of them).
1. 
https://cisco.webex.com/ciscosales/j.php?ED=206352908&UID=484347612&PW=NN2ZhOGJiMTUx&RT=MiM0[Singleton
- OpenStack Integration]
2. 
https://cisco.webex.com/ciscosales/j.php?ED=206353333&UID=484347612&PW=NMTA1ZmYxOTFk&RT=MiM0[Momento]
3. 
https://cisco.webex.com/ciscosales/j.php?ED=206353453&UID=484347612&PW=NYjlkNGZmYWRi&RT=MiM0[Proxy
- SouthBound Plugins]
4. 
https://cisco.webex.com/ciscosales/j.php?ED=206353838&UID=484347612&PW=NNjNlNjZhNDM5&RT=MiM0[Visitor]
5. 
https://cisco.webex.com/ciscosales/j.php?ED=206353753&UID=484347612&PW=NZTQwNTExYThj&RT=MiM0[Adapter]

The webex sessions should allow folks to participate via audio, video,
and web share remotely :)

Since the Hackfest is run as an unconference, its not really knowable
ahead of time what will be going on at each Webex, but we will update on
IRC and here on this page as this ebb and flow so people can go to the
topics that interest them :)

[[ideas-1]]
== Ideas

* OpenDaylight_Virtual_Tenant_Network_(VTN):Main[ VTN Project] Demo
** Demonstrate that VTN controls multiple OpenDaylight Controllers
(OpenDaylight_Virtual_Tenant_Network_(VTN):Implementation[VTN System]).
** => The demo slides are available here:
Media:NEC_VTN_Demo_0910.pdf[VTN Demo slides]
** dmm: It looks like the figure implies that each controller controls
some number of switches and the sets of switches controlled by each
controller don't overlap. Its this the case?
*** hideyuki: Yes, each controller controls some number of switches, and
the sets of switches controlled by each controller don't overlap.
** dmm: in addition, does the VTN Coordinator (ODC driver?) do state
management among the ODCs?
*** sarath: Yes, VTN Coordinator does state management for the virtual
networks (VTN, vBridge, vBridge Interface) managed by VTN Coordinator.
* OF 1.3+ SB Plugin and Protolib
** Hack code on integrating the SB Plugin and Protolib plugins and the
SB Plugin and the MD-SAL
** Hack code on adding support for multiple ports for OF 1.3+ (OF is
having to change its port... we should support the old and new)
** Hack on code to allow policies like message shaping and connection
policing (as well as others)
* Understanding MD-SAL and how to integrate your project with it - move
real code
* Understanding Clustering and HA support, and how to add them to your
project (Presentation and Hands on Work)
* Controller's native container/tenant support discussion & its usage by
other projects
* Openstack ML2 integration with networkconfig.bridgedomain services
with OVSDB south-bound plugin
* Start writing some OVSDB models
* Work on OpenStack ML2 integration

[[hackfest-agenda-july-22-23-2013]]
= HackFest Agenda: July 22-23, 2013

*IMPORTANT:* You must register for the HackFest by clicking
http://www.regonline.com/Register/Checkin.aspx?EventID=1253008[here].

July 22

* 8:30am - 9:30am Breakfast available
* 9:30am - 5:30pm Hackfest (lunch included on-site)
* 5:30pm - 7:00pm Happy Hour

July 23

* 8:30am - 9:30am Breakfast available
* 9:30am - 5:30pm Hackfest (lunch included on-site)

Final HackFest details/location will be emailed to all registered
attendees on Thursday, July 18th.

[[vhackfest-2]]
== vHackfest

We will once again be running a vHackfest for those who cannot attend in
person. This will consist of:

1.  Ongoing participation on #opendaylight on Freenode IRC
2.  We will have a very nice video camera hooked up to a Webex session
named Prototype. This camera will cover the room in general.
1. 
https://cisco.webex.com/ciscosales/j.php?ED=232907882&UID=484320912&PW=NNmJlOTE2ODFi&RT=MiM3[Prototype]
- Affinity Project Presentation
3.  Five iPad Mini's will be set up on Webex sessions and hooked up to
good mic/speakers to allow participation remotely (click on link for
webex session below, password is 'default' for each of them).
1. 
https://meetings.webex.com/collabs/#/meetings/detail?uuid=M417LH9LDSQG5RFU55ZHRJXU8P-9VIB[Singleton]
2. 
https://meetings.webex.com/collabs/#/meetings/detail?uuid=M6PH6UUF7QR2T9OEN8Y0ER31BO-9VIB[Momento]
3. 
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MEM6VLGNYMPVV5E09HIWRFCSN6-9VIB[Proxy]
4. 
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MEX2N4P5OZCAY634IZD0T9QOK9-9VIB[Visitor]
5. 
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MA1WYVJUUUOFOT8FZCXPOR5O2R-9VIB[Adapter]

The webex sessions should allow folks to participate via audio, video,
and web share remotely :)

Since the Hackfest is run as an unconference, its not really knowable
ahead of time what will be going on at each Webex, but we will update on
IRC and here on this page as this ebb and flow so people can go to the
topics that interest them :)

[[ideas-2]]
== Ideas

* *VTN Code Walkthrough:*
* *Intro to new projects:* We have quite a few newly proposed projects
that people would probably like at least a brief dive into. You can find
them on the Project Proposals:Main[project proposals page], but they
include.
** Project_Proposals:Affinity_Metadata_Service[ The Affinity Metadata
Service Proposal]
** Project_Proposals:LispMappingService[ The LISP MappingService
Proposal]
(https://wiki.opendaylight.org/images/6/6e/LispMappingService_ProjectProposalSlides.pdf[slides])
** Project_Proposals:YANG_Tools[ YANG Tools]
** Project_Proposals:OpenDefenseFlow[ OpenDefenseFlow - An Anti-Dos
system]
(https://wiki.opendaylight.org/images/f/fc/130708_-_OpenDefenseFlow_Proposal_Overview.pdf[slides])
** Project_Proposals:BGP_and_PCEP[ BGP and PCEP Project Proposal]
** Project_Proposals:Openflow_1.3_Protocol_Library[ Openflow 1.3
Protocol Library (Java)]
** Project_Proposals:Open_DOVE[ Open DOVE network virtualization
platform]
** Project Proposals:OVSDB-Integration[ OVSDB Integration]
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Architectural_Framework#Evolution_of_the_Controller_Service_Abstraction_Layer[Model
Driven SAL]
* Overlay API Collaboration ( OpenDOVE,VTN,LISP,BGP-LS/PCEP)
* OpenDaylight southbound plugin architecture/framework
* Overall Continuous System/Integration Testing for Simultaneous Release

[[what-happened]]
== What happened

1.  Intro and gathering of topics:
1.  OpenStack Integration (13)
2.  HA/Clustering/Persistency stuff (12)
3.  SAL data model and how to minimize duplicate functionality (11)
4.  Getting started with new projects: Sync source, Building, Etc (9)
5.  Auto-generating NB API's from model (9)
6.  VTN Manager (7) and VTN Coordinator (5)
7.  Southbound plug-in architecutre and framework (6)
8.  YANG Tools overview (5)
9.  Lisp flow mapping service (5)
10. Affinity and service chaining (on Tuesday) (5)
11. OVS DB integration (4)
12. Continuous integration between projects (4)
13. Overlay collaboration model (4)
14. How to do a distribution directory for your project (3)
15. Flow persistency and OVS flow sync (?)
2.  VTN Demo and Code Walkthrough
3.  LISP Mapping Service Presentation

Day 2:

1.  Intro and gathering of topics (new topics only)
1.  Infrastructure (DBs, pub/sub, messge bus, distribution/clustering)
(3)
2.  Types of Storage (3)
2.  Affinity Management Service Presentation

[[intro-to-opendaylight]]
== Intro to OpenDaylight

Some set of people, hopefully including those who got spun up at the
last hackfest, will set up at least a table to walk newcomers through
getting code up and working. This should be at least for the
`controller` project, but perhaps other projects as well assuming we
have code.

[[hackfest-agenda-june-6-7-2013]]
= HackFest agenda: June 6-7, 2013

[[dixon-erickson-proposal-blueprint-creation]]
== Dixon-Erickson Proposal Blueprint creation

Goal: collect owners for each row in
link:Dixon-Erickson_OpenDaylight_Merged_Controller_Proposal[DE plan] and
build detailed blueprints

* D-E_Proposal:Host_Tracker_Plan[Host Tracker] plan
** Rob Adamn's gerrit commit
https://git.opendaylight.org/gerrit/#/c/438/[1]
* Consistent, Replicated Data Store:
https://lists.opendaylight.org/pipermail/controller-dev/2013-May/000537.html[discuss
mail thread]
* Threading support:
https://lists.opendaylight.org/pipermail/controller-dev/2013-May/000495.html[discuss
mail thread]

[[deep-dive-on-virtual-tenant-networking-vtn-proposal]]
== Deep Dive on Virtual Tenant Networking (VTN) Proposal

Goal: Introduce VTN Proposal

Time: 2 hours

1.  Media:NEC VTN Model 0606.pdf[Overview of the VTN Proposal]
2.  Media:NEC VTN Demo 0606.pdf[Live Demo]
3.  Media:NEC VTN Implementation 0606.pdf[VTN Implementation]

[[introduction-to-opendaylight]]
== Introduction to OpenDaylight

* Some set of people should set up at a table or perhaps a whole corner
of a room to provide tutorials and help for one or both code bases to
get people up to speed. Ideally, this could be paid forward with people
passing along their expertise to those coming later.
* This is a request: Could someone do a deep dive into the controller
codebase for people who are relatively new to OpenDaylight codebase?

[[additional-topics]]
== Additional topics

* Patterns and best practices for integrating non-Java projects into the
Open Daylight controller

