[[meeting-minutes]]
= Meeting Minutes

[[minutes-for-2015-jan-28]]
== Minutes for 2015-JAN-28

Agenda - get up and runnning with ODL, and await a sample iotdm project
tutorial

* Get on the mailing list if you have not already done so …
https://lists.opendaylight.org/mailman/listinfo/iotdm-dev
* Here is a link to our project page
https://wiki.opendaylight.org/view/IoTDM:Main
** Webex instructions for the meeting are on this page
* Here is a link to a new project responsible fore OpenDaylight
tutorials
https://wiki.opendaylight.org/view/Controller_Core_Functionality_Tutorials:Main
** Take a look at the
https://wiki.opendaylight.org/view/Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project
** It is a set of chapters that explain model driven development in ODL.
These are a work in progress and thus will change.
* Also in the documentation, there is a new StartingAProject maven
archetype that is being developed. It in a work in progress too.
** An archetype is used to generate a project structure, see
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Startup_Project_Archetype
** We hope to use this for the IoTDM repository once it is DONE
* We can provide a sample of some of the stuff we have been working on …
** A sample directory of what IoTDM might ultimately look like
** It has the start of a yang model for the OneM2M resource tree
** There are instructions on how to use RESTconf to add resources to the
IoTDM resource tree
* A small document on OneM2M Wire Protocol Plugin’s.
** Describing the flow of messages from a client to the ODL plugin to
OneM2M core
** All of this stuff is a work in progress but illustrates what we are
thinking so far.

ACTION: EVERYBODY ... try the tutorials, get comfortable with the dev
environment, let us know if you cannot get up and running

[[minutes-for-2015-feb-11]]
== Minutes for 2015-FEB-11

ACTION: EVERYBODY ... try the tutorials, get comfortable with the dev
environment, let us know if you cannot get up and running

[[minutes-for-2015-feb-25]]
== Minutes for 2015-FEB-25

Meeting cancelled.

[[minutes-for-2015-mar-11]]
== Minutes for 2015-MAR-11

Status Update: In a couple of weeks, the repo will start to be populated
with infrastructure for core OneM2M data collector services. At that
point, it may be possible to write external applications that can
interact with the OneM2M resource tree via HTTP and CoAP. See below for
TS-0008 CoAP[0] and TS-0009 HTTTP[1] for protocol details. Some thought
is being put into how somebody would write a local Karaf OneM2M plugin.
A CMX prototype plugin is being developed concurrent to the core
development to give us better ideas and best practices. The insight is
really the thought and design of the OneM2M resource tree
structure/provisioning with applications use requirements and device
capabilities kept in mind. Kevin B from Echelon is also going to give
some thought how he would model a resource tree for the suite of Echelon
devices and how it would interact with the Echelon gateway. ACTION:
Lionel to provide him with his prototype to give him ideas. Also, we
will need to FIND OneM2M compliant "things" to interact with as the
OneM2M specs have been fluid. The use of long vs short names, JSON vs
XML, and Enum's in some of the documents are causing us some grief so an
integration excersize with a 3rd party Onem2m compliant device would be
a good exercise.

We need go figure out how to work with the OpenDaylight integration
framework so that our code can be tested and integrated automatically as
builds are done!

`[0] `http://www.onem2m.org/images/files/deliverables/TS-0008-CoAP_Protocol_Binding-V1_0_1.pdf[`http://www.onem2m.org/images/files/deliverables/TS-0008-CoAP_Protocol_Binding-V1_0_1.pdf`]` ` +
`[1] `http://www.onem2m.org/images/files/deliverables/TS-0009-HTTP_Protocol_Binding-V1_0_1.pdf[`http://www.onem2m.org/images/files/deliverables/TS-0009-HTTP_Protocol_Binding-V1_0_1.pdf`]
