[[welcome-to-the-opendaylight-developer-wiki]]
== Welcome to the OpenDaylight Developer Wiki

This wiki contains all of the developer level information for the
OpenDaylight Project. You will need an
https://identity.opendaylight.org[account] if you would like to
contribute to this wiki or the components of the OpenDaylight Project.
As components are being proposed for inclusion in the project and added
to the software repository, we are adding the documentation for each
component as it has been provided by the contributor. These
contributions and their documentation are either in the project
lifecycle state of "Bootstrap" or "Incubation" (as identified below). As
the projects graduate from these early lifecycle states to more mature
states, their associated wiki documentation will also become more mature
and integrated.

[[opendaylight-projects]]
== OpenDaylight Projects

[[getting-started]]
=== Getting Started

GettingStarted:Developer Main[ Getting Started for Developers ]

GettingStarted:Project_Main[ Getting Started for Projects]

GettingStarted:Code_of_Conduct[ Code of conduct for collaboration]

[[core-architectural-principles]]
=== Core Architectural Principles

OpenDaylight Controller:Architectural Principles[Architectural
Principles]

OpenDaylight_Controller:Architectural_Principles#Open_Extensible_Northbound_API[API]

[[maturecoretop-level-projects]]
=== Mature/Core/Top Level Projects

* No Projects are currently in a Mature or greater state

[[bootstrap-projects]]
=== Bootstrap Projects

* OpenDaylight Controller:Main[OpenDaylight Controller]
* OpenDaylight SDN Controller Platform (OSCP):Main[OpenDaylight Network
Virtualization Platform]
* OpenDaylight_Virtual_Tenant_Network_(VTN):Main[ OpenDaylight Virtual
Tenant Network]
* Open_DOVE:Main[Open DOVE]
* OpenDaylight_OpenFlow_Plugin:Main[OpenFlow Plugin]
* Project_Proposals:Affinity_Metadata_Service[Affinity Metadata Service]

[[incubation-projects]]
=== Incubation Projects

* YANG Tools:Main[YANG Tools]
* OpenDaylight_Lisp_Flow_Mapping:Main[LISP Flow Mapping]
* OVSDB_Integration:Main[OVSDB Integration]
* Openflow_Protocol_Library:Main[ OpenFlow Protocol Library]
* BGP_LS_PCEP:Main[ BGP-LS/PCEP]
* Project_Proposals:Defense4All[Defense4All]
* Project_Proposals:SNMP4SDN[SNMP4SDN]

[[to-propose-a-new-opendaylight-project]]
=== To Propose a New OpenDaylight Project

* Go to the Project_Proposals:Main[Project Proposals Page] and from
there follow the instructions to create a new page that describes your
proposal. Anyone member or not can propose a project (there have already
been projects successfully created by non-member companies and by
unaffiliated individuals).

[[technical-collaborations]]
== Technical Collaborations

[[developer-events]]
=== Developer Events

* *The next OpenDaylight vHackFest is scheduled for September 19th, 2013
in online* - HackFests:vHackFest Sept 19 2013[vHackFest Sept 19 2013]

Events:Main[Developer Events]

[[work-streams-committees]]
=== Work Streams & Committees

* TSC:Main[ TSC Page]
* Tech Work Stream:Main[ Technical Work Stream Page]

[[cross-project-collaborative-groups]]
=== Cross Project Collaborative Groups

* CrossProject:OpenStack Plugin Group[OpenStack Plugin Group]
* CrossProject:Integration Group[Integration Group]

[[simultaneous-release]]
=== Simultaneous Release

Simultaneous Release:Simultaneous Release Plan 2013[ Simultaneous
Release Plan]
