__NOTOC__

[[welcome-to-the-opendaylight-developer-wiki]]
== Welcome to the OpenDaylight Developer Wiki

[cols=",",]
|===================================
a|
[[deploying-and-using-opendaylight]]
=== Deploying and using OpenDaylight

 a|
[[getting-involved]]
=== Getting involved

a|
[[release-planning]]
=== Release planning

 a|
[[projects]]
=== Projects

|===================================

*_You will need an https://identity.opendaylight.org[OpenDaylight
Account] if you would like to contribute to this wiki or the components
of the OpenDaylight Project. To access the account creation form,
currently you need to click the colorful icon
https://identity.opendaylight.org/carbon/user-registration/index.jsp?region=region1&item=user_registration_menu[here]._*

This wiki contains all of the developer level information for the
OpenDaylight Project. As components are being proposed for inclusion in
the project and added to the software repository, we are adding the
documentation for each component as it has been provided by the
contributor. These contributions and their documentation are either in
the project lifecycle state of "Bootstrap" or "Incubation" (as
identified below). As the projects graduate from these early lifecycle
states to more mature states, their associated wiki documentation will
also become more mature and integrated.

[[infrastructure-guides]]
== Infrastructure Guides

Infrastructure:Nexus[Nexus proxy setup guide]

[[core-architectural-principles]]
== Core Architectural Principles

OpenDaylight Controller:Architectural Principles[Architectural
Principles]

OpenDaylight_Controller:Architectural_Principles#Open_Extensible_Northbound_API[API]

[[representation-on-the-opendaylight-board-of-directors]]
== Representation On The OpenDaylight Board Of Directors

Two committers from the OpenDaylight technical community are elected
annually to the Board of Directors. Please see the
link:Committer_Members_Board_Representation[Committer Members Board
Representation] page for more details.

The 2014 Committer Board Member Election has ended with Matthieu Lemay
and Luis Gomez elected to represent the ODL committer members to the ODL
Board of Directors.

[[technical-collaborations]]
== Technical Collaborations

[[developer-events]]
=== Developer Events

* Events:Main[Developer Events]

[[work-streams-committees-meetings]]
=== Work Streams, Committees & Meetings

[[cross-project-collaborative-groups]]
=== Cross Project Collaborative Groups

* CrossProject:OpenStack Plugin Group[OpenStack Plugin Group]
* CrossProject:Integration Group[Integration Group]
* CrossProject:Documentation Group[Documentation Group]
* CrossProject:HouseKeeping Best Practices Group:Main[ HouseKeeping Best
Practices Group]
* CrossProject:Hydrogen Release Work[Hydrogen Release Work]
* CrossProject:Demos and PoCs[Demos & PoCs]
* CrossProject:OpenDaylight Security Analysis[OpenDaylight Security
Analysis]
* CrossProject:Helium Release Vehicle Brainstorming[Helium Release
Vehicle Brainstorming]
* CrossProject:AutoRelease[Autorelease process]

[[intern-project-ideas]]
=== Intern Project Ideas

* InternProjects:Main[ Projects for Interns ]

[[collateral]]
== Collateral

[[opendaylight-presentations-people-have-done]]
=== OpenDaylight Presentations People Have Done

OpenDaylight Presentations:Main[OpenDaylight Presentations]
