__TOC__

[[overview]]
= Overview

The Weekly MD-SAL interest call will contain a 15 minute status update
followed by additional information for the given week. Please see the
agenda for the update topic.

[[weekly-meeting]]
= Weekly Meeting

* Link
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MCQK23GTHZNO7LDV6UWT6KLYPV-9VIB&rnd=497132.35684

* IRC Meeting Name: "MD-SAL interest call"

* *Time:* Tuesdays 9am US/Pacific
** Meeting number: 194 764 014
** Password: This meeting does not require a password.
** Host key: 720589 (Use this key in the meeting if you have made
someone else the host and then want to reclaim the host role.)

* Audio Connection
** 1-855-244-8681 Call-in toll-free number (US/Canada)
** 1-650-479-3207 Call-in toll number (US/Canada)
** Access code: 194 764 014

[[agenda]]
= Agenda

''Tuesday, April 14th, 2015 - Discuss Yangtools bug 2825

* Link to Presentation on Yangtools:
https://wiki.opendaylight.org/images/3/32/Bug-2825_copy.pdf
* See IRC notes from April 7th for links to e-mails on this topic.

Event Bus:

* Andrew to provide information and demo on the Event Bus

Other Topics:

* New Cohorts API -
* New Data Change Listener Overview?

Other topics? Please modify this page and/or email
Devin.Avery[at]Brocade.com.

We will do a call for topics at the start of a call (if there is room).
If we do not have enough content we will end the meeting early.

[[queries]]
= Queries

The following queries can help to provide insight into changes in the
controller and will help to expose discussion points during the call.

[[code]]
== Code

Pending:

*
https://git.opendaylight.org/gerrit/#/q/status:open+project:controller+NOT+age:7d[Controller:
Open Items Updated in the Last 7 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:open+project:controller+NOT+age:14d[Controller:
Open Items Updated in the Last 14 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:open+project:yangtools+NOT+age:7d[Yangtools:
Open Items Updated in the Last 7 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:open+project:yangtools+NOT+age:14d[Yangtools:
Open Items Updated in the Last 14 Days]

Merged:

*
https://git.opendaylight.org/gerrit/#/q/status:merged+project:controller+NOT+age:7d[Controller:
Merged Items in Last 7 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:merged+project:controller+NOT+age:14d[Controller:
Merged Items in Last 14 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:merged+project:yangtools+NOT+age:7d[Yangtools:
Merged Items in Last 7 Days]
*
https://git.opendaylight.org/gerrit/#/q/status:merged+project:yangtools+NOT+age:14d[Yangtools:
Merged Items in Last 14 Days]

[[bugs]]
== Bugs

*
https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_target_milestone&f1=cf_target_milestone&f2=days_elapsed&list_id=25751&o1=substring&o2=lessthaneq&order=bug_status%20DESC%2C&product=controller&query_format=advanced&v1=Lithium&v2=7[Controller
Bugs: Modified in Last 7 Days]
*
https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_target_milestone&f1=cf_target_milestone&f2=days_elapsed&list_id=25751&o1=substring&o2=lessthaneq&order=bug_status%20DESC%2C&product=controller&query_format=advanced&v1=Lithium&v2=14[Controller
Bugs: Modified in Last 14 Days]
*
https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_target_milestone&f1=cf_target_milestone&f2=days_elapsed&list_id=25751&o1=substring&o2=lessthaneq&order=bug_status%20DESC%2C&product=yangtools&query_format=advanced&v1=Lithium&v2=7[Yangtools
Bugs: Modified in Last 7 Days]
*
https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_target_milestone&f1=cf_target_milestone&f2=days_elapsed&list_id=25751&o1=substring&o2=lessthaneq&order=bug_status%20DESC%2C&product=yangtools&query_format=advanced&v1=Lithium&v2=14[Yangtools
Bugs: Modified in Last 14 Days]

https://wiki.opendaylight.org/view/OpenDaylight_Bugs

[[weekly-status]]
= Weekly Status

[[lithium]]
== Lithium

[[may-26-2015---discussion-bugs-for-major-controller-components-and-yangtools]]
==== May 26, 2015 - Discussion: Bugs For Major Controller Components and
Yangtools

*Topics* ODL Upgrade was discussed today.

[[link-for-meetings-webex-recording]]
==== Link for Meetings WebEx Recording

https://meetings.webex.com/collabs/meetings/playRecording?recordID=16056206&meetingInstanceID=I2ZNJLBAI2LUZFAVFFY61VCW4F-9VIB[WebEx
Recording]

[[link-to-irc-notes]]
==== Link to IRC Notes

https://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-26-16.00.log.html[IRC
Notes]

[[bug-scrub-and-general-meeting-notes]]
===== Bug Scrub and General Meeting Notes

*Discussed*

* How to effectively get bugs assigned to community volunteers
* Staring to discern what code changes are needed to implement a upgrade
feature from He to Li.
* Begin planning for MD-SAL in Beryllium
* Third Party libraries need to have their src files available.

*Bugs* Discussed

* Bugs with no assignee and bugs with no target milestone
* https://bugs.opendaylight.org/show_bug.cgi?id=2976[2976]
* https://bugs.opendaylight.org/show_bug.cgi?id=3160[3160]

[[may-19-2015---discussion-bugs-for-major-controller-components-and-yangtools]]
==== May 19, 2015 - Discussion: Bugs For Major Controller Components and
Yangtools

*Topics* Upgrade process from He to Li .

[[link-to-irc-notes-1]]
===== Link to IRC Notes

http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-19-16.03.html[`http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-19-16.03.html`]

[[bug-scrub-and-general-meeting-notes-1]]
===== Bug Scrub and General Meeting Notes

*Discussed* Scrubbed through approximately 15 bugs. There were questions
about bug 3051 as it affects downstream projects.
https://bugs.opendaylight.org/show_bug.cgi?id=3051[v6 prefix checking
broken]

`Can’t resolve bug 3051 until the downstream projects merge changes to use new IPv6builder()`

*Bugs* 3228, 1135, 1946, 2679, 3134, 3138

[[may-12-2015---discussion-bugs-for-major-controller-components-and-yangtools]]
==== May 12, 2015 - Discussion: Bugs For Major Controller Components and
Yangtools

*Topics*

` Recap Upgrading from He to Li  ` +
` Scrubbed 49 Bugs` +
`   `

Link for Meetings WebEx Recording:

https://meetings.webex.com/collabs/meetings/playRecording?recordID=15860531&meetingInstanceID=I2UDS9N8L4EU8QDYVV6MB239J0-9VIB

[[link-to-irc-notes-2]]
===== Link to IRC Notes

http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-12-16.02.html

[[bug-scrub-and-general-meeting-notes-2]]
===== Bug Scrub and General Meeting Notes

*Discussed*

Colin Informed mdsal meeting attendees that the TSC discussed Upgrading
from He to Li issue they feel ODL needs to work on a solution but
resources, volunteers are needed. Ttkacik advised that it will take a
least a week to analyze what is involved and any problems that may arise
as result of an upgrade process. Further discussion will be conducted
via email list.

*Bugs*

In order to foster more participation in bug fixing, we made a table of
the 49 bugs based on ease, difficulty of addressing and those that are
already assigned. This table will be published to the OpenDaylight
community via the MD-SAL and Discuss email list where subscribers can
volunteer to help with bug fixes.

[[may-5-2015---discussion-bugs-for-major-controller-components-and-yangtools]]
==== May 5, 2015 - Discussion: Bugs For Major Controller Components and
Yangtools

*Topics*

` Upgrading from He to Li  ` +
` Interpretation Matrix for Java Exceptions and Controller component errors` +
` Java 8`

Link for Meetings WebEx Recording:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-05-16.02.html

[[link-to-irc-notes-3]]
===== Link to IRC Notes

http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-05-05-16.02.html

[[bug-scrub-and-general-meeting-notes-3]]
===== Bug Scrub and General Meeting Notes

Discussed

* Bug 2976: Restarting controller after configuring netconf connector
fails
* The Upgrading process from He to Li; How to upgrade without loosing
current configuration.

[[april-28th-2015---discussion-bugs-for-major-controller-components-and-yangtools]]
==== April 28th 2015 - Discussion: Bugs For Major Controller Components
and Yangtools

Link for Meetings WebEx Recording: No recordings this meeting

[[bug-scrub-and-general-meeting-notes-4]]
===== Bug Scrub and General Meeting Notes

Reviewed critical bugs and bugs with no assignee.

For bugs where a workaround exists but the workaround is not in patch
form but is procedural, the steps for the workaround should be listed in
the Release Notes and a link to the bug put on the ¨Weather¨ page. All
AD-SAL bugs should be closed as AD-SAL has been deprecated.

Link To Unassigned Bugs Lithium
[https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&bug_severity=enhancement&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_severity%2Ccf_issue_type%2Cshort_desc%2Cbug_status%2Cpriority%2Cdeadline%2Ccf_target_milestone&component=config&component=General&component=mdsal&component=netconf&component=other&component=restconf&email1=bug&emailassigned_to1=1&emailtype1=substring&f1=cf_target_milestone&known_name=MD-SAL&list_id=28944&o1=substring&product=controller&product=yangtools&query_based_on=MD-SAL&query_format=advanced&resolution=---&v1=Lithium
Unassigned Bugs]

*Blocking Bugs*:

`Bring to Release meeting` +
`Note on Weather page`

[[april-21st-2015---discussion-of-calls-bugs]]
==== April 21st, 2015 - Discussion of Calls, Bugs

Link for Meetings WebEx Recording:
https://meetings.webex.com/collabs/meetings/playRecording?recordID=15548346&meetingInstanceID=I2MGWFWW7U20J4RL991XXAGGV8-9VIB

Summary of Meeting times for MD-SAL

* Tuesday 8 AM - MD_SAL Clustering Call
* Tuesday 9 AM PST - MD-SAL Weekly Call

[[bug-scrub-and-general-meeting-notes-5]]
===== Bug Scrub and General Meeting Notes

Link to query for Bugs to be discussed weekly until Lithium release:
https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&bug_severity=enhancement&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_severity%2Ccf_issue_type%2Cshort_desc%2Cbug_status%2Cpriority%2Cdeadline%2Ccf_target_milestone&component=config&component=General&component=mdsal&component=netconf&component=other&component=restconf&list_id=28323[Lithium
Bugs]

Anton's Discussion of Bug 2825 - IPv4, IPv6 parsing incorrectly affects
performance https://bugs.opendaylight.org/show_bug.cgi?id=2825 List
Discussion of bug 2825:

[[april-14th-2015---discussion-of-calls-event-bus-demo]]
==== April 14th, 2015 - Discussion of Calls, event bus demo

Links for Meetings WebEx Recording:

Recording:https://meetings.webex.com/collabs/url/lc_1Krr44mnvMMK0FAqvOPJtHfpzi0YeVLoGsfix2qm00000

[[bug-scrub-and-general-meeting-notes-6]]
===== Bug Scrub and General Meeting Notes

'''Four Calls:

* Monday 8 AM PST — MD-SAL “hackers” call
** Introduced because MD-SAL weekly call didn’t have enough bandwidth.
* Monday 10 AM PST — TWS Call
** Colin - Colin’s take is that the TWS call is - higher level, more
granular call.
* Tuesday 8 AM - MD_SAL Clustering Call
* Tuesday 9 AM PST - MD-SAL Weekly Call

What do we want to cover in public meetings?

* Bug Scrub
** Tony - twice a week after M5 ?
** First 30 minutes of MD-SAL weekly call, and one on Thursday - time
TBD
** This would be moderated for the purpose looking at yangtools,
controller bugs
*** relating yangtools, md-sal, config, restconf, netconf, clustering
*** would we want to break clustering out? Suggestion to include
clustering.
*** these timeslots would be focused on doing:
**** look at and groom any new incoming bugs - decide if they are an
issue / FAD / enhancement etc.
**** discussing implementation details and prioritizing bugs
**** possibly finding volunteers to work bugs?
**** which bugs have been resolved fix
**** any outstanding issues.
**** Call is open to all, but moderator will cut off tangents.
* Design(?) and Implementation Details(?)
** High level overview design discussion, gather requirements, feedback
etc.
** Should happen in a more general forum where people with MD-SAL
implementation
*** knowledge can provide general feedback on concepts, usage etc.
** covered on MD-SAL hackers call and Clustering call
* Discussion happens at low level around API specifics etc
* General Topics / Q&A from community on how to use MD-SAL, Config,
issues etc
** Presentations of features and new functionality

[[april-7th-2015---bug-overview-discussions-on-things-coming-down-the-pipe]]
==== April 7th, 2015 - Bug overview, discussions on things coming down
the pipe

Links for Meetings:

[12:37] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-04-07-16.03.html
[12:37] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-04-07-16.03.txt
[12:37] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-04-07-16.03.log.html

Recording:
https://meetings.webex.com/collabs/url/SdyiFow2hJJjIZICGRzmkcSj9FWRhI-1NBaIuqnFIsy00000

[[march-31st-2015---wiki-conversations]]
==== March 31st, 2015 - Wiki Conversations

Quick discussion on how we can improve wiki links some.

Recording:
https://meetings.webex.com/collabs/url/B8jEh3NR3oun7zu1uK9agD7y2ootHmjnfof6bJ-JDla00000

* [12:35] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-31-16.03.html
* [12:35] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-31-16.03.txt
* [12:35] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-31-16.03.log.html

[[march-24th-2015---odl-message-bus-overview]]
==== March 24th, 2015 - ODL Message Bus Overview

Andrew / Tony / Robert went over the Message Bus that was pushed back in
January

Recording:
https://meetings.webex.com/collabs/url/ZEnV2s_OxJUZzstqbQzr6Xtl9B8iVxgYpk_8PojuaaC00000

* [13:37] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-24-16.01.html
* [13:37] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-24-16.01.txt
* [13:37] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-24-16.01.log.html

[[march-17th-2015---status-update-on-md-sal-related-work]]
==== March 17th, 2015 - Status Update on MD-SAL Related Work

Went over the "Queries" on this page - looked out changes in bug reports
and pending changes to code. Sparked conversations on adding bug ID's,
patch sizes and communication methods.

Major Change Groups:

Recording:
https://meetings.webex.com/collabs/url/GYVgjsIp5SoVGt3zjyUAWp1j5-Jv-zt_XMFhFdYZUBa00000

* Clustering - number of new bugs opened /updated and some resolved
bugs. Number of patches pending.
* Some pending changes to yang constraint validation (pending the added
ability to make it optional)
* Some rest conf improvements

* [12:50] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-17-16.01.html
* [12:50] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-17-16.01.txt
* [12:50] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-17-16.01.log.html

[[march-10th-2015---status-update-on-md-sal-related-work]]
==== March 10th, 2015 - Status Update on MD-SAL Related Work

* Andrew M will present the "message bus" (needs better name per Robert
/ Andrew ).

* ** No notes captured - message bus presentation will be on 3/24

[[march-3rd-2015---status-update-on-md-sal-related-work]]
==== March 3rd, 2015 - Status Update on MD-SAL Related Work

[12:28] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-03-16.59.html
[12:28] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-03-16.59.txt
[12:28] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2015-03-03-16.59.log.html

[[february-24th-2015---netconf-and-md-sal-spin-out-project-proposals]]
==== February 24th, 2015 - NETCONF and MD-SAL Spin Out Project Proposals

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest/opendaylight-meeting-md_sal_interest.2015-02-24-17.04.html[IRC
Minutes]
* :File:MD-SAL-Weeky-Controller_spin-off.pptx[Slides]
* WebEx Recording

[[janurary-20th-2015---binding-aware-serialization-layer-for-md-sal]]
==== Janurary 20th, 2015 - binding aware serialization layer for MD-SAL

Sharon Aicler presented a binding aware serialization layer for MD-SAL -
e.g. taking a MD-SAL generated java interface model instance and
translating it to a bunch of bytes and back...

Meet Bot was not working - full conversation cut and paste below.

[12:09] #info Sharon Aicler describes the binding used by the
sal-persisted-dom-test [12:09] tbachman: it's the same bot, it just sits
in a lot of channels ;) [12:10] :) [12:10] * tbachman tries to catch up
to the presentation [12:12] #info Sharon shows the PojoObject test,
where there’s a member that’s a sub-element of the PojoObject; the
serializer uses reflection to look at all the get methods on the object,
and if they don’t contain any arguments, it refers to them as properties
that need to be serialized and asks them to do their own serialization
[12:12] #info If the object is something not native to Java, it will
create a serializer for it [12:13] #info the generated serializer
converts everything to a bunch of bytes, and goes to the sub-element to
add the bunch of bytes to the original stream of bytes; this leaves you
with a set of bytes that describes a single object [12:15] #info the
byte array also contains an encoder [12:17] #info You can specify the
object class to the encoder to do things such as encoding using a
superclass for something that’s a derived class [12:25] * tbachman is
terrible at multitasking [12:30] #info pantelis says there’s a javabeans
class that can do the bean introspect on a class and will return all the
property descriptors [12:31] #info ttkacik says the yang binding has a
binding reflections class that also provides these convenience functions
[12:33] * mestery has quit (Remote host closed the connection) [12:34] *
mestery (~mestery@12.130.116.223) has joined #opendaylight-meeting
[12:45] * sdean778 (deanste@nat/hp/x-qlcftuammbzeovnm) has joined
#opendaylight-meeting [12:50] #info devinavery asks Sharon for a higher
level picture with the serializer/deserializer [12:51] * mestery has
quit (Max SendQ exceeded) [12:51] #info moizr asks how the datastore
would handle restconf [12:51] #info Sharon says he hasn’t created
RESTCONF for this datastore yet [12:52] #info Sharon says they have a
“collector”, which is an external JVM, which will eventually pass this
data to the controller [12:53] * mestery (~mestery@12.130.116.223) has
joined #opendaylight-meeting [12:56] * xsited has quit (Quit: Leaving.)
[13:03] * colindixon (ckd@nat/hp/x-hupewdrtjytxasfv) has joined
#opendaylight-meeting [13:03] #stopmeeting

[[janurary-6th-2015]]
==== Janurary 6th, 2015

Due to lack of attendance tabling topics until next week so we can have
a larger audience (many folks in Europe still on holiday).

[12:07] Meeting ended Tue Jan 6 17:07:53 2015 UTC. Information about
MeetBot at http://ci.openstack.org/meetbot.html . (v 0.1.4) [12:07]
Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest/opendaylight-meeting-md_sal_interest.2015-01-06-17.01.html
[12:07] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest/opendaylight-meeting-md_sal_interest.2015-01-06-17.01.txt
[12:07] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_interest/opendaylight-meeting-md_sal_interest.2015-01-06-17.01.log.html

[[october-14th-2014---documentation-efforts-searching-md-sal]]
==== October 14th, 2014 - Documentation Efforts & Searching MD-SAL

Only 6 people showed up, so canceled meeting. Do we still want to
continue to have this meeting? How is it different than the TWS call on
Mondays?

[12:07] Meeting ended Tue Oct 14 16:07:18 2014 UTC. Information about
MeetBot at http://ci.openstack.org/meetbot.html . (v 0.1.4) [12:07]
Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-14-16.00.html
[12:07] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-14-16.00.txt
[12:07] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-14-16.00.log.html

[[october-7th-2014---moving-forward-how-to-make-md-sal]]
==== October 7th, 2014 - Moving Forward, how to make MD-SAL

Gave a quick overview of what the next steps we are taking in making
MD-SAL easier to use.

Meeting ended Early

Recording:
https://meetings.webex.com/collabs/url/XmX7sfSfEl-wI9pI-QJTji8ZTahttHuoH3C8VmOvvse00000

[12:12] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-07-16.03.html
[12:12] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-07-16.03.txt
[12:12] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-10-07-16.03.log.html

[[helium]]
== Helium

[[september-23rd-2014---canceled]]
==== September 23rd, 2014 - Canceled

Meeting was cancelled due to lack of interest. Next meeting is on
October 7th.

[[september-16th-2014---no-status-no-questions---ended-early]]
==== September 16th, 2014 - No Status, No Questions - Ended Early

* Status Update
* Bug on MD-SAL about setting MAC address in actions

New Functionality (or anything you think people should know about):

* Nothing New.

IRC Notes:

* [12:11] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-16-16.03.html
* [12:11] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-16-16.03.txt
* [12:11] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-16-16.03.log.html

Recording: TBD

[[september-9th-2014---network-topology-modeling-discussion-bug-reporting-bugzilla-overview---wild-card-queries]]
==== September 9th, 2014 - Network Topology Modeling Discussion, Bug
Reporting / BugZilla Overview - Wild Card Queries

* Status Update
* Recap / Continued discussion on Modeling Network Topologies - Ramkumar
is the owner
* Bug Reporting / Bug Fixing -
https://wiki.opendaylight.org/view/OpenDaylight_Bugs

Questions:

* Wild Card Queries in MD-SAL

New Functionality (or anything you think people should know about):

* Thomas Bachman - sent mail to list as well, but the osgi distribution
builds at runtime will have a lot of errors now. Karaf @ runtime should
not have those errors as that is the supported release mechanism going
forward.

IRC Notes:

* [12:58] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-09-16.05.html
* [12:58] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-09-16.05.txt
* [12:58] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-09-16.05.log.html

Recording:
https://meetings.webex.com/collabs/url/iJ8avNqAhoL7et_2JcNz5gdxpQE82OJq-3HyaM7LfSC00000

[[september-2nd-2014---topics-for-sept-design-forum-jmx-stats]]
==== September 2nd, 2014 - Topics for Sept Design Forum, JMX Stats

* Status Update
*
https://lists.opendaylight.org/pipermail/controller-dev/2014-August/006371.html

* Topics for September Design Forum?
** Clustering, messaging
*** Helium How to we use it for day-to-day-use etc. ie Clustering 101
*** Lithium and beyond design session for clustering (others want to
work on this)
** Brain storming binding specifications (Colin D to find a wiki page)
***
https://wiki.opendaylight.org/view/YANG_Tools:Design:Binding_Specification_v2_Analysis
*** Bug 1411
** Config Subsystem -
*** Introduction to basic use, and then how to extend with own classes.
*** How to find what already exists in the config subsystem and what I
need to register again.
*** What can we do in Lithium to make it easier to use.
** Modeling - Network Topology
*** How to model and represent heterogeneous network topology
*** Extends to services as well - how are we going to manage multiple
topologies
*** How is the northbound view of the underlying networks composed and
maintained?
** Modeling - How do we build common models so multiple applications can
use it?
*** There is a sense that "Everyone is building their own models"

* Tom P - show the JMX Stats for the MD-SAL

New Functionality / Bug Fixes / Anything to tell community about :

* Write out codec to restconf that are more efficient - removes any
internal representation of the data - still a few integration problems,
but bug fixes are ready and are just waiting on verify job to be merged.

Questions: None

IRC Notes: [13:01] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-02-16.06.html
[13:01] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-02-16.06.txt
[13:01] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-09-02-16.06.log.html

Recording:
https://meetings.webex.com/collabs/url/PilwL2Wsej7TLFOs1_PlrdyauU4sUPh3FeLzPxjIbJG00000

[[august-26th-2014---yang-testing-question-karaf-features-discussion]]
==== August 26th, 2014 - Yang Testing Question, Karaf Features
Discussion

Status Update (New things in the MD-SAL since last time): Yang Testing
Question

New Functionality: ...nothing exciting...

* Jan is requesting stats on MD-SAL - how to plug them in and how to use
them.
** Tom P has the stats prototyped and waiting to be merged - Need to
merge changes (yangtools - 9837, controller 9797 ) then Tom P to demo
next week

Questions:

IRC Notes:

* [12:59] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-26-16.18.html
* [12:59] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-26-16.18.txt
* [12:59] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-26-16.18.log.html

Recording:
https://meetings.webex.com/collabs/url/WU1OmIGb4xGZqrYZNYiJPI5YBUoHbss7tP7Bc_vOG-W00000

[[august-19th-2014---karaf-features]]
==== August 19th, 2014 - Karaf Features

Status Update (New things in the MD-SAL since last time): Karaf Features
(Ed Presents) Questions from the Community

New Functionality: ...nothing exciting...

Questions:

IRC Notes: [12:58] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-19-16.09.html
[12:58] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-19-16.09.txt
[12:58] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-19-16.09.log.html

Recording:
https://meetings.webex.com/collabs/url/iQwZek9VnWd-drth6U-FZueD2wPy9ABlKh7VcXr9UiK00000

[[august-12th-2014]]
==== August 12th, 2014

Status Update (New things in the MD-SAL since last time): Question on
Swagger UI Usability - Gerrit 9068 Questions:

* Errors when you build anything about duplicate version of the same
name space
* Builders for Unions

Upcoming:

* Focusing on Testing and bug fixes now that API freeze has passed.
* SchemaContext scalability (Yangtools parts are there, but there may be
some bugs (related to netconf client). More investigation tomorrow.
** Trying to make storing schemas more efficient, in particular with
duplicate versions of the same schema
* DataObject to XML / JSON put on hold since there was a lot of work
coming from Tony to make this easy.
** Dependent codecs have been pushed to yangtools. There are some
patches in the pipeline.

Questions:

IRC Notes: [12:53] Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-12-16.03.html
[12:53] Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-12-16.03.txt
[12:53] Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-12-16.03.log.html

Recording:
https://meetings.webex.com/collabs/url/9kHPnIdPb0EkNpa_6uO-t9w7exXkw3XGAlaOcipvkZq00000

[[august-5th-2014]]
==== August 5th, 2014

Status Update (New things in the MD-SAL since last time):

* Snippets of YANG in generated classes.
** https://git.opendaylight.org/gerrit/#/c/9144/
* CompositeNode has been deprecated. It is now NormalizedNode.
** Plan is to eliminate them in the Lithium time-frame.
** DataNormalizer class which will translate between CompositeNode and
NormalizedNode.
** General use is described in:
OpenDaylight Controller:MD-SAL:Design:Normalized DOM Model[OpenDaylight
Controller:MD-SAL:Design:Normalized DOM Model]
** netconf-connector and restconf-connector now use the new APIs and
NormalizedNode (but still use codecs that go through CompositeNode)
* added binding-data-codec
** https://git.opendaylight.org/gerrit/#/c/9496/
** will provide direct translation between NormalizedNode and DataObject
** this was created because benchmarking write-heavy workloads to the
MD-SAL showed that multiple conversions using lots of resources
** the new version should be faster, also easier because it goes
straight from JSON to/from DataObject
** The plan is to move to using these codecs in restconf and binding
connectors by M5
*** netconf is also planned, but slip past Helium

Upcoming:

* SchemaContext scalability
** Trying to make storing schemas more efficient, in particular with
duplicate versions of the same schema

Questions:

* Brent ask what's going on with automatically creating the path for
nodes
** You can now have puts create parents, but you need to explicitly ask
for this behavior, default is to not
** Legacy API behaves as before, i.e., it creates parents
** When you delete a node it deletes the whole subtree
* Flavio says that while he's running tests, he's seeing lots of
somewhat odd looking logs
** https://gist.github.com/anonymous/3a4ac3907c45049c6789
** This is the stats manager trying to write data into flows that aren't
there
** It would be nice if there was a way to stop logs of a badly behaving
while we work on things

MD-SAL Clustering Demo:

* See the IRC notes below.

IRC Notes:

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-08-05-16.12.html

[[july-22nd-2014]]
==== July 22nd, 2014

Agenda:

* Status Update
* Start discussions on how we want to "standardize" models in ODL.
[Tabled for today]
** An extremely light weight review body?
** Add certain people as reviewers to gerritts that change yang models?
** How do we keep this from being an impedance to getting things done?
** Their purpose: review and discuss models, provide suggestions when
two models are close to eachother.
* Discuss proposal to change behavior of generated builders.

---------------------------------------------------------------------------------------------------------------
Hi,
 We have proposal and bugfix ready for bug 1097 (https://bugs.opendaylight.org/show_bug.cgi?id=1097)
 in YANGTools, but This one changes behaviour in generated builders and DTOs in such way,
 that if you have getter for List of items, it will allways return non-null value,  even if 
 user specified null for list.
  
 This means users of DTOs can not use null value to signallize there is no list present (which may be different
 then List is empty). There are some projects, which uses these DTOs also for protocol libraries and so 
 on, and we want to know from the community point of view, if we want to have non-null lists 
 or possibility to use also nulls.
 
 Tony
---------------------------------------------------------------------------------------------------------------

* Wojciech - seeing a need to change the restconf implementation and
some aspects on how it is set up.

*What was Done:*

* commit API was changed to a "CheckedFuture" and renamed to "submit".
Toaster was updated with this example.

*What will be done (Whats planned):*

* [Colin D] Build DataObject <-> XML/JSON (focusing on DataObject->JSON)
- hoping it will be done by the end of the week.
* auto-create parents when putting a child into databroker.
(https://git.opendaylight.org/gerrit/#/c/8736/)

* '''Recording: ''' -
https://meetings.webex.com/collabs/url/jtRO3Mh1oDWerF-xznqRmxjAKfJcvhWXtYFc2SziZVG00000

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-07-22-16.07.html
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-07-22-16.07.txt
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_interest_call/opendaylight-meeting-md_sal_interest_call.2014-07-22-16.07.log.html

[[july-15th-2014]]
==== July 15th, 2014

Agenda:

* Status Update - 15 minutes

*What was Done:*

* Toaster example was updated with "proper" async programming code
samples.

*What will be done (Whats planned):*

* Tom Pantelis - Write Transaction API - we are changing the commit
method so that it does return any error - all error conditions will go
through exceptions. Deprecating the commit() and will add a method
called "ready()"
** Simplifies how you would check if the transaction was "successful"
* Tony - pushing a patch to allow MD-SAL to optionally create parents
* Read method - make it type safe so you don't have to case the response
manually.
* Clustering (On going) - need to bring Moiz back for an update (Check
IRC logs for links)
*
* '''Recording: ''' - coming

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call___july_15th__2014/opendaylight-meeting-md_sal_status_call___july_15th__2014.2014-07-15-16.14.html
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call___july_15th__2014/opendaylight-meeting-md_sal_status_call___july_15th__2014.2014-07-15-16.14.txt
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call___july_15th__2014/opendaylight-meeting-md_sal_status_call___july_15th__2014.2014-07-15-16.14.log.html

[[july-8th-2014]]
==== July 8th, 2014

Agenda:

* Status Update - 15 minutes
* [Owner: Harman Singh] Demo dLux UI? - 15 minutes (Tentative - may not
show today).
* [Owner: Devin Avery]: Demo the archtetype to get a MD-SAL project
started.

*What was Done:*

* MD-SAL Archetypes - number fixes delivered to master [Devin]
* Pushed some code to config subsystem for merging config references.
[Ed]
* A number of bug fixes to address issues with new data broker API.
[Tony]

` * Some are in review, merged and pending discussions.` +
` * Increasing test coverage on MD-SAL  `

*What will be done (Whats planned):*

* More bug fixes and usability enhancements on MD-SAL

* '''Recording: ''' - No Recording this week due to limitation with
concurrent licenses on Web-Ex.

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call/opendaylight-meeting-md_sal_status_call.2014-07-08-16.01.html
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call/opendaylight-meeting-md_sal_status_call.2014-07-08-16.01.txt
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_status_call/opendaylight-meeting-md_sal_status_call.2014-07-08-16.01.log.html

[[july-1st-2014]]
==== July 1st, 2014

Scheduled:

* Status Update - 15 minutes
* [Owner: Devin]: Demo the DataBrokerService apis via the toaster
example - 15 minutes
* [Owner: Harman Singh] Demo dLux UI? - 15 minutes (Tentative - may not
show today).
* [Owner: Moiz] Clustering Update - 15 minutes

*What was Done:*

* Renamed "BindingDataBroker" to just DataBroker -
https://git.opendaylight.org/gerrit/8338
* Documented the "DataBroker" APIs -
https://git.opendaylight.org/gerrit/8046
* Document the RPC related service APIs -
https://git.opendaylight.org/gerrit/8330
* Deprecate Old APIs ( with pointers to new APIs ) -
https://git.opendaylight.org/gerrit/8322
* Updated Toaster to use new APIs:
https://git.opendaylight.org/gerrit/8168
* Updated Notification Document ...
* Clustering work is on going (see update in middle of call)

*What will be done (Whats planned):*

* Archetype for generating a MD-SAL application - hope is this can help
simplify initial interations with config subsystem.

`    * A bunch of simple changes that make things easier. See `https://bugs.opendaylight.org/buglist.cgi?list_id=10140&product=toolkit&query_format=advanced&resolution[`https://bugs.opendaylight.org/buglist.cgi?list_id=10140&product=toolkit&query_format=advanced&resolution`]`=---` +

*Blocking Issues:*

* Toolkit who owns? - Harman, Madhu, Colin D...
* Question - why are archetypes not pushing to git repo? (Colin D to
look at)

*Other Topics:*

* '''Recording: ''' TBD

* *Minutes*
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-07-01-16.03.html[minutes
(html)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-07-01-16.03.txt[minutes
(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-07-01-16.03.log.html[log]

[[june-24th-2014]]
==== June 24th, 2014

Scheduled:

* Status Update - 15 minutes
** Review config vs operational attributes and how they relate to data
stores
** Review DataBroker documented APIs, updated Toaster
** Run through comments on BindingAware Consumer/Provider

*What was Done:*

* Documented DataBroker interfaces, and also updated the Toaster example
to leverage the DataBroker interfaces (toaster example is merge pending)
* Cleaned up pom files, moving versioning up to variables in the parent
pom.xml
* Clustering - lots of patches are coming in.
* Removed a duplicate "Node" yang file that added one of the many
"Node.class" which made things confusing

*What will be done (Whats planned):*

* Add extensive documentation to RPC & Notification classes
* Update the yang generation to add more comments into the generated
java files
* Commented the opendaylight-inventory.yang file with extensive usage
comments (Ramkumar to look at)

*Blocking Issues:*

* [Colin] A future discussion might be nice around how much we want /
need to expose the yang to developers (Agenda item for next week - What
should be done in Java vs in Yang? What should you be able to understand
from Java without looking at Yang?)

*Other Topics:*

* Sharon - new API - SQL API to the yang datastore ( would like to
present next week)
* Existing Bug - Prevent operational only attributes to be written to
config datastore. https://bugs.opendaylight.org/show_bug.cgi?id=1014

* '''Recording: ''' -
https://meetings.webex.com/collabs/url/hlz-ZP08VfcS2bsgN1lMCN9X8eWcpIXnvrTligqqqFG00000

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-06-24-16.05.html +
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-06-24-16.05.txt +
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_meeting/opendaylight-meeting-md_sal_meeting.2014-06-24-16.05.log.html

[[june-17th-2014]]
==== June 17th, 2014

Scheduled:

* Status Update - 15 minutes
* Krish – Discussing how to have a consumer/producer defined in the same
model (Krish – please come prepared to share your code and show some
code to level set folks)
* Ed – Concrete MD-SAL Usability improvement.

*What was Done:*

* Clustering patches for datastore are starting to merge into master
(coming in in small chunks)

*What will be done (Whats planned):*

* Start making usability enhancements to MD-SAL - start small iterate.
[Devin]
* Restconf Swagger Documentation that show MountPoints, and a number of
other enhancements [Devin] - patch set 8038
* Restconf Depth parameter -
https://git.opendaylight.org/gerrit/#/c/5325/
* sql API on top of MD-SAL - 7197 - interesting approach to how we might
be able to put a query mechanism on top.

*Blocking Issues:* None

*Other Topics:* None

* '''Recording: '''

No recording this week since we didn't have host reclaim key. :( Next
week I hope to fix that.

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_call/opendaylight-meeting-md_sal_call.2014-06-17-16.06.html +
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_call/opendaylight-meeting-md_sal_call.2014-06-17-16.06.txt +
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_call/opendaylight-meeting-md_sal_call.2014-06-17-16.06.log.html

[[june-3nd-2014]]
==== June 3nd, 2014

Scheduled:

* Status Update - 15 minutes
* Bug Scrub - Remainder of the time. [ This didn't work out - if you
have specific items which need debate please bring it up. If you would
like to contribute, please select a bug that sounds interesting and send
a mail asking for help if needed. ]
* Ed W. asked for a follow-up on M2 MD-SAL goals.

*What was Done:*

* Datastore performance improvements (multiple patches, being submitted
as we go) - restructures the data store for clarity. (Robert Varga)
* Bug 1120 - binding independent notification completely lock free and
most of the time doesn't allocate any objects. (Robert)
* Bug 724 - Hashcode Equals in Instance Identifier (Tom P)
* Merged issue that resolves problem with whitespace in RPC call input
(Tom P)
* Xtend code was removed from a number of places

*What will be done (Whats planned):*

*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Architecture:Clustered_Data_Store
(https://bugs.opendaylight.org/show_bug.cgi?id=1052)

`  - continuing with proof of concept work. Would like to demo something next week (Moiz)`

* Introduction of transaction chaining (Tony) - patches are in

` - In code review. Merge depends on other committers.`

* Xtend code is slowly being removed from a number of places.

* On going - documenting yangtools and md-sal API - documenting one
package a day (Tony) Look up api-clarity topic of gerrit patches to find
this documentation.
* working on a jquery style interface into MD-SAL - ability to do faster
/ lookups on dom tree -colindixon - working with intern neil_b
* new regression test suite which will contain new models which will
help with tricky testing situations - augmentation etc. ( Martin V. )
Patches on code review.

*Blocking Issues:*

* Waiting on getting code merged to main - [ Tom P to add lists ]

`  - What do we need to do to get code committer?` +
`       - Assign a committer to review the issue once you are done - that way committer can see it listed in their "changes".` +
`       - Who is actively committing MD-SAL code to Controller? Tony, Ed Warnicke, Rob Varga         -  YangTools? RobVarga, Tony` +
`  - Proposal: Stick a "DO NOT MERGE" in front of patch that is not ready to be looked at.  `

*Other Topics:* None

* '''Recording: '''

No recording of last week.

* *Minutes*

Minutes:
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_md_sal_call/opendaylight-meeting-weekly_md_sal_call.2014-06-03-16.06.html
Minutes (text):
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_md_sal_call/opendaylight-meeting-weekly_md_sal_call.2014-06-03-16.06.txt
Log:
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_md_sal_call/opendaylight-meeting-weekly_md_sal_call.2014-06-03-16.06.log.html

[[may-27th-2014]]
==== May 27th, 2014

Scheduled:

* Status Update - 15 minutes
** What do we complete last week?
** What are we planning to complete this week?
** Are you blocked (need help) on anything? (helps if you open an
ask.opendaylight.com question if you are blocked so we can track)
* Demo the Akka Clustering Prototype (Moiz) - 40 Minutes

*What was Done:*

* ietf-restconf (/modules and /streams) (Devin Avery)
* Bug 990, where enum types are not getting translated between binding
aware / binding independent correctly - Martin is looking at these
issues – The fix was merged just before the call. - Martin Bobak
* Datastore performance improvements (multiple patches, being submitted
as we go) - restructures the data store for clarity. (Robert Varga)
\{some merged in, more to come}
* Bug 1010 - Return from Restconf the errors as defined in the ieft
draft (Tom Pantelis)
* Netconf connector – return the netconf errors back in the rpc result
(allow the RPC errors to be passed through). (Tom Pantelis)
* waiting on a parent patch.

*What will be done (Whats planned):*

* Datastore performance improvements (multiple patches, being submitted
as we go) - restructures the data store for clarity. (Robert Varga)
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Architecture:Clustered_Data_Store
(https://bugs.opendaylight.org/show_bug.cgi?id=1052)
* Introduction of transaction chaining (Tony) - patches are in
* On going - documenting yangtools and md-sal API - documenting one
package a day (Tony) Look up api-clarity topic of gerrit patches to find
this documentation.
* working on a jquery style interface into MD-SAL - ability to do faster
/ lookups on dom tree -colindixon - working with intern neil_b
* new regression test suite which will contain new models which will
help with tricky testing situations - augmentation etc. ( Martin V. )

*Blocking Issues:*

*
https://ask.opendaylight.org/question/99/how-does-request-routing-works/
[Need confirmation that underlying issue was resolved] - Tony will
follow
* If you have two different vendors, and you want to create a vlan, the
consumer will issue the same command, how does it get routed to the
correct plug based on the node. Is there some flag? -Tony and Shoaib
will follow-up off line - [Need to confirm that this issue is resolved]
* Request to do a bug triage to see what bugs are valid, need to be
worked etc [Triage / bug scrub] - proposal to have a scrub next week

*Other Topics:* "What is preventing from using MD-SAL?" -

` * Survey Monkey? ` +
` * Need to figure out who is willing to work on stuff?` +
` * Some items should be discussed. Statement of work for an item may change after we discuss (particular performance).` +
` * Suggest opening a bug zilla ticket for each item in the list so we can discuss them in detail and track discussion [ unless someone objects ]` +
`      * Ask.opendaylight.org ( or something similar?)` +
`      * example: scala discussion - open as bug or on the mailing list? No "bug" associated, so different problem.`

* '''Recording: '''

https://meetings.webex.com/collabs/url/eDAvgQyS3hPw7JmZdIL2M6KwVmKRY-iSdr_NGzFQzcO00000

* *Minutes*
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_call/opendaylight-meeting-md_sal_weekly_call.2014-05-27-16.05.html[HTML]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_call/opendaylight-meeting-md_sal_weekly_call.2014-05-27-16.05.txt[Test]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_call/opendaylight-meeting-md_sal_weekly_call.2014-05-27-16.05.log.html[Log]

[[may-20th-2014]]
==== May 20th, 2014

*What was Done:*
https://docs.google.com/spreadsheets/d/1O5PxEM1eLszMuWf9M11AD5w7siT9vHOkzR85gjCB-6c/edit#gid=322436364

* Call mounted RPC calls via RestConf
* Binding Aware builders have been improved in terms of memory
efficiency ( should be 48 bytes less)
* Stability issues and correctness issues fixed over last week – some
coming from openFlow plugins
* 100% testing all OF13 integration tests

*What will be done (Whats planned):*

* Bug 1010 - Return from Restconf the errors as defined in the ieft
draft (Tom Pantelis)
* ietf-restconf (/modules and /streams) (Devin Avery)
* Netconf connector – return the netconf errors back in the rpc result
(allow the RPC errors to be passed through). (Tom Pantelis)
* waiting on a parent patch.
* Bug 990, where enum types are not getting translated between binding
aware / binding independent correctly - Martin is looking at these
issues – The fix was merged just before the call. - Martin Bobak
* Datastore performance improvements (multiple patches, being submitted
as we go) - restructures the data store for clarity. (Robert Varga)
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Architecture:Clustered_Data_Store
(https://bugs.opendaylight.org/show_bug.cgi?id=1052)

*Blocking Issues:*

*
https://ask.opendaylight.org/question/99/how-does-request-routing-works/
- Tony will follow
* If you have two different vendors, and you want to create a vlan, the
consumer will issue the same command, how does it get routed to the
correct plug based on the node. Is there some flag? -Tony and Shoaib
will follow-up off line

*Other Topics:* Any thing else big coming down the pipe?

* Clusting MD-SAL (How, when, architecture etc) - (Jake Samash) – Akka
clusting, rest api’s, clustered data store.
* Also clustering the features, so we could provide a registered OSGI
service, and then deploy different features to different nodes and
potentially cluster the controller.

[[may-6-2014-infinispan-in-memory-data-store-prototype]]
==== May 6, 2014: Infinispan In-Memory Data Store Prototype

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=ee9b23edb5fd449da213d7f3a83e2042[WebExRecording]
* OpenDaylight_Controller:MD-SAL:The Infinispan Data Store[Prototype
wiki]
* https://git.opendaylight.org/gerrit/#/c/5900/[Prototype code]

[[april-29-2014-inocybe-dat-store-update-md-sal-archetype-resctonf-tool]]
==== April 29, 2014: Inocybe dat store update, MD-SAL Archetype,
RESCTONF Tool

*
https:///cisco.webex.com/ciscosales/lsr.php?RCID=0e025c295c004d238f3c3a016b8c3318[WebEx
Recording]

[[april-22-2014-karaf-container]]
==== April 22, 2014: Karaf Container

*
https://cisco.webex.com/ciscosales/lsr.php?RCID=ea008e89723b4f0fa64204d78d5a5146[WebEx
Recording]

[[april-15-2014-apic-presentation-part-ii]]
==== April 15, 2014: APIC Presentation Part II

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=108032230c024db6b4d037f6d1fda5e1[WebEx
Recording]
* *Notes from Part I (TWS Call on April 4, 2014):*
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.txt[Minutes
(text)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.log.html[Log]
* *Presentation*:
image:APIC Presentation 04-13-2014.pdf[APIC Presentation 04-13-2014.pdf,title="fig:APIC Presentation 04-13-2014.pdf"]

[[april-8-2014-md-sal-akka-prototype]]
==== April 8, 2014: MD-SAL Akka Prototype

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=8a19ade66f0f49daaae57886e3305af2[WebEx
Recording]
* *Presentation*:
image:MD-SAL Akka Prototype.pdf[MD-SAL Akka Prototype.pdf,title="fig:MD-SAL Akka Prototype.pdf"]

[[april-1-2014-data-store-performance-improvements-demo]]
==== April 1, 2014: Data Store Performance Improvements Demo

*
https://cisco.webex.com/ciscosales/lsr.php?RCID=43af95c195404d10bba1f57a63049f1a%20[WebEx
recording]

