[[overview]]
== Overview

This page contains a summary of the OpenDaylight meetings. Some are for
projects, others are for committees.

Meetings are typically held via a combination of these tools:

* IRC, either Freenode/#opendaylight-meeting or a project-specific
channel
* Google Hangouts
* Webex

[[other-resources]]
== Other Resources

[[project-specific-wikis]]
=== Project-specific wikis

Many projects maintain their own wikis for their meeting info. They
typically contain information about the meeting time, how to connect and
a log of meeting minutes. Those wikis should be considered more
authoritative than this aggregate wiki. If you're having problems with a
Webex link, check the project's meeting wiki and/or their IRC channel
for an updated one.

[[google-calendar]]
=== Google Calendar

The information on this page is aggregated in a Google Calendar, which
some people may find to be a more consumable format. Here's a
http://www.google.com/calendar/embed?src=aDc5aGltYm9rcThhYXVyOWxlZDhvYzc5MGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ[direct
link], here's an
https://www.google.com/calendar/ical/h79himbokq8aaur9led8oc790g%40group.calendar.google.com/public/basic.ics[iCal-format
link] and here's an
https://www.google.com/calendar/feeds/h79himbokq8aaur9led8oc790g%40group.calendar.google.com/public/basic[XML-format
link]. Following the direct link, then clicking on the small button at
the bottom right corner of the page seems to be a method that works for
most people. This wiki, and by extension the project-specific wikis,
should be considered more authoritative than the Google Calendar.

If there's an error with the Google Calendar, please contact Daniel
Farrell (dfarrell07 on Freenode/#opendaylight, dfarrell@redhat.com).

[[time-representation-explanation]]
== Time Representation Explanation

For better or worse, many meeting times are pegged to a given time in a
given location. This implies that the meeting time in UTC will change
when that base location transitions between Daylight and Savings time.
Currently, all such meetings are pegged to the US, which is currently in
Standard Time and will be until November 2nd 2014. *If you're reading
this before that date, use the Standard Time UTC value, else use the
Daylight Time value and update this wiki*. For example, Bonnie in the
Western US will always see 10AM on her phone when the TSC meeting
starts, but Clyde in Eastern China will need to add 8 to the UTC time
appropriate for the current date.

In general, to translate a UTC meeting time into your local time issue
the `timedatectl status` command in a Linux shell, then add/subtract the
timezone offset it gives you from the appropriate Daylight/Standard UTC
meeting time to derive the meeting time in your location's notation.

Note that UTC is always written in 24-hour format, and that this wiki
expresses all times in 24-hour format.

[[tsc]]
== TSC

* Weekly on Thursday from 10:00-11:00 PST/PDT | 13:00-14:00 EST/EDT |
17:00-18:00 UTC during Daylight Time/18:00-19:00 UTC during Standard
Time
* Note that TSC meetings sometime last 2 hours, sometimes 1. Depends on
the schedule for the week.
**
https://meetings.webex.com/collabs/meetings/join?uuid=MA3SRND964PIX06V2LS3SXX3RE-9VIB[Webex
meeting link]
** Meeting number: 194 548 370
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-meeting
* Authoritative source and details: TSC:Main. Check this and IRC if the
Webex link is broken.

[[tws]]
== TWS

* Weekly on Monday at 10:00 PST/PDT | 13:00 EST/EDT | 17:00 UTC during
Daylight Time/18:00 UTC during Standard Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=M749G9M6E4A5JG72SD48WWG57F-9VIB[Webex
meeting link]
** Meeting Number: 196 592 514
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-meeting
* Authoritative source and details: Tech_Work_Stream:Main. Check this
and IRC if the Webex link is broken.

[[ovsdb-plugin-network-virtualization-project]]
== OVSDB Plugin / Network Virtualization Project

* Weekly on Tuesday from 12:00-13:00 PST/PDT | 15:00-16:00 EST/EDT |
19:00-20:00 UTC during Daylight Time/20:00-21:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MBEJOM1CNOV3D3YXNTHITWGVNZ-9VIB&rnd=199048.03614[Webex
meeting link]
** Meeting Number: 196 498 415
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-ovsdb
* Authoritative source and details:
OVSDB_Integration:Main#Weekly_OVSDB_Plugin_Meeting_.28Open_to_All.29[OVSDB
Plugin Project Weekly Meeting]. Check this and IRC if the Webex link is
broken.

[[dlux]]
== DLUX

* Weekly on Thursday from 09:00-10:00 PST/PDT | 12:00-13:00 EST/EDT |
16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during Standard
Time
**
https://plus.google.com/hangouts/_/calendar/aHBzc2FobmlAZ21haWwuY29t.pdq7ta4ud3uveuaf00bt47ubk0[Google
Hangout link]
** IRC: Freenode/#opendaylight-dlux
* Authoritative source: IRC, as there's no project-specific meeting
wiki.

[[group-based-policy]]
== Group Based Policy

* Group_Policy:Sub-Groups:STATUS#Team_Meeting[Meeting information]

[[md-sal]]
== MD-SAL

* Weekly on Tuesday from 09:00-10:00 PST/PDT | 12:00-13:00 EST/EDT |
16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MCQK23GTHZNO7LDV6UWT6KLYPV-9VIB&rnd=497132.35684[Webex
meeting link]
** Meeting Number: 194 764 014
** Meeting password: This meeting does not require a password.
** Host key: 720589. Use this key in the meeting if you have made
someone else the host and then want to reclaim the host role.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-meeting
* Authoritative source and details: link:MD-SAL Weekly Call[MD-SAL
Weekly Call]. Check this and IRC if the Webex link is broken.

[[md-sal-hackers]]
== MD-SAL Hackers

* Weekly on Tuesday from 08:00-9:00 PST/PDT | 11:00-12:00 EST/EDT |
15:00-16:00 UTC during Daylight Time/16:00-17:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MCT85SFEJTE5WAJSEMK35OXSR9-9VIB&rnd=134434.93272[Webex
meeting link]
** Meeting Number: 191 442 342
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-meeting
* Authoritative source:
OpenDaylight_Controller:MD-SAL#MD-SAL_Hackers_Weekly_Call. Check this
and IRC if the Webex link is broken.

[[clustering-hackers]]
== Clustering Hackers

* Weekly on Tuesday from 08:00-9:00 PST/PDT | 11:00-12:00 EST/EDT |
15:00-16:00 UTC during Daylight Time/16:00-17:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/meetings/join?uuid=MALTOMIMY5WPSZORCBFJSNI22V-9VIB[Webex
meeting link]
** Meeting Number: 206 041 896
** Call-in toll-free number (US/Canada): 1-866-432-9903
** Call-in toll number (US/Canada): 1-408-525-6800
** IRC: Freenode/#opendaylight-clustering
** Authoritative source:
OpenDaylight Controller:MD-SAL-Clustering#Hackers_Meeting[OpenDaylight
Controller:MD-SAL-Clustering#Hackers_Meeting]. Check this and IRC if the
Webex link is broken

[[aaa]]
== AAA

* Weekly on Thursday from 09:00-10:00 PST/PDT | 12:00-13:00 EST/EDT |
16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during Standard
Time
**
https://cisco.webex.com/cisco/j.php?MTID=m8c9760bd2a68fa805ba2103821e5ee75[Webex
meeting link]]
** IRC: freenode.net #opendaylight-aaa
* Authoritative source: AAA:Main#Meetings_.28open_to_all.29[AAA Project
Weekly Meeting]

[[documentation]]
== Documentation

* Weekly on Wednesday at 08:00 PST/PDT | 11:00 EST/EDT | 15:00 UTC
during Daylight Time/16:00 UTC during Standard Time.
** Meeting URL:
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MEZ64MQAEG678HB95FQDDX9QER-9VIB&rnd=580672.24351
** Meeting Number: 195 651 551
** Call-in toll number (US/Canada): 1-650-479-3207
** Call-in toll-free number (US/Canada): 1-855-244-8681
** IRC: Freenode/#opendaylight-docs
* Authoritative source and details:
CrossProject:Documentation Group:Meetings[CrossProject:Documentation
Group:Meetings]. Check this and IRC if the Webex link is broken.

[[integration]]
== Integration

* Weekly on Thursday at 08:00 PST/PDT | 11:00 EST/EDT | 15:00 UTC during
Daylight Time/16:00 UTC during Standard Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=ME4A4AK1D71RUK0VCM1LSBW45C-9VIB&rnd=595405.44392[Webex
meeting link]
** Meeting Number: 190 637 318
** Meeting password: This meeting does not require a password.
** Host key: 955850. Use this key in the meeting if you have made
someone else the host and then want to reclaim the host role.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-integration
* Authoritative source and details:
CrossProject:Integration Group:Meetings[CrossProject:Integration
Group:Meetings]. Check this and IRC if the Webex link is broken.

[[lisp-flow-mapping]]
== LISP Flow Mapping

* Monthly on the first Tuesday of every month from 10:00-11:00 PST/PDT |
13:00-14:00 EST/EDT | 17:00-18:00 UTC during Daylight Time/18:00-19:00
UTC during Standard Time
** IRC: Freenode/#opendaylight-lispflowmapping
* This project doesn't seem to have a wiki for documenting meeting info,
so IRC and this page are the authoritative sources.

[[openflow-plugin]]
== OpenFlow Plugin

* Webex: Weekly on Mondays from 09:00-10:00 am PST/PDT | 12:00-1:00
EST/EDT | 16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during
Standard Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=M2D4SMAUPJLGFE395VGN2HU7M7-9VIB&rnd=180270.26196[Webex
meeting link]
** Meeting Number: 193 161 271
** Meeting password: This meeting does not require a password.
** Host key: 561881. Use this key in the meeting if you have made
someone else the host and then want to reclaim the host role.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode: #opendaylight-openflowplugin
* Authoritative source and details: OpenDaylight_OpenFlow_Plugin:Main.
Check this and IRC if the Webex link is broken.

[[opendaylight-security-analysis]]
== OpenDaylight Security Analysis

*This group isn't currently meeting, but they hope to start again fairly
soon (as of 6/16/2014).*

* Weekly on Friday from 08:30-09:30 PST/PDT | 11:30-12:30 EST/EDT |
15:30-16:30 UTC during Daylight Time/16:30-17:30 UTC during Standard
Time
**
https://cisco.webex.com/mw0401l/mywebex/default.do?service=1&siteurl=cisco&nomenu=true&main_url=%2Fmc0901l%2Fe.do%3Fsiteurl%3Dcisco%26AT%3DMI%26EventID%3D266170932%26UID%3D0%26Host%3D985c1f043f0a1f18%26FrameSet%3D2%26MTID%3Dm7204f855e3c37c2e098ebd9ef8101c41[Webex
meeting link]
** Meeting Number: 204 707 600
** Meeting password: security
** Call-in toll-free number (US/Canada): 1-866-432-9903
** Call-in toll number (US/Canada): 1-408-525-6800
** IRC: Freenode/#opendaylight-meeting
* Authoritative source and details:
CrossProject:OpenDaylight_Security_Analysis#Meeting_Notes. Check this
and IRC if the Webex link is broken.

[[service-function-chaining]]
== Service Function Chaining

* Weekly on Thursday from 09:00-09:30 PST/PDT | 12:00-12:30 EST/EDT |
16:00-16:30 UTC during Daylight Time/17:00-17:30 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=M4NGM5T0LCI1P9OKQQR10DMIRW-9VIB&rnd=515664.68103[Webex
meeting link]
** Meeting Number: 191 678 114
** Meeting password: odl
** Host key: 896113. Use this key in the meeting if you have made
someone else the host and then want to reclaim the host role.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode: #opendaylight-sfc

[[snmp-plugin]]
== SNMP Plugin

* Weekly on Wednesday from 10:00-11:00 PST/PDT | 13:00-14:00 EST/EDT |
17:00-18:00 UTC during Daylight Time/18:00-19:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/meetings/join?uuid=M9CIDR1B0LHMEK224U9I2BH19A-9VIB[Webex
meeting link]
** Meeting Number: 199 379 022
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-meeting

[[persistence-store-service]]
== Persistence Store Service

* Weekly on Wednesday from 09:00-10:00 PST/PDT | 12:00-13:00 EST/EDT |
16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/meetings/join?uuid=MALH0BTM0WALT9F31XVSIM8F4C-9VIB[Webex
meeting link]
** Meeting Number: 190 169 316
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-persistence
*** http://webchat.freenode.net/?channels=opendaylight-persistence
** Authoritative source: Persistence:Weekly_Meeting[Persistence Weekly
Meeting]

[[network-intent-composition-nic]]
== Network_Intent_Composition:Main[ Network Intent Composition (NIC) ]

* Weekly on Friday at 08:00 PST/PDT | 11:00 EST/EDT | 15:00 UTC during
Daylight Time/16:00 UTC during Standard Time
**
https://meetings.webex.com/collabs/meetings/join?uuid=M69T280MTV4WSJXDR9U8DB5CN2-9VIB[Webex
meeting link]
** Meeting Number: 199 413 454
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** Host Key: 466804
** IRC: Freenode/#opendaylight-nic

[[neutron-northbound]]
== NeutronNorthbound:Main[ Neutron Northbound ]

* Weekly on Friday at 08:00 PST/PDT | 11:00 EST/EDT | 15:00 UTC during
Daylight Time/16:00 UTC during Standard Time
** IRC meeting at Freenode/#opendaylight-neutron
* Authoritative source and details: NeutronNorthbound:Meetings.

[[maven-to-gradle-migration]]
== Maven to Gradle Migration

* Weekly on Wednesday from 09:00-10:00 AM PST/PDT | 12:00-13:00 EST/EDT
| 16:00-17:00 UTC during Daylight Time/17:00-18:00 UTC during Standard
Time
** https://connect18.uc.att.com/attinc5/meet/?ExEventID=82886027[AT&T
Connect meeting link (sorry, may require IE)]
** Meeting password: 2886027#
** Call-in toll-free number (US/Canada): 1-888-297-2353
** Call-in toll number (US/Canada): 1-646-364-1271

