This is also contained in the odcs/README file:

[[code-language]]
== Code Language

The Code is designed to run as a single process on a DOVE Service
Appliance or any Linux-based OS system. It's comprised of code written
in C and Python. The C code is compiled into a dynamically load(able)
library that can be invoked by the Python scripts. Each component on the
DCS is written in either C or Python.

The C/Python interaction is implemented using simple Extension and
Embedding Techniques. The Python libraries and header files needed to
compile the DCS is described in the README_PYTHON file.

[[code-structure]]
== Code Structure

Each folder in the code repository implements a specific functionality.

* init - Contains the initialization files and files for functionality
that was too simple to have a folder of its own for e.g. logging.
* inc - Contains all the header files that are used by all components
* fd_process - File descriptor processing routine. Currently implemented
using "poll" since the number descriptors are 2-3 but should be
converted to "epoll" at some time.
* client_server_protocol - The (currently) UDP based communication
channel between clients (DOVE Switches and Gateways) and the DCS.
* data_hander - Handles the run-time database of objects stored in the
DCS.

