1.  REDIRECT ODL_Coding_Guidelines

[[introduction]]
= Introduction

The OpenDaylight Java Style Guide is not yet defined. There is currently
discussion on the discuss mailing list.

[[requirements]]
= Requirements

The OpenDaylight Java Style Guide will enable developers to output code
that is consistent in style across project. This enhances readability
and also allows developers to contribute in each project without having
to change their code style.

* Code Style should be automatically enforced by the IDE and as a
compile-time check
* Code Repositories should be gated such that only commits that pass the
style-check are merged

[[proposal]]
= Proposal

The current proposal is hosted on
https://github.com/dave-tucker/opendaylight-java-guide/[GitHub]

* Elements that can be enforced with the
https://maven.apache.org/plugins/maven-checkstyle-plugin/[Maven
Checkstyle Plugin] will be checked at compile time
* Elements that cannot be enforce in Checkstyle will be enforced by the
IDE
** Code Style settings will be maintained for Eclipse and re-used in
IntelliJ via the http://plugins.jetbrains.com/plugin/6546[Eclipse Code
Formatter Plugin]
* Other elements, such as best practices should be manually vetted by
project committers

[[rollout]]
= Rollout

Style Checks will be introduced incrementally to avoid disruption

[[ci-integration]]
= CI Integration

It is recommended to use the
https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin[Jenkins
Checkstyle Plugin]

If it is decided to integrated
http://findbugs.sourceforge.net/[FindBugs] then it is also recommended
to use the accompanying
https://wiki.jenkins-ci.org/display/JENKINS/FindBugs+Plugin[Jenkins
Plugin]

[[current-votes]]
= Current Votes

https://docs.google.com/forms/d/1oA1a-n_y1frpeB0fPPx9xUUZrNDUTZ_KVeyGSgrZEBs/viewform?usp=send_form[Column
Width + Indentation]
