[[overview]]
= Overview

This Network Intent Composition project will enable the controller to
manage and direct network services and network resources based on
describing the “Intent” for network behaviours and network policies.
Intents are described to the controller through a new NorthBound
Interface, which provides generalized and abstracted policy semantics
instead of Openflow-like flow rules. The Intent based NBI allows for a
descriptive way to get what is desired from the infrastructure, unlike
the current SDN interfaces which are based on describing how to provide
different services. This NBI will accommodate orchestration services and
network and business oriented SDN applications, including OpenStack
Neutron, Service Function Chaining, and Group Based Policy. The Network
Intent Composition function will use existing OpenDaylight Network
Service Functions and Southbound Plug-ins to control both virtual and
physical network devices. The Network Intent Composer will be designed
to be protocol agnostic such that any control protocol can be used such
as Openflow, OVSDB, I2RS, Netconf, SNMP etc.

[[vtn-renderer]]
= VTN Renderer

VTN Renderer validates the corresponding subjects addresses, and passes
the intent to performs the respective actions between them. Each intent
has an Intent ID. If the Intent ID doesn't exist, it creates an ID and
the respective action is performed. If the ID is already exists and new
action is performed under that ID, then new action will be overwritten
the old action.

The VTN Renderer has three operations.

* Create
* Update
* Delete

[[subjects]]
== Subjects

The subjects are the IP addresses for the corresponding source and the
destination.

[[actions]]
== Actions

There are two actions

* Allow

::
  The communication between two hosts are enabled.

* Block

::
  The connection between two hosts are disabled.

*Note*:

* Multiple actions are not supported for now.
* VTN and vBridge are created for the very first intent request.

[[feature-overview]]
= Feature Overview

* *odl-nic-core* provides NIC core
* *odl-nic-console* provides NIC CLI
* *odl-nic-renderer-vtn* provides VTN Renderer

[[running-karaf-distribution]]
= Running Karaf distribution

* Move to the corresponding location.

::
---------------------------
cd nic/distribution/target/
---------------------------

* Unzip the file.

::
-----------------------------------------
tar -zxvf nic-karaf-1.0.0-SNAPSHOT.tar.gz
-----------------------------------------

* cd into the assembly directory.

::
------------
cd assembly/
------------

* To run the Karaf

::
-----------
./bin/karaf
-----------

* Once the console is up, type as below to install feature.

::
------------------------------------
feature:install odl-nic-renderer-vtn
------------------------------------

