[[engineering-network-traffic-with-opendaylight-packet-design]]
== Engineering network traffic with OpenDaylight: Packet Design

It is not easy to be aware of the current state of your network all the
time. Identifying network issues, seeing routing information and
monitoring network traffic to anticipate and react to network hot-spots
are all hard problems being attacked by Packet Design, an Austin-based
company with around 75 employees.

To help them solve these issues, the company has turned to OpenDaylight
to collect information and provision paths and flows to virtual and
physical network infrastructure. Paths are provisioned using the BGPCEP
project, which provides a RESTCONF interface to 3rd parties. A network
topology data model, created in YANG, enables the automatic generation
of this RESTCONF interface.

This allows Packet Design to consume OpenDaylight as a 3rd party
project, giving them the flexibility to use any SDN controller which
provides a similar RESTCONF API. In fact, Packet Design engineers have
been active in the definition of the Network Topology YANG model in the
IETF standards body to make it easier for controllers to adopt a
standard data model.

[[why-did-packet-design-choose-opendaylight]]
== Why did Packet Design choose OpenDaylight?

There were a number of reasons why Packet Design decided to use
OpenDaylight as its SDN controller. The first is that it is open
source—the ability to interact with a broad community of vendors to
shape the software was important. Their community experience has been
very good; they have found it to be a friendly place to work and the
people helpful. And finally, the broad industry support has given them
confidence that the project will be around for many years, which is a
requirement when you want to build a product with it.

The initial version of Packet Design’s SDN product included the first
OpenDaylight release, Hydrogen, and they are currently using the Helium
SR2 release. However, since they have been interacting closely with the
BGPCEP team, they are eager to migrate to the upcoming Lithium release
soon to take advantage of some features which have been added to BGPCEP
in the last release cycle.

[[future-directions]]
== Future directions

Like all projects, OpenDaylight has room for improvement. One
improvement in Lithium that the Packet Design team is looking forward to
is the improvement of RPC notifications for PCEP topology. For future
enhancements, they would like to see all OpenDaylight projects support
HTTPS by default, and improve its handling of asynchronous requests to
RESTCONF.

When I asked Hariharan Ananthakrishnan, Distinguished Engineer at Packet
Design, about their plans for the future, he said that they plan to
continue their work on defining the Network Topology YANG model. As a
well-known industry modelling language and the foundation for
OpenDaylight's MD-SAL, he sees YANG as an excellent way to allow
OpenDaylight to leverage community members with a deep knowledge of
networking but without Java developers in-house. They see OpenDaylight
as a key controller platform for them to develop and deliver future
analytics based SDN applications.

Category:Case studies[Category:Case studies]
