[[opendaylight-user-guide-template]]
= OpenDaylight User Guide Template

The user guide should be the home for documentation on: Overview and
Architecture, Configuration, Tutorial / How-To, Web/GUI, CLI, and
Console. It should link out to: Installation, APIs, and Release Notes

[[per-edition-user-guide]]
== Per-Edition User Guide

[[overview-and-architecture]]
=== Overview and Architecture

A brief description of the edition; likely including the OpenDaylight
edition block diagram indicating which projects are included

[[installation-guide-link]]
=== Installation Guide (link)

A hyperlink to installation instructions

[[installation-troubleshooting-link]]
=== Installation Troubleshooting (link)

A hyperlink to a list of troubleshooting steps for installation of the
edition

[[configuration]]
=== Configuration

How to configure the edition (ex: Use OpenFlow 1.0 or OpenFlow 1.3)

[[tutorial-how-to]]
=== Tutorial / How-To

Step-by-step instructions for doing some basic functionality with this
edition

[[web-graphical-interface]]
=== Web / Graphical Interface

If applicable, screenshots of end-user facing web pages and descriptions
of what functionality each control exposes

[[command-line-interface]]
=== Command Line Interface

If applicable, descriptions of command line interfaces and common
parameters / switches

[[console-interface]]
=== Console Interface

If applicable, descriptions of menus and choices in a console interface

[[programmatic-interfaces-link]]
=== Programmatic Interface(s) (link)

If applicable, hyperlink(s) to the relevant sections of the Developer
Guide

[[release-notes-link]]
=== Release Notes (link)

A hyperlink to the release notes for the project

[[per-project-user-guide]]
== Per-Project User Guide

[[overview-and-architecture-1]]
=== Overview and Architecture

A brief description of the project likely including one or more
high-level architecture diagrams (ex: VTN Overview)

[[installation-guide-link-1]]
=== Installation Guide (link)

If applicable, a hyperlink to installation instructions for the project
beyond what is in the per-edition installation instructions (ex: VTN
Installation)

[[installation-troubleshooting-link-1]]
=== Installation Troubleshooting (link)

If applicable, a hyperlink to a list of troubleshooting steps for
installation of the project

[[configuration-1]]
=== Configuration

If applicable, how to configure the project beyond the per-edition steps

[[tutorial-how-to-1]]
=== Tutorial / How-To

Step-by-step instructions for doing some basic functionality with this
project (ex: L2 Network Example using VTN)

[[web-graphical-interface-1]]
=== Web / Graphical Interface

If applicable, screenshots of end-user facing web pages and descriptions
of what functionality each control exposes

[[command-line-interface-1]]
=== Command Line Interface

If applicable, descriptions of command line interfaces and common
parameters / switches

[[console-interface-1]]
=== Console Interface

If applicable, descriptions of menus and choices in a console interface

[[programmatic-interfaces-link-1]]
=== Programmatic Interface(s) (link)

If applicable, hyperlink(s) to the relevant sections of the Developer
Guide

[[help]]
=== Help

If the project maintains a “users” email list or other community help
opportunities (ex: YouTube channel), they should be described and linked
here.
