[[about-this-document]]
== About this Document

Note that this is intentionally a verbatim copy of sections from the
http://www.opendaylight.org/project-lifecycle-releases#MatureReleaseProcess[Project
Lifecycle & Releases Document] which has the following to say about the
Release Review Document:

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
_Both the Release Plan and Release review document are intended to be
relatively short, simple, posted publicly on the wiki documents to
assist projects in coordinating among themselves, and the general world
in gaining visibility._
________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

When copying, please remove this section and simply fill out the next
sections.

[[project-name]]
== Project Name

[[features]]
== Features

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

Your project / feature should be included in the appropriate
link:Release/Hydrogen[Hydrogen Release Guides and Documentation]:

* Installation Guide(s)
* User Guide(s)
* Developer Guide(s)

[[architectural-issues]]
== Architectural Issues

[[security-issues]]
== Security Issues

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)
