This page lists all security vulnerabilities fixed in OpenDaylight. Each
vulnerability is assigned a security impact rating on a four-point scale
(low, moderate, important and critical). The versions that are affected
by each vulnerability are also listed.

[[low-cve-2015-1857-md-sal-information-disclosure]]
== [Low] CVE-2015-1857 MD-SAL: information disclosure

[[description]]
=== Description

It was found that the OpenDaylight MD-SAL API docs did not require
authentication. The API docs contain potentially sensitive information,
such as which devices are mounted on the server. A remote,
unauthenticated attacker could use this flaw to gain information about
the OpenDaylight server that could assist in the exploitation of another
vulnerability.

[[affected-versions]]
=== Affected versions

All releases of OpenDaylight Helium are vulnerable.

[[patch-commits]]
=== Patch commit(s)

* https://git.opendaylight.org/gerrit/#/c/17709/

[[patched-versions]]
=== Patched Versions

The Helium SR4 release will include a patch for this issue. Given its
low impact, a patch asynchronous to the existing release schedule will
not be produced.

[[credit]]
=== Credit

This issue was reported by Ryan Goulding.

[[important-cve-2015-1778-opendaylight-authentication-bypass]]
== [Important] CVE-2015-1778 OpenDaylight: authentication bypass

[[description-1]]
=== Description

It was found that the custom authentication realm used by karaf-tomcat's
"opendaylight" realm would authenticate any username and password
combination. The custom realm is work-in-progress code that is not yet
suitable for production use. A remote attacker could use this flaw to
access interfaces secured using the opendaylight realm, such as the
northbound neutron API. The opendaylight realm has been updated to use
UserDatabaseRealm, which reads credentials from the tomcat-users.xml
file.

This issue does not affect the Lithium branch.

[[affected-versions-1]]
=== Affected versions

All releases of OpenDaylight Helium are vulnerable.

[[patch-commits-1]]
=== Patch commit(s)

* https://git.opendaylight.org/gerrit/#/c/16307/

[[patched-versions-1]]
=== Patched Versions

The Helium SR3 release includes a patch for this issue. You can download
it here:

https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.2.3-Helium-SR3/

[[credit-1]]
=== Credit

This issue was reported by Flavio Fernandes of Red Hat.

[[moderate-cve-2015-1611-cve-2015-1612-openflowplugin-topology-spoofing-via-lldp]]
== [Moderate] CVE-2015-1611 CVE-2015-1612 openflowplugin: topology
spoofing via LLDP

[[description-2]]
=== Description

It has been reported that it is possible for an attacker to spoof
network topology via LLDP. An attacker can inject crafted LLDP packets
that announce internal links between switches, thereby affecting the
flow of data in the SDN network. Further technical details are available
in a
http://www.internetsociety.org/sites/default/files/10_4_2.pdf[conference
paper].

[[affected-versions-2]]
=== Affected versions

All releases of openflowplugin are vulnerable.

[[patch-commits-2]]
=== Patch commit(s)

* https://git.opendaylight.org/gerrit/#/c/16193/
* https://git.opendaylight.org/gerrit/#/c/16208/

[[patched-versions-2]]
=== Patched Versions

The Helium SR3 release includes a patch for this issue. You can download
it here:

https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.2.3-Helium-SR3/

Note that the patch does not prevent an attacker capable of acting as a
man-in-the-middle from exploiting this issue.

[[credit-2]]
=== Credit

This issue was reported by Lei Xu of Texas A&M.

[[moderate-cve-2015-1610-l2switch-topology-spoofing-via-hosttracker]]
== [Moderate] CVE-2015-1610 l2switch: topology spoofing via hosttracker

[[description-3]]
=== Description

It has been reported that it is possible for an attacker to spoof
network topology via hosttracker. An attacker can abuse hosttracker by
updating the host location information without any validation,
authentication or authorization. This makes it possible to impersonate
other networking devices by obtaining their MAC address. This issue is
related to well-known MAC spoofing attacks. Further technical details
are available in a
http://www.internetsociety.org/sites/default/files/10_4_2.pdf[conference
paper].

[[affected-versions-3]]
=== Affected versions

All releases of l2switch are vulnerable.

[[patch-commits-3]]
=== Patch commit(s)

Patches are still under development.

[[patched-versions-3]]
=== Patched Versions

Patched builds are not yet available. A
https://bugs.opendaylight.org/show_bug.cgi?id=2724[bug has been filed]
to track the development of patches.

[[credit-3]]
=== Credit

This issue was reported by Lei Xu of Texas A&M.

[[moderate-cve-2014-8149-defense4all-users-can-export-report-data-to-an-arbitrary-file-on-the-servers-filesystem]]
== [Moderate] CVE-2014-8149 defense4all: users can export report data to
an arbitrary file on the server's filesystem

[[description-4]]
=== Description

It was found that the defense4all framework's "dump" method allows a
user to request that report data is exported to a file on the server's
filesystem. The user can specify any path, and the server will write to
it with no validation. This could be used to perform a range of attacks.
For example, a critical file could be overwritten, thereby disabling the
defense4all server. On Windows servers, a UNC path could be injected,
potentially causing the server to write data to remote filesystems. An
attacker cannot control the contents of the file, but they can define a
report query that returns no results, and therefore force it to write an
empty file. An error message is received if the server cannot write to
the provided path. An attacker could therefore use this issue to map out
the writable filesystem on the server and potentially perform more
advanced attacks by manipulating special files in the /dev and /proc
filesystems of Linux servers.

It was also found that defense4all was using Spring 3.0.0 RC3. This
component is vulnerable to a number of vulnerabilities as listed on the
pivotal advisories page:
http://www.pivotal.io/security[http://www.pivotal.io/security]

[[affected-versions-4]]
=== Affected versions

All releases of defense4all <= 1.1.0 built before 15 Jan 2015 are
vulnerable.

[[patch-commits-4]]
=== Patch commit(s)

* https://git.opendaylight.org/gerrit/#/c/13972/
* https://git.opendaylight.org/gerrit/#/c/14088/

[[patched-versions-4]]
=== Patched Versions

Builds of defense4all on or after 15 Jan 2015 contain a patch for these
issues:

https://jenkins.opendaylight.org/defense4all/job/defense4all-merge/[https://jenkins.opendaylight.org/defense4all/job/defense4all-merge/]

Please note that older builds of defense4all 1.1.0 may be vulnerable,
ensure you use a build from on or after 15 Jan 2015.

[[credit-4]]
=== Credit

These issues were reported by David Jorm of IIX.

[[important-cve-2014-5035-netconf-xml-external-entity-xxe-vulnerability]]
== [Important] CVE-2014-5035 netconf: XML eXternal Entity (XXE)
vulnerability

[[description-5]]
=== Description

It was found that OpenDaylight's netconf implementation did not disable
external entities when processing user-supplied XML documents. A remote
attacker, if able to interact with one of OpenDaylight's netconf
interfaces, could use this flaw to exfiltrate files on the OpenDaylight
controller, and potentially perform more advanced XXE attacks.

[[affected-versions-5]]
=== Affected versions

OpenDaylight Helium GA and SR1 are both affected.

[[patch-commits-5]]
=== Patch commit(s)

* https://git.opendaylight.org/gerrit/#/c/13647/ (NETCONF, master)
* https://git.opendaylight.org/gerrit/#/c/13646/ (NETCONF,
stable/helium)
* https://git.opendaylight.org/gerrit/#/c/13649/ (RESTCONF, master)
* https://git.opendaylight.org/gerrit/#/c/13650/ (RESTCONF,
stable/helium)
* https://git.opendaylight.org/gerrit/#/c/13651/ (EXI, master)
* https://git.opendaylight.org/gerrit/#/c/13774/ (EXI, stable/helium)

[[patched-versions-5]]
=== Patched Versions

You can download Helium-SR1.1 which has the patches listed with
stable/helium applied here:

https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.2.1-Helium-SR1.1/[https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.2.1-Helium-SR1.1/]

[[credit-5]]
=== Credit

This issue was reported by Gregory Pickett of Hellfire Security.
