[[technical-overview-and-architecture]]
== Technical Overview and Architecture

Refer the architecture and design page
https://wiki.opendaylight.org/view/SNBI_Architecture_and_Design[here] to
get the overview of the architecture and the protocol details.

[[getting-the-basic-setup]]
== Getting the Basic Setup

Refer the [https://wiki.opendaylight.org/view/SNBI_User_Guide. User
Guide] to the basic setup.

[[setting-up-the-required-environment]]
== Setting up the required environment

Refer the
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Installation[OpenDaylight_Controller:Installation]
guide to setup all required environment.

[[accessing-snbi-repository]]
== Accessing SNBI Repository

* First clone the SNBI from the git repository.

-----------------------------------------------------------------
git clone https://<userid>@git.opendaylight.org/gerrit/p/snbi.git
cd snbi
-----------------------------------------------------------------

* Once in the SNBI directory, the source code is split into multiple sub
directories as below.

------------------
distribution
features
portablefoundation
shellplugin
snbiFe
southplugin
------------------

[[southplugin]]
=== SouthPlugin

The southplugin contains both the protocol implementation as described
in the architecture and the Certificate management APIs.

[[shellplugin]]
=== Shellplugin

The shellplugin contains the CLI implementation for Karaf console. You
can further refer the document
http://karaf.apache.org/manual/latest-2.2.x/developers-guide/extending-console.html[here]
to understand how to add a custom CLI to karaf console.

[[snbife]]
=== SnbiFE

This is the SNBI Forwarding Element implementation which is in C, you
could build the executable using the make file located in the directory.
Further the implementation has been integrated with libcli to provide a
router like console to configure the SNBI instance. See
https://github.com/dparrish/libcli[here] for more documentation on
libcli and how to add a custom cli. Once the SNBI FE code is built, the
executable is available in the bin directory. snbi-sim is a CLI
simulator and provides various CLIs to control the operation of the
Forwarding Element SNBI Agent, to start SNBI execute "snbi-start" on the
simulator. This should start neighbour discovery and eventually
bootstrapped once discovered and authenticated by the Controller SNBI
south plugin.

-------------------------

snbi/snbiFe => cd bin
snbi/snbiFe => ./snbi-sim
snbisim > snbi-start
-------------------------

Please add multiple module level make files and dependencies and link it
to the main make file, please avoid adding everything to the root
makefile file.

[[features]]
=== Features

The features directory contains all required information to define the
SNBI feature - odl-snbi-all. Please refer to the
https://wiki.opendaylight.org/view/Karaf:Step_by_Step_Guide[Karaf Guide]
on how to add additional features.

[[distribution]]
=== Distribution

There are two distribution that we could build to verify the SNBI
feature.

* base distribution - This is the traditional OSGI based build, refer
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Building_from_CLI[here]
how to build the controller project
* karaf distribution - This is for Karaf based distribution, refer
https://wiki.opendaylight.org/view/Karaf:Step_by_Step_Guide#Test_your_features_for_functionality_in_your_local_karaf_distro[here]
to build your local karaf distribution.

[[portable-foundation]]
=== Portable Foundation

* Portable foundation contains all required scripts to setup the docker,
refer
https://wiki.opendaylight.org/view/SNBI_Architecture_and_Design#Forwarding_Element_Components[here]
to understand how the docker and the docker-host network stacks are
provisioned.
** The applications running within the docker don't have host root
access privileges, but still have have host network visibility.
* Refer https://wiki.opendaylight.org/view/Page[here] to understand how
to start the docker instance and access it.

[[committing-code-to-the-repository]]
=== Committing code to the repository

* Refer to the Hacking and Pushing tutorial
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_the_CLI#Push_the_code_via_git_CLI[here]
to setup everything that is required to push the code to gerrit.
* Please wait for someone from the project to review/approve the gerrit
request before the code could be pushed to the repository.

