Table Type Patterns (TTPs) are the (upcoming) first tangible output from
the ONF's Forwarding Abstractions Working Group (FAWG). The goal is to
allow for an OpenFlow controller and OpenFlow switch to agree on a set
of functionality to help manage the increased diversity made possible
with OpenFlow versions 1.1+. While the current focus of TTPs within the
ONF is on OpenFlow, these abstractions are the first incarnation of a
category of abstractions known as "Negotiable Datapath Models" (NDMs),
which are likely to be more broadly useful and inside OpenDaylight they
could expand to be used for other protocols. (Note that this project was
proposed under the title
"Project Proposals:Negotiable Datapath Models[Negotiable Datapath
Models]", based on the anticipated specification title being developed
at the ONF. When the ONF changed the title, this project's title change
was requested.)

[[project-information]]
== Project Information

* Project Proposals:Negotiable Datapath Models[Project Proposal]
* Helium
** Table Type Patterns:Helium Release Plan[Release Plan]
** Table Type Patterns:Helium Release Review[Release Review]
** Table Type Patterns:Helium Release Notes[Release Notes]
* Lithium
** Table Type Patterns:Lithium Release Plan[Release Plan]
** Table Type Patterns:Lithium Release Review[Release Review]
** Table Type Patterns:Lithium Release Notes[Release Notes]
* Test contact: Colin Dixon (colin@colindixon.com)
* Documentation contact: Curt Beckmann (beckmann@brocade.com)

[[logical-subprojects]]
== Logical Subprojects

There are currently two major sub-projects: `ttp-model` and `parser`.

[[model]]
=== Model

This consists of a YANG model for a TTP that closely matches the ONF
spec and a simple model that allows you to associate zero or one "active
TTPs" as well as zero or more "supported TTPs" with a switch.

[[parser]]
=== Parser

The parser provides CLI tools to read, write and work with TTPs.

[[other-subprojects]]
=== Other Subprojects

The `distribution-karaf` and `features` subprojects are there for
building and testing Karaf features so that others can load and depend
on TTP functionality easily. The `utils` subproject contains the common,
shared functionality between `ttp-model` and `parser`.

[[models]]
== Models

*
https://git.opendaylight.org/gerrit/gitweb?p=ttp.git;a=blob;f=ttp-model/src/main/yang/ttp.yang[TTP
Yang Model]

[[roadmap-and-plans]]
== Roadmap and Plans

*
https://docs.google.com/a/colindixon.com/document/d/1YwAvznNnU76ETMOpS7Z7b2qPvxExw0Mjnb3o0gqD8DA/edit[Google
Doc covering use cases and API sketches]
* https://trello.com/b/QxGfHDiy/odl-table-type-patterns[Trello Board]
*
https://lists.opendaylight.org/pipermail/ttp-dev/2015-February/000031.html[2/4/15
e-mail on possible Lithium work items]
**
https://docs.google.com/a/colindixon.com/document/d/1Sj_Bq9VBLmUk0btgK5d2Fa5IjsYmTxXK65hOATKNzSg/edit?usp=sharing[low-level
lithium planning]

[[references]]
== References

*
https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/OpenFlow%20Table%20Type%20Patterns%20v1.0.pdf[TTP
1.0 Spec]
* http://www.youtube.com/watch?v=bcaBS6w_k_o[Curt and Colin's
OpenDaylight Summit Talk]
*
http://events.linuxfoundation.org/sites/events/files/slides/TTPs%20and%20NBIs%20for%20ods2014-final_0.pdf[Slides
from the OpenDaylight Summit Talk]
*
http://www.slideshare.net/US-Ignite/interoperable-open-flow-with-nd-ms-and-ttpsbeckmann[Curt's
slides from US Ignite]
* https://github.com/Broadcom-Switch/of-dpa[Source, binaries and
documentation for Broadcom's OF-DPA]

[[contribute]]
== Contribute

[[list-of-all-subpages]]
== List of all subpages
