Table Type Patterns (TTPs) are the (upcoming) first tangible output from
the ONF's Forwarding Abstractions Working Group (FAWG). The goal is to
allow for an OpenFlow controller and OpenFlow switch to agree on a set
of functionality to help manage the increased diversity made possible
with OpenFlow versions 1.1+. While the current focus of TTPs within the
ONF is on OpenFlow, these abstractions are the first incarnation of a
category of abstractions known as "Negotiable Datapath Models" (NDMs),
which are likely to be more broadly useful and inside OpenDaylight they
could expand to be used for other protocols. (Note that this project was
proposed under the title
"Project Proposals:Negotiable Datapath Models[Negotiable Datapath
Models]", based on the anticipated specification title being developed
at the ONF. When the ONF changed the title, this project's title change
was requested.)

[[project-information]]
== Project Information

* Project Proposals:Negotiable Datapath Models[Project Proposal]
* Table Type Patterns:Helium Release Plan[Helium Release Plan]
* (github and other resoureces pending)

[[logical-subprojects]]
== Logical Subprojects

[[concepts]]
=== Concepts

[[code-generator]]
=== Code Generator

[[model]]
=== Model

[[restconf]]
=== RestConf

[[models]]
== Models

[[references]]
== References

*
https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/OpenFlow%20Table%20Type%20Patterns%20v1.0.pdf[TTP
1.0 Spec]
* http://www.youtube.com/watch?v=bcaBS6w_k_o[Curt and Colin's
OpenDaylight Summit Talk]
*
http://events.linuxfoundation.org/sites/events/files/slides/TTPs%20and%20NBIs%20for%20ods2014-final_0.pdf[Slides
from the OpenDaylight Summit Talk]
*
http://www.slideshare.net/US-Ignite/interoperable-open-flow-with-nd-ms-and-ttpsbeckmann[Curt's
slides from US Ignite]
* https://github.com/Broadcom-Switch/of-dpa[Source, binaries and
documentation for Broadcom's OF-DPA]

[[contribute]]
== Contribute

[[list-of-all-subpages]]
== List of all subpages
