[[opendaylight-at-the-university-of-luxembourg]]
== OpenDaylight at the University of Luxembourg

One of the great things about open source projects is that they provide
a solid, easily available, and generally well documented basis for
university research. This generally gives researchers the ability to
concentrate just on the algorithms and instrumentation which they are
interested in, without having to completely develop a software suite for
the subject area they are studying.

In the http://wwwen.uni.lu/snt/[Interdisciplinary Centre for Security,
Reliability and Trust (SnT)] at the University of Luxembourg,
researchers are using OpenDaylight as basis for addressing specific
aspects in the context of the ongoing Cognitive Software Defined
Networks http://secan-lab.uni.lu/index.php/projects/cosdn[(CoSDN)]
project. CoSDN seeks to combine the efficiency of SDN with cognitive
learning algorithms and enhanced protocols to automatise SDN systems. To
this aim, the team under the supervision of Prof.
http://wwwen.uni.lu/snt/people/thomas_engel[Thomas Engel], is adopting
OpenDaylight to tackle two directions:

* Attack Detection (through learning): Having Defense4All:Main[
Defense4All] as starting point, Dr.
http://wwwen.uni.lu/snt/people/emilia_tantar[Emilia Tantar] is
developing advanced learning algorithms for the specific SDN security
challenges. The machine learning techniques are used for online
dynamically detecting known patterns of attack, but also in identifying
new attack signatures.
* Network troubleshooting: Dr.
http://wwwen.uni.lu/snt/people/tigran_avanesov[Tigran Avanesov] is
integrating the work done by the CoSDN team in cooperation with
http://nephos6.com[Nephos6], on an agent-based approach to measure
network quality metrics and localize potential issues in the network, by
using information from the OpenDaylight_Controller:Topologies[ topology
manager].

Their experiences with the OpenDaylight project have for the most part
been good - they describe it as a very helpful community - but they
admit that the move from AD-SAL to MD-SAL was a difficult transition for
the group, as they had to rewrite their applications.

When I asked about potential improvements which could be made to get new
people into the project, they mentioned a number of issues related to
making it more obvious how to create an account for the bug tracker and
wiki, and they mentioned that it can be hard to find information in the
project wiki, which could use better content organization.

As for future improvements they would like to see implemented in ODL,
Tigran mentioned the limits of the REST API, which does not allow
reactive programming or event handling. He pointed to a
http://www.frank-durr.de/?p=165[proof of concept], developed by a
researcher from the University of Stuttgart, of a message broker which
applications could subscribe to in order to receive events from the
controller, and suggested that integrating this would be useful.

http://secan-lab.uni.lu/index.php/projects/cosdn[Contact details]

Category:Case_studies
