This page exists to track current and past issues that may concern
multiple projects. The idea is to report anything that you are doing
that might break other projects and/or report breakages that are coming
from other projects. Then, people can look here to see if one of the
current issues explains the breakage they're seeing and help them fix
it.

In general, there are two reasons you're posting here.

1.  You're going to make a change that might break people.
2.  You've just had something break on you that appears to be caused by
some other project and it's not already listed here.

In either event copy the link:#Example_Issue[example issue] to
link:#Current_Weather_Report[current weather report] and fill it out to
the best of your ability. Then send a mail to the
https://lists.opendaylight.org/mailman/listinfo/release[release list] as
well as relevant project dev lists if you know them with a link to the
relevant section on this page. Make sure the subject starts with
`[WEATHER]`.

[[lithium-blocking-bugs]]
== Lithium Blocking Bugs

NB: We're still figuring this concept out, so expect it to be iterated
on. Suggestions welcome!

[[blocking-bugs-definition]]
=== Blocking Bugs definition

Blocking bugs may meet one or more of the following conditions:

* Cause a major controller-wide regression. e.g: A bug in openflowplugin
prevents OpenFlow switches from connecting.
* Cause a major regression in another project. e.g: A bug in OVSDB
causes GBP service to fail.
* Dramatically decrease controller performance or scale. e.g: A bug in
yangtools causes OpenFlow perf test results to decrease by an order of
magnitude.
* Are immediately obvious to users. e.g: A bug in DLUX makes topology
unavailable in the GUI.

Generally, major regressions are likely candidates. Of course, terms
like "major" require substantial case-by-case interpretation.

[[blocking-bugs]]
=== Blocking Bugs

The
https://docs.google.com/spreadsheets/d/1KPpO9LH539Vlcoa4RvLa6PPCdLifi5JD-ihRhlybqeo/edit#gid=676729675["Blocking
Bugs" tab] of the "Lithium Project Status" spreadsheet is the primary
source for blocking bug info.

Currently, only
https://wiki.opendaylight.org/view/CrossProject:Integration_Group[active
Integration committers] and people involved in the release process have
edit-permissions to the spreadsheet. Please contact them if you'd like
to add a new bug. After a new bug is added, please email the
https://lists.opendaylight.org/mailman/listinfo/release[release mailing
list].

[[current-weather-report]]
== Current Weather Report

[[openflowplugin-model-issues-cause-feature-installation-issues]]
=== OpenflowPlugin model issues cause feature installation issues

* *Description:* OpenflowPlugin's models are not loaded when started
causes the odl-ovsdb-openstack feature to not load it's bundles.
* *Reported By:*
** Sam Hague, shague@redhat.com, IRC handle: shague, ODLID:shague
** Anil Vishnoi, vishnoianil@gmail.com, IRC handle: vishnoianil,
ODLID:vishnoanil
* *Link to e-mail reporting it:*
https://lists.opendaylight.org/pipermail/release/2015-May/002428.html
* *Links to opened bugs:*
** https://bugs.opendaylight.org/show_bug.cgi?id=3341
* *Links to patches:*
** [link-to-patch-one-in-gerrit description of patch 1]
** [link-to-patch-two-in-gerrit description of patch 2]
* *Example output showing the error:*

--------------------------------------------------------------------------------------------------------------------------------------------------------------
015-05-22 07:13:35,534 | WARN  | pool-12-thread-1 | DataObjectCodecContext           | 116 - org.opendaylight.yangtools.binding-data-codec - 0.7.0.SNAPSHOT | 
Failed to load augmentation prototype for GeneratedTransferObject [packageName=org.opendaylight.yang.gen.v1.urn.opendaylight.flow.inventory.rev130819, 
name=FlowCapableNode, comment=, annotations=[],
...
java.lang.ClassNotFoundException: org.opendaylight.yang.gen.v1.urn.opendaylight.flow.inventory.rev130819.FlowCapableNode
--------------------------------------------------------------------------------------------------------------------------------------------------------------

* *Steps to Reproduce:*

1.  start ovsdb karaf distribution
2.  odl-ovsdb-openstack feature is loaded at bootstrap and exceptions
occur

* *Proposed Solution:*
* *Proposed Workaround:* Failures happen randomly so sometimes
restarting fixes the issue.

[[jenkins-slave-utilization-and-job-failures]]
=== Jenkins Slave utilization and job failures

* *Description:* Jenkins has started hitting our Rackspace resource caps
again. As such the job wait queue may be extra long, or some jobs
(integration jobs in specific) may fail due to inability to acquire the
resources that they require to operate.
* *Reported By:* Andrew Grimberg, agrimberg@linuxfoundation.org, IRC
handle: tykeal, ODLID: agrimberg
* *Link to e-mail reporting it:*
https://lists.opendaylight.org/pipermail/infrastructure/2015-May/000507.html[Infrastructure
mail announcing the issue]

[[ad-sal-removal-on-master-beryllium-branch]]
=== AD-SAL Removal on master (beryllium) branch

* *Description:* Removal AD-SAL and related components which wad
deprecated in Lithium
* *Reported By:*
** Tony Tkacik, ttkacik@cisco.com IRC handle: ttkacik, ODLID: ttkacik
* *Links to opened bugs:*
* *Links to patches:*
** https://git.opendaylight.org/gerrit/#/c/18740/

This change will not affect bumping, since berrylium numbered AD-SAL
SNAPSHOT components are present in Nexus repository, but there will be
no release version of this components.

[[neutron-northbound-must-be-loaded-before-any-other-jaxb-feature]]
=== Neutron Northbound must be loaded before any other JAXB feature

* *Description:*
* *Reported By:*
** Ed Warnicke, hagbard@gmail.com, IRC handle: edwarnicke, ODLID:
** Ryan Moats, rmoats@us.ibm.com, IRC handle: regXboi, ODLID:
* *Link to e-mail reporting it:*
https://meetings.opendaylight.org/opendaylight-meeting/2015/weekly_lithium_irc_sync/opendaylight-meeting-weekly_lithium_irc_sync.2015-04-08-14.31.html[discussed
as item 2 in 4/8/15 Lithium Weekly IRC sync]
* *Links to opened bugs:*
** ???
* *Links to patches:*
** ???
* *Example output showing the error:*

---
???
---

* *Steps to Reproduce:*

1.  Load the restconf feature
2.  Load the neutron feature
3.  The Neutron feature won't receive requests

* *Proposed Solution:* ???
* *Proposed Workaround:* Load the neutron feature first.

[[example-issue]]
=== Example Issue

* *Description:*
* *Reported By:* , , IRC handle: , ODLID:
* *Link to e-mail reporting it:*
* *Links to opened bugs:*
** [link-to-bug-one-in-bugzilla description of bug 1]
** [link-to-bug-two-in-bugzilla description of bug 2]
* *Links to patches:*
** [link-to-patch-one-in-gerrit description of patch 1]
** [link-to-patch-two-in-gerrit description of patch 2]
* *Example output showing the error:*

--------------
Put your logs
Here
Spanning lines
--------------

* *Steps to Reproduce:*

1.  step one
2.  step two

* *Proposed Solution:*
* *Proposed Workaround:*

[[weather-forecast]]
== Weather Forecast

Only put things scheduled for the future here.

[[historical-weather-data]]
== Historical Weather Data

[[switch-to-lithium-notification-broker]]
=== Switch to Lithium Notification Broker

* https://git.opendaylight.org/gerrit/#/c/19303/
* may temporalily decrease throughput of current existing drop-test or
notification listeners which used MD-SAL threads to do blocking work.
But is required for Openflowplugin redesign in order to use non-blocking
publish APIs.
* Change 01-mdsal.xml in karaf - remove added lines by this patch.
* *Links to opened bugs:*
** https://bugs.opendaylight.org/show_bug.cgi?id=3148[This change
completely broke notifications in lispflowmapping] Removing lines added
to 01-md-sal.xml in karaf is a workaround, we need a solution.

[[authentication-service-unavailable]]
=== 503 - Authentication Service Unavailable

* *Description:*

Some projects including integration have seen this error when starting
karaf with preloaded features (including odl-restconf), weirdly it is
not seen when features are installed from console.

* *Reported By:* Luis Gomez, ecelgp@gmail.com, IRC handle: LuisGomez,
ODLID:ecelgp
* *Link to e-mail reporting it:*
https://lists.opendaylight.org/pipermail/integration-dev/2015-April/003050.html
* *Steps to Reproduce:*

1.  configure preloaded features in karaf
etc/org.apache.karaf.features.cfg file
2.  start karaf with bin/karaf
3.  do REST GET http://localhost:8181/restconf/modules and you get 503 -
Authentication Service Unavailable
4.  check for Java Exception in karaf console

* *Proposed Solution:* Work on fixing the Java Exception
* *Proposed Workaround:* Start features with feature:install instead of
config file

[[karaf-3.0.3-upgrade]]
=== Karaf 3.0.3 Upgrade

[[description]]
==== Description

In order to support Java 8 we need to upgrade to Karaf 3.0.3. This
transition has some potential to introduce breakage. Effort has been
made to try to insure it *doesn't* introduce breakage... but letting
folks know just in case.

[[scheduled-date]]
==== Scheduled Date

Switchover is scheduled to occur on 2015-04-13 (Monday).

[[reported-by]]
==== Reported By

Ed Warnicke IRC handle: edwarnicke ODLID: eaw

[[email-reporting-it]]
==== Email reporting it

[[open-bugs]]
==== Open Bugs

* *Bug for change*:
https://bugs.opendaylight.org/show_bug.cgi?id=2907[Bug 2907 Karaf 3.0.3
Upgrade]

[[patches]]
==== Patches

https://git.opendaylight.org/gerrit/#/c/15391/[odlparent patch]

https://git.opendaylight.org/gerrit/#/c/15393/[controller patch]

[[breakages]]
==== Breakages

1.  This only expected in retrospect, it only breaks some tests, and
from ODL point of view, it is a feature. Previous version of karaf had
bin/client command allowing connection without credentials, but on 3.0.3
it leads to cryptic NPE. The solution is to provide credentials to
client, for example "sshpass -p karaf ./bin/client -u karaf
feature:install odl-restconf". This solution works on the current karaf
too. This issue does not affect other scripts in bin/ (karaf, start).
Also, test jobs by Integration group do install features by editing
bootFeatures, so no change is needed there.
2.  It is possible that local .m2 repos could get into a strange state
that result in errors either complaining about missing dependency on
feature 'standard' or an NPE from the karaf maven plugin.

The solution is to "rm -rf ~/.m2/repository/org/opendaylight" and build
again.

1.  *UPDATE: Fixed* Currently karaf 3.0.3 is known to have breakage,
which should be fixed by:
1.  https://git.opendaylight.org/gerrit/#/c/18402/ <- odlparent
2.  https://git.opendaylight.org/gerrit/#/c/18410/ <- controller
2.  *UPDATE: Fixed* Karaf 3.0.3 maven plugin reinstalls features
recursively, giving the appearance of looping on feature install,
bloating logs, and causing long builds.
1.  If you are using karaf-parent, this should be fixed by:
https://git.opendaylight.org/gerrit/#/c/18525/
2.  If you are setting the maven plugin version locally, use the 3.0.1
version of the karaf-maven-plugin
3.  https://bugs.opendaylight.org/show_bug.cgi?id=3011[Tomcat as
startupFeature prevents first run of controller]: The AD-SAL Northbound
features are still pulling in Tomcat, and that is pulling in
wrap:mvn:javax.servlet.jsp/jsp-api/2.1 which apparently has an issue.
This should not effect any feature using jetty (neutron, restconf, etc).
4.  Karaf 3.0.3 does not install your feature if compile / runtime
dependencies referenced from features.xml were not compile / runtime
dependencies of features project. That is bug in your application, since
build with Karaf 3.0.1 would not install your feature on fresh machine
without internet access. In Karaf 3.0.3 it prevents installation of your
feature even if

required dependencies are in your local .m2 repository.

[[helpful-notes]]
==== Helpful Notes

If you would prefer, rather than building odlparent and controller with
these patches and then your stuff to test, you can test your stuff in a
pre-built
https://drive.google.com/open?id=0B4Szir1BfjyWNFhBcHJkT21rSlk&authuser=0[integration
build] that incorporates the changes.

https://drive.google.com/open?id=0B4Szir1BfjyWZkFvVEJCUUF5T28&authuser=0[NEW
BUILD from 2015-04-08 with OFP fixes and clustering on by default with
karaf 3.0.3]

* Do* check at the karaf console with

system:version

to make sure you are running karaf version 3.0.3. Please *do* test your
functionality.

For local distributions, you may find it much smoother to migrate to
using karaf-parent, rather than maintaining all of the build machinery
locally. See the
https://git.opendaylight.org/gerrit/gitweb?p=coretutorials.git;a=blob;f=hello/hello-karaf/pom.xml;h=b2a7de3a0e7e12b853e7c4d9b6d7c7d19dd6e1d3;hb=HEAD[hello-karaf
example from coretutorials] for an example. You should just need the
dependencies on your local feature and possibly to set the property.

[[projects-that-have-tested-wo-issues]]
==== Projects that have tested w/o issues

* LISP Flow Mapping
* TTP
* VTN
** We tested VTN features on
https://drive.google.com/open?id=0B4Szir1BfjyWZkFvVEJCUUF5T28&authuser=0[the
new build (2015-04-08)].
* BGPCEP and TCPMD5

[[clustered-data-store-switch-over]]
=== Clustered Data Store Switch over

[[description-1]]
==== Description

Currently the MD-SALs default datastore is the inmemory data store. This
change would switch to using by default the clustered datastore,
including persistence being on for the config datastore.

[[scheduled-date-1]]
==== Scheduled Date

Switchover is scheduled to occur on 2015-04-06 (Monday).

[[reported-by-1]]
==== Reported By

Ed Warnicke IRC handle: edwarnicke ODLID: eaw

[[email-reporting-it-1]]
==== Email reporting it

*
https://lists.opendaylight.org/pipermail/release/2015-March/001784.html[Formal
email sent 2015-03-26]
*
https://lists.opendaylight.org/pipermail/discuss/2015-January/004381.html[Previous
email about it 2015-01-20]
*
https://lists.opendaylight.org/pipermail/discuss/2015-February/004695.html[Previous
email about it 2015-02-24]

[[open-bugs-1]]
==== Open Bugs

* *Bug for change*:
https://bugs.opendaylight.org/show_bug.cgi?id=2903[Bug 2903: Clustering:
Turn on Clustered Datastore by default]
* https://bugs.opendaylight.org/show_bug.cgi?id=2953[Bug 2953:
Clustering : Unable to read from datastore root with clustering enabled]
- ETA 04/14/2015

List any collateral bugs below for breakage:

1.  [link-to-bug-one-in-bugzilla description of bug 1]
2.  [link-to-bug-two-in-bugzilla description of bug 2]

[[patches-1]]
==== Patches

1.  https://git.opendaylight.org/gerrit/#/c/14313/[Gerrit 14313
implementing the switch]
2.  [link-to-patch-two-in-gerrit description of patch 2]

[[expected-breakages]]
==== Expected breakages

1.  BGPCEP's https://bugs.opendaylight.org/show_bug.cgi?id=2383[RIB
structure rework] will be broken by this until
https://git.opendaylight.org/gerrit/#/c/16690/[Support for
DOMDataTreeChangeService] lands
2.  Services Function Chaining will be broken indefinitely until Netconf
and OVSDB fully define their data persistence behavior.

https://bugs.opendaylight.org/show_bug.cgi?id=2920[1]
https://bugs.opendaylight.org/show_bug.cgi?id=2921[2]
https://bugs.opendaylight.org/show_bug.cgi?id=2922[3]
https://bugs.opendaylight.org/show_bug.cgi?id=2923[4]

[[helpful-notes-1]]
==== Helpful Notes

There is a prebuilt integration build with the clustering patches
applied to test with
https://drive.google.com/open?id=0B4Szir1BfjyWaGRuU3FqUGhZeE0&authuser=0[here].

[[jenkins-and-nexus-outage]]
=== Jenkins and Nexus outage

[[description-2]]
==== Description

Upcoming outage of Jenkins and Nexus for storage remanagement.

[[scheduled-date-2]]
==== Scheduled Date

Saturday April 04, 2015 (2015-04-04) @ 10:00 - 11:00 PDT

[[reported-by-2]]
==== Reported By

Andrew Grimberg IRC handle: tykeal ODLID: agrimberg

[[email-reporting-it-2]]
==== Email reporting it

*
https://lists.opendaylight.org/pipermail/discuss/2015-April/005004.html[5]

[[expected-breakages-1]]
==== Expected breakages

Jenkins and Nexus will be offline for the storage remanagement. Internal
builds will fail. External builds that do not already go through a local
Maven repository proxy will fail.

[[openflow-plugin-openflow-java-bugs-blocking-other-projects]]
=== OpenFlow Plugin & OpenFlow Java Bugs Blocking other projects

[[description-3]]
==== Description

* A pair of bugs in OFP and OFJ are blocking other projects in their
testing
* *Reported By:* Keith Burns & Flavio Fernandes,
alagalah@noironetworks.com ffernand@redhat.com , alagalah flaviof,
ODLID:
*
https://lists.opendaylight.org/pipermail/controller-dev/2015-March/008689.html[Link
to e-mail reporting it]
* *Links to opened bugs:*
** https://bugs.opendaylight.org/show_bug.cgi?id=2895[Exception in FRM
with no flows installed on nodes]
** https://bugs.opendaylight.org/show_bug.cgi?id=2913[GroupMods not
being written to second switch]
* *Links to patches:*
** https://git.opendaylight.org/gerrit/#/c/17818/[Fix for bug 2895
"Exception in FRM with no flows installed on nodes"]
** https://git.opendaylight.org/gerrit/#/c/17740/[Fix for bug 2913
"GroupMods not being written to second switch"]
* *Example output showing the error:*

--------------
Put your logs
Here
Spanning lines
--------------

* *Steps to Reproduce:*

1.  step one
2.  step two

* *Proposed Solution:*
* *Proposed Workaround:*

[[jenkins-slave-instability]]
=== Jenkins slave instability

[[description-4]]
==== Description

Jenkins has recently been having regular issues with slaves not
connecting or disconnecting from the master appropriately. LF is aware
of the situation and monitoring it, unfortunately this is a manual
monitoring process presently. Should you see weird major queue backups
pinging either tykeal or zxiiro in either #opendaylight or
#opendaylight-releng can be useful.
