[[wiki-gardening]]
= Wiki gardening

Wikis are subject to entropy. Not everyone knows the naming conventions,
people don't create links to new pages in the right place, the
organization that made sense with 20 pages no longer makes sense with
200, articles get old and out of date...

The Wiki Gardeners is a group created to address these issues. Our job
is to fight the entropy, to keep order in a wild, wild world. Weeding,
pruning, replanting, caring for the wiki. A lot like gardening.

Our primary goal is to ensure that the wiki is a nice place for
OpenDaylight users and developers to find and share information.

For general guidelines on editing wiki pages, please read
link:wiki guidelines[wiki guidelines].

In addition:

* The front page should remain clean. Each section will have 4 to 5
front-page links, with a category link (hidden behind "More topics") to
all of the other pages in the category.
* Pages should be split or consolidated to ensure that they are neither
too long or too short.
* The wiki will refer to external content rather than duplicate it - we
do not wish to be a source of truth, but we do wish to link to all
relevant content.

[[current-wiki-gardening-tasks]]
== Current wiki gardening tasks

* Ensure that all Special:LonelyPages[ orphaned pages] are linked to
from at least one other page
* Ensure that all Special:UncategorizedPages[ uncategorized pages] are
associated with at least one Special:Categories[ category]
* Maintain the link:Main Page[ front page], and any additional sub-pages
needed for prominent content

[[guidelines-for-categories]]
== Guidelines for categories

There are a few categories we can use to indicate that a page is
deprecated, or in need of updating. Please add relevant pages to these
categories as you find them:

* :Category:AD-SAL: Content which is either deprecated, or is not going
to be current in future releases as all projects move to MD-SAL.
* :Category:Needs_Updating: Content which is good, but out of date and
requires updating for a newer release
* :Category:Deprecated: Content which is being kept around, but which is
specifically related to older releases

[[gardening-templates]]
== Gardening Templates

* Template:Deprecated: This template is an easy-to-use way to flag a
page as out-of-date and provide an optional link to more up-to-date
content.
** Template:AD-SAL: A version of the deprecated template that provides
some additional context that the page covers the AD-SAL.
* Template:Needs Updating[Template:Needs Updating]: Used to flag a page
as in need of updating.
* Template:Hydrogen Release[Template:Hydrogen Release]: Used to flag
content as belonging to the Hydrogen Release (and thus Deprecated)
* Template:Helium Release[Template:Helium Release]: Used to flag content
as belonging to the Helium Release
* Template:Lithium Release[Template:Lithium Release]: Used to flag
content as belonging to the Lithium Release

Category:Community
