[[major-features]]
=== Major Features

Helium release marks the second release (previous was
YANG Tools:Hydrogen Release Notes[Hydrogen]) of the most of YANG Tools
components. The following features have been updated:

* Bugfixes and performance updates to YANG parser infrastructure with a
set of regression tests
* Small updates of a YANG Binding Specification for Java for
representing YANG-modeled data, RPCs and notifications
* Updated Definition of a revision-aware model-independent data
representation of YANG-modeled data
* Maven plugin for compile-time interface and implementation of YANG
Binding Specification for Java
* Small updates of Java meta-model of YANG model language
* Minimization of Xtend usage only to source code templates.

New features delivered:

* Normalized Node data model
* Implementation of Normalized Node data model and vatious concepts.
* Stream based codecs for JSON / XML and Normalized Nodes
* Run-time component for mapping Java Binding Specification objects
from/to Normalized Node representation

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

YANG tools are kept completely portable and require only a Java-7
compliant JVM to run. The Maven plugin requires Maven version 3.0.4 or
later.

[[for-development]]
==== For Development

YANG tools is developed as a normal Java project, but it makes small use
of https://www.eclipse.org/xtend/[Xtend] language for templating.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

* During the development of Hydrogen and Helium release a number of
issues have been identified in the Java Binding Specification:
** Using the same name for groupings and containers in the same context
results in invalid code (issues #138, #157, #295)
** The specification contains a static get() method, conflicting with
JMX implementation
** Binding's handling of unsigned types could be improved with Guava's
Unsigned types
** The translation of choice/case statements requires users to use
instanceof and explicit typecasts, leading to run-time errors due to
missed spots in refactoring
** The exact mapping of YANG lists to Set/Map/List is not completely
satisfactory

The implementation has been tested extensively with its downstream
projects (openflowjava, bgpcep, controller, openflowplugin) and works
reasonably well for complex models.

There are a few known bugs which will be addressed in the next bugfix
release.
