[[benchmarking-of-yangtools-components]]
== Benchmarking of Yangtools components

This page provides information about how to run various benchmarks on
Yangtools project.

[[general-howto]]
=== General HowTo

Clone Yangtools project into your local repository:

-------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/yangtools.git
-------------------------------------------------------------------

If you just want to do an anonymous git clone, you can use HTTPS:

-------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/yangtools.git
-------------------------------------------------------------

If you want to build Yangtools and run benchmarks navigate to your
yangtools parent directory (where parent .pom is located) and execute:

------------------------------------------
mvn clean install -DskipTests -Pbenchmarks
------------------------------------------

The flag "-Pbenchmarks" executes the benchmarks profile after whole
Yangtools project is built.

If you want just run benchmarks project navigate (inside Yangtools
parent folder) into "benchmarks folder"

In benchmarks folder just run:

-----------------
mvn clean install
-----------------

If you don't have yangtools built the yangtools artefacts should be
automatically downloaded from nexus and after build of benchmarks
project the benchmarks should run automatically.

Wait until all benchmarks are done.

You should see result output formatted in console

[cols=",,,,,",options="header",]
|=======================================================================
|Benchmark |Mode |Samples |Score |Score error |Units
|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write100KSingleNodeWithOneInnerItemInCommitPerWriteBenchmark
|avgt |200 |2867.443 |60.840 |ms/op

|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write100KSingleNodeWithOneInnerItemInOneCommitBenchmark
|avgt |200 |231.552 |1.631 |ms/op

|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write10KSingleNodeWithTenInnerItemsInCommitPerWriteBenchmark
|avgt |200 |212.069 |2.256 |ms/op

|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write10KSingleNodeWithTenInnerItemsInOneCommitBenchmark
|avgt |200 |16.616 |0.227 |ms/op

|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write50KSingleNodeWithTwoInnerItemsInCommitPerWriteBenchmark
|avgt |200 |1262.044 |14.743 |ms/op

|o.o.y.y.d.i.t.InMemoryDataTreeBenchmark.write50KSingleNodeWithTwoInnerItemsInOneCommitBenchmark
|avgt |200 |107.397 |1.929 |ms/op
|=======================================================================

Just consider that results may warry depending on hardware and
conditions under which you run the benchmarks.

[[general-considerations]]
=== General considerations

In order to acquire the most accurate results possible we reccommend to
run benchmarks on clean system without any necessary applications
running.

Currently the Yangtools benchmarks project contains only benchmarks for
benchmarking InMemoryDataTree component which is considered as core
DataStore component.

[[tools-used-for-benchmarking]]
=== Tools used for benchmarking

Currently the Yangtools project uses
http://openjdk.java.net/projects/code-tools/jmh/[JMH] tool for building,
running, and analysing nano/micro/milli/macro benchmarks written in Java
and other languages targetting the JVM. If you are interested in writing
your own benchmarks you can learn from various sources like:
http://java-performance.info/jmh/[Java Performance Tuning Guide]
