[[technical-architecture]]
== Technical Architecture

...

[[installation-guide]]
== Installation Guide

[[make-sure-you-have-an-account]]
=== Make sure you have an account

While you can pull code anonymously, if you want to push it (or edit the
wiki) you will need to
https://identity.opendaylight.org/carbon/user-registration/index.jsp?region=region1&item=user_registration_menu[get
an account].

[[gerrit-setup]]
=== Gerrit Setup

Code reviews are enabled through Gerrit.
OpenDaylight Controller:Gerrit Setup[Set up Gerrit] for use if you wish
to use ssh. If you wish to use https,
OpenDaylight Controller:Setting up HTTP in Gerrit[Set up Gerrit to use
HTTPS].

Note: You will need to perform the
OpenDaylight Controller:Gerrit Setup[Gerrit Setup] before you can access
git via ssh as described below.

[[pull-code-via-ssh]]
=== Pull code via ssh

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
git clone ssh://${ODL_USERNAME}@git.opendaylight.org:29418/yangtools.git;(cd yangtools; scp -p -P 29418 ${ODL_USERNAME}@git.opendaylight.org:hooks/commit-msg .git/hooks/;chmod 755 .git/hooks/commit-msg;git config remote.origin.push HEAD:refs/for/master)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[pull-code-with-https]]
=== Pull code with https

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/yangtools.git;(cd yangtools; curl -o .git/hooks/commit-msg https://git.opendaylight.org/gerrit/tools/hooks/commit-msg;chmod 755 .git/hooks/commit-msg;git config remote.origin.push HEAD:refs/for/master)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[installation-troubleshooting-link]]
== Installation Troubleshooting (link)

...

[[build-the-code]]
== Build the code

You are going to want to increase the memory available to maven, the
settings on the Jenkins build server are:

--------------------------------------------------
export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
--------------------------------------------------

Below is the top level build line for yangtools project:

--------------------------------
(cd yangtools;mvn clean install)
--------------------------------

[[tutorial-how-to]]
== Tutorial / How-To

...

[[command-line-interface]]
== Command Line Interface

...

[[programmatic-interfaces]]
== Programmatic Interface(s)

...
