[[major-features]]
=== Major Features

Hydrogen release marks the first release of the collection of YANG
tools. The following features have been delivered:

* Parser of http://tools.ietf.org/html/rfc6020[RFC6020]-compliant files
along with a set of regression tests
* Definition of a YANG Binding Specification for Java for representing
YANG-modeled data, RPCs and notifications
* Definition of a revision-aware model-independent data representation
of YANG-modeled data
* Maven plugin for compile-time interface and implementation of YANG
Binding Specification for Java
* Run-time component for mapping Java Binding Specification objects
from/to the model-independent representation
* Run-time component for mapping XML documents objects from/to the
model-independent representation
* OSGi repackaging of ANTLR 4.0 runtime stripped of GUI-related
dependencies
* Java meta-model of YANG model language
* A set of YANG extensions for improving naming of generated code
* A set of YANG models extracted from
https://tools.ietf.org/html/rfc6021[RFC6021] and
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[draft-clemm-netmod-yang-network-topo-01]

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

YANG tools are kept completely portable and require only a Java-7
compliant JVM to run. The Maven plugin requires Maven version 3.0.4 or
later.

[[for-development]]
==== For Development

YANG tools is developed as a normal Java project, but it makes heavy use
of https://www.eclipse.org/xtend/[Xtend] language. While development is
possible with bare tools, Eclipse with Xtend plugin is recommended.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

* During the development of Hydrogen release a number of issues have
been identified in the Java Binding Specification:
** Using the same name for groupings and containers in the same context
results in invalid code (issues #138, #157, #295)
** The specification contains a static get() method, conflicting with
JMX implementation
** Binding's handling of unsigned types could be improved with Guava's
Unsigned types
** The translation of choice/case statements requires users to use
instanceof and explicit typecasts, leading to run-time errors due to
missed spots in refactoring
** The exact mapping of YANG lists to Set/Map/List is not completely
satisfactory

The implementation has been tested extensively with its downstream
projects (openflowjava, bgpcep) and works reasonably well for complex
models. There are a few known bugs which will be addressed in the next
bugfix release.
