Issue tracking should not only be used for bug / defect reporting, but
also for better visibility into projects and to ease cross-team
management of work. Community, contributors and commiters on projects
could benefit from better use of tools which are available to
Opendaylight, such as https://bugs.opendaylight.org[Bugzilla] or
https://git.opendaylight.org[Gerrit], if we will keep our Bugzilla and
Gerrit well-maintained.

Aim of this document is to provide common grounds for better tracking of
open issues, feature requests and milestones for participating projects.
Most of described processes are in practice for link:YANG Tools[YANG
Tools] and Controller project and was used during
Simultaneous Release:Helium Release Plan[Helium release] for these
projects. Team working on project benefited from better insight into
open issues, closed issues etc.

[[issue-types]]
== Issue Types

Each reported issue, work item or overall target could be represented as
an issue.

[[topic]]
=== Topic

Topic bug is overarching concern, which is continuously addressed and
may span several release cycles. Usually it could be achieved by proving
tag to concrete bugs, but (bugzilla does not support public tags).

Topic has always following properties:

* *Summary* starts with _"Topic:"_
* *Severity* is always _Enhancement_

This type of bug is usually blocked by actual milestones (preferably) or
bugs which addresses concrete work items.

Using Bugzilla link *Show dependency: tree* could provide quick insight
what could be done / is proposed / planned to address particular
concern.

[[examples]]
==== Examples

Existing examples are:

*
*

[[milestone]]
=== Milestone

Milestone represents delivery of larger functionality block, which
itself could be decomposed into several tasks. Milestones usually have
one-to-one mapping to
https://wiki.opendaylight.org/view/Simultaneous_Release:Per-Project_Lithium_Release_Plan_Template#Release_Deliverables[Deliverables
in Simultaneous Release plan].

* _Summary_ starts with _"Milestone:"_
* _Severity_ is always _Enhancement_

This type of issue is usually blocked by normal issues
(#Bug,#Improvement or #New_Feature or actual milestones (dependencies,
could be cross-project) which addresses concrete work items.

[[examples-1]]
==== Examples

Existing examples are:

` * `

[[bug]]
=== Bug

Bugs represents defect in already existing implementation, this bugs are
mostly freeform, but following properties are recommended:

* *Issue Type* is _Bug_
* *Severity* is NOT _enhancement_

[[new-feature]]
=== New Feature

New feature to implement. Difference between Improvement and New Feature
is sometimes bit blury, but new feature usually manifests in addition of
new public APIs / UI to be consumed by external projects.

* *Issue Type* is _New Feature_

[[improvement]]
=== Improvement

Improvement in existing functionality. Difference between Improvement
and New Feature is sometimes bit blury, but improvement usually DOES NOT
introduce new public APIs / UI to be consumed by external projects.

* *Issue Type* is _Improvement_

[[change-request]]
=== Change Request

Change in existing functionality, such as changing behaviour.

* *Issue Type* is _Change Request_

[[task]]
=== Task

Task is actually catch-it-all type of the concept for issues which do
not fall into previous categories.

* *Issue Type* is _Task_

[[best-practices]]
== Best Practices

Usual structure is:

* Release Plan Milestone (defined as option for Lithium-M2)

:* User-defined Milestones (See #Milestone), with *Target Milestone* set
to Release Plan Milestone (eg. _Lithium-M3_ if milestone represents
deliverable for Lithium M3).

::* New Features

::* Improvements

::* Change Requests

::* Tasks

[[tie-in-with-release-plan]]
=== Tie-in with Release Plan

Lithium release plan still requires Wiki page and Google Spreadsheets to
be properly filled up, but Wiki ang Google Docs are disconnected from
Gerrit and Bugzilla (Gerrit to Bugzilla tie-in exists).

[[issue-structure]]
==== Issue structure

In order to have best tie-in into simultaneous release plan following
structure is proposed (nested level blocks item on previous level):

* Release Milestone - Overarching milestone, representing release of
project, during Simultaneous Release.

:* Release Plan Milestone (e.g. Lithium-M2) - Milestone representing
Simultaneous Release plan milestone. This one is usually blocked by
deliverables milestone.

::* Deliverable Milestones (See #Milestone), with *Target Milestone* set
to Release Plan Milestone (eg. _Lithium-M3_ if milestone represents
deliverable for Lithium M3).

:::* New Features - New features to be implemented in order to achieve
this deliverable.

:::* Improvements - Improvements in existing functionality required to
achieve this deliverable.

:::* Change Requests - Change requests to be addressed by this
deliverable.

:::* Tasks - Any other tasks, such as documentation, design, etc.

These milestones should be linked from Release Plan wiki page as part of
Deliverable description.

[[recommendations-for-milestones]]
==== Recommendations for Milestones

* If milestone *depends on other milestone/deliverable*, this should be
properly captured in Bugzilla as depends/block relationship. This is
true even for cross-project milestones. (Developers of projects have
better visibility what is affected by their deliverables, without
reading each and every release plan).
* If milestone *delivers feature / public API* - milestone summary
SHOULD clearly state
Simultaneous Release:Lithium Release Plan#Definitions[type of API (
Provisional / Tentative)].

[[example]]
==== Example

Imagine we have standard project named *Example*, which is new to
Opendaylight, plans to use Openflow protocol with Sample extension (it
is offset 2 project, bar project is offset 1 project), and have standard
phases such as design, prototype, API freeze, code freeze.

* BUG-1 Milestone: Lithium Release of Example (target-milestone:
Lithium)

:* BUG-2 Milestone: Deliver Lithium M2 Deliverables (target-milestone:
Lithium-M2, blocks BUG-1)

::* BUG-3: Architecture & Design of Example (target-milestone: Lithium
M2, blocks BUG-2, Issue Type: Task)

::* BUG-4: Finalize Lithium Release plan (target-milestone: Lithium M2,
blocks BUG-3, Issue Type: Task)

:* BUG-5 Milestone: Deliver Lithium M3 Deliverables (target-milestone:
Lithium-M3, blocks BUG-1)

::* BUG-6 Implement Feature A (target-milestone: Lithium-M3, blocks
BUG-7, Issue Type: New Feature)

::* BUG-7 Implement Feature B (target-milestone: Lithium-M3, blocks
BUG-8, Issue Type: New Feature)

::* BUG-8 Implement Feature C (target-milestone: Lithium-M3, blocks
BUG-5, Issue Type: New Feature)

:* BUG-9 Milestone: Deliver Lithium M4 Deliverables (target-milestone:
Lithium-M4, blocks BUG-1)

::* BUG-10 Finalize Provisional API for Feature A (target-milestone:
Lithium-M4, blocks BUG-9,depends on BUG-6, Issue Type: Improvement)

::* BUG-11 Finalize Provisional API for Feature B (target-milestone:
Lithium-M4, blocks BUG-9,depends on BUG-7, Issue Type: Improvement)

::* BUG-12 Finalize Provisional API for Feature C (target-milestone:
Lithium-M4, blocks BUG-9,depends on BUG-8, Issue Type: Improvement)

:* BUG-13 Milestone: Deliver Lithium M5 Deliverables (target-milestone:
Lithium-M5, blocks BUG-1)

::* BUG-14 Improve performance of Feature A and B (target-milestone:
Lithium-M5, blocks BUG-13,depends on BUG-6,BUG-7, Issue Type:
Improvement)

::* BUG-15 Make code comply to best practices (target-milestone:
Lithium-M4, blocks BUG-9,depends on BUG-6,BUG-7, Issue Type:
Improvement)
