[[overload-protection]]
= Overload Protection

[[rationale-and-usecase-scenarios]]
== Rationale and Usecase Scenarios

Typically on OpenFlow interface, there is likelihood of heavy packet-ins
spikes due to scenarios like links going down, switches going down
(thereby, potentially invalidating the pre-computed path-based flow
rules) etc. Combining this with ongoing traffic across the topology the
spike of packet-in rate punted towards controller could be very high and
steep.

There could be other scenarios which can trigger spikes of packet-ins
apart from above example.

So, it becomes essential to protect the controller from becoming
unstable due to these spikes. One way would be to spread the load. But
that is a discussion related to clustering. But, it would still be
prudential to have a overload-protection as do all communications server
systems do.

There are multiple means of realizing overload-protection

[[solution-approaches]]
== Solution Approaches

Some options which could be considered are (there could be other
options, but following ones are relatively simpler)

*Option 1*: when OpenFlow messages are constructed from raw wire bytes,
timestamp the objects with "creation-time". At plugin layer, compare
current-time with the creation time of the message. This would indicate
that how long message has "waited" in individual queues. By setting a
higher and a lower threshold for wait times in queue, we can decide to
process / drop the packet-in

*Option 2*: monitor the resource loading - CPU utilization, memory etc
and based on a higher and lower watermarks, sense the load. Action part
could be to drop packet-ins when load is between lower and higher
thresholds

[[event-dampening]]
= Event Dampening

[[rationale-and-usecase-scenarios-1]]
== Rationale and Usecase Scenarios

This has more to do with the events which occur very frequently due to
instability in switch/network layer. For example, flapping of switch
links is one such case.

If multiple applications start reacting to the link-up down events at a
very high rate, the possibility of system becoming unstable is very
high. So, selective Openflow (or any events from southbound interfaces)
must be dampened before escalating the same to the applications layer.

[[solution-approaches-1]]
== Solution Approaches

One solution approach is discussed here (this example explains the
edge-device-side implementation - but, in principle, this can also be
useful on controller) -
http://www.cisco.com/c/en/us/td/docs/ios/12_0s/feature/guide/s_ipevdp.html

Of course, side-effects of event-dampening has to be analyzed further.
But, this can be a useful feature on the controller side.
