[[current-status]]
= Current Status

Brief of the current statistics collection module (Statistics-Manager)
is present
https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin:Statistics[here]

Current implementation sends all statistics collection request to all
the connected node at the same time. This results in flooding of
response from all the connected nodes and causing CPU spikes as well as
stressing MD-SAL operational data store.

[[ideas-for-improvement]]
= Ideas for improvement

Current approach is not scalable and has performance issues. To reduce
statistics collection resource consumption and make it more scalable

* Dynamic stats polling interval based on the number of connected nodes
and number of entries in the respective tables (Flow tables, Group,
Meter ]
* For each connected node spread out stats polling throughout the stats
collection interval
* Only start stats collection after the previous collection of the stat
has finished (i.e. do not be timer-driven)
* Different periodic interval for each statistics type
** Flow statistics is crucial compared to aggregate flow stats
*** Keep the initial periodic interval High for low priority statistics
*** and make it adaptive according to amount of data received in
response

image:Statistics Manager Optimization Ideas.ppt[Statistics Manager
Optimization Ideas
decks,title="Statistics Manager Optimization Ideas decks"]
