[[what]]
== What

Members of the OpenDaylight Technical Steering Committee (TSC) elect a
Chairperson each year.

[[who]]
== Who

This election and nomination process is limited to TSC Members. Any TSC
Member can nominate themselves, run for election, and vote in the
election for the TSC Chair.

[[how]]
== How

The election process occurs in two phases; the Nomination phase, and the
Election phase.

[[nomination-phase]]
=== Nomination Phase

1.  An email is sent from the Election Coordinator (Phil Robb) to the
TSC distribution list for OpenDaylight and the subject line is tagged
with the keywords [TSC CHAIR PERSON NOMINATION].
2.  Any TSC Member may nominate themselves to stand for election. Note
that no one can nominate another person to run for election.
3.  To submit a nomination, the TSC Member must reply-all to the
original nomination email stating their interest to stand for the
election.
4.  All nominees are invited to publish their Picture, Biography, and
Statement of Intent on the election wiki page so that the other members
of the TSC, and the community, can learn more about the candidate and
their intentions for the role of TSC Chairperson. The nominee ordering
on the election wiki page will be in ascending alphabetical order by
last name.
5.  The length of the Nomination phase is 5 days. This clock starts when
the email described above is sent.

[[election-phase]]
=== Election Phase

1.  Immediately upon the close of the Nomination Phase, an email will be
sent from the Election Coordinator (Phil Robb) via the Condorcet
Internet Voting Service (CIVS) to each TSC member. This email will have
the subject line: “Poll: OpenDaylight TSC Chairperson Election”. This
email acts as an invitation by the CIVS for each TCS Member to vote.
This voting invitation is only sent to the TSC Members. The TSC mailing
list is not cc-ed on this email as per the CIVS process. Included in
this election invitation will be a pointer to the Election wiki page
which contains the names, pictures, biographies, and
statements-of-intent for each of the candidates. The email also has
instructions and a private URL where each TSC Member is sent to vote.
2.  At the CIVS-provided voting URL, each voter will rank the
candidates, where a smaller-numbered rank means that the voter prefers
that choice more. Once the ranking is complete, the voter will press the
“Submit ranking” button to complete the voting process.
3.  The Election Phase will remain open for 5 days from the time the
invitation-to-vote email is sent by the CIVS.
4.  Once the Election Phase has completed, the results of the election,
including the votes cast by all participating TSC members, will be made
available to the TSC mailing list.

Category:TSC
