This page is currently a Draft of the proposed process pending approval
from the TSC.

[[committer-promotions]]
=== Committer Promotions

While the initial committers on a project are nominated at project
formation, it is expected that community members will emerge as willing
committers over time. Committer nomination and promotion must take place
according to http://www.opendaylight.org/project/tsc/charter[Section 7
of the TSC Charter]. This page intends to describe how the charter shall
be interpreted in a practical step by step manner.

[[prior-to-nomination]]
==== Prior to nomination

Project contributors who are interested in promotion to project
committer should first approach the project lead and committer community
to discuss their interest and receive feedback on their work within the
community.

To be promoted to committer the TSC will be looking for the nominated
contributors to have demonstrated:

* A history of active contributions in the project
* Has demonstrated to the project lead and committer a deep knowledge of
the code and project best practices
* Has shown a willingness to lead and coordinate amongst peers

Once the project lead and committers feel the candidate has demonstrated
these items to the point where a nomination may occur the project lead
or a delegate may initiate a nomination for committer promotion amongst
the projects current committers.

[[nomination-for-committer-promotion]]
==== Nomination for committer promotion

The nomination for committer promotion begins with the project lead or
delegate sending an e-mail to the -dev list requesting the committers on
the project vote on the nomination.

The nomination e-mail should begin with a clear topic name and be
followed by a statement of motivation. The statement of motivation
should describe any achievements or activities the contributor has
performed of notable value for the project and may include a link to a
git-log of the nominee's activity history. More than one contributor may
be nominated in one nomination e-mail.

The e-mail may take the following form:

* From:
* To: -dev@lists.opendaylight.org
* Nomination for new Committer(s):
* The motivation for nominating to committer on the project is due to a
long history of providing value to the project through consistent high
quality and valuable contributions. I provide a link to the relevant
contributions.

Once the e-mail has been sent the nomination stands until a clear
majority vote for or against the nomination has been met, or the
nominator withdraws the nomination. _Note that since the vote is binary
rather than an election, simple +1,0,-1 voting conforms to the Condorcet
or single transferable vote methods outlined in
http://www.opendaylight.org/project/tsc/charter[Section 6 of the TSC
charter]._

[[addressing-the-tsc-with-a-successful-nomination]]
==== Addressing the TSC with a successful nomination

At the completion of a nomination process, if the nominee was
successful, the nominator should address the TSC via the TSC mailing
list tsc@lists.opendylight.org by forwarding the nomination e-mail along
with a summary of the outcome of the committer votes. _Note: Please
provide a link to a publicly accessible mailing list thread showing the
votes._

The TSC Chair should be contacted to identify a suitable time-slot at
the available opportunity for the TSC to take a formal vote on the
nomination.

The TSC will consider the following as relevant to the decision:

* The nomination process and the outcome as captured by the project lead
or delegate
* The number of committers on the project and the need for an increase
in committers
* Any community feedback received around the nomination or nominee

The TSC will vote on the nomination according to the voting methods
outlined in http://www.opendaylight.org/project/tsc/charter[Section 6 of
the TSC charter]. The outcome of the vote will be recorded in the
minutes of the meeting and any associated reasoning for the decision
that has been taken. If the vote on the TSC is successful the
OpenDaylight administrative team will be informed and the nominee will
be promoted to project committer.

If the vote on the TSC was not successful the reasoning and motivations
for the decision will be captured in the meeting minutes. The project
lead may choose to act to redress the captured reasoning and once ready
nominate the contributor once more following the above described
process.

Category:TSC
