Welcome to the OpenDaylight Technical Steering Committee (TSC) Wiki.
This page hosts all information associated with the OpenDaylight TSC
including meeting schedules, Agendas, and Minutes. To see a list of who
is on the TSC along with their Biographies, please go to the
http://www.opendaylight.org/project/governance/tsc[TSC] page at
http://www.opendaylight.org[OpenDaylight.org]. To contact the TSC, send
an email to the mailto:tsc@lists.opendaylight.org[TSC] mail list.

[[meeting-schedule-and-logistics]]
== Meeting Schedule and Logistics

TSC meetings are held weekly for one hour on Thursday mornings at
10:00am Pacific Daylight Time (-7:00 GMT). Meetings are held using WebEx
for screen sharing and audio and IRC for recording meeting minutes.

* Meeting URL:
https://meetings.webex.com/collabs/meetings/join?uuid=MA3SRND964PIX06V2LS3SXX3RE-9VIB

* Access Information
** Meeting number: 194 548 370
** Meeting password: This meeting does not require a password.

* Audio Connection
** 1-855-244-8681 Call-in toll-free number (US/Canada)
** 1-650-479-3207 Call-in toll number (US/Canada)
** Access code: 194 548 370

* IRC
** 1.  opendaylight-meeting room on https://freenode.net/[freenode]
** Web-based IRC client:
https://webchat.freenode.net/[https://webchat.freenode.net/]

[[agenda]]
== Agenda

The next TSC meeting is scheduled for May 28th, 2015 with the following
agenda:

* Start the Recording
* Agenda Bashing, Roll Call, Action Items (all, 5 minutes)
** call for any new topics for the agenda
** yet-to-be-done action items are restated here
** Last week's minutes:
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-05-21-16.59.html[https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-05-21-16.59.html]
* Updates (all, 15 minutes)
** Events (Phil)
*** OpenDaylight events page:
http://www.opendaylight.org/news/events/[http://www.opendaylight.org/news/events/]
** lithium and stable/helium updates (George/Thanh)
*** link:Weather[Weather page]
***
https://docs.google.com/spreadsheets/d/1KPpO9LH539Vlcoa4RvLa6PPCdLifi5JD-ihRhlybqeo/edit#gid=676729675[blocking
bugs]
***
https://lists.opendaylight.org/pipermail/tsc/2015-May/003014.html[Helium
to Lithium migration]
** System Integration and Testing (Luis)
** Infrastructure (Andrew/Thanh)
* Committer Promotions (All, 0 minutes)
** none this week
* Creation Reviews (All, 0 minutes)
** none this week
* Moving to JIRA? (Robert Varga, 10 minutes/remaining time)
** See this mailing list thread starting
https://lists.opendaylight.org/pipermail/tsc/2015-February/002554.html[here]
and continuing
https://lists.opendaylight.org/pipermail/tsc/2015-March/002730.html[here]
and
https://lists.opendaylight.org/pipermail/tsc/2015-May/003106.html[here].
* Beryllium Planning/Board Requests: (All, remaining time)
**
https://lists.opendaylight.org/pipermail/tsc/2015-May/002985.html[Discussion
topics mailing list thread] and
https://docs.google.com/document/d/1oqR04DTPp38X9qLKngPecKNKJCFBi-k1uTXLG_q2X7g/edit[document]
** Source materials:
*** Simultaneous_Release:Lithium_Release_Plan[The Lithium Release Plan]
***
Simultaneous_Release:Lithium_Release_Plan#Lessons_from_Hydrogen.2C_Helium_and_Lithium_for_future_releases[Lessons
Learned]
***
https://lists.opendaylight.org/pipermail/tsc/2015-April/002824.html[This
mailing list thread]
***
https://lists.opendaylight.org/pipermail/tsc/2015-April/002931.html[Sample
dates for a Lithium-like Beryllium Release plan]
** Board Requests of the TSC:
***
https://lists.opendaylight.org/pipermail/tsc/2015-March/002806.html[Board
requests]
***
https://lists.opendaylight.org/pipermail/tsc/2015-March/002818.html[Some
ideas for how to respond]
***
https://lists.opendaylight.org/pipermail/tsc/2015-March/002740.html[Colin's
use case pipeline email with ppt slides]
*** Possible actions: (largely drawn from
https://lists.opendaylight.org/pipermail/tsc/2015-March/002818.html[https://lists.opendaylight.org/pipermail/tsc/2015-March/002818.html])
**** Draft language for details about how projects can, will and should
move to mature and what they need to do
**** Draft processes around developing, selecting and encouraging work
on use cases
**** Draft per-release definitions for "kernel" and "important" projects
(or maybe features)

[[intended-topics-for-next-week]]
=== Intended Topics for Next Week

Proposed topics for June 4th, 2015:

* Creation Reviews:

[[future-topics]]
=== Future Topics

* Creation Reviews:
** Project Proposals:Netconf[Netconf]
(https://lists.opendaylight.org/pipermail/project-proposals/2015-February/000253.html[Proposed
on 2/17/2015])
** Project Proposals:MD-SAL[MD-SAL]
(https://lists.opendaylight.org/pipermail/project-proposals/2015-February/000268.html[Proposed
on 2/19/2015])
** Project Proposals:Openflowplugin-extension-circuitsw[OpenFlow
Extensions in support of Circuit Switching]
(https://lists.opendaylight.org/pipermail/project-proposals/2015-April/000305.html[Proposed
on 4/3/2015])
* Progress on Technical Debt/Integration (10 minutes)
** Resolving cyclic dependencies (Thanh, 5 minutes)
** Release/version bump automation (Thanh, 5 minutes)
* Code Maturity and Lifecycle Issues
** Helium (and future release) Support Lifetime (Ryan/all, 10 minutes)
** Promotion Process (all, 15 minutes)
*** Encouraging projects to move to mature
*** How we want to deal with overlapping functionality and/or resolve
the "singularity" clause in the TSC policy.
*** Discussion: Proposals for more detailed guidelines for promotion
from incubation
* Future Release Mechanics (All, 15 minutes)
** Is a simultaneous release tenable at our current (and future size).
** If not, what is the replacement?
** See thread here:
https://lists.opendaylight.org/pipermail/tsc/2015-January/002410.html[https://lists.opendaylight.org/pipermail/tsc/2015-January/002410.html]
** Also see notes/recording/slides from the 2/2/2015
Tech_Work_Stream:Main[TWS Meeting]
* Security Response Process (Chris Wright, ?? minutes)
** Grant's draft is here:
[https://stackedit.io/viewer#!provider=gist&gistId=74e6a40bfbb449d7f78e&filename=opendaylight_security_process
https://stackedit.io/viewer#!provider=gist&gistId=74e6a40bfbb449d7f78e&filename=opendaylight_security_process]
** Suggested edits are here:
https://pad.opendaylight.org/p/Security_Response_Process[https://pad.opendaylight.org/p/Security_Response_Process]
(use your ODL credentials to login)
** A simpler document that the Linux kernel uses is here:
[https://www.kernel.org/doc/Documentation/SecurityBugs
https://www.kernel.org/doc/Documentation
* Post-Helium Release Hot Issues
** Code Quality
*** and its relationship to "core" projects
** TSC Operation, Project Scope and promotion framework(s)
*** General Project Scope: What are the important ("core") components of
ODL?
*** Need to discuss and build a framework around
**** What duplicative/overlapping functionality and goals are to be
allowed within Incubation projects?
**** How is that duplication resolved as one or more projects move from
incubation to mature?
**** Providing clear boundries for projects on a case by case basis
regarding scope (based on the framework that is TBD) so that projects
are clear on what they can and cannot do
**** More generally, additional clarity and process around project
promotion
* *TSC/TWS call timing/timezones*
* *API Review Process*
* *Waiting on External Actions:*
** Vendor-specific Code (Steve Dean, 10 minutes)
***
https://lists.opendaylight.org/pipermail/tsc/2015-February/002618.html[mailing
list thread]
** OVSDB Rename (Madhu/all, minutes)
** Update on http://www.google.com/patents/US8078707[Network management
using hierarchical domains] patent issues (0 minutes if legal isn't
ready)

[[archived-topics]]
=== Archived Topics

* OpenDaylight Best Practices (Colin/all, 10 minutes)
** link:Developer Best Practices[Developer Best Practices]
** link:Logging Best Practices[Logging Best Practices]
** link:General Style Guidelines[General Style Guidelines]
** link:OpenDaylight Java Style[OpenDaylight Java Style]
**
CrossProject:HouseKeeping Best Practices Group:Main[CrossProject:HouseKeeping
Best Practices Group:Main]
***
CrossProject:HouseKeeping Best Practices Group:Project layout[CrossProject:HouseKeeping
Best Practices Group:Project layout]
***
CrossProject:HouseKeeping Best Practices Group:Versioning[CrossProject:HouseKeeping
Best Practices Group:Versioning]
****
CrossProject:HouseKeeping Best Practices Group:Versioning:Automated Weekly Releases[CrossProject:HouseKeeping
Best Practices Group:Versioning:Automated Weekly Releases]
***
CrossProject:HouseKeeping Best Practices Group:Integration Test[CrossProject:HouseKeeping
Best Practices Group:Integration Test]
***
CrossProject:HouseKeeping Best Practices Group:Whitespace[CrossProject:HouseKeeping
Best Practices Group:Whitespace]
**
https://lists.opendaylight.org/pipermail/controller-dev/2014-July/005766.html[Proposed
Committer Checklist]
** Additional points
*** Keep the "download, unzip, and just run" deployment model, i.e.,
allow for external dependencies, but don't require them
*** Keep things cross-platform, i.e., avoid JNI if you can

[[tsc-membership]]
== TSC Membership

The TSC is comprised of technical leaders within the OpenDaylight
development community coming from one of three groups.

1.  Project Leaders from OpenDaylight projects designated as "Core"
projects within the
http://www.opendaylight.org/project-lifecycle-releases[OpenDaylight
Project Lifecycle]
2.  Two Committer-At-Large members elected annually:
TSC:Committer-At-Large_Election_Process[ Committer-At-Large Election
Process]
3.  One member designated by each Platinum Member of the OpenDaylight
Project

The TSC is led by the TSC Chairperson. The TSC Chair is elected
annually: TSC:Chair_Election_Process[ TSC Chair Election Process]

The current members of the TSC can be viewed
http://www.opendaylight.org/project/governance/tsc[here].

[[tsc-chair-election]]
=== 2014 TSC Chair Election

The 2014 TSC Chair election has concluded. Colin Dixon is the new TSC
Chair

[[committer-at-large-tsc-elections]]
=== 2014 Committer-At-Large TSC Elections

The 2014 Committer-At-Large Elections have concluded. The 2014
Committer-At-Large TSC Members are:

* Colin Dixon
* Ed Warnicke

[[how-to-run-an-electronic-condorcet-election-within-your-project]]
=== How To Run an Electronic Condorcet Election within your project

A common reason to run a Condorcet Election within a project is to elect
a Project Lead. Please refer to the following page for detailed
instructions on running such an election.

* https://wiki.opendaylight.org/view/CondorcetElection4PTLs[Condorcet
Election Process For Project Leads]

[[tsc-procedures-and-processes]]
== TSC Procedures and Processes

[[project-proposals-and-creation-reviews]]
=== Project Proposals and Creation Reviews

The Project Proposals:Main[project proposals] page includes lots of
useful information including
Project_Proposals:Main#Instructions_For_Submitting_New_Proposals[how to
propose a project],
Project_Proposals:Main#Guidelines_for_your_Creation_Review[how to
schedule and what to expect from your creation review], as well as
Project_Proposals:Main#After_your_Creation_Review[what to do after a
successful creation review].

[[committer-promotion-process-for-contributors-draft]]
=== Committer promotion process for contributors (Draft)

The draft version of the committer promotion process can be found at the
TSC:Committer Promotion Process[committer promotion process] page. This
page is currently in a draft version for comment by the community
pending approval from the TSC.

[[committer-removal-process-draft]]
=== Committer removal process (Draft)

_Note: According to the
http://www.opendaylight.org/project/tsc/charter[TSC charter], the power
to remove committers lies with project leads. However to log these
actions and provide visibility, the TSC asks to be informed (by mail to
the TSC mailing list) of these events and provides the following
guidelines._

In general, a project seeking to remove a committer should do so with
consent of the committer being removed. This has happened several times
in the past, most commonly with the committers themselves instigating
the process.

*If a committer would like to be removed, the general approach is:*

1.  The committer should e-mail the project's -dev mailing list letting
the project and other committers know their intention.
* This is useful both to keep people in the loop and to potentially
address any issues that might cause the committer to stay.
* _DO NOT_ try to coerce a committer who wants to leave into staying if
they would rather not.
2.  Assuming the project and committer agree that the removal makes
sense, the project lead should send an email to the TSC mailing list
notifying the TSC of the removal.
* Make sure to include a link to the public e-mail documenting the
committer asking to be removed.
3.  Finally, the committer must notify the helpdesk
(helpdesk@opendaylight.org) with the request to have their committer
privileges removed for that project.

*If the project instigates the removal, the general approach is:*

_NOTE: In general, the TSC advises against removing committers without
them instigating the process for reasons other than inactivity._

1.  The project lead should privately reach out to the committer and
explain what's going on and get their opinion on how to proceed.
* This should be done privately first to avoid any embarrassment if
something is merely a misunderstanding.
* _DO NOT_ try to coerce them into stepping down.
* In most cases, people that have simply not had as much time as they
expected are happy to step down voluntarily.
2.  Assuming they are willing to step down, make sure they send an
e-mail to the project's -dev mailing list stating that publicly.
3.  The project lead should send an email notifying the TSC to remove
the committer to the TSC mailing list
* Make sure to include a link to the public e-mail from the committer
saying they would like to step down.
4.  Finally, open a helpdesk (helpdesk@opendaylight.org) ticket to have
their committer privileges removed for that project including the link
to the e-mail sent to the TSC mailing list.

*If the project and committer disagree:* +
In the event that the committer can't be reached or is unwilling to step
down, the http://www.opendaylight.org/project/tsc/charter[TSC charter]
states that "A Committer who is disruptive, or has been inactive for an
extended period (e.g., six or more months) may have his or her Committer
status revoked by the project leads." We would like to avoid doing this
in a non-consensual way if at all possible, so please reach out to the
TSC to figure out how to proceed. If you would rather figure out the
right approach in private first, feel free to e-mail the TSC chair
directly.

[[project-archiving-and-termination-reviews]]
=== Project Archiving and Termination Reviews

According to the OpenDaylight
http://www.opendaylight.org/project-lifecycle-releases[Project Lifecycle
and Releases] document, a project can be moved to the Achived state by a
Termination Review. The termination review can be instigated either by a
vote of the project committers or by the TSC. For the TSC to instigate
the termination review, the project must have no remaining committers or
have had no commits to their repository for more than 18 months.

In either event, a *Termination Proposal must be posted for two weeks*
containing the following information:

1.  The the project is being terminated
2.  A description of the impact on other projects, users, and
communities as well as how they will be mitigated
3.  Where the project will be archived to

[[meeting-minutes]]
== Meeting Minutes

A complete list of the IRC TSC meeting minutes and logs since July 24th,
2014 should be here:

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/[Minutes
From 2014]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/[Minutes
From 2015]

[[specific-dates]]
=== Specific Dates

April 30th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-30-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-30-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/7aTQBkEbzSckTLrUMrGm5t0QGPFU090yokgnwdu2v4a00000[Link
To WebEx Recording]

April 23rd, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-23-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-23-17.00.log.html[Meetbot
Log]
* No WebEx Recording

April 16th, 2015

* No TSC Meeting Due To Hackfest

April 9th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-09-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-09-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/WmrsFZJk2bK6YHSHglX4pBekRs9wvDb9Lc65Vj5C_pW00000[Link
To WebEx Recording]

April 2nd, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-02-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-04-02-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/CuS_820pmWwqEKP3GFGAsg8cfkEOUg0wLpraZq-7CRe00000[Link
To WebEx Recording]

March 26th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-26-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-26-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/4IObY46LfmO_H3_CdAOcI-_3A9TtHfNB-SvP9spz-MG00000[Link
To WebEx Recording]

March 19th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-19-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-19-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/xzkb_ZJWlVs475vVxb2h7eWq0rJxZkyQTfbZFpv5QO400000[Link
To WebEx Recording]

March 12th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-12-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-12-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/BHZNWRnuIXtFNB9TPpcH4dnfEIAdfd1cbQwm9urvkZO00000[Link
To WebEx Recording]

March 5th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-05-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-03-05-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/5DfII1CgXZNMTkr2Vb0WpW8EPcYqy7U2Zph9v2BeDSC00000[Link
To WebEx Recording]

February 26th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-26-18.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-26-18.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/lXIi-hT_U1ci7KTnvJWatjnimuDDEPmyu54uSAyS-YS00000[Link
To WebEx Recording]

February 19th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-19-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-19-18.00.log.html[Meetbot
Log]
* No WebEx Recording Available

February 12th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-12-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-12-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/qfsOJz-fBunfcZwxgayw2Gk_oSsBYULsddrxk8UDvK800000[Link
To WebEx Recording]

February 5th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-05-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-02-05-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/6BKfv3BD2pwTd60RN-u2oRF6a3F_YV2KbHrH7mUOnFO00000[Link
To WebEx Recording]

January 29th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-29-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-29-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/xoD9sBopk63KtstxOd4WYVV0z1RylbB3S0XAL0lm_hC00000[Link
To WebEx Recording]

January 22nd, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-22-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-22-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/vTfXtlG-wHXd-vxNFBVDjmV6Hei_DPnsd1LOIYQzkkq00000[Link
To WebEx Recording]

January 15th, 2015

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-15-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-15-18.00.log.html[Meetbot
Log]
* No WebEx Recording Available

January 8th, 2015

*
https://wiki.opendaylight.org/images/9/9d/Preview_of_Network_Intent_Compiler_Project2.pdf[Network
Intent Composition Project Preview Presentation]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-08-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2015/tsc/opendaylight-meeting-tsc.2015-01-08-18.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/8JlP2JSb0BwrPrTv6tFufSrNtI7PPCkACfthUZUoI9W00000[Link
To WebEx Recording]

*TSC Meetings from 2014*

December 18th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-18-17.57.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-18-17.57.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-18-17.57.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/ICWMGAhGxa9VKGJQCPDFu_yVy046Pap7okDJVHzu_d800000[Link
To WebEx Recording]

December 11th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-11-17.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-11-17.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-11-17.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/dBUSnXAxBT7nEH-582Qyslcd_5QWOFrKyJifawPrIBu00000[Link
To WebEx Recording]

December 4th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-04-18.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-04-18.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-12-04-18.00.log.html[Meetbot
Log]
* No WebEx Recording Available

November 20th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-20-18.03.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-20-18.03.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-20-18.03.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/BXwQ_K0zPFRcuIobXuMYLeNwKcK0L9SgqnXRU7ywynC00000[Link
To WebEx Recording]

November 13th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-13-17.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-13-17.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-13-17.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/pWVcBg9yqCX8tMjOMc_Wq62-5EqEnIFbBQYeG63iB9000000[Link
To WebEx Recording]

November 10th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-10-17.31.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-10-17.31.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-11-10-17.31.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/qO5nXC-sCpc29T-hf8V7qb4tWmqZf_dK4quAVhG6GwG00000[Link
To WebEx Recording]

November 6th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_11_6_2014/opendaylight-meeting-tsc_11_6_2014.2014-11-06-17.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_11_6_2014/opendaylight-meeting-tsc_11_6_2014.2014-11-06-17.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_11_6_2014/opendaylight-meeting-tsc_11_6_2014.2014-11-06-17.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/c3_-86nYWp27ietFZGzQBihZ-H-FcrdC_ifzVN7HeKq00000[Link
To WebEx Recording]

October 30th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-30-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-30-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-30-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/uWqP4_u4oiOeJBzlIBQm712GoykV1EAdBlhHnLFAzaS00000[Link
To WebEx Recording]

October 23rd, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-23-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-23-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-23-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/Rv25jTP5687zL01rdekZu11Cm2TKcfg677vsC1p9XL000000[Link
To WebEx Recording]

October 16th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-16-17.02.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-16-17.02.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-16-17.02.log.html[Meetbot
Log]
* Link To WebEx Recording Unavailable

October 9th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-09-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-09-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-09-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/ZnBV4Uila4o3FWC0cKY_jg3rsYF4Zr9P7puWPwUNxXC00000[Link
To WebEx Recording]

October 2nd, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-02-15.02.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-02-15.02.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-02-15.02.log.html[Meetbot
Log]

October 1st, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-01-15.04.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-01-15.04.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-10-01-15.04.log.html[Meetbot
Log]

September 30th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-30-15.08.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-30-15.08.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-30-15.08.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/AnI98dcULTuWzIehoYPrj-3cpGAtgf_Oi_9xWSlXJX400000[Link
To WebEx Recording]

September 29th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-29-19.39.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-29-19.39.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-29-19.39.log.html[Meetbot
Log]

September 25th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-25-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-25-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-25-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/SVk2o8twiFKUH5Y-AxyxXTIVvVP_CGulbtiC5NyAX-i00000[Link
To WebEx Recording]

September 18th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-18-16.58.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-18-16.58.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-18-16.58.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/0E5nTV9K80bQoG6Lnl9WSOHxkRTxORKiJUnlIj-O6EC00000[Link
To WebEx Recording]

September 11th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-11-17.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-11-17.01.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-11-17.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/FdoiKrou1CqoAN2l8fUlT3daszmnI_1q7cZ_a7UOhuC00000[Link
To WebEx Recording]

September 4th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-04-17.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-04-17.01.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-09-04-17.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/HSVCYOHoanzUZ4z_mqFG06YSBElI7v83BBkgPh2U_MS00000[Link
To WebEx Recording]

August 28th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-28-16.56.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-28-16.56.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-28-16.56.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/Pyw9lNzgzYwiTSpYUeQR_V3srd1bwZnlSYLG7-K23Y400000[Link
To WebEx Recording]

August 21st, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_08_21_2014/opendaylight-meeting-tsc_08_21_2014.2014-08-21-17.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_08_21_2014/opendaylight-meeting-tsc_08_21_2014.2014-08-21-17.01.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_08_21_2014/opendaylight-meeting-tsc_08_21_2014.2014-08-21-17.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/ZJ6GZn5-djaVS7HI-OqTYINVuHihF3UVXFMeyAGTedq00000[Link
To WebEx Recording]

August 14th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-14-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-14-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-14-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/JVTiValfHzmHAOOwnS0zHNoHDHb-JFdMAj_aFnBESDm00000[Link
To WebEx Recording]

August 7th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-07-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-07-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-08-07-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/SE2IkEOiP4hxWrwcerS-yoJLy4pQMq38KuUBr3t7fPC00000[Link
To WebEx Recording]

July 31st, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-31-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-31-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-31-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/foXw-Gx1E2JgG8tOpdVkOE1NqZ2zC29bfVCDcDSpxYe00000[Link
To Webex Recording]

July 24th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-24-16.58.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-24-16.58.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc/opendaylight-meeting-tsc.2014-07-24-16.58.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/5to4b6pxQacYQ8Yt1v8q4I8R377gXELurrxgeoaCjdm00000[Link
to WebEx Recording]

July 17th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_7_17/opendaylight-meeting-tsc_7_17.2014-07-17-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_7_17/opendaylight-meeting-tsc_7_17.2014-07-17-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_7_17/opendaylight-meeting-tsc_7_17.2014-07-17-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/FD0wkyaqtEULvgU2i3ilf2uAqKgk0Azy45KYnW8f46G00000[Link
To WebEx Recording]

July 10th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting_2014_07_10/opendaylight-meeting-weekly_tsc_meeting_2014_07_10.2014-07-10-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting_2014_07_10/opendaylight-meeting-weekly_tsc_meeting_2014_07_10.2014-07-10-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting_2014_07_10/opendaylight-meeting-weekly_tsc_meeting_2014_07_10.2014-07-10-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/dBjHhl1QgbSsSfDzbVnUPZnm2jo5q9InYJSsZq4pDA000000[Link
To WebEx Recording]

July 3rd, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_2014_07_03/opendaylight-meeting-tsc_2014_07_03.2014-07-03-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_2014_07_03/opendaylight-meeting-tsc_2014_07_03.2014-07-03-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_2014_07_03/opendaylight-meeting-tsc_2014_07_03.2014-07-03-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/Pie4QZ4bX4c4elIGvS-zV6Dxi5qhJCSSzGQkraMQIQC00000[Link
to WebEx Recording]

June 26th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/6_26_2014_tsc/opendaylight-meeting-6_26_2014_tsc.2014-06-26-16.57.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/6_26_2014_tsc/opendaylight-meeting-6_26_2014_tsc.2014-06-26-16.57.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/6_26_2014_tsc/opendaylight-meeting-6_26_2014_tsc.2014-06-26-16.57.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/6EYn_oUP1gUBQQtx5Io79k0eTiQ7-g0gwsyCX2RAHNy00000[Link
to WebEx Recording]

June 19th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_mtg_2014_06_19/opendaylight-meeting-tsc_mtg_2014_06_19.2014-06-19-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_mtg_2014_06_19/opendaylight-meeting-tsc_mtg_2014_06_19.2014-06-19-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_mtg_2014_06_19/opendaylight-meeting-tsc_mtg_2014_06_19.2014-06-19-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/5lIWgtjOtbaRt28VXdtJfW6PinUZ_MwPkCFPFCBQB5u00000[Link
to WebEx Recording]

June 12th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_2014_06_12/opendaylight-meeting-tsc_meeting_2014_06_12.2014-06-12-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_2014_06_12/opendaylight-meeting-tsc_meeting_2014_06_12.2014-06-12-16.59.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_2014_06_12/opendaylight-meeting-tsc_meeting_2014_06_12.2014-06-12-16.59.log.html[Meetbot
Log]

June 5th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_weekly_meeting/opendaylight-meeting-tsc_weekly_meeting.2014-06-05-17.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_weekly_meeting/opendaylight-meeting-tsc_weekly_meeting.2014-06-05-17.01.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_weekly_meeting/opendaylight-meeting-tsc_weekly_meeting.2014-06-05-17.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/GaTEnsnZZzj4TdVFnMffw3uhBPKpirOwyH0CoQTeC8S00000[Link
To WebEx Recording]

May 29th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_5_29_2014/opendaylight-meeting-tsc_meeting_5_29_2014.2014-05-29-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_5_29_2014/opendaylight-meeting-tsc_meeting_5_29_2014.2014-05-29-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_5_29_2014/opendaylight-meeting-tsc_meeting_5_29_2014.2014-05-29-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/oJSLhU9wyVZ7aVpEI56HJRBR2OZJWttNjzDYeFK9mDK00000[Link
To WebEx Recording]

May 15th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_mtg___05_15_2014/opendaylight-meeting-opendaylight_tsc_mtg___05_15_2014.2014-05-15-16.59.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_mtg___05_15_2014/opendaylight-meeting-opendaylight_tsc_mtg___05_15_2014.2014-05-15-16.59.txt[Meetbot
Minutes (Text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_mtg___05_15_2014/opendaylight-meeting-opendaylight_tsc_mtg___05_15_2014.2014-05-15-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_0145671888E6C6A309911BFB00968C5C790E86DF00B4F46993064479D427C01592DDAB9BAD6697629BABF3C9AC6AA36353BA5633D62ECCFD38AE7F00FD34C69B4211F7D668D84E38844E5AEF35C7B6B8_47F9F5B0919ABA6FB9E28CA89FB1BF0AE356D8CC[Link
To WebEx Recording]

May 8th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_meeting_2014_05_08/opendaylight-meeting-opendaylight_tsc_meeting_2014_05_08.2014-05-08-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_meeting_2014_05_08/opendaylight-meeting-opendaylight_tsc_meeting_2014_05_08.2014-05-08-17.00.log.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight_tsc_meeting_2014_05_08/opendaylight-meeting-opendaylight_tsc_meeting_2014_05_08.2014-05-08-17.00.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_3E67FE4CCEE5BC65FB3C2D5E19F142EA235A75647D46A771665C6268C957D32DDE80CE0C7FD03FCB7C11ED10280579B4FC84CFE0BE840C71B68F16EB387CA2BEB783CA42B8D7DE67B8CD6E6C01F96477_2A57F964A4C6AB146EB13E7EDF5C503BC5DEE27D[Link
to WebEx Recording]

May 1st, 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting/opendaylight-meeting-weekly_tsc_meeting.2014-05-01-16.57.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting/opendaylight-meeting-weekly_tsc_meeting.2014-05-01-16.57.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/weekly_tsc_meeting/opendaylight-meeting-weekly_tsc_meeting.2014-05-01-16.57.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_CA822D135F46E8AFA2F53E69F933F9BE78F768B3592F9CF9B13463338A2BE75DE3AD3667BE8EF926073BD7AE280BD9C12170BD1910BCA563492978ECBBBA5B30F6880E090E25C12DD7898B3369B54FD9_40AD1C0BFC6E5146EC8E1A76655E7D669DD0ABAE[Link
To WebEx Recording]

April 24th, 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_4_24_2014/opendaylight-meeting-tsc_meeting_4_24_2014.2014-04-24-16.58.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_4_24_2014/opendaylight-meeting-tsc_meeting_4_24_2014.2014-04-24-16.58.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tsc_meeting_4_24_2014/opendaylight-meeting-tsc_meeting_4_24_2014.2014-04-24-16.58.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_611B3BDD326A6B2A6A57A44FC9895DFC6E3EA93D4BFB84AB5A99960342B2B38013F1FF9BBA7550D8461EC567DB61C99DC49C185CA821C7FF35582476F4028127C1B9F6AFCE998B5C13A38DF976633F8F_3683088150EA3E3333B122A4F70D45F04C4AF9A1[Link
To WebEx Recording]

April 17th, 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-17-16.56.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-17-16.56.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-17-16.56.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_D5C3497CFD5D50EDBF255DE1D6DAA9A39C6A493E7AD842EBBB07C9ADDEC11A4948F403FE657FB37C1C588A522165F980BA0AB4F477FE980C7816A092376E3DEA518FA613D536B9BB81D1D67F341F7B82_314C4C72D231FE4216B18DC94AC5E00F308D6F74[Link
To WebEx Recording]

April 10th, 2014

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-10-17.00.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-10-17.00.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-10-17.00.log.txt[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_1DA38F0CFAFE2A458B206589F9626B0B597FD98F77C29BC8A715AC5CA70FF2348ECB5C07712D22921D7383DDB15448A0567950E4BE8D4A144B1FAB78446AD4E71E387A4A14C4D61D865C83082315C125_280F50EBAB80E5E54687315DA703A473839BED31[Link
to WebEx Recording]

April 3rd, 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-03-17.03.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-03-17.03.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-03-17.03.log.html[Meetbot
Log]

March 20th, 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-20-16.55.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-20-16.55.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-20-16.55.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_5791FDF0CD0D0541F6177EEA823C87994C037DF4AD9A992210F9BC6389F569D30A7CB355A9F2F6FC754C7FE2FE0ECFACEE12AC2BE658005EBFF2AE09641D43E90DADA5C0A969FF74992883B72A2AA64A_5A8207DAF1FB0D3BEDE5CE2D67131EA22C633251[Link
to Webex Recording]

March 13th 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-13-16.59.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-13-16.59.txt[Meetbox
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-13-16.59.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_991E1BC2D1164403570EC4278650C63E4B828A6FA491360DE35445CE8DEAE925C77B8B81EF56CEC3959902C5ECD43F21A1FABC8AEFEF19696C514A0A2AB987F8565086D9EC060F0F55B22D175D374AE2_335D8E1582C60629C5A959D1DE4001FBF3A1DCE4[Link
to Webex Recording]

February 27th 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-27-18.01.html[Meetbot
Minutes]
** Note as an addition to the Meetbot minutes that at approximately 1
hour, 22 minutes into the recording, TSC delegate Jan Medved made the
comment that there was a requirement to have all projects that are in
OpenDaylight covered by the EPL license. A project may be convered by
mulitiple licenses, but everything that is in OpenDaylight should have
the EPL license.
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-27-18.01.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-27-18.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_3242D76A485B9A4AD5DBB10DE0C06F0B4814699BBC86DF136D3A82CDE83D6C1101F67CC0F2A80394FFD5CDE500A5EACEEC88F28195BA3A0E0543B3A315D39F8DC3788D51964CCBA9601C2534AAE86522_9BFBB500772FF306BBC90E340D402D2EBF00815E[Link
to Webex Recording]

February 20th 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-20-18.01.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-20-18.01.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-20-18.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_49E618CAC3F2326B2249F27FDAEDE8AFF3E38641F5709FADA01FCD045FD1F41C6AF486CE47B71927ABB2F667A6D20075BB6BCC7184CE18A3A9C2A50533171FD8080791ACD86E7711FD66BEC6B1135925_694B491C852C85E45632026A5F25B8CF3504D0A8[Link
to Webex Recording]

February 13th 2014

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-13-18.22.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-13-18.22.txt[Meetbot
Minutes (text)]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-02-13-18.22.log.html[Meetbot
Log]
* WebEx Recording Unavailable Due To WebEx Site Errors

Media:TSC_2014-01-30_Minutes.pdf[January 30th 2014]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_8375EDA7B66180D386272A8EE5ECB284B27C39A19B2816123BC1EC53219BD7B8CBF2894455DC906BE0525B78E88F0B52C2775426F4A5006B303F5BEAD6591F1E261FA95D0E737FFA45BA9414B1F20B7A_993424F22C4A89BCAF07527E0A09399D0AB0FBDE[Link
To Webex Recording]

Media:TSC_2014-01-23_Minutes.pdf[January 23rd 2014]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_66F9137DFAE8B9E908C375973FA54A14B874B96705D9F834CD5F8E85DCA31AA6D8A7C7DA4A1B063C0CB323AF570E9D5A009F729FE559F5CE090486904FCECFE8D4D7C9E60BE43ED24B9EA06E9E40B534_7A2317ECB735CE604F4CD981353CB321950034F1[Link
To Webex Recording]

Media:TSC_2014-01-16_Minutes.pdf[January 16th 2014]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_70D0F7D041E26B18F722F82EE8E0E4B6BF040D8162D4BCB0C3B672149178B4E54FC9AE287034831175875CE3F291796AE8BDDA71D3CA9CF16E609F26B3C713D6D1E4F4E010D913AA10B957C83EEE3CA4_DA5BB8A9E087CAFB9DF0871B4EBCEA3A0D98B509[Link
To Webex Recording]

Media:TSC_2014-01-09_Minutes.pdf[January 9th 2014]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_904121E3DD739B315B980D4FD5EB714C4EC96B2D362DE5BAE9ED87D6FCDFCE79B5EC47A092ECAA862407488BDAA6679F38D8364CE0D1E8F3975246DF9F210B367A929CA68B663B8459B3EFE90583558A_E06FEE116D6EA12C3ACC22039199E9F7BA26869D[Link
To Webex Recording]

Media:TSC_2014-01-06_Minutes.pdf[January 6th 2014]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_2A67E3E17D7B470DE80F85A54BDB2571286EC1AB5DCE0C0FB4992597AF41F67348B6AF704812D01AE6902504E53F00EBEE01C80BF9F790BB2E8C197F5D79659A1EFCB511559D1345396794786AE8307A_15C89597643B7285D53599CCE6F929DBDA17C199[Link
To Webex Recording]

*TSC Meetings from 2013*

Media:TSC_2013-12-19_Minutes.pdf[December 19th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_A832BC1146970A62A04D170A566236423B55216D6A0ABFA95788E31D26CA3758876703B1FB57FBC7D2D9FB37E4E370AC21451A0F032A6C880F67C5B36910C0F88AA2DC2FDDA0018DDBDAB5E530D71F61_7BE7123749F420D79CA803108AF95D980A5EC3A1[Link
To Webex Recording]

Media:TSC_2013-12-12_Minutes.pdf[December 12th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_BD338C691969D4B3461B3582D5E49E1F0CB81AE46B6210E60EFAA847FEDC693DEF20418AB942750C3003C50BA853FE8493CAD47FEF0AA9A76873D0211B581D76D2053C9DC7ACFA90A907AFBF09460076_8B8F073FADCF23E5081CFBC8CA4F1E7852F208C4[Link
To Webex Recording]

Media:TSC_2013-12-05_Minutes.pdf[December 5th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_E2660AA5E9EE294C6D1817A3765F1722B70C60B343D8A60C2271357F37B305F36211E5BC026E4D70E890D2F6971E36914B687B215B620E49803D923365A14155686FC121EB23B9717BB0DA29DCD0BB39_03423D0EA76792BFE96A5777BE1CE3E43BDB3C84[Link
To Webex Recording]

Media:TSC_2013-11-21_Minutes.pdf[November 21st 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_04BACFDF8B6F8E4CCABE57E331B64FDE84BB65C1997195AC7C600F768A1BDE784C8C3484FCDC8C4E68F1E25B804146790DDFDDC82DAD58C0B6EAA8178A9B038F37FB8AE8E8D55EE31CD1DF8680712827_B2811195633BBADE5EEB208E50760011FD88DD14[Link
To Webex Recording]

Media:TSC_2013-11-14_Minutes.pdf[November 14th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_1E03E06803E62CBD535D35AC12D8C87A07E43D06910219AEC414E3718FF23A8AAEFEB7EB43D2436E8779218AF38A1827E9E4B28455BAB4C21E9C5BEF5056A3B7173E7971479E1808BB58D8BC46CE6452_DA8F203428C2FC827B0897ED512178666805F68B[Link
To Webex Recording]

November 7th, 2013

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_2911A867C67C96B01374BB6BDB223CA154E9900B788CCF8B5766FD5BFEED33B2DB2EDFDACF109079A1128EEB8164BF21C077644A2B86CA6ABAA2033995E1F1A16C0E87DF0A889F1F22B889B66226EB79_10CEE35366743CA4FE39FE014E40FB7A4541599C[Link
To Webex Recording]

Media:TSC_2013-10-31_Minutes.pdf[October 31st 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_5012A5288474E834602A51FCACF3B47A0E6D4B75EA80B7635B05AA315ADDB35451C7F3495EB695FB63C5BC683790FDE9550123CCCA0A8EC2F26D62E4705F610A3178363330EDEABC3F3DC2B37DEC535E_0DADA95EE37BA3DC410C75A676BD503D8548A314[Link
To Webex Recording]

Media:TSC_2013-10-24_Minutes.pdf[October 24th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_DD40C0E21A481047570B9F6E0789828F43F381F0E831D9A4931C17F539E826B60E27FA337E57413039F2988F161AE772AF1EE13966A3B98866C6A5C922FEAFF27AFCAEB8CB005E159B539524859D6535_48122881B733C9A606C5E45E53BEE87A57782FC6[Link
To Webex Recording]

Media:TSC_2013-10-10_Minutes.pdf[October 10th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_2D55C0D66791664A6B2D4C73E559589F082FD63554B3CF0749F26563F102404E9B0DC60914AE829993D20C77C4D3475A73DE9564A6BBA2E03F1C7FF64B534C152EBFE7174F26E35E07573B55881BABFE_F737696FF8E727D0FE32BC665C77B1D6EB2C3176[Link
To Webex Recording]

Media:TSC_2013-10-03_Minutes.pdf[October 3rd 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_4A6BE9B5033E4799AA67CD55ED26E3C1816743B3F191643C612336FE914303862121571643838461136AD3808F5EAA26F78417750EA38F2E4631600B9CA97B544147AC8054177374C1E443F64D222205_0B1E9E0E12561D01BAEBD29F1C777617DA081AFA[Link
to Webex Recording]

Media:TSC_2013-09-26_Minutes.pdf[September 26th 2013]

*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_08ECAA1E5026B7955D4E9365A5F895FDD315A1E8020975223BC61B8E7F3FBD1BF6B19F7F65E671F6C7B5D02E5D3E84EBC5D16043404074B91B5CF82E9CDBD0FC6152DF25E28E643A9CED880EDEB28724_3370255A2209C943DF223DF7085AE30B5943B6DE[Link
to Webex Recording]

Media:TSC_2013-09-05_Minutes.pdf[September 5th 2013]

*
https://meetings.webex.com/collabs/files/playRecording?encryptedDocID=0_5C1404CEE7AF4E92F35367CCBA21FEE866A7704540228CA701D5B4B9E7FCC3C597DF2AECA2910ADEB66116933FF4598A_988FDDD448F225A2981215060E41052BAC875C30[Link
to Webex Recording]

Media:TSC_2013-08-29_Minutes.pdf[August 29th 2013] +
Media:TSC_2013-08-22_Minutes.pdf[August 22nd 2013] +
Media:TSC_2013-08-15_Minutes.pdf[August 15th 2013] +
Media:TSC_2013-08-08_Minutes.pdf[August 8th 2013] +
Media:TSC_2013-08-01_Minutes.pdf[August 1st 2013] +
Media:TSC_2013-07-25_Minutes.pdf[July 25th 2013] +
Media:TSC_2013-07-18_Minutes.pdf[July 18th 2013] +
Media:TSC_2013-07-11_Minutes.pdf[July 11th 2013] +
Media:OpenDaylight_TSC_Meeting_20130627_1704_1.arf[June 27th Link To
WebEx Recording] +
Media:TSC_2013-06-20_Minutes.pdf[June 20th 2013] +
Media:TSC_2013-06-13_Minutes.pdf[June 13th 2013] +
Media:TSC_2013-05-30_Minutes.pdf[May 30th 2013] +
Media:TSC_2013-05-23_Minutes.pdf[May 23rd 2013] +
Media:TSC_2013-05-16_Minutes.pdf[May 16th 2013] +
Media:TSC_2013-05-09_Minutes_.pdf[May 9th 2013] +
Media:TSC_2013-05-02_Minutes.pdf[May 2nd, 2013] +
Media:TSC_042513_Minutes.pdf[April 25th, 2013] +
Media:TSC_041813_Meeting_Minutes.pdf[April 18th, 2013] +
Media:TSC_041013_Meeting_Minutes.pdf[April 10th, 2013] +

[[all-tsc-wiki-pages]]
== All TSC Wiki Pages

 category = TSC ordermethod = categorysortkey order = ascending

Category:TSC
