[[introduction]]
== Introduction

The OVSDB Plugin integration project is a project for OpenDaylight that
will implement the Open vSwitch Database RFC 7047 management protocol,
allowing the Southbound configuration of vSwitches. OVSDB was created by
Ben Pfaff, Bruce Davie, and Martin Casado at Nicira Networks. The
project consists of a library, along with various plugin usages.

[[getting-started-with-opendaylight-ovsdb-plugin-network-virtualization]]
== Getting Started with OpenDaylight OVSDB Plugin Network Virtualization

We are still in development and need resources from developers to
network persons, or anyone in between. Required are all contributions
from upstream code to docs and tutorials. Take a look at the Getting
Started links and jump on #opendaylight-ovsdb on irc.freenode.net and
start hacking!

* OVSDB:Installation_Guide[Installation Guide]
* OVSDB:User_Guide[User Guide]
* OVSDB:Developer_Guide[Developer Guide]

[[weekly-ovsdb-plugin-meeting-open-to-all]]
== Weekly OVSDB Plugin Meeting (Open to All)

* Weekly on Tuesday from 12:00-13:00 PST/PDT | 15:00-16:00 EST/EDT |
19:00-20:00 UTC during Daylight Time/20:00-21:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MBEJOM1CNOV3D3YXNTHITWGVNZ-9VIB&rnd=199048.03614[Webex
meeting link]
** Meeting Number: 196 498 415
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-ovsdb

[[high-level-design]]
== High-Level Design

* OVSDB_Integration:Design[High-Level architecture and design]

* OVSDB Integration:Mininet OVSDB Tutorial[OVSDB Integration:Mininet and
OVSDB Tutorial]

* http://www.youtube.com/channel/UCMYntfZ255XGgYFrxCNcAzA[OVSDB Hangout
Recording Weekly Calls and Informational]

* https://wiki.opendaylight.org/view/OVSDB_Integration:Design[OVSDB
Integration Architecture]

Links to recordings on different OVSDB aspects:

*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=I0SKFYQXT1UH61UF5FH80687RD-9VIB[Sonar
for static analysis, unit and integration test coverage, high-level
overview of all OVSDB bundles]
* http://youtu.be/A0C3stQnh4g[L3 Walkthrough]
*
http://www.flaviof.com/blog/work/how-to-odl-with-openstack-part1.html[Openstack
integration and pipeline in net-virt]
* https://bluejeans.com/s/7X2f/[Schema and library walkthrough]
* https://www.youtube.com/watch?v=vACyoKdefRs[Plugin walkthrough]
* http://www.youtube.com/watch?v=ieB645oCIPs[Original OVSDB walkthrough]

[[example-usage]]
== Example Usage

OVSDB is a critical protocol for Network Virtualization with Open
vSwitch forwarding elements.

File:Ovsdb-architecture.png[framed|center]

[[clone-the-ovsdb-plugin-repository]]
== Clone The OVSDB Plugin repository

---------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/ovsdb.git

OR

git clone ssh://<username>@git.opendaylight.org:29418/ovsdb.git
---------------------------------------------------------------

[[people]]
== People

* Sam Hague , shague on irc.freenode.net
* Flavio Fernandes flaviof on irc.freenode.net
* Kyle Mestery mestery on irc.freenode.com

[[issues]]
== Issues

* jsonrpc4j does not provide the bidirectional capabilities that we need
to create calls, and respond to echo as well. There are several options
being investigated:

:# Integrate http://deavid.github.io/bjsonrpc/[bjsonrpc] via Jython

:# Create our own json-rpc implementation.

:# Add the functionality needed to jsonrpc4j

* Continue working on fully integrating the full functionality of the
protocol.

[[technical-overview]]
== Technical Overview

[[json-rpc-overview]]
=== JSON-RPC Overview

JSON-RPC is a remote procedure protocol which allows the OVSDB client to
call methods that exist on the OVSDB server, allowing the provisioning
of bridges, ports, interfaces, tunnels, and more in the database. An RPC
request is formatted as follows:

code,java------------------------------ code,java
{
    "method":<string>,
    "params":[<object>],
    "id":<string> or <integer>
}
------------------------------

This will invoke the value given in "method" on the server, passing in
the parameters specified in order. Parameters can be simple strings, or
complicated JSON objects. RPC response messages also have a standard
formatting:

code,java------------------------------ code,java
{
    "result":[<object>],
    "error":<error>,
    "id":<string> or <integer>
}
------------------------------

The library https://code.google.com/p/jsonrpc4j/[jsonrpc4j] will
serialize and de-serialize these standard messages. However, but for
most situations, as the "result" value is likely to be a complicated
JSON object, we will need to deserialize the messages ourselves. Also,
for many methods, the "params" array will contain JSON objects; we
define these as actual Java objects which then get deserialized into
JSON strings on the server side. Using the Jackson streaming API, it is
possible to call methods and process responses using only string
manipulation, but this method is inconvenient, and is currently not
used. The
http://tools.ietf.org/html/draft-pfaff-ovsdb-proto-02#section-4.1[ovsdb
protocol draft] describes the methods and their responses in detail.

[[example-add-bridge-and-associated-port-and-interface]]
==== Example: Add bridge and associated port and interface

code,javascript----------------------------------------- code,javascript
{
    "method":"transact",
    "params":[
        "Open_vSwitch",
        {
            "row": {
                "bridges": [
                    "named-uuid",
                    "new_bridge"
                ]
            },
            "table": "Open_vSwitch",
            "uuid-name": "new_switch",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "type": "internal"
            },
            "table": "Interface",
            "uuid-name": "new_interface",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "interfaces": [
                    "named-uuid",
                    "new_interface"
                ]
            },
            "table": "Port",
            "uuid-name": "new_port",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "ports": [
                    "named-uuid",
                    "new_port"
                ]
            },
            "table": "Bridge",
            "uuid-name": "new_bridge",
            "op": "insert"
        }
    ],
    "id":1234
}
-----------------------------------------

[[see-also]]
== See also

Project Proposals:OVSDB-Integration[OVSDB Integration project proposal
page]

http://tools.ietf.org/html/draft-pfaff-ovsdb-proto-02#section-4.1[OVSDB
Protocol Draft]

OpenDaylight_OVSDB:Helium_Release_Plan[Helium Release Plan]

OpenDaylight_OVSDB:Lithium_Release_Plan[Lithium Release Plan]

OVSDB:dlux_mininet[DLUX and Mininet]

OVSDB:Helium_and_Openstack_on_Fedora20[Helium and OpenStack on Fedora
20]

OVSDB:MDSAL_Southbound[ MDSAL Southbound Plugin]

OVSDB:Integration_Testing[ Integration Testing]

OVSDB:Northbound[ Northbound]

OVSDB:Running Tempest Tests[ Running Tempest Tests]

OVSDB:Tempest Tests daily Results[ Tempest Tests daily Results]
