[cols="^",]
|=======================================================================
|'''OVSDB Plugin Network Virtualization Integration Facts '''

a|
*Project Creation Date:* July 18th, 2013 *Lifecycle State:* Incubation +
*Primary Contacts:* +
* Madhu Venugopal  +
* Brent Salisbury  +
*Project Lead:* N/A +
*Committers:* +
* Madhu Venugopal

* Brent Salisbury
* Evan Zeller
* Giovanni Meo
* Kyle Mestery
* Aswin Nair
* Dave Tucker  +

*IRC:* freenode.net #opendaylight-ovsdb +
*Mailing List:* ovsdb-dev@lists.opendaylight.org +
*Meeting Info:* +
* When: Tuesdays at 12 noon Pacific Time

* Where:
**
https://www.google.com/url?q=https%3A%2F%2Fmeetings.webex.com%2Fcollabs%2F%23%2Fmeetings%2Fdetail%3Fuuid%3DMBEJOM1CNOV3D3YXNTHITWGVNZ-9VIB&ust=1394558455728000&usg=AFQjCNFJgpkNrlTmjel3b_f1PWudSgZXxg[Link
To Webex]
** Webex Meeting number: 196 498 415
** 1-855-244-8681 Call-in toll-free number (US/Canada)
** 1-650-479-3207 Call-in toll number (US/Canada)

|=======================================================================

[[introduction]]
== Introduction

The OVSDB Plugin integration project is a project for OpenDaylight that
will implement the Open vSwitch Database RFC 7047 management protocol,
allowing southbound configuration of vSwitches. OVSDB was created by Ben
Pfaff, Bruce Davie and Martin Casado at Nicira Networks. The project
consists of a library, along with various plugin usages.

[[getting-started-with-opendaylight-ovsdb-plugin-network-virtualization]]
== Getting Started with OpenDaylight OVSDB Plugin Network Virtualization

We are still in development and have needs from developers to network
guys or anywhere in between. All contributions from upstream code to
docs and tutorials. Take a look at the getting started links and jump on
#opendaylight-ovsdb on irc.freenode.net and get started hacking!

* OVSDB:Installation_Guide[Installation Guide]
* OVSDB:User_Guide[User Guide]
* OVSDB:Developer_Guide[Developer Guide]

[[weekly-ovsdb-plugin-meeting-open-to-all]]
== Weekly OVSDB Plugin Meeting (Open to All)

* Weekly on Tuesday from 12:00-13:00 PST/PDT | 15:00-16:00 EST/EDT |
19:00-20:00 UTC during Daylight Time/20:00-21:00 UTC during Standard
Time
**
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MBEJOM1CNOV3D3YXNTHITWGVNZ-9VIB&rnd=199048.03614[Webex
meeting link]
** Meeting Number: 196 498 415
** Meeting password: This meeting does not require a password.
** Call-in toll-free number (US/Canada): 1-855-244-8681
** Call-in toll number (US/Canada): 1-650-479-3207
** IRC: Freenode/#opendaylight-ovsdb

[[high-level-design]]
== High-Level Design

* OVSDB_Integration:Design[High-Level architecture and design]

* OVSDB Integration:Mininet OVSDB Tutorial[OVSDB Integration:Mininet and
OVSDB Tutorial]

* http://www.youtube.com/channel/UCMYntfZ255XGgYFrxCNcAzA[OVSDB Hangout
Recording Weekly Calls and Informational]

* https://wiki.opendaylight.org/view/OVSDB_Integration:Design[OVSDB
Integration Architecture]

[[example-usage]]
== Example Usage

OVSDB is a critical protocol for Network Virtualization with Open
vSwitch forwarding elements.

File:Ovsdb-architecture.png[framed|center]

[[clone-the-ovsdb-plugin-repository]]
== Clone The OVSDB Plugin repository

---------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/ovsdb.git

OR

git clone ssh://<username>@git.opendaylight.org:29418/ovsdb.git
---------------------------------------------------------------

[[people]]
== People

* Brent Salisbury networkstatic on irc.freenode.net
* Evan Zeller evanz on irc.freenode.net
* Madhu Venugopal Madhu on irc.freenode.net
* Giovanni Meo
* Kyle Mestery

[[issues]]
== Issues

* jsonrpc4j does not provide the bidirectional capabilities that we need
to create calls, and respond to echo as well. There are several options
being investigated:

:# integration of http://deavid.github.io/bjsonrpc/[bjsonrpc] via Jython

:# Create our own json-rpc implementation.

:# Add the functionality needed to jsonrpc4j

* Continue working on fully integrating the full functionality of the
protocol.

[[technical-overview]]
== Technical Overview

[[json-rpc-overview]]
=== JSON-RPC Overview

JSON-RPC is a remote procedure protocol which allows our ovsdb client to
call methods that exist on the ovsdb server, allowing us to provision
bridges, ports, interfaces, tunnels, and more in the database. Any rpc
request is formatted as follows:

code,java------------------------------ code,java
{
    "method":<string>,
    "params":[<object>],
    "id":<string> or <integer>
}
------------------------------

This will invoke the value given in "method" on the server, passing in
the parameters specified in order. Parameters can be simple strings, or
complicated json objects. RPC response messages also have a standard
formatting:

code,java------------------------------ code,java
{
    "result":[<object>],
    "error":<error>,
    "id":<string> or <integer>
}
------------------------------

The library https://code.google.com/p/jsonrpc4j/[jsonrpc4j] will take
care of serializing and deserializing these standard messages for us,
but for most situations we will need to deserialize the "result" value
ourselves as it is most likely a complicated json object. Also, for many
methods the "params" array will contain json objects, we define these as
actual java objects which then get deserialized into json strings on the
server side. Using the jackson streaming API it is possible to call
methods and process responses using only string manipulation, but it is
less convenient and as of now we are not using this method. The
http://tools.ietf.org/html/draft-pfaff-ovsdb-proto-02#section-4.1[ovsdb
protocol draft] describes the methods and their responses in detail.

[[example-add-bridge-and-associated-port-and-interface]]
==== Example: add bridge and associated port and interface

code,javascript----------------------------------------- code,javascript
{
    "method":"transact",
    "params":[
        "Open_vSwitch",
        {
            "row": {
                "bridges": [
                    "named-uuid",
                    "new_bridge"
                ]
            },
            "table": "Open_vSwitch",
            "uuid-name": "new_switch",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "type": "internal"
            },
            "table": "Interface",
            "uuid-name": "new_interface",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "interfaces": [
                    "named-uuid",
                    "new_interface"
                ]
            },
            "table": "Port",
            "uuid-name": "new_port",
            "op": "insert"
        },
        {
            "row": {
                "name": "br1",
                "ports": [
                    "named-uuid",
                    "new_port"
                ]
            },
            "table": "Bridge",
            "uuid-name": "new_bridge",
            "op": "insert"
        }
    ],
    "id":1234
}
-----------------------------------------

[[see-also]]
== See also

Project Proposals:OVSDB-Integration[OVSDB Integration project proposal
page]

http://tools.ietf.org/html/draft-pfaff-ovsdb-proto-02#section-4.1[OVSDB
Protocol Draft]

OpenDaylight_OVSDB:Helium_Release_Plan[Release Plan]
