[[packet-handler]]
== Packet Handler

\1. packet decoding infrastructure that has base class for all
decoders. +
2. yang models and decoders for Ethernet, ARP, IPV4, IPV6. +

[[address-tracker]]
== Address Tracker

\1. Yang model that augments inventory node connector to store address
observations. +
2. currently it would store mac, Ip and vlan observed on each node
connector. +

[[network-loop-elimination]]
== Network Loop Elimination

\1. Augment node connector to have a spanning tree state (Discarding,
Forwarding) +
2. listen to topology changes and compute the MST based on current
topology. Each link addition or elimination would result is
reconstruction of MST. For MST it assumes the cost of each link is same
at this time. +
3. update the node connector augmentation with appropriate state.
(Discarding, Forwarding) , based links that are not present in MST +

[[l2-switch-main]]
== L2 Switch Main

\1. Track address: a module that leverages address tracker model to
store the observations in inventory tree by listening to ARP, IPV4, and
IPV6 packets. +
2. Transmit packet back: it would transmit the packet back to switch
using node connectors that are in 'Forwarding' state. +
3. write flows: Writes flow to the switch if both src and dest mac is
known in "ARP, IPV4, and IPV6" packets that it consumed in point 1. +
4. Delete flows: Listen to augmented node connector data changes for
state change, and delete flows forwarding to a node connector that is
marked as "Discarding" +

[[l2-switch-distribution]]
== L2 Switch Distribution

\1. Create a L2 Switch Distribution that loads all the bundles necessary
for L2 Switch app to run, also remove conflicting bundles from
controller distribution that may cause erroneous results. 2. Add DLUX UI
to this distribution, so that data added to the store can be viewed
easily.
