[[running-with-karaf---integration-build]]
== Running with Karaf - Integration Build

* *WIP*.

[[running-with-karaf---intent-distribution]]
== Running with Karaf - Intent Distribution

[[building]]
=== Building

\1. Clone the nic project from
https://git.opendaylight.org/gerrit/#/admin/projects/nic

\2. cd into nic

\3. mvn clean install

\4. cd into the distribution folder

\5. extract the target/nic-karaf-1.0.0-SNAPSHOT.tar.gz (or zip)

\6. run the binary target/nic-karaf-1.0.0-SNAPSHOT/bin

[[install-the-required-features]]
=== Install the required features

load the required features into the karaf instance:

`opendaylight-user@root>feature:install odl-nic-renderer-gbp`

[[demo-setup-environment]]
== Demo Setup Environment

reference:
https://wiki.opendaylight.org/view/Group_Policy:Building_and_Running

[[prerequesites]]
=== Prerequesites

* Vagrant

[[setup-the-vm]]
=== Setup the VM

* Prerequesite: a running instance of the intent with the GBP feature
installed. This should have come with the _odl-nic-renderer-gbp_ feature
in step *Building*.

* Clone https://github.com/sniggel/odl-intent-gbprenderer-testbed

`git clone `https://github.com/sniggel/odl-intent-gbprenderer-testbed.git[`https://github.com/sniggel/odl-intent-gbprenderer-testbed.git`]

* Modify and run the env.yaml to reflect your environment settings. In
this case, the network is 192.168.1.x and the controller is running on
192.168.1.143.

* Provision s1 and s2:

`vagrant up`

This will create Group Based-Policy Endpoints automatically by reading
the env.yaml file at vagrant provision time.

[[intents-operations]]
=== Intents Operations

* Import the intent collection (it should be in the postman directory of
the repository)

* Use the "Add intent with subjects, actions and constraints" to create
an intent

*Note:* Here we assume the end-point-group correspond to the GBP
endpoint groups. Modify the payload to reflect the endpoints:

`{  ` +
`  "intent:intent":{  ` +
`     "intent:id":"b9a13232-525e-4d8c-be21-cd65e3436033",` +
`     "intent:actions":[  ` +
`        {` +
`           "order":2,` +
`           "allow":{` +
`           }` +
`        },` +
`        {  ` +
`           "order":1,` +
`           "block":{` +
`           }` +
`        }` +
`     ],` +
`     "intent:constraints":[  ` +
`        {` +
`           "order":1,` +
`           "include-node":{  ` +
`              "include-selector":"node1"` +
`           }` +
`        },` +
`        {  ` +
`           "order":2,` +
`           "exclude-node":{  ` +
`              "exclude-selector":"node2"` +
`           }` +
`        }` +
`     ],` +
`     "intent:subjects":[  ` +
`        {  ` +
`           "order":1,` +
`           "end-point-group":{  ` +
`              "name":"1eaf9a67-a171-42a8-9282-71cf702f61dd"` +
`           }` +
`        },` +
`        {  ` +
`           "order":2,` +
`           "end-point-group":{  ` +
`              "name":"e593f05d-96be-47ad-acd5-ba81465680d5"` +
`           }` +
`        }` +
`     ]` +
`  }` +
`}`

[[verify-the-contract-creation]]
==== Verify the contract creation

*WIP*
