This document serves as the _Termination Proposal_ for the
OpenDaylight SDN Controller Platform (OSCP):Main[OpenDaylight SDN
Controller Platform (OSCP) project] as described in Section 2.3.5 of the
http://www.opendaylight.org/project-lifecycle-releases[Project Lifecycle
& Releases] document.

[[reason-for-archiving]]
== Reason for Archiving

The project has been inactive for over 18 months (the last merged patch
was on June 4th, 2013) as evidenced by the
https://git.opendaylight.org/gerrit/#/q/project:net-virt-platform+status:merged[list
of merged patches]. This meets the guidelines for a _Termination Review_
initiated by the TSC as described in Section 2.3.5 of the
http://www.opendaylight.org/project-lifecycle-releases[Project Lifecycle
& Releases] document. Further, we have contacted a representative of the
project about archiving the project and they
https://lists.opendaylight.org/pipermail/tsc/2015-February/002645.html[agreed
that this was the right course of action].

[[impact-on-other-projects-users-and-communities]]
== Impact on Other Projects, Users, and Communities

Since this project has been effectively inactive for 18 months, the
impact should be minimal with the exception of occasional people cloning
the repository or finding the wiki pages describing the project without
understanding that it is not currently maintained. Archiving the project
(and thus enabling some cleanup of wiki pages) will likely decrease
confusion.

[[mitigation-strategies]]
=== Mitigation Strategies

The TSC will attempt to mark wiki pages to clear show that the project
has been archived and the projects git repository will be renamed to
archived-net-virt-platform at it's archived location. Further, we will
add notes in both places pointing to alternate locations to get working
with the currently-maintained projects in OpenDaylight.

[[archive-location]]
== Archive Location

The project will be archived on the
https://github.com/opendaylight/[OpenDaylight github mirror] with the
project name changed from net-virt-platform to
archived-net-virt-platform.
