[[configuration-and-transaction]]
= Configuration and Transaction

The *Configuration* operation has three stages: +
1. First, a *Proposed* configuration is created; its target is to
replace the old configuration. +
2. Second, the Proposed configuration must be validated before it can be
committed. If it passes validation successfully, the Proposed the state
of the configuration will be changed to *Validated*. +
3. Finally, a Validated configuration can be *Committed* and the
affected modules can be reconfigured. +
 In fact, each configuration operation is wrapped in a *transaction*.
Once a transaction is created, it can be *configured*, that is to say. a
user can *abort* the transaction during this stage. After the
transaction configuration is done, it is committed to the *validation*
stage. In this stage, the validation procedures are invoked. If one or
more validations fail, the transaction can be reconfigured. On success,
the *second phase commit* is invoked. If this commit is successful, the
transaction enters the last stage, *committed*. After that, the desired
modules are reconfigured. If the second phase commit fails, it means
that the transaction is *unhealthy*: basically, a new configuration
instance creation failed, and the application can be in an inconsistent
state.

File:Configuration.jpg|Configuration states
File:Transaction.jpg|Transaction states

[[validation]]
== Validation

To secure the consistency and safety of a new configuration, and to
avoid conflicts, the configuration validation process is necessary.
Usually, validation checks the input parameters of a new configuration
and mostly verifies module-specific relationships. The validation
procedure results in a decision indicating whether the proposed
configuration is healthy.

[[dependency-resolver]]
== Dependency Resolver

Since there can be dependencies between modules, a change of a module
configuration can affect the state of other modules. Therefore, we need
to verify whether dependencies on other modules can be resolved. The
Dependency Resolver acts similar to dependency injectors. Basically, a
dependency tree is built.

[[apis-and-spis]]
== APIs and SPIs

In this section, the configuration system APIs and SPIs will be briefly
described.

[[spis]]
=== SPIs

*Module* org.opendaylight.controller.config.spi.Module is a common
interface for all modules: every module must implement it. The module is
designated to hold configuration attributes, validate them, and create
an instance of service based on the attributes. This instance must
implement AutoCloseable interface, owing to resources clean up. If the
module was created from an already running instance, it contains an old
instance of the module. The module can implement multiple services. If
the module depends on other modules, setters need to be annotated with
@RequireInterface.

*Module creation* Firstly, the module needs to be *configured*, be set
with all required attributes. Thereafter, the module is moved to the
*commit* stage, where validation is performed. If it fails: the module
attributes can be reconfigured. Otherwise, a new instance is *created*
or an old instance is reconfigured. A module instance is identified by
*ModuleIdentifier* which consists of the factory name and instance name.

*ModuleFactory* org.opendaylight.controller.config.spi.ModuleFactory
interface must be implemented by each module factory. The module factory
can create new module instance in two ways: from an existing module
instance or a pure new instance. Also, it can return default modules,
useful for populating registry with an already existing configuration. A
module factory implementation must have a globally unique name.

[[apis]]
=== APIs

*ConfigRegistry* +
Represents functionality provided by configuration transaction (create,
destroy module, validate, abort transaction).

*ConfigTransactionController* +
Represents functionality for manipulating configuration transactions
(begin, commit config ).

*RuntimeBeanRegistratorAwareConfiBean* +
The module implementing this interface will recieve
RuntimeBeanRegistrator before getInstance is invoked.

[[runtime-apis]]
=== Runtime APIs

*RuntimeBean* +
The common interface for all runtime beans.

*RootRuntimeBeanRegistrator* +
Represents functionality for the root runtime bean registration, which
subsequently allows hierarchical registrations.

*HierarchicalRuntimeBeanRegistration* +
Represents functionality for the runtime bean registration and
unreregistration from hierarchy.

[[jmx-apis]]
=== JMX APIs

JMX API is purposed as a transition between Client API and JMX platform.

*ConfigTransactionControllerMXBean* +
Extends ConfigTransactionController, executed by Jolokia clients on
configuration transaction.

*ConfigRegistryMXBean* +
Represents the entry point of configuration management for MXBeans.

[[object-names]]
=== Object names

The Object Name is the pattern used in JMX to locate JMX beans. It
consists of domain and key properties (at least one key-value pair).
Domain is defined as "org.opendaylight.controller". The only mandatory
property is "type".

[[use-case-scenarios]]
== Use case scenarios

The list provides a few samples of successful and unsuccessful
transactions scenarios.

[[successful-commit-scenario]]
=== Successful commit scenario

1.  The user creates a transaction calling creteTransaction() method on
ConfigRegistry.
2.  The ConfigRegisty creates a transaction controller, and registers
the transaction as a new bean.
3.  Runtime configurations are copied to the transaction. The user can
create modules, and set their attributes.
4.  The configuration transaction is to be committed.
5.  The validation process is performed.
6.  After successful validation, the second phase commit begins.
7.  Modules proposed to be destroyed are destroyed, their service
instances are closed.
8.  The Runtime beans are set to registrator.
9.  The transaction controller invokes the method getInstance on each
module.
10. The transaction is committed and resources are closed or released.

[[validation-failure-scenario]]
=== Validation failure scenario

The transaction is the same as previous case until validation process.

1.  If validation fails (that is to say. illegal input attributes values
or dependency resolver failure), ValidationException is thrown and
exposed to the user.
2.  The user can decide to reconfigure the transaction, commit again, or
abort current transaction.
3.  On aborted transactions, TransactionController and JMXRegistrator
are properly closed.
4.  The Unregistration event is sent to ConfigRegistry.

[[default-module-instances]]
== Default Module Instances

The Configuration subsystem provides a way for modules to create default
instances. Default instance is an instance of a module that is created
at the module bundle startup (module becomes visible for configuration
subsystem for example, its bundle is activated in OSGi environment). By
default, no default instances are produced.

The default instance does not differ from instances created later in the
module lifecycle. The only difference is that the configuration for the
default instance cannot be provided by the configuration subsystem. The
module has to acquire the configuration for these instances on its own,
and it can be acquired from, for example, environment variables. After
the creation of a default instance, it acts as a regular instance, and
fully participates in the configuration subsystem (It can be
reconfigured or deleted in following transactions.).
