Logging in ODL container is done via http://logback.qos.ch/[Logback].
Comprehensive documentation is available at
http://logback.qos.ch/documentation.html

By default logging messages are appended to stdout of the java process
and to file logs/opendaylight.log . When debugging a problem it might be
useful to increase logging level:

----------------------------------------------------------
<logger name="org.opendaylight.controller" level="DEBUG"/>
----------------------------------------------------------

Logger tags can be appended under root node . Name of logger is used to
select all loggers to which specified rules should apply. Loggers are
usually named after class in which they reside. The example above
matches all loggers in controller - they all are starting with
org.opendaylight.controller . There are 5 logging levels:
TRACE,DEBUG,INFO, WARN, ERROR. Additionally one can specify which
appenders should be used for given loggers. This might be helpful to
redirect certain log messages to another file or send them to syslog or
over SMTP. See logback documentation for details.
