[[configuration-subsystem]]
= Configuration subsystem

[[terminology]]
= Terminology

*Module* is a compact part of a system, whose configuration is managed
by the configuration subsystem. +
*Module factory* is important for creating module instances. Module
factories are uniquely identified by name. +
*Service* represents public API, which is used to access module
instances (similar to interface in Java). Any module can implement or
provide multiple services. +
*Configuration* application state represented by modules definition,
properties and relations among them.

[[motivation]]
= Motivation

Common way for application configuration is usage of configuration files
(i.e. xml or properties files). However they are easy to use for small
scale applications, they offer only limited possibilities in case of
fast growing and multi-module applications. Static config files become
vast, non-transparent and inconsistent. For highly dynamic and long
living environments is proper configuration essential requirement. The
OSGi framework, provides configuration service
(http://www.osgi.org/javadoc/r4v42/org/osgi/service/cm/package-summary.html[Config
Admin]), allows runtime module configuration, but still lack of
validation process - new module configuration can negatively affect
other modules, also does not solve problems of change's atomicity.

[[configuration-process]]
= Configuration process

OpenDaylight Controller:Config:Configuration[Configuration]

[[initial-configuration]]
= Initial configuration

OpenDaylight Controller:Config:Configuration:Initial[Initial
configuration for controller modules]

[[yang-to-java-code-generator]]
= YANG to Java code generator

OpenDaylight Controller:Config:Java Code Generator[Java code generator]

[[component-maps]]
= Component maps

List of components present in config and netconf subsystem with
additional useful information (description, names of experts for each
component, documentation etc.)

* OpenDaylight Controller:Config:Component_Map[ Config subsystem
component map]
* OpenDaylight Controller:Netconf:Component_Map[ Netconf subsystem
component map]

[[examples]]
= Examples

* OpenDaylight Controller:Config:Examples:Threadpool[ Thread pools
configuration using yuma yangcli-pro and telnet as netconf clients]
* OpenDaylight Controller:Config:Examples:Logback[Logback configuration
using jolokia, telnet and yuma yangcli-pro as netconf clients]
* OpenDaylight_Controller:Config:Examples:Netconf[ Netconf client (NCC)
configuration]
* OpenDaylight Controller:Config:Examples:Sample Project[Example "config
subsystem aware" maven project built from ground]

[[faq]]
= FAQ

OpenDaylight Controller:Config:FAQ[Frequently asked questions]

[[user-guide]]
= User guide

OpenDaylight Controller:Config:Examples:User guide[User guide]

[[configuration-outside-of-config-subsystem-domain]]
= Configuration outside of config-subsystem domain

* OpenDaylight Controller:Config:Logback.xml[Logback.xml]
* OpenDaylight Controller:Config:config.ini[Config.ini]

[[netconf-client]]
= Netconf Client

https://wiki.opendaylight.org/view/OpenDaylight_Controller:Config:Examples:Netconf

[[all-subpages]]
= All subpages
