Welcome to the Device Identification and Driver Management (DIDM)
project page!

[[introduction]]
= Introduction

* Project_Proposals:Device Identification And Driver Management[Project
Proposal]
* Trello Board: https://trello.com/b/eUMAIoda/open-daylight-didm

[[lithium-wip]]
= Lithium (WIP)

* DIDM:Lithium[Project Release Plan]

[[test-and-integration-plan]]
= Test and Integration Plan

https://wiki.opendaylight.org/view/DIDM:Lithium_Test_and_Integration_Plan

[[meetings-open-to-all]]
= Meetings (open to all)

* Topic: ODL - Weekly DIDM Project meeting
* Date/Time: Tuesday's at 10am PST
* Host(s): Gunjan Patel (gupatel@ciena.com)

* WebEx:
https://ciena.webex.com/ciena/j.php?MTID=m3ae30a9a80254613375406708a6bfb9f

* Meeting password: didm (please note passwords are case sensitive)

* Call in toll free number: 1-855-215-5891 (US)
* Call in number: 1-443-863-6577 (US)
* Meeting Number: 687 434 100
* Conference Code: 375 653 4621
* Global numbers:
https://www.tcconline.com/offSite/OffSiteController.jpf?cc=2153369354

Please contact hosts in case of any issues.

[[clustering-support]]
== Clustering Support

* The DIDM will work in a cluster configuration. The DIDM is an MD-SAL
application does not require special code to operate in a clustered
configuration.

[[meeting-agendas]]
= Meeting Agendas

* 04/14:
https://www.dropbox.com/s/64j4we20oecqgmu/DIDM%20weekly%20Meeting%20%E2%80%93%200414.docx?dl=0
* 04/21:
https://www.dropbox.com/s/dqpdha1ahmz41be/DIDM%20weekly%20Meeting%20%E2%80%93%200421.docx?dl=0
* 05/05:
https://www.dropbox.com/s/276nshwb4ugi6vv/DIDM%20weekly%20Meeting%20%E2%80%93%200505.docx?dl=0
* 05/19:
https://www.dropbox.com/s/gelgtbk8pks8dpe/DIDM%20weekly%20Meeting%20%E2%80%93%200519.docx?dl=0
* 05/26:
https://www.dropbox.com/s/p7l78ycnzl7v4kh/DIDM%20weekly%20Meeting%20%E2%80%93%200526.docx?dl=0

[[meeting-minutes]]
= Meeting Minutes

* 2/10/2015:
https://meetings.opendaylight.org/opendaylight-didm/2015/didm_weekly_status_2015_02_10/opendaylight-didm-didm_weekly_status_2015_02_10.2015-02-10-17.59.html

[[all-subpages]]
= All subpages
