OpenDaylight Coding Guidelines

_Note: This document is a work in progress._

[[wiki-guidelines]]
= Wiki Guidelines

*Wiki and Continuous Evolution* – Documentation should be published to
http://wiki.OpenDaylight.org/ so any contributor can improve it

*Versioning* – We want the documentation to continue to improve even
after the bits are released but we need to make sure readers understand
what is available in various releases:

* If a feature will only be available in the next release indicate as
“Coming in Helium”
* If a feature is deprecated in a future release, indicate as
“Deprecated in Helium”

*Language* - The OpenDaylight project uses English as its primary
language but contributors are encouraged to translate into other
languages. If content is available in other languages, consider
providing hyperlinks at the top of the section (ex: “English | Hebrew |
Spanish”)

*Platforms* – Where possible, there should be a single set of
documentation for all platforms. If there is variance, this should be
described in parallel. For example:

* On Linux, …
* On MacOS, …
* On Windows, …

*Screenshots* – When possible, screenshots should vary (ex: Chrome on
MacOS, Firefox on Windows, etc.)

[[some-style-guidelines-for-headings]]
== Some style guidelines for headings

A compilation (from diverse sources) of generally accepted guidelines
for headings follows.

_Use_:

* Self explanatory, descriptive, and concise headings

::
  Preferred: Prerequisites for an AAA Service installation
  +
  Not preferred: Prerequisites

* Singular nouns in headings
* Sentence style capitalization: Capitalize the first word and proper
nouns in a heading.
* Gerunds for task topic headings

::
  Example: Installing the AAA Service

* Infinitives in task headings

::
  Example: Install the AAA Service or To install the AAA Service

* Nouns in concept and reference section headings
* Parallel construction
* Two or three headings in page-length content to create white space

_Practices to avoid when writing headings_

* Interrogative headings

::
  Example: What is the AAA Service?

* More than 3 levels of headings
* Skipped levels of headings

::
  Example: A Heading 3 cannot follow a Heading 1.

* "Stacked" headings: Ensure that there is text between one heading and
the next.
* "Widowed" headings: Headings that stand alone at the bottom of a page
while the related text

::
  appears on the next page

* Expanded acronyms: Use an acronym in a heading, and expand it when it
occurs next in the body text
* Articles at the beginning of headings: Avoid wherever possible

*Terms and definitions* +
Include a labeled list of terms and their definitions in content for
each ODL component (chapter) in the user guide. +
The Asciidoctor user manual provides more information:
http://asciidoctor.org/docs/user-manual/#labeled-list/[Labeled List]

[[some-tips-for-asciidoc-conversion]]
== Some tips for asciidoc conversion

*Headings* +
Always leave space after the = of a heading. +
* ==Level 1 Section (incorrect syntax)

* == Level 1 Section (correct syntax)

*Lists* +
If you use [start=number] in lists, remember that the syntax is
case-sensitive.

* Start=2 (The list repeats number 1.)
* start=2 (The item will be numbered 2.)

To make words in list items bold: +
* *Bold face* for the item (Will not be rendered correctly)

* ** *** Bold face** for the item (You will get the expected
formatting.)

[[git-commit-message-style]]
= Git commit message style

For Git commit messages we recommend following the
https://wiki.openstack.org/wiki/GitCommitMessages[OpenStack commit
message recommendations].

[[general-code-headers]]
= General Code headers

License and Copyright headers need to exist at the top of all code
files. Examples of copyright headers for each language can be seen
below.

Note: In case you need multiple Copyright headers simply duplicate the
Copyright line for additional copyrights

[[ccjava]]
== C/C++/Java

---------------------------------------------------------------------------------
/*******************************************************************************
 * Copyright (c) 2015 <Company or Individual>.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
---------------------------------------------------------------------------------

[[bashpython]]
== Bash/Python

-------------------------------------------------------------------------------
##############################################################################
# Copyright (c) 2015 <Company or Individual>.  All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
##############################################################################
-------------------------------------------------------------------------------

[[xml]]
== XML

-------------------------------------------------------------------------------
<!--
  Copyright (c) 2015 <Company or Individual>.  All rights reserved.

  This program and the accompanying materials are made available under the
  terms of the Eclipse Public License v1.0 which accompanies this distribution,
  and is available at http://www.eclipse.org/legal/epl-v10.html
-->
-------------------------------------------------------------------------------

[[general-code-style]]
= General Code Style

* 120 character line length

[[java]]
= Java

In General we follow the Google Java Code Style Guide with a few
exceptions. See:
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

* 4 space indentation
* 120 character line length
* 72 or 80 chars for javadoc
* import ordering
(https://wiki.opendaylight.org/view/GettingStarted:_Eclipse_Setup#Import_ordering)
* YangTools Design Guidelines
(https://wiki.opendaylight.org/view/YANG_Tools:Design_and_Coding_Guidelines)
* follow JLS modifier ordering
(http://checkstyle.sourceforge.net/config_modifier.html)
* do not use underscores (_) in identifiers, as they trigger warnings
with JDK8

[[checkstyle]]
== Checkstyle

Enabling checkstyle for your build is easy if you are using odlparent.
Simply add the following sections to your project's top-level parent
pom.xml file. The odlparent checkstyle currently only throws warnings
and will not prevent your project from building if code violations are
found.

--------------------------------------------------------
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
--------------------------------------------------------

*Additional Resources:*

* Maven:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml
** Dependent on https://jira.codehaus.org/browse/MCHECKSTYLE-261
* Eclipse:
https://code.google.com/p/google-styleguide/source/browse/trunk/eclipse-java-google-style.xml
* IntelliJ:
https://code.google.com/p/google-styleguide/source/browse/trunk/intellij-java-google-style.xml

[[python]]
= Python

PEP8 is the Python standard that should be followed when coding any
Python code with the following exceptions.

* 120 character line length

To automate pep8 scanning we recommend using a tox configuration as
follows:

tox.ini

--------------------------------------------------------
[tox]
envlist = pep8
#skipsdist = true  # Command only available in tox 1.6.0

[testenv:pep8]
deps = flake8
commands = flake8

[flake8]
max-line-length = 120
--------------------------------------------------------

Unfortunately the version of tox installed in the Jenkins build infra
does not support the skipdist parameter which is necessary if your
project does not have a setup.py file. A workaround is to create a
minimal setup.py file as follows:

setup.py

---------------------------------------------------------------------
# Workaround for tox missing parameter 'skipsdist=true' which was not
# introduced until tox 1.6.0

import setuptools

setuptools.setup(name='project-name')
---------------------------------------------------------------------

[[xml-1]]
= XML

* use self-closing
* include proper namespace/model/version declarations
* TBD

[[yang]]
= Yang

* Do not use underscores ('_') in identifiers. JDK 9 is on track to
making underscores forbidden in identifiers, which means we will need to
map them and it is not going to be pleasant :-(
* Each declaration needs to have either a description or a reference to
a defintion document (like an IETF draft)
* Use typedefs to declare concepts. An UUID is typeless, so each
instance should have its scope, so we know its applicability domain.
'type string' should only be used to things like free-form comments and
similar. Please attach a 'units' statement whenever possible.
* TBD

