[[introduction]]
= Introduction

Entry point for the extensibility is SwitchConnectionProvider.
SwitchConnectionProvider contains methods for (de)serializer
registration. To register deserializer it is needed to use
.register*Deserializer(key, impl). To register serializer one must use
.register*Serializer(key, impl). Registration can occur either during
configuration or at runtime.

*NOTE:* In case when experimenter message is received and no
(de)serializer was registered, the library will throw
IllegalArgumentException.

[[basic-principle-example]]
= Basic principle & example

*
Openflow Protocol Library:Openflow Protocol Library's extensibility:Basic Principle & Example[
Basic Principle & Example]

[[detailed-walkthrough]]
= Detailed walkthrough

*
Openflow Protocol Library:Openflow Protocol Library's extensibility:Detailed walkthrough[
Detailed walkthrough]

[[registration-keys]]
= Registration keys

*
Openflow Protocol Library:Openflow Protocol Library's extensibility:Registration keys[
Registration keys]

