[[hydrogen-release-notes]]
== Hydrogen Release Notes

[[major-features]]
=== Major Features

* OpenFlow v1.3 support
* OpenFlow v1.0 support
* Non-blocking extensible implementation

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

* It is enough to have JRE installed on your computer in order to run
OpenFlow Protocol Library project. No OS related issues are known.

[[for-development]]
==== For Development

* It is enough to have JDK installed on your computer in order to work
with OpenFlow Protocol Library project. No OS related issues are known.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

* deserialization issue during MultipartReply (OF v1.3) deserialization
can occur. The issue occurs with different probability on different
machines. There is a suspicion that virtual switch is sending incorrect
data (based on the wireshark capture) or it might have something to do
with network errors. This issue is under further investigation
* TLS uses bogus key for communication. Real TLS encrypted communication
hasn't been carried out yet. Infrastructure for TLS keys is ready,
waiting for the global keystore implementation in Config Substystem.

[[release-review]]
=== Release review

*
Openflow_Protocol_Library:Release_Notes:Hydrogen Release Review[Openflow_Protocol_Library:Release_Notes:Hydrogen
Release Review]

