[[introduction]]
== Introduction

Statistics collection collects message statistics. +
Current collected statistics (DS - downstream, US - upstream):

* DS_ENTERED_OFJAVA - all messages that entered openflowjava (picked up
from openflowplugin)
* DS_ENCODE_SUCCESS - successfully encoded messages
* DS_ENCODE_FAIL - messages that failed during encoding (serialization)
process
* DS_FLOW_MODS_ENTERED - all flow-mod messages that entered openflowjava
* DS_FLOW_MODS_SENT - all flow-mod messages that were successfully sent
* US_RECEIVED_IN_OFJAVA - messages received from switch
* US_DECODE_SUCCESS - successfully decoded messages
* US_DECODE_FAIL - messages that failed during decoding
(deserialization) process
* US_MESSAGE_PASS - messages handed over to openflowplugin

[[karaf]]
== Karaf

In orded to start statistics, it is needed to feature:install
odl-openflowjava-stats. +
To see the logs one should use log:set DEBUG
org.opendaylight.openflowjava.statistics and than probably log:display
(you can log:list to see if the logging has been set). +
To adjust collection settings it is enough to modify
45-openflowjava-stats.xml. +

[[jconsole]]
== JConsole

JConsole provides two commands for the statistics collection:

* printing current statistics
* resetting statistic counters

After attaching JConsole to correct process, one only needs to go into
MBeans tab -> org.opendaylight.controller -> RuntimeBean ->
statistics-collection-service-impl -> statistics-collection-service-impl
-> Operations to be able to use this commands.
