[[testing-approach]]
= Testing approach

[[use-cases]]
== Use Cases

With regards to complexity of individual use cases these will be part of
testing designs and not of this document. For now we are considering
following basic use cases that involve:

* Setting up connection to switch
* Receiving messages from switch
* Processing messages in library
* Passing them to plugin/SAL
* Passing possible response from plugin/SAL back to switch

[[unit-tests]]
== Unit tests

Unit tests will be designed as short and fast units. Special attention
will be addressed to test failures caused by occupied ports by other
automated test processes. Unit tests will cover below areas:

* Detection of TLS connection
* Obtaining information about OpenFlow protocol version from the message
header
* Converting messages into/from binary stream with taking into account
right format of converted messages

Types of messages that will be incorporated in unit tests:

* Hello
* Features request
* Features reply
* Echo request
* Echo reply
* Flow modification and flow related messages
* Various combinations of matches

Tests will be written and administrated using JUnit framework.

[[integration-tests]]
== Integration tests

Integration tests will be focused on testing the communication between
the switch and the library as it will run in real world. This will be
emulated by virtual switch. Other part of integration tests will cover
the passing of information to plugin/SAL. Start of integration test is
planned on September 16th and will last until November 22nd.

[[system-test]]
== System test

This part will be specified later. Start of system test is planned on
October 14th and will last until November 22nd.

[[automated-tests]]
== Automated tests

All unit tests are envisioned to run fully automated (as part of
continuous integration in Jenkins). We also intend to automate part of
the integration tests that involve communication between switch and
plugin/SAL.

[[error-tracking]]
== Error tracking

All issues that will appear through testing will be logged in BugZilla
for easy tracking and managing.
