[[installation]]
= Installation

Pull the code:

----------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/openflowjava.git
----------------------------------------------------------------------

and import project into your IDE

[[startup]]
= Startup

Library is started by Openflow Plugin. Library can be started also by
itself (via Integration test).

[[startup-in-openflow-plugin-or-other-component]]
=== Startup in Openflow Plugin (or other component)

Any component that wants to use the library's funcionality needs to
import the library's bundle. To start the library it is needed to:

* 1. configure,
* 2. inject SwitchConnectionHandler,
* 3. start the library

NOTE: detailed description and diagram can be found here:
Openflow_Protocol_Library:Openflow_Protocol_Library%27s_lifecycle[Library's
lifecycle]

[[startup-in-the-library]]
=== Startup in the library

* 1. Navigate to IntegrationTest.java
* 2. Uncomment @Test anotation above testCommunicationWithVM() method
* 3. Set the desired configuration in the setUp() method (see
configuration part below)
* 4. Run the testCommunicationWithVM()
** Modify MockPlugin.java to test some scenarios with vswitch

[[configuration]]
= Configuration

Current implementation allows to configure:

* listening port (mandatory)
* transfer protocol (mandatory)
* switch idle timeout (mandatory)
* TLS configuration (optional)
* thread count (optional)

You can find exemplary Openflow Protocol Library instance configuration
below:

------------------------------------------------------------------------------------------------------------------------------------------------------------------
    <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <modules xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
        <!-- default OF-switch-connection-provider (port 6633) -->
        <module>
          <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:openflow:switch:connection:provider:impl">prefix:openflow-switch-connection-provider-impl</type>
          <name>openflow-switch-connection-provider-default-impl</name>
          <port>6633</port>
          <transport-protocol>TCP</transport-protocol>
          <switch-idle-timeout>15000</switch-idle-timeout>
          <tls>
            <keystore>/exemplary-ctlKeystore</keystore>
            <keystore-type>JKS</keystore-type>
            <keystore-path-type>CLASSPATH</keystore-path-type>
            <keystore-password>opendaylight</keystore-password>
            <truststore>/exemplary-ctlTrustStore</truststore>
            <truststore-type>JKS</truststore-type>
            <truststore-path-type>CLASSPATH</truststore-path-type>
            <truststore-password>opendaylight</truststore-password>
            <certificate-password>opendaylight</certificate-password>
          </tls>
          <threads>
            <boss-threads>2</boss-threads>
            <worker-threads>8</worker-threads>
          </threads>
        </module>
------------------------------------------------------------------------------------------------------------------------------------------------------------------

Possible transport-protocol options:

* TCP
* TLS
* UDP +

Switch-idle timeout specifies time needed to detect idle state of
switch. When no message is received from switch within this time, upper
layers are notified on switch idleness. +
To be able to use this exemplary TLS configuration:

* uncomment the tag
* copy exemplary-switch-privkey.pem, exemplary-switch-cert.pem and
exemplary-cacert.pem files into your virtual machine
* set VM encryption options to use copied keys (please visit
OpenDaylight OpenFlow Plugin: TLS Support[ TLS support] wiki page for
detailed information regarding TLS)
* start communication +

Thread model configuration specifies how many threads are desired to
perform Netty's I/O operations.

* boss-threads specifies the number of threads that register incoming
connections
* worker-threads specifies the number of threads performing read / write
(+ serialization / deserialization) operations.

[[developer-guide]]
= Developer Guide

For developer guide check
Openflow Protocol Library:Documentation[Documentation] page

[[openflow-protocol-librarymain-page]]
= Openflow Protocol Library:Main page

* Openflow Protocol Library:Main[Openflow Protocol Library:Main]

