[[purpose]]
== Purpose

The purpose of this page is to gather questions for the MD-SAL team that
can be used to help guide the MD-SAL deep dive meetings. Some of these
questions / answers should eventually make their way into the
OpenDaylight_Controller:MD-SAL:Developer_FAQ[MD-SAL developer FAQ]. So
if you have a question please tack it onto the end with a '#'.

'''''

1.  What is the sequence from a RESTCONF request down to an RPC
implementation invocation, including the serialization / deserialization
of data assuming an binding dependent RPC implementation?
2.  What is the best practices you have found for debugging / tracing
the serialization (javaassit) code? Or can we get rid of it?
3.  What is the best practices you have found for debugging / tracing
the xtend code? Or can we get rid of it?
4.  Is there a standard way to provide notifications back to a RESTCONF
(or other) client when a config data change or a callback associated
with a config change fails? The example here is when something like a
Flow is pushed but fails when being configured on a device for any
reasons (such as connectivity) how do we alert a client or a GUI? In ODL
the actions that are invoked because of a config change cannot be known
apriori, but being able to at least associate a failure with a request
and show that "something" failed is important.

'''''

[[futures]]
== Futures

1.  How with distributed/partitioned data be handled?
2.  How will distributed/partitioned processing be handled?
3.  Should clients be able to put constraints around RPC invocations to
indicate if a given request should ever go remote or should it only be
invoked if locale?
4.  If we want to more ODL more towards an Erlang style processing
model, how does that change the MD-SAL interfaces and the component
implementations? Or is the plan to have an adaption layer between them?

