Model-Driven SAL (MD-SAL) is a set of infrastructure services aimed at
providing common and generic support to application and plugin
developers.

MD-SAL currently provides infrastructure services for the following:

* Data Services
* RPC or Service routing
* Notification subscription and publish services

This model-driven infrastructure allows developers to develop
applications and plugins against an API type of their choice (Java
generated APIs, DOM APIs, REST APIs). The infrastructure automatically
provides the other API types.

The modelling language of choice for MD-SAL is YANG, which is an IETF
standard, for modelling network element configuration. The YANGTools
project and its development tools provide support for YANG.

[[api-types]]
== API Types

MD-SAL provides three API types:

* Java generated APIs for consumers and producers
* DOM APIs: Mostly used by infrastucture components and usuful for
XML-driven plugin and application types
* REST APIs: OpenDaylight Controller:MD-SAL:Restconf[Restconf] that is
available to consumer type applications and provides access to RPC and
data stores

[[basic-yang-concepts-and-their-rendition-in-apis]]
== Basic YANG Concepts and their rendition in APIs

The following are the basic concepts in YANG modeling:

* Remote Procedure (RPCs): In MD-SAL, RPCs are used for any call or
invocation that crosses the plugin or module boundaries. RPCs are
triggered by consumers, and usually have return values.
* Notifications: Asynchronous events, published by components for
listeners.
* Configuration and Operational Data tree: The well-defined (by model)
tree structure that represents the operational state of components and
systems.
** Instance Identifier: The path that uniquely identifies the sub-tree
in the configuration or operational space. Most of the addressing of
data is done by Instance Identifier.

[[rpc]]
=== RPC

In YANG, Remote Procedure Calls (RPCs) are used to model any procedure
call implemented by a Provider (Server), which exposes functionality to
Consumers (Clients).

In MD-SAL terminology, the term 'RPC' is used to define the input and
output for a procedure (function) that is to be provided by a Provider,
and adapted by the MD-SAL.

In the context of the MD-SAL, there are three types of RPCs (RPC
services):

* OpenDaylight Controller:MD-SAL:Service Types#Global_Service[Global]:
One service instance (implementation) per controller container or mount
point
* OpenDaylight Controller:MD-SAL:Service Types#Routed_Service[Routed]:
Multiple service instances (implementations) per controller container or
mount point

RPCs in various API types:

* Java Generated APIs: For each model there is *Service interface. See
YANG_Tools:YANG_to_Java_Mapping#Rpc to understand how YANG statements
maps to Service interface.
** Providers expose their implementation of *Service by registering
their implementation to RpcProviderRegistry.
** Consumers get the *Service implementation from RpcConsumerRegistry.
If the implementator uses a different API type, MD-SAL automatically
translates data in the background.
* DOM APIs: RPCs are identified by QName.
** Providers expose their implementation of RPC idetified by QName
registering their RpcImplementation to RpcProvisionRegistry.
** Consumers get the *Service implementation from RpcConsumerRegistry.
If the implementator uses different API type, MD-SAL automatically
translates data in the background.
* REST APIs: RPCs are identified by the model name and their name.
* Consumers invoke RPCs by invoking POST operation to
/restconf/operations/model-name:rpc-name.

[[notification]]
=== Notification

In YANG, Notifications represent asynchronous events, published by
providers for listeners.

RPCs in various API types:

* Java Generated APIs: For each model, there is *Listener interface and
transfer object for each notification. See
YANG_Tools:YANG_to_Java_Mapping#Notification to understand how YANG
statements map to the Notifications interface.
** Providers publish notifications by invoking the publish method on
NotificationPublishService.
** To receive notifications, consumers register their implementation of
*Listener to NotificationBrokerService. If the notification publisher
uses a different API type, MD-SAL automatically translates data in the
background.
* DOM APIs: Notifications are represented only by XML Payload.
** Providers publish notifications by invoking the publish method on
NotificationPublishService.
** To receive notifications, consumers register their implementation of
*Listener to NotificationBrokerService. If the notification publisher
uses a different API type, MD-SAL automatically translates data in the
background.
* REST APIs: Notifications are currently not supported.

[[instance-identifier]]
=== Instance Identifier

The Instance Identifier is the unique identifier of an element
(location) in the yang data tree; basically, it is the *path* to the
node that uniquely identifies all the parent nodes of the node. The
unique identification of list elements requires the specification of key
values as well.

MD-SAL currently provides three different APIs to access data in the
common data store:

* Binding APIs (Java generated DTOs)
* DOM APIs
* OpenDaylight_Controller:MD-SAL:Restconf[HTTP Restconf APIs]

[[example]]
==== Example

Consider the following simple YANG model for inventory:

-----------------------------------------------------
module inventory {
    namespace &quot;urn:opendaylight:inventory&quot;;
    prefix inv;
    revision &quot;2013-06-07&quot;;
    container nodes {
        list node {
            key &quot;id&quot;;
            leaf &quot;id&quot; {
                type &quot;string&quot;;
            }
        }
    }
}
-----------------------------------------------------

And having one instance of node with the name _foo_;

Let us assume that we want to create an instance identifier for the node
foo, in the following bindings or formats:

* YANG / XML / XPath version
+
---------------------------------------
/inv:nodes/inv:node[id=&quot;foo&quot;]
---------------------------------------
* Binding-Aware version (generated APIs)
+
------------------------------------------------------------------------------------------------------------------------------------------------
import org.opendaylight.yang.gen.urn.opendaylight.inventory.rev130607.Nodes;
import org.opendaylight.yang.gen.urn.opendaylight.inventory.rev130607.nodes.Node;
import org.opendaylight.yang.gen.urn.opendaylight.inventory.rev130607.nodes.NodeKey;

import org.opendaylight.yangtools.yang.binding.InstanceIdentifier;

InstanceIdentifier&lt;Node&gt; identifier = InstanceIdentifier.builder(Nodes.class).child(Node.class,new NodeKey(&quot;foo&quot;)).toInstance();
------------------------------------------------------------------------------------------------------------------------------------------------
+
*Note:* The last call, _toInstance()_ does not return an instance of the
node, but the Java version of Instance identifier which uniquely
identifies the node "foo".
* *HTTP Restconf APIs*

--------------------------------------------------------------
http://localhost:8080/restconf/config/inventory:nodes/node/foo
--------------------------------------------------------------

*Note:* We assume that HTTP APIs are exposed on localhost, port 8080.

Binding Independent version (yang-data-api)

------------------------------------------------------------------------------------------------------------
import org.opendaylight.yang.common.QName;
import org.opendaylight.yang.data.api.InstanceIdentifier;

QName nodes = QName.create(&quot;urn:opendaylight:inventory&quot;,&quot;2013-06-07&quot;,&quot;nodes&quot;);
QName node = QName.create(nodes,&quot;nodes&quot;);
QName idName = QName.create(nodes,&quot;id&quot;);
InstanceIdentifier = InstanceIdentifier.builder()
    .node(nodes)
    .nodeWithKey(node,idName,&quot;foo&quot;)
    .toInstance();
------------------------------------------------------------------------------------------------------------

*Note:* The last call, _toInstance()_ does not return an instance of
node, but the Java version of Instance identifier which uniquely
identifies the node "foo".

[[plugin-types]]
=== Plugin Types

* OpenDaylight Controller:MD-SAL:Plugin Types[Plugin Types]
*
OpenDaylight Controller:MD-SAL:Southbound Plugin Development Guide[Southbound
Plugin Development Guide]
* OpenDaylight_Controller:MD-SAL:FAQ[ Model-Driven SAL FAQ]
* OpenDaylight_Controller:Config:Main[ Controller Configuration
Subsystem]
* OpenDaylight_Controller:Config:Model Reference[ OpenDaylight Model
Reference]

