[[overview]]
= Overview

[[the-model-reference]]
= The Model Reference

[cols=",,,",options="header",]
|=======================================================================
|Model |Description |Project |API Definition
|*OpenDaylight Yang Extensions*

a| |Yang Extensions for OpenDaylight |YANG Tools:Main[YANG Tools] a| a|

|*Base Types*

a| |IANA definition of private enterprise number |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Definitions for the 'AFN' and 'SAFI' IANA-registered enumerations
(http://datatracker.ietf.org/doc/draft-ietf-netmod-iana-afn-safi/[draft])
|YANG Tools:Main[YANG Tools] a| a|

a| |Definitions for IANA-registered interface types
(http://datatracker.ietf.org/doc/draft-ietf-netmod-iana-if-type/[draft-ietf-netmod-iana-if-type])
|YANG Tools:Main[YANG Tools] a| a|

a| |Definitions of IEEE754 floating point types |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base network types |BGP_LS_PCEP:Main[ BGP-LS/PCEP] |[ a|

|*Configuration Subsystem*

|Base Types

a| |Base YANG definitions for configuration subsystem
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/config-api/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for rpc context reference used for rpc routing
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/config-api/target/apidocs/index.html[JavaDoc]
a|

|Base Modules

a| |Base YANG definitions for netty threadgroup implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/netty-threadgroup-config/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for thread services pure Java implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/threadpool-config-impl/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for thread services pure Java implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/threadpool-config-impl/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for thread services pure Java implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/threadpool-config-impl/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for thread services pure Java implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/threadpool-config-impl/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for netty services
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/netty-config-api/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for thread-related services
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/threadpool-config-api/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for logging service
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/logback-config/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for shutdown service
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/shutdown-api/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for shutdown implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/shutdown-impl/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for netty timer implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/netty-timer-config/target/apidocs/index.html[JavaDoc]
a|

a| |Base YANG definitions for netty event executor implementation
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/config/netty-event-executor-config/target/apidocs/index.html[JavaDoc]
a|

|BGPCEP Modules

a| |Base YANG definitions for Programming SPI |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for Programming implementation
|BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP topology provider |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP listener service |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP listener service |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP listener service |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP Linkstate extension |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for PCEP topology provider service
|BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

a| |Base YANG definitions for PCEP SPI module |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for the Topology API |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for PCEP protocol handler |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for PCEP implementation |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP message parser pure Java
implementation |BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

a| |Base YANG definitions for reconnect strategy |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP listener implementation
|BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

a| |Base YANG definitions for BGP listener service |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|MD-SAL Modules

a| |Common definition for MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-dom-api/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-dom-api/target/apidocs/index.html[JavaDoc]
a|

a| |Definition of types related to Internet Assigned Numbers Authority
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-remote/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-binding-config/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for MD-SAL Clustered Store
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/clustered-data-store/implementation/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-remoterpc-connector/implementation/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-netconf-connector/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-binding-broker/target/apidocs/index.html[JavaDoc]
a|

a| |Service definition for Binding Aware MD-SAL
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/sal-dom-broker/target/apidocs/index.html[JavaDoc]
a|

a| |YANG version of the TOASTER-MIB
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/md-sal/samples/toaster/target/apidocs/index.html[JavaDoc]
|---

|Netconf Endpoint

a| |NETCONF Monitoring Module
(http://datatracker.ietf.org/doc/rfc6022/[RFC6022])
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/netconf/ietf-netconf-monitoring/target/apidocs/index.html[Javadoc]
a|

a| |NETCONF Monitoring Module extension for tcp transport type
|OpenDaylight_Controller:Main[Controller]
|https://jenkins.opendaylight.org/controller/job/controller-daily/ws/opendaylight/netconf/ietf-netconf-monitoring-extension/target/apidocs/index.html[Javadoc]
a|

|*Services*

|Inventory

a| |The base (abstract) inventory model
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |The netconf-specific augmentation of the base inventory model
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |opendaylight-inventory-config
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|Topology

a| |The base (abstract) network topology model
(http://datatracker.ietf.org/doc/draft-clemm-netmod-yang-network-topo/[draft-clemm-...])
|YANG Tools:Main[YANG Tools] a| a|

a| |The base L3 IGP network topology model
(http://datatracker.ietf.org/doc/draft-clemm-netmod-yang-network-topo/[draft-clemm-...])
|YANG Tools:Main[YANG Tools] a| a|

a| |Network topology data types specific to IS-IS
(http://datatracker.ietf.org/doc/draft-clemm-netmod-yang-network-topo/[draft-clemm-...])
|YANG Tools:Main[YANG Tools] a| a|

a| |Network topology data types specific to OSPF
(http://datatracker.ietf.org/doc/draft-clemm-netmod-yang-network-topo/[draft-clemm-...])
|YANG Tools:Main[YANG Tools] a| a|

a| |Data types for the Traffic Engineering Database
(http://datatracker.ietf.org/doc/draft-clemm-netmod-yang-network-topo/[draft-clemm-...])
|YANG Tools:Main[YANG Tools] a| a|

a| |Segment Routing extensions to base tunnel topology model.
|BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

|Model Topology

a| |opendaylight-topology
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |opendaylight-topology-inventory
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |opendaylight-topology-view
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|*OpenFlow Services*

|Flow Base Types

a| |Data types for OpenFlow action structures
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, Section A.3.4.2])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for programming flows (match, action, instruction, group,
meter)
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for OpenFlow groups
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, , Section 5.6])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |opendaylight-match-types
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for OpenFlow meter structures
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, , Section 5.7])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for OpenFlow port structures
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, , Section A.2.1])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for OpenFlow action structures
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, , Section A.3.6])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Data types for table programming
(https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf[OF
1.3.1, , Section 5])
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|Flow Management

a| |flow-management
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |A service API for manipulating groups (deprecated)
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |A service API for manipulating meters (deprecated)
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |A service API for manipulating ports (deprecated)
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |queue-management
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |table-management
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|Flow Service

a| |flow-capable-transaction
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |flow-errors
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |flow-node-inventory
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |flow-topology-discovery
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |packet-processing
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|Flow Statistics

a| |individual and aggregate flow statistics APIs and notification
interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Flow table statistics collection APIs and notification interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Group stats collection APIs and notification interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Meter collection APIs and notification interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Node connector stats collection APIs and notification interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Queue statistics collection APIs and notification interfaces
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

a| |Generic stats type definitions (Node Connector, Flow, Group, Meter,
Queue etc.)
|https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[MD-SAL]
|--- a|

|*Affinity Services*

a| |affinity
|https://wiki.opendaylight.org/view/Project_Proposals:Affinity_Metadata_Service[Affinity]
|--- |---

|*BGPCEP*

|BGP Models

a| |Contains the base concepts contained in
http://datatracker.ietf.org/doc/rfc4271/[RFC4271] and
http://datatracker.ietf.org/doc/rfc4760/[RFC4760]. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Contains the base data model of a BGP message.
(http://datatracker.ietf.org/doc/rfc4271/[RFC4271])
(http://datatracker.ietf.org/doc/rfc4893/[RFC4893]) |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base data model of a BGP message.
(https://datatracker.ietf.org/doc/draft-ietf-idr-ls-distribution/[draft])
(http://datatracker.ietf.org/doc/rfc4271/[RFC4271]) |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base data model of a BGP message.
(https://datatracker.ietf.org/doc/draft-ietf-idr-ls-distribution/[draft])
(http://datatracker.ietf.org/doc/rfc4271/[RFC4271]) |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Contains the concept of a Routing Information Base, as defined by
(http://datatracker.ietf.org/doc/rfc4271/[RFC4271]). |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|PCEP Models

a| |Data model for PCEP extensions defined in
http://tools.ietf.org/html/draft-crabbe-pce-pce-initiated-lsp-00[draft-crabbe-...].
|BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

a| |Base data model the the PCEP message.
(http://datatracker.ietf.org/doc/rfc5440/[RFC5440])
(https://datatracker.ietf.org/doc/rfc5520/[RFC5520])
(http://datatracker.ietf.org/doc/rfc6006/[1]) |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Base data types for the PCEP message.
(http://datatracker.ietf.org/doc/rfc5440/[RFC5440])
(https://datatracker.ietf.org/doc/rfc5520/[RFC5520])
(http://datatracker.ietf.org/doc/rfc6006/[2]) |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|RSVP Models

a| |Contains the definition of types related to Resource Reservation
Protocol (RSVP). |BGP_LS_PCEP:Main[ BGP-LS/PCEP] a| a|

|PCEP Topology Models

a| |PCEP extensions to base topology model. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |PCEP extensions to base topology model. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|PCEP Tunnel Topology Models

a| |PCEP extensions to base tunnel topology model. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Programming extensions for tunnel topologies. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|Programming Models

a| |The basic tunnel programming model. |BGP_LS_PCEP:Main[ BGP-LS/PCEP]
a| a|

a| |Programming extensions for tunnel topologies. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

a| |Programming extensions for tunnel topologies. |BGP_LS_PCEP:Main[
BGP-LS/PCEP] a| a|

|*Plugins*

|*Openflow Protocol Library* (under Openflow Plugin)

a| |Base Openflow actions. |Openflow_Protocol_Library:Main[
Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-action.html[REST]

a| |Object augmentations. |Openflow_Protocol_Library:Main[ Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-augments.html[REST]

a| |Openflow OXM match. |Openflow_Protocol_Library:Main[ Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-extensible-match.html[REST]

a| |Base Openflow instructions. |Openflow_Protocol_Library:Main[
Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-instruction.html[REST]

a| |Openflow Protocol messages. |Openflow_Protocol_Library:Main[
Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-protocol.html[REST]

a| |Common Openflow specific types. |Openflow_Protocol_Library:Main[
Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/openflow-types.html[REST]

a| |System notification objects. |Openflow_Protocol_Library:Main[
Openflowjava]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-merge/org.opendaylight.openflowjava$openflow-protocol-api/ws/target/apidocs/index.html[Javadoc]
|https://jenkins.opendaylight.org/openflowjava/job/openflowjava-verify/ws/openflow-protocol-api/target/site/restconf/system-notifications.html[REST]
|=======================================================================

