[[how-to-use-restconf]]
= How to use Restconf

[[how-to-start-and-access-restconf]]
== How to start and access Restconf

Restconf protocol is implemented in sal-rest-connector artifact which is
packed to bundle. After successfull starting of Karaf:

* it is necessary to install all required features. At least it is
necessary to install *feature:install odl-restconf-all* which contains
reference to mentioned bundle.
+
If you want to work e. g. with open flow structures in datastore you
have to also install features which contain bundles with yangs for open
flow plugin - feature:install odl-flow-model odl-flow-services.
* Restconf is listening on port *8181* for *HTTP* requests. (Before
Karaf Restconf listened on port *8080*.),
* Restconf is started in debug mode via command *karaf debug* and then
it is possible to connect to *5005* for remote debugging. (Before Karaf
Restconf was started in debug via command *karaf -debug* and it was
necessary to connect to *8000* debug port),

[[available-datastores]]
== Available datastores

Restconf allows access to datastores in the controller. There are two
datastores:

* *config* - contains data inserted via controller
* *operational* - contains other data

[[supported-data-formats]]
== Supported data formats

Request and response data can be in *XML or JSON* format. XML structures
according to yang are defined at:
http://tools.ietf.org/html/rfc6020[XML-YANG].

JSON structures are defined at:
http://tools.ietf.org/html/draft-lhotka-netmod-yang-json-02[JSON-YANG].

The media type of request data (input) has to be set via
“*Content-Type*” field in HTTP header with.

The media type of response data (output) has to be set in the “*Accept*”
field in HTTP header.

Get the media types for each resource by calling the OPTIONS operation.

[[restconf-uri]]
== Restconf URI

[[identifier-in-uri]]
=== Identifier in URI

Most of the Restconf endpoints paths (URI) use
OpenDaylight Controller:MD-SAL:Concepts#Instance_Identifier[Instance
Identifier]. In following text it will be formatted as `<identifier>`.
Following requirements on `<identifier>` has to be met:

* it must start with *`<moduleName>`:`<nodeName>`* where
*`<moduleName>`* is a name of the YANG module and *`<nodeName>`* is the
name of the top level node in the module.
* child nodes has to be specified in format:
** *`<nodeName>`* - can be used everytime expect case when node with the
same name was added via agumentation from external YANG model
(Concretely: Module A has node A1 with child X. Module B augments node
A1 by adding node X.)
** *`<moduleName>`:`<nodeName>`* - is valid everytime
* *`<nodeName>`* has to be separated by */*
* *`<nodeName>`* can represent a data node which is of _list_ or
_container_ YANG built-in type. If the data node is a _list_, there must
be defined keys of the list behind the data node name for example,
*`<nodeName>/<valueOfKey1>/<valueOfKey2>`*.

For more details about encoding see:
http://tools.ietf.org/html/draft-bierman-netconf-restconf-02#section-5.3.1[Restconf
02 - Encoding YANG Instance Identifiers in the Request URI]

[[uri-parameters]]
=== URI parameters

*Uri parameters described below aren't currently working. Functionality
was removed and reworked. For more details see [#Known_Issues Known
issues] chapter.* +
There are following URI parameters supported:

* *_depth_* - cut output data to specified level. Leaf value, leaf list
value and keyed list with all keys values are specified as one level.
Example of using:
+
http://[`http://`]`:``/restconf/config/``:``/``?depth=n`
+
where *n* is positive integer or "unbounded" string value. +
Possible behavior if URI *depth* parameter is:
** missing - data won't be pruned,
** specified but incorrect - then exception will be raised,
** specified and correct - data will be pruned to specified level
+
Depth parameter is implemented according to 3.8.1 chapter of
http://tools.ietf.org/html/draft-bierman-netconf-restconf-02#page-39[Restconf
RFC]
* *_prettyPrint_* - is responsible for indentation of output data
according to data levels. Example of using:
+
http://[`http://`]`:``/restconf/config/``:``/``?prettyPrint=val`
+
where *val* is boolean value - true or false. +
Possible behavior if URI *prettyPrint* parameter is:
** missing - data won't be pretty printed
** specified but incorrect - data won't be pretty printed
** specified but incorrect - data will be pretty printed

[[mount-point]]
== Mount point

A Node can be behind a mount point. In this case, the URI has to be in
format *`<identifier>`/yang-ext:mount/`<identifier>`*. The first
*`<identifier>`* is the path to a mount point and the second
*`<identifier>`* is the path to a node behind the mount point. A URI can
end in a mount point itself by using *`<identifier>`/yang-ext:mount*

More information on how to actually use mountpoints is available at:
OpenDaylight_Controller:Config:Examples:Netconf

[[supported-operations]]
== Supported operations

Restconf supports *OPTIONS, GET, PUT, POST, DELETE* HTTP operations. +
Each URI for rest calls must start with */restconf* prefix.

HTTP operation

URI link

Description

Example

OPTIONS

/restconf

Returns the XML description of the resources with the required request
and response media types in Web Application Description Language (WADL)

 

GET

/restconf/config/`<identifier>`

Returns a data node from the *Config* datastore. `<identifier>` points
to concrete data node and its data will be returned

 

GET

/restconf/operational/`<identifier>`

Returns the value of the data node from the *Operational* datastore.
`<identifier>` points to concrete data node and its data will be
returned

 

PUT

/restconf/config/`<identifier>`

Updates or creates data in the *Config* datastore and returns the state
about success. `<identifier>` points to a data node which will be
updated or created

Example1

`PUT `http://[`http://`]`:8181/restconf/config/module1:foo/bar` +
`Content-Type: applicaton/xml` +
 +
`  …` +

Example with mount point:

`PUT `http://[`http://`]`:8181/restconf/config/module1:foo1/foo2/` +
`  yang-ext:mount/module2:foo/bar` +
`Content-Type: applicaton/xml` +
 +
`  …` +

POST

/restconf/config

Creates the data if it does not exist

`POST `http://localhost:8181/restconf/config/[`http://localhost:8181/restconf/config/`] +
`content-type: application/yang.data+json` +
`JSON payload:` +
`  {` +
`    "toaster:toaster" :` +
`    {` +
`      "toaster:toasterManufacturer" : "General Electric",` +
`      "toaster:toasterModelNumber" : "123",` +
`      "toaster:toasterStatus" : "up"` +
`    }` +
`  }`

POST

/restconf/config/`<identifier>`

Creates the data if it does not exist in the Config datastore, and
returns the state about success. `<identifier>` points to a data node
where data must be stored. The root element of data must have the
namespace (data are in XML) or module name (data are in JSON.)

Example:

`POST `http://[`http://`]`:8181/restconf/config/module1:foo` +
`Content-Type: applicaton/xml/` +
 +
`  …` +

Example with mount point:

`POST `http://[`http://`]`:8181/restconf/config/` +
`  module1:foo1/foo2/yang-ext:mount/module2:foo` +
`Content-Type: applicaton/xml` +
 +
`  …` +

POST

/restconf/operations/`<moduleName>`:`<rpcName>`

Invokes RPC. `<moduleName>`:`<rpcName>` - `<moduleName>` is the name of
the module and `<rpcName>` is the name of the RPC in this module. The
Root element of the data sent to RPC must have the name “input”. The
result can be the status code or the retrieved data having the root
element “output”.

Example:

`POST `http://[`http://`]`:8181/restconf/operations/module1:fooRpc` +
`Content-Type: applicaton/xml` +
`Accept: applicaton/xml` +
 +
`  …` +

The answer from the server could be:

`  …` +

An example using a JSON payload:

`POST `http://[`http://`]`:8181/restconf/operations/toaster:make-toast` +
`Content-Type: application/yang.data+json` +
`{` +
`  "input" :` +
`  {` +
`     "toaster:toasterDoneness" : "10",` +
`     "toaster:toasterToastType":"wheat-bread" ` +
`  }` +
`}`

Note: Even though this is a default for the toasterToastType value in
the yang, you still need to define it.''

DELETE

/restconf/config/`<identifier>`

Removes the data node in the Config datastore and returns the state
about success. `<identifier>` points to a data node which must be
removed.

 

GET

/restconf/streams

List of all notification event streams.

Example call

`GET `http://[`http://`]`:8181/restconf/streams` +
`Accept: applicaton/xml`

Example of response

 +
`  ` +
`    ``opendaylight-inventory:nodes/datastore=CONFIGURATION/scope=BASE` +
`    ``DESCRIPTION_PLACEHOLDER` +
`    ``true` +
`    ` +
`    ` +
`  ` +

GET

/restconf/streams/stream/`<stream_name>`

Subscribes to `stream_name` to receive notifications from this stream

Example

`GET `http://[`http://`]`:8181/restconf/streams/stream/` +
`  opendaylight-inventory:nodes/datastore=CONFIGURATION/scope=BASE`

More information is available at:
http://tools.ietf.org/html/draft-bierman-netconf-restconf-02[Restconf
RFC]

[[known-issues]]
= Known Issues

There are several known issues associated with Restconf usage:

* Trying to make an RPC which has no inputs returns an exception (HTTP
500 error).
** *Reason*: If you have content-type _defined_ when you make an RPC
call with no input then you will be directed to a java method which
expects non-null/empty input and thus fails accordingly.
** *Workaround*: Removing the content-type header results in the rest
call getting routed to a different java method which expects an empty
body and thus there is success.
* The cancel-toast method in the MD-SAL toaster example still fails with
an exception.

:*This is a bug in either the toaster or MD-SAL core code. Essentially
the cancel-toaster call returns a null future object, which the rpc
caller chokes on (i.e. doesn't null check). While the simple fix is to
change the toaster to return a non-null future, we should consider
enhancing the RPC caller to gracefully handle null futures. No bug has
been filed on this yet.

* All query parameters appear to be ignored.
** patches for support of
https://bugs.opendaylight.org/show_bug.cgi?id=2155[depth] and
https://bugs.opendaylight.org/show_bug.cgi?id=2153[prettyPrint] query
parameters are tracked in corresponding bugs

