[[md-sal-and-odl-app-tutorials]]
=== MD-SAL and ODL App Tutorials

* OpenDaylight_Controller:MD-SAL:Toaster_Tutorial[Toaster Tutorial]
**
https://cisco.webex.com/ciscosales/lsr.php?RCID=3a6016d6a55c40c78a1a5fe5b44c5d61[Webex
recording from a Toaster code/design walkthrough on 2014/04/16]
* OpenDaylight Controller:MD-SAL:Toaster Step-By-Step[Toaster
Step-By-Step]
* OpenDaylight Controller:MD-SAL:MD-SAL App Tutorial[Learning Switch
Tutorial]
* link:Ping[Simple TCP Ping Plugin]
* http://sdntutorials.com/qa/[MD-SAL Q&A] (a tutorial by Ciena)
* http://sdntutorials.com/difference-between-ad-sal-and-md-sal/[AD-SAL /
MD-SAL Comparison] (a tutorial by Ciena)
* OpenDaylight_Toolkit:MD-SAL-Simple_Archetype[MD-SAL Simple Archetype]
* OpenDaylight_Controller:MD-SAL:Archetype_Tutorial[Yet Another MD-SAL
Simple Archetype Tutorial]

[[tutorial-videos-on-youtube]]
=== Tutorial Videos on YouTube

*
https://www.youtube.com/playlist?list=PL9t_Bh_snqSwyOnR5vtVwQH4bbegfXvFQ[YouTube:
5 Minute or less ODL Tutorials]: a set of excellent short tutorials
covering various aspects of ODL (config subsystem for now)
*
https://www.youtube.com/playlist?list=PL8F5jrwEpGAhSUlVz14S50aSRfHCWLXOQ[Youtube:
Developers: Intro to OpenDaylight]

[[md-sal-how-tos---quick-code-snippets-tutorials-by-ciena]]
=== MD-SAL How Tos - Quick Code Snippets (Tutorials by Ciena)

* http://sdntutorials.com/how-to-insert-data-in-md-sal-data-store/[How
To Insert Data In MD-SAL Data Store] (outdated)
* http://sdntutorials.com/how-to-register-a-service-to-md-sal/[How To
Register A Service To MD-SAL]
* http://sdntutorials.com/how-to-publish-notifications-to-md-sal/[How To
Publish Notifications To MD-SAL]
*
http://sdntutorials.com/how-to-handle-notifications-published-to-md-sal/[How
To Handle Notifications Published To MD-SAL]
*
http://sdntutorials.com/how-to-access-data-in-md-sal-from-mount-point/[How
To Access Data In MD-SAL From MountPoint]
* http://sdntutorials.com/how-to-look-up-data-in-md-sal/[How To Look Up
Data In MD-SAL]
* http://sdntutorials.com/how-to-publish-node-to-md-sal/[How To Publish
Node To MD-SAL]
* http://sdntutorials.com/how-to-publish-nodeconnector-to-md-sal/[How To
Publish NodeConnector To MD-SAL]
* http://sdntutorials.com/how-to-publish-link-to-md-sal/[How To Publish
Link To MD-SAL]
* http://sdntutorials.com/how-to-remove-node-from-md-sal/[How To Remove
Node From MD-SAL]
* http://sdntutorials.com/how-to-remove-nodeconnector-from-md-sal/[How
To Remove NodeConnector From MD-SAL]
* http://sdntutorials.com/how-to-remove-link-from-md-sal/[How To Remove
Link From MD-SAL]
*
http://sdntutorials.com/how-to-look-up-topology-and-links-in-md-sal/[How
To Look Up Topology and Links In MD-SAL]
*
http://sdntutorials.com/how-to-lookup-all-nodeconnectors-of-a-node-in-md-sal/[How
to Lookup all NodeConnectors of a Node in MD-SAL]
*
http://sdntutorials.com/how-md-sal-identifies-southbound-plugin-for-flow-provisioning/[How
MD-SAL Identifies Southbound Plugin For Flow Provisioning]

Note* - Some of the above code snippets work for hydrogen release and
are deprecated for helium. I am currently working on writing code
snippets for helium and will be updated here soon.

[[netconfyang-tutorials]]
=== Netconf/Yang Tutorials

* http://www.yang-central.org/twiki/bin/view/Main/YangDocuments[Yang
Central]: the first section lists a bunch of tutorials.
* http://www.netconfcentral.org/[Netconf Central]: this is more netconf
oriented, but still contains a lot of yang-related information
*
http://www.tail-f.com/wordpress/wp-content/uploads/2013/02/Tail-f-Presentation-Netconf-Yang.pdf[Tail-F:
a yang overview paper:]
* http://www.slideshare.net/tailfsystems/netconf-yang-tutorial[A
Netconf/Yang Tutorial by Tail-F]
* http://trac.tools.ietf.org/wg/netconf/trac/wiki[IETF Netconf wiki]:
contains a list if Netconf/Yang pointers
* https://code.google.com/p/pyang/wiki/Tutorial[YANG modeling tutorial
(pyang)]
*
https://www.dropbox.com/s/bsu11hj1ophf5b2/pyang-test.tgz?dl=0[Pyang-based
validation scripts, presented at Dev Design Summit]

