[[about]]
= About

[[repository]]
== Repository

* coretutorials
** git clone https://git.opendaylight.org/gerrit/p/coretutorials.git

[[project-proposal]]
== Project Proposal

Controller_Core_Functionality_Tutorials:Project_proposal[Project
Proposal]

[[documents]]
== Documents

Controller_Core_Functionality_Tutorials:Lithium_Release_Plan[Lithium
Release Plan]

[[getting-started]]
= Getting Started

[[documentation]]
== Documentation

WIP WIP WIP WIP WIP

* GettingStarted:Project_Main#New_Project_Checklist[ New Project
Checklist]
* OpenDaylight_Controller:Development_Infrastructure_Overview[ Back-end
systems]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:Architecture[Overall
Architecture]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:Config_SubSystem[Config
Subsystem Sub-Project]
* OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:MD_SAL[MD-SAL
Sub-Project]
* OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:YANG[YANG
Sub-Project]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:KARAF_OSGI[Karaf/OSGi
Sub-Project]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:RESTCONF[RESTCONF
Sub-Project]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:RESTCONF_NETCONF[RESTCONF/NETCONF
Sub-Project - Placeholder]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:General_Pain[Painpoints
not captured in templates - Placeholder]
*
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:Morez_buckets[Buckets
not captured in templates - Placeholder]

[[how-to-add-a-new-tutorial]]
== How to Add a New Tutorial

Run the OpenDaylight_Controller:MD-SAL:Startup_Project_Archetype[MD-SAL
Startup Project Archetype]:

`mvn archetype:generate -DarchetypeGroupId=org.opendaylight.controller -DarchetypeArtifactId=opendaylight-startup-archetype -DarchetypeRepository=`http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/[`http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/`]` -DarchetypeVersion=1.0.0-SNAPSHOT -DarchetypeCatalog=`http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/archetype-catalog.xml[`http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/archetype-catalog.xml`]

Make sure the groupID is defined as _org.opendaylight.coretutorials_,
and the package has the name of your tutorial. Respond to the prompts as
follows:

`Define value for property 'groupId': : `*`org.opendaylight.coretutorials`* +
`Define value for property 'artifactId': : `** +
`Define value for property 'version':  1.0-SNAPSHOT: : 1.0.0-SNAPSHOT` +
`Define value for property 'package':  org.opendaylight.coretutorials: : `** +
`Define value for property 'classPrefix':  ${artifactId.substring(0,1).toUpperCase()}${artifactId.substring(1)}: : ` +
`Define value for property 'copyright': : Copyright (c) 2015 Yoyodyne, Inc.`

Use the directory structure generated by the archetype to add your yang
models, code and configuration files.

[[tutorials]]
= Tutorials

* OpenDaylight Controller:MD-SAL:Startup Project Archetype[Breaking
ground on your project: Hello World]
* Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project[
Karaf-Based Application 101: Toaster]
*
Controller_Core_Functionality_Tutorials:Tutorials:Data_Store_Benchmarking_and_Data_Access_Patterns[
Working with the MD-SAL Datastore: Data Access Patterns and
Benchmarking]
* Controller_Core_Functionality_Tutorials:Tutorials:Netconf Mount[
Working with Netconf devices]
*
Controller_Core_Functionality_Tutorials:Tutorials:IETF Syslog Yang Model Implementation for Linux[
IETF Syslog Yang Model Implementation for Linux]
*
Controller_Core_Functionality_Tutorials:Tutorials:Event / Notification Manager[
Working with Southbound Plugin Notifications]

[[how-tos-and-useful-tips]]
= How-Tos and Useful Tips

* OpenDaylight_dlux:Create_and_add_a_module[How to create and add a
module in dlux]

