This page describes the API offered by VTN Manager for components inside
OpenDaylight controller. All the classes described on this page are
implemented in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#bundle.api[manager]
bundle and placed in *org.opendaylight.vtn.manager* package.

Further, in this page, the package name is omitted during the reference
of Java classes other than the one offered by VTN Manager.

:;Object

::
  ;;
    java.lang.Object

[[java-class]]
= Java class

This section describes Java class offered by VTN Manager as API.

[[vtn-class]]
== VTN class

This section describes Java class showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information.

[[vtenantpath]]
=== VTenantPath

------------------------------------------------
public class VTenantPath implements Serializable
------------------------------------------------

*VTenantPath* is a class that shows the position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
inside container. It is used to identify the VTN while executing any
operations against it.

[[constructor]]
==== Constructor

=====

VTenantPath(String)

=====

-------------------------------------
public VTenantPath(String tenantName)
-------------------------------------

It creates VTenantPath object that shows the position of that
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
having the specified name.

Specify string showing VTN name in tenantName.

* Exception will not occur even if incorrect names like `null` etc. are
specified, but if you specify such a VTenantPath object in API of
link:#IVTNManager[IVTNManager] service it will give error.

[[instance-method]]
==== Instance method

=====

getTenantName()

=====

-----------------------------
public String getTenantName()
-----------------------------

It returns the name of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
configured in VTenantPath object.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* Object specified in o is a VTenantPath object.
* The following value inside o is equal to value in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
name

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VTenantPath object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VTenantPath object.

[[vtenantconfig]]
=== VTenantConfig

--------------------------------------------------
public class VTenantConfig implements Serializable
--------------------------------------------------

*VTenantConfig* is a class that shows the config information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].
This is used during the creation or modification of VTN for specifying
VTN information to VTN Manager.

[[constructor-1]]
==== Constructor

=====

VTenantConfig(String)

=====

---------------------------------
public VTenantConfig(String desc)
---------------------------------

It creates VTenantConfig object that shows config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify any description for VTN in desc. `null` will imply that
description is not configured for VTN.

If this constructor is used, then Flow entry timeout value becomes
unset.

=====

VTenantConfig(String, int, int)

=====

-----------------------------------------------------
public VTenantConfig(String desc, int idle, int hard)
-----------------------------------------------------

It creates VTenantConfig object showing the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify the following values in argument.

:;desc

::
  ;;
    Specify any description for VTN.
    +
    * `null` will imply that description is not configured for VTN.

The value set in hard must be bigger than idle if the value set in both
idle and hard is bigger than 0. Exception will not occur even if
incorrect value is specified in idle or hard, but there will be error if
you specify such VTenantConfig object in API of
link:#IVTNManager[IVTNManager] service.

[[instance-method-1]]
==== Instance Method

=====

getDescription()

=====

------------------------------
public String getDescription()
------------------------------

It returns the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
description set in VTenantConfig object. It returns `null` in case of no
description.

=====

getIdleTimeout()

=====

---------------------------
public int getIdleTimeout()
---------------------------

It returns seconds configured in idle_timeout of flow entry set in
VTenantConfig object.

It returns -1 in case no value is configured.

=====

getIdleTimeoutValue()

=====

------------------------------------
public Integer getIdleTimeoutValue()
------------------------------------

It returns the Integer object for seconds configured in idle_timeout of
flow entry set in VTenantConfig object.

It returns `null` in case no value is configured.

=====

getHardTimeout()

=====

---------------------------
public int getHardTimeout()
---------------------------

It returns the seconds configured in hard_timeout of flow entry set in
VTenantConfig object.

It returns -1 in case no value is configured.

=====

getHardTimeoutValue()

=====

------------------------------------
public Integer getHardTimeoutValue()
------------------------------------

It returns the Integer object for seconds configured in hard_timeout of
flow entry set in VTenantConfig object.

It returns `null` in case no value is configured.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VTenantConfig object.
* The following values stored in o are the same as in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
description
** Seconds set in idle_timeout of Flow entry
** Seconds set in hard_timeout of Flow entry

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VTenantConfig object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VTenantConfig object.

[[vtenant]]
=== VTenant

------------------------------------------
public class VTenant extends VTenantConfig
------------------------------------------

*VTenant* is a class that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information. It inherits link:#VTenantConfig[VTenantConfig] class and
also holds VTN config information. VTN Manager passes the VTN
information to other components by passing the VTenant object having VTN
information .

[[constructor-2]]
==== Constructor

=====

VTenant(String, VTenantConfig)

=====

------------------------------------------------------
public VTenant(String tenantName, VTenantConfig tconf)
------------------------------------------------------

It creates VTenant object that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information.

Specify following values in argument.

:;tenantName

::
  ;;
    Specify VTN name.

[[instance-method-2]]
==== Instance method

=====

getName()

=====

-----------------------
public String getName()
-----------------------

It returns the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
name configured in VTenant object.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VTenant object.
* The following values stored in o are the same as in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
name
** VTN description
** Seconds set in idle_timeout of Flow entry
** Seconds set in hard_timeout of Flow entry

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VTenant object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VTenant object.

[[vbridge-class]]
== VBridge class

This section describes the Java class that shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information.

[[vbridgepath]]
=== VBridgePath

--------------------------------------------
public class VBridgePath extends VTenantPath
--------------------------------------------

*VBridgePath* is a class for showing the position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside container. It inherits link:#VTenantPath[VTenantPath] and also
stores position information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
to which vBridge belongs. This is used for identifying the vBridge
during any operation performed against it.

[[constructor-3]]
==== Constructor

=====

VBridgePath(String, String)

=====

--------------------------------------------------------
public VBridgePath(String tenantName, String bridgeName)
--------------------------------------------------------

It creates VBRidgePath object showing position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This constructor specifies the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
to which vBridge belongs by using name.

Specify following values in argument.

:;tenantName

::
  ;;
    Specify VTN name.

Exception will not occur even if incorrect names like `null` etc. are
specified in tenantName or bridgeName but if you specify such
VBridgePath object in API of link:#IVTNManager[IVTNManager] service, it
will give error.

=====

VBridgePath(VTenantPath, String)

=====

-------------------------------------------------------------
public VBridgePath(VTenantPath tenantPath, String bridgeName)
-------------------------------------------------------------

It creates VBRidgePath object that shows the position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This constructor specifies the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
to which vBridge belongs by using link:#VTenantPath[VTenantPath].

Specify following values in argument.

:;tenantPath

::
  ;;
    Specify link:#VTenantPath[VTenantPath] object that specifies the
    position of VTN.
    +
    * All the values inside tenantPath get copied to VBridgePath object.
    * NullPointerException will occur if you specify `null`.

[[instance-method-3]]
==== Instance method

=====

getBridgeName()

=====

-----------------------------
public String getBridgeName()
-----------------------------

It returns the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
name set in VBridgePath object.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VBridgePath object.
* The following values inside o are equal to value in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
name
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
name

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VBridgePath object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VBridgePath object.

[[vbridgeconfig]]
=== VBridgeConfig

--------------------------------------------------
public class VBridgeConfig implements Serializable
--------------------------------------------------

*VBridgeConfig* is a class showing config information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This is used for specifying vBridge information to VTN Manager during
creation or modification of vBridge.

[[constructor-4]]
==== Constructor

=====

VBridgeConfig(String)

=====

---------------------------------
public VBridgeConfig(String desc)
---------------------------------

It creates VBridgeConfig object showing config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify any description for vBridge in desc. `null` will imply that
description is not configured for vBridge.

OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable.aging[Aging]
interval of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] becomes unset if this constructor is used.

=====

VBridgeConfig(String, int)

=====

------------------------------------------
public VBridgeConfig(String desc, int age)
------------------------------------------

It creates VBridgeConfig object that shows config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify following values in argument.

:;desc

::
  ;;
    Specify any description for vBridge
    +
    * `null` will imply that description is not configured for vBridge.

Exception will not occur even if incorrect value is specified in age,
but there will be error if you specify such VBridgeConfig object in API
of link:#IVTNManager[IVTNManager] service.

[[instance-method-4]]
==== Instance method

=====

getDescription()

=====

------------------------------
public String getDescription()
------------------------------

It returns
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
description configured in VBridgeConfig object. It returns `null` if no
description is set.

=====

getAgeInterval()

=====

---------------------------
public int getAgeInterval()
---------------------------

It returns the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable.aging[aging]
interval in seconds for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] configured in VBridgeConfig object.

It returns -1 if no value is set.

=====

getAgeIntervalValue()

=====

------------------------------------
public Integer getAgeIntervalValue()
------------------------------------

It returns Integer object showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable.aging[aging]
interval (seconds) for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] configured in VBridgeConfig object.

It returns `null` when no value is set.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VBridgeConfig object.
* The following values inside o are equivalent to the value in own
object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
description
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable.aging[aging]
interval for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table]

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VBridgeConfig object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VBridgeConfig object.

[[vbridge]]
=== VBridge

------------------------------------------
public class VBridge extends VBridgeConfig
------------------------------------------

*VBridge* is a class showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information. It inherits link:#VBridgeConfig[VBridgeConfig] class and
also holds vBridge config information. VTN Manager passes the vBridge
information to other components by passing vBridge object having the
vBridge information.

[[constructor-5]]
==== Constructor

=====

VBridge(String, VNodeState, int, VBridgeConfig)

=====

------------------------------------------------------------------------------------
public VBridge(String bridgeName, VNodeState state, int faults, VBridgeConfig bconf)
------------------------------------------------------------------------------------

It creates VBridge object showing the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information.

Specify following values in argument.

:;bridgeName

::
  ;;
    Specify vBridge name.

[[instance-method-5]]
==== Instance method

=====

getName()

=====

-----------------------
public String getName()
-----------------------

It returns
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
name configured in VBridge object.

=====

getState()

=====

----------------------------
public VNodeState getState()
----------------------------

It returns the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
state configured in VBridge object.

* link:#VNodeState.UNKNOWN[VNodeState.UNKNOWN] is returned when vBridge
is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.state.UNKNOWN[UNKNOWN]
state.
* link:#VNodeState.DOWN[VNodeState.DOWN] is returned when vBridge is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.state.DOWN[DOWN]
state.
* link:#VNodeState.UP[VNodeState.UP] is returned when vBridge is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.state.UP[UP]
state.

====

getFaults()

====

----------------------
public int getFaults()
----------------------

It returns the number of path faults configured inside VBridge object.
It returns *0* is path fault has not been detected.

The value returned by this method shows the number of paths that could
not be configured by VTN Manager between the switches that constitute
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
because the paths were broken.

Number of path faults is counted for both directions of the path. E.g.,
when switch *A* and switch *B* are separated, then the path from switch
*A* to switch *B* and path from switch *B* to switch *A* are counted as
different paths.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VBridge object.
* The following values inside o are equal to the values in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
name
** vBridge description
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable.aging[aging]
interval for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table]
** Number of path faults detected inside vBridge

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VBridge object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VBridge object.

[[virtual-interface-class]]
== Virtual Interface class

This section describes the Java class that shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface] information.

[[vbridgeifpath]]
=== VBridgeIfPath

*VBridgeIfPath* is a class showing position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
It inherits link:#VBridgePath[VBridgePath] and stores position
information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
and
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
to which virtual interface belongs.

This is used for specifying target vbridge interface when performing
vBridge interface operations.

[[constructor-6]]
==== Constructor

=====

VBridgeIfPath(String, String, String)

=====

-------------------------------------------------------------------------
public VBridgeIfPath(String tenantName, String bridgeName, String ifName)
-------------------------------------------------------------------------

It creates VBridgeIfPath object for showing the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] position inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This constructor specifies the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
and vBridge to which virtual interface belongs by using name.

Specify following values in argument.

:;tenantName

::
  ;;
    Specify VTN name.

Exception will not occur even if incorrect value like `null` etc. is
specified in tenantName, bridgeName or ifName, but there will be error
if such VBridgeIfPath object is specified in API of
link:#IVTNManager[IVTNManager] service.

=====

VBridgeIfPath(VBridgePath, String)

=====

-----------------------------------------------------------
public VBridgeIfPath(VBridgePath bridgePath, String ifName)
-----------------------------------------------------------

It creates VBridgeIfPath object showing position of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This constructor specifies the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
to which virtual interface belongs by using
link:#VBridgePath[VBridgePath].

Specify following values in argument.

:;bridgePath

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that specifies vBridge
    location.
    +
    * All the values in bridgePath are copied in VBridgeIfPath object.
    * NullPointerException occurs if you specify `null`.

[[instance-method-6]]
==== Instance method

=====

getInterfaceName()

=====

--------------------------------
public String getInterfaceName()
--------------------------------

It returns
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] name configured in vBridgeIfPath object.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* The object specified in o is a VBridgeIfPath object.
** The following values inside o are equal to the values in own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
name
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
name
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] name

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VBridgeIfPath object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VBridgeIfPath object.

[[vinterfaceconfig]]
=== VInterfaceConfig

-----------------------------------------------------
public class VInterfaceConfig implements Serializable
-----------------------------------------------------

*VInterfaceConfig* is a class that shows config information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface]. This is used for specifying virtual interface information to
VTN Manager during creation or modification of interface in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[constructor-7]]
==== Constructor

=====

VInterfaceConfig(String, Boolean)

=====

-----------------------------------------------------
public VInterfaceConfig(String desc, Boolean enabled)
-----------------------------------------------------

It creates VInterfaceConfig object that shows the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface].

Specify following values in argument.

:;desc

::
  ;;
    Specify any description for virtual interface in desc.
    +
    * `null` will imply that description is not configured for
    interface.

[[instance-method-7]]
==== Instance method

=====

getDescription()

=====

------------------------------
public String getDescription()
------------------------------

It returns description of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] configured in VInterfaceConfig object. It returns `null` if
description is not set.

=====

getEnabled()

=====

---------------------------
public Boolean getEnabled()
---------------------------

It returns the enable/disable configuration of interface set in
VInterfaceConfig object.

* It returns *Boolean.TRUE* if it is configured as enable.
* It returns *Boolean.FALSE* if it is configured as disable.
* It returns `null` if enable or disable is not specified.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether object specified in o is equal to own object or
not.

It returns true only when all the following conditions are met.

* Object specified by o is VInterfaceConfig object.
* Following values maintained in the o are equal to the values inside
own object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[Virtual
interface] description
** Interface enable/ disable configuration

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VInterfaceConfig object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VInterfaceConfig object.

[[vinterface]]
=== VInterface

------------------------------------------------
public class VInterface extends VInterfaceConfig
------------------------------------------------

*VInterface* is a class that shows information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface]. It inherits link:#VInterfaceConfig[VInterfaceConfig] class
and config information of virtual interface is also maintained. VTN
Manager passes the virtual interface information to other components by
passing the VInterface object that maintains virtual interface
information.

[[constructor-8]]
==== Constructor

=====

VInterface(String, VNodeState, VNodeState, VInterfaceConfig)

=====

---------------------------------------------------------------------------------------------
public VInterface(String ifName, VNodeState state, VNodeState estate, VInterfaceConfig iconf)
---------------------------------------------------------------------------------------------

It creates VInterface object that shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] information.

Specify following values in argument.

:;ifName

::
  ;;
    Specify the interface name.

[[instance-method-8]]
==== Instance method

=====

getName()

=====

-----------------------
public String getName()
-----------------------

It returns the name of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] configured in VInterface object.

=====

getState()

=====

----------------------------
public VNodeState getState()
----------------------------

It returns the state of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] configured in VInterface object.

* If interface is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface.state.UNKNOWN[UNKNOWN]
state, then link:#VNodeState.UNKNOWN[VNodeState.UNKNOWN] is returned.
* If interface is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface.state.DOWN[DOWN]
state, then link:#VNodeState.DOWN[VNodeState.DOWN] is returned.
* If interface is in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface.state.UP[UP]
state, then link:#VNodeState.UP[VNodeState.UP] is returned.

=====

getEntityState()

=====

----------------------------------
public VNodeState getEntityState()
----------------------------------

It returns the state of network elements mapped to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] configured in VInterface object. It returns the state of
physical port of switch that is mapped, if information of interface
configured with
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
Mapping] is maintained.

* link:#VNodeState.UNKNOWN[VNodeState.UNKNOWN] gets returned if network
elements are not mapped to interface.
* link:#VNodeState.DOWN[VNodeState.DOWN] gets returned if mapped network
elements are not operating.
* link:#VNodeState.UP[VNodeState.UP] is returned if mapped network
elements are operating.

Status of mapped network elements is configured irrespective of whether
the interface is enabled or disabled. E.g., even if the interface is
disabled, this method returns link:#VNodeState.UP[VNodeState.UP] when
mapped network elements are operating.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether object specified by o is equal to own object or
not.

It returns true only if all the conditions mentioned below are met.

* Object specified by o is VInterface object.
* Following values maintained in the o are equal to the value inside own
object.
**
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[Virtual
interface] name
** Interface description
** Enable/ disable configuration of interface
** Value of link:#VNodeState[VNodeState] that shows the state of
interface
** Value of link:#VNodeState[VNodeState] that shows the status of mapped
network elements

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of VInterface object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of VInterface object.

[[class-for-port-mapping]]
== Class for Port mapping

This section describes the Java class that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information.

[[switchport]]
=== SwitchPort

-----------------------------------------------
public class SwitchPort implements Serializable
-----------------------------------------------

*SwitchPort* class is a class that shows the location of port of
physical switch. This is used to specify the port of physical switch to
be mapped during configuration of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping].

SwitchPort maintains only the information that identifies the port
within physical switch and does that maintain the information that
identifies physical switch. Port of physical switch to be mapped by Port
mapping is specified by the combination of link:#Node[Node] object,
which shows physical switch, and SwitchPort object.

[[constructor-9]]
==== Constructor

=====

SwitchPort(String)

=====

------------------------------
public SwitchPort(String name)
------------------------------

It creates SwitchPort that specifies the port of physical switch. This
constructor specifies port by the name set in the port.

Specify in name the name configured in the port of physical switch.

* String containing 1 or more characters must be specified
* Exception will not occur even if `null` or empty string is specified,
but if that SwitchPort object is used to configure
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping], then it will give an error.

=====

SwitchPort(String, String)

=====

-----------------------------------------
public SwitchPort(String type, String id)
-----------------------------------------

It creates the SwitchPort object that specifies port of physical switch.
This constructor specifies the port by type and ID of
link:#NodeConnector[NodeConnector].

Specify following values in argument.

:;type

::
  ;;
    Specify the string that shows the type of NodeConnector.
    +
    * Specify *`"OF"`* for physical port of OpenFlow switch.

Exception will not occur even if `null` or empty string is specified in
type or id but if that SwitchPort object is used to configure
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping], then it will give an error.

=====

SwitchPort(String, String, String)

=====

------------------------------------------------------
public SwitchPort(String name, String type, String id)
------------------------------------------------------

It creates the SwitchPort object that specifies the port of physical
switch. This constructor specifies the port by using the name configured
in port, and type and ID of link:#NodeConnector[NodeConnector].
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] is enabled only when port of physical switch exists for
specified NodeConnector and when the name of that port matches with the
string specified in name.

Specify following values in argument.

:;name

::
  ;;
    Specify the name configured in the port of physical switch.

If `null` is specified in argument it is treated as the conditions for
that argument were not specified. However, if following conditions are
not met, then error will be given if this SwitchPort object is used to
configure
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping].

* If `null` is specified in name, then you need to specify value other
than `null` in both type and id so that NodeConnector can be identified.
* When `null` is specified in both type and id, then you need to specify
a string containing 1 or more characters in name so that port name can
be identified.
* It is not possible that `null` is specified only in one value out of
type and id, and value other than `null` is specified in the other one.

[[instance-method-9]]
==== Instance method

=====

getName()

=====

-----------------------
public String getName()
-----------------------

It returns the name of physical port configured in SwitchPort object. It
returns `null` if the same is not configured.

=====

getType()

=====

-----------------------
public String getType()
-----------------------

It returns the string that shows the type of
link:#NodeConnector[NodeConnector] configured in SwitchPort object. It
returns `null` if the same is not configured.

=====

getId()

=====

---------------------
public String getId()
---------------------

It returns the string that shows the identifier of
link:#NodeConnector[NodeConnector] set in SwitchPort object. It returns
`null` if the same is not configured.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether object specified in o is equal to own object or
not.

It returns true only if all the following conditions are met.

* Object specified by o is SwitchPort object.
* Following values maintained in the o are equal to the value inside own
object.
** Name of the port configured in physical switch
** Type of link:#NodeConnector[NodeConnector]
** Identifier of NodeConnector

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of SwitchPort object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns string representation of SwitchPort object.

[[portmapconfig]]
=== PortMapConfig

--------------------------------------------------
public class PortMapConfig implements Serializable
--------------------------------------------------

*PortMapConfig* is a class that shows the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. This is used to specify config information to VTN Manager
during configuration of Port mapping.

[[constructor-10]]
==== Constructor

=====

PortMapConfig(Node, SwitchPort, short)

=====

------------------------------------------------------------
public PortMapConfig(Node node, SwitchPort port, short vlan)
------------------------------------------------------------

It creates PortMapConfig object that shows the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping].

Specify following values in argument.

:;node

::
  ;;
    Specify the link:#Node[Node] object corresponding to the physical
    switch that you want to map to
    OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
    interface].

[[instance-method-10]]
==== Instance method

=====

getNode()

=====

---------------------
public Node getNode()
---------------------

It returns link:#Node[Node] object that is configured in PortMapConfig
object.

=====

getPort()

=====

---------------------------
public SwitchPort getPort()
---------------------------

It returns link:#SwitchPort[SwitchPort] object that is configured in
PortMapConfig object.

=====

getVlan()

=====

----------------------
public short getVlan()
----------------------

It returns the VLAN ID configured in PortMapConfig object.

It returns *0* if configuration has been done to map Untagged Ethernet
frames.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether object specified in o is equal to own object or
not.

It returns true only if all the following conditions are met.

* Object specified by o is PortMapConfig object.
* Following values maintained internally in o, are equal to the values
within own object.
** link:#Node[Node] object corresponding to physical switch
** link:#SwitchPort[SwitchPort] object that specifies the port of
physical switch
** VLAN ID

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns hash code of PortMapConfig object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns the string representation of PortMapConfig object.

[[portmap]]
=== PortMap

--------------------------------------------
public class PortMap implements Serializable
--------------------------------------------

*PortMap* is a class that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information set in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. VTN Manager passes the Port mapping information to other
components by passing PortMap object that maintains Port mapping
information.

[[constructor-11]]
==== Constructor

=====

PortMap(PortMapConfig, NodeConnector)

=====

------------------------------------------------------
public PortMap(PortMapConfig pmconf, NodeConnector nc)
------------------------------------------------------

It creates PortMap object that shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information.

Specify following values in argument.

:;pmconf

::
  ;;
    Specify link:#PortMapConfig[PortMapConfig] object that shows config
    information of Port mapping.

[[instance-method-11]]
==== Instance method

=====

getConfig()

=====

--------------------------------
public PortMapConfig getConfig()
--------------------------------

It returns the link:#PortMapConfig[PortMapConfig] object set in PortMap
object. Config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] is included in the values that are returned.

=====

getNodeConnector()

=====

---------------------------------------
public NodeConnector getNodeConnector()
---------------------------------------

It returns the link:#NodeConnector[NodeConnector] object set in PortMap
object.

* If physical port is actually mapped to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface], it returns the NodeConnector object corresponding to that
port.
* It returns `null` if no physical port meets the conditions specified
by link:#PortMapConfig[PortMapConfig] object.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* Object specified by o is PortMap object.
* Following values maintained in o are same as the values within own
object.
** link:#PortMapConfig[PortMapConfig] object that shows config
information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping]
** link:#NodeConnector[NodeConnector] object corresponding to mapped
physical switch port

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns the hash code of PortMap object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns the string representation of PortMap object.

[[class-for-vlan-mapping]]
== Class for VLAN mapping

This section explains the Java class that shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information.

[[vlanmapconfig]]
=== VlanMapConfig

--------------------------------------------------
public class VlanMapConfig implements Serializable
--------------------------------------------------

*VlanMapConfig* is a class that shows the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This is used to specify config information to VTN Manager during
configuration of VLAN mapping.

[[constructor-12]]
==== Constructor

=====

VlanMapConfig(Node, short)

=====

-------------------------------------------
public VlanMapConfig(Node node, short vlan)
-------------------------------------------

It creates the VlanMapConfig object that shows the config information of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping].

Specify the following values in the parameter.

:;node

::
  ;;
    Specify the link:#Node[Node] object that corresponds to the physical
    switch that you want to map.
    +
    * Specify `null` if you want to map all switches instead of
    identifying a particular switch.

[[instance-method-12]]
==== Instance method

=====

getNode()

=====

---------------------
public Node getNode()
---------------------

It returns that link:#Node[Node] object configured in VlanMapConfig
object.

=====

getVlan()

=====

----------------------
public short getVlan()
----------------------

It returns the VLAN ID configured in VlanMapConfig object.

It returns *0* if the configuration has been done to map Untagged
Ethernet frame.

=====

isOverlapped(VlanMapConfig)

=====

-------------------------------------------------
public boolean isOverlapped(VlanMapConfig vlconf)
-------------------------------------------------

It determines whether there is a duplicate of the VLAN mapped by
VlanMapConfig object.

Specify in vlconf the VlanMapConfig object that you want to judge.
Further, NullPointerException will occur if you specify `null` in
vlconf.

It compares the config information stored in vlconf and own object, and
returns true if all the following conditions are met. It will return
false in other cases.

* Value of VLAN ID is equal.
* Same Node object is configured, or if Node object is not configured in
one of the two.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* Object specified in o is a VlanMapConfig object.
* Values stored inside o are equal to the values in own object.
** link:#Node[Node] object corresponding to the physical switch to be
mapped
** VLAN ID

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns the hash code of VlanMapConfig object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns the string representation of VlanMapConfig object.

[[vlanmap]]
=== VlanMap

------------------------------------------
public class VlanMap extends VlanMapConfig
------------------------------------------

*VlanMap* is a class that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] information configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
It inherits the link:#VlanMapConfig[VlanMapConfig] class, and it also
stores the config information of VLAN Mapping. VTN Manager passes the
VLAN Mapping information to other components by passing the VlanMap
object that stores the VLAN Mapping information.

[[constructor-13]]
==== Constructor

=====

VlanMap(String, Node, short)

=====

------------------------------------------------
public VlanMap(String id, Node node, short vlan)
------------------------------------------------

It creates the VlanMap object that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] information.

Specify the following values in the parameter.

:;id

::
  ;;
    Specify the identifier allocated in VLAN mapping.

[[instance-method-13]]
==== Instance method

=====

getId()

=====

---------------------
public String getId()
---------------------

It returns the identifier allocated in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping].

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object
or not.

It returns true only if all the following conditions are met.

* Object specified in o is a VlanMap object.
* Values stored inside o are equal to the values in own object.
** link:#Node[Node] object corresponding to the physical switch to be
mapped
** VLAN ID
** Identifier allocated in VLAN Mapping

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns the hash code of VlanMap object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns the string representation of VlanMap object.

[[mac-address-table-class]]
== MAC address table class

This section describes the Java class that shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] information inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[macaddressentry]]
=== MacAddressEntry

----------------------------------------------------
public class MacAddressEntry implements Serializable
----------------------------------------------------

*MacAddressEntry* is a class that shows the MAC address information
learned inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table]. VTN Manager passes the MAC address information inside
MAC address table to other components by passing the MacAddressEntry
object that stores the MAC address information.

[[constructor-14]]
==== Constructor

=====

MacAddressEntry(DataLinkAddress, short, NodeConnector, Set

=====

----------------------------------------------------------------------------------------------------
public MacAddressEntry(DataLinkAddress addr, short vlan, NodeConnector nc, Set<InetAddress> ipaddrs)
----------------------------------------------------------------------------------------------------

It shows the MacAddressEntry object that shows the MAC address
information.

:;addr

::
  ;;
    Specify the link:#DataLinkAddress[DataLinkAddress] object that shows
    the MAC address.
    +
    * `null` must not be specified. Behavior is not defined if `null` is
    specified.

[[instance-method-14]]
==== Instance method

=====

getAddress()

=====

-----------------------------------
public DataLinkAddress getAddress()
-----------------------------------

It returns that link:#DataLinkAddress[DataLinkAddress] object that shows
the MAC address that was detected.

=====

getVlan()

=====

----------------------
public short getVlan()
----------------------

It returns the VLAN ID configured in the Ethernet frame where MAC
address is detected.

It returns *0* if the VLAN tag is not configured in the Ethernet frame
where MAC address is detected.

=====

getNodeConnector()

=====

---------------------------------------
public NodeConnector getNodeConnector()
---------------------------------------

It returns the link:#NodeConnector[NodeConnector] object corresponding
to the physical port of the switch where MAC address is detected.

=====

getInetAddresses()

=====

------------------------------------------
public Set<InetAddress> getInetAddresses()
------------------------------------------

It returns the set of InetAddress object that shows the IP address
configured in Ethernet frame where MAC address is detected.

* If multiple IP addresses corresponding to MAC address are detected,
then it returns the set that includes all the detected IP addresses.
* If no IP address is detected, then it returns an empty set.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object.

It returns true only if all the following conditions are met.

* Object specified in o is a MacAddressEntry object.
* Values stored inside o are equal to the values in own object.
** link:#DataLinkAddress[DataLinkAddress] object corresponding to the
MAC address
** link:#NodeConnector[NodeConnector] object corresponding to the
physical port of the switch
** Array of InetAddress object that shows the IP address list
corresponding to MAC address

=====

hashCode()

=====

---------------------
public int hashCode()
---------------------

It returns the hash code of the MacAddressEntry object.

=====

toString()

=====

------------------------
public String toString()
------------------------

It returns the string representation of MacAddressEntry object.

[[other-classes]]
== Other classes

[[vnodestate]]
=== VNodeState

----------------------
public enum VNodeState
----------------------

*VNodeState* is an Enumeration class that shows the status of virtual
nodes, like
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
etc., present in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

[[constants]]
==== Constants

VNodeState defines the following constants.

:;

UNKNOWN

::
  ;;
    It implies that the status of virtual node cannot be determined.

[[instance-method-15]]
==== Instance method

=====

getValue()

=====

---------------------
public int getValue()
---------------------

It returns the numeric representation of VNodeState object.

[[vtnexception]]
=== VTNException

-------------------------------------------
public class VTNException extends Exception
-------------------------------------------

*VTNException* is an exception for notifying errors that occur in OSGi
services provided by VTN Manager. It stores the link:#Status[Status]
showing the cause of internal error.

[[constructor-15]]
==== Constructor

=====

VTNException(Status)

=====

----------------------------------
public VTNException(Status status)
----------------------------------

It creates the VTNException object that internally stores the
link:#Status[Status] specified in status. Message configured in status
will get configured in exception message.

=====

VTNException(Status, String)

=====

-------------------------------------------------
public VTNException(StatusCode code, String desc)
-------------------------------------------------

It creates the VTNException object that internally stores the
link:#Status[Status] created from code and desc. desc gets configured in
the message of the exception.

=====

VTNException(String, Throwable)

=====

----------------------------------------------------
public VTNException(String message, Throwable cause)
----------------------------------------------------

It creates an VTNException object which shows that VTN Manager has
caught an unexpected exception cause. message gets configured in the
exception message.

*StatusCode.INTERNALERROR* will be the value of the
link:#StatusCode[StatusCode] of link:#Status[Status] configured
internally.

[[instance-method-16]]
==== Instance method

=====

getStatus()

=====

-------------------------
public Status getStatus()
-------------------------

It returns the link:#Status[Status] configured in VTNException object.
It returns `null` if Status is not configured.

[[bundleversion]]
=== BundleVersion

---------------------------
public class BundleVersion 
---------------------------

*BundleVersion* class shows version information of OSGi bundle. It is
used for passing OSGi bundle version of VTN Manager to other components.

[[constructor-16]]
==== Constructor

=====

BundleVersion(int, int, int, String)

=====

------------------------------------------------------------------------
public BundleVersion(int major, int minor, int micro, String qualifier) 
------------------------------------------------------------------------

It creates a BundleVersion object that shows the OSGi bundle version
information.

Specify following values in the argument.

:;major

::
  ;;
    Specify major component of OSGi bundle version.

[[instance-method-17]]
==== Instance method

=====

getMajor()

=====

---------------------
public int getMajor()
---------------------

It returns the value for major component of OSGi bundle version
configured in BundleVersion object.

=====

getMinor()

=====

---------------------
public int getMinor()
---------------------

It returns the value for minor component of OSGi bundle version
configured in BundleVersion object.

=====

getMicro()

=====

---------------------
public int getMicro()
---------------------

It returns the value for micro component of OSGi bundle version
configured in BundleVersion object.

=====

getQualifier()

=====

----------------------------
public String getQualifier()
----------------------------

It returns the value for qualifier component of OSGi bundle version
configured in BundleVersion object.

It returns `null` if qualifier is not configured in OSGi bundle version.

=====

equals(Object)

=====

-------------------------------
public boolean equals(Object o)
-------------------------------

It determines whether the object specified in o is equal to own object.

It returns true only if all the following conditions are met.

::* Object specified in o is a BundleVersion object.

::* Following values stored inside o are equal to the values inside own
object.

:::* Major component

:::* Minor component

:::* Micro component

:::* Qualifier component

=====

hashCode()

=====

----------------------
public int hashCode() 
----------------------

It returns hash code of BundleVersion object.

=====

toString()

=====

-------------------------
public String toString() 
-------------------------

It returns the string representation of BundleVersion object.

[[osgi-services]]
= OSGi services

This section describes the specifications of OSGi services provided by
VTN Manager.

Further, except for link:#IVTNGlobal[IVTNGlobal] service, all other are
instantiated for each container.

[[ivtnglobal]]
== IVTNGlobal

----------------------------
public interface IVTNGlobal 
----------------------------

*IVTNGlobal* is an interface that defines OSGi service for providing
container independent functionalities of VTN Manager. IVTNGlobal service
is instantiated inside OpenDaylight controller only once, and it is
registered in OSGi service registry.

[[version-information-retrieval-api]]
=== Version information retrieval API

This section describes the API for retrieving version information of VTN
Manager.

====

getApiVersion()

====

---------------------------
public int getApiVersion() 
---------------------------

It returns the number showing API version of VTN Manager. API version
will be a numerical value equal to or more than 1, and it gets
incremented when the API of VTN Manager is changed.

Current VTN Manager will return 1 as API version.

====

getBundleVersion()

====

----------------------------------------
public BundleVersion getBundleVersion() 
----------------------------------------

It returns the link:#BundleVersion[BundleVersion] object that shows the
version information of OSGi bundle that implements VTN Manager.

It returns `null` if version information of OSGi bundle could not be
retrieved.

[[ivtnmanager]]
== IVTNManager

----------------------------
public interface IVTNManager
----------------------------

*IVTNManager* is the interface that defines OSGi services for operating
VTN Manager. IVTNManager service is instantiated for each container and
it is registered in OSGi service registry. It is possible to give
instructions to VTN Manager inside the container by calling the
necessary methods after acquiring from OSGi service registry the object
where IVTNManager service is implemented.

[[api-for-vtn-operations]]
=== API for VTN operations

This section describes the APIs provided for operating
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

====

getTenants()

====

------------------------------------------------------
public List<VTenant> getTenants() throws VTNException;
------------------------------------------------------

It acquires the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
present in Container.

In case of normal end, it returns the List object that includes
link:#VTenant[VTenant] objects corresponding to all the VTNs present
inside the container. It returns an empty List object if VTN is not
present inside the Container.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.INTERNALERROR

::
  ;;
    Fatal internal error occurred in VTN Manager.

====

getTenant(VTenantPath)

====

---------------------------------------------------------------
public VTenant getTenant(VTenantPath path) throws VTNException;
---------------------------------------------------------------

It retrieves the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify in path the link:#VTenantPath[VTenantPath] object that specifies
the position of VTN.

In case of normal end, it returns link:#VTenant[VTenant] object that
shows the information of the VTN specified in path.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in VTN name inside the path.

====

addTenant(VTenantPath, VTenantConfig)

====

---------------------------------------------------------------
public Status addTenant(VTenantPath path, VTenantConfig tconf);
---------------------------------------------------------------

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
inside the Container.

Specify the following values in argument.

:;path

::
  ;;
    Specify the link:#VTenantPath[VTenantPath] object that specifies the
    position of the VTN that you want to create. VTN name inside the
    path must be configured using a string that meets the following
    conditions.
    +
    * Configure a string having 1 or more and 31 or less characters.
    * String must contain only US-ASCII alphabets, numbers, and
    underscore ('_').
    * First character must be US-ASCII alphabet or number.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or tconf.
    * Incorrect VTN name is configured in path.
    * Incorrect value is configured in idle_timeout or hard_timeout of
    tconf.

====

modifyTenant(VTenantPath, VTenantConfig, boolean)

====

-------------------------------------------------------------------------------
public Status modifyTenant(VTenantPath path, VTenantConfig tconf, boolean all);
-------------------------------------------------------------------------------

It modifies the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify the following values in argument.

:;path

::
  ;;
    Specify the link:#VTenantPath[VTenantPath] object that shows the
    position of the VTN that you want to modify.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or tconf.
    * `null` is configured in the VTN name inside path.
    * Incorrect value is configured in idle_timeout or hard_timeout of
    tconf.

====

removeTenant(VTenantPath)

====

---------------------------------------------
public Status removeTenant(VTenantPath path);
---------------------------------------------

It removes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].
All the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
etc., which are included inside the specified VTN will also be removed.

Specify in path the link:#VTenantPath[VTenantPath] object that specifies
the position of VTN that you want to remove.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name inside path.

[[api-for-vbridge-operations]]
=== API for vBridge operations

This section describes the APIs provided for operating
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

====

getBridges(VTenantPath)

====

----------------------------------------------------------------------
public List<VBridge> getBridges(VTenantPath path) throws VTNException;
----------------------------------------------------------------------

It retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
present inside the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify in path the link:#VTenantPath[VTenantPath] object that specifies
the position of VTN.

In case of normal end, it returns the List object that includes
link:#VBridge[VBridge] objects corresponding to all the vBridges that
are present inside VTN specified in path. It returns an empty list
object if vBridge is not present inside the specified VTN.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name inside path.

====

getBridge(VBridgePath)

====

---------------------------------------------------------------
public VBridge getBridge(VBridgePath path) throws VTNException;
---------------------------------------------------------------

It retrieves the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge.

In case of normal end, it returns the link:#VBridge[VBridge] object that
shows the information of the vBridge specified in path.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name inside path.

====

addBridge(VBridgePath, VBridgeConfig)

====

---------------------------------------------------------------
public Status addBridge(VBridgePath path, VBridgeConfig bconf);
---------------------------------------------------------------

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge that you want to create. vBridge name inside the
    path must be configured using a string that meets the following
    conditions.
    +
    * Configure a string having 1 or more and 31 or less characters.
    * String must contain only US-ASCII alphabets, numbers, and
    underscore ('_').
    * First character must be US-ASCII alphabet or number.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or bconf.
    * Incorrect vBridge name is configured inside path.
    * Incorrect value is configured in bconf for the aging interval of
    MAC address table.

====

modifyBridge(VBridgePath, VBridgeConfig, boolean)

====

-------------------------------------------------------------------------------
public Status modifyBridge(VBridgePath path, VBridgeConfig bconf, boolean all);
-------------------------------------------------------------------------------

It modifies the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge that you want to modify.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or bconf.
    * `null` is configured in the VTN name or vBridge name inside path.
    * Incorrect value is configured in bconf for the aging interval of
    MAC address table.

====

removeBridge(VBridgePath)

====

---------------------------------------------
public Status removeBridge(VBridgePath path);
---------------------------------------------

It removes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
All the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] etc. that are included inside the specified vBridge will also
get removed.

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge that you want to remove.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name inside path.

[[api-for-vbridge-interface-operations]]
=== API for vBridge interface operations

This section describes the APIs provided for operating the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

====

getBridgeInterfaces(VBridgePath)

====

----------------------------------------------------------------------------------
public List<VInterface> getBridgeInterfaces(VBridgePath path) throws VTNException;
----------------------------------------------------------------------------------

It retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] present inside the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge.

In case of normal end, it returns the List object that includes
link:#VInterface[VInterface] objects corresponding to all the virtual
interfaces that are present inside the vBridge specified in path. It
returns an empty list object if virtual interface is not present inside
the specified vBridge.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name inside path.

====

getBridgeInterface(VBridgeIfPath)

====

-----------------------------------------------------------------------------
public VInterface getBridgeInterface(VBridgeIfPath path) throws VTNException;
-----------------------------------------------------------------------------

It retrieves the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

Specify in path the link:#VBridgeIfPath[VBridgeIfPath] object that
specifies the position of vBridge interface.

In case of normal end, it returns the link:#VInterface[VInterface]
object that shows the information of the vBridge interface specified in
path.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name or interface
    name inside path.

====

addBridgeInterface(VBridgeIfPath, VInterfaceConfig)

====

-----------------------------------------------------------------------------
public Status addBridgeInterface(VBridgeIfPath path, VInterfaceConfig iconf);
-----------------------------------------------------------------------------

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgeIfPath[VBridgeIfPath] object that shows the
    position of vBridge interface that you want to create. Interface
    name inside the path must be configured using a string that meets
    the following conditions.
    +
    * Configure a string having 1 or more and 31 or less characters.
    * String must contain only US-ASCII alphabets, numbers, and
    underscore ('_').
    * First character must be US-ASCII alphabet or number.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or iconf.
    * Incorrect interface name is configured inside path.

====

modifyBridgeInterface(VBridgeIfPath, VInterfaceConfig, boolean)

====

---------------------------------------------------------------------------------------------
public Status modifyBridgeInterface(VBridgeIfPath path, VInterfaceConfig iconf, boolean all);
---------------------------------------------------------------------------------------------

It modifies the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgeIfPath[VBridgeIfPath] object that shows the
    position of vBridge interface that you want to modify.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or iconf.
    * `null` is configured in the VTN name or vBridge name or interface
    name inside path.

====

removeBridgeInterface(VBridgeIfPath)

====

--------------------------------------------------------
public Status removeBridgeInterface(VBridgeIfPath path);
--------------------------------------------------------

It removes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

Specify in path the link:#VBridgeIfPath[VBridgeIfPath] object that
specifies the position of vBridge interface that you want to remove.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name or interface
    name inside path.

[[api-for-port-mapping-operations]]
=== API for Port Mapping operations

This section describes the APIs provided for operating
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
Mapping].

====

getPortMap(VBridgeIfPath)

====

------------------------------------------------------------------
public PortMap getPortMap(VBridgeIfPath path) throws VTNException;
------------------------------------------------------------------

It retrieves the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
Mapping] information configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

Specify in path the link:#VBridgeIfPath[VBridgeIfPath] object that
specifies the position of vBridge interface.

In case of normal end, it returns link:#PortMap[PortMap] object that
shows the Port Mapping information configured in the vBridge interface
specified in path. It returns `null` if Port Mapping is not configured
on the specified vBridge interface.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name or interface
    name inside path.

====

setPortMap(VBridgeIfPath, PortMapConfig)

====

-------------------------------------------------------------------
public Status setPortMap(VBridgeIfPath path, PortMapConfig pmconf);
-------------------------------------------------------------------

It configures
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
Mapping] in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. If Port Mapping is already configured in the specified
vBridge interface, then old configuration is deleted and the specified
settings get applied.

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgeIfPath[VBridgeIfPath] object that shows the
    position of vBridge interface where Port Mapping is to be
    configured.

If value other than `null` is specified in pmconf, then Ethernet frame
that flows through the port of the physical switch specified in pmconf
will get mapped to the vBridge interface specified in path.

* In pmconf, you must configure the link:#Node[Node] object
corresponding to the physical switch that you want to map to the
interface.
** Currently, it is possible to configure only the Node objects that
correspond to OpenFlow switches.
* In pmconf, you must specify the link:#SwitchPort[SwitchPort] object
that shows the position of the physical switch port that you want to map
to the interface.
** Currently, it is possible to configure only the physical ports of
OpenFlow switches.
** Configuration of Port Mapping will succeed even if the specified
physical port of the switch does not exist. Port Mapping will come into
effect whenever, at a later point in time, the specified physical port
is found.
* The VLAN network of Ethernet frame is mapped to the interface
according to the VLAN ID configured in pmconf.
** If a value between *1* or more and *4095* or less is configured, then
the Ethernet frames that have this VLAN ID configured will get mapped to
interface.
** If *0* is configured, untagged Ethernet frames will get mapped to
interface.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name or interface
    name inside path.
    * pmconf is not `null` and, in addition, Node or SwitchPort object
    is not configured in that.
    * pmconf is not `null` and, in addition, incorrect value is
    configured in that for Node or SwitchPort object.
    * pmconf is not `null` and, in addition, incorrect VLAN ID is
    configured in that.

[[api-for-vlan-mapping-operations]]
=== API for VLAN Mapping operations

This section describes the APIs provided for operating
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping].

====

getVlanMaps(VBridgePath)

====

-----------------------------------------------------------------------
public List<VlanMap> getVlanMaps(VBridgePath path) throws VTNException;
-----------------------------------------------------------------------

It retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge.

In case of normal end, it returns List object that includes
link:#VlanMap[VlanMap] objects corresponding to all the VLAN Mapping
configured on vBridge specified in path. It returns an empty List object
if VLAN Mapping is not configured on the specified vBridge.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name inside path.

====

getVlanMap(VBridgePath, String)

====

------------------------------------------------------------------------------
public VlanMap getVlanMap(VBridgePath path, String mapId) throws VTNException;
------------------------------------------------------------------------------

It retrieves the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] information configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge.

In case of normal end, it returns the link:#VlanMap[VlanMap] object that
shows the information of VLAN Mapping specified in path and mapId.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or mapId.
    * `null` is configured in the VTN name or vBridge name inside path.

====

getVlanMap(VBridgePath, VlanMapConfig)

====

--------------------------------------------------------------------------------------
public VlanMap getVlanMap(VBridgePath path, VlanMapConfig vlconf) throws VTNException;
--------------------------------------------------------------------------------------

Out of the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] that are configured on the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge],
it retrieves the VLAN Mapping information that contains the specified
config information.

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge.

If any VLAN Mapping with the config information that matches with vlconf
is present in the vBridge specified in the path, then it returns
link:#VlanMap[VlanMap] object that shows that VLAN Mapping information.

Else, link:#VTNException[VTNException] that includes the
link:#Status[Status] showing error cause is thrown. Following are the
main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or vlconf.
    * `null` is configured in the VTN name or vBridge name inside path.

====

addVlanMap(VBridgePath, VlanMapConfig)

====

--------------------------------------------------------------------------------------
public VlanMap addVlanMap(VBridgePath path, VlanMapConfig vlconf) throws VTNException;
--------------------------------------------------------------------------------------

It configures
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge .

VLAN network specified in vlconf will get mapped to vBridge specified in
path.

* In vlconf, it is possible to configure link:#Node[Node] object
corresponding to physical switch that is to be the target of VLAN
Mapping.
** Currently, it is possible to configure the Node objects corresponding
to OpenFlow switches only as a target of VLAN Mapping.
** Configuration of VLAN Mapping will succeed even if the physical
switch corresponding to the specified Node object does not exist. VLAN
Mapping will come into effect whenever, at a later point in time, the
specified physical switch is found.
** All the physical switches will be a target of VLAN Mapping if the
Node object is not configured.
* The VLAN network is mapped to vBridge according to the VLAN ID
configured inside vlconf.
** If a value between *1* or more and *4095* or less is configured, then
the Ethernet frames that have this VLAN ID configured will get mapped to
vBridge.
** If *0* is configured, untagged Ethernet frames will get mapped to
vBridge.

In case of normal end, it returns the link:#VlanMap[VlanMap] object that
shows the information for VLAN mapping that was configured.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or vlconf.
    * `null` is configured in the VTN name or vBridge name inside path.
    * Incorrect Node object is configured inside vlconf.
    * Incorrect VLAN ID is configured inside vlconf.

====

removeVlanMap(VBridgePath, String)

====

------------------------------------------------------------
public Status removeVlanMap(VBridgePath path, String mapId);
------------------------------------------------------------

It removes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
Mapping] configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge wherein the VLAN Mapping is to be removed.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or mapId.
    * `null` is configured in the VTN name or vBridge name inside path.

[[api-for-arp-transmission]]
=== API for ARP transmission

This section describes the APIs provided for sending ARP request to
Broadcast domains that correspond to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

====

findHost(InetAddress, Set)

====

-----------------------------------------------------------------
public void findHost(InetAddress addr, Set<VBridgePath> pathSet);
-----------------------------------------------------------------

It sends broadcast ARP request to find hosts that have the specified IP
address.

Specify the following values in argument.

:;addr

::
  ;;
    Specify the InetAddress object that shows the IP address that you
    want to search.
    +
    * It returns without doing anything in following cases.
    ** If `null` is specified.
    ** If InetAddress object that shows IPv6 address is specified.

====

probeHost(HostNodeConnector)

====

-------------------------------------------------
public boolean probeHost(HostNodeConnector host);
-------------------------------------------------

It sends unicast ARP request to check the existence of a specified host.

Specify the link:#HostNodeConnector[HostNodeConnector] object
corresponding to the host in host. ARP request will be sent to the
Physical switch port corresponding to the
link:#NodeConnector[NodeConnector] configured in host.

It returns *true* if ARP request is actually sent. It returns *false* if
it is not sent.

Following are main reasons for returning *false*.

* If `null` is specified in host.
* If NodeConnector object is not configured inside host.
* If the physical port corresponding to the NodeConnector object
configured in host is not operating.
* If the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
to which the host belongs does not exist.

[[api-for-mac-address-table]]
=== API for MAC address table

This section describes the API provided for operating
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

====

getMacEntries(VBridgePath)

====

---------------------------------------------------------------------------------
public List<MacAddressEntry> getMacEntries(VBridgePath path) throws VTNException;
---------------------------------------------------------------------------------

It retrieves the MAC address information list learned inside the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge.

In case of normal end, it returns the List object that includes the
link:#MacAddressEntry[MacAddressEntry] objects corresponding to entire
MAC address information learned inside MAC address table of the vBridge
specified in path. It returns an empty List object if not even one MAC
address is learnt inside the specified vBridge.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path.
    * `null` is configured in the VTN name or vBridge name inside path.

====

getMacEntry(VBridgePath, DataLinkAddress)

====

-----------------------------------------------------------------------------------------------
public MacAddressEntry getMacEntry(VBridgePath path, DataLinkAddress addr) throws VTNException;
-----------------------------------------------------------------------------------------------

It searches the specified MAC address information from the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify the link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge.

It returns link:#MacAddressEntry[MacAddressEntry] that shows the MAC
address information corresponding to addr if the MAC address specified
in addr has been learnt inside the MAC address table. It returns `null`
if the MAC address specified in addr has not been learnt.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or addr.
    * `null` is configured in the VTN name or vBridge name inside path.

====

removeMacEntry(VBridgePath, DataLinkAddress)

====

--------------------------------------------------------------------------------------------------
public MacAddressEntry removeMacEntry(VBridgePath path, DataLinkAddress addr) throws VTNException;
--------------------------------------------------------------------------------------------------

It removes the specified MAC address information from
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify the following values in argument.

:;path

::
  ;;
    Specify the link:#VBridgePath[VBridgePath] object that shows the
    position of vBridge.

It returns link:#MacAddressEntry[MacAddressEntry] object that shows the
removed information if MAC Address information has been removed in
reality. It returns `null` if the MAC address specified in addr has not
been learnt.

In case of abnormal end, link:#VTNException[VTNException] that includes
the link:#Status[Status] showing error cause is thrown. Following are
the main link:#StatusCode[StatusCode] set in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path or addr.
    * `null` is configured in the VTN name or vBridge name inside path.

====

flushMacEntries(VBridgePath)

====

------------------------------------------------
public Status flushMacEntries(VBridgePath path);
------------------------------------------------

It removes all the MAC Address information learnt inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

Specify in path the link:#VBridgePath[VBridgePath] object that specifies
the position of vBridge.

In case of normal end, it returns link:#Status[Status] wherein
*link:#StatusCode[StatusCode].SUCCESS* is configured.

In case of abnormal end, it returns the Status showing error cause.
Following are the main StatusCode configured in Status.

:;StatusCode.BADREQUEST

::
  ;;
    * `null` is specified in path
    * `null` is configured in the VTN name or vBridge name inside path.

[[other-api]]
=== Other API

====

isActive()

====

--------------------------
public boolean isActive();
--------------------------

It determines whether the Virtual network of VTN Manager is operating
inside the Container. It returns *true* if virtual network by VTN
Manager is operating and *false* if it is not operating.

Even if one
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
is created inside Container, then it is judged that virtual network of
VTN Manager is operating and it returns true. However, if container
other than default container is present, then VTN Manager inside the
default container gets disabled. In this case, isActive() will always
return error against the IVTNManager service for default container.

[[ivtnmanageraware]]
== IVTNManagerAware

---------------------------------
public interface IVTNManagerAware
---------------------------------

*IVTNManagerAware* defines the listener interface that monitors the
status change of VTN Manager inside container. Corresponding method gets
called when there is a change in the management information of VTN
Manager, if you register in OSGi service registry the object where
IVTNManagerAware is implemented.

===

vtnChanged(VTenantPath, VTenant, UpdateType)

===

---------------------------------------------------------------------------
public void vtnChanged(VTenantPath path, VTenant vtenant, UpdateType type);
---------------------------------------------------------------------------

This is called when the information related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
inside Container gets changed.

Following values gets specified in arguments.

:;path

::
  ;;
    link:#VTenantPath[VTenantPath] object gets specified. This shows the
    position of the VTN where information is modified.

Further, if VTN is present in container at the time of registering in
VTN Manager the listener where IVTNManagerAware is implemented, then
this method gets called with information of each VTN specified so that
the existence of these can be notified to listener. type is specified as
*UpdateType.ADDED* in such cases.

===

vBridgeChanged(VBridgePath, VBridge, UpdateType)

===

-------------------------------------------------------------------------------
public void vBridgeChanged(VBridgePath path, VBridge vbridge, UpdateType type);
-------------------------------------------------------------------------------

This gets called when information related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside the Container gets changed.

Following values gets specified in arguments.

:;path

::
  ;;
    link:#VBridgePath[VBridgePath] object gets specified. This shows the
    position of the vBridge where information is changed.

Further, if vBridge is present in container at the time of registering
in VTN Manager the listener where IVTNManagerAware is implemented, then
this method gets called with information of each vBridge specified so
that the existence of these can be notified to listener.

* It is guaranteed that
#IVTNManagerAware.vtnChanged:VTenantPath-VTenant-UpdateType[vtnChanged](link:#VTenantPath[VTenantPath],
link:#VTenant[VTenant], link:#UpdateType[UpdateType]), which notifies
the existence of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
to which this vBridge belongs, gets called first.
* *UpdateType.ADDED* gets specified in type.

===

vBridgeInterfaceChanged(VBridgeIfPath, VInterface, UpdateType)

===

--------------------------------------------------------------------------------------------
public void vBridgeInterfaceChanged(VBridgeIfPath path, VInterface viface, UpdateType type);
--------------------------------------------------------------------------------------------

This gets called when information related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside the Container is changed.

Following values gets specified in arguments.

:;path

::
  ;;
    link:#VBridgeIfPath[VBridgeIfPath] object gets specified. This shows
    the position of the vBridge interface where information is changed.

Further, if vBridge interface is present in container at the time of
registering in VTN Manager the listener where IVTNManagerAware is
implemented, then this method gets called with information of each
vBridge interface specified so that the existence of these can be
notified to listener.

* It is guaranteed that
#IVTNManagerAware.vBridgeChanged:VBridgePath-VBridge-UpdateType[vBridgeChanged](link:#VBridgePath[VBridgePath],
link:#VBridge[VBridge], link:#UpdateType[UpdateType]), which notifies
the existence of vBridge to which this vBridge interface belongs, gets
called first.
* *UpdateType.ADDED* gets specified in type.

===

vlanMapChanged(VBridgePath, VlanMap, UpdateType)

===

-----------------------------------------------------------------------------
public void vlanMapChanged(VBridgePath path, VlanMap vlmap, UpdateType type);
-----------------------------------------------------------------------------

This gets called when information related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside the Container is changed.

Following values gets specified in arguments.

:;path

::
  ;;
    link:#VBridgePath[VBridgePath] object gets specified. This shows the
    position of the vBridge where VLAN mapping information is changed.

Further, if VLAN Mapping configured vBridge is present in container at
the time of registering in VTN Manager the listener where
IVTNManagerAware is implemented, then this method gets called with
information of each VLAN Mapping specified so that the existence of
these can be notified to listener.

* It is guaranteed that
#IVTNManagerAware.vBridgeChanged:VBridgePath-VBridge-UpdateType[vBridgeChanged](link:#VBridgePath[VBridgePath],
link:#VBridge[VBridge], link:#UpdateType[UpdateType]), which notifies
the existence of vBridge wherein this VLAN Mapping is configured, gets
called first.
* *UpdateType.ADDED* gets specified in type.

===

portMapChanged(VBridgeIfPath, PortMap, UpdateType)

===

------------------------------------------------------------------------------
public void portMapChanged(VBridgeIfPath path, PortMap pmap, UpdateType type);
------------------------------------------------------------------------------

This gets called when information related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] configured in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface] inside the Container is changed.

Following values gets specified in arguments.

:;path

::
  ;;
    link:#VBridgeIfPath[VBridgeIfPath] gets specified. This shows the
    position of the vBridge interface where Port mapping information is
    changed.

Further, if Port Mapping configured vBridge interface is present in
container at the time of registering in VTN Manager the listener where
IVTNManagerAware is implemented, then this method gets called with
information of each Port Mapping specified so that the existence of
these can be notified to listener.

* It is guaranteed that
#IVTNManagerAware.vBridgeInterfaceChanged:VBridgeIfPath-VInterface-UpdateType[vBridgeInterfaceChanged](link:#VBridgeIfPath[VBridgeIfPath],
link:#VInterface[VInterface], link:#UpdateType[UpdateType]), which
notifies the Existence of vBridge interface wherein this Port Mapping is
configured, gets called first.
* *UpdateType.ADDED* gets specified in type.

[[ivtnmodelistener]]
== IVTNModeListener

---------------------------------
public interface IVTNModeListener
---------------------------------

*IVTNModeListener* defines the listener interface that monitors the
presence of virtual network environment of VTN Manager inside the
container. It is possible to detect the operation start and end of
virtual network of VTN Manager, if you register in OSGi service registry
the object where IVTNModeListener is implemented.

===

vtnModeChanged(boolean)

===

-------------------------------------------
public void vtnModeChanged(boolean active);
-------------------------------------------

This is called when the operation mode of VTN Manager inside the
Container changes.

This method is called when the value returned by
link:#IVTNManager[IVTNManager].link:#IVTNManager.isActive[isActive]() is
modified. Value returned by IVTNManager.isActive() at that point in time
gets specified in active. That is, *true* gets specified if the virtual
network of VTN Manager is operating, and *false* gets specified if it is
not operating.

Further, if you register in VTN Manager the listener where
IVTNModeListener is implemented, then this method is called for
notifying the operation mode, at that point in time, to listener.

[[ihostfinder]]
=== IHostFinder

link:#IHostFinder[IHostFinder] provides the functionality for sending
ARP request to search the host information.

Normally this service is provided by
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#arphandler[arphandler].
However, since it is necessary to uninstall arphandler for running VTN
Manager, instead this service is provided by VTN Manager.

====

find(InetAddress)

====

---------------------------------------------
public void find(InetAddress networkAddress);
---------------------------------------------

It sends Broadcast ARP request for searching the host that has the
specified IP address.

Specify in networkAddress the InetAddress object that shows the IP
address that you want to search. Further, it will return without doing
anything if `null` or IPv6 is specified in networkAddress.

The behavior of this method will vary depending upon whether
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
is present inside the container or not.

:;If VTN is present inside the Container

::
  ;;
    It will behave exactly as the same method provided by
    OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#arphandler[arphandler].
    +
    * Only when the subnet information that includes networkAddress is
    registered, ARP request is sent to the port of the switch defined by
    that subnet information.

====

probe(HostNodeConnector)

====

------------------------------------------
public void probe(HostNodeConnector host);
------------------------------------------

It sends Unicast ARP request for confirming the presence of specified
host.

Specify in host the link:#HostNodeConnector[HostNodeConnector] object
corresponding to the target host. Further, it returns without doing
anything if `null` is specified.

The behavior of this method will vary depending upon whether
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
is present inside the container or not.

:;If VTN is present inside the Container

::
  ;;
    It will behave exactly as the same method provided by
    OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#arphandler[arphandler].
    +
    * Only when the subnet information that includes IP address of host
    is registered, ARP request is sent to port of the physical switch
    corresponding to link:#NodeConnector[NodeConnector] configured in
    the host.

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
