This page describes the REST APIs provided by VTN Manager.

[[data-format]]
= Data Format

REST API of VTN Manager uses wikipedia:JSON[JSON] or wikipedia:XML[XML]
while exchanging Struct data with REST client.

* REST client uses JSON or XML format data as request body while sending
Struct data.
** Specify format of the data sent in the *Content-Type* header of HTTP.
*** Specify *Application/Json* for JSON.
*** Specify *Application/Xml* for XML.
* OpenDaylight controller uses JSON or XML format data as response body
while sending data to REST client.
** Format of the data received is decided on the basis of HTTP *Accept*
header that was sent by REST client.
*** Specify *Application/Json* for receiving data in JSON format.
*** Specify *Application/Xml* for receiving data in XML format.
*** JSON format is used if the REST client does not specify *Accept*
header.

[[data-model]]
= Data Model

This section describes the Struct data used in REST API of VTN Manager.

[[vtn-data]]
== VTN Data

This section describes the data showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information.

[[vtnconf]]
=== vtnconf

*vtnconf* shows the configuration information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].
This is used for sending VTN information to controller during creation
or modification of VTN by REST client.

* XML format

-----------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vtnconf description="Description about VTN 1" idleTimeout="300" 
         hardTimeout="0"/>
-----------------------------------------------------------------

* JSON format

---------------------------------------------
{  
  "description": "Description about VTN 1",  
  "idleTimeout": "300",  
  "hardTimeout": "0"  
}  
---------------------------------------------

Meaning of each attribute is given below.

:;

description

::
  ;;
    Specify the string that shows the description of VTN.
    +
    * There are no restrictions on the permissible characters or length
    of the string.
    * Can be omitted.

Further, if a value greater than 0 is configured in both *idleTimeout*
and *hardTimeout*, then the value specified in *hardTimeout* must be
greater than the value in *idleTimeout*.

[[vtn]]
=== vtn

*vtn* shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information. This is used for returning VTN information to REST client.

* XML format

-------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vtn name="vtn_1" description="Description about VTN 1" idleTimeout="300"
     hardTimeout="0"/>
-------------------------------------------------------------------------

* JSON format

-------------------------------------------
{
  "name": "vtn_1",
  "description": "Description about VTN 1",
  "idleTimeout": "300",
  "hardTimeout": "0"
}
-------------------------------------------

Meaning of each attribute is given below.

:;

name

::
  ;;
    VTN name gets configured.

[[vtns]]
=== vtns

*vtns* shows a list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information. This is used for returning VTN information list to REST
client.

* When child elements are included
** XML format

----------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vtns>
  <vtn name="vtn_1" description="Description about VTN 1"
       idleTimeout="300" hardTimeout="0"/>
  <vtn name="vtn_2" idleTimeout="600" hardTimeout="1000"/>
</vtns>
----------------------------------------------------------

:*JSON format

-----------------------------------------------
{
  "vtn": [
    {
      "name": "vtn_1",
      "description": "Description about VTN 1",
      "idleTimeout": "300",
      "hardTimeout": "0"
    },
    {
      "name": "vtn_2",
      "idleTimeout": "600",
      "hardTimeout": "1000"
    }
  ]
}
-----------------------------------------------

* When child elements are not included
** XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vtns/>
-------------------------------------------------------

:*JSON format

----------
{"vtn":[]}
----------

*vtns* includes 0 or more link:#vtn[vtn] as child elements.

[[vbridge-data]]
== vBridge data

This section describes the data showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information.

[[vbridgeconf]]
=== vbridgeconf

*vbridgeconf* shows the configuration information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This is used for sending vBridge information to controller during
creation or modification of vBridge by REST client.

* XML format

--------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vbridgeconf description="Description about vBridge 1" ageInterval="600"/>
--------------------------------------------------------------------------

* JSON format

--------------------------------------------------------------------
{"description": "Description about vBridge 1", "ageInterval": "600"}
--------------------------------------------------------------------

Meaning of each attribute is given below.

:;

description

::
  ;;
    Specify the string that describes vBridge.
    +
    * There are no restrictions on the permissible characters or length
    of the string.
    * Can be omitted.

[[vbridge]]
=== vbridge

*vbridge* shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information. This is used to return vBridge information to REST client.

* XML format

-------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vbridge name="vbridge_1" description="Description about vBridge 1"
         ageInterval="600" faults="0" state="-1"/>
-------------------------------------------------------------------

* JSON format

-----------------------------------------------
{
  "name": "vbridge_1",
  "description": "Description about vBridge 1",
  "ageInterval": "600",
  "faults": "0",
  "state": "-1"
}
-----------------------------------------------

Meaning of each attribute is given below.

:;

name

::
  ;;
    vBridge name gets configured.

[[vbridges]]
=== vbridges

*vbridges* shows the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
information. This is used for returning vBridge information list to REST
client.

* When child elements are included
** XML format

---------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vbridges>
  <vbridge name="vbridge_1" description="Description about vBridge 1"
           ageInterval="600" faults="0" state="-1" />
  <vbridge name="vbridge_2" ageInterval="1000" faults="2" state="0"/>
</vbridges>
---------------------------------------------------------------------

:*JSON format

---------------------------------------------------
{
  "vbridge": [
    {
      "name": "vbridge_1",
      "description": "Description about vBridge 1",
      "ageInterval": "600",
      "faults": "0",
      "state": "-1"
    },
    {
      "name": "vbridge_2",
      "ageInterval": "1000",
      "faults": "2",
      "state": "0"
    }
  ]
}
---------------------------------------------------

* When child elements are not included
** XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vbridges/>
-------------------------------------------------------

:*JSON format

--------------
{"vbridge":[]}
--------------

*vbridges* includes 0 or more link:#vbridge[vbridge] as child elements.

[[interface-data]]
== Interface data

This section describes the data showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface] information.

[[interfaceconf]]
=== interfaceconf

*interfaceconf* shows the configuration information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. This is used for sending interface information to controller
during creation or modification of vBridge interface by REST client.

* XML format

--------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<interfaceconf description="Description about IF-1" enabled="true"/>
--------------------------------------------------------------------

* JSON format

----------------------------------------------------------
{"description": "Description about IF-1", "enabled": true}
----------------------------------------------------------

Meaning of each attribute is given below.

:;

description

::
  ;;
    Specify the string showing interface description.
    +
    * There are no restrictions on the permissible characters or length
    of the string.
    * Can be omitted.

[[interface]]
=== interface

*interface* shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface] information. This is used for returning vBridge interface
information to REST client.

* XML format

----------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<interface name="if_1" state="-1" entityState="-1"
           description="Description about IF-1" enabled="true"/>
----------------------------------------------------------------

* JSON format

------------------------------------------
{
  "name": "if_1",
  "state": "-1",
  "entityState": "-1",
  "description": "Description about IF-1",
  "enabled": "true"
}
------------------------------------------

Meaning of each attribute is given below.

:;

name

::
  ;;
    Interface name gets configured.

Further, the status of network elements are configured irrespective of
whether interface is enabled or not. E.g., even if the interface is
disabled, *1* will be configured in
link:#interface.entityState[entityState] if the mapped network elements
are operating.

[[interfaces]]
=== interfaces

*interfaces* shows the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface] information. This is used for returning vBridge interface
information list to REST client.

* When child elements are included
** XML format

--------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<interfaces>
  <interface name="if_1" state="-1" entityState="-1"
             description="Description about IF-1" enabled="true"/>
  <interface name="if_2" state="0" entityState="1" enabled="false"/>
</interfaces>
--------------------------------------------------------------------

:*JSON format

----------------------------------------------
{
  "interface":[
    {
      "name": "if_1",
      "state": "-1",
      "entityState": "-1",
      "description": "Description about IF-1",
      "enabled": "true"
    },
    {
      "name": "if_2",
      "state": "0",
      "entityState": "1",
      "enabled": "false"
    }
  ]
}
----------------------------------------------

* When child elements are not included
** XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<interfaces/>
-------------------------------------------------------

:*JSON format

----------------
{"interface":[]}
----------------

*interfaces* includes 0 or more link:#interface[interface] as child
elements.

[[port-mapping-data]]
== Port mapping data

This section describes the data showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information.

[[portmapconf]]
=== portmapconf

*portmapconf* shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] configuration information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. This is used to send configuration information to controller
during configuration of Port mapping by REST client.

* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<portmapconf vlan="100">
  <node>
    <type>OF</type>
    <id>00:00:00:00:00:00:00:03</id>
  </node>
  <port name="port-1" type="OF" id="1"/>
</portmapconf>
-------------------------------------------------------

* JSON format

-----------------------------------
{
  "vlan": 100,
  "node": {
    "type": "OF",
    "id": "00:00:00:00:00:00:00:03"
  },
  "port": {
    "name": "port-1",
    "type": "OF",
    "id": "1"
  }
}
-----------------------------------

Meaning of each attribute is given below.

:;

vlan

::
  ;;
    Specify the VLAN ID to be mapped by using numerical value.
    +
    * Allowed range for value is between *0* or more and *4095* or less.
    * *0* implies untagged ethernet frame.
    * If omitted, it will be treated as if *0* is specified.

*node* element shows the `Node` information corresponding to the switch
that is mapped to interface. It is necessary to include one *node*
element in *portmapconf*.

Meaning of elements inside *node* is given below.

:;

type

::
  ;;
    Specify the string showing `Node` type.
    +
    * Specify *OF* for OpenFlow switch.

*port* element shows the condition for identifying physical ports of the
switch specified in the element link:#portmapconf.node[node]. It is
necessary to include one *node* element in *portmapconf*.

Meaning of *port* attributes is given below.

:;

name

::
  ;;
    Show port name of switch.
    +
    * It is necessary to specify a character string with 1 or more
    characters.
    * If the attribute *name* is omitted, then it is necessary to
    specify both *type* and *id* attributes.

Actual physical port of switch that gets mapped to vBridge interface is
decided as follows.

* If the attribute link:#portmapconf.port.name[name] is configured in
the element link:#portmapconf.port[port], then out of the physical ports
in the switch specified in the element link:#portmapconf.node[node],the
physical port that has the specified port name will get mapped.
* If the attributes link:#portmapconf.port.type[type] and
link:#portmapconf.port.id[id] are configured in the element
link:#portmapconf.port[port], then out of the physical ports in the
switch specified in the element link:#portmapconf.node[node], the
physical port corresponding to the specified `NodeConnector` will get
mapped.
* If all the attributes are configured in the element
link:#portmapconf.port[port], then out of the physical ports in the
switch specified in the element link:#portmapconf.node[node], the
physical port that meets all the condition will get mapped.

::
  I.e., Port mapping will be enabled only if the specified port name is
  configured for the specified `NodeConnector`.

[[portmap]]
=== portmap

*portmap* shows the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information corresponding to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. It is used for returning Port mapping information to REST
client.

* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<portmap vlan="100">
  <node>
    <type>OF</type>  
    <id>00:00:00:00:00:00:00:03</id>
  </node>
  <port name="port-1" type="OF" id="1"/>
  <mapped type="OF" id="1" />
</portmap>
-------------------------------------------------------

* JSON format

-----------------------------------
{
  "vlan": "100",
  "node": {
    "type": "OF",
    "id": "00:00:00:00:00:00:00:03"
  },
  "port": {
    "name": "port-1",
    "type": "OF",
    "id": "1"
  },
  "mapped": {
    "type": "OF",
    "id": "1"
  }
}
-----------------------------------

Meaning of each attribute is given below.

:;

vlan

::
  ;;
    Mapped VLAN ID gets configured.
    +
    * *0* implies that untagged ethernet frame is mapped.

Details given in the elements link:#portmapconf.node[node] and
link:#portmapconf.port[port] of link:#portmapconf[portmapconf], which
was specified during port mapping configuration, will get configured in
*node* element and *port* element respectively.

*mapped* element shows the `NodeConnector` information corresponding to
physical port of the switch which is actually mapped. If there are no
physical ports that meet the condition mentioned in
link:#portmapconf[portmapconf], then the element *mapped* is omitted.

Meaning of attributes of the element *mapped* is as follows.

:;

type

::
  ;;
    String showing the type of `NodeConnector` gets configured.
    +
    * *OF* is configured in case of OpenFlow switch.

[[vlan-mapping-data]]
== VLAN mapping data

This section describes the data showing
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information.

[[vlanmapconf]]
=== vlanmapconf

*vlanmapconf* shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] configuration information for
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
This is used to send configuration information to controller during
configuration of VLAN mapping by REST client.

* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vlanmapconf vlan="100">
  <node>
    <type>OF</type>
    <id>00:00:00:00:00:00:00:03</id>
  </node>
</vlanmapconf>
-------------------------------------------------------

* JSON format

-----------------------------------
{
  "vlan": "100",
  "node":  {
    "type": "OF",
    "id": "00:00:00:00:00:00:00:03"
  }
}
-----------------------------------

Meaning of each attribute is given below.

:;

vlan

::
  ;;
    Specify the VLAN ID to be mapped by using numerical value.
    +
    * Allowed range for value is between *0* or more and *4095* or less.
    * *0* implies untagged ethernet frame.
    * If omitted, it will be treated as if *0* is specified.

*vlanmapconf* can include one *node* element in child elements. The
element *node* shows the `Node` information corresponding to the switch
that is to be mapped. If the element *node* is omitted, then all the
switches are mapped.

Meaning of elements inside *node* is given below.

:;

type

::
  ;;
    Specify the string showing the type of `Node`.
    +
    * Specify *OF* for OpenFlow switch.

[[vlanmap]]
=== vlanmap

*vlanmap* shows
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information. This is used for returning VLAN mapping
information to REST client.

* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vlanmap id="OF-00:00:00:00:00:00:00:03.0" vlan="0">
  <node>
    <type>OF</type>
    <id>00:00:00:00:00:00:00:03</id>
  </node>
</vlanmap>
-------------------------------------------------------

* JSON format

---------------------------------------
{
  "id": "OF-00:00:00:00:00:00:00:03.0",
  "vlan": "0",
  "node": {
    "type": "OF",
    "id": "00:00:00:00:00:00:00:03"
  }
}
---------------------------------------

Meaning of each attribute is as follows.

:;

id

::
  ;;
    Identifier allocated in VLAN mapping information gets configured.

Contents of link:#vlanmapconf.node[node] element of
link:#vlanmapconf[vlanmapconf] specified during VLAN Mapping
configuration gets set in *node*. The element *node* will be omitted if
switch is not specified.

[[vlanmaps]]
=== vlanmaps

*vlanmaps* shows list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information. This is used for sending VLAN mapping information
list to REST client.

* When child elements are included
** XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vlanmaps>
  <vlanmap id="OF-00:00:00:00:00:00:00:03.0" vlan="0">
    <node>
      <type>OF</type>
      <id>00:00:00:00:00:00:00:03</id>
    </node>
  </vlanmap>
  <vlanmap id="ANY.7" vlan="7"/>
</vlanmaps>
-------------------------------------------------------

:*JSON format

-------------------------------------------
{
  "vlanmap": [
    {
      "id": "OF-00:00:00:00:00:00:00:03.0",
      "vlan": "0",
      "node": {
        "type": "OF",
        "id": "00:00:00:00:00:00:00:03"
      }
    },
    {
      "id": "ANY.7",
      "vlan": "7"
    }
  ]
}
-------------------------------------------

* When child elements are not included
** XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vlanmaps/>
-------------------------------------------------------

:*JSON format

--------------
{"vlanmap":[]}
--------------

*vlanmaps* includes 0 or more link:#vlanmap[vlanmap] as child elements.

[[mac-address-table-data]]
== MAC address table data

This section describes the data that shows the MAC address information
learned in
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[macentry]]
=== macentry

*macentry* shows the MAC address information learned inside
[OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable|MAC
address table]]. This is used to return MAC address information inside
MAC address table to REST client.

:* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<macentry address="01:02:03:04:05:06" vlan="0">
  <node>
    <type>OF</type>
    <id>00:00:00:00:00:11:22:33</id>
  </node>
  <port type="OF" id="1"/>
  <inetAddresses>
    <inetAddress address="192.168.10.1"/>
  </inetAddresses>
</macentry>
-------------------------------------------------------

:* JSON format

----------------------------------------------
{ 
  "address": "01:02:03:04:05:06",
  "vlan": "0",
  "node": {
    "type": "OF",
    "id": "00:00:00:00:00:11:22:33"
  },
  "port": {
    "type": "OF",
    "id": "1"
  },
  "inetAddresses": {
    "inetAddress": {"address": "192.168.10.1"}
  }
} 
----------------------------------------------

Meaning of each attribute is as follows.

:;

address

::
  ;;
    String showing the learned MAC address gets configured.
    +
    * String wherein hexadecimal notation of each octet inside MAC
    address are concatenated by `':'` gets configured.

Element *node* shows the `Node` information corresponding to switch
where MAC address is detected.

Meaning of elements inside *node* is as follows.

:;

type

::
  ;;
    String showing the type of `Node` gets configured.
    +
    * *OF* gets configured for OpenFlow switches.

Element *port* shows the `NodeConnector` information corresponding to
physical port of switch where MAC address is detected.

Meaning of attributes of element *port* is as follows.

:;

type

::
  ;;
    String showing the type of `NodeConnector` gets configured.
    +
    * *OF* gets configured for OpenFlow switches.

Element *inetAddresses* shows the IP address information configured in
the Ethernet frame where MAC address was detected.

* If multiple IP address corresponding to MAC address are detected, then
the information for all the IP addresses that were detected gets
configured.
* If no IP address is detected, element *inetAddresses* is omitted.

One or more than one *inetAddress* elements are configured inside the
element *inetAddresses*. String representation of the detected IP
address gets configured in the attribute *address* of each *inetAddress*
element.

[[macentries]]
=== macentries

*macentries* shows the list of MAC address information learned inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table]. This is used to return MAC address information list to
REST client.

* When child elements are included

:* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<macentries>
  <macentry address="01:02:03:04:05:06" vlan="0">
    <node>
      <type>OF</type>
      <id>00:00:00:00:00:11:22:33</id>
    </node>
    <port type="OF" id="1"/>
    <inetAddresses>
      <inetAddress address="192.168.10.1"/>
    </inetAddresses>
  </macentry>
  <macentry address="11:22:33:44:55:66" vlan="1">
    <node>
      <type>OF</type>
      <id>00:00:00:00:12:34:56:78</id>
    </node>
    <port type="OF" id="2"/>
    <inetAddresses>
      <inetAddress address="192.168.10.20"/>
      <inetAddress address="10.1.2.3"/>
    </inetAddresses>
  </macentry>
</macentries>
-------------------------------------------------------

:* JSON format

--------------------------------------------------
{
  "macentry": [
    {
      "address": "01:02:03:04:05:06",
      "vlan": "0",
      "node": {
        "type": "OF",
        "id": "00:00:00:00:00:11:22:33"
      },
      "port": {
        "type": "OF",
        "id": "1"
      },
      "inetAddresses": {
        "inetAddress": {"address": "192.168.10.1"}
      }
    },
    {
      "address": "11:22:33:44:55:66",
      "vlan": "1",
      "node": {
        "type":"OF",
        "id": "00:00:00:00:12:34:56:78"
      },
      "port": {
        "type": "OF",
        "id":"2"
      },
      "inetAddresses": {
        "inetAddress": [
          {"address": "192.168.10.20"},
          {"address": "10.1.2.3"}
        ]
      }
    }
  ]
}
--------------------------------------------------

* When child elements are not included

:* XML format

-------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<macentries/>
-------------------------------------------------------

:* JSON format

---------------
{"macentry":[]}
---------------

*macentries* includes 0 or more link:#macentry[macentry] as child
elements.

[[other-data]]
== Other data

[[version]]
=== version

*version* shows version information of VTN Manager. It is used for
returning version information of VTN Manager to REST client.

:* XML format

--------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<version api="1">
  <bundle major="0" minor="1" micro="0" qualifier="SNAPSHOT"/>
</version>
--------------------------------------------------------------

:* JSON format

---------------------------
{
  "api": "1",
  "bundle": {
    "major": "0",
    "minor": "1",
    "micro": "0",
    "qualifier": "SNAPSHOT"
  }
}
---------------------------

Meaning of each attribute is as follows.

:;

api

::
  ;;
    Value showing the API version of VTN Manager will get configured.
    +
    API version will be a value equal to or greater than 1, and it is
    incremented if API of VTN Manager is changed.
    +
    * Current VTN Manager will return 1 as API version.

*bundle* element shows version information of OSGi bundle that
implements VTN Manager. Meaning of each *bundle* attribute is as
follows.

:;

major

::
  ;;
    major component of OSGi bundle version is configured.

[[rest-api]]
= REST API

This section describes the specifications of REST API provided by VTN
Manager.

Further, specify the name of the target container in the REST URI
*containerName* described in this document. For example, specify
*default* in *containerName* when operation is to be performed against
default container.

[[vtn-related-api]]
== VTN related API

This section describes
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
related REST API.

===

Get VTN information list

===

This retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
present in the specified container.

[[request]]
==== Request

----------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns
----------------------------------------------

:;containerName

::
  ;;
    Specify the Container name.

[[response]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vtns[vtns], which shows VTN information list, gets configured in
Response body.

It returns Status Code showing the error in case of an abnormal end.
Following are the main Status Codes that get returned in case of error.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Create VTN

===

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
inside the specified container.

[[request-1]]
==== Request

------------------------------------------------------------
POST /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}
------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

Specify link:#vtnconf[vtnconf] in Request body.

* VTN description is not registered if
link:#vtnconf.description[description] is omitted.
* If link:#vtnconf.idleTimeout[idleTimeout] is omitted, it will be
treated as if *300* is specified in the value.
* If link:#vtnconf.hardTimeout[hardTimeout] is omitted, it will be
treated as if *0* is specified in the value.

[[response-1]]
==== Response

It returns *201 (Created)* as Status Code in case of normal end.

* Response body is not configured.
* URI of the resource that is created (URI specified in request) gets
configured in *Location* header.

It returns Status Code showing error in case of abnormal end. Following
are the main Status Codes returned during error.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Get VTN information

===

It acquires the information related to the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].

[[request-2]]
==== Request

-----------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}
-----------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-2]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vtn[vtn] that shows VTN information gets configured in Response
body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Modify VTN information

===

It modifies the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN]
information.

[[request-3]]
==== Request

-----------------------------------------------------------
PUT /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}
-----------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

You must specify link:#vtnconf[vtnconf] in Request body.

Also, the following query parameter can be specified in URI.

:;all

::
  ;;
    Specify the Boolean value that decides the handling of attributes
    omitted in link:#vtnconf[vtnconf].
    +
    If nothing is specified, then it is treated as *false*.
    +
    * If *true* is specified, then all the attributes related to VTN are
    modified.
    ** If link:#vtnconf.description[description] is omitted, then the
    description of the specified VTN will get deleted.
    ** If link:#vtnconf.idleTimeout[idleTimeout] is omitted, it will be
    treated as if *300* is specified in the value.
    ** If link:#vtnconf.hardTimeout[hardTimeout] is omitted, it will be
    treated as if *0* is specified in the value.
    * If *false* is specified, then the attributes that are omitted will
    not be modified.

[[response-3]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Delete VTN

===

It deletes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VTN[VTN].
All the vBridge etc. that are included in the specified VTN also will
get deleted.

[[request-4]]
==== Request

--------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}
--------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-4]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[vbridge-related-api]]
== vBridge related API

This section describes REST APIs related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

===

Get vBridge information list

===

It retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
present inside the specified VTN.

[[request-5]]
==== Request

--------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges
--------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-5]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vbridges[vbridges] showing vBridge information list gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Create vBridge

===

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
inside the specified VTN.

[[request-6]]
==== Request

----------------------------------------------------------------------------------
POST /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}
----------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#vbridgeconf[vbridgeconf] must be specified in the Request body.

* If link:#vbridgeconf.description[description] is omitted, then vBridge
description is not registered.
* If link:#vbridgeconf.ageInterval[ageInterval] is omitted, it will be
treated as if *600* is specified in the value.

[[response-6]]
==== Response

It returns *201 (Created)* as Status Code in case of normal end.

* Response body is not configured.
* URI of the resource that is created (URI specified in request) gets
configured in *Location* header.

It returns Status Code showing error in case of abnormal end. Following
are the main Status Codes returned during error.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Get vBridge information

===

It retrieves the information related to the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-7]]
==== Request

---------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}
---------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-7]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vbridge[vbridge] showing vBridge information gets configured in
Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Modify vBridge information

===

It modifies the information of specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-8]]
==== Request

---------------------------------------------------------------------------------
PUT /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}
---------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#vbridgeconf[vbridgeconf] must be specified in Request body.

Also, the following query parameter can be specified in URI.

:;all

::
  ;;
    Specify the Boolean value that decides the handling of attributes
    omitted in link:#vbridgeconf[vbridgeconf].
    +
    If nothing is specified, then it is treated as *false*.
    +
    * If *true* is specified, then all the attributes related to vBridge
    are modified.
    ** If link:#vbridgeconf.description[description] is omitted, then
    the description of the specified vBridge will get deleted.
    ** If link:#vbridgeconf.ageInterval[ageInterval] is omitted, it will
    be treated as if *600* is specified in the value.
    * If *false* is specified, then the attributes that are omitted will
    not be modified.

[[response-8]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Delete vBridge

===

It deletes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].
All the interfaces etc. that are included inside the specified vBridge
also get deleted.

[[request-9]]
==== Request

------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}
------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-9]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[vbridge-interface-related-api]]
== vBridge interface related API

This section describes the REST API related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

===

Get vBridge interface information list

===

It retrieves the list of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] present inside the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-10]]
==== Request

--------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces
--------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-10]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#interfaces[interfaces] showing vBridge information list gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Create vBridge interface

===

It creates
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-11]]
==== Request

------------------------------------------------------------------------------------------------------
POST /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}
------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#interfaceconf[interfaceconf] must be specified in Request body.

* If link:#interfaceconf.description[description] is omitted, then the
description of the interface will not get registered.
* If link:#interfaceconf.enabled[enabled] is omitted, then it is treated
as if *true* is specified in the value.

[[response-11]]
==== Response

It returns *201 (Created)* as Status Code in case of normal end.

* Response body is not configured.
* URI of the resource that is created (URI specified in request) gets
configured in *Location* header.

It returns Status Code showing error in case of abnormal end. Following
are the main Status Codes returned during error.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Get vBridge interface information

===

It retrieves information related to a specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-12]]
==== Request

-----------------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}
-----------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-12]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#interface[Interface] showing vBridge interface information gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Modify vBridge interface information

===

It modifies the information of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-13]]
==== Request

-----------------------------------------------------------------------------------------------------
PUT /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}
-----------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#interfaceconf[interfaceconf] must be specified in the Request
body.

Also, the following query parameter can be specified in URI.

:;all

::
  ;;
    Specify the Boolean value that decides the handling of attributes
    omitted in link:#interfaceconf[interfaceconf].
    +
    If nothing is specified, then it is treated as *false*.
    +
    * If *true* is specified, then all the attributes related to vBridge
    interface are modified.
    ** If link:#interfaceconf.description[description] is omitted, then
    the description of the specified vBridge interface will get deleted.
    ** If link:#interfaceconf.enabled[enabled] is omitted, value is
    modified to *true*.
    * If *false* is specified, then the attributes that are omitted will
    not be modified.

[[response-13]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Delete vBridge interface

===

It deletes the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[virtual
interface] inside the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-14]]
==== Request

--------------------------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}
--------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-14]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[port-mapping-related-api]]
== Port mapping related API

This section describes the REST API related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping].

===

Configure Port mapping

===

It configures
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface]. If Port mapping is already configured on the specified
vBridge interface, then old configuration is deleted and the
configuration specified in request body gets applied.

[[request-15]]
==== Request

-------------------------------------------------------------------------------------------------------------
PUT /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}/portmap
-------------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#portmapconf[portmapconf] must be specified in the Request body.

* Information of the node corresponding to the switch, which is to be
mapped to interface, must be specified in link:#portmapconf.node[node].
* Conditions that specify the physical port of the switch, which is to
be mapped to interface, must be specified in
link:#portmapconf.port[port].
** Currently you can specify physical port of OpenFlow switches only.
* Specify VLAN ID, which is to be mapped to interface, in
link:#portmapconf.vlan[vlan].
** If value other than *0* is specified, then the ethernet frame that
has the specified VLAN ID configured will get mapped.
** If *0* is specified, or if link:#portmap.vlan[vlan] is omitted, then
untagged ethernet frame will get mapped to the interface.

[[response-15]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.
* Port map is successful even if the specified physical port of the
switch does not exist. Actual mapping will be done when that specified
physical port is found later.
** However, when mapping is actually done with the specified physical
port, the processing will not be carried out if that physical port and
VLAN ID are mapped to another vBridge interface.

It returns Status Code showing error in case of abnormal end. Following
are the main Status Codes returned during error.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Get Port mapping information

===

It retrieves the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] information configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

[[request-16]]
==== Request

-------------------------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}/portmap
-------------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-16]]
==== Response

It returns the following information in case of normal end.

* It returns *200 (OK)* as Status Code if Port mapping is configured on
the specified vBridge interface.
** link:#portmap[portmap] which shows Port mapping information is
configured in the Response body.
* It returns *204 (No Content)* as Status Code if port mapping is not
configured on the specified vBridge interface.
** Request body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Delete Port mapping

===

It deletes
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#port-map[Port
mapping] configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vInterface[vBridge
interface].

[[request-17]]
==== Request

----------------------------------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/interfaces/{ifName}/portmap
----------------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-17]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end. Further, it
will end normally even if Port mapping is not configured in the
specified vBridge interface.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[vlan-mapping-related-api]]
== VLAN mapping related API

This section describes the REST API related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping].

===

Get VLAN mapping information list

===

It retrieves
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information list configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-18]]
==== Request

------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/vlanmaps
------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-18]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vlanmaps[vlanmaps] showing VLAN mapping information list gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Configure VLAN mapping

===

It creates the mapping between the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge]
and
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN].

[[request-19]]
==== Request

-------------------------------------------------------------------------------------------
POST /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/vlanmaps
-------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

link:#vlanmapconf[vlanmapconf] must be specified in the Request body.

* Specify the VLAN ID, which is to be mapped to vBridge, in
link:#vlanmapconf.vlan[vlan].
** If value other than *0* is specified, then the ethernet frame that
has the specified VLAN ID configured will get mapped to vBridge.
** If *0* is specified, or if link:#vlanmapconf.vlan[vlan] is omitted,
then untagged ethernet frame will get mapped to the vBridge.
* Specify the `Node` information corresponding to switch, which is
mapped to vBridge, in link:#vlanmapconf.node[node].
** Currently you can specify `Node` corresponding to OpenFlow switches
only.
** If it is omitted, then it will be treated as if all the switches are
specified.

[[response-19]]
==== Response

It returns *201 (Created)* as Status Code in case of normal end.

* An identifier is allocated to the VLAN mapping information that was
created, and the REST resource URI corresponding to that VLAN mapping
information gets configured in *Location* header.
** Last path configuration element of URI configured in *Location*
header is the identifier allocated to VLAN mapping information.
* Response body is not configured.
* VLAN configuration will succeed even if the switch specified in
link:#vlanmapconf.node[node] is not found. Actual mapping is done when
the specified switch is found later.

It returns Status Code showing error in case of abnormal end. Following
are the main Status Codes returned during error.

:;400 (Bad Request)

::
  ;;
    Incorrect XML or JSON data is specified in Request body.

===

Get VLAN mapping information

===

It retrieves the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] information configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-20]]
==== Request

--------------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/vlanmaps/{mapId}
--------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-20]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#vlanmap[vlanmap] which shows the VLAN mapping information gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Search VLAN Mapping information based on config information

=== Out of the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] that are configured on the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge],
it retrieves the VLAN Mapping information that matches with the
specified config information.

[[request-21]]
==== Request

------------------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/vlanmapsearch/byconf
------------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

Specify config information of VLAN Mapping by using the query parameter
given below.

:;vlan

::
  ;;
    Specify in decimal the VLAN ID mapped by VLAN Mapping.
    +
    * If omitted, it will be treated as if 0 is specified as VLAN ID.

[[response-21]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

::* link:#vlanmap[vlanmap] which shows the VLAN mapping information gets
configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;400 (Bad Request)

::
  ;;
    Value specified in Query parameter has an invalid format.

===

Delete VLAN mapping

===

It deletes
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#VLAN-map[VLAN
mapping] configured in the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-22]]
==== Request

-----------------------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/vlanmaps/{mapId}
-----------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-22]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[mac-address-table-related-api]]
== MAC address table related API

This section describes the REST API related to
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

===

Get MAC address information list

===

It retrieves the MAC address information list learned inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-23]]
==== Request

-------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/mac
-------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-23]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#macentries[macentries] that shows the MAC address information
list gets configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Flush MAC address table

===

It deletes the entire MAC address information learned inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-24]]
==== Request

----------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/mac
----------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-24]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Get MAC address information

===

It retrieves the specific MAC address information learned inside the
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-25]]
==== Request

-----------------------------------------------------------------------------------------------
GET /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/mac/{macAddr}
-----------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-25]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#macentry[macentry] showing the showing the information of the
MAC address specified in *macAddr* gets configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

===

Delete MAC address information

===

It deletes a specific MAC address information learned inside
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge.macTable[MAC
address table] of the specified
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification#vBridge[vBridge].

[[request-26]]
==== Request

---------------------------------------------------------------------------------------------------
DELETE /controller/nb/v2/vtn/{containerName}/vtns/{tenantName}/vbridges/{bridgeName}/mac/{macAddr} 
---------------------------------------------------------------------------------------------------

:;containerName

::
  ;;
    Specify Container name.

[[response-26]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* Response body is not configured.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

[[container-independent-api]]
== Container independent API

This section describes the container independent REST API provided by
VTN Manager.

[[retrieval-of-version-information]]
=== Retrieval of version information

It retrieves the version information of VTN Manager.

[[request-27]]
==== Request

---------------------------------
GET /controller/nb/v2/vtn/version
---------------------------------

[[response-27]]
==== Response

It returns *200 (OK)* as Status Code in case of normal end.

* link:#version[version] showing the version information of VTN Manager
gets configured in Response body.

It returns Status Code showing error in case of abnormal end. Main
Status Codes returned during error is as follows.

:;401 (Unauthorized)

::
  ;;
    Authorization error.

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
