Back to Defense4All:User_Guide[Defense4All User Guide Page]

[[overview-and-supported-platforms]]
= Overview and Supported Platforms

These instructions describe how to download, install, configure, and run
Defense4All. Defense4All is downloaded and installed separately from the
ODC machine. It runs on a separate machine and communicates with the ODC
via REST API calls. The currently supported platforms are:

* RHEL 6.1/CentOS 6.1 (64-Bit)
* RHEL 6.4/CentOS 6.4 (64-Bit)
* Debian 7.x (Stable version, 64-Bit)
* Ubuntu 12.04 or later (64-Bit)

[[download]]
= Download

Download the Defense4All and Defense4All-CLI package files from
https://jenkins.opendaylight.org/defense4all/job/defense4all-merge

Note: Visit the URL and choose the latest zip file to download.

[[installation-on-rhelcentos]]
= Installation on RHEL/CentOS

*Install JDK*:

* For version 6.1 - download Oracle JDK 7 from the following link and
install it:
http://www.oracle.com/technetwork/java/javase/downloads/index.html
* For version 6.4 - Install OpenJDK 7 using the following command:

::
  ;;
    $ yum install java-1.7.0-openjdk-devel

*Install Cassandra rpm packages*:

* Refer to http://www.datastax.com/docs/1.0/install/install rpm:

::
  ;;
    $ sudo gedit /etc/yum.repos.d/datastax.repo . Add the following
    lines:
    +
    ::
      [datastax]
      +
      name= DataStax Repo for Apache Cassandra
      +
      baseurl=http://rpm.datastax.com/community
      +
      enabled=1
      +
      gpgcheck=0
    +
    $ sudo yum install cassandra20.noarch

* Start and validate the Cassandra service:

::
  ;;
    $ sudo service cassandra start
    +
    $ sudo service cassandra status
    +
    cassandra is running...

*Install Defense4All:*

* Install Defense4all packages: (from packages download directory)

::
  ;;
    $ sudo rpm -i defense4all-1.0.14-1.noarch.rpm
    +
    $ sudo rpm -i defense4all-cli-1.0.14-1.noarch.rpm

* Start and validate Defense4All service as follows :

::
  ;;
    $ sudo service defense4all restart
    +
    $ sudo service defense4all status
    +
    defense4all is running

[[installation-on-debian-or-ubuntu]]
= Installation on Debian or Ubuntu

*Install JDK:*

* Install OpenJDK 7

::
  ;;
    $ sudo apt-get install openjdk-7-jre
    +
    $ sudo update-alternatives --config java

* Choose java-7-openjdk from the list

*Install Cassandra rpm packages*:

* Refer to
http://www.datastax.com/documentation/cassandra/2.0/pdf/cassandra20.pdf

::
  ;;
    $ echo "deb http://debian.datastax.com/community stable main" | sudo
    tee – a /etc/apt/sources.list.d/cassandra.sources.list
    +
    $ sudo apt-get install curl
    +
    $ curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key
    add –
    +
    $ sudo apt-get update
    +
    $ sudo apt-get install dsc20

* Start and validate the Cassandra service:

::
  ;;
    $ sudo service cassandra start
    +
    $ sudo service cassandra status
    +
    cassandra is running...

*Install Defense4All*:

* Install Defense4all packages: (from the packages download directory)

::
  ;;
    $ sudo dpkg -i defense4all_1.0.14.deb
    +
    $ sudo dpkg -i defense4all-cli_1.0.14.deb

* Start and validate the Defense4All service as follows :

::
  ;;
    $ sudo service defense4all restart
    +
    $ sudo service defense4all status
    +
    defense4all is running

Back to Defense4All:User_Guide[Defense4All User Guide Page]
