[[major-features]]
=== Major Features

Defense4All is an SDN application for detecting and mitigating DDoS
attacks. It communicates with OpenDaylight Controller via the ODC
north-bound REST API to:

1.  Monitor behavior of protected traffic - the application sets flow
entries in selected network locations to read traffic statistics for
each of the PNs (aggregating statistics collected for a given PN from
multiple locations).
2.  Divert attacked traffic to selected AMSs – the application set flow
entries in selected network locations to divert traffic to selected
AMSs. When an attack is over the application removes these flow entries,
thus returning to normal operation and traffic monitoring.

Defense4All can optionally dynamically configure defined AMSs, monitor
them or collect and act upon attack statistics from them. It contains a
reference implementation pluggable driver to communicate with Radware’s
DefensePro AMS. Defense4All presents its north-bound REST and CLI APIs
to:

1.  Control and configure the application (runtime parameters, ODC
connectivity, AMSs in domain, PNs, etc.).
2.  Obtain reporting data – operational or security, current or
historical, unified from Defense4All and other sources (like ODC, AMSs).

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

* *Operating Systems*:
** RHEL 6.1/CentOS 6.1 (64-Bit)
** RHEL 6.4/CentOS 6.4 (64-Bit)
** Debian 7.x (Stable version, 64-Bit)
** Ubuntu 12.04 or later (64-Bit)
* *Java*: A Java 7-compliant runtime environment.
* *Cassandra*: Cassandra 2.0

[[for-development]]
==== For Development

* *Linux OS* - Any of the OSs for execution.
* *Java* - A Java 7-compliant JDK.
* *Maven* - Maven 2 or 3
* *Git* - Connectivity to ODL Git
* *Editing/debugging/running* - Any choice, for instance Eclipse for
Linux.
* *Cassandra* - Cassandra 2.0 in the same machine as Defense4All.
* *Minimal environment to run and test DDoS attacks* - Normal traffic
generator, attack traffic generator, server, OVS switch, ODC. AMS is not
mandatory, but advisable. Currently Defense4All has plugin to Radware's
DefensePro.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

* *Order in configuring elements in Defense4All* – The order described
in Defense4All configuration (Hostaddress, OFC, AMSs, NetNodes, PNs)
must be preserved.
* *Only one ODC instance* – Only one ODC instance (can be a cluster with
single system image) can be set in Defense4All.
* *No removal of ODC* – ODC removal is not supported. To remove an ODC a
(factory) reset should be performed.
* *No clustering* – No Defense4All clustering is supported, and a single
Cassandra instance is configured by Defense4All
* *Only one AMS per NetNode* – Defense4All can redirect traffic to only
of the AMSs connected to each NetNode (identified by port-pair
connectivity). Defense4All chooses the AMS target arbitrarily.
* *AMS must be “logically” connected to the traffic NetNode* –
Defense4All redirects traffic in a NetNode (switch) per AMS connectivity
(identified by port-pair connectivity). It does not address L2 or L3
routing to deliver packets to the switch connected to the target AMS.
Note that redirection can still work to distant AMSs, as long as network
routing takes care to send packets exiting a given NetNode port – to the
right AMS.
* *Only factory reset* – “Soft”, “dynamic” and other more granular
resets are not supported yet.
* *PN traffic specification of only subnet networks* – PN traffic
selection specification only supports network subnet of arbitrary size
and end servers (/X where 0<X<=32). Protocols and ports are not
supported. Neither network links (all traffic through a specified
network link – switch port – should be protected). In addition, only
combined traffic of all the subnet is monitored (i.e., the user cannot
specify to monitor separately each of the servers in a given subnet).
Finally, address ranges or discrete address sets is also unsupported.
* '''No support for detecting outbound attacks '''– Only inbound traffic
attacks are detected.
* *HealthTracker does not reset Defense4All* – Permanent health issues
are not yet used, and HealthTracker does not trigger reset in response
to permanent health issues beyond a predefined threshold.
* *No support for counting and redirection traffic off SDN native
switches that perform switching function* – Defense4All does not learn
or interfere with packet routing, except to/from “logically” locally
connected AMS (see AMS connectivity restriction). As such, it can only
cope with native SDN switches topologically connected as “bump in the
wire”.
* *No synchronized coexistence with other SDN apps* – Other SDN Apps can
conflict with Defense4All in flow entries priorities and actions in the
same switch. The only two options to presently co-exist with other SDN
Apps is: 1) disjoint traffic specifications (the other SDN App does not
work on the traffic of PNs configured to Defense4All), or 2) The other
SDN App places its flow entries switches that are not introduced as
NetNodes to Defense4All.
* *No health checking is performed against external entities (ODC,
NetNodes, AMSs)* – This means, that in case of their failure no
automated recovery (such as redirecting traffic to a different AMS
connectivity port-pair) is performed by Defense4All.
* *No static threshold is currently supported to detect attacks* – Only
dynamically learned normal baselines with configured deviations
percentages trigger attack detection.
* *No guaranteed deletion from repositories of removed elements (PNs,
NetNodes, AMSs)* – They may be left in the repositories (with status
removed). Background cleanup and consistency check processes are not
there yet.
* *No PN protection SLA* – Currently all PNs are treated equally - no
prioritization in resources, or attack detection eagerness and accuracy.
* *No mitigation confirmation* – Mitigations of attacks against any PN
are always assumed to be auto-confirmed by user.
* *No overlaps of destination addresses specified in different PNs* – If
PN1 has a destination subnet specification that is not disjoint with PN2
destination subnet specification then the capability to detect and
mitigate attacks on eith PN1 or PN2 may be compromised and the results
will be unpredictable.
* *No Defense4All API security (authentication and authorization)* –
Defense4All REST API presently does not check for credentials. Nor does
it restrict REST APIs according to user roles.
* *Stats collection period is unchangeable* – Static, for all PNs,
retrieved and computed in bursts.
* *No support for OpenFlow 1.3* – Currently Defense4All operates and
utilizes the features of OpenFlow 1.0 only.

For other information please refer to Defense4All:Tutorial[Tutorial].

[[release-review]]
=== Release review

*
Defense4All:Release_Notes:Hydrogen Release Review[Defense4All:Release_Notes:Hydrogen
Release Review]

