Back to Defense4All:User_Guide[Defense4All User Guide Page]

Defense4All Web GUI is based on the REST API.

[[configuring-the-framework-environment]]
= Configuring the FrameWork Environment

This section describes how to configure the Defense4All Framework
environment.

To set Defense4All configuration parameters +
1. If you are not already in the Defense4All user interface, from an
Internet browser, go to *http://:8086/controlapps*, where is the address
for the host that is running Defense4All. +
2. If you are not already in the FrameWork Setup pane, select *Framework
> Setup*. +
3. Set the *Framework Control Network Address* to the IP address
Defense4All uses to access the control network. +
4. To the right of the *SDN Controllers* label, click *Add*. +
5. In the Add SDN Controller pane, set the following parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Hostname ||
Name of the SDN Controller. This is the SDN Controller that supports
OpenFlow network programming (OFC stands for OpenFlow Controller).
OpenDaylight Controller provides this flavor both for OpenFlow enabled
network devices and other network devices with adequate plug-ins in the
PFC. |- | IP address || IP address of the SDN Controller. |- | Port ||
Port number of the SDN Controller. |- | Statistics Polling Interval ||
The frequency that the SDN Controller polls for statistics. |- |
Username || Username to log into the SDN Controller. |- | Password ||
Password to log into the SDN Controller. |- | Confirm Password ||
Confirmation of the password of the SDN Controller. |} 6. Click
*Submit*. +
*Note*: The SDN controller cannot be changed or removed. Only one (1)
SDN controller can be configured. To change the SDN controller, you must
reset Defense4All to factory settings. +
7. In the FrameWork Setup pane, to the right of the *Attack Mitigation
Systems (AMSs)* label, click *Add*. +
8. In the Add Attack Mitigation System (AMS) pane, set the following
parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Name || AMS
descriptive name. |- | Brand || Select the AMS brand from the drop-down
list. +
 Values: Radware DefensePro, Other +
 Default: Radware +
 *Note*: The Radware DefensePro device can be removed only when there
are no active mitigations (traffic redirections to it). |- | Version ||
AMS version. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
IP Address || AMS IP address. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
Port || AMS port number. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
Username || AMS username. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
Password || Password to log into the AMS. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
Confirm Password || Confirmation of the password of the AMS. +
 *Note*: This parameter is only applicable to Radware DefensePro. |- |
Health Check Interval || Time in seconds. +
 *Note*: This parameter is only applicable to Radware DefensePro. +
 Default: 60 seconds |} *Note*: Only relevant for DefensePro. *Layer 2
Broadcast Destination MAC Address*, *Multicast Destination MAC Address*,
*Unrecognized L2 Format*, and *TTL Less Than or Equal to 1* blocking
must be configured to avoid Layer 2 loops. For more information, refer
to the discussion on Packet Anomaly protection in the DefensePro User
Guide. +
9. Click *Submit*. +
10. In the FrameWork Setup pane, to the right of the *Net Nodes* label,
click *Add*. +
11. In the Add Net Node pane, set the following parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Name || NetNode
descriptive name. |- | ID || NetNode ID. |- | Type (read-only) ||
Default: Openflow |- | SDN Node Mode (read-only) || Default:
sdnenablednative. |- | Health Check Interval (read- only) || Default: 60
seconds |} 12. To the right of the *Protected Links* label, click
*Add*. +
13. In the Add Proetcted Link pane, set the following parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Incoming
Traffic Port || The incoming traffic port number. |- | Outgoing Traffic
Port || The outgoing traffic port number. |} 14. Click *OK*. +
15. To the right of the *AMS Connections* label, click *Add*. +
16. In the Add AMS Connection pane, set the following parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Name || AMS
connection descriptive name. |- | AMS Name || AMS connection name. |- |
NetNode North Port || NetNode NothPort. |- | NetNode South Port ||
NetNode South Port. |- | AMS North Port || AMS North Port. |- | AMS
South Port || AMS South Port. |} 17. Click *OK*. +
18. In the Add Net Node pane, click *Submit*. +

[[framework-maintenance]]
= FrameWork Maintenance

This section describes how to run maintenance operations on Defense4All

* *Reset to Factory Settings* — If you want to reset Defense4All to its
factory settings, at the bottom of the FrameWork Setup pane, click Reset
to Factory Settings.
* *Restart Framework* — To manually restart Defense4All, at the bottom
of the FrameWork Setup

pane, click Restart FrameWork.

[[framework-reports]]
= FrameWork Reports

You can generate reports containing syslog messages that have been saved
over a period of time. +
*To generate FrameWork reports:* +
1. If you are not already in the Defense4All user interface, from an
Internet browser enter the IP address for the host that is running
Defense4All. +
2. If you are not already in the FrameWork Reports pane, select
*Framework > Report*. +
3. In the FrameWork Report pane, select one of the tabs: +
a. Query by Time Period +
* In the *From* and *To* fields, select the appropriate dates to define
the range of the query.

* Select the *Event Types* you want included in the report.
* Click *Run Query*. The results display at the bottom of the pane.
* If you want save the query to a file, enter a file path in the
*Filename* filed, and click *Export Query to File*.

\b. Query by Last Number of Rows +
* In the *Number of Rows* field, enter the last number of rows in the
database you want displayed in your report.

* Select the *Event Types* you want included in the report.
* Click *Run Query*. The results display at the bottom of the pane. You
cannot save this query to a file

\c. Cleanup +
* In the *Delete events older than* field, enter a number of days.
Events older than this number of days are deleted.

* Click *Submit*. The results display at the bottom of the pane. You
cannot save this query to a file.

[[configuring-defense4all-protected-objects-pos]]
= Configuring Defense4All Protected Objects (POs)

This section describes how to configure Defense4All protected objects
(POs).

*To set up Defense4All protected objects (POs)* +
1. If you are not already in the Defense4All user interface, from an
Internet browser, enter the IP address for the host that is running
Defense4All. +
2. If you are not already in the Defense4All Setup pane, select
*Defense4All > Setup*. +
3. To the right of the *Protected Objects (POs)* label, click *Add*. +
4. In the Add Protected Object (PO) pane, set the following
parameters: +
\{| class="wikitable" |- ! Parameter !! Description |- | Name || Name of
the PO. +
 Valid characters: A–Z, a–z, 0-9, _ +
 *Note*: A PO cannot be removed when under attack. |- | IP Address || IP
address and net mask of the PO. |} 5. Click *Submit*. +

[[defense4all-reports]]
= Defense4All Reports

You can generate reports containing syslog messages that have been saved
over a period of time.

*To generate Defense4All reports* +
1. If you are not already in the Defense4All user interface, from an
Internet browser enter the IP address for the host that is running
Defense4All. +
2. If you are not already in the Defense4All Reports pane, select
*Defense4All > Report*. +
3. In the Defense4All Reports pane, select one of the tabs: +
— Query by Time Period

* In the *From* and *To* fields, select the appropriate dates to define
the range of the query.
* Select the *Event Type*s you want included in the report.
* Click *Run Query*. The results display at the bottom of the pane.
* If you want save the query to a file, enter a file path in the
*Filename* filed, and click *Export Query to File*.

— Query by Last Number of Rows

* In the *Number of Rows* field, enter the last number of rows in the
database you want displayed in your report.
* Select the *Event Types* you want included in the report.
* Click *Run Query*. The results display at the bottom of the pane. You
cannot save this query to a file

— Cleanup

* In the *Delete events older than* field, enter a number of days.
Events older than this number of days are deleted.
* Click *Submit*. The results display at the bottom of the pane. You
cannot save this query to a file.

Back to Defense4All:User_Guide[Defense4All User Guide Page]
