[[overview]]
= Overview

This guide explains how to get, build, and run VTN Manager for
developers who want to hack the source code of VTN Manager. The page
assumes that you want to hack the latest code of VTN project. If you are
interested in hacking source code in stable branch rather than the
latest one, please see
Release/Helium/VTN/Developer_Guide:Hacking:VTN_Manager[ the Hacking
guide for Helium].

The all procedures below assume that you are getting the latest source
code of VTN Project on your local Linux machine.

[[getting-vtn-source]]
= Getting VTN Source

Download the code from the Git repository of VTN Project.

::
-------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/vtn.git
-------------------------------------------------------------
  +
  ;;
    or
  +
-------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/vtn.git
-------------------------------------------------------

[[building-vtn-manager]]
= Building VTN Manager

[[prior-preparation]]
== Prior preparation

VTN Manager is a set of OSGi bundles running in OpenDaylight controller
in Karaf platform, so prior preparation for building VTN Manager is the
same as OpenDaylight controller.

Please see
OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_the_CLI#Prerequisites[Prerequisites
section of controllers's guide].

[[building]]
== Building

The following instructions assume you put the code in directory
$\{VTN_DIR}.

-----------------------------
cd ${VTN_DIR}/manager
mvn clean install –DskipTests
-----------------------------

::
  *Note*:
  +
  * You will need direct internet connection for this build to be
  successful.
  * The *skipTests* property makes it to skip running the tests to save
  your time.
  * It is recommended to run all tests and strict coding style checks
  before you push a patch to Gerrit.
  +
--------------------------------------------------
mvn clean install -Pintegrationtests -Pstrictcheck
--------------------------------------------------

[[running-vtn-manager]]
= Running VTN Manager

The following instruction explains how to run VTN Manager on Karaf.

------------------------------------------------
cd ${VTN_DIR}/manager/dist/karaf/target/assembly
./bin/karaf
------------------------------------------------

[[verify-if-vtn-is-running]]
== Verify if VTN is running

* In the karaf prompt, type the below command to ensure that vtn
packages are installed.

`feature:list –i | grep vtn `

[[rest-api]]
== REST API

VTN Manager provides REST API for virtual network functions.

Please check
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:RestApi[the VTN
Manager's REST API specification page] for detailed information.

Here is an example of how to create a virtual tenant network.

`curl --user "admin":"admin" -H "Accept: application/json" -H \` +
`"Content-type: application/json" -X POST \` +
http://localhost:8080/controller/nb/v2/vtn/default/vtns/Tenant1[`http://localhost:8080/controller/nb/v2/vtn/default/vtns/Tenant1`]` \` +
`-d '{"description": "My First Virtual Tenant Network"}'`

You can check the list of all tenants by executing the following
command.

`curl --user "admin":"admin" -H "Accept: application/json" -H \` +
`"Content-type: application/json" -X GET \` +
http://localhost:8080/controller/nb/v2/vtn/default/vtns[`http://localhost:8080/controller/nb/v2/vtn/default/vtns`]

To know the usage of VTN Manager in Opendaylight Controller, Please
click the below link:

* Media:NEC_VTN_Demo_0722.pdf[ How to use VTN Manager in Opendaylight
Controller]

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
