[[major-features]]
=== Major Features

Helium release of TCP-MD5 project delivers the support for providing
access to TCP MD5 Signature Option on operating systems which support it
in their TCP stack.

* https://tools.ietf.org/html/rfc2385[RFC2385] - TCP MD5 Signature
Option

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

A Java 7-compliant runtime environment is sufficient to run the protocol
libraries. TCP-MD5 functionality requires 64 bit Linux, other platforms
are currently not supported.

[[for-development]]
==== For Development

In order to participate on development, you will need some standard Java
development environment which supports Maven projects hosted in Git.
Core developers use Eclipse on Linux, but also plain console with
vim/mvn/git, so pretty anything you are comfortable should work
reasonably well. This project contains a JNI component (tcpmd5-jni),
which requires Linux-compatible build environment to compile. Working on
other parts of the project does not require it, as it can be satisfied
from the Nexus repository.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

Currently no issues are known. The project is limited to x86-64 Linux
delivery due to design (it is a backdoor to OS functionality) and build
infrastructure, which runs on Linux (and not *BSD, for example).

[[helium-stable-update-1]]
=== Helium Stable Update 1

For Helium Stable Update 1, the following bugs are fixed:

* https://bugs.opendaylight.org/show_bug.cgi?id=2082[BUG-2082] -
feature.xml is missing dependencies on tcp-md5

