[[introduction]]
== Introduction

The project is available from the tcpmd5 repository. It is split into
the following artifacts:

[[tcpmd5-api]]
=== tcpmd5-api

Defines the basic API and a dummy implementation.

[[tcpmd5-jni]]
=== tcpmd5-jni

Contains the JNI implementation and its Java binding. The core of the
artifact is NativeKeyAccess.java, which is the Java frontend and binding
class. It defines the two native methods, setChannelKey0() and
isClassSupported0(). These are implemented in tcpmd5_jni.c. Individual
instances are then provided by NativeKeyAccessFactory, which runs basic
sanity tests before allowing itself being instantiated.

[[tcpmd5-nio]]
=== tcpmd5-nio

Contains the code to bridge the JNI component with java.nio package,
specifically ServerSocketChannel, SocketChannel and SocketOption
classes.

[[tcpmd5-netty]]
=== tcpmd5-netty

Contains the code to bridge the JNI component with netty.io, by
providing the appropriate SocketChannelFactory.

[[tcpmd5-controller-config]]
=== tcpmd5-controller-config

Default (disabled) configuration for activation.

[[tcpmd5-feature]]
=== tcpmd5-feature

Karaf feature artifact, pulling in all the other artifacts.
