https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review[back
to parent]

[[what-is-it]]
== WHAT IS IT

Restconf is protocol described in RFC
http://tools.ietf.org/html/draft-bierman-netconf-restconf-02[RESTCONF
Protocol]. According to this document the protocol "_provides a
programmatic interface over HTTP for accessing data defined in YANG,
using the datastores defined in NETCONF_".

RFC describes several operation which is possible to execute via HTTP
protocol and thus realize CRUD (create, retrive, update, delete)
operation above datastore or just obtain some specific information.

[[additional-components]]
=== ADDITIONAL COMPONENTS

[[interfaces-to-restconf]]
=== INTERFACES TO RESTCONF

Restconf is accessible via HTTP operation POST, PUT, UPDATE, DELETE,
OPTIONS. It is possible to execute GET operation directly from web
browser. For additional operations it is necessary to install REST
client to web browser or use application which is able to execute HTTP
operation (e. g. http://curl.haxx.se/[CURL])

[[assumed-knowledge]]
=== ASSUMED KNOWLEDGE

Users of the config subsystem should consider consulting following
resources:

[[for-developers]]
==== FOR DEVELOPERS

If some changes or new code should be added it is time saving advantage
to have following knowledges:

* REST
* JAX-RS - according to javadoc "_Java API for RESTful Web Services
provides portable APIs for developing, exposing and accessing Web
applications designed and implemented in compliance with principles of
REST architectural style_"
* Jersey - according to official site "_framework for developing RESTful
Web Services in Java that provides support for JAX-RS APIs_"
* + the same as operators

[[for-operators]]
==== FOR OPERATORS

//TODO Are any specific knowledges required for operator?

* + the same as endusers

[[for-endusers]]
==== FOR ENDUSERS

* XML/JSON - input and output data are currently specified in these two
formats.
* YANG - input data has to have specified correct namespace (XML) or
module name (JSON). This information is specified in YANG files.

[[assumed-environment]]
=== ASSUMED ENVIRONMENT

(if applicable)

[[why-do-we-have-it]]
=== WHY DO WE HAVE IT?

It makes it possible to:

* manipulate with datastores,
* call RPCs

[[painpoints]]
=== PAINPOINTS

what exactly should be here

[[how-does-it-work]]
=== HOW DOES IT WORK?

[[configuration-process]]
==== CONFIGURATION PROCESS

[[component-map]]
==== COMPONENT MAP

// TODO what should be here?

[[how-does-it-fit-into-the-controller-architecture]]
==== HOW DOES IT FIT INTO THE CONTROLLER ARCHITECTURE?

[[who-should-use-it]]
=== WHO SHOULD USE IT?

End-user

[[which-projects-dodont-use-it]]
==== WHICH PROJECTS DO/DON'T USE IT?

//TODO

[[education]]
== EDUCATION

[[learning-resources]]
=== LEARNING RESOURCES

*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Restconf[How
to use restconf]
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Restconf:Real_world_example[Real
world example]

*Resources for developers:* +
*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Restconf:Overview_for_programmers[Overview
for programmers]

* http://en.wikipedia.org/wiki/Representational_state_transfer[REST] -
wiki about REST
* https://jax-rs-spec.java.net/[JAX-RS] - javadoc,
* https://jersey.java.net/[Jersey] - concrete implementation of JAX-RS
which is used in controller,
* http://tools.ietf.org/html/draft-bierman-netconf-restconf-02[RESTCONF
Protocol] - restconf protocol (draft 2)
* http://tools.ietf.org/html/draft-lhotka-netmod-yang-json-02[Modeling
JSON text with YANG]
* http://tools.ietf.org/html/rfc6020[YANG - A Data Modeling Language for
NETCONF]

[[alternatives-investigated-or-possible]]
=== ALTERNATIVES (INVESTIGATED OR POSSIBLE)

[[examplestutorials]]
== EXAMPLES/TUTORIALS

*
https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Restconf:Change_event_notification_subscription[Change-event
notification subscription step-by-step manual]

[[meetingsaction-itemsprogress]]
== Meetings/Action Items/Progress
