[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
*
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi#VTNCoordinator_RestApi_Contents[VTN
Coordinator RestApi Contents] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Functions[vBridge
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Interface Flow Filter Functions[vBridge
Interface Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Interface Port Map Functions[vBridge
Interface Port Map functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Network Example Using VTN Virtualization[L2
Network Example Using VTN Virtualization]

|=======================================================================

[[about]]
= About

This Page will list the REST API to add/update/delete vBridge Interface
functions to
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator[VTN
Coordinator]

[[list-of-functions-supported]]
= List of Functions Supported

[[create-vbridge-interface]]
== Create vBridge Interface

This operation is used to create a vBridge Interface.

[[request]]
=== Request

[cols=",",]
|=====================================================
|Method |POST
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces.json`

|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`   "interface": {` +
`     "if_name": "{if_name}",` +
`     "description":` +
`     "{description}",` +
`     "adminstatus":` +
`     "{adminstatus}"` +
`   }` +
` }`
|=====================================================

Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). ||Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).
||Yes
|=======================================================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning). ||Yes

|description |Additional information. Valid value: A string of up to 127
characters. ||No

|adminstatus |Admin status. Valid value: enable, disable ||No
|=======================================================================

[[response]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
POST -H 'ipaddr:127.0.0.1' -d '\{"interface": \{"if_name":
"ifone","description": "ifone_desc"}}'
http://127.0.0.1:8083/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/interfaces.json
|=======================================================================

[[delete-vbridge-interface]]
== Delete vBridge Interface

This operation is used to delete a vBridge Interface

[[request-1]]
=== Request

[cols=",",]
|===============================================================
|Method |DELETE
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.json`

|===============================================================

Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). ||Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).
||Yes

|if_name |vBridge Interface name Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning). ||Yes
|=======================================================================

Request Body::
  None

Remember: vBridge Interface that is set in if1_name or if2_name of vLink
cannot be deleted.

[[response-1]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
DELETE -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8083/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/interfaces/ifone.json
|=======================================================================

[[update-vbridge-interface]]
== Update vBridge Interface

This operation is used to update a vBridge Interface.

[[request-2]]
=== Request

[cols=",",]
|===============================================================
|Method |PUT
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.json`

|Request Body(XML format) a|
|

`  `

|Request Body(JSON format) a|
|

`{` +
`  "interface": {` +
`        "description":` +
`  "{description}",` +
`  "adminstatus":` +
`  "{adminstatus}"` +
`  }` +
`}`

|===============================================================

Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). ||Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).
||Yes

|if_name |vBridge Interface name Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning). ||Yes
|=======================================================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|description |Additional information. Valid value: A string of up to 127
characters. ||No

|adminstatus |Admin status. Valid value: enable, disable. ||No
|=======================================================================

[[response-2]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
PUT -H 'ipaddr:127.0.0.1' -d '\{"interface": \{"description": "new
ifone_desc"}}'
http://127.0.0.1:8083/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/interfaces/ifone.json
|=======================================================================

[[list-vbridge-interfaces]]
== List vBridge Interfaces

This operation is used to list vBridge Interface information based on
specified conditions.

[[request-3]]
=== Request

[cols=",",]
|================================================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces.xml` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/detail.xml` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/count.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces.json` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/detail.json` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/count.json`

|Query String |?index=\{if_name}&max_repetition=\{max_repetition}
|================================================================

Request Body::
  None
Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). ||Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).
||Yes
|=======================================================================

Description of query string elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning). ||No

|max_repetition |Number of the resources that are returned. Valid value:
A positive integer Valid range: 1 to MAX of UINT32. Default is 10000.
||No
|=======================================================================

[[response-3]]
=== Response

[cols=",",]
|===========================================
|Response Body(XML format) a|
| If count or detail is not specified in URI

` ` +
`  ` +
` ` +
`     ` +
` ` +
`     ` +
` `

If count is specified in URI

|Response Body(JSON format) a|
| If count or detail is not specified in URI

` {` +
`   "interfaces": [` +
`        {` +
`       "if_name": "{if_name}"` +
`        }` +
`     ]` +
` }`

If detail is specified in URI

`   {` +
`   "interfaces": [` +
`         {` +
`         "if_name":` +
`     "{if_name}",` +
`         "description":` +
`     "{description}",` +
`         "adminstatus":` +
`     "{adminstatus}",` +
`         "operstatus":` +
`     "{operstatus}",` +
`         "neighbor": {` +
`             "vnode_name":` +
`        "{vnode_name}",` +
`                "if_name":` +
`        "{if_name}",` +
`                "vlk_name":` +
`        "{vlk_name}"` +
`          }` +
`       }` +
`     ]` +
`   }`

If count is specified in URI

` {` +
`  "interfaces":{` +
`     "count": "{count}"` +
`       }` +
`  }`

|===========================================

Description of response elements(interface)::

[cols=",",]
|=======================================================================
|Element |Description

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|adminstatus |Admin status. Valid value: enable, disable.

|operstatus |Operational status. Valid value: up, down, unknown

|neighbor |Information about the neighbor.

|count |The number of vBridge Interface. Valid value: A positive
integer.
|=======================================================================

Description of response elements(neighbor)::

[cols=",",]
|=======================================================================
|Element |Description

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|vnode_name |Virtual node name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|vlk_name |vLink name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning).
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
GET -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8083/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/interfaces.json
|=======================================================================

[[show-vbridge-interface]]
== Show vBridge Interface

[[request-4]]
=== Request

[cols=",",]
|===============================================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/interfaces/{if_name}.json`

|===============================================================

Request Body::
  None

Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). ||Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).
||Yes

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning). ||Yes
|=======================================================================

[[response-4]]
=== Response

[cols=",",]
|====================================
|Response Body(XML format) a|
` ` +
` ` +
` `

|Response Body (JSON format) |` { ` +
`    "interfaces": {` +
`         "if_name": "{if_name}",` +
`         "description":` +
`      "{description}",` +
`         "adminstatus":` +
`      "{adminstatus}",` +
`         "operstatus":` +
`      "{operstatus}",` +
`         "neighbor": {` +
`                 "vnode_name":` +
`            "{vnode_name}",` +
`                 "if_name":` +
`            "{if_name}",` +
`                 "vlk_name":` +
`            "{vlk_name}" ` +
`                }` +
`          }` +
`   }`
|====================================

Description of response elements(interface)::

[cols=",",]
|=======================================================================
|Element |Description

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|adminstatus |Admin status. Valid value: enable, disable.

|operstatus |Operational status. Valid value: up, down, unknown

|neighbor |Information about the neighbor.
|=======================================================================

Description of response elements(neighbor)::

[cols=",",]
|=======================================================================
|Element |Description

|if_name |vBridge Interface name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|vnode_name |Virtual node name. Valid value: Up to 31 characters that
can include alphabets, numbers, and underscore (except at the
beginning).

|vlk_name |vLink name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning).
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
GET -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8083/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/interfaces/ifone.json
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
