[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
*
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi#VTNCoordinator_RestApi_Contents[VTN
Coordinator RestApi Contents] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Interface Functions[vBridge
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Flow Filter Functions[vBridge
Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Host Address Functions[Host
Address functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Domain Function[L2
Domain function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:MAC Entry Function[MAC
Entry function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Network Example Using VTN Virtualization[L2
Network Example Using VTN Virtualization]

|=======================================================================

[[about]]
= About

This Page will list the REST API to add/update/delete vBridge(s) to
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator[VTN
Coordinator]

[[list-of-functions-supported]]
= List of Functions Supported

[[create-vbridge]]
== Create vBridge

This operation is used to create a vBridge.

[[request]]
=== Request

[cols=",",]
|========================================
|Method |POST
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges.xml`

* JSON format

`/vtns/{vtn_name}/vbridges.json`

|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`       "vbridge": {` +
`           "vbr_name": "{vbr_name}",` +
`           "controller_id":` +
`         "{controller_id}",` +
`           "description":` +
`         "{description}",` +
`           "domain_id": "{domain_id}"` +
`            }` +
`  }`
|========================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes
|=======================================================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes

|description |Additional information. Valid value: A string of up to 127
characters. || No

|domain_id |domain_id Domain identifier. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive. || Yes
|=======================================================================

[[response]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v -X POST -H 'content-type: application/json' -H 'username:
admin' -H 'password: adminpass' -H 'ipaddr:127.0.0.1' -d '\{"vbridge" :
\{"vbr_name":"vbr_one","controller_id":"controllerone","domain_id":"(DEFAULT)"
}}' http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges.json
|=======================================================================

[[delete-vbridge]]
== Delete vBridge

This operation is used to delete a vBridge.

[[request-1]]
=== Request

[cols=",",]
|==========================================
|Method |DELETE
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}.json`

|==========================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes
|=======================================================================

Remember: vBridge whose Interface is set in if1_name or if2_name of
vLink cannot be deleted.

[[response-1]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v -X DELETE -H 'content-type: application/json' -H 'username:
admin' -H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one.json
|=======================================================================

[[update-vbridge]]
== Update vBridge

This operation is used to update a vBridge.

[[request-2]]
=== Request

[cols=",",]
|==========================================
|Method |PUT
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}.json`

|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`      "vbridge": {` +
`           "controller_id":` +
`    "{controller_id}",` +
`           "description":` +
`    "{description}",` +
`           "domain_id": "{domain_id}"` +
`         }` +
` }`
|==========================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes
|=======================================================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || No

|description |Additional information. Valid value: A string of up to 127
characters. || No

|domain_id |domain_id Domain identifier. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive. || No
|=======================================================================

[[response-2]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v -X PUT -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1' -d
'\{"vbridge":\{"controller_id":"\{controllerone}","description":"\{description}","domain_id":
"\{domain_id}"}}'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one.json
|=======================================================================

[[list-vbridge]]
== List vBridge

This operation is used to list vBridge information based on specified
conditions.

[[request-3]]
=== Request

[cols=",",]
|=================================================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges.xml` +
`/vtns/{vtn_name}/vbridges/detail.xml` +
`/vtns/{vtn_name}/vbridges/count.xml`

* JSON format

`/vtns/{vtn_name}/vbridges.json` +
`/vtns/{vtn_name}/vbridges/detail.json` +
`/vtns/{vtn_name}/vbridges/count.json`

|Query string |`?index={vbr_name}&max_repetition={max_repetition}`
|=================================================================

Request Body::
  None

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes
|=======================================================================

Description of Query String Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
No

|max_repetetion |Number of the resources that are returned. Valid value:
A positive integer Valid range: 1 to MAX of UINT32. Default is 10000. ||
No
|=======================================================================

[[response-3]]
=== Response

[cols=",",]
|=============================================
|Response Body (XML) a|
`If detail or count is not specified in URI` +

 +
`   ` +

If detail is specified in URI

 +
`    ` +

If count is specified in URI

|Response Body (JSON) a|
`If detail or count is not specified in URI` +
`{` +
`  "vbridges": [` +
`      {` +
`        "vbr_name":` +
`   "{vbr_name}"` +
`      }` +
`    ]` +
` }`

If detail is specified in URI

`{` +
`  "vbridges": [` +
`     {` +
`         "vbr_name":` +
`     "{vbr_name}",` +
`         "controller_id":` +
`     "{controller_id}",` +
`         "description":` +
`     "{description}",` +
`         "status": "{status}",` +
`         "domain_id":` +
`     "{domain_id}"` +
`      }` +
`    ]` +
`}`

If count is specified in URI

`  {` +
`  "vbridges": {` +
`      "count": "{count}"` +
`        }` +
`   }`

|=============================================

Description of response elements::

[cols=",",]
|=======================================================================
|Element |Description

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|domain_id |domain_id Domain identifier. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive.

|status |vBridge status. Valid value: up, down, unknown

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).

|count |The number of vBridge. Valid value: A positive integer.
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v -X GET -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges.json
|=======================================================================

[[show-vbridge]]
== Show vBridge

This operation is used to view a specific vBridge information.

[[request-4]]
=== Request

[cols=",",]
|==========================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}.json`

|==========================================

Request Body::
  None

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes
|=======================================================================

[[response-4]]
=== Response

[cols=",",]
|====================================
|Response Body (XML) a|
` ` +

|Response Body (JSON format) |` {` +
`   "vbridge": {` +
`        "vbr_name": "{vbr_name}",` +
`        "controller_id":` +
`   "{controller_id}",` +
`        "description":` +
`   "{description}",` +
`        "status": "{status}",` +
`   "domain_id": "{domain_id}"` +
`   }` +
`  }`
|====================================

Description of response elements::

[cols=",",]
|=======================================================================
|Element |Description

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|domain_id |domain_id Domain identifier. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive.

|status |vBridge status. Valid value: up, down, unknown

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning).

|count |The number of vBridge. Valid value: A positive integer.
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v -X GET -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges.json
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
