[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
*
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi#VTNCoordinator_RestApi_Contents[VTN
Coordinator RestApi Contents] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: Physical Controller Functions[Controller
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Switch Functions[Switch
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Port Functions[Physical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:Physical Link Function[Physical
Link function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Domain Functions[Domain
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Logical Port Function[Logical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Network Example Using VTN Virtualization[L2
Network Example Using VTN Virtualization]

|=======================================================================

[cols="^",]
|=======================================================================
|*NOTE*

|This REST API is not supported in current release, its targeted for
future release.
|=======================================================================

[[about]]
= About

This section lists the Physical Boundary functions.

[[list-of-functions-supported]]
= List of Functions Supported

[[create-physical-boundary]]
== Create Physical Boundary

This operation is used to add a Physical Boundary information.

[[request]]
=== Request

[cols=",",]
|==============================================
|Method |POST
|Request URI |`/boundaries`
|Request Body(XML format) a|
|

 +
 +

|Request Body(JSON format) a|
|

` {` +
` "boundary": {` +
` "boundary_id": "{boundary_id}",` +
` "description": "{description}",` +
` "link": {` +
`  "controller1_id": "{controller1_id}",` +
`  "domain1_id": "{domain1_id}",` +
`  "logical_port1_id": "{logical_port1_id}",` +
`  "controller2_id": "{controller2_id}",` +
`  "domain2_id": "{domain2_id}",` +
`  "logical_port2_id": "{logical_port2_id}"` +
`  }` +
` }` +
` }`

|==============================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes

|description |Additional information. Valid value: A string of up to 127
characters. || No

|controller1_id |Identifier of the first Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning). || Yes

|domain1_id |Identifier of the first Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive. || Yes

|logical_port1_id |Name of the first Logical Port. Valid value: A string
of up to 319 characters. Note: • This parameter is required for PFC. •
This parameter cannot be specified if type of controller specified in
controller1_id is bypass. || Conditional

|controller2_id |Identifier of the second Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning). || Yes

|domain2_id |Identifier of the second Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning) and the string - (DEFAULT). Note: The value of
domain_id is case sensitive. || Yes

|logical_port2_id |Name of the second Logical Port. Valid value: A
string of up to 319 characters. Note: • This parameter is required for
PFC. • This parameter cannot be specified if type of controller
specified in controller2_id is bypass. || Conditional
|=======================================================================

[[delete-physical-boundary]]
== Delete Physical Boundary

This operation is used to delete a Physical Boundary.

[[request-1]]
=== Request

[cols=",",]
|========================================
|Method |DELETE
|Request URI |`/boundaries/{boundary_id}`
|========================================

Description of request URI elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes
|=======================================================================

[[response]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

[[update-physical-boundary]]
== Update Physical Boundary

This operation is used to update a Physical Boundary.

[[request-2]]
=== Request

[cols=",",]
|========================================
|Method |PUT
|Request URI |`/boundaries/{boundary_id}`
|Request body (XML format) | +
|Request body (JSON format) |`{` +
`"boundary": {` +
` "description": "{description}"` +
` }` +
`}`
|========================================

Description of request elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes

|description |Additional information. Valid value: A string of up to 127
characters. || Yes
|=======================================================================

[[response-1]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

[[list-physical-boundaries]]
== List Physical Boundaries

This operation is used to list Physical Boundary information.

[[request-3]]
=== Request

[cols=",",]
|=======================================================================
|Method |GET

|Request URI |`/boundaries` +
`/boundaries/detail` +
`/boundaries/count`

|Query string |?
index=\{boundary_id}&max_repetition=\{max_repetition}&controller1_id=\{controller1_id}&controller2_id=\{controller2_id}
|=======================================================================

Description of query string elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes

|controller1_id |Identifier of the first Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning). || Yes

|controller2_id |Identifier of the second Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning). || No

|max_repetition |The number of resources that are returned. Valid value:
A positive integer. Valid range: 1 to MAX of UINT32. Default is 10000.
|| No
|=======================================================================

Request body::
  None

[[response-2]]
=== Response

[cols=",",]
|===============================================
|Response Body(XML format) a|
| If detail or count is not specified in URI

 +
 +

If detail is specified in URI

 +
 +
 +
 +

If count is specified in URI

|Response Body(JSON format) a|
| If count or detail is not specified in URI

`{` +
` "boundaries": [` +
` {` +
` "boundary_id": "{boundary_id}"` +
` }` +
` ]` +
`}`

If detail is specified in URI

`{` +
` "boundaries": [` +
`  {` +
`  "boundary_id": "{boundary_id}",` +
`  "description": "{description}",` +
`  "operstatus": "{operstatus}",` +
`  "link": {` +
`   "controller1_id": "{controller1_id}",` +
`   "domain1_id": "{domain1_id}",` +
`   "logical_port1_id": "{logical_port1_id}",` +
`   "controller2_id": "{controller2_id}",` +
`   "domain2_id": "{domain2_id}",` +
`   "logical_port2_id": "{logical_port2_id}"` +
`   }` +
` }` +
` ]` +
`}`

If count is specified in URI

`{` +
`"boundaries": {` +
` "count": "{count}"` +
` }` +
` }`

|===============================================

Description of response elements(boundary)::

[cols=",",]
|=======================================================================
|Element |Description

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|operstatus |The operational status. Valid value: up, down, unknown

|count |The number of Domains. Valid value: A positive integer.

|link |Link list.
|=======================================================================

Description of response elements (link)::

[cols=",",]
|=======================================================================
|Element |Description

|controller1_id |Identifier of the first Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning).

|domain1_id |Identifier of the first Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|logical_port1_id |Name of the first Logical Port. Valid value: A string
of up to 319 characters.

|controller2_id |Identifier of the second Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning).

|domain2_id |Identifier of the second Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning)

|logical_port2_id |Name of the second Logical Port. Valid value: A
string of up to 319 characters.
|=======================================================================

[[show-physical-boundary]]
== Show Physical Boundary

This operation is used to view a specific Physical Boundary information.

[[request-4]]
=== Request

[cols=",",]
|========================================
|Method |GET
|Request URI |`/boundaries/{boundary_id}`
|========================================

Description of request URI element::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). || Yes
|=======================================================================

Request body::
  None

[[response-3]]
=== Response

[cols=",",]
|==============================================
|Response Body(XML format) a|
|

 +
 +

|Response Body(JSON format) a|
|

`{` +
`"boundary": {` +
` "boundary_id": "{boundary_id}",` +
` "description": "{description}",` +
` "operstatus": "{operstatus}",` +
` "link": { ` +
`  "controller1_id": "{controller1_id}",` +
`  "domain1_id": "{domain1_id}",` +
`  "logical_port1_id": "{logical_port1_id}",` +
`  "controller2_id": "{controller2_id}",` +
`  "domain2_id": "{domain2_id}",` +
`  "logical_port2_id": "{logical_port2_id}"` +
` }` +
` }` +
`}`

|==============================================

Description of response elements(boundary)::

[cols=",",]
|=======================================================================
|Element |Description

|boundary_id |Identifier of the Boundary. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |Additional information. Valid value: A string of up to 127
characters.

|operstatus |The operational status. Valid value: up, down, unknown

|link |Link list.
|=======================================================================

Description of response elements (link)::

[cols=",",]
|=======================================================================
|Element |Description

|controller1_id |Identifier of the first Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning).

|domain1_id |Identifier of the first Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|logical_port1_id |Name of the first Logical Port. Valid value: A string
of up to 319 characters.

|controller2_id |Identifier of the second Controller. Valid value: Up to
31 characters that can include alphabets, numbers, and underscore
(except at the beginning).

|domain2_id |Identifier of the second Domain. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning)

|logical_port2_id |Name of the second Logical Port. Valid value: A
string of up to 319 characters.
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
