[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
*
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi#VTNCoordinator_RestApi_Contents[VTN
Coordinator RestApi Contents] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Switch Functions[Switch
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Port Functions[Physical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:Physical Link Function[Physical
Link function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Domain Functions[Domain
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Logical Port Function[Logical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Boundary Functions[Boundary
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Network Example Using VTN Virtualization[L2
Network Example Using VTN Virtualization]

|=======================================================================

[[about]]
= About

This Page will list the REST API to add/update/delete Physical
controllers to
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator[VTN
Coordinator]

[[list-of-functions-supported]]
= List of Functions Supported

[[create-physical-controller]]
== Create Physical Controller

Add a Physical Controller to Coordinator

[[request]]
=== Request

[cols=",",]
|===============================
|Method |POST
|Request URI |`/controllers`
|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`   "controller": {` +
`   "controller_id":` +
`   "{controller_id}",` +
`   "description":` +
`   "{description}",` +
`   "ipaddr": "{ipaddr}",` +
`   "type": "{type}",` +
`   "auditstatus":` +
`   "{auditstatus}",` +
`   "username": "{username}",` +
`   "password": "{password}",` +
`   "version": "{version}"` +
`   }` +
` }`
|===============================

Description of Request Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller.value: Up to 31 characters
that can include alphabets, numbers, and underscore (except at the
beginning). ||Yes

|description |A small description of the Controller. Valid value: A
string of up to 127 characters. ||No

|ipaddr |IP address. Valid value: IPv4 dot-separated format (Example:
192.168.1.1) Note: This parameter cannot be specified if _type_ is
bypass. ||No

|type |Controller type. Valid value: bypass, pfc, odc ||Yes

|auditstatus |Audit status. Valid value: enable, disable Note: This
parameter cannot be specified if _type_ is bypass. ||No

|usename |The user name you want to specify. Valid value: A string of up
to 31 characters. Note: This parameter cannot be specified if _type_ is
bypass. ||No

|password |The password that corresponds to the specified user name.
Valid value: A string of up to 256 characters. Note: This parameter
cannot be specified if _type_ is bypass. ||No

|version |Version of Controller. Valid value: A string of up to 31
characters that can include numbers and dot (.). ||Yes
|=======================================================================

[[response]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
POST -d '\{"controller": \{"controller_id": "controllerone",
"ipaddr":"10.100.9.16", "type": "odc", "version": "1.0",
"auditstatus":"enable"}}' http://127.0.0.1:8083/vtn-webapi/controllers
|=======================================================================

[[delete-physical-controller]]
== Delete Physical Controller

This operation is used to delete a Physical controller.

[[request-1]]
=== Request

[cols=",",]
|===========================================
|Method |DELETE
|Request URI |`/controllers/{controller_id}`
|===========================================

Description of Request Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller.value: Up to 31 characters
that can include alphabets, numbers, and underscore (except at the
beginning). ||Yes
|=======================================================================

[[response-1]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
DELETE http://127.0.0.1:8083/vtn-webapi/controllers/controllerone
|=======================================================================

[[update-physical-controller]]
== Update Physical Controller

This operation is used to update a Physical Controller.

[[request-2]]
=== Request

[cols=",",]
|===========================================
|Method |PUT
|Request URI |`/controllers/{controller_id}`
|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`   "controller": {` +
`     "description":` +
`     "{description}",` +
`     "ipaddr": "{ipaddr}",` +
`     "auditstatus":` +
`     "{auditstatus}",` +
`     "username": "{username}",` +
`     "password": "{password}",` +
`     "version": "{version}"` +
`   }` +
` }`
|===========================================

Description of Request Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller.value: Up to 31 characters
that can include alphabets, numbers, and underscore (except at the
beginning). ||Yes

|description |A small description of the Controller. Valid value: A
string of up to 127 characters. ||No

|ipaddr |IP address. Valid value: IPv4 dot-separated format (Example:
192.168.1.1) Note: This parameter cannot be specified if _type_ is
bypass. ||No

|auditstatus |Audit status. Valid value: enable, disable Note: This
parameter cannot be specified if _type_ is bypass. ||No

|username |The user name you want to specify. Valid value: A string of
up to 31 characters. Note: This parameter cannot be specified if _type_
is bypass. ||No

|password |The password that corresponds to the specified user name.
Valid value: A string of up to 256 characters. Note: This parameter
cannot be specified if _type_ is bypass. ||No

|version |Version of Controller. Valid value: A string of up to 31
characters that can include numbers and dot (.). ||Yes
|=======================================================================

[[response-2]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi#List_of_Response_codes[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
PUT -d '\{"controller": \{"description": "new
controller","ipaddr":"10.100.9.17", "version": "1.0",
"auditstatus":"enable"}}'
http://127.0.0.1:8083/vtn-webapi/controllers/controllerone
|=======================================================================

[[list-physical-controllers]]
== List Physical Controllers

This operation is used to list Physical Controller information.

[[request-3]]
=== Request

[cols=",",]
|=======================================================
|Method |GET
|Request URI |`/controllers` +
`/controllers/detail` +
`/controllers/count`
|Query string |` ?` +
` index={controller_id}&max_repetition={max_repetition}`
|=======================================================

Description of query string elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). ||No

|max_repetetion |Number of the Controllers that are returned. When the
count is specified as "0", then the result is the total number of the
Controller. Valid value: A positive integer Valid range: 1 to MAX of
UINT32. Default is 10000 ||No
|=======================================================================

[[response-3]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::

[cols=",",]
|============================================
|Response Body (XML) a|
If count or detail is not specified in URI

` ` +
` ` +
` `

If detail is specified in URI

 +
`  ` +
`  `

If count is specified in URI

|Request Body (JSON) a|
If count or detail is not specified in URI

`{` +
`   "controllers": [` +
`     {` +
`        "controller_id":` +
`        "{controller_id}"` +
`     }` +
`   ]` +
`}`

If detail is specified in URI

` {` +
`  "controllers": [` +
`    {` +
`    "controller_id": "{controller_id}",` +
`    "description": "{description}",` +
`    "ipaddr": "{ipaddr}",` +
`    "type": "{type}",` +
`    "auditstatus": "{auditstatus}",` +
`    "username": "{username}",` +
`    "password": "{password}",` +
`    "version": "{version}",` +
`    "actual_version": "{actual_version}",` +
`    "operstatus": "{operstatus}"` +
`    }` +
`  ]` +
`}`

If count is specified in URI

`{` +
`  "controllers": {` +
`      "count": "{count}"` +
`  }` +
`}`

|============================================

Description of Response Elements::

[cols=",",]
|=======================================================================
|Element |Description

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |A small description of the Controller. Valid value: A
string of up to 127 characters.

|ipaddr |IP address. Valid value: IPv4 dot-separated format (Example:
192.168.1.1) Note: This parameter cannot be specified if _type_ is
bypass.

|type |Controller type. Valid value: bypass, pfc, odc

|auditstatus |Audit status. Valid value: enable, disable Note: This
parameter cannot be specified if _type_ is bypass.

|username |The user name you want to specify. Valid value: A string of
up to 31 characters. Note: This parameter cannot be specified if _type_
is bypass.

|password |The password that corresponds to the specified user name.
Valid value: A string of up to 256 characters. Note: This parameter
cannot be specified if _type_ is bypass.

|version |Version of Controller. Valid value: A string of up to 31
characters that can include numbers and dot (.).

|actual_version |Actual version of Controller. Valid value: A string of
up to 31 characters that can include numbers and dot (.).

|operstatus |The operational status. Valid value: up, down,
waiting_audit, auditing

|count |The number of Controllers. Valid value: A positive integer.
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass -H 'content-type: application/json' -X
GET http://127.0.0.1:8083/vtn-webapi/controllers.json
|=======================================================================

[[show-physical-controller]]
== Show Physical Controller

This operation is used to view a specific Physical Controller
information.

[[request-4]]
=== Request

[cols=",",]
|===========================================
|Method |GET
|Request URI |`/controllers/{controller_id}`
|===========================================

Description of query string elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning). ||Yes
|=======================================================================

[[response-4]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::

[cols=",",]
|============================================
|Response Body (XML) a|
 +
`  ` +
`  `

|Request Body (JSON) |` {` +
`  "controllers": [` +
`    {` +
`    "controller_id": "{controller_id}",` +
`    "description": "{description}",` +
`    "ipaddr": "{ipaddr}",` +
`    "type": "{type}",` +
`    "auditstatus": "{auditstatus}",` +
`    "username": "{username}",` +
`    "password": "{password}",` +
`    "version": "{version}",` +
`    "actual_version": "{actual_version}",` +
`    "operstatus": "{operstatus}"` +
`    }` +
`  ]` +
`}`
|============================================

Description of Response Elements::

[cols=",",]
|=======================================================================
|Element |Description

|controller_id |Identifier of the Controller. Valid value: Up to 31
characters that can include alphabets, numbers, and underscore (except
at the beginning).

|description |A small description of the Controller. Valid value: A
string of up to 127 characters.

|ipaddr |IP address. Valid value: IPv4 dot-separated format (Example:
192.168.1.1) Note: This parameter cannot be specified if _type_ is
bypass.

|type |Controller type. Valid value: bypass, pfc, odc

|auditstatus |Audit status. Valid value: enable, disable Note: This
parameter cannot be specified if _type_ is bypass.

|username |The user name you want to specify. Valid value: A string of
up to 31 characters. Note: This parameter cannot be specified if _type_
is bypass.

|password |The password that corresponds to the specified user name.
Valid value: A string of up to 256 characters. Note: This parameter
cannot be specified if _type_ is bypass.

|version |Version of Controller. Valid value: A string of up to 31
characters that can include numbers and dot (.).

|actual_version |Actual version of Controller. Valid value: A string of
up to 31 characters that can include numbers and dot (.).

|operstatus |The operational status. Valid value: up, down,
waiting_audit, auditing
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v --user admin:adminpass 'content-type: application/json' -X GET
http://127.0.0.1:8083/vtn-webapi/controllers/controllerone
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
