[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
*
OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi#VTNCoordinator_RestApi_Contents[VTN
Coordinator RestApi Contents] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Functions[vBridge
Functions] +

|=======================================================================

[[about]]
= About

This Page will list the REST API to add/update/delete VLAN Map to
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator[VTN
Coordinator]

[[list-of-functions-supported]]
= List of Functions Supported

[[create-vlan-map]]
== Create VLAN Map

This operation is used to create a VLAN Map.

[[request]]
=== Request

[cols=",",]
|===================================================
|Method |POST
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps.json`

|Request Body (XML) |` `
|Request Body (JSON) |` {` +
`    "vlanmap": {` +
`       "logical_port_id":` +
`     "{logical_port_id}",` +
`       "vlan_id": "{vlan_id}",` +
`       "no_vlan_id":` +
`     "{no_vlan_id}"` +
`        }` +
` }`
|===================================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes
|=======================================================================

Description of Request Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|logical_port_id |Logical port identifier. Valid value: A string of up
to 319 characters. || No

|vlan_id |Identifier of the mapped VLAN. Valid value: A positive
integer. Valid range: 1 - 4095 || No

|no_vlan_id |Indicates that no vlan_id is used.Valid value: true. Note:
Either vlan_id or no_vlan_id can be specified. || No
|=======================================================================

Remember: Combination of logical_port_id and vlan_id must be unique
within vBridge.

Important: When setting VLAN Map in the vBridge under controller whose
type is pfc, PFC needs to be configured as bellow.

* When specifying switch identifier in logical_port_id, configure
Extended VLAN mode (vlan-connect

enable).

* When specifying no_vlan_id configure Standard VLAN mode (no
vlan-connect enable).

[[response]]
=== Response

[cols=",",]
|===========================
|Response Body (XML) a|
` `

|Request Body (JSON) |` {` +
`   "vlanmap": {` +
`       "vlanmap_id":` +
`    "{vlanmap_id}"` +
`     }` +
`  }`
|===========================

Description of Response Elements::

[cols=",",]
|=======================================================================
|Element |Description

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise, it is
"no_lpid ".
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v -X POST -H 'content-type: application/json' -H 'username:
admin' -H 'password: adminpass' -H 'ipaddr:127.0.0.1' -d '\{"vlanmap":
\{"logical_port_id":"\{logical_port_id}","vlan_id":
"\{vlan_id}","no_vlan_id":"\{no_vlan_id}"}}’
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/vlanmaps.json
|=======================================================================

[[delete-vlan-map]]
== Delete VLAN Map

This operation is used to delete a VLAN Map.

[[request-1]]
=== Request

[cols=",",]
|================================================================
|Method |DELETE
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.json`

|================================================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise, it is
"no_lpid". || Yes
|=======================================================================

Request Body::
  None

[[response-1]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v -X DELETE -H 'content-type: application/json' -H 'username:
admin' -H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/vlanmaps/vlan_one.json
|=======================================================================

[[update-vlan-map]]
== Update VLAN Map

This operation is used to update a VLAN Map.

[[request-2]]
=== Request

[cols=",",]
|================================================================
|Method |PUT
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.json`

|Request Body (XML) |` `
|Request Body (JSON) |`  {` +
`    "vlanmap": {` +
`        "vlan_id": "{vlan_id}",` +
`     "no_vlan_id":` +
`  "{no_vlan_id}"` +
`        }` +
`  }`
|================================================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise, it is
"no_lpid". || Yes
|=======================================================================

Description of Request Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vlan_id |Identifier of the mapped VLAN. Valid value: A positive
integer. Valid range: 1 - 4095 || No

|no_vlan_id |Indicates that no vlan_id is used. Valid value: true. Note:
Either vlan_id or no_vlan_id can be specified. || No
|=======================================================================

Remember: Combination of logical_port_id and vlan_id must be unique
within vBridge.

[[response-2]]
=== Response

::
  The Response returned will be one of the values in the
  OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[List
  of response Codes].

Response Body::
  None

Example::

[cols="",]
|=======================================================================
|curl -v -X PUT -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1' -d
'\{"vlanmap":"vlan_id":"\{vlan_id}","no_vlan_id":"\{no_vlan_id}" }}'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/vlanmaps/vlan_one.json
|=======================================================================

[[list-vlan-map]]
== List VLAN Map

This operation is used to list VLAN Map information based on specified
conditions.

[[request-3]]
=== Request

[cols=",",]
|============================================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps.xml` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/detail.xml` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/count.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps.json` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/detail.json` +
`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/count.json`

|============================================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes
|=======================================================================

Description of Query String Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise,
vlanmap_id is "no_lpid". || No

|max_repetetion |Number of the resources that are returned. Valid value:
A positive integer Valid range: 1 to MAX of UINT32. Default is 10000. ||
No
|=======================================================================

[[response-3]]
=== Response

[cols=",",]
|=========================================
|Request Body (XML) a|
If count or detail is not specified in URI

 +
`     ` +

If detail is specified in URI

`      ` +
` ` +
` `

If count is specified in URI

` `

|Request Body (JSON) a|
If count or detail is not specified in URI

` {` +
`   "vlanmaps": [` +
`      {` +
`      "vlanmap_id":` +
`   "{vlanmap_id}"` +
`      }` +
`    ]` +
`  }`

If detail is specified in URI

`  {` +
`   "vlanmaps": [` +
`        {` +
`      "vlanmap_id":` +
`   "{vlanmap_id}",` +
`      "logical_port_id":` +
`   "{logical_port_id}",` +
`      "vlan_id":` +
`   "{vlan_id}",` +
`      "no_vlan_id":` +
`   "{no_vlan_id}"` +
`        }` +
`    ]` +
`  }`

If count is specified in URI

`  {` +
`  "vlanmaps": {` +
`     "count": "{count}"` +
`     }` +
`  }`

|=========================================

Description of Response Elements::

[cols=",",]
|=======================================================================
|Element |Description

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise,
vlanmap_id is "no_lpid".

|logical_port_id |Logical port identifier. Valid value: A string of up
to 319 characters.

|vlan_id |Identifier of the mapped VLAN. Valid value: A positive
integer. Valid range: 1 - 4095

|no_vlan_id |Indicates that no vlan_id is used. Valid value: true. Note:
Either vlan_id or no_vlan_id can be specified.

|count |Number of VLAN Maps. Valid value: A positive integer.
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v -X GET -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/vlanmaps/vlan_one.json
|=======================================================================

[[show-vlan-map]]
== Show VLAN Map

This operation is used to view a specific VLAN Map information.

[[request-4]]
=== Request

[cols=",",]
|================================================================
|Method |GET
|Request URI a|
* XML format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.xml`

* JSON format

`/vtns/{vtn_name}/vbridges/{vbr_name}/vlanmaps/{vlanmap_id}.json`

|================================================================

Description of Request URI Elements::

[cols=",,",]
|=======================================================================
|Element |Description |Required

|vtn_name |VTN name. Valid value: Up to 31 characters that can include
alphabets, numbers, and underscore (except at the beginning). || Yes

|vbr_name |vBridge name. Valid value: Up to 31 characters that can
include alphabets, numbers, and underscore (except at the beginning). ||
Yes

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise, it is
"no_lpid". ||Yes
|=======================================================================

Request Body::
  None

[[response-4]]
=== Response

[cols=",",]
|====================================
|Response Body (XML) a|
` `

|Response Body (JSON) |`{` +
`     "vlanmap": {` +
`          "vlanmap_id":` +
`    "{vlanmap_id}",` +
`          "logical_port_id":` +
`    "{logical_port_id}",` +
`          "vlan_id": "{vlan_id}",` +
`    "no_vlan_id":` +
`          "{no_vlan_id}"` +
`      }` +
` }`
|====================================

Description of Response Elements;::

[cols=",",]
|=======================================================================
|Element |Description

|vlanmap_id |VLAN Map identifier. If logical_port_id is specified at
creation time, vlanmap_id is "lpid-\{logical_port_id}". Otherwise,
vlanmap_id is "no_lpid".

|logical_port_id |Logical port identifier. Valid value: A string of up
to 319 characters.

|vlan_id |Identifier of the mapped VLAN. Valid value: A positive
integer. Valid range: 1 - 4095

|no_vlan_id |Indicates that no vlan_id is used. Valid value: true. Note:
Either vlan_id or no_vlan_id can be specified.

|count |Number of VLAN Maps. Valid value: A positive integer.
|=======================================================================

Example::

[cols="",]
|=======================================================================
|curl -v -X GET -H 'content-type: application/json' -H 'username: admin'
-H 'password: adminpass' -H 'ipaddr:127.0.0.1'
http://127.0.0.1:8080/vtn-webapi/vtns/vtn_one/vbridges/vbr_one/vlanmaps/vlan_one.json
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
