OpenDaylight_Toolkit:Main[Go back to OpenDaylight Toolkit]

[[opendaylight-toolkit-on-mac]]
= OpenDaylight Toolkit on Mac

Getting started with OpenDaylight Toolkit on Mac

Tested on

* OS X 10.9.3

[[getting-started]]
== Getting Started

[[prerequisites]]
=== Prerequisites

* ensure https://developer.apple.com/xcode/[xcode] is installed on your
mac so you have git
* ensure
http://www.oracle.com/technetwork/java/javase/downloads/index.html[java]
is installed (jdk 7 or later)
* ensure http://maven.apache.org/download.cgi[maven] is installed or
available

Note: you won't be able to install maven like the other tools. You can
either directly access the executable bin/mvn or add it to your PATH.
(todo more details)

[[steps]]
=== Steps

1.  git clone https://git.opendaylight.org/gerrit/p/toolkit.git
2.  cd toolkit
3.  mvn install (this may take a while since you're downloading the
entire opendaylight controller)
4.  cd samples/simple
5.  mvn install
6.  cd ../.. (to back to toolkit root directory)
7.  cd main/target/main-osgipackage/opendaylight
8.  ./run.sh -console

The controller may take anywhere from a minute to a few minutes to
start. Then go to http://localhost:8080/ and you should be able to login
OpenDaylight Toolkit with simple App accessible from the overlay menu.

[[app-development]]
== App Development

To provision simple app development workspace

[[prerequisites-1]]
=== Prerequisites

* ensure http://nodejs.org/[nodejs] is installed on your mac

[[steps-1]]
=== Steps

1.  Ensure OpenDaylight controller is running in the background (refer
to section above)
2.  Ensure you are in the toolkit project root directory
3.  cd kit
4.  npm install (this will install the necessary node modules)
5.  node provision.js --scaffold (find out your ip address by using the
ifconfig command from your mac's terminal, if you're not sure try
localhost)
6.  cd .. (to go back to the toolkit project root directory)
7.  cd tool/node
8.  npm install
9.  node server.js

Then go to http://localhost:8000/ and you should be able to develop the
simple application from there. You can start in
samples/simple/src/main/resources/js/app.js. If your setup doesn't work,
then try scaffolding again with a different IP address.
