OpenDaylight_Toolkit:Main[Go back to OpenDaylight Toolkit]

[[opendaylight-toolkit-on-windows]]
= OpenDaylight Toolkit on Windows

Getting started with OpenDaylight Toolkit on Windows

Tested on

* Windows 7

[[getting-started-with-eclipse-on-windows]]
== Getting Started with Eclipse on Windows

Tested with Eclipse Kepler 4.3.2 on Windows 7 64-bit

[[prerequisites]]
=== Prerequisites

* ensure http://www.oracle.com/technetwork/java/javase[Java SE
Development Kit] is installed (jdk 7 or later)
* ensure http://nodejs.org/[nodejs] is installed

[[steps]]
=== Steps

1.  Install http://git-scm.com/[git-scm Windows client]
2.  Open up *Git Bash*, go to a directory where you want to download
toolkit, and do *git clone
https://git.opendaylight.org/gerrit/p/toolkit.git*
3.  Open Eclipse
4.  [to import toolkit project] Eclipse IDE > File > Import > Maven >
Existing Maven Projects > Next > Browse (navigate to toolkit project
directory) > (ensure all projects except releasepom are selected) >
Finish (this may take a while)
5.  [to build odl controller] Eclipse IDE > Run > Run Configurations.. >
Maven Build > opendaylight-assemble-skiput (this may take a while)
6.  [to run odl controller] Eclipse IDE > Run > Debug Configurations.. >
Java Application > opendaylight-controller

[[steps-for-simple-application]]
=== Steps for simple application

1.  Import toolkit/samples/simple
2.  Perform fast build on simple application (select simple project in
Eclipse IDE > Run > Run Configurations... > Maven Build >
opendaylight-assemble-fast)
3.  (in command) cd toolkit/kit
4.  npm install (this will install the necessary node modules)
5.  node provision.js --scaffold (find out your ip address by using
ipconfig, if you're not sure try localhost)
6.  cd ../tool/node
7.  npm install
8.  node server.js

Then go to http://localhost:8000/ and you should be able to develop the
simple application from there. You can start in
samples/simple/src/main/resources/js/app.js. If your setup doesn't work,
then try scaffolding again with a different IP address.

[[draft-getting-started-with-cli]]
== [Draft] Getting Started with CLI

[[prerequisites-1]]
=== Prerequisites

* ensure http://git-scm.com/[git-scm] is installed on your windows so
you have git
* ensure http://www.oracle.com/technetwork/java/javase[java] is
installed (jdk 7 or later)
* ensure http://maven.apache.org/download.cgi[maven] is installed or
available

Note: you won't be able to install maven like the other tools. You can
either directly access the executable bin/mvn or add it to your PATH.
(todo more details)

[[steps-1]]
=== Steps

1.  git clone https://git.opendaylight.org/gerrit/p/toolkit.git
2.  cd toolkit
3.  mvn install (this may take a while since you're downloading the
entire opendaylight controller)
4.  cd samples/simple
5.  mvn install
6.  cd ../.. (to back to toolkit root directory)
7.  cd main/target/main-osgipackage/opendaylight
8.  ./run.sh -console

The controller may take anywhere from a minute to a few minutes to
start. Then go to http://localhost:8080/ and you should be able to login
OpenDaylight Toolkit with simple App accessible from the overlay menu.

[[draft-app-development]]
== [Draft] App Development

To provision simple app development workspace

[[prerequisites-2]]
=== Prerequisites

* ensure http://nodejs.org/[nodejs] is installed on your windows

[[steps-2]]
=== Steps

1.  Ensure OpenDaylight controller is running in the background (refer
to section above)
2.  Ensure you are in the toolkit project root directory
3.  cd kit
4.  npm install (this will install the necessary node modules)
5.  node provision.js --scaffold (find out your ip address by using the
ipconfig, if you're not sure try localhost)
6.  cd .. (to go back to the toolkit project root directory)
7.  cd tool/node
8.  npm install
9.  node server.js

Then go to http://localhost:8000/ and you should be able to develop the
simple application from there. You can start in
samples/simple/src/main/resources/js/app.js. If your setup doesn't work,
then try scaffolding again with a different IP address.
