[[project-name]]
== Project Name

Openflow Protocol Library (openflowjava)

[[features]]
== Features

Openflow v1.3 support

Openflow v1.0 support

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

* Openflow_Protocol_Library:Startup_Guide[Startup Guide]

*
image:OpenFlow_Protocol_Library_-_Project_documentation.pdf[OpenFlow_Protocol_Library_-_Project_documentation.pdf,title="fig:OpenFlow_Protocol_Library_-_Project_documentation.pdf"]

[[issues-to-be-fixed]]
== Issues to be fixed

* YANG model should go through a minor refactoring
** groupings should have "-grouping" suffix to ease the development and
remove ambiguity
** list actions-list (openflow-action.yang) and underlying container
action should be merged into list action
** all lists with plural nouns (e.g. list instruction*s*) should be
replaced by their singular form to improve code understanding
* Netty's threads should go through performance testing to improve
overall performance

[[security-considerations]]
== Security Considerations

Communication over TLS uses bogus key - will be replaced when global
keystore is implemented in Config Subsystem

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

Unit tests cover all message (de)serialization factories and util
classes. Integration test is used to test communication over wire
(SimpleClient is used as lightweight switch implementation). Detailed
test cases are tested also in the Openflow Plugin tests. It is also
possible to test openflowjava communication with vswitch.

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

There is only one issue in bugzilla
(https://bugs.opendaylight.org/show_bug.cgi?id=370[1]) assigned to
openflowjava. It occurs during Multipart message (OF v1.3)
deserialization. There is a suspicion that vswitch is sending incorrect
data (based on Wireshark capture) or that network errors might be the
cause. This issue is under further investigation.

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

* Openflow v1.3.2 specification
* Openflow v1.0.0 specification

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)

* TLS support not tested / fully implemented
* Added Openflow v1.0 support

