[[reporting-security-issues]]
== Reporting security issues

Please report any security issues you find in OpenDaylight to:
security@lists.opendaylight.org

Anyone can post to this list. The subscribers are only trusted
individuals who will handle the resolution of any reported security
issues in confidence. In your report, please note how you would like to
be credited for discovering the issue and the details of any embargo you
would like to impose.

The OpenDaylight vulnerability management process is
https://wiki.opendaylight.org/view/TSC:Vulnerability_Management[documented
here].

[[security-advisories]]
== Security advisories

The link:Security Advisories[security advisories] page lists all
security vulnerabilities fixed in OpenDaylight.

[[secure-engineering]]
== Secure engineering

An effort is currently underway to bootstrap a pro-active secure
engineering effort, similar to OpenStack's OSSG. A presentation on the
secure engineering vision for OpenDaylight is
https://wiki.opendaylight.org/images/8/8c/201501-ODL-Bay_Area_Meetup.pdf[available
here]. If you are interested in assisting with this effort, please see
the
https://wiki.opendaylight.org/view/InternProjects:Main#Implement_a_secure_engineering_process_for_OpenDaylight[summer
internship project proposal].
