[[neutron-service]]
= Neutron Service

[[code-name]]
== Code Name

Karaf: odl-neutron-service

[[description]]
== Description

This karaf feature provides support for OpenStack Neutron via the ODL
ML2 agent (link needed). It includes the bundles in the next section and
follows this NeutronNorthbound:Architecture[Architecture]. As the karaf
feature includes everything necessary for communicating northbound, no
special configuration is needed.

[[bundles]]
== Bundles

As shown in the
https://git.opendaylight.org/gerrit/gitweb?p=neutron.git;a=blob;f=features/src/main/features/features.xml;h=e54a8068d41e81e9075512e980682c1b39be55fc;hb=HEAD[features.xml
file] this feature includes the following bundles:

* neutron-spi
* transcriber
* northbound-api

[[upstream-dependencies]]
== Upstream Dependencies

controller

[[downstream-dependents]]
== Downstream Dependents

* Group_Policy:Main[groupbasedpolicy]
* CrossProject:Integration_Group[integration]
* OpenDaylight_Lisp_Flow_Mapping:Main[lisp]
* OVSDB_Integration:Main[ovsdb]
* Southbound_plugin_to_the_OpenContrail_platform:Main[plugin2oc]
* OpenDaylight_Virtual_Tenant_Network_(VTN):Main[vtn]

[[incompatibilities]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness]]
== Network Intrusiveness

None

[[recommended-karaf-features]]
== Recommended Karaf features

none

[[how-to-test]]
== How to test

The Neutron Northbound project includes a dummyprovider bundle which is
used for testing the API, objects and transcriber function of the
neutron service.

For testing this feature, we have a TBD Jenkins Job that can be
triggered to handle CI testing of the odl-neutron-service feature.

[[performancescalability-concerns]]
== Performance/Scalability Concerns

As this service is providing simple data transcribing no additional
performance and scalability concerns over those provided by the MD-SAL
or existing whiteboard patterns are expected.
