[[when]]
= When

Weekly on Friday at 08:00 PST/PDT | 11:00 EST/EDT | 15:00 UTC during
Daylight Time/16:00 UTC during Standard Time

[[where]]
= Where

IRC: #opendaylight-neutron on freenode

[[miscellany]]
= Miscellany

* https://trello.com/b/LhIIQ8Z0/odl-neutronnorthbound[Trello Board]
*
[https://bugs.opendaylight.org/buglist.cgi?list_id=27656&product=neutron&query_format=advanced&resolution=---
bugs]

[[agenda-for-next-meeting-529]]
= Agenda for Next Meeting (5/29)

* Agenda Bashing
* Action Items from Last Meeting (reordered to put quick items up front)
1.  regXboi to make best effort to move
https://git.opendaylight.org/gerrit/#/c/18356/ forward
2.  flaviof to update OS issues and move from
https://trello.com/b/ddIvDQE0/ovs-openstack to
https://trello.com/b/LhIIQ8Z0/odl-neutronnorthbound
3.  all to continue to look at why neutron-daily-openstack-master is
hosed
4.  all to work on ODL running in the OS gate so that we can unblock OS
patches
* Work session on Last two action items
* Other Topics
** regXboi is OOC with no computer access 6/5 - am looking for a
volunteer to run weekly meetings that date...

[[minutes-from-past-meetings]]
= Minutes from Past Meetings

* 5/29:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-29-15.01.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-29-15.01.log.html[log]
* 5/22: there was no meeting
* 5/15:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-15-15.01.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-15-15.01.log.html[log]
* 5/8:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-08-15.00.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-08-15.00.log.html[log]
* 5/1:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-01-15.00.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-05-01-15.00.log.html[log]
* 4/24:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-24-15.00.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-24-15.00.log.html[log]
* 4/17:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-17-14.59.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-17-14.59.log.html[log]
* 4/10:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-10-14.59.html[minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-17-14.59.log.html[log]
* 4/3:
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-03-15.02.html[Minutes]
and
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-04-03-15.02.log.html[Log]
* 3/27:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_03_27_2015/opendaylight-neutron-neutron_northbound_03_27_2015.2015-03-27-14.59.html[Minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_03_27_2015/opendaylight-neutron-neutron_northbound_03_27_2015.2015-03-27-14.59.log.html[Log]
* 3/20:
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_03_20_2015/opendaylight-neutron-neutron_northbound_03_20_2015.2015-03-20-15.04.html[Minutes]
and
https://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_03_20_2015/opendaylight-neutron-neutron_northbound_03_20_2015.2015-03-20-15.04.log.html[Log]
* 3/13:
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_2015_03_13/opendaylight-neutron-neutron_northbound_2015_03_13.2015-03-13-15.00.html[Minutes]
and
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound_2015_03_13/opendaylight-neutron-neutron_northbound_2015_03_13.2015-03-13-15.00.log.html[Log]
* 3/6:
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-03-06-16.04.html[Minutes]
and
http://meetings.opendaylight.org/opendaylight-neutron/2015/neutron_northbound/opendaylight-neutron-neutron_northbound.2015-03-06-16.04.log.html[Log]

