[[intro]]
== Intro

[[what-is-karaf]]
=== What is Karaf

http://karaf.apache.org[Apache Karaf] is a small OSGi based runtime
which provides a lightweight container onto which various components and
applications can be deployed. It tends to be helpful to think of Karaf
as providing an ecosystem for your application - we've collected
together various libraries and frameworks, and tested that they work
well together, simplifying your runtime experience.

Here is a short list of features supported by the Karaf:

* Hot deployment: Karaf supports hot deployment of OSGi bundles by
monitoring jar files inside the [home]/deploy directory. Each time a jar
is copied in this folder, it will be installed inside the runtime. You
can then update or delete it and changes will be handled automatically.
In addition, the Karaf also supports exploded bundles and custom
deployers (blueprint and spring ones are included by default).
* Dynamic configuration: Services are usually configured through the
ConfigurationAdmin OSGi service. Such configuration can be defined in
Karaf using property files inside the [home]/etc directory. These
configurations are monitored and changes on the properties files will be
propagated to the services.
* Logging System: using a centralized logging back end supported by
Log4J, Karaf supports a number of different APIs (JDK 1.4, JCL, SLF4J,
Avalon, Tomcat, OSGi)
* Provisioning: Provisioning of libraries or applications can be done
through a number of different ways, by which they will be downloaded
locally, installed and started.
* Native OS integration: Karaf can be integrated into your own Operating
System as a service so that the lifecycle will be bound to your
Operating System.
* Extensible Shell console: Karaf features a nice text console where you
can manage the services, install new applications or libraries and
manage their state. This shell is easily extensible by deploying new
commands dynamically along with new features or applications.
* Remote access: use any SSH client to connect to Karaf and issue
commands in the console
* Security framework based on JAAS
* Managing instances: Karaf provides simple commands for managing
multiple instances. You can easily create, delete, start and stop
instances of Karaf through the console.

[[karaf-provisioning-in-details]]
=== Karaf Provisioning in Details

Karaf has two methods of provisioning high level components known as
features. This can be done via Feature Descriptors or standalone .KAR
file packages. Feature descriptors are suitable for development ,
testing and advanced users while .KAR archives provides downloadable
binary artifacts mostly suitable for end-user standalone offline
installation.

[[feature-descriptors]]
==== Feature Descriptors

Karaf supports provisioning via 'feature descriptors' which allow
developers to group together sub-features, bundles, configuration files,
and other resources into one simple to use deployable package. The
bundles will be resolved via
https://ops4j1.jira.com/wiki/display/paxurl/Documentation|PAX-URL[1]
compatible URL as defined in the feature file. The current descriptors
currently is using the local maven repository (.m2/repository) along
with whatever is part of the custom distribution (/system) as the
locations from which to fetch the bundles. The feature descriptor also
specifies the *start-level* and order in which the bundles have to start
as such making feature start-stop behaviour more deterministic thus
reducing the number of runtime errors encountered.

* Example: Feature MD-SAL contains 25+ bundles, and requires yang tools.
All told that around 40 bundles plus configuration files. Using
''feature:install odl-mdsal-all" will provision all of these bundles
along with the configuration files and install them into the OSGi
container. This frees users and developers from needing to know about
all the individual components required to run MD-SAL.

* Example: Feature openflowplugin contains two openflowplugin bundles,
and requires the md-sal feature. Just specifying the openflowplugin
feature get you exactly what you need, no more, no less.

[[kar-archives]]
==== KAR Archives

The KAR archive (Karaf Archive) is a special archive package that
contains both the feature descriptor file along with all the referenced
bundles. This way a user doesn't need to have a local or remote maven
repository with the bundles in order to install the feature. This makes
.kar files suitable for offline installations or easy to download links.
Installing KAR files can be done via

kar:install /path/odl-feature.kar

on the console or simply by putting the .kar file in the /deploy folder
of the customized Karaf distribution for OpenDaylight

[[what-makes-karaf-useful-as-a-release-vehicle]]
== What makes Karaf useful as a Release Vehicle

Karaf allows us to have:

1.  A minimal karaf-based OpenDaylight container which consists of :
karaf + branding fragment + osgi framework extensions + a few config
files

1.  Features which can be installed as one liners like:

''feature:install odl-openflowplugin-all"

which pull in openflowplugin and everything you need for it to work.

[[published-repositories]]
=== Published Repositories

Because Karaf allows us to specify high level features which users can
be installed in the container, we have the opportunity to allow users to
have exactly the high level features they want.

As an example a download page could either provide a list of
downloadable .kar packages for each features or we can host an online
official /TSC approved feature repository from which features can be
downloaded. Moreover, there could be different repositories based on the
stability of the projects. As such a list of "stable" features would
make it into the stable repository while "unstable" and "experimental"
features could be available based on user's needs. Moreover project may
have stable and experimental features published which makes it possible
for projects to innovate without disrupting their stable components.

[cols=",",options="header",]
|==================================================
|Feature Repository |Stability
|http://xxx/stable-features.xml |Stable
|http://xxx/unstable-features.xml |Unstable
|http://xxx/experimental-features.xml |Experimental
|==================================================

These repositories would be available as part of the minimal customized
...

[[downloadable-configuration-profiles]]
=== Downloadable Configuration Profiles

A suggestion would be to make a small web application that would
generate proper configuration files from a set of selectable features.
Users would then simply put that configuration file at the right startup
location. This configuration file could also be bundled and added to a
release .zip archive along with the .kar files if necessary to provide
users with their completely customized distribution.

For example user wants features:

* bgpcep-all
* ovsdb-neutron

Thus when they start OpenDaylight, they will get *precisely* the minimum
set of things they need for the requested features to run. No more, no
less.

[[current-editions-using-karaf]]
=== Current Editions using Karaf

Current editions using Karaf is simply about providing the preinstalled
features as part of a distribution archive and providing the proper kar
files as dependencies to that archive. `
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.karaf.tooling</groupId>
                <artifactId>karaf-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <!-- no startupFeatures -->
                    <bootFeatures>
                        <feature>odl-mdsal-all</feature>
                        <feature>odl-adsal-all</feature>
                    </bootFeatures>
                    <!-- no installedFeatures -->
                </configuration>
            </plugin>
        </plugins>
    </build>
`

While doable, it becomes difficult to determine what exactly makes up a
good edition and what would be provided is simply enough to let users
choose what features to install or not.

[[user-driven-feature-selection]]
== User Driven Feature Selection

Because there is a huge set of combinatronics in terms of the features
that users want together, and they are difficult to predict accurately,
having User Driven Feature Selection rather than Centrally Planned
Release Vehicle Definition allows us to give our users what they
actually want.

[[recommended-release-vehicles-for-karaf]]
== Recommended Release Vehicles for Karaf

This proposal requires no 'hard' Release Vehicles based on projects and
features, because we provide users with the ability to choose the
features (add-ons) they want to have for their controller.

[[opendaylight-container]]
=== OpenDaylight Container

This download contains the minimal OpenDaylight container as a standard
Karaf distribution will not work because of ODL specific requirements.
This container should ideally also serve a CLI & GUI interfaces which
allows end-users to configure the environment by adding features. This
distribution is currently available from controller but should be
sitting in OpenDaylight's root dependency whether this is parent pom
project or a runtime project of some sort.

[[opendaylight-online-distribution]]
=== OpenDaylight Online Distribution

While it is impossible to predict the features that end-users would
expect I would consult a small user group to know what are end-users
expecting from a base controller. My personal bias would be to support
basic behaviors like l2switching along with an OpenFlow southbound, the
other features should then be downloaded from the online repository on
demand as required. (Think Package-Manager like). Other add-ons can also
be added by dropping a .kar in Deploy.

[[opendaylight-offline-distribution]]
=== OpenDaylight Offline Distribution

The offline distribution will package all projects without installing
them so that environments without internet can install the features from
the local repository instead. It should have the same level of basic
functionality as decided for the online distribution working from the
start.

[[testing-strategy]]
== Testing Strategy

Basic testing strategy would be to test feature-wise, with each feature
integration test running minimally in:

1.  Only load the feature - to make sure the feature works as defined
2.  Load all the features - to make sure we understand any collisions

[[pax-exam-integration-test]]
=== PAX-EXAM Integration Test

Testing of one or multiple features and combinations can easily be done
via PAX-Exam using Karaf based extensions to PAX-Exam 3...

`
 @RunWith(PaxExam.class)
 public class DefaultServiceIT {
 
    @Inject
    private BundleContext bundleContext;
 
    @Inject
    private ConfigurationAdmin configurationAdmin;
 
    @Configuration
    public Option[] config() {
        return new Option[] {
                // Provision and launch a container based on a distribution of Karaf (Apache ServiceMix).
                karafDistributionConfiguration()
                    .frameworkUrl(
                             maven()
                                     .groupId("org.opendaylight.controller")
                                     .artifactId("distribution-karaf")
                                     .type("zip")
                                     .version("0.4.2"))
                    .karafVersion("3.0.1")
                    .name("OpenDaylight")
                    .unpackDirectory(new File("target/pax"))
                    .useDeployFolder(false),
                // It is really nice if the container sticks around after the test so you can check the contents
                // of the data directory when things go wrong.
                keepRuntimeFolder(),
                // Don't bother with local console output as it just ends up cluttering the logs
                configureConsole().ignoreLocalConsole(),
                // Force the log level to INFO so we have more details during the test.  It defaults to WARN.
                logLevel(LogLevel.INFO),
                // Provision the example feature exercised by this test
                features(
                        "mvn:org.opendaylight.controller/features-base/0.6.2-SNAPSHOT/xml/features",
                        "odl-base-all"),
                // Remember that the test executes in another process.  If you want to debug it, you need
                // to tell Pax Exam to launch that process with debugging enabled.  Launching the test class itself with
                // debugging enabled (for example in Eclipse) will not get you the desired results.
                //debugConfiguration("5000", true),
                };
    }
 
    @Test
    public void test() throws Exception {
 
        ...
    }
`

[[robot-system-integration-test]]
=== Robot System Integration Test

System Integration Test is also available for system level features. For
this purpose there is already a test framework full documented in the
CrossProject:Integration_Group:CSIT[ CSIT wiki].

Projects with system test requirements will appoint a person to work
with Integration group with the goal of developing system test for their
features. Ideally this person should start collaborating with
Integration group by M4.

[[test-documention]]
=== Test Documention

Test documentation is very important in this release. Testopia (Bugzilla
extension) is already available at OpenDaylight and can be used to
document any SW test (Unit, Integration, System, Performance,...). It is
highly recommended projects use this tool to document their tests.
Please check our CrossProject:Integration_Group:Testopia[ Testopia wiki]
to learn how.

Projects with sytem test requirements should start filling Feature Test
documentation in Testopia by M4.
