[[introduction]]
== Introduction

The group-based policy project defines an application-centric policy
model for OpenDaylight that separates information about application
connectivity requirements from information about the underlying details
of the network infrastructure.

This approach offers a number of distinct advantages, including:

* Easier, application-focused way of expressing policy: By creating
policies that mirror application semantics, this framework provides a
simpler, self-documenting mechanism for capturing policy requirements
without requiring detailed knowledge of networking.
* Improved automation: Grouping constructs allow higher level automation
tools to easily manipulate groups of network endpoints simultaneously.
* Consistency: By grouping endpoints and applying policy to groups, the
framework offers a consistent and concise way to handle policy changes
* Extensible policy model: Since the policy model is abstract and not
tied to specific network implementations, it can easily capture
connectivity, security, L4-7, QoS, etc.

See the information below to learn more about the project.

[[team-meeting]]
== Team Meeting

* Group_Policy:Sub-Groups:STATUS#Team_Meeting[ Weekly status meeting]

[[user-guide]]
== User Guide

*FIXME:* Currently, the project is in the early stages. Check back later
for installation and operation guides.

[[developer-guide]]
== Developer Guide

[[proof-of-concept-integration-testing]]
=== Proof of Concept, Integration, Testing

* Group_Policy:Building and Running Docker[Building and Running -
Docker]
*
https://wiki.openstack.org/wiki/GroupBasedPolicy/InstallODLIntegrationDevstack#OpenDaylight_Set_up[Building
and Running - Openstack Integration]
* Group_Policy:Use-Cases[Working Use-Cases]
* Group_Policy:Building and Running[Building and Running - Mininet]

[[documentation]]
=== Documentation

* Group_Policy:Architecture[Architecture]

[[project-tracking]]
=== Project Tracking

*
https://trello.com/b/yc0xHFlv/opendaylight-groupbasedpolicy-lithium[Trello
- Lithium Release]
* https://bugs.opendaylight.org/show_bug.cgi?id=2817[Meta-bug for
tracking bugs in Lithium Release]
*
https://trello.com/b/SlwZh0MI/opendaylight-groupbasedpolicy-featurebacklog[Trello
- Feature Backlog]
*
https://docs.google.com/a/noironetworks.com/spreadsheets/d/1b_LuanBXzDIbuzhU03njB1coJwBqs8uYgzTD3dcASsQ/edit#gid=0[Lithium
Release Plan - Working Doc]
* Group_Policy:Lithium_Release_Plan[Lithium Release Plan]
* Group_Policy:Lithium_User_Facing_Features[Lithium User Facing
Features]

[[project-subgroups]]
=== Project Subgroups

The following project subgroups exist. See information on each of these
pages about periodic meetings

* Group Policy:Sub-Groups:STATUS[ Group 0: Status Meeting]
* Group Policy:Sub-Groups:ARCH[Group 1: Architecture]
* Group Policy:Sub-Groups:REQUIREMENTS[Group 11: Requirements]

[[presentationsevents]]
== Presentations/Events

* https://vimeo.com/92734822[SDDC Symposium 2014 - Metadata-Defined Data
Center, Mike Dvorkin]
*
https://wiki.opendaylight.org/images/f/f6/Intent_Summit_What_is_GBP.pptx[Intent
Summit - OpenDaylight Group Based Policy - Keith Burns]
*
https://wiki.opendaylight.org/view/SJBay_SDN_Meetup_141215-OS+ODL_livedemo.pptx[San
Jose SDN Meetup 12/15/14 OpenStack + OpenDaylight GBP Live Demo - Keith
Burns]
* https://www.youtube.com/watch?v=_e9iafRSi8E[Helium Mininet Demo - Rob
Adams]

[[other-documents]]
== Other Documents

These are some older documents that are left here for now for reference
purposes as they are phased out:

* Project Proposals:Group Based Policy Plugin[ Project Proposal]
* Group Policy:Scaling[ Draft Scaling Targets]
* Group Policy:Label ABNF[ Draft Label ABNF]
*
https://docs.google.com/a/midokura.com/document/d/1bZAwLk1EffE3ZU3QfzROZQ5kDdm6yScBcZADIFKFDbo/edit[Use
Cases]
*
https://docs.google.com/document/d/1u6fATpJaLBr4FtzCjPmNFxgky3o4vacwZcg5btKau8I/edit[Project
Sub Groups (OLD gdoc - still migrating data)]
* https://docs.google.com/file/d/0B0Pf6vxIzl4lVDZ3SUp6UGRzNHM/edit[GBP
model v0.982 (PDF)]
* https://wiki.opendaylight.org/view/File:SLBS%2BChains.pptx[Service
chain model proposal (PPT)]
*
https://docs.google.com/document/d/1qEpcN-Iftw5LBM_9i716Q4w3qi4tPWZq5lMO45sE1Ok/edit?usp=sharing[Future
Feature Wishlist brainstorming]
* Group Policy:RestAPI[ RestAPI]
* Helium
**
https://docs.google.com/a/noironetworks.com/spreadsheets/d/1Tp2dblnizQ4xi_4xcQgHP8dRPiqxdgC9pqlRdEuP6_I/edit#gid=0[Plan
of Record]
**
https://docs.google.com/a/noironetworks.com/spreadsheets/d/1IREsQFpuIKJCcVspjkNK3sUkinKh0a8tGpMRH6IRbEg/edit#gid=0[Release
Plan - Helium]
** Group Policy:Helium-Release-Review[ Helium Release Review]
* ** Group Policy:Helium-Release-Notes[ Helium Release Notes]

*Enterprise Access use cases* Enterprise Access, Dynamic Policy Use
cases https://wiki.opendaylight.org/view/File:Policy_Usecases.pptx

[[googleyoutube-information]]
== Google+/YouTube information

*
https://plus.google.com/u/1/b/111679737496425092024/111679737496425092024/posts[Google+
page - for Events and Hangouts on Air]
*
https://www.youtube.com/channel/UCZ9J9QECE82XOBsIQ9OtnxQ/feed?filter=2[YouTube
channel for Meeting Recordings and Tutorials]

[[all-subpages]]
== All subpages
