[[introduction]]
== Introduction

The group-based policy project defines an application-centric policy
model for OpenDaylight that separates information about application
connectivity requirements from information about the underlying details
of the network infrastructure.

This approach offers a number of distinct advantages, including:

* Easier, application-focused way of expressing policy: By creating
policies that mirror application semantics, this framework provides a
simpler, self-documenting mechanism for capturing policy requirements
without requiring detailed knowledge of networking.
* Improved automation: Grouping constructs allow higher level automation
tools to easily manipulate groups of network endpoints simultaneously.
* Consistency: By grouping endpoints and applying policy to groups, the
framework offers a consistent and concise way to handle policy changes
* Extensible policy model: Since the policy model is abstract and not
tied to specific network implementations, it can easily capture
connectivity, security, L4-7, QoS, etc.

See the information below to learn more about the project.

[[user-guide]]
== User Guide

Currently, the project is in the early stages. Check back later for
installation and operation guides.

[[developer-guide]]
== Developer Guide

[[documentation]]
=== Documentation

* Group_Policy:Building and Running[Building and Running]
* Group_Policy:Architecture[Architecture]

[[project-tracking]]
=== Project Tracking

*
https://trello.com/b/edPC5PAe/opendaylight-groupbasedpolicy-helium[Trello
- Helium Release]
*
https://trello.com/b/SlwZh0MI/opendaylight-groupbasedpolicy-featurebacklog[Trello
- Feature Backlog]
*
https://docs.google.com/a/noironetworks.com/spreadsheets/d/1Tp2dblnizQ4xi_4xcQgHP8dRPiqxdgC9pqlRdEuP6_I/edit#gid=0[Plan
of Record]
* Group Policy:Sub-Groups:Release_Plan_Helium[ Release Plan - Helium]

[[project-subgroups]]
=== Project Subgroups

The following project subgroups exist. See information on each of these
pages about periodic meetings

* Group Policy:Sub-Groups:STATUS[ Group 0: Status Meeting]
* Group Policy:Sub-Groups:ARCH[Group 1: Architecture]
* Group Policy:Sub-Groups:REQUIREMENTS[Group 11: Requirements]

[[other-documents]]
== Other Documents

These are some older documents that are left here for now for reference
purposes as they are phased out:

* Project Proposals:Group Based Policy Plugin[ Project Proposal]
* Group Policy:Scaling[ Draft Scaling Targets]
* Group Policy:Label ABNF[ Draft Label ABNF]
*
https://docs.google.com/a/midokura.com/document/d/1bZAwLk1EffE3ZU3QfzROZQ5kDdm6yScBcZADIFKFDbo/edit[Use
Cases]
*
https://docs.google.com/document/d/1u6fATpJaLBr4FtzCjPmNFxgky3o4vacwZcg5btKau8I/edit[Project
Sub Groups (OLD gdoc - still migrating data)]
* https://docs.google.com/file/d/0B0Pf6vxIzl4lVDZ3SUp6UGRzNHM/edit[GBP
model v0.982 (PDF)]
* https://wiki.opendaylight.org/view/File:SLBS%2BChains.pptx[Service
chain model proposal (PPT)]

[[googleyoutube-information]]
== Google+/YouTube information

*
https://plus.google.com/u/1/b/111679737496425092024/111679737496425092024/posts[Google+
page - for Events and Hangouts on Air]
*
https://www.youtube.com/channel/UCZ9J9QECE82XOBsIQ9OtnxQ/feed?filter=2[YouTube
channel for Meeting Recordings and Tutorials]

[[all-subpages]]
== All subpages
