Note: Work in progress.

[[conversion-rules]]
== Conversion Rules

[[data-node-container]]
=== Data Node Container

Each OpenDaylight_Controller:MDA:YANG_Metamodel#Data_Node_Container[Data
Node Container] is represented by Java interface which describes it's
structure. The structure is inferred from mapping rules for concrete
types of Data Schema Definitions.

[[leaf-node-definition]]
=== Leaf Node Definition

Instance of Leaf Node Definition in represented by property
(getter,setter) in the interface generated for the parent Data Node
Container.

[[leaf-list-definition]]
=== Leaf List Definition

Instance of Leaf List Definition in represented by property
(getter,setter) in the interface generated for the parent Data Node
Container.

[[container-definition]]
=== Container Definition

Instance of Container Definition in represented by property
(getter,setter) in the interface generated for the parent Data Node
Container.

[[list-definition]]
=== List Definition

[[choice-definition]]
=== Choice Definition

[[choice-case-definition]]
==== Choice Case Definition

[[anyxml-node-definition]]
=== AnyXml Node Definition

[[augmentation-target]]
=== Augmentation Target

Interface generated for YANG data node which is also Augmentation
Target, extends *Extensible* interface from
OpenDaylight_Controller:SAL:Evolution:API_Design_Principles,_Patterns#Pattern:_Extension_Interface_Pattern[
Extensible Interface] contract the Extensible interface is provided in
yang-binding artefact.
