https://tools.ietf.org/html/rfc6020|RFC[6020 - YANG - A Data Modeling
Language for NETCONF] defines syntax and semantics of YANG models in
concrete terms but does not describe common abstraction (or meta-model).
In order to better understand the YANG and to use it for code generation
and modeling we defined an set of abstractions (traits) which describes
various behavior of the YANG concepts and generated code.

[[data-schema-definition]]
== Data Schema Definition

[[leaf-node-definition]]
=== Leaf Node Definition

[[leaf-list-definition]]
=== Leaf List Definition

[[container-definition]]
=== Container Definition

[[list-definition]]
=== List Definition

[[choice-definition]]
=== Choice Definition

[[choice-case-definition]]
==== Choice Case Definition

[[anyxml-node-definition]]
=== AnyXml Node Definition

[[data-node-container]]
== Data Node Container

[[notification-definition]]
== Notification Definition

[[rpc-definition]]
== Rpc Definition

[[rpc-input-definition]]
=== Rpc Input Definition

[[rpc-output-definition]]
=== Rpc Output Definition

[[augmentation-definition]]
== Augmentation Definition

The extensibility of data models in the YANG is solved by introducing
concept of augmentations:

`  YANG allows a module to insert additional nodes into data models,` +
`  including both the current module (and its submodules) or an external` +
`  module.  This is useful for example for vendors to add vendor-` +
`  specific parameters to standard data models in an interoperable way.`

In YANG augment statement defines augmentation target, augmentation

[[augmentation-target]]
=== Augmentation Target

Augmentation Target is node in model, which could be extended by
augmentation which is defined by Augmentation Definition.
