[[the-toaster-tutorial]]
= The Toaster Tutorial

[[prerequisites]]
== Prerequisites

* Creating your app skeleton:
OpenDaylight Controller:MD-SAL:Startup Project Archetype[MD-SAL
Application Startup Project Archetype]

* Getting the toaster Tutorial code from the coretutorials repository:

` > git clone `https://git.opendaylight.org/gerrit/p/coretutorials.git[`https://git.opendaylight.org/gerrit/p/coretutorials.git`] +
` > cd coretutorials/toaster` +
` > ls`

[[getting-started]]
== Getting Started

At this point, you will see a set of directories/folders that correspond
to the Chapter links below. To work on a particular chapter, example
ch0: Welcome to POM Land And Karaf: move into the chaptor 0 directory,
and build it, then follow the wiki link corresponding to chaptor 0 below
and following the instructions documented on that wiki page:

--------------------------------------
> cd ch0-Welcome_To_POM_Land_And_Karaf
> mvn clean install
--------------------------------------

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch0[Chapter
0: Welcome to POM Land and Karaf]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch1[Chapter
1: Your Feature and Hello World]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch2[Chapter
2: The Toaster Yang Model]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch3[Chapter
3: Getting Data from MD-SAL Data Store (OnDataChanged)]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch4[Chapter
4: Putting Data into MD-SAL Data Store - Write Transactions]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch5[Chapter
5: RPCs]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch6[Chapter
6: Full implementation]

Controller_Core_Functionality_Tutorials:Tutorials:Starting_A_Project:ch0-old[Ch0-Keith
attempt]
