Welcome to the OpenDaylight Work Stream Wiki. This page information and
topics under active discussion within the OpenDaylight Technical
community.

[[meeting-schedule-and-logistics]]
== Meeting Schedule and Logistics

The Technical Work Stream meetings are held weekly on Mondays at 10:00am
PDT - 5:00pm UTC (-7:00 GMT). To participate in the next meeting, please
refer to the information below:

* Meeting coordinators: Madhu Venugopal, Brent Salisbury

[[teleconference-information]]
=== Teleconference information

Webex info:

` `https://meetings.webex.com/collabs/#/meetings/detail?uuid=M749G9M6E4A5JG72SD48WWG57F-9VIB[`Webex`
`Meeting` `URL`] +
` Meeting number:  196 592 514` +
`   ` +
` Audio Connection` +
` 1-855-244-8681 Call-in toll-free number (US/Canada)` +
` 1-650-479-3207 Call-in toll number (US/Canada)` +
` Access code: 196 592 514`

[[upcoming-meeting-agendas]]
== Upcoming Meeting Agendas

July 28th, 2014 (5pm UTC / 10am PDT / 1pm EDT / 10.30pm IST)

* *Karaf Testing Approach* (Luis Gomez, ~30 mins)

[[possible-future-topics]]
=== Possible Future Topics

* Helium Release
** General project expectations and plans here:
Simultaneous Release:Project Expectations[Simultaneous Release:Project
Expectations]
** Karaf tutorial _[Mathieu, ?? minutes]_
*** i.e., how to get started with Karaf
*** This wiki page can help:
Runtime:Karaf Features Guidelines[Runtime:Karaf Features Guidelines]
** Documentation tutorial _[Paul Zimmerman or Mathieu, ?? minutes]_
*** i.e., how to build docs and get them picked up
** Testing tutorial
*** i.e., how a project needs to run integration tests and system test
*** explain how pax-exam works (this wiki page can help:
OpenDaylight Controller:Integration Tests[OpenDaylight
Controller:Integration Tests]
*** System Test documentation:
CrossProject:Integration Group:CSIT[CrossProject:Integration Group:CSIT]
*** Using docker for better system/integration testing _[Madhu, ??
minutes]_
* New(ish) features
** YANG IDE Extensions for Eclipse _[Ed, ?? minutes]_
** XSQL for MD-SAL discussion _[Sharon, ?? minutes]_
*** Requested by Ryan Moats
** OpenFlow Plugin new features _[???, ?? minutes]_
** MD-SAL documentation and changes _[Devin Avery or Tom Pantelis, 30
minutes]_
** Clustering _[Moiz, 30+ minutes]_
** Notification Patterns _[Colin, 20 minutes]_
* What can we do with what we have?
** e.g., BGP as it's present in the controller _[Robert Varga?, ??
minutes]_
** e.g., MPLS _[???, ?? minutes]_

[[information-from-past-meetings]]
== Information From Past Meetings

*July 28st, 2014 meeting*

* Helium Testing in a Karaf environment (Luis Gomez)
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-28-17.01.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-28-17.01.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-28-17.01.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/SkxbdkyrncEkmmvWqX71UTGySOwUaAvtvlFAu8622cm00000[Link
to WebEx Recording]

*July 21st, 2014 meeting*

* Stable/Hydrogen (R3) : Ryan Moots : To get updates from all the
projects on and decide on the release date.
* Helium Documentation : Paul Zimmerman : To get updates from all
projects on the status / plan for Helium documentation for the
participating projects.
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call/opendaylight-meeting-tws_call.2014-07-21-17.02.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call/opendaylight-meeting-tws_call.2014-07-21-17.02.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call/opendaylight-meeting-tws_call.2014-07-21-17.02.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/3Ugwq4HmC7K4PX8RC7Kn7qUmQYvn_FsNb-d2QQ9Bpm400000[Link
to WebEx Recording]

*July 14th, 2014 meeting*

* Default OpenFlow plugin changeover. (Brief.)
* Helium Packaging and Karaf
* Notes:
**
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-14-17.04.html[Meetbot
Minutes]
**
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-14-17.04.txt[Meetbot
Minutes (text)]
**
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-07-14-17.04.log.html[Meetbot
Log]
*
https://meetings.webex.com/collabs/url/PyF31oHvdAzKKZWDs_Ftgcp5J9i1Tjys-4UkN2-rHHC00000[Link
To WebEx Recording]

*June 30th, 2014 meeting*

* HP OpenFlow plugin presentation
https://wiki.opendaylight.org/images/8/81/HP_OpenFlow.pptx[HP OpenFlow
Plugin Slides]
* HP Openflow Plugin Javadocs
http://colindixon.com/docs/hp-of-controller-api-docs.zip[HP Openflow
Plugin Javadocs zip file]
*
https://meetings.webex.com/collabs/url/ChDaZiRWUuI6TBZoecSc5Fhz2iR8i2Omlykb8nsL-5u00000[Link
to WebEx Recording]
* Notes:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-30-17.03.html[minutes
(html)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-30-17.03.txt[minutes
(text)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-30-17.03.log.html[log]

*June 16th, 2014 meeting*

* Security Analysis discussion - Meenakshi Kaushik
(CrossProject:OpenDaylight_Security_Analysis[presented wiki page])
* https://addd.webex.url.here/[Link To WebEx Recording]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_2014_06_16/opendaylight-meeting-tws_2014_06_16.2014-06-16-17.05.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_2014_06_16/opendaylight-meeting-tws_2014_06_16.2014-06-16-17.05.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws_2014_06_16/opendaylight-meeting-tws_2014_06_16.2014-06-16-17.05.log.html[Meetbot
Log]

*June 9th, 2014 meeting*

* Automated Release mechanics for Helium - Giovanni Meo (20 mins)
https://wiki.opendaylight.org/images/8/84/OpenDaylight_AutoRelease_TWS_Presentation.ppt[slides
(pptx)]
* Automated Robot Integration test to verify FlowMod installation -
Chris O’Shea & Luis Gomez (20 mins)
*
https://meetings.webex.com/collabs/url/-Rczbgjf3Vy5cu_BKZ8n9WMXRw9VpAt2UNihdUxK9Bq00000[Link
To WebEx Recording]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-09-17.03.html[Meetbot
Minutes]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-09-17.03.txt[Meetbot
Minutes (text)]
*
https://meetings.opendaylight.org/opendaylight-meeting/2014/tws/opendaylight-meeting-tws.2014-06-09-17.03.log.html[Meetbot
Log]

*June 2nd, 2014 meeting*

* Karaf in OpenDaylight & Hands-On demo on developing ODL components for
Karaf Runtime - Mathieu Lemay (40 mins)
** Mathieu's slides for Karaf discussion
https://wiki.opendaylight.org/images/7/7e/Karaf-Discussion-TWS-June2-2014-Lemay.pdf[Karaf
Slides for June 2 TWS Call]
* Multi-Tenancy Discussion - David Lenrow (20 mins)
** Slides:
image:TWS-ODL-tenancy-2014-06-02.pptx[TWS-ODL-tenancy-2014-06-02.pptx,title="fig:TWS-ODL-tenancy-2014-06-02.pptx"]
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_4A29F92901EC0A119745F3BCDA243EF4FF354C4C2B44A58E8845A2AF8DBF9D4ADEB7DDDE355C17C339A62A6E1810C34AD57DAD761A6C28260D5C74AE6DEA7523230AB231CB83018091A786A1DFA0F3A9_446AB28F309C6F12F503FEFBF548EAE1B0762856[Link
To WebEx Recording]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.txt[Meetbot
Log]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.log.html[Meetbot
Minutes (Text)]

*May 19th, 2014 meeting*

* Bringing the community together around MD-SAL - Devin Avery, Brocade
*
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_4A29F92901EC0A119745F3BCDA243EF4FF354C4C2B44A58E8845A2AF8DBF9D4ADEB7DDDE355C17C339A62A6E1810C34AD57DAD761A6C28260D5C74AE6DEA7523230AB231CB83018091A786A1DFA0F3A9_446AB28F309C6F12F503FEFBF548EAE1B0762856[Link
To WebEx Recording]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.html[Meetbot
Minutes]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.txt[Meetbot
Log]
*
http://meetings.opendaylight.org/opendaylight-meeting/2014/tws_call_devin_avery_leading_a_discussion_on_the_md_sal/opendaylight-meeting-tws_call_devin_avery_leading_a_discussion_on_the_md_sal.2014-05-19-17.04.log.html[Meetbot
Minutes (Text)]

*April 28th, 2014 meeting*

* Mathieu Lemay, Jamie Goodyear & Heath Kesler will introduce Karaf and
the work done on ODL.

https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_B3DAD90D79410E767FF208B51F829BF1027F4F4F8CB6EBCE6A251B581F0C29EDCE42FA79AFF0648AE687CF5CFC0C4892B5541975A935E82FA5968765D24A6EBCCD12A40ECB24A83D2ABCD80A63D18FCE_216A64CCBA67F87A6EE90C4014D13BB3412A6661[Link
To WebEx Recording]

*April 14th, 2014 meeting*

* Mike Dvorkin leading the Data Store discussions that was implemented
as part of Cisco APIC.

https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.html[Meetbot
Minutes] +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_95F44C56BED325D9B29D7DAFB457968F72A6EE5E9B0409F892B95FBB3CE4C8AAE1F0362903921F3513D7AD94CE340F2162C36D8EEBEBA561426B7804F183E45A38D8FD4955CF9033333FF79951CEFC7E_0E238C7D8649BD7DEC5D29E015752C1EDAAC13D6[Link
To WebEx Recording]

*April 7th, 2014 meeting*

* Raghu will debrief a proposal that came from the Hackfest to cleanup
the Maven POM file dependency hierarchy and version management.
* Review the even swap / evaluation of data store options from the
HackFest TODO last week.
* Continuing Data Store Discussions. Mike Dvorkin will present what
Cisco has done with ACI/APIC.

https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-07-17.05.log.html[Meetbot
Minutes] +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_6BCD594A95DDB8CE86F0ECE4494557D4E3C8AD5F2F5DE60A2484291B2D3B99BF5EB88FDE80AB609A43EB84183AC645691E4191A71811744B196050360EAA9E2BB13E84BF7F3474FB05EDA609E7161085_71C516A2D08151665C2F2F9F2177DF5E69E7703A[Link
To WebEx recording]

*March 31st, 2014 meeting*

* Sadly, no minutes, nor recording are available for this meeting.

*March 24th, 2014 meeting*

* Continuing MD-SAL and Data Store Discussions.

http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-24-17.10.html[Meetbot
Minutes] +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_13B7AE9595BE94AAA247FC3C77CCAD391A56A5969C2B4688AB524AF35587B6E0884D739FC901591557F0B600C06DFD168B9F724AE09E934DEE29E58062B1B4915895040CF19FAE96AA505D5755E03466_171A781DD284D7DDCF1F8736CE080935DA412620[Link
To WebEx recording]

*March 17th, 2014 meeting*

* More MD-SAL Discussion

Link to Meetbot Minutes - TBD +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_ECA586516CAF1C2E31254D05A72051E32B2EE75011D20F0CC686460EB1BA6FD9154E003D360359229CB7C1AE4F97DEB47DDE6AAF81F99CD6B16B766799BE0AEE1CABED9F1C44306F0ACA6BD0C2022569_1A1EC2334831025AB5E402108203D6D67966CD81[Link
To WebEx recording]

*March 10th, 2014 meeting*

* MD-SAL Deep-Dive. Part-2 : Jan & Tony
* Community interest on future TWS call topics

https://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-03-10-17.17.html[Link
to Meetbot Minutes] +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_E0D1259988051C279413EAFB5482D540DB84A33F37F252EF0C0A54DDB42AEEE3D8B362126CBF962A6E40FA077B665A66A623CA02D43B9F9C615F39B129A7404F82090FCB8638E8495CA24A9C87220B7F_3B6F8F043C63CE1D48DAD60CBFBB846A348C68F0[Link
To WebEx recording]

*February 24th, 2014 meeting*

* Proposal on East-Friendly 2nd alternating TWS slot
* MD-SAL Deep-Dive. Part-1 : Jan & Tony
* Community interest on future TWS call topics

https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_DA75E4E305EE81E2ABA2E403047DBC928841028FEF35F6A97B2326BE7E1632CFA75A3C103FB45F1A09A6C09EE40EB1D0EC6EB2BC3CFA8A8C19F22E72485EB657D61592972352F3DB4553FDEAD6DD8642_15A04A44F281A455D23C1BADDD970920E4DB282F[Link
To WebEx recording]

*January 20th, 2014 meeting*

* System Test VM usage and demo (Luis Gomez)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_FED7CE707B5D20CAE99139DC96D4CB68540FC96221940AA933A1F72075506BE8BE044929D0175C147B0EB1D63AED5B1A45F483FA7A1B8B7AC1ACCD4C118654D359E9B10ED33D737225FA3896573D1B8F_A7A851A33F5E7FFEA1AF67801352B064AFFF90E3[Link
To WebEx recording]

*December 16th, 2013 meeting*

* Project proposal overviews
** OpenDaylight DPDK Switch (Craig Griffin, Chris Buerger)
** Logical switch and FC SAN proposals to be rescheduled

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_C3ED3FC3B3FEA5A99CEA034A87E6D420F21C0D494FF3DA87EA21F9F582972ACE610A9BD3FFE2F01EE6A2DB2A3EAA6D49029957B7ABCC2DA9220A0998CCABD8E64818AD9AD8002D48CF79AD9B32E03F28_9C6A1C960720E6A60F854393B52B4724A5FF41EA[Link
To WebEx recording]

*December 2nd, 2013 meeting*

* Discuss outstanding Hydrogen release issues
** system test
** base edition status
** configuration for each edition
** documentation expectations
** project-specific issues or questions

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_27682AE8268E42E34FB44AA2C1A5E071FEEB992FE4712A2C628C2D0604F6F20C6AA0E8F89795A6AC140B2EE765BBA03AF1E0561005A3AB809DFBD33F5C4A010B33EDC6EAC9FA7403B206FE8CD2BF5B5C_DB979D134807EC3FACD2423C8C80E59213BD97AE[Link
To WebEx recording]

*November 18, 2013 meeting*

* Update on OpenStack plugin / integration (Kyle Mestery) (pushed from
last week's agenda)
* Other topics

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_D5286158FDF02ADDDE40E658C4D705F927D846239CCC182C53B10436E9D9F485B0D8A30CC8453E71F11D2D478CD477D0BF2412BE5312CEAEFB674E6D190C07A79848712A1B7827358EA8030E6A134BDE_257843227B4FA69E5B6E215983E79F686528C4AF[Link
To WebEx recording]

*November 11, 2013 meeting*

* Northbound API conventions and organization
* Other topics
** update on OpenStack integration
** OpenDaylight summit

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_5DC138D5054BF13C2415989FBD53662E9902A7BF3B29C45B935DFB6F93D24E7B9585274B509DF5007AC72BA706815BFFD95EA813EE402D4A38C91967E3DEE550EFF5EDFB84ACA2216A65D60633354CDB_BFDF3C4F77EF1673D3B8BF4545342B31596D2567[Link
To WebEx recording]

*October 28, 2013 meeting*

* OpenFlow / OF-Config modeling (Jan Medved)
* Misc topics
** Securing access to interfaces
** Nexus / build

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_025B15A28E12BB05BAF3865737DCE5D7E5490FFEEA86E4A83A405228F23157E30007C6213CFB54DCDFB68B0C5C34F107A1E9D7F1FEA1FDEF364B6115A2F4AA79B2062CFDF08BC5A880B91F2006F4EAC1_77DDE61D5793F30BAD2F1CAA0FE5A30102D90920[Link
To WebEx recording]

*October 21, 2013 meeting*

* MD-SAL migration (contd.)
* OpenStack Neutron integration (controller service and plugin) (Ryan
Moats / Kyle Mestery)
* Hydrogen release issues discussion

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_80BB2ECECE6A634780438DB51C0CEDCF8273D2CAAFE3321B1EA915C71267C72B00C9FFE657C2D9959AA60B70EFE1B9F590E4BE0874A5343ED2D726C12ED069377A1CB85F6387EB05BDD9158E269EAA20_C3F700D8F6F4CDD6D942EDC0D2E31FA4B81895BF[Link
To WebEx recording]

*October 14, 2013 meeting*

* MD-SAL migration plan
* Hydrogen release issues discussion

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_9F035A7D5E5A74573065477402136E9FACBC3DEA580397F4C38CB3DD83C15A57028A1F9DD92323B27094EDD93C6825B9CC2CA25DF7D00BAE27E5B7713A6593AF6094B3CC5A272FE672A707AA76EAA53D_C11ECAE108DDDD28855084B3202D9CD3AE0AB4F0[Link
To WebEx recording]

*October 7, 2013 meeting*

* dlux UI project overview (Endre Karlson)
* Hydrogen milestone status review (project leads / members)

media:TWS2013 10 07.mov[Link To Webex recording] +

*September 30, 2013 meeting*

* ONOS Network OS and ON.Lab (Pankaj Berde)
(https://wiki.opendaylight.org/images/d/dc/ONOS_ODL_TechTalkv7.pptx[slides])

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_2A3DDB8357A8007A512BC6E25B7388024B461A95F0334D1C7528444DFF5A9005B1EE1E888F4D2EF2B7C8D0DF16D3E960BC67E938EB86FA3EDEDF9F1EC1D9CFB4F051DAD61E5945C1742A7A0B266582E5_C1BFAA363E6792B0EA6E4E30CCC82C79C6DA6D9E[Link
to WebEx Recording]

*September 23, 2013 meeting*

* OpenStack integration -- summary of hackfest discussion (Anees Shaikh)
(https://wiki.opendaylight.org/images/8/87/OpenStack_ML2_hackfest_summary_Sep2013.pdf[slides])
* OpenStack / Neutron ML2 plugin structure (Kyle Mestery)
(https://wiki.opendaylight.org/images/e/e9/ML2_Overview.pptx[slides])
* OpenStack / Neutron API service and SB SAL extensions (Ryan Moats)
(https://wiki.opendaylight.org/images/b/b8/Neutron_OpenDaylight.pdf[slides])

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_356CDEA77B883C41A525BC75A4DBB5BE321DDC405234D588125CB76F462648023F72A496111AB0EA63DFB50FA912719D5AE33C762BD343D8AFBBDB73041B92F6301074DF2160AE1410B7E34259E071CF_D7F7DD2274298B6CF8A2F21B0F2CBAC52F8CA808[Link
to WebEx Recording]

*September 16, 2013 meeting*

* Integration Testing / release plan (Luis Gomez)
* Release vehicle discussion (Ed Warnicke)
* vHackfest plan (Ed Warnicke)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_D1719459C0E8C05B75BF67DEED18584343845AFE2BC1A88C45D69373DA611616E2C7E738F36291240FC8B5A54846558335D13F44319793AEF8761E9F9305D5C0B90EAB5CAB99A8F3663136E39FE06F7C_BFFD6A758E372ACB5837DDDAEB36F16DA8AD5E73[Link
to WebEx Recording]

*August 26, 2013 meeting*

* Model-Driven SAL code walkthrough (Tony Tkacik)
(https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL[reference])

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_48C3AD91309F08614D69F9C21940804DE06FFB9D06CDCDBEAAC894BDC5A5E8FE7333528919D7E19D172FD17013D70E1BF8889214B3483D346B8F1550D0D12E0EBE8A5E4C03CD29DDE6CCE3483B1FAB38_1348A9E3E77962C327E3BACADF269451631C0F67[Link
To WebEx Recording]

*August 19, 2013 meeting*

* Milestone M2 project updates (OpenDaylight project leads / committers)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_48C3AD91309F08614D69F9C21940804DE06FFB9D06CDCDBEAAC894BDC5A5E8FE7333528919D7E19D172FD17013D70E1BF8889214B3483D346B8F1550D0D12E0EBE8A5E4C03CD29DDE6CCE3483B1FAB38_1348A9E3E77962C327E3BACADF269451631C0F67[Link
to Webex Recording]

*August 12, 2013 meeting*

* Controller performance / scalability (Muthu Kothandaraman)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_7FE3CB57EB8A6415DE4F0E8B9A554619B675C2A5F6E312B24E4DCF15F9219629185DB5356988AD98E1389F004765A255C0C3C821EEEBC85DB9668FC4A51BB8F8632A08A07AA5E8556F77542F3476580A_C2B3D6380B880FEC97D7A180A3D376E6A225058D[Link
to Webex Recording]

*August 5, 2013 meeting*

* Call for Speakers for the Mini-Summit (Phil)
* SAL Ethernet Plugin project proposal overview (Tzi-cker Chiueh, ITRI)
(slides)
* Controller state persistence (Colin Dixon to recap hackfest
discussion)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_A38A885F6F357EB6D5320A6008507BF0B8224BF5801F5CBAB66A1157C497937FAA2E1746083A51F53273D188272E1292DC5A324239B691AF66CF7FB2E171F95808BBF325068621083D0F9E900EBA69DA_0DF61A3256D45A9B2E8B142244D8A9691D3EEA29[Link
to Webex Recording]

*July 29, 2013 meeting*

* OpenFlow 1.3 protocol plugin design discussion (Chris Price)
(https://wiki.opendaylight.org/images/9/9a/ODL_OFPI_Project.pdf[slides])

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_085DAFF1B7682A4E755096AB002C208B5B9E2C9D04A180A74D5D324E90B234B7CAF900D56661D461598A10A12727B1178B410BEDF63210319B4A4E6D1767A076A82B843DF4CE52D97A2F1E6687F4E499_256480FA6644819A951AEECE05AAB42A4556A073[Link
to Webex Recording]

*July 15, 2013 meeting*

Project proposal overviews

* OVSDB integration (Brent Salisbury)
* Affinity metadata service (Dave Lenrow)
* OpenFlow southbound plugin (Chris Price)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_87AC2C647FCD5FA2DCF1E6C8FB419A1C3C6A05E65D2EE1F9EE97C7F6FC15F136701AC807BACCC9A4E33807CA602D9DE99747804DE0220AB36BF709D66D219111EF071879BD60C93A73E7FED60C862E75_7EA9221D0C181F8630DC779394F8152D02792896[Link
to Webex Recording]

*July 8, 2013 meeting*

Project proposal overviews

* OpenDaylight LISP Mapping Service (Gal Mainzer)
(https://wiki.opendaylight.org/images/2/28/2013_07_08_-_ODL_-_Project_proposal_for_TSC.pptx[slides])
* OpenDefenseFlow DDoS mitigation system (Benny Rochwerger)
(https://wiki.opendaylight.org/images/f/fc/130708_-_OpenDefenseFlow_Proposal_Overview.pdf[slides])

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_814DB8FB4E0C34B3F338B379B55367C9BA11E7F51214ED4084D3E01297F2B3D74E6B60F0D566807D5B783C7B342ACE8369DF7755DE324EE8BEFCBE7D4BAF6F06A0AC48DBD196B50C7EFD49FD1ADC7079_E2D943E9545C6951A567ECB680FA79701BDA4C0D[Link
to Webex Recording]

*June 24, 2013 meeting*

* Infinispan / JBOSS roadmap and discussion (Shane Johnson, Chris
Wright)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_CBF808808BE49552E3997CAEB315FDD0621676CC88ABCF39B9AF4A80C31247908473AEAEE3EE2829F742B523CC963B3376A431AA855DDBC875DCD7447A80DF5244B24DECA68F1E24BA41322889675582_735EF8AA8E51DEC83EEC07B74A4FBB2454A540AD[Link
to Webex recording]

*June 17, 2013 meeting*

* Open DOVE proposed contribution
(https://wiki.opendaylight.org/images/5/5a/Open_DOVE_for_OpenDaylight_tech_v2.pdf[slides])
(Jay Kidambi, Anees Shaikh)
* Simultaneous release plan discussion

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_A6A598FD5FA9049CAC9EF71F544BFE7209DBD1CCF47523F53E617B586F97D9BF62C7770026A0CB124B05EEE5133DD0FBD1EEE6A66E7C0ADB78E6CB8B03245BFFA2221312243EFDCCBE776D18F007CE19_1DA37C2EDE19BCAA30D0BF07184573AE610DFA10[Link
to Webex recording]

*June 10, 2013 meeting*

* Update on last week's Hackfest workstreams and progress (Chris Wright
and hackfest participants)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_0FE91D32F0D887D469CC92562926000951877F3DC688FC34BEEE208DBB7A9617ADF293FB9542B2017175704423CB238C4D63E4B1E7673C4A7A78B15A55992F392BFBCFDE31E92BE13A9C16B5550403CA_5A2DBF9268E6EB09F2181FAD5E9F6D13ACF2CCC7[Link
to Webex recording]

*June 3, 2013 meeting*

* Overview of VTN project proposal (Su-hun Yun)
(https://wiki.opendaylight.org/images/d/d9/NEC_VTN_Model_overview_v3.pdf[slides])
* Update on Jun 6-7 hackfest agenda / plan (current agenda posted
https://wiki.opendaylight.org/view/HackFestAgenda[here]) (Chris Wright)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_DBD9B58EFDBDF1C7A326F9921FD5206B631D23542EF7E45EE856DE53EDE1E164EE2A50ED230818F3E647D33D0D8B653A56E41310BDF4078369369BAA6A977AF36E0733A108C1E6476FA5B24B39B666E9_4A90F8BCC1D89A23CE28B6A2432AD38C57360CF8[Link
to Webex recording]

*May 20, 2013 meeting*

* review / summary of May 16 TSC meeting (Dave Meyer)
* Discuss next steps in implementing D-E proposal
** review specific host tracker proposal
(https://wiki.opendaylight.org/view/D-E_Proposal:Host_Tracker_Plan[link])
** gaps in host tracker proposal (Rob Sherwood)
(https://wiki.opendaylight.org/view/File:OpenDaylight_Technical_Call_2013-05-20.pptx[slides])
** overview of host tracker adaptor bundle implementation (Ed Warnicke)

https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_0C05EA359BE5675FF509F880A6D2760974B6216657B72722507024A4998DE370E0890EACC100E62B5EB12A4F89AF837D92A9A833D318D925609C495A3A232FA8EB1B408F9F025A25930531F80395FCC4_5EC00E095B65156E7C43F138FA9BD861E394EFFA[Link
To Webex Recording]

*May 13, 2013 meeting*

Review of Layered API controller merge proposal +
Rob Sherwood (Big Switch) +
Link to
https://wiki.opendaylight.org/view/File:LayeredAPIProposal.pdf[proposal]
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_A5C22AF11B0DE9836430EA26D13A55E570F7E5A72C5AA5B961A58120174DB85771690A7052A4F0B6AE9141D9AFA3E309F88A99CF0686D34AF69F3F30B3F930953BDC59620400E1C0389E62A84762942C_372CFB3AC0137D2D9680D22C4405884D7D3698EF[link
to Webex recording]

*May 6, 2013 meeting*

Analysis of functionality in existing controller codebases and
recommendations for merged controller +
https://wiki.opendaylight.org/view/Dixon-Erickson_OpenDaylight_Merged_Controller_Proposal[Link]
to document +
Colin Dixon (IBM), David Erickson (Stanford) +
https://meetings.webex.com/collabs/files/viewRecording?encryptData=0_AFA8518F9238850AFA327990E4578F7E898139E4920DE8F7AECEB6AC7AA09E319870B834FDB951BB9BB3B1F477A8DFA78950F7EE3D575C6477627A8D6B8111B8392FCE34252FD4245CD22A4EC3254925_C9A4611D20B79C78F09EAC9D8ED5C1156D95B227[link
to Webex recording]

*April 29, 2013 meeting*

Discussion and demo of model-driven approaches for an extensible
southbound protocol abstraction layer. +
Jan Medved, Tony Tkacik (Cisco) +
Model-driven SAL Media:MDA_SAL.pptx[slides (pptx)]
https://linuxfoundation.webex.com/linuxfoundation/lsr.php?AT=pb&SP=EC&rID=6781737&rKey=259ae7e837db1b87[link
to Webex recording]

Closely related talk on BigDB given earlier by Rob Sherwood +
Media:OpenDaylightBigDB.pptx[slides],
https://cisco.webex.com/cisco/ldr.php?AT=pb&SP=MC&rID=66883207&rKey=6e22c6e620dfbde9[link
to Webex recording]

*April 22, 2013 meeting*

Agenda: Media:Apr_22.pptx[agenda slide (pptx)]

Meeting summary:

This was primarily a planning / kickoff meeting for the technical
workstream to agree on meeting logistics and set a few topics for
upcoming meetings (see the agenda slides for topics that were
discussed).

* Agreed that we will have once per week meetings on Mondays at 1p PT
(until we find that we need to change the scheduling).

* Dave Meyer (TSC chair) gave an overview of the Open Daylight developer
track sessions at the recently concluded Open Networking Summit.

* Discussed some upcoming topics:
** next meeting will cover model-driven service abstraction layer
** Ericsson team agreed to present in upcoming weeks on proposed
contributions
** Dell team agreed to provide an update on SDN standardization effort
they are leading in OMG in upcoming weeks
** NEC team agreed to present an overview of their proposed project on
Virtual Tenant Networking (VTN) in upcoming weeks
** Incorporating non-EPL code in Open Daylight : The ODP board has
commissioned a subcommittee to look at IPR and licensing issues. Benson
Schliesser agreed to report back to the technical workstream on this
from the board.
** Discussion and agreement that tech workstream should tackle the issue
of integrating non-Java code, driven by specific module use cases (e.g.,
Python CLI), or language use cases
** Colin Dixon, David Erickson and others to organize some discussions
with contributing teams on a framework for resolving overlapping base
controller codebases. Will report back to the tech workstream as this
progresses

