[[install]]
== Install

Use this method to install OpenDaylight using the yum repo:

`  1. Install the yum repo` +
`  Download the repo file from:` +
`  `https://nexus.opendaylight.org/content/repositories/opendaylight-yum-fedora-19-x86_64/rpm/opendaylight-release/0.1.0-2.fc19.noarch/opendaylight-release-0.1.0-2.fc19.noarch.rpm[`https://nexus.opendaylight.org/content/repositories/opendaylight-yum-fedora-19-x86_64/rpm/opendaylight-release/0.1.0-2.fc19.noarch/opendaylight-release-0.1.0-2.fc19.noarch.rpm`] +
`  Install the repo file:` +
`  sudo rpm -Uvh opendaylight-release-0.1.0-2.fc19.noarch.rpm` +
`  ` +
`  2. Install opendaylight` +
`  Base Edition: sudo yum install opendaylight` +
`  Virtualization Edition: sudo yum install opendaylight-virtualization` +
`  Service Provider: sudo yum install opendaylight-serviceprovider`

Use this method if the OpenDaylight packages have already been
downloaded:

`  sudo rpm -Uvh /path/to/rpms/*.rpm or` +
`  sudo yum localinstall /path/to/rpms/*.rpm`

[[enabledisable]]
== Enable/disable

`  sudo systemctl enable opendaylight-controller.service` +
`  sudo systemctl disable opendaylight-controller.service`

[[startstop]]
== Start/stop

`  sudo systemctl start opendaylight-controller.service` +
`  sudo systemctl stop opendaylight-controller.service`

::
  _Note(1): to get the osgi console: telnet 127.0.0.1 2400._
  +
  _Use ctrl+] to break from the osgi console. Then quit to exit the
  telnet session._
  +
  _Note(2): to reach the OpenDaylight page use the following url:
  http://127.0.0.1:8080/_

[[configuration]]
== Configuration

Edit the sysconfig file to change the type of edition:

`  sudo vi /etc/sysconfig/opendaylight-controller`

Set ODL_DIST to the desired edition, e.g.,

`  ODL_DIST="virt-ovsdb"`

::
  _Note: to use a virtualization or service-provider edition requires
  that the compatable rpm be installed._

Use the following table to select the edition:

::
  _Note: only the base and virt-ovsdb editions are supported when
  installed via rpm_

[cols=",",options="header",]
|======================================
|Edition |Value
|base |base
|virtualization ovsdb |virt-ovsdb
|virtualization vtn |virt-vtn
|virtualization opendove |virt-opendove
|virtualization affinity |virt-affinity
|service provider |sp
|======================================

Any additional options, e.g., -of13 and -debug can be specified like
this:

`  ODL_OPTS="-debug -of13"`

The default installation assumes the Base edition with OpenFlow 1.0: +
ODL_DIST="base" +
ODL_OPTS="" +
 To use the OVSDB Virtualization edition with OpenFlow 1.3, use the
following values: +
ODL_DIST="virt-ovsdb" +
ODL_OPTS="-of13" +

