[[vm-description]]
== VM description

* Intalled SW: http://openjdk.java.net/[Java 1.7 OpenJDK],
http://www.opendaylight.org/software[OpenDaylight release
distributions], http://mininet.org/[mininet 2.1.0],
http://openvswitch.org/[Open vSwitch 2.0.0],
https://github.com/CPqD/ofsoftswitch13[CPqD ofsoftswitch13],
http://code.google.com/p/robotframework/[Robot framework 2.8.3],
https://git.opendaylight.org/gerrit/gitweb?p=integration.git;a=tree[integration
test scripts],
https://wiki.opendaylight.org/view/OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator[VTN
coordinator], http://www.wireshark.org/[Wireshark],
* VM configuration:
** odl_server: Ubuntu 13.04 server, 8GB HDD, ova file size=2GB
** odl_desktop: Ubuntu 13.04 desktop (GUI), 20GB HDD, ova file size=3GB

[[installation-procedure]]
== Installation Procedure

[[prerequisites]]
=== Prerequisites

* https://www.virtualbox.org/[Virtualbox] (if you use
http://wiki.qemu.org/Main_Page[QEMU] or VMware you can find instructions
online on how to covert ova file to these)

[[installation-steps]]
=== Installation steps

1.  Download the VM ova file from link above
2.  Open VirtualBox and do import appliance
3.  Configure the VM with the following recommended settings
* _Processor:_ 4x CPU if you plan to run the controller in the VM, just
1 if you don't
* _RAM:_ 4GB if you plan to run the controller in the VM, or just 1GB if
you don't
* _Network:_ 1x NIC, bridge mode is recommended, otherwise NAT (to share
your Internet connection) or host-only (creates internal network)
4.  Start the VM
5.  Login with mininet/mininet
6.  Open README.txt

[[using-the-vm]]
== Using the VM

This VM can be used in two scenarios:

* Self contained: Both OpenDaylight and the mininet network emulator
will run in the this VM
* Network Emulator: The mininet network emulator will run in this VM,
and OpenDaylight can be run on an external machine or another VM

