[[config-subsystem]]
= CONFIG SUBSYSTEM

[[code-name]]
== Code Name

odl-config-all

[[description]]
== Description

Config subsystem core management.

* Overview & Design Architecture:

OpenDaylight_Controller:Config:Design[Overview & Design]
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:Config_SubSystem[Config
subsystem overview]

* Configuration:

Config subsystem is the configuration manager, its configuration and
startup is automatic

[[bundles]]
== Bundles

[[upstream-dependencies]]
== Upstream Dependencies

* odl-config-api
* odl-config-netty-config-api
* odl-config-core
* odl-config-manager

[[downstream-dependencies]]
== Downstream Dependencies

Each project and feature in the ODL universe that is configured and
managed by the config subsystem.

[[incompatibilities]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness]]
== Network Intrusiveness

None.

[[recommended-karaf-features]]
== Recommended Karaf features

Recommended features for karaf testing:

* odl-netconf-connector-all
* odl-restconf-all

[[how-to-test]]
== How to test

Testing this feature alone would be quite challenging using an ODL karaf
distribution and is probably worthless. This feature would be tested
extensively indirectly in the tests for
https://wiki.opendaylight.org/index.php?title=Opendaylight_Controller:Lithium:Netconf:Integration_Test&action=submit#Feature_ODL-NETCONF-CONNECTOR-ALL[Netconf
connector tests].

[[performancescalability-concerns]]
== Performance/Scalability Concerns

So far, config subsystem was able to handle 20k and more instances of
configurable modules present in a single instance of ODL.

[[config-persister]]
= CONFIG PERSISTER

[[code-name-1]]
== Code Name

odl-config-persister-all

[[description-1]]
== Description

Configuration pusher/persister for config subsystem.

* Overview & Design Architecture:

OpenDaylight_Controller:Config:Design[Overview & Design]
OpenDaylight_Controller:MD-SAL:MD-SAL_Document_Review:Config_SubSystem[Config
subsystem overview]

* Configuration:

OpenDaylight_Controller:Config:config.ini[Static configuration for
persister/pusher]

[[bundles-1]]
== Bundles

[[upstream-dependencies-1]]
== Upstream Dependencies

* odl-config-persister
* odl-config-startup
* odl-config-all

[[downstream-dependencies-1]]
== Downstream Dependencies

This feature stands on its own and has no direct dependencies, but all
downstream features that leverage the config subsystem and provide
initial config could be considered dependencies.

[[incompatibilities-1]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness-1]]
== Network Intrusiveness

None.

[[recommended-karaf-features-1]]
== Recommended Karaf features

Recommended features for karaf testing:

* odl-netconf-connector-all
* odl-restconf-all

[[how-to-test-1]]
== How to test

Testing this feature alone would be quite challenging using an ODL karaf
distribution and is probably worthless. This feature would be tested
extensively indirectly in the tests for
https://wiki.opendaylight.org/index.php?title=Opendaylight_Controller:Lithium:Netconf:Integration_Test&action=submit#Feature_ODL-NETCONF-CONNECTOR-ALL[Netconf
connector tests].

[[performancescalability-concerns-1]]
== Performance/Scalability Concerns

Category:Integration Group[Category:Integration Group]
