[[md-sal-binding-in-memory]]
= MD-SAL Binding & In-Memory

[[code-name]]
== Code Name

odl-mdsal-broker

[[description]]
== Description

OpenDaylight Controller:MD-SAL[OpenDaylight Controller:MD-SAL]

[[bundles]]
== Bundles

See feature description in repository up-to-date information

[[upstream-dependencies]]
== Upstream Dependencies

Yangtools, Config subsystem (precise info is in repository in feature
description).

[[downstream-dependencies]]
== Downstream Dependencies

Most of offest one and offset two projects.

[[how-to-test]]
== How to test

Execute mvn clean install in opendaylight/md-sal/sal-binding-dom-it for
JUnit integration tests.

Some of test scenarios defined in:

https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Testing

[[performancescalability-concerns]]
== Performance/Scalability Concerns

[[incompatibilities]]
== Incompatibilities

None

[[network-intrusiveness]]
== Network Intrusiveness

None

[[md-sal-clustering]]
= MD-SAL Clustering

[[code-name-1]]
== Code Name

odl-mdsal-clustering

[[description-1]]
== Description

OpenDaylight_Controller:MD-SAL:Architecture:Clustering
Running_and_testing_an_OpenDaylight_Cluster

[[bundles-1]]
== Bundles

See feature description in repository up-to-date information

[[upstream-dependencies-1]]
== Upstream Dependencies

Yangtools, Config subsystem (precise info is in repository in feature
description).

[[downstream-dependencies-1]]
== Downstream Dependencies

Most of offest one and offset two projects.

[[how-to-test-1]]
== How to test

[[performancescalability-concerns-1]]
== Performance/Scalability Concerns
