This page is to publicly record requests for exceptions to the Helium
API Freeze that took place as part of the M4 Milestone of the
Simultaneous_Release:Helium_Release_Plan[Helium Simultaneous Release
Plan]. The full process is describe on
Simultaneous_Release:Helium:Suggestions_for_Post_API_Freeze_Exception_Handling[this
page].

To request an exception, please copy from the link:#Template[template]
below and the put it in the link:#Requested_Waivers[Requested Waivers]
section until the waiver has been granted at which point, move it to the
link:#Granted_Waivers[Granted Waivers] section.

[[granted-waivers]]
== Granted Waivers

[[ordered-interface-change-waiver]]
=== Ordered Interface Change Waiver

[[core-details]]
==== Core Details

* API Name: getOrder
** Containing repo: controller
** Path to the API:
opendaylight/md-sal/model/model-flow-base/src/main/yang/opendaylight-action-types.yang
* *RECEIVING PROJECT*: controller
* *API PROVIDERS*: controller
* *API IMPLEMENTORS*: controller
* *API CONSUMERS*: openflowplugin
* Other *IMPACTED PROJECTS*: NONE
* State: *WAIVER GRANTED*

[[comments]]
==== Comments

[[description-of-the-api-change-and-rationale]]
===== Description of the API Change and Rationale

The patch, just, creates an Interface named Ordered for all those models
which can be ordered.

The interface is created by adding a new grouping to the yang file, and
is done for action list, instruction list and table-feature-properties.

This patch would help to create a generic Order Comparator for those
elements where order can be specified by the client. There is NO API
change.

The API calls in controller-dependent projects would NOT have to change,
as this change would remain transparent to them.

Dependent Patch : https://git.opendaylight.org/gerrit/#/c/9214/ in
openflowplugin.

Since this is yang related change, requesting a waiver.

[[feedback-from-impacted-projects]]
===== Feedback from *IMPACTED PROJECTS*

[[notification]]
==== Notification

* Filed bug: https://bugs.opendaylight.org/show_bug.cgi?id=1508
* Sent e-mail:
https://lists.opendaylight.org/pipermail/openflowplugin-dev/2014-August/001759.html

[[seek-agreement]]
==== Seek Agreement

* Pushed gerrit: https://git.opendaylight.org/gerrit/#/c/9802/
* List of *PROJECT REPRESENTATIVES*: Ed Warnicke (controller)
* Sent e-mail:
https://lists.opendaylight.org/pipermail/openflowplugin-dev/2014-August/001759.html

[[waiver-granted]]
==== Waiver Granted

* Group-based policy: Rob Adams: Reviews
https://git.opendaylight.org/gerrit/#/c/9802/ and
https://git.opendaylight.org/gerrit/#/c/9214/

[[bindingnormalizednode-stream-writer-change-waiver]]
=== Binding/NormalizedNode Stream Writer Change Waiver

[[core-details-1]]
==== Core Details

* API Name: BindingSteamEventWriter, DataObjectSerializer,
DataObjectSerializerImplementation, NormalizedNodeStreamWriter
** Containing repo: yangtools
** Path to the API:
***
yang/yang-data-api/src/main/java/org/opendaylight/yangtools/yang/data/api/schema/stream/NormalizedNodeStreamWriter.java
***
yang/yang-binding/src/main/java/org/opendaylight/yangtools/yang/binding/BindingStreamEventWriter.java
***
yang/yang-binding/src/main/java/org/opendaylight/yangtools/yang/binding/DataObjectSerializer.java
***
yang/yang-binding/src/main/java/org/opendaylight/yangtools/yang/binding/DataObjectSerializerImplementation.java
* *RECEIVING PROJECT*: yangtools
* *API PROVIDERS*: yangtools
* *API IMPLEMENTORS*: yangtools
* *API CONSUMERS*: yangtools
* Other *IMPACTED PROJECTS*: NONE
* State: *WAIVER GRANTED*

[[comments-1]]
==== Comments

[[description-of-the-api-change-and-rationale-1]]
===== Description of the API Change and Rationale

Existing methods get a 'throws IOException' amendment. The two
StreamWriters get a flush() and close() methods defined to make them
consistent with java.io.Writer. These changes are required to properly
integrate with other stream writing interfaces, such as JsonWriter,
especially where error reporting is concerned.

[[feedback-from-impacted-projects-1]]
===== Feedback from *IMPACTED PROJECTS*

[[notification-1]]
==== Notification

* Filed bug: https://bugs.opendaylight.org/show_bug.cgi?id=1605

[[seek-agreement-1]]
==== Seek Agreement

* Pushed gerrit: https://git.opendaylight.org/gerrit/#/c/10188/,
https://git.opendaylight.org/gerrit/#/c/10189/
* List of *PROJECT REPRESENTATIVES*: Tony Tkacik (yangtools)
* Sent e-mail:
https://lists.opendaylight.org/pipermail/release/2014-August/000232.html

[[waiver-granted-1]]
==== Waiver Granted

* Reviewed gerrit: https://git.opendaylight.org/gerrit/10188,
https://git.opendaylight.org/gerrit/10189

[[bgp-application-peer-waiver]]
=== BGP Application Peer Waiver

[[core-details-2]]
==== Core Details

* API Name: AbstractAdjRIBs, AdjRIBsIn
** Containing repo: bgpcep
** Path to the API:
bgp/rib-spi/src/main/java/org/opendaylight/protocol/bgp/rib/spi/AdjRIBsIn.java,
bgp/rib-spi/src/main/java/org/opendaylight/protocol/bgp/rib/spi/AbstractAdjRIBs.java
* *RECEIVING PROJECT*: bgpcep
* *API PROVIDERS*: bgpcep
* *API IMPLEMENTORS*: bgpcep
* _'API CONSUMERS_: bgpcep
* Other *IMPACTED PROJECTS*: bgpcep
* State: *WAIVER GRANTED*

[[comments-2]]
==== Comments

[[description-of-the-api-change-and-rationale-2]]
===== Description of the API Change and Rationale

New helper methods needed to be added in order to fill the RIB API
through Application Peer.

[[feedback-from-impacted-projects-2]]
===== Feedback from *IMPACTED PROJECTS*

[[seek-agreement-2]]
==== Seek Agreement

* Pushed gerrit: https://git.opendaylight.org/gerrit/#/c/10066/
* List of *PROJECT REPRESENTATIVES*: Robert Varga (bgpcep)
* Sent e-mail:
https://lists.opendaylight.org/pipermail/release/2014-August/000258.html

[[waiver-granted-2]]
==== Waiver Granted

* Reviewed gerrit: https://git.opendaylight.org/gerrit/#/c/10066/

[[bgp-linkstate-routes-grouping]]
=== BGP Linkstate routes grouping

[[core-details-3]]
==== Core Details

* API Name: bgp-linkstate.yang
** Containing repo: bgpcep
** Path to the API: bgp/linkstate/src/main/yang/bgp-linkstate.yang
* *RECEIVING PROJECT*: bgpcep
* *API PROVIDERS*: bgpcep
* *API IMPLEMENTORS*: bgpcep
* _'API CONSUMERS_: bgpcep
* Other *IMPACTED PROJECTS*: bgpcep
* State: *SEEK AGREEMENT*

[[comments-3]]
==== Comments

[[description-of-the-api-change-and-rationale-3]]
===== Description of the API Change and Rationale

In order to use linkstate routes in other RIBs, we need to make it a
grouping and add appropriate augmentation.

[[feedback-from-impacted-projects-3]]
===== Feedback from *IMPACTED PROJECTS*

[[seek-agreement-3]]
==== Seek Agreement

* Pushed gerrit: https://git.opendaylight.org/gerrit/#/c/10449
* List of *PROJECT REPRESENTATIVES*: Dana Kutenicsova (bgpcep)
* Sent e-mail:
https://lists.opendaylight.org/pipermail/release/2014-September/000261.html

[[waiver-granted-3]]
==== Waiver Granted

* Reviewed gerrit: https://git.opendaylight.org/gerrit/#/c/10449

[[ttp-model-change-waiver]]
=== TTP Model Change Waiver

[[core-details-4]]
==== Core Details

* API Name: onf-ttp YANG module
** Containing repo: ttp
** Path to the API: ttp-model/src/main/yang/ttp.yang
* *RECEIVING PROJECT*: ttp
* *API PROVIDERS*: ttp
* *API IMPLEMENTORS*: ttp
* *API CONSUMERS*: ttp
* Other *IMPACTED PROJECTS*: none
* State: *WAIVER GRANTED*

[[comments-4]]
==== Comments

[[description-of-the-api-change-and-rationale-4]]
===== Description of the API Change and Rationale

Enhancing the TTP model before code freeze.

[[feedback-from-impacted-projects-4]]
===== Feedback from *IMPACTED PROJECTS*

* Colin Dixon (ttp)
** Since the change is local to the TTP project, I approve.

[[notification-2]]
==== Notification

* Filed bug: n/a
* Sent e-mail:
https://lists.opendaylight.org/pipermail/release/2014-September/000275.html[https://lists.opendaylight.org/pipermail/release/2014-September/000275.html]

[[seek-agreement-4]]
==== Seek Agreement

* Pushed gerrit:
**
https://git.opendaylight.org/gerrit/#/c/9818/[https://git.opendaylight.org/gerrit/#/c/9818/]
**
https://git.opendaylight.org/gerrit/#/c/10742/[https://git.opendaylight.org/gerrit/#/c/10742/]
**
https://git.opendaylight.org/gerrit/#/c/10751/[https://git.opendaylight.org/gerrit/#/c/10751/]
**
https://git.opendaylight.org/gerrit/#/c/10813/[https://git.opendaylight.org/gerrit/#/c/10813/]
* List of *PROJECT REPRESENTATIVES*: Colin Dixon (ttp)
* Sent e-mail:
https://lists.opendaylight.org/pipermail/release/2014-September/000275.html[https://lists.opendaylight.org/pipermail/release/2014-September/000275.html]

[[waiver-granted-4]]
==== Waiver Granted

* Reviewed gerrit:
**
https://git.opendaylight.org/gerrit/#/c/9818/[https://git.opendaylight.org/gerrit/#/c/9818/]
**
https://git.opendaylight.org/gerrit/#/c/10742/[https://git.opendaylight.org/gerrit/#/c/10742/]
**
https://git.opendaylight.org/gerrit/#/c/10751/[https://git.opendaylight.org/gerrit/#/c/10751/]
**
https://git.opendaylight.org/gerrit/#/c/10813/[https://git.opendaylight.org/gerrit/#/c/10813/]

[[requested-waivers]]
== Requested Waivers

[[template]]
== Template

Fields in red are ones that should be replaced and filled in when using
the template. Fields in *BOLD ALL CAPS* are defined in
Simultaneous_Release:Helium:Suggestions_for_Post_API_Freeze_Exception_Handling[Suggestions
for Post API Freeze Exception Handling].

[[api-name-change-waiver]]
=== API Name Change Waiver

[[core-details-5]]
==== Core Details

* API Name: The name of the API in code, e.g., YANG Module or Java
Interface
** Containing repo: e.g., controller
** Path to the API: e.g.,
opendaylight/hosttracker/api/src/main/java/org/opendaylight/controller/hosttracker/IfIptoHost.java
* *RECEIVING PROJECT*: project's repo name
* *API PROVIDERS*: list of projects' repo names
* *API IMPLEMENTORS*: list projects' repo names
* *API CONSUMERS*: list of projects's repo names
* Other *IMPACTED PROJECTS*: list of projects's repo names
* State: one of *NOTIFICATION*, *SEEK AGREEMENT*, or *WAIVER GRANTED* +
*Note:* If the state is *NOTIFICATION* or *SEEK AGREEMENT*, it should go
in the link:#Requested_Waivers[Requested Waivers] section and if the
state is *WAIVER GRANTED* it should go in the
link:#Granted_Waivers[Granted Waivers] section.

[[comments-5]]
==== Comments

[[description-of-the-api-change-and-rationale-5]]
===== Description of the API Change and Rationale

A short English description of what changed and why. No more than a few
sentences.

[[feedback-from-impacted-projects-5]]
===== Feedback from *IMPACTED PROJECTS*

* $ *PROJECT REPRESENTATIVE* ($ *IMPACTED PROJECT*), e.g., Colin Dixon
(ttp)
** comments, e.g., I agree that this change needs to be made and the ttp
project has the resources to deal with it. +
*Note:* formal approval of the final API change will come in the form of
a +1 vote on the gerrit.

[[notification-3]]
==== Notification

* Filed bug: link to bug in https://bugs.opendaylight.org/[bugzilla]
* Sent e-mail: link to email on the
https://lists.opendaylight.org/[lists archive]

[[seek-agreement-5]]
==== Seek Agreement

* Pushed gerrit: link to the patch on
https://git.opendaylight.org/[gerrit]
* List of *PROJECT REPRESENTATIVES*: list of representatives and their
project, e.g., Ed Warnicke (controller)
* Sent e-mail: link to email on the
https://lists.opendaylight.org/[lists archive]

[[waiver-granted-5]]
==== Waiver Granted

* Reviewed gerrit: link to the patch on
https://git.opendaylight.org/[gerrit] showing a +1 review from each
*PROJECT REPRESENTATIVE*

