[[introduction]]
= Introduction

We are now past API Freeze for Helium (M4, Monday Aug 4, 2014).

At the pre-M4 meeting on IRC, the following was the best available
consensus on
https://lists.opendaylight.org/pipermail/release/2014-July/000129.html[API
freeze]:

Definition of *API FREEZE*

---------------------------------------------------------------------------
"There is a lot of discussion about what constitutes API Freeze. Everyone
agrees that the type signatures of things "public" in Java should not have
any changes and that the high-level behavior should remain the same. For
YANG files, a similar rule applies with no structural changes being made.
Adding new functions, fields, etc. (that don't change the existing ones)
will be allowed until code freeze (M5). However this should be
well-documented as an interface in flux and you should make a good faith
effort to identify users of the API and work with them. After that point
only bug fixes can be applied, so this would include not adding anything to
(or changing anything about) any interfaces."
---------------------------------------------------------------------------

In the event that there needs to be a breaking API change in spite of
this, we need an appropriate process for handling it.

[[basic-idea]]
= Basic Idea

The agreement above clearly covers cases of adding new functions, fields
etc. For things that are *not* that we need a way to cleanly handle
them.

[[who]]
== Who

1.  *IMPACTED PROJECTS* are defined as:
1.  *API CONSUMERS* - the projects that consume the API
2.  *API IMPLEMENTORS* - the projects that implement the API
3.  *API PROVIDERS* - the projects that provide the API (where the
changes will be merged if accepted)
2.  *PROJECT REPRESENTATIVE* - one person from each *IMPACTED PROJECTS*
to represent it for purposes of reaching agreement.
3.  *RECEIVING PROJECT* - project to whom the patch will be contributed
(always definitionally an *IMPACTED PROJECT*)

[[purpose]]
== Purpose

The purpose is to:

1.  Provide clarity to developers on how to proceed.
2.  To provide a lightweight process to reach agreement among the
*IMPACTED PROJECTS* to wave the

*API FREEZE* restriction for specific patches.

The purpose is *NOT* to:

1.  Govern method or field additions (which are defined as not blocked
by the *API FREEZE* as defined above).
2.  Short circuit the normal project committer review process.

[[principle]]
== Principle

The *IMPACTED PROJECTS*, being the ones impacted, should be the ones to
agree to wave API Freeze restrictions if necessary.

[[process]]
== Process

Need for Exception to *API FREEZE* will be handled via a three step
process:

1.  NOTIFY(Optional)
2.  SEEK AGREEMENT
3.  WAIVER GRANTED

[[details]]
= Details

[[notifyoptional]]
== NOTIFY(Optional)

[[purpose-1]]
=== Purpose

The purpose of NOTIFY is to:

1.  Let *IMPACTED PROJECTS* know that someone thinks there should be an
API change
2.  Query the *IMPACTED PROJECTS* as to possible criteria for acceptance
from them (Examples: A patch to fix any breakage, testing, etc)

The purpose of NOTIFY is *not*

1.  To ask permission to do the work

No one ever needs permission to do work. That does not mean the work
will be committed to master.

Notify is optional (though a good idea) because it is non-blocking.
Nobody can tell you not to do work, but for your work to be merged
during *API FREEZE*, you would need a waiver.

[[process-1]]
=== Process

1.  File a Bug
2.  Send Email
3.  Record

[[file-a-bug]]
==== File a Bug

Bug should be filed against the *RECEIVING PROJECT* for tracking.

[[send-email]]
==== Send Email

A NOTIFY is done via an email to release@lists.opendaylight.org and the
-dev lists for the *IMPACTED PROJECTS*.

Email template:

-----------------------------------------------------------------------------------------------------------------------
Subject: [INTENT TO CHANGE SEEK API FREEZE WAIVER] ${api name}

Note: This email is an advisement of intent to seek a waiver of '''API FREEZE'''.

The patch for this would be going to:
${RECEIVING PROJECT}

The following projects have been determined to be impacted:

${for $IMPACTED_project: $IMPACTED_project}
$IMPACTED_project - ${CONSUMER, IMPLEMENTER, PROVIDER}
${endfor}

No API changing code will be committed until these projects have agreed to wave API FREEZE, but
Gerrits may be pushed.

${whatever else you want to ask, like asking what '''IMPACTED PROJECTS''' would need to be comfortable with the change}
-----------------------------------------------------------------------------------------------------------------------

[[record]]
==== Record

Record Notification on
*Simultaneous_Release:Helium:API_Freeze_Waiver_Records[API FREEZE
Exception Wiki Page]*, the person who sent the notification should:

1.  Add a record for their notification
2.  Record *IMPACTED PROJECTS* and their role (*API CONSUMERS*, *API
PROVIDER*,*API IMPLEMENTER*)

[[seek-agreement]]
== SEEK AGREEMENT

[[purpose-2]]
=== Purpose

The purpose of SEEK AGREEMENT is to:

1.  Facilitate *IMPACTED PROJECTS* reaching agreement to wave *API
FREEZE* for a specific patch.
2.  Let API changes that are non-objectionable to *IMPACTED PROJECTS*
proceed expeditiously.
3.  Allow the conversation to be about *actual* code, not ideas.
4.  Record decisions from projects on
Simultaneous_Release:Helium:API_Freeze_Waiver_Records[API FREEZE
Exceptions Wiki page].

Prior to waving the *API FREEZE* for a patch, the *IMPACTED PROJECTS*
should agree that it should be waved.

Without agreement from all *IMPACTED PROJECTS* the API FREEZE should not
be waved for a patch.

With agreement from *IMPACTED PROJECTS* projects, the *API FREEZE* may
be waved for a patch, and normal code review may occur (possibly
including merging of the patch if it is accepted).

In the event that not all *IMPACTED PROJECTS* agree, and there is still
desire to wave API FREEZE for the patch, the question should be
escalated to the TSC.

[[process-2]]
=== Process

1.  Push Gerrit
2.  Add *PROJECT REPRESENTATIVE* as Reviewers
3.  Send Email
4.  Record Request
5.  Record Result

[[push-a-gerrit]]
==== Push a Gerrit

1.  Push Gerrit: Push a Gerrit for the API change.
1.  Set topic to 'api-change'
2.  Prefix with "DO NOT MERGE Bug $\{bugid}: " in the commit message
summary.
3.  Make sure the commit message is clear about the API change to be
made and that this patch is seeking a wave of the *API FREEZE*.

[[add-project-representative-as-reviewers]]
==== Add *PROJECT REPRESENTATIVE* as Reviewers

1.  Add each *IMPACTED PROJECTS* *PROJECT REPRESENTATIVE* to the Gerrit
as a reviewer
2.  Provide a comment to the Gerrit indicating who is representing each
project.

[[send-email-1]]
==== Send Email

A SEEK AGREEMENT is done via an email to release@lists.opendaylight.org
the -dev lists for the *IMPACTED PROJECTS*.

Email template:

-----------------------------------------------------------------------------------------------------------------------
Subject: [SEEK AGREEMENT ON API FREEZE WAIVER] ${api name}

Note: This email is to seek agreement on a waiver of API FREEZE.

The patch for wich a waiver of API FREEZE is being sought is:
${link to gerrit}
and it is contributed to:
${RECEIVING PROJECT}

The following projects have been determined to be impacted:

${for $IMPACTED_project: $IMPACTED_project}
$IMPACTED_project - ${CONSUMER, IMPLEMENTER, PROVIDER}
${endfor}

ACTION FOR IMPACTED PROJECTS: Please:
1) Name a single committer from your project as a representative and add them to the wiki:
${link to wiki page} 
2) Add your project representative to the Gerrit as a reviewer
3) Add a comment to the Gerrit indicating who your representative is, and for what project.

Agreement to waive API FREEZE for 
${link to gerrit}
will be indicated by +1 from each project representative on the Gerrit itself.

There is no agreement to waive API FREEZE until all project representatives have +1ed the Gerrit.

This email is *only* about waiving of API FREEZE, normal code review will proceed in the normal fashion

${whatever else you want to ask, like asking what '''IMPACTED PROJECTS''' would need to be comfortable with the change}
-----------------------------------------------------------------------------------------------------------------------

[[record-request]]
==== Record Request

The person *SEEKing AGREEMENT* should

1.  Update the
Simultaneous_Release:Helium:API_Freeze_Waiver_Records[*API FREEZE
Exception Wiki Page*] with:
1.  A link to the Gerrit
2.  A link to the email in the
https://lists.opendaylight.org/mailman/listinfo[email archives]
3.  The *PROJECT REPRESENTATIVE* for each project.

[[record-result]]
==== Record Result

The person *SEEKing AGREEMENT* should:

1.  Update the
Simultaneous_Release:Helium:API_Freeze_Waiver_Records[*API FREEZE
Exception Wiki Page*] when the waiver has been granted indicating that
result.

[[waiver-granted]]
== WAIVER GRANTED

1.  Once the Gerrit has +1 from each of the *PROJECT REPRESENTATIVE*s
the waiver of *API FREEZE* is granted and it may be handled by the
receiving projects committers in the normal fashion.

[[todo-to-complete-this-process-suggestion]]
= TODO to Complete this Process Suggestion

1.  Create *API FREEZE Exception Wiki Page* - should include a way to
record *IMPACTED PROJECTS* and their role (*API CONSUMERS*, *API
PROVIDER*,*API IMPLEMENTER*), a place for them to record their comments
on NOTIFICATION and their decisions on *REQUEST PERMISION*, a link to
the bug and the gerrit, and the state (*NOTIFICATION*, *REQUEST
PERMISION*, *WAIVER GRANTED*) - note, and embedded google spreadsheet
might be good.
* Done. See the page here:
Simultaneous_Release:Helium:API_Freeze_Waiver_Records

