[[maintainer]]
== Maintainer

integration-dev@lists.opendaylight.org

[[introduction]]
== Introduction

OpenDaylight Jenkins builds and provides all artifacts we need for
testing so there is no need to setup development environment for
building controller if you do not want to. Also OSGi framework allows
easy integration and generation of custom controller editions.

[[artifacts-links]]
== Artifacts Links

[[lithium-latest-distribution-artifacts]]
=== Lithium Latest Distribution Artifacts

These are the Nexus latest generated artifacts for current release

OpenDaylight karaf edition (no integration test features*):

-----------------------------------------------------------------------------------------------------------------------------------------
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.3.0-SNAPSHOT/
-----------------------------------------------------------------------------------------------------------------------------------------

(*) Check further sections to know how to add integration test features

[[stable-helium-distribution-artifacts]]
=== Stable Helium Distribution Artifacts

These are the Nexus latest generated artifacts for stable Helium

OpenDaylight Karaf edition:

-----------------------------------------------------------------------------------------------------------------------------------------
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.2.4-SNAPSHOT/
-----------------------------------------------------------------------------------------------------------------------------------------

[[helium-stable-release]]
=== Helium Stable Release

This is the Nexus latest Helium stable release

OpenDaylight Karaf edition:

------------------------------------------------------------------------------------------------------------------------------------------
https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distribution-karaf/0.2.3-Helium-SR3/
------------------------------------------------------------------------------------------------------------------------------------------

[[artifacts-installation]]
== Artifacts Installation

[[setup-controller-run-environment]]
=== Setup Controller run environment

Install Java JDK 1.7+ (note Java 1.8 is not supported yet):

-----------------------------------------------------
odluser@odl-vm:~\$ sudo apt-get install openjdk-7-jre
-----------------------------------------------------

Set JAVA_HOME in environment. Add follow lines (Java path may change
depending on the JDK installation) in ~/.bashrc file:

------------------------------------------------------
odluser@odl-vm:~\$ vi ~/.bashrc
...
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
...
------------------------------------------------------

[[installing-karaf-distribution]]
=== Installing Karaf Distribution

Download the distribution artifact, unzip it and run it:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\$ wget 'https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.3.0-SNAPSHOT/distribution-karaf-0.3.0-SNAPSHOT.zip'
odluser@odl-vm:~\$ unzip distribution-karaf-0.3.0-SNAPSHOT.zip
odluser@odl-vm:~\$ cd distribution-karaf-0.3.0-SNAPSHOT
odluser@odl-vm:~\$ bin/karaf 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[adding-test-features-repositories-optional]]
=== Adding test features repositories (Optional)

To add integration features (only for testing), type the following in
Karaf console:

------------------------------------------------------------------------------------------------------------------------------
opendaylight-user@root>feature:repo-add mvn:org.opendaylight.integration/features-integration-test/0.3.0-SNAPSHOT/xml/features
------------------------------------------------------------------------------------------------------------------------------

[[installing-karaf-features]]
=== Installing Karaf Features

Karaf distribution does not install any feature by default, to do so use
feature:install command from Karaf console:

----------------------------------------
 feature:install odl-l2switch-switch-ui 
----------------------------------------

For a complete list of features and their description please check the
ODL Installation Guide:

http://www.opendaylight.org/software/downloads

For more information on how to deal with features check this
CrossProject:Integration_Group:karaf[ Karaf wiki]

[[installing-java-artifacts-in-karaf-distribution-optional]]
=== Installing Java Artifacts in Karaf Distribution (Optional)

If the jar is already shipped in karaf:

Find the bundle path in the system folder:

------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\$  cd <distro-folder>/system/system/org/opendaylight/controller/arphandler/<version> 
------------------------------------------------------------------------------------------------------

Install and run the bundle from karaf console:

---------------------------------------------------------------------------
> bundle:install mvn:org.opendaylight.controller/arphandler/0.6.0-SNAPSHOT 
> bundle:start arphandler
---------------------------------------------------------------------------

If it is a new artifact just place it in /deploy folder.

--------------------------------------------------------------------------------------
mv samples.loadbalancer-0.6.0-SNAPSHOT.jar ~/distribution-karaf-0.3.0-SNAPSHOT/deploy/
--------------------------------------------------------------------------------------

Category:Integration Group[Category:Integration Group]
