[[maintainer]]
== Maintainer

Luis Gomez (ecelgp@gmail.com)

[[introduction]]
== Introduction

OpenDaylight Jenkins builds and provides all artifacts we need for
testing so there is no need to setup development environment for
building controller if you do not want to. Also OSGi framework allows
easy integration and generation of custom controller editions.

[[artifacts-links]]
== Artifacts Links

[[hydrogen-stable-distribution-artifacts]]
=== Hydrogen Stable Distribution Artifacts

These are the Jenkins latest generated artifacts for Hydrogen stable
release (every ~1 hour)

OpenDaylight Base edition:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-hydrogen-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/base/target/distributions-base-0.1.1-1-SNAPSHOT-osgipackage.zip
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

OpenDaylight Virtualization edition:

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-hydrogen-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/virtualization/target/distributions-virtualization-0.1.1-1-SNAPSHOT-osgipackage.zip
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

OpenDaylight Service Provider edition:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-hydrogen-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/serviceprovider/target/distributions-serviceprovider-0.1.1-1-SNAPSHOT-osgipackage.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The artifacts are also available on the nexus server:

------------------------------------------------------------------------------------------------------
http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/
------------------------------------------------------------------------------------------------------

[[helium-latest-distribution-artifacts]]
=== Helium Latest Distribution Artifacts

These are the Jenkins latest generated artifacts for current release
(every ~1 hour)

OpenDaylight Base edition:

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-master-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/base/target/distributions-base-0.2.0-SNAPSHOT-osgipackage.zip
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

OpenDaylight Virtualization edition:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-master-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/virtualization/target/distributions-virtualization-0.2.0-SNAPSHOT-osgipackage.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

OpenDaylight Service Provider edition:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/integration/job/integration-master-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/serviceprovider/target/distributions-serviceprovider-0.2.0-SNAPSHOT-osgipackage.zip
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The artifacts are also available on the nexus server:

------------------------------------------------------------------------------------------------------
http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/
------------------------------------------------------------------------------------------------------

[[project-custom-distribution-artifacts]]
=== Project Custom Distribution Artifacts

These are project generated artifacts created for in-project usage

Controller edition (only controller project):

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/controller/job/controller-merge/lastSuccessfulBuild/artifact/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage.zip
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

OF plugin edition (controller + openflowplugin project):

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/openflowplugin/job/openflowplugin-merge/lastSuccessfulBuild/org.opendaylight.openflowplugin$distributions-openflowplugin-base/artifact/org.opendaylight.openflowplugin/distributions-openflowplugin-base/0.0.3-SNAPSHOT/distributions-openflowplugin-base-0.0.3-SNAPSHOT-osgipackage.zip
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[test-java-artifacts]]
=== Test Java Artifacts

Java applications created for testing (normally they are not part of
official distributions)

OF plugin reactive forwarding bundle (used for CBench test):

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
https://jenkins.opendaylight.org/openflowplugin/job/openflowplugin-merge/lastSuccessfulBuild/org.opendaylight.openflowplugin$drop-test/artifact/org.opendaylight.openflowplugin/drop-test/0.0.3-SNAPSHOT/drop-test-0.0.3-SNAPSHOT.jar
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[artifacts-installation]]
== Artifacts Installation

[[installing-distribution-artifacts]]
=== Installing Distribution Artifacts

Download the distribution artifact, unzip it and run it:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\$ wget 'https://jenkins.opendaylight.org/integration/job/integration-master-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/base/target/distributions-base-0.1.2-SNAPSHOT-osgipackage.zip'
odluser@odl-vm:~\$ unzip distributions-base-0.1.2-SNAPSHOT-osgipackage.zip
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[installing-java-artifacts-in-existing-distribution]]
=== Installing Java Artifacts in existing Distribution

Download the Java artifact, place the jar file in /opendaylight/plugins
folder:

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\$ wget 'https://jenkins.opendaylight.org/openflowplugin/job/openflowplugin-merge/lastSuccessfulBuild/org.opendaylight.openflowplugin$drop-test/artifact/org.opendaylight.openflowplugin/drop-test/0.0.3-SNAPSHOT/drop-test-0.0.3-SNAPSHOT.jar'
odluser@odl-vm:~\$ mv drop-test-0.0.3-SNAPSHOT.jar opendaylight/plugins
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[run-controller]]
== Run Controller

[[setup-controller-run-environment]]
=== Setup Controller run environment

Install Java JDK 1.7+:

-----------------------------------------------------
odluser@odl-vm:~\$ sudo apt-get install openjdk-7-jre
-----------------------------------------------------

Set JAVA_HOME in environment. Add follow lines (Java path may change
depending on the JDK installation) in ~/.bashrc file:

------------------------------------------------------
odluser@odl-vm:~\$ vi ~/.bashrc
...
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
...
------------------------------------------------------

[[start-controller]]
=== Start Controller

* Hydrogen Stable distribution:

Go to /opendaylight and execute
CrossProject:Integration_Group:Controller_Artifacts:run_sh[run.sh]:

----------------------------------
odluser@odl-vm:~\$ cd opendaylight
odluser@odl-vm:~\$ ./run.sh 
----------------------------------

Start OpenFlow 1.3 plugin:

----------------------------------
odluser@odl-vm:~\$ cd opendaylight
odluser@odl-vm:~\$ ./run.sh -of13 
----------------------------------

* Helium distribution:

It starts OpenFlow 1.3 plugin by default:

----------------------------------
odluser@odl-vm:~\$ cd opendaylight
odluser@odl-vm:~\$ ./run.sh 
----------------------------------

Start old OpenFlow 1.0 plugin:

----------------------------------
odluser@odl-vm:~\$ cd opendaylight
odluser@odl-vm:~\$ ./run.sh -of10 
----------------------------------

* Custom distribution:

----------------------------------
odluser@odl-vm:~\$ cd opendaylight
odluser@odl-vm:~\$ ./run.sh 
----------------------------------

Check controller is running:

-----------------------------------------------------------------------------
osgi> ss
"Framework is launched."


id      State       Bundle
0       ACTIVE      org.eclipse.osgi_3.8.1.v20120830-144521
1       ACTIVE      org.apache.felix.fileinstall_3.1.6
2       ACTIVE      org.eclipse.jdt.core.compiler.batch_3.8.0.I20120518-2145
3       ACTIVE      org.eclipse.equinox.ds_1.4.0.v20120522-1841
4       ACTIVE      org.eclipse.equinox.util_1.0.400.v20120522-2049
5       ACTIVE      org.eclipse.osgi.services_3.3.100.v20120522-1822
6       ACTIVE      org.eclipse.equinox.console_1.0.0.v20120522-1841
7       ACTIVE      slf4j.api_1.7.2
8       ACTIVE      ch.qos.logback.classic_1.0.9
9       ACTIVE      ch.qos.logback.core_1.0.9
10      ACTIVE      org.opendaylight.controller.logging.bridge_0.4.1.SNAPSHOT
11      ACTIVE      com.sun.jersey.core_1.17.0
12      ACTIVE      com.sun.jersey.json_1.17.0
13      ACTIVE      com.sun.jersey.jersey-server_1.17.0
-----------------------------------------------------------------------------

Category:Integration Group[Category:Integration Group]
