[[introduction]]
== Introduction

Continuous System Integration Test (CSIT) area has been created to
develop automated system test executed at distribution build time.

[[test-execution]]
== Test Execution

We use CrossProject:Integration_Group:Jenkins[Jenkins] to trigger and
execute the system test

System Test runs continuously in
CrossProject:Integration_Group:ODL_Test_Lab[Linux Foundation Lab]

[[test-work-flow]]
== Test Work Flow

* Create a Test plan in
CrossProject:Integration_Group:Testopia[Testopia]
* Setup
CrossProject:Integration_Group:Create_System_Test_Environment[System
Test Environment]
* Write Automation in
CrossProject:Integration_Group:Robot_Framework[Robot Framework]
* Upload Test files to GIT repo using this
CrossProject:Integration_Group:Hack_Code[instruction]

[[old-test-plans]]
== Old Test Plans

* CrossProject:Integration_Group:CSIT_Test_Plan_Base[Base Edition]
* CrossProject:Integration_Group:CSIT_Test_Plan_Base_of13[Base Edition
-of13 Option]
* CrossProject:Integration_Group:CSIT_Test_Plan_Service_Provider[Service
Provider Edition]
*
CrossProject:Integration_Group:CSIT_Test_Plan_Virtualization[Virtualization
Edition]
* CrossProject:Integration_Group:CSIT_Test_Plan_Cluster_HA[Cluster HA
test]

Category:Integration Group[Category:Integration Group]
