[[maintainer]]
== Maintainer

Luis Gomez (ecelgp@gmail.com)

[[introduction]]
== Introduction

The purpose of this wiki is to describe how to download and run the
System Test code.

[[requirements]]
== Requirements

This instruction requires a System Test environment so please visit
CrossProject:Integration_Group:Create_System_Test_Environment[Create
System Test Environment] wiki if you do not have it yet.

[[download-system-test-code]]
== Download System Test Code

Get latest integration code:

----------------------------------------------------------------------------
odluser@odl-vm:~\> git clone https://git.opendaylight.org/gerrit/integration
----------------------------------------------------------------------------

Navigate to system test suites folder:

--------------------------------------------------
odluser@odl-vm:~\> cd integration/test/csit/suites
--------------------------------------------------

System test suites are organized in 2 level folder structure:

* First level folder is the main suite for a given distribution like
Base, VTN, Service Provider or Base edition with -of13 option
* Second level folder is for the sub-suites that run within the main
suite: AD-SAL NSF, AD-SAL Apps, MD-SAL NSF, OVSDB, VTN, etc...

[[running-system-test-code]]
== Running System Test Code

[[start-controller]]
=== Start Controller

Before starting system test, make sure controller is running. Please
visit CrossProject:Integration_Group:Controller_Artifacts[Controller
Artifacts] wiki to get more help on how to install and run controller.

[[executing-system-test]]
=== Executing System Test

Robot framework is used to write and execute system test, so we just
need to execute pybot command with following arguments:

* CONTROLLER: Controller IP address
* MININET: Mininet IP address
* USER_HOME: Robot user home path (for ssh authentication)
* MININET_USER: Mininet User (for ssh authentication)
* Suite path: suite to be executed

[[examples]]
=== Examples

Run system test for base edition with new plugin (default) when
controller and mininet are in the same VM:

------------------------------------------------------------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\> pybot -v CONTROLLER:127.0.0.1 -v MININET:127.0.0.1 -v USER_HOME:$HOME -v MININET_USER:$USER $HOME/integration/test/csit/suites/base-of13/
------------------------------------------------------------------------------------------------------------------------------------------------------------

Run system test for base edition old plugin (-of10) AD-SAL NSF when
controller and mininet are on different VM:

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
odluser@odl-vm:~\> pybot -v CONTROLLER:192.168.1.1 -v MININET:192.168.1.2 -v USER_HOME:$HOME -v MININET_USER:$USER $HOME/integration/test/csit/suites/base-of10/010__AD_SAL_NSF
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

*IMPORTANT*: In case of different VMs for controller and mininet, you
have to use interface IPs instead of loopback IPs like example above

Category:Integration Group[Category:Integration Group]
