[[maintainer]]
== Maintainer

integration-dev@lists.opendaylight.org

[[introduction]]
== Introduction

The purpose of this wiki is to describe how to download and run the
System Test code.

[[requirements]]
== Requirements

This instruction requires a System Test environment including Robot
Framework and Robot IDE (RIDE) so please visit
CrossProject:Integration_Group:Create_System_Test_Environment[Create
System Test Environment] wiki if you do not have it yet.

[[download-system-test-code]]
== Download System Test Code

Get latest integration code:

----------------------------------------------------------------------------
odluser@odl-vm:~\> git clone https://git.opendaylight.org/gerrit/integration
----------------------------------------------------------------------------

Navigate to system test suites folder:

--------------------------------------------------
odluser@odl-vm:~\> cd integration/test/csit/suites
--------------------------------------------------

System test suites are organized in 2 level folder structure:

* First level folder is the project folder, here you can see projects in
OpenDaylight that have some robot based System Test today
* Second level folder is the robot suites folder to verify specific
project functionality: MD-SAL NSF, L2Switch Host Tracker, VTN manager,
etc...

[[running-system-test-code]]
== Running System Test Code

Before starting system test, make sure controller is running. Please
visit CrossProject:Integration_Group:Controller_Artifacts[Controller
Artifacts] wiki to get more help on how to install and run controller.

[[import-your-test-in-ride]]
=== Import your test in RIDE

Open RIDE and import a robot suite of your choice.

[[run-the-test-suite-in-ride]]
=== Run the test suite in RIDE

On the right window of RIDE, select Run tab and enter Execution Profile:
*pybot* and following Arguments with -v:

* CONTROLLER: Controller IP address
* MININET: Mininet IP address
* USER_HOME: Robot executing user home path (for mininet ssh
authentication)
* MININET_USER: Mininet executing user (for mininet ssh authentication)

For example:

------------------------------------------------------------------------------------------------
Arguments: -v CONTROLLER:127.0.0.1 -v MININET:127.0.0.1 -v USER_HOME:$HOME -v MININET_USER:$USER
------------------------------------------------------------------------------------------------

Press *Start* button

You should see test execution in the same tab

Once the test is completed, you can see the test reports by clicking on
the top right *Report* and *Log* (this should open a web browser).

[[editing-the-system-test-code]]
== Editing the System Test Code

On the RIDE left menu select the file or folder (folder config is stored
in __init__.robot) you want to edit and select *Edit* or *Text Edit*
tab.

Once you are done with the changes, save the suite (top left buttons)
and Run again to verify.

For information about Robot Framework please check
http://robotframework.org/#documentation[Robot Documentation]

Category:Integration Group[Category:Integration Group]
