[[feature-name-e.g.-md-sal-clustering]]
= Feature name (e.g. MD-SAL Clustering)

[[code-name]]
== Code Name

In this section, state Karaf or not Karaf "in code" name of the feature
(e.g. odl-mdsal-cluster)

If the same functionality comes with different interfaces (REST, GUI),
you can mention all here (e.g. odl-l2switch-switch,
odl-l2switch-switch-ui)

[[description]]
== Description

In this section, please provide a detailed description of your project
feature including:

* Overview
* Design Architecture
* Configuration

(you can point to your project wiki if this information already exists
there)

[[bundles]]
== Bundles

In this section, enumerate software bundles (OSGi and not OSGi) that are
part of the feature

(You can just provide a link to the feature.xml file)

[[upstream-dependencies]]
== Upstream Dependencies

In this section, state any dependency on features in the same or other
projects within Opendaylight

[[downstream-dependents]]
== Downstream Dependents

In this section, state any feature or project that you know depends on
this feature

[[incompatibilities]]
== Incompatibilities

In this section, state any incompatibility you know on the same or other
projects features and the effect on your feature.

Please also note, if known, why the incompatibility exists as well as
any plans and discussions you have had about possibly resolving this
incompatiblity either during this release or in a future release.
Projects are encouraged to do this to improve the consumability of
OpenDaylight. Doing so, especially if it resolves incompatibilities will
be seen favorably as part of project maturity when advancing through the
http://www.opendaylight.org/project-lifecycle-releases[project
lifecycle].

[[network-intrusiveness]]
== Network Intrusiveness

Does your feature program devices, send flows, packets out, etc...
without any special setting or configuration?

[[recommended-karaf-features]]
== Recommended Karaf features

In this section, state which features would you recommended to enable in
Karaf distribution to use and test your feature

[[how-to-test]]
== How to test

In this section, provide details about:

* How to setup your feature test
** Provide details of any scripts, tools, etc required for the test
* How to execute basic test cases to validate the feature’s
functionality
** Provide details of at least 3-7 system test cases which would allow
your feature to be tested at a minimum
** Test cases should include:
*** Purpose of the test
*** Pre-conditions or Pre-requisites
*** Detailed Test Steps
*** Expected Results

If your tests are already implemented in Robot, please provide the pybot
commands and robot scripts or repo

(you can point to your project wiki if this information already exists
there)

[[performancescalability-concerns]]
== Performance/Scalability Concerns

In this section, provide any concerns related to performance and
scalability

[[examples]]
= Examples

OpenDaylight_Controller:Lithium:Netconf:Integration_Test[ Netconf
Features ]

Category:Integration Group[Category:Integration Group]
