[[introduction]]
= Introduction

Since Lithium release, projects are responsible for their own features
integration and system tests. For more information, check
CrossProject:Integration_Group:Lithium_Project_Integration_Requirements[
the Integration requirements for the Lithium release].

This guide aims to help projects get started with Robot Framework.

[[step-by-step]]
= Step by Step

[[install-robot-framework-environment]]
== Install Robot Framework environment

Follow instructions in
CrossProject:Integration_Group:Create_System_Test_Environment[ System
Test Environment wiki] to install Robot and Robot IDE (RIDE) in your
computer system.

Additionally you can use same wiki to install other tools like mininet
or wirehark.

[[download-an-opendaylight-distribution]]
== Download an OpenDaylight distribution

System Test requires a distribution, follow instructions in
CrossProject:Integration_Group:Controller_Artifacts[ Download controller
wiki] to install and run OpenDaylight distribution in your computer
system.

[[run-some-integration-system-test]]
== Run some Integration System Test

Get familiar with Robot. Follow instructions in
CrossProject:Integration_Group:Download_and_Run_System_Test[ How to run
System Test wiki] to download integration repository and run a System
Test of your choice.

[[create-your-own-integration-system-test]]
== Create your own Integration System Test

The March 16th 2015 Tech_Work_Stream:Main[ TWS] was about Robot, with an
explicit emphasis on writing your own system tests. The
https://meetings.webex.com/collabs/url/fI_jTMbTyPKuDAREuBLYn-9YKno2Gg83cay8Ub2u0vu00000[WebEx
recording],
https://wiki.opendaylight.org/images/c/cd/RobotFW_ODL_IntegrationGroup.pptx[slides]
and
http://meetings.opendaylight.org/opendaylight-meeting/2015/tws/opendaylight-meeting-tws.2015-03-16-17.02.html[minutes]
are available.

Our CrossProject:Integration_Group:Test_Code_Guidelines[ Test Code
Guidelines] document best practices to follow when writing your Robot
tests.

[[upload-system-test-code-to-integration]]
== Upload System Test Code to Integration

Use standard
GettingStarted:Pulling,_Hacking,_and_Pushing_All_the_Code_from_the_CLI[
git wiki] to download and upload test code in the integration project.

Please ONLY edit the files and folders that are in your project folder.
You can add resources and libraries (test/csit/libraries), constants and
variables (test/csit/variables) as you see fit but never delete others.

Once you push your code you can check in gerrit some verify jobs are
kicked off to check your code, just wait for an integration committer to
review and merge your test code.

[[robot-assistance]]
== Robot Assistance

* Robot Happy Hour: Integration group will be available for Robot
questions in irc channel *opendaylight-integration* every Wednesday at
8AM PST.
* Integration IRC: OpenDaylight channel *opendaylight-integration* is
always on for Robot questions.
* Integration Mail: OpenDaylight list
*integration-dev@lists.opendaylight.org* is also available for Robot
queries.

