[[integration]]
== Integration

Responsible for distribution assembly, system test and packaging

[[features]]
== Features

Our features are just created for testing purposes, we do not expect or
recommend end users to install them:

* odl-integration-compatible-with-all
* odl-integration-compatible-with-groupbasedpolicy
* odl-integration-compatible-with-l2switch
* odl-integration-compatible-with-plugin2oc
* odl-integration-compatible-with-ovs-openstack
* odl-integration-compatible-with-ovs-sfc
* odl-integration-compatible-with-vtn-manager

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

We updated and wrote few wikis this release:

*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Download_and_Run_System_Test
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Open_Labs
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Test_Tools
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Performance_Test
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:FlowMod_Test
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:NetConf_Test
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Fuzzy_Test
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Code_Coverage_using_Jacoco
*
https://wiki.opendaylight.org/view/CrossProject:Integration_Group:karaf

[[architectural-issues]]
== Architectural Issues

Main issues this release were:

* Lack of gear and people for doing system test -> Next release we need
more gear and project devs writing system test
* Lack of infra flexibility to launch system test from projects -> We
need to work with LF to fix this
* Changes introduced by Karaf distro -> Hopefully we do not have to deal
with this anymore ;)

[[security-considerations]]
== Security Considerations

None that I know

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

We provide system test for following components:

* MD-SAL
* AD-SAL
* NSFs
* OpenFlow plugin
* Netconf plugin
* VTN Manager
* l2switch
* OpenStack-OVSDB (in progress)

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

We support our tests for the entire release life

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

https://bugs.opendaylight.org/buglist.cgi?bug_status=__open__&list_id=17715&order=relevance%20desc&product=integration&query_format=specific

All major issues fixed at this moment

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

N/A

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)

* OpenStack-OVSDB test delayed because of Karaf introduction -> planned
for Helium-1
* Cluster test delayed due to lack of gear and test readiness -> planned
for Helium-1
* Robot report & documentation plugin delayed -> planned for Lithium

Category:Integration Group[Category:Integration Group]
