[[how-to-manually-test-south-bound-netconf-connection-with-netopeer]]
== How to Manually Test South Bound Netconf Connection with Netopeer

Steps

\1. Install netopeer server and latest controller.

`  Refer to: `https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Create_System_Test_Environment[`https://wiki.opendaylight.org/view/CrossProject:Integration_Group:Create_System_Test_Environment`]` `

\2. Edit Controller NetConf connector file
opendaylight/configuration/initial/99-netconf-connector.xml

`   Change: ` +
`    ``netopeer` +
`                  `

127.0.0.1

`                  ``1831` +
`                  ``root` +
`                  ``root`

\3. Start Controller and verify Netopeer has connected successfully.

`   Check the cli output for the following message:` +
`         2014-07-01 11:20:17.449 PDT [remote-connector-processing-executor-1] INFO  o.o.c.s.c.netconf.NetconfDevice - RemoteDevice{netopeer}: Netconf connector initialized ` +
`         successfully`

\4. Try these test cases

`  a. Verify device is in the controller inventory.` +
`      curl -v `http://localhost:8080/restconf/operational/opendaylight-inventory:nodes/[`http://localhost:8080/restconf/operational/opendaylight-inventory:nodes/`] +
`      * Hostname was NOT found in DNS cache` +
`      *   Trying 127.0.0.1...` +
`      * Connected to localhost (127.0.0.1) port 8080 (#0)` +
`      > GET /restconf/operational/opendaylight-inventory:nodes/ HTTP/1.1` +
`      > User-Agent: curl/7.35.0` +
`      > Host: localhost:8080` +
`      > Accept: */*` +
`    > ` +
`   < HTTP/1.1 200 OK` +
`   * Server Apache-Coyote/1.1 is not blacklisted` +
`   < Server: Apache-Coyote/1.1` +
`   < Cache-Control: private` +
`   < Expires: Wed, 31 Dec 1969 16:00:00 PST` +
`   < Content-Type: application/yang.data+json` +
`   < Transfer-Encoding: chunked` +
`   < Date: Tue, 01 Jul 2014 18:27:24 GMT` +
`   < ` +
`   {` +
`           "nodes": {` +
`       "node": [` +
`           {` +
`               "id": "netopeer",` +
`               "netconf-node-inventory:connected": true,` +
`               "netconf-node-inventory:initial-capability": [` +
`                   "(urn:ietf:params:xml:ns:netmod:notification?revision=2008-07-14)nc-notifications",` +
`                   "(urn:ietf:params:xml:ns:netconf:notification:1.0?revision=2008-07-14)notifications",` +
`                   "(http://netconfcentral.org/ns/toaster?revision=2009-11-20)toaster",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?revision=2011-08-07)ietf-netconf-notifications",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?revision=2010-10-04)ietf-netconf-monitoring",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-yang-types?revision=2010-09-24)ietf-yang-types",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-netconf-acm?revision=2012-02-22)ietf-netconf-acm",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-inet-types?revision=2010-09-24)ietf-inet-types",` +
`                   "(urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?revision=2010-06-09)ietf-netconf-with-defaults",` +
`                   "(urn:ietf:params:xml:ns:netconf:base:1.0?revision=2011-03-08)ietf-netconf"` +
`                 ]` +
`             }` +
`            ]` +
`       }` +
`   `

`   b. Verify you can pull out the configuration` +
`      curl -v `http://localhost:8080/restconf/config/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount/[`http://localhost:8080/restconf/config/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount/`] +
`   * Hostname was NOT found in DNS cache` +
`   *   Trying 127.0.0.1...` +
`   * Connected to localhost (127.0.0.1) port 8080 (#0)` +
`   > GET /restconf/config/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount/ HTTP/1.1` +
`   > User-Agent: curl/7.35.0` +
`   > Host: localhost:8080` +
`   > Accept: */*` +
`   > ` +
`   < HTTP/1.1 200 OK` +
`   * Server Apache-Coyote/1.1 is not blacklisted` +
`   < Server: Apache-Coyote/1.1` +
`   < Cache-Control: private` +
`   < Expires: Wed, 31 Dec 1969 16:00:00 PST` +
`   < Content-Type: application/yang.data+json` +
`   < Transfer-Encoding: chunked` +
`   < Date: Tue, 01 Jul 2014 18:30:59 GMT` +
`   < ` +
`   {` +
`       "data": {}` +
`   * Connection #0 to host localhost left intact `

`   c. Verify Operational data and mount of external device.` +
`      curl -v `http://localhost:8080/operational/restconf/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount[`http://localhost:8080/operational/restconf/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount`]

`   * Hostname was NOT found in DNS cache` +
`   *   Trying 127.0.0.1...` +
`   * Connected to localhost (127.0.0.1) port 8080 (#0)` +
`   > GET /restconf/operational/opendaylight-inventory:nodes/node/netopeer/yang-ext:mount HTTP/1.1` +
`   > User-Agent: curl/7.35.0` +
`   > Host: localhost:8080` +
`   > Accept: */*` +
`   > ` +
`   < HTTP/1.1 200 OK` +
`   * Server Apache-Coyote/1.1 is not blacklisted` +
`   < Server: Apache-Coyote/1.1` +
`   < Cache-Control: private` +
`   < Expires: Wed, 31 Dec 1969 16:00:00 PST` +
`   < Content-Type: application/yang.data+json` +
`   < Transfer-Encoding: chunked` +
`   < Date: Tue, 01 Jul 2014 18:32:52 GMT` +
`   < ` +
`   {` +
`       "data": {` +
`           "toaster": {` +
`               "toasterManufacturer": "CESNET, z.s.p.o.",` +
`               "toasterModelNumber": "toaster",` +
`               "toasterStatus": "down"` +
`           },` +
`           "netconf-state": {` +
`           "datastores": {` +
`               "datastore": [` +
`                       {` +
`                           "name": "running"` +
`                       },` +
`                       {` +
`                           "name": "startup"` +
`                       },` +
`                       {` +
`                           "name": "candidate"` +
`                       }` +
`                   ]` +
`               },` +
`               "sessions": {` +
`                   "session": [` +
`                       {` +
`                           "session-id": 567,` +
`                           "transport": "netconf-ssh",` +
`                           "username": "root",` +
`                           "source-host": "172.17.42.1",` +
`                           "login-time": "2014-07-01T18:20:17Z",` +
`                           "in-rpcs": 10,` +
`                           "in-bad-rpcs": 0,` +
`                           "out-rpc-errors": 0,` +
`                           "out-notifications": 0` +
`                       }` +
`                   ]` +
`               },` +
`               "schemas": {` +
`                   "schema": [` +
`                       {` +
`                           "identifier": "toaster",` +
`                           "version": "2009-11-20",` +
`                           "format": "yin",` +
`                           "namespace": "`http://netconfcentral.org/ns/toaster[`http://netconfcentral.org/ns/toaster`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "toaster",` +
`                           "version": "2009-11-20",` +
`                           "format": "yang",` +
`                           "namespace": "`http://netconfcentral.org/ns/toaster[`http://netconfcentral.org/ns/toaster`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-acm",` +
`                           "version": "2012-02-22",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-acm[`urn:ietf:params:xml:ns:yang:ietf-netconf-acm`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-acm",` +
`                           "version": "2012-02-22",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-acm[`urn:ietf:params:xml:ns:yang:ietf-netconf-acm`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-with-defaults",` +
`                           "version": "2010-06-09",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults[`urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-with-defaults",` +
`                           "version": "2010-06-09",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults[`urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "notifications",` +
`                           "version": "2008-07-14",` +
`                           "format": "yin",` +
`                          "namespace": "`urn:ietf:params:xml:ns:netconf:notification:1.0[`urn:ietf:params:xml:ns:netconf:notification:1.0`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "notifications",` +
`                           "version": "2008-07-14",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:netconf:notification:1.0[`urn:ietf:params:xml:ns:netconf:notification:1.0`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "nc-notifications",` +
`                           "version": "2008-07-14",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:netmod:notification[`urn:ietf:params:xml:ns:netmod:notification`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "nc-notifications",` +
`                           "version": "2008-07-14",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:netmod:notification[`urn:ietf:params:xml:ns:netmod:notification`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-notifications",` +
`                           "version": "2011-08-07",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-notifications[`urn:ietf:params:xml:ns:yang:ietf-netconf-notifications`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-notifications",` +
`                           "version": "2011-08-07",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-notifications[`urn:ietf:params:xml:ns:yang:ietf-netconf-notifications`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                          ]` +
`                      },` +
`                      {` +
`                          "identifier": "ietf-netconf-monitoring",` +
`                          "version": "2010-10-04",` +
`                          "format": "yin",` +
`                          "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring[`urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring`]`",` +
`                          "location": [` +
`                              "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf-monitoring",` +
`                           "version": "2010-10-04",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring[`urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf",` +
`                           "version": "2011-03-08",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:netconf:base:1.0[`urn:ietf:params:xml:ns:netconf:base:1.0`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                       ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-netconf",` +
`                           "version": "2011-03-08",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:netconf:base:1.0[`urn:ietf:params:xml:ns:netconf:base:1.0`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-yang-types",` +
`                           "version": "2010-09-24",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-yang-types[`urn:ietf:params:xml:ns:yang:ietf-yang-types`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-yang-types",` +
`                           "version": "2010-09-24",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-yang-types[`urn:ietf:params:xml:ns:yang:ietf-yang-types`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-inet-types",` +
`                           "version": "2010-09-24",` +
`                           "format": "yin",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-inet-types[`urn:ietf:params:xml:ns:yang:ietf-inet-types`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       },` +
`                       {` +
`                           "identifier": "ietf-inet-types",` +
`                           "version": "2010-09-24",` +
`                           "format": "yang",` +
`                           "namespace": "`urn:ietf:params:xml:ns:yang:ietf-inet-types[`urn:ietf:params:xml:ns:yang:ietf-inet-types`]`",` +
`                           "location": [` +
`                               "NETCONF"` +
`                           ]` +
`                       }` +
`                   ]` +
`               },` +
`               "statistics": {` +
`                   "netconf-start-time": "2014-07-01T07:23:55Z",` +
`                   "in-bad-hellos": 0,` +
`                   "in-sessions": 1,` +
`                   "dropped-sessions": 0,` +
`                   "in-rpcs": 10,` +
`                   "in-bad-rpcs": 0,` +
`                   "out-rpc-errors": 0,` +
`                   "out-notifications": 0` +
`               }` +
`           },` +
`           "netconf": {` +
`               "streams": {` +
`                   "stream": [` +
`                       {` +
`                           "name": "NETCONF",` +
`                           "description": "NETCONF Base Notifications",` +
`                           "replaySupport": true,` +
`                           "replayLogCreationTime": "2014-07-01T07:23:55Z"` +
`                       }` +
`                   ]` +
`               }` +
`           },` +
`           "nacm": {` +
`               "denied-operations": 0,` +
`               "denied-data-writes": 0,` +
`               "denied-notifications": 0` +
`           }` +
`    }`
