[[get-started]]
== Get Started

Welcome to Integration group, here are some steps might help you to get
started:

* Get an OpenDaylight account
https://identity.opendaylight.org/carbon/user-registration/index.jsp?region=region1&item=user_registration_menu[here],
you will need this to access opendaylight resources
* Sign up for discuss (general), infrastructure (ODL infra) and
integration-dev (us) mail lists
https://lists.opendaylight.org/mailman/listinfo[here]
* Jump on #opendaylight (general), #opendaylight-meetings (meetings) and
#opendaylight-integration (us) channels on link:IRC[ IRC]
* Join next available
CrossProject:Integration_Group:Meetings[Integration call] and present
youself
* Check out our tasks in
https://trello.com/#b/ACYMpTVD/opendaylight-integration-group[Trello].
You can register, be added to the board and edit the tasks
* Browse the CrossProject:Integration_Group[Integration wiki] and the
useful links below
* Try to
CrossProject:Integration_Group:Download_and_Run_System_Test[Download and
Run our Integration System Test]

[[links]]
== Links

List of useful links:

* https://wiki.opendaylight.org/view/File:ODL-diagram.pptx[OpenDaylight
Release Diagram]
*
OpenDaylight_Controller:Development_Infrastructure_Overview[Development
Infrastructure]
* CrossProject:Integration_Group:Code_Review_Process[ Code Review
Process]
* CrossProject:Integration_Group:Getting_Started_with_Robot[ Getting
Started with Robot]

Category:Integration Group[Category:Integration Group]
