These are athe Labs available at OpenDaylight:

[[linux-foundation-lab]]
== Linux Foundation Lab

This is the Lab used to run Continuous System Integration Test (CSIT).
It is maintained by Linux Foundation and uses OpenDaylight Integration
Jenkins for test automation.

* CrossProject:Integration_Group:ODL_Test_Lab[OpenDaylight Open Test
Lab]

[[community-labs]]
== Community Labs

Commnutity Labs are available for OpenDaylight test preparation and
debug. They can also be used to run test cases when these are difficult
to implement at LF because of: special SW requirements, some HW involved
like real switches or commercial test tools, or no Robot integration
posible. In this last case, the test cases can be manually executed or
automated through the Jenkins integration instruction below.

* CrossProject:Integration_Group:Test_Lab[Community Test Lab at
Ericsson]
* CrossProject:Integration_Group:East_Test_Lab[Community Test Lab at
Huawei]

[[lab-instructions]]
== Lab Instructions

* CrossProject:Integration_Group:Jenkins_Integration[Jenkins
Integration]

