The following Labs are available for OpenDaylight. If you would like to
have an OpenDaylight forwarder created for your Lab
(CommunityLab-Company@opendaylight.org) and be listed on the
http://www.opendaylight.org/developers/community-labs[Community Labs]
page of the OpenDaylight website, please contact
mailto:tbenzies@linuxfoundation.org[Todd Benzies]

[[linux-foundation-lab]]
== Linux Foundation Lab

This is the Lab used to run Continuous System Integration Test (CSIT).
It is maintained by Linux Foundation and uses OpenDaylight Integration
Jenkins for test automation.

* CrossProject:Integration_Group:ODL_Test_Lab[OpenDaylight Open Test
Lab]

[[community-labs]]
== Community Labs

Community Labs are available for OpenDaylight test preparation and
debug. They can also be used to run test cases when these are difficult
to implement at LF because of: special SW requirements, some HW involved
like real switches or commercial test tools, or no Robot integration
possible. In this last case, the test cases can be manually executed or
automated through the Jenkins integration instruction below.

* CrossProject:Integration_Group:Test_Lab[Community Test Lab at
Ericsson]
* CrossProject:Integration_Group:East_Test_Lab[Community Test Lab at
Huawei]
* CrossProject:Integration_Group:VCT_Lab[Spirent Community Test Lab at
Nephoscale]

[[lab-instructions]]
== Lab Instructions

* CrossProject:Integration_Group:Jenkins_Integration[Jenkins
Integration]

Category:Integration Group[Category:Integration Group]
