[[introduction]]
==== Introduction

This post shall capture tools, scripts and environment setup for
performance benchmarking. This is used more so with openflow performance
test but can be generalized for others. It would be ideal to have them
all running on the same machine, either local or lab setup. Lab setup
would be the best option, if possible.

Requirements:

* git
* maven
* python
* cbench
* gnu plot
* ubuntu/Mac setup
* ODL or openflow distribution

[[step1-clone-the-performance-scripts.]]
==== Step1 : Clone the performance scripts.

Clone the git repository which has the scripts and configuration for
performance test.

[[git-clone-httpsgist.github.com9837240.git]]
===== > git clone https://gist.github.com/9837240.git

Information on this repository is available in the link
https://gist.github.com/soyo42/9837240 . Thanks for michal rehak who
provided these scripts. Once you have cloned the repository you would
have the below files from the repository.

* .runCbench.config - This has the custom configurations for the cbench
run. We can set the controller location, port, loops, mspertest,
startupdelay, warmup, num of switches and more.
* generate3dGp.py - python script which takes the log files as input and
generates the out3d.plot file
* generateGp.py - python script which takes the log files as input and
generates the out.plot file
* howto - instructions to run the scripts
* processFolder.sh - script that runs generateGp for all the log files
* processFolder3d.sh - script that runs generate3dGp for all the log
files.
* runCbench.sh - script that runs the cbench over the supplied custom
configurations in the .runCbench.config

[[step-2-create-sym-link-for-the-oflops-folder.]]
==== Step 2 : Create sym link for the oflops folder.

This oflops folder is in the path /home/mininet for the virtual box
where the ubuntu machine is running. This is the same virtual box setup
which has the ubuntu with mininet and cbench installed.

[[create-symbolic-link-to-oflops-folder-so-that-cbench-executable-could-be-reached-like-this-oflopscbenchcbench]]
===== create symbolic link to oflops folder so, that cbench executable
could be reached like this oflops/cbench/cbench

[[ln--s-oflops]]
===== ln -s oflops

I have tried this step but it stills takes the current folder instead of
the /home/mininet, so I have copied the files from Step1 into the
/home/mininet folder so would not need to do this sym link step. If you
were able to setup this sym link then please update the steps here

[[step-3-run-the-cbench-tool]]
==== Step 3 : Run the cbench tool

Now run the cbench tool with the configurations that you have mentioned
in the .runCbench.config file.

[[homemininet.runcbench.sh-test-description-logfolder]]
===== /home/mininet>./runCbench.sh "test description" logFolder

This will run the cbench tool and store the log files in the logFolder.

[[step-4-generate-2d-or-3d-plot-data]]
==== Step 4 : Generate 2d or 3d plot data

Now run the processFolder script for generating 2d or 3d plot data.
Generate 2d plot data

[[homemininet.processfolder.sh-logfolder]]
===== /home/mininet>./processFolder.sh logFolder

Generate 3d plot data

[[homemininet-processfolder3d.sh-logfolder]]
===== /home/mininet> /processFolder3d.sh logFolder

[[step-5-install-the-gnuplot-graphing-utility]]
==== Step 5 : Install the gnuplot graphing utility

[[homemininet-sudo-apt-get-install-gnuplot]]
===== /home/mininet> sudo apt-get install gnuplot

If this results in some errors then try to update and then install again

[[homemininet-sudo-apt-get-update]]
===== /home/mininet> sudo apt-get update

Then try to install the gnuplot.

I received error that it could not fetch some archives in the virtual
box where I tried to run this command. If you were able to get around
with this problem then please update this step. I guess if you are
running this in ubuntu without the virtual box setup then it might work.

So the alternative that I have done was install gnuplot in my Mac. All
the previous steps 1 to 4 are run in my virtual box setup, only the
logFolder needs to be copied over to Mac to plot the chart.

[[step-5-alternative-alternative-step-if-step-5-does-not-work.-installing-gnuplot-in-the-mac.]]
==== Step 5-alternative: Alternative step if Step 5 does not work.
Installing gnuplot in the Mac.

Sorry windows folks, I have not tried this in windows. If you have tried
it then please add the step here as the alternative step. After some
googling, found the below links helpful to install the gnuplot in the
Mac.
http://mithunme.wordpress.com/2013/02/10/installing-gnuplot-in-mac-os-x/
http://bhou.wordpress.com/2011/09/13/how-to-install-gnuplot-in-mac-os-x-lion/
Both the links above have similar steps to install gnuplot. Follow the
instructions in the above links and you should have the gnuplot
installed in Mac.

Try out gnuplot to see if it works. sjc-vpn6-985:ODL lmukkama$ gnuplot

G N U P L O T Version 4.6 patchlevel 5 last modified February 2014 Build
System: Darwin x86_64

Copyright (C) 1986-1993, 1998, 2004, 2007-2014 Thomas Williams, Colin
Kelley and many others

gnuplot home: http://www.gnuplot.info faq, bugs, etc: type "help FAQ"
immediate help: type "help" (plot window: hit 'h')

Terminal type set to 'x11' gnuplot> Help topics available:

`                     2D                3D                automated` +
`   background        backwards         batch/interactive binary` +
`   bugs              canvas            circle            colornames` +
`   colorspec         commands          comments          complete` +
`   coordinates       datafile          datastrings       ellipse` +
`   enhanced          environment       examples          expressions`

Press return for more:

`   fonts             gd                glossary          gnuplot` +
`   gprintf           help-desk         if                image` +
`   introduction      iteration         line-editing      linecolor` +
`   linetypes         mixing_macros_backquotes            mouse` +
`   new-features      newhistogram      object            plotting` +
`   pm3d              polygon           pseudocolumns     quotes` +
`   rectangle         rgbcolor          set               show` +
`   startup           strings           substitution      syntax` +
`   time/date         unset             using             while` +
`   xticlabels` +
 +

[[step-6-run-gnuplot-to-generate-the-plot-for-analyzing-the-test-run-results.]]
==== Step 6 : Run gnuplot to generate the plot for analyzing the test
run results.

> gnuplot logFolder/out.plot OR > gnuplot logFolder/out3d.plot

Example Run:

cbench configurations: controller='192.168.56.1' port='6633' loops=20
msPerTest='10000' macPerSwitch=1000 startupDelay=100 warmup=1 swSet=( 16
)

After step 3 and 4: Attached the files generated for this run in
logFolder.zip file. This is just for your reference to verify your test
run.

gnuplot chart from Step 5: The data point run from above step is the
circle shown below. Once we run many test runs for different number of
switches or number of loops or any other parameter then we should get a
neat 2D or 3D graphs to analyze the data results to check on the
performance benchmark result.

File:Cbench_sample_run.png|Cbench sample run

3D plot of the performance results with total messages per sec VS loops
VS num of switches.

File:Cbench_gnuplot_sd.png|Cbench 3D plot Example.

Category:Integration Group[Category:Integration Group]
