[[maintainer]]
== Maintainer

Luis Gomez (ecelgp@gmail.com)

[[introduction]]
== Introduction

New test VM is available through the link below. The purpose of the VM
is to ease the task of developing/running integration/system test on the
OpenDaylight controller. Old test VMs are available on this
CrossProject:Integration_Group:Old_Test_VMs[ link].

[[test-environments]]
== Test environments

Test VM can be used in two scenarios:

* Self contain test: you have controller, mininet and robot framework
all running in the same VM. This is useful for verifying the tools
included in the VM and/or writing system test.
* External controller test: you can use tools like mininet, netopeer and
robot framework in the VM to test an external controller running on a
separate VM or platform. This is useful for developers to test their
builds or to validate a specific controller platform.

[[vm-description]]
== VM description

* VM disk: Ubuntu 14.04 desktop, 20GB HDD, ova file size=4GB
* Intalled SW: http://openjdk.java.net/[Java 1.7 OpenJDK],
http://www.opendaylight.org/software/downloads[OpenDaylight
Helium-SR1.1], http://www.getpostman.com[POSTMAN plugin with some
example collections], http://mininet.org/[mininet 2.1.0],
http://openvswitch.org/[Open vSwitch 2.0.2],
https://github.com/CPqD/ofsoftswitch13[CPqD ofsoftswitch13],
http://www.wireshark.org/[Wireshark 1.12.2 with OF1.3 dissectors],
https://code.google.com/p/netopeer[Netopeer Netconf server],
https://git.opendaylight.org/gerrit/gitweb?p=integration.git;a=tree[integration
test repository], http://robotframework.org[Robot framework 2.8.6],
http://github.com/robotframework/ride[RIDE
1.3],http://www.openflowhub.org/display/floodlightcontroller/Cbench+(New)[CBench]

[[link-to-vm]]
== Link to VM

*
https://wiki.opendaylight.org/images/HostedFiles/odl-test-desktop-4.ova[odl-test-desktop-4.ova]

[[installation-procedure]]
== Installation Procedure

[[prerequisites]]
=== Prerequisites

* https://www.virtualbox.org/[Virtualbox]
* For http://wiki.qemu.org/Main_Page[QEMU] you can find online
instructions on how to covert vmdk file to raw or qcow, normally you
will need to convert to intermediate vdi format using VBoxManage tool
* For VMware Player just install the ova file accepting any warning
* For VMware vCenter please remove this line from ovf fle:
virtualbox-2.2

[[installation-steps]]
=== Installation steps

1.  Download the VM ova file from link above
2.  Open VirtualBox and do import appliance
3.  Configure the VM with the following recommended settings
* _Processor:_ 4x CPU if you plan to run the controller in the VM, just
2 if you don't
* _RAM:_ 6GB if you plan to run the controller in the VM, or just 2GB if
you do not
* _Display:_ Disable 3D Acceleration otherwise left menu may not show
* _Network:_ 1x NIC, bridge mode is recommended, otherwise NAT (to share
your Internet connection) or host-only (creates internal network)
4.  Start the VM
5.  Login with mininet/mininet
6.  Open README.txt

[[using-the-vm]]
=== Using the VM

The VM contains the following (see README.txt file):

-----------------------------------------------------------------------------------------
OpenDaylight test VM
--------------------
Prepared by Luis Gomez (ecelgp@gmail.com)

This VM contains the following:

1) OpenDaylight release editions:

~/controller-Helium-SR1.1/ -> Helium SR1.1

Note: to run controller just go to distribution folder and type bin/karaf. Be aware that 
controller comes with no feature installed. In order to install a feature or deal with
Karaf check https://wiki.opendaylight.org/view/CrossProject:Integration_Group:karaf

2) Postman app (REST client)

Start Postman from Desktop launcher or Chrome apps page.

Note: there are a few collections for OpenDaylight stored for your reference.

3) Mininet 2.1 with OVS 2.0.2 and CPqD (OpenFlow switch):

sudo mn --controller=remote,ip=127.0.0.1 --topo tree,2 -> starts mininet OVS OF1
0 on local controller

sudo mn --controller=remote,ip=127.0.0.1 --topo tree,2 --switch ovsk,protocols=O
penFlow13 -> starts mininet OVS OF13 on local controller

sudo mn --controller=remote,ip=127.0.0.1 --topo tree,2 --switch user -> starts m
ininet CPqD on local controller

4) Wireshark 1.12.2 (Packet capture):

sudo wireshark &

5) Netopeer (Netconf server):

Note: It runs by default on ssh port 830, more information can be found in https
://wiki.opendaylight.org/view/OpenDaylight_Controller:Config:Examples:Netconf

6) Integration tests (Robot Framework):

~/integration/test/csit/suites/ -> Robot suites folder

Note: Information on how to run these suites can be found in https://wiki.openda
ylight.org/view/CrossProject:Integration_Group:Download_and_Run_System_Test

7) Robot IDE (RIDE):

Start RIDE from Desktop launcher

Note: you can use RIDE to edit or create robot tests
-----------------------------------------------------------------------------------------

You can update controller SW to latest available, please check
CrossProject:Integration_Group:Controller_Artifacts[ Controller
Artifacts wiki]

Also make sure to update the integration repo time to time by issuing
this commands:

----------------------------------
mininet@mininet:~\> cd integration
mininet@mininet:~\> git pull
----------------------------------

For more information on how to download and run system test, please
check this CrossProject:Integration_Group:Download_and_Run_System_Test[
wiki]

If you want to know more about system test and what tests are available,
please click CrossProject:Integration_Group:CSIT[here]

Category:Integration Group[Category:Integration Group]
