[[what-is-robot-framework]]
== What is Robot Framework

[[maintainer]]
== Maintainer

Carol Sanders (csanders@brocade.com)

Robot Framework is a Keyword Driven automation framework using Python or
Java as it's back-end. Test cases are automated by writing steps using
Robot framework keywords.

*Robot Framework Provides*

* Provides a simple library API for creating customized test libraries.
* Provides a command line interface and XML based outputs for
integration into existing build infrastructure (continuous integration
systems).
* Report files created as a result of every pybot execution:
report.html, log.html, output.xml.
* Implemented with Python
* Runs also on Jython (JVM) and IronPython (.NET)
* Can be extended natively using Python or Java
* Other languages supported via a remote interface
* Open source
* – Apache 2.0 license
* – Active development and growing community

* Robot Framework Tests and Test suites hierarchy

Robot Framework test cases are created using test case tables in test
case files. A collection of test cases is called a test suite. The test
cases in this example couple be contained in one .txt or robot format
file or many. Test case files can be organized into directories, and
these directories create higher-level test suites. A test suite created
from a directory cannot have any test cases directly, but it contains
other test suites with test cases, instead. These directories can then
be placed into other directories creating an even higher-level suite.
There are no limits for the structure, so test cases can be organized as
needed.

When a test directory is executed, the files and directories it contains
are processed recursively as follows: Files and directories with names
starting with a dot (.) or an underscore (_) are ignored. Directories
with the name CVS are ignored (case-sensitive). Files not having one of
the recognized extensions (.html, .xhtml, .htm, .tsv, .txt, .rst, or
.rest) are ignored (case-insensitive). Other files and directories are
processed. If a file or directory that is processed does not contain any
test cases, it is silently ignored (a message is written to the syslog)
and the processing continues.

[[test-case-test-suite-format]]
== Test Case / Test suite Format

Files not having one of the recognized extensions (.html, .xhtml, .htm,
.tsv, .txt, .rst, or .rest) are ignored (case-insensitive). Plain text
format is most commonly used for internal testing.

* Plain text format

The plain text format can use either two or more spaces or a pipe
character surrounded with spaces ( | ) to separate test data. The test
data tables must have one or more asterisk before their names. Otherwise
asterisks and possible spaces in the table header are ignored so, for
example, *** Settings *** and *Settings work the same way. Everything
before the first table is ignored.

http://robotframework.googlecode.com/hg/doc/userguide/RobotFrameworkUserGuide.html?r=2.8.4#test-data-syntax

* How to wirite good test cases:

https://code.google.com/p/robotframework/wiki/HowToWriteGoodTestCases

[[test-execution]]
== Test Execution

pybot|jybot|ipybot [options] data_sources python|jython|ipy -m robot.run
[options] data_sources python|jython|ipy path/to/robot/run.py [options]
data_sources java -jar robotframework.jar [options] data_sources

Test execution is normally started using pybot, jybot or ipybot runner
script. These scripts are otherwise identical, but the first one
executes tests using Python, the second using Jython, and the last one
using IronPython.

Alternatively it is possible to use robot.run entry point either as a
module or a script using any interpreter, or use the standalone JAR
distribution. Regardless of execution approach, the path (or paths) to
the test data to be executed is given as an argument after the command.
Additionally, different command line options can be used to alter the
test execution or generated outputs in some way.

* Specifying test data to be executed

Robot Framework test cases are created in files and directories, and
they are executed by giving the path to the file or directory in
question to the selected runner script. The path can be absolute or,
more commonly, relative to the directory where tests are executed from.
The given file or directory creates the top-level test suite, which gets
its name, unless overridden with the --name option, from the file or
directory name. Different execution possibilities are illustrated in the
examples below.

Note that in these examples, as well as in other examples in this
section, only the pybot script is used, but other execution approaches
could be used similarly.

pybot test_cases.html pybot path/to/my_tests/ pybot c:\robot\tests.txt
It is also possible to give paths to several test case files or
directories at once, separated with spaces. In this case, Robot
Framework creates the top-level test suite automatically, and the
specified files and directories become its child test suites. The name
of the created test suite is got from child suite names by catenating
them together with an ampersand (&) and spaces. For example, the name of
the top-level suite in the first example below is My Tests & Your Tests.
These automatically created names are often quite long and complicated.
In most cases, it is thus better to use the --name option for overriding
it, as in the second example below:

pybot my_tests.html your_tests.html pybot --name Example
path/to/tests/pattern_*.html

[[using-command-line-options]]
== Using command line options

Robot Framework provides a number of command line options that can be
used to control how test cases are executed and what outputs are
generated. This section explains the option syntax, and what options
actually exist. How they can be used is discussed elsewhere in this
chapter.

* Using options

When options are used, they must always be given between the runner
script and the data sources. For example: pybot -L debug my_tests.txt
pybot --include smoke --variable HOST:10.0.0.42 path/to/tests/

* Short and long options

Options always have a long name, such as --name, and the most frequently
needed options also have a short name, such as -N. In addition to that,
long options can be shortened as long as they are unique. For example,
--logle DEBUG works, while --lo log.html does not, because the former
matches only --loglevel, but the latter matches several options. Short
and shortened options are practical when executing test cases manually,
but long options are recommended in start-up scripts, because they are
easier to understand.

The long option format is case-insensitive, which facilitates writing
option names in an easy-to-read format. For example, --SuiteStatLevel is
equivalent to, but easier to read than --suitestatlevel.

Setting option values Most of the options require a value, which is
given after the option name. Both short and long options accept the
value separated from the option name with a space, as in --include tag
or -i tag. With long options, the separator can also be the equals sign,
for example --include=tag, and with short options the separator can be
omitted, as in -itag. Some options can be specified several times. For
example, --variable VAR1:value --variable VAR2:another sets two
variables. If the options that take only one value are used several
times, the value given last is effective.

Simple patterns Many command line options take arguments as simple
patterns. These glob-like patterns are matched according to the
following rules: •* is a wildcard matching any string, even an empty
string. •? is a wildcard matching any single character. •Unless noted
otherwise, pattern matching is case, space, and underscore insensitive.

Examples: --test Example* # Matches tests with name starting 'Example',
case insensitively. --include f?? # Matches tests with a tag that starts
with 'f' or 'F' and is three characters long. Tag patterns Most tag
related options accept arguments as tag patterns. They have all the same
characteristics as simple patterns, but they also support AND, OR and
NOT operators explained below. These operators can be used for combining
two or more individual tags or patterns together. AND or & The whole
pattern matches if all individual patterns match. AND and & are
equivalent. --include fooANDbar # Matches tests containing tags 'foo'
and 'bar'. --exclude xx&yy&zz # Matches tests containing tags 'xx',
'yy', and 'zz'. OR The whole pattern matches if any individual pattern
matches. --include fooORbar # Matches tests containing either tag 'foo'
or tag 'bar'. --exclude xxORyyORzz # Matches tests containing any of
tags 'xx', 'yy', or 'zz'. NOT

The whole pattern matches if the pattern on the left side matches but
the one on the right side does not. If used multiple times, none of the
patterns after the first NOT must not match. --include fooNOTbar #
Matches tests containing tag 'foo' but not tag 'bar'. --exclude
xxNOTyyNOTzz # Matches tests containing tag 'xx' but not tag 'yy' or tag
'zz'. Mixed

The above operators can also be used together. The operator precedence,
from highest to lowest, is AND, OR and NOT. --include xANDyORz # Matches
tests that contain either tags 'x' and 'y', or tag 'z'. --include
xORyNOTz # Matches tests that contain either tag 'x' or 'y', but not tag
'z'. --include xNOTyANDz # Matches tests that contain tag 'x', but not
tags 'y' and 'z'.

Note All operators are case-sensitive and must be written with capital
letters.

Note OR operator is new in Robot Framework 2.8.4.

[[how-to-write-a-test-case]]
== *How To Write a Test Case*

* Use Robot Ride to create test suites and test cases for organization
and correct Test case syntax. Test suites creation will be easier and
more intuitive and including all the sections easier.
* Test suites must contain the following sections:

`           Suite Setup and Tear Down, Resource file(s), Variables file, Well defined Keywords, Test Case(s) `

[[example-test-suite]]
== *Example Test Suite*

[[best-practices]]
== *Best Practices*

Test Case and Test Suite Automation Best Practices

CrossProject:Integration_Group:Test_Code_Guidelines[Full Details Here]

* Documentation is important
* Use BuiltIn "Log" Keyword in appropriate places to aid in debugging
* Test one attribute of the feature not many attributes
* Every test case should have a tag to enable/disable test case run
* Avoid Sleeps
* Use Resource files if your keywords span more than one test case
* Under Consideration (Use an initialization file __init_.txt to start
services or systems needed for the tests)

* Do not hard code values
* Shorter test cases are better
* Clean up environment before and after each test suite.

