[[overview]]
== Overview

WCBench is a set of scripts, with CBench at its core, that benchmark the
performance of OpenDaylight. They build on CBench by automating all
install and configuration steps, storing results in a more useful
format, adding functionally for getting more reliable results and
supporting statistical analysis.

[[code-location]]
== Code Location

The WCBench code, its full commit history and the bug tracker (GitHub
Issues) are hosted at
https://github.com/dfarrell07/wcbench[dfarrell07/wcbench].

WCBench is also hosted in the ODL Integration team's Git repo, under
https://github.com/opendaylight/integration/tree/master/test/tools/cbench_regression[integration/test/tools/cbench_regression].

The code at https://github.com/dfarrell07/wcbench[dfarrell07/wcbench]
will be updated more frequently, and should considered the authoritative
version. Updates will be made to
https://github.com/opendaylight/integration/tree/master/test/tools/cbench_regression[integration/test/tools/cbench_regression],
but they will typically only occur for version bumps and/or particularly
important changes.

[[detailed-usage]]
== Detailed Usage

The https://github.com/dfarrell07/wcbench#usage[Usage section] of the
https://github.com/dfarrell07/wcbench/blob/master/README.md[README] in
the https://github.com/dfarrell07/wcbench[codebase] provides detailed
usage information for all scripts. In order to avoid duplication (and
the associated increased maintenance overhead), please read it there and
don't unnecessarily duplicate information in this wiki.

[[detailed-walkthrough]]
== Detailed Walkthrough

See the
https://github.com/dfarrell07/wcbench#detailed-walkthrough[Detailed
Walkthrough section] of the README in the
https://github.com/dfarrell07/wcbench[codebase].
