[[prepare-the-environment]]
= Prepare the Environment

[[run-opendaylight-controller-with-the-topoprocessing-plugin]]
== Run OpenDaylight controller with the topoprocessing plugin

1.  Download or clone the *topoprocessing* project
+
::
  GettingStarted:Pulling, Hacking, and Pushing All the Code from the CLI[GettingStarted:Pulling,
  Hacking, and Pushing All the Code from the CLI]

1.  Build the project
+
::
  `cd topoprocessing`
  +
  `mvn clean install`

1.  Extract the build
+
::
  You can find the archive here:
  +
  *
  `topoprocessing/distribution-karaf/target/distribution-karaf-0.0.1-SNAPSHOT.zip`
  *
  `topoprocessing/distribution-karaf/target/distribution-karaf-0.0.1-SNAPSHOT.tar.gz`

#: Or download the latest one here:

#:*
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/topoprocessing/distribution-karaf/0.0.1-SNAPSHOT/

1.  Run it
+
::
  `cd <extracted directory>/bin`
  +
  `./karaf` or use `karaf.bat`

[[enable-the-restconf-feature]]
== Enable the Restconf feature

Check if `odl-restconf` feature is installed. You can use the command
for listing all installed features.

---------------
feature:list -i
---------------

If not then install it:

----------------------------
feature:install odl-restconf
----------------------------

[[debug]]
== Debug

1.  Set dubug
+
::
---------------------
log:set LEVEL PACKAGE
---------------------
  +
  eg.:
  +
--------------------------------------------------
log:set DEBUG org.opendaylight.topoprocessing.impl
--------------------------------------------------

1.  Show log
+
::
--------
log:list
--------
  +
--------
log:tail
--------

[[comunicating-with-the-restconf]]
== Comunicating with the RestConf

https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en[Install
Postman for Chrome]

Set headers:

Content-Type::
  application/xml
Accept: application/xml +
username::
  admin
password::
  admin
Use URL::
  http://localhost:8181/restconf/config/network-topology:network-topology
method::
  POST

[[restconf-queries]]
= RestConf queries

[[new-configuration-request]]
== New configuration request

` ` +
`   ``"mytopo:1"``  ` +
`     ` +
`       ` +
`         ``equality` +
`         ``node` +
`             ` +
`               ` +
`                 ``"openflow:1"` +
`                 ``"path1"` +
`               ` +
`               ` +
`                 ``"bgp:1"` +
`                 ``"path2"` +
`               ` +
`             ` +
`       ` +
`     ` +
` `
