This page is a collection of topics of that are of interest to
developers for Open DOVE and topics coming from the development of Open
DOVE that might be of interest to OpenDaylight developers.

[[general-topics]]
== General Topics

* oDMC: Using MOXy as the JAXB provider[oDMC: Using MOXy as the JAXB
provider]
* link:Mapping from Neutron to OpenDove[Mapping from Neutron to
OpenDove]

[[code-structure]]
== Code Structure

* link:oDMC Bundle Structure[oDMC Bundle Structure]
* link:oDCS Code Structure[oDCS Code Structure]
* link:oDGW Code Structure[oDGW Code Structure]
* link:OVS-Agent Code Structure[OVS-Agent Code Structure]

[[building-dove-components]]
== Building Dove Components

First pull the OpenDove code with

------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/opendove.git
------------------------------------------------------------------

[[building-the-odmc]]
=== Building the oDMC

From the opendove directory, simply execute:

-----------------
mvn clean install
-----------------

[[building-the-odcs]]
=== Building the oDCS

Prerequisites: Any RedHAT type system (Ubuntu or Fedora works just fine
though you may need to download some packages depending on your
environment, e.g., python-dev, libjansson-dev, libevent-dev, openssl).

READ the README_PYTHON file and download the necessary files.

The os_distributor_script file must be made executable (chmod +x)

Use "make" to build - The executable files and .pyc scripts end up in
the "build" directory. Use "make clean" to delete the compiled files.

[[building-the-odgw]]
=== Building the oDGW

Complex enough to have it's own page:

* link:Building the oDGW[Building the oDGW]

[[building-the-ovs-agent]]
=== Building the OVS-Agent

The agent needs to be compiled with the openvswitch source code (release
2.0.0)

You may use the getdeps.sh script in the opendove/third-party directory
to download and build Open vSwitch.

1.  Ensure the the Open DOVE Connectivity Server objects are built (run
'make' in the opendove/odcs directory).
2.  Run 'make' in the ovs-agent directory

