[[project-name-opendove]]
== Project Name: OpenDOVE

[[components]]
=== Components

[[odmc-opendove-management-controller]]
==== oDMC (OpenDove Management Controller)

This component, packaged as part of the virtualization edition of
OpenDaylight, provides both a control and access point into the OpenDOVE
management plane.

[[odcs-opendove-connectivity-server]]
==== oDCS (OpenDove Connectivity Server)

This component, packaged as an rpm in the supporting VM, provides the
control point for the OpenDOVE control plane.

[[odgw-opendove-gateway]]
==== oDGW (OpenDove Gateway)

Provides gateway functionality (encap/decap/NAT) between the overlay and
the outside world. It is packaged as an rpm in the supporting VM.

[[ovs-agent-opendove-ovs-agent]]
==== OVS-Agent (OpenDove OVS Agent)

Provides interface between OVS and OpenDove control plane. It is
packaged as an rpm in the supporting VM

[[features]]
== Features

* Network virtualization: the ability to create isolated networks for
subsets of hosts
* Connectivity policy: the ability to define whether isolated networks
should be able to communicate with each other
* External connectivity: the ability to allow isolated networks to talk
to the outside world via static routes, SNAT, or DNAT

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

Your project / feature should be included in the appropriate
link:Release/Hydrogen[Hydrogen Release Guides and Documentation]:

* Open_Dove:Installation[Installation Guide(s)]
* Open_Dove:How_To_Use[User Guide(s)]
* Open_DOVE:Developer Pages[Developer Guide(s)]
* Open_DOVE:API[OpenDove APIs]
* There is also an IRC channel (#opendove) available for discussion of
issues and extensions...

[[architectural-issues]]
== Architectural Issues

Unfortunately, the OpenDOVE Gateway will not be available for download
by the official release. Instructions and source to build it are
forthcoming.

[[security-considerations]]
== Security Considerations

None known.

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

Open DOVE has been extensively tested via manual configuration of
virtual networks and "canary in the coal mine"-style tests. Automated
integration testing was inhibited by the complexity of managing multiple
VMs to act as the network. These tests an unit testing are a target for
the next release.

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

This is the first release of Open DOVE, so no features have been EOLed.

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

* No
https://bugs.opendaylight.org/buglist.cgi?query_format=specific&order=relevance%20desc&bug_status=__open__&product=opendove&list_id=3343[open
bugs] listed as of 1/31/2014.

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

* Open DOVE implements the VXLAN packet encapsulation format, but not
the VXLAN control plane.

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)

* At the moment, we will not be able to release the Open DOVE Gateway
for non-technical reasons. We hope to resolve this issue soon.

