These tasks all assume that the oDMC is up and running

[[configure-odcs-with-odmc-address]]
=== Configure oDCS with oDMC address

1.  Start oDCS with ./build/dcs_server.py
2.  Log in as Developer with password "Hook&Ladder"
3.  Point oDCS at oDMC with "controller_add 8080"

[[enable-odcs-role]]
=== Enable oDCS Role

1.  Issue a GET request to
http://:8080/controller/nb/v2/opendove/odmc/serviceAppliances
2.  In response, copy out the uuid of the oDCS and issue a PUT request
to http://:8080/controller/nb/v2/opendove/odmc/odcs//role with the
following JSON body:

` { "service_appliance": { "isDCS": true } }`

[[configure-odgw-with-odmc-address]]
=== Configure oDGW with oDMC address

1.  Start oDGW with build/dove_gateway.py from the dgadmin directory
2.  log in with password "admin"
3.  Point oDGW at oDMC with "service dmcadd 8080"

[[enable-odgw-role]]
=== Enable oDGW Role

1.  Issue a GET request to
http://:8080/controller/nb/v2/opendove/odmc/serviceAppliances
2.  In response, copy out the uuid of the oDGW and issue a PUT request
to http://:8080/controller/nb/v2/opendove/odmc/odgw//role with the
following JSON body:

` { "service_appliance": { "isDGW": true } }`

[[configure-odgw-dove-tunnel-interface]]
=== Configure oDGW Dove Tunnel Interface

1.  Issue a PUT request to
http://:8080/controller/nb/v2/opendove/odmc/odgw//ipv4 with the
following JSON body:

` { "gw_ipv4_assignment": {  "ip": "``", "nexthop": "``", "mask": "``", "vlan": 0, "intf_type":` +
`   "dovetunnel" } }`

1.  At oDGW verify the address has been added with "service show"

[[start-ovs-agent]]
=== Start OVS-Agent

At each host with OVS and the OVS-Agent installed, start the OVS-Agent
with ./dove-controller ptcp: -d
