[[technical-architecture]]
== Technical Architecture

FIXME: add a high-level picture of what we BGP/LS and PCEP do. A
detailed description of the project likely including both high-level and
lower-level architecture diagrams

[[configuration]]
== Configuration

* For basic configuration see BGP LS PCEP:User Guide[User Guide]

[[tutorial-how-to]]
== Tutorial / How-To

[[introduction]]
=== Introduction

An extension to a protocol means basically adding parsers and
serializers for new elements, such as messages, objects, tlvs or
subobjects. This is usually necessary when you are extending the
protocol with another RFC or draft. Both BGP and PCEP parsers are
pluggable and you can specify which extensions to load alongside to the
base parser in the configuration file.

[[writing-an-extension-to-pce-protocol]]
==== Writing an extension to PCE protocol

[[current-standards-support]]
===== Current standards support

Current pcep base-parser implementation supports following RFCs:

*http://tools.ietf.org/html/rfc5440[RFC5440]* - Path Computation Element
(PCE) Communication Protocol (PCEP) +
*http://tools.ietf.org/html/rfc5541[RFC5541]* - Encoding of Objective
Functions in the Path Computation Element Communication Protocol
(PCEP) +
*http://tools.ietf.org/html/rfc5455[RFC5455]* - Diffserv-Aware
Class-Type Object for the Path Computation Element Communication
Protocol +
*http://tools.ietf.org/html/rfc5521[RFC5521]* - Extensions to the Path
Computation Element Communication Protocol (PCEP) for Route Exclusions +
*http://tools.ietf.org/html/rfc5557[RFC5557]* - Path Computation Element
Communication Protocol (PCEP) Requirements and Protocol Extensions in
Support of Global Concurrent Optimization +
 There are already two extensions for: +
*http://tools.ietf.org/html/draft-ietf-pce-stateful-pce[draft-ietf-pce-stateful-pce]*
- in versions 02 and 07 +
*http://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp[draft-ietf-pce-pce-initiated-lsp]*
- versions crabbe-initiated-00 and ietf-initiated-00 +

`    ``${project.groupId}` +
`    ``pcep-ietf-stateful02` +

 +
`    ``${project.groupId}` +
`    ``pcep-ietf-stateful07` +

Note, that they extend each other, so it is vital to load the extensions
with compatible versions. In this case crabbe-initiated-00 is compatible
with stateful-02 and ietf-initiated-00 is compatible with stateful-07.

[[how-to-implement-an-extension-to-pcep]]
===== How to implement an extension to PCEP

* Create a separate artefact (eclipse project) for your extension. Make
sure it depends on pcep-api and pcep-spi.

* Write yang model for new elements or augment existing ones. Perform
'mvn install' to generate files from the model.

* Write parsers and serializers. All parsers need to implement *Parser
and *Serializer interfaces from pcep-spi (e.g. if you are writing a new
TLV, your parser should implement TlvParser and TlvSerializer). Add
Activator, that extends AbstractPCEPExtensionProviderActivator, where
you register your parsers and serializers.

[[update-configuration]]
====== Update configuration

* Update
https://jenkins.opendaylight.org/integration/view/Integration%20jobs/job/integration-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/serviceprovider/target/distributions-serviceprovider-0.1.1-SNAPSHOT-osgipackage/opendaylight/configuration/initial/32-pcep.xml[32-pcep.xml].
Register your parser as a module in pcep-impl:

 +
`   ``prefix:pcep-parser-new-parser` +
`   ``pcep-parser-new-parser` +

* Add it as an extension to pcep-parser-base:

 +
`   ``pcepspi:extension` +
`   ``pcep-parser-new-parser` +

* Add it's instance to services:

 +
`   ``pcep-parser-new-parser` +
`   ``/config/modules/module[name='pcep-parser-new-parser']/instance[name='pcep-parser-new-parser']` +

* Update odl-pcep-impl-cfg.yang so that it generates Module and
ModuleFactory classes for your new parser.

`identity pcep-parser-new-parser {` +
`   base config:module-type;` +
`   config:provided-service spi:extension;` +
`   config:java-name-prefix NewParserPCEPParser;` +
`}`

`augment "/config:modules/config:module/config:configuration" {` +
`   case pcep-parser-new-parser {` +
`       when "/config:modules/config:module/config:type = 'pcep-parser-new-parser'";` +
`   }` +
`}`

Run mvn install on pcep-impl-config to generate Module and ModuleFactory
files.

* Update Module to start your NewParserPCEPParserModule.java whent it's
created.

`@Override` +
`public java.lang.AutoCloseable createInstance() {` +
`   return new InitiatedActivator();` +
`}`

[[writing-an-extension-to-bgp]]
==== Writing an extension to BGP

[[current-standards-support-1]]
===== Current standards support

Current bgp base-parser implementation supports following RFCs:

*http://tools.ietf.org/html/rfc4271[RFC4271]* - A Border Gateway
Protocol 4 (BGP-4) +
*http://tools.ietf.org/html/rfc4724[RFC4724]* - Graceful Restart
Mechanism for BGP +
*http://tools.ietf.org/html/rfc4760[RFC4760]* - Multiprotocol Extensions
for BGP-4 +
*http://tools.ietf.org/html/rfc1997[RFC1997]* - BGP Communities
Attribute +
*http://tools.ietf.org/html/rfc4360[RFC4360]* - BGP Extended Communities
Attribute +
*http://tools.ietf.org/html/rfc6793[RFC6793]* - BGP Support for
Four-Octet Autonomous System (AS) Number Space (NEW speaker only) +
 There is already one extension for: +
*http://tools.ietf.org/html/draft-ietf-idr-ls-distribution[draft-ietf-idr-ls-distribution]*
- in version 04 +

 +
`   ``${project.groupId}` +
`   ``bgp-linkstate` +

[[how-to-implement-an-extension-to-bgp]]
===== How to implement an extension to BGP

* Create a separate artefact (eclipse project) for your extension. Make
sure it depends on pcep-api and pcep-spi.

* Write yang model for new elements or augment existing ones. Perform
'mvn install' to generate files from the model.

* Write parsers and serializers. All parsers need to implement *Parser
and *Serializer interfaces from bgp-spi (e.g. if you are writing a new
Capability, your parser should implement CapabilityParser and
CapabilitySerializer).

* Add Activator, that extends AbstractBGPExtensionProviderActivator,
where you register your parsers and serializers. If your extension adds
another AFI/SAFI you also habe to add another Activator that extends
AbstractRIBExtensionProviderActivator and registrate new address family
and subsequent address family.

[[update-configuration-1]]
====== Update configuration

* Update
https://jenkins.opendaylight.org/integration/view/Integration%20jobs/job/integration-project-centralized-integration/lastSuccessfulBuild/artifact/distributions/serviceprovider/target/distributions-serviceprovider-0.1.1-SNAPSHOT-osgipackage/opendaylight/configuration/initial/31-bgp.xml[31-bgp.xml].
Register your parser as a module in bgp-impl:

 +
`   ``prefix:bgp-new-parser` +
`   ``bgp-new-parser` +

* Add it as an extension to bgp-parser-base:

 +
`   ``bgpspi:extension` +
`   ``bgp-new-parser` +

* Add it's instance to services:

 +
`   ``bgp-new-parser` +
`   ``/modules/module[type='bgp-new-parser'][name='bgp-new-parser']` +
 +

Also, if you are introducing new AFI/SAFI, don't forget to registrate
your extension also to RIB.

* Create your own configuration file so that it generates Module and
ModuleFactory classes for your new parser.

`identity bgp-new-parser {` +
`       base config:module-type;` +
`       config:provided-service bgpspi:extension;` +
`       config:provided-service ribspi:extension; // for new AFI/SAFI` +
`       config:java-name-prefix NewParser;` +
`}`

`augment "/config:modules/config:module/config:configuration" {` +
`       case bgp-new-parser {` +
`               when "/config:modules/config:module/config:type = 'bgp-new-parser'";` +
`       }` +
`}`

Run mvn install on your extension artefact to generate Module and
ModuleFactory files.

* Update Module to start your NewParserModule.java whent it's created.

`@Override` +
`public java.lang.AutoCloseable createInstance() {` +
`   return new NewParserActivator();` +
`}`

[[programmatic-interfaces]]
== Programmatic Interface(s)

* Howto pull code from gerrit:
OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_the_CLI +
* Gerrit repository: https://git.opendaylight.org/gerrit/bgpcep[gerrit]
* Bugzilla: https://bugs.opendaylight.org/[Bugzilla]

* Mailing lists

::
  _bgpcep-bugs@opendaylight.org_ +
  +
  _bgpcep-dev@opendaylight.org_ +
  +
  _bgpcep-gerrit@opendaylight.org_ +

* YANG Models - BGP LS PCEP:Models[BGP LS PCEP:Models]

* API Documentation –
https://jenkins.opendaylight.org/bgpcep/job/bgpcep-nightly/lastSuccessfulBuild/artifact/target/staging/releasepom/apidocs/index.html[Javadoc
API]

For debugging purposes, set lower log levels for bgpcep project in
logback.xml .


