[[features]]
== Features

* Second release of BGP protocol library, with BGP listener/speaker
support for BGP MP and linkstate
* Second release of PCEP protocol library, with base RFC5440, Stateful,
Initiated and segment routing extensions, in two different revisions
* Model-driven protocols, e.g. there are models for each protocol's
messages
* Integrated export of gleaned data into MD-SAL
* Programming pipeline and scheduling prototype

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

* BGP_LS_PCEP:Helium_Release_Notes[Release Notes]
* BGP_LS_PCEP:Helium_User_Guide[User Guide]
* BGP_LS_PCEP:Helium_Developer_Guide[Developer Guide]
* BGP_LS_PCEP:Helium_How-To's/Tutorials[How-To's/Tutorials]
* BGP_LS_PCEP:Helium_Operations_Guide[Operations Guide]

https://git.opendaylight.org/gerrit/11533 - ascii doc commit

[[architectural-issues]]
== Architectural Issues

* The configuration is non-trivial and while giving the end-user control
over the details how the protocols operate, it also means there is a
steep learning curve
* Some components within BGPCEP could probably be restructured (e.g. RIB
module handling also BGP session negotiation)

[[security-considerations]]
== Security Considerations

* There is no support for any form of session authentication. Both
protocols support TCP MD5 authentication.
* North-bound access to data is completely unrestricted and
unauthenticated. Data dissemination policies are expected to be defined
on the MD-SAL boundary and/or applications.

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

* The code is covered by unit tests, test coverage is tracked in
https://sonar.opendaylight.org/dashboard/index/org.opendaylight.bgpcep:releasepom[Sonar]

Helium release marks 80,3% of unit test coverage (87,4% line coverage,
63,6% branch coverage)

* Sonar also reports technical debt issues

Helium release marks 171 issues (30d of technical debt)

* BGP code has been tested to interoperate with various implementations
and its exposed information checked through RESTCONF. The
interoperability is summarized in IETF draft:

https://tools.ietf.org/html/draft-gredler-idr-ls-distribution-impl-01[draft-gredler-idr-ls-distribution-impl]

* BGP speaker functionality was tested locally as a prototype and it's
also used in project ODL-SDNi App:Main[ODL-SDNi]
* PCEP code has been tested with one commercial implementation, session
establishment, as well as LSP operations.
* Both protocols have integration as well as performance and scale tests
implemented with commercial product. In further release the team will
recreate those tests with opensource implementations and add them to ODL
integration project.

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

There are no EOL APIs nor features in this release.

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

The project tracks mainly enhancements, which can be categorized as
follows:

* code cleanups and reorganization: 2 issues (#731, #1025)
* new features: 5 issues (#139, #196, #608, #989, #2064)
* missed feature: 1 issue (#105)
* testing improvement: 2 issues (#110. #1530)
* karaf performance bug: 1 issue (#2027)

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

* https://tools.ietf.org/html/rfc4271[RFC4271] - A Border Gateway
Protocol 4 (BGP-4)
* https://tools.ietf.org/html/rfc4760[RFC4760] - Multiprotocol
Extensions for BGP-4
* https://tools.ietf.org/html/rfc1997[RFC1997] - BGP Communities
Attribute
* https://tools.ietf.org/html/rfc4360[RFC4360] - BGP Extended
Communities Attribute
* https://tools.ietf.org/html/rfc6793[RFC6793] - BGP Support for
Four-Octet Autonomous System (AS) Number Space
*
https://tools.ietf.org/html/draft-ietf-idr-ls-distribution-04[draft-ietf-idr-ls-distribution-04]
- North-Bound Distribution of Link-State and TE Information using BGP
* https://tools.ietf.org/html/rfc5440[RFC5440] - Path Computation
Element (PCE) Communication Protocol (PCEP)
* https://tools.ietf.org/html/rfc5541[RFC5541] - Encoding of Objective
Functions in the Path Computation Element Communication Protocol (PCEP)
* https://tools.ietf.org/html/rfc5455[RFC5455] - Diffserv-Aware
Class-Type Object for the Path Computation Element Communication
Protocol
* https://tools.ietf.org/html/rfc5521[RFC5521] - Extensions to the Path
Computation Element Communication Protocol (PCEP) for Route Exclusions
* https://tools.ietf.org/html/rfc5557[RFC5557] - Path Computation
Element Communication Protocol (PCEP) Requirements and Protocol
Extensions in Support of Global Concurrent Optimization
* Stateful extensions to the Path Computation Element Protocol, December
2012
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-02[draft-ietf-pce-stateful-pce-02]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-crabbe-pce-pce-initiated-lsp-00[draft-crabbe-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model
* Stateful extensions to the Path Computation Element Protocol, December
2013
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce-07]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-00[draft-ietf-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model
* Segment routing extension to the Path Computation Element Protocol,
October 2013
**
https://tools.ietf.org/html/draft-sivabalan-pce-segment-routing-02[draft-sivabalan-pce-segment-routing-02]
- PCEP Extension for segment routing
**
https://tools.ietf.org/html/draft-sivabalan-pce-lsp-setup-type-01[draft-sivabalan-pce-lsp-setup-type-01]
- PCEP Extension for path setup type

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)

The project's schedule slipped a bit during M3 phase, the cause was a
demand on fully working pcep stateful in version 07 (which was
implemented but not fully tested). The consequence was a delay in
delivering BGP speaker. All slips have been eliminated by M5 and from
this point, the project is on track.
