[[major-features]]
=== Major Features

Helium release of BGPCEP project delivers the support for the two
protocols and applications which tie the protocols to the controller's
MD-SAL infrastructure.

[[bgp-support]]
==== BGP support

* Core Border Gateway Protocol
** https://tools.ietf.org/html/rfc4271[RFC4271] - A Border Gateway
Protocol 4 (BGP-4)
** https://tools.ietf.org/html/rfc4760[RFC4760] - Multiprotocol
Extensions for BGP-4
** https://tools.ietf.org/html/rfc1997[RFC1997] - BGP Communities
Attribute
** https://tools.ietf.org/html/rfc4360[RFC4360] - BGP Extended
Communities Attribute
** https://tools.ietf.org/html/rfc6793[RFC6793] - BGP Support for
Four-Octet Autonomous System (AS) Number Space
* Extended AFI/SAFI support
**
https://tools.ietf.org/html/draft-ietf-idr-ls-distribution-04[draft-ietf-idr-ls-distribution-04]
- North-Bound Distribution of Link-State and TE Information using BGP

[[pcep-support]]
==== PCEP support

* Core Path Computation Element Protocol
** https://tools.ietf.org/html/rfc5440[RFC5440] - Path Computation
Element (PCE) Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5541[RFC5541] - Encoding of Objective
Functions in the Path Computation Element Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5455[RFC5455] - Diffserv-Aware
Class-Type Object for the Path Computation Element Communication
Protocol
** https://tools.ietf.org/html/rfc5521[RFC5521] - Extensions to the Path
Computation Element Communication Protocol (PCEP) for Route Exclusions
** https://tools.ietf.org/html/rfc5557[RFC5557] - Path Computation
Element Communication Protocol (PCEP) Requirements and Protocol
Extensions in Support of Global Concurrent Optimization
* Stateful extensions to the Patch Computation Element Protocol,
December 2012
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-02[draft-ietf-pce-stateful-pce-02]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-crabbe-pce-pce-initiated-lsp-00[draft-crabbe-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model
* Stateful extensions to the Patch Computation Element Protocol,
December 2013
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce-07]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-00[draft-ietf-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model
* Segment routing extension to the Path Computation Element Protocol,
October 2013
**
https://tools.ietf.org/html/draft-sivabalan-pce-segment-routing-02[draft-sivabalan-pce-segment-routing-02]
- PCEP Extension for segment routing
**
https://tools.ietf.org/html/draft-sivabalan-pce-lsp-setup-type-01[draft-sivabalan-pce-lsp-setup-type-01]
- PCEP Extension for path setup type

[[md-sal-applications]]
==== MD-SAL applications

* BGP Local/Remote Routing Information Base export
* Export of BGP/LS-sourced information to
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Level
3 (L3) Interior Gateway Protocol (IGP) Topology]
* Export of PCEP-sourced Label Switched Path information as a
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Network
Topology] and support for initiating them

[[programming-pipeline]]
==== Programming pipeline

* Proposal for a north-bound programming pipeline, which can perform
optimistic instruction scheduling and parallel execution. Used in the
PCEP initiation interface.

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

A Java 7-compliant runtime environment is sufficient to run the protocol
libraries. An MD-SAL enabled container, such as the OpenDaylight
Controller is required for operation of the MD-SAL application. TCP-MD5
functionality requires 64 bit Linux, other platforms are not supported.

[[for-development]]
==== For Development

In order to participate on development, you will need some standard Java
development environment which supports Maven projects hosted in Git.
Core developers use Eclipse on Linux, but also plain console with
vim/mvn/git, so pretty anything you are comfortable should work
reasonably well.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

This release is focused on getting all the functionality required for
both protocols working. The implementation has been tested to
inter-operate with one major router vendor and its topology export was
examined for consistency with underlying network topology.

* The BGP speaker was not tested for performance/scale
* No performance/scale tests are visible to open-source community (this
will be addressed in upcoming release)

[[helium-stable-update-1]]
=== Helium Stable Update 1

For Helium Stable Update 1, the following bugs are fixed:

* https://bugs.opendaylight.org/show_bug.cgi?id=1924[BUG-1924] -
features.xml lists multiple commons-codec versions

* https://bugs.opendaylight.org/show_bug.cgi?id=1921[BUG-1921] -
features-bgpcep has incorrect guava version

* https://bugs.opendaylight.org/show_bug.cgi?id=1931[BUG-1931] -
Overridden version of junit

* https://bugs.opendaylight.org/show_bug.cgi?id=2082[BUG-2082] -
feature.xml is missing dependencies on tcp-md5

* https://bugs.opendaylight.org/show_bug.cgi?id=2115[BUG-2115] - close()
method of BGPSessionImpl should set the error subcode

* https://bugs.opendaylight.org/show_bug.cgi?id=2109[BUG-2109] - Ghost
BGP session could not be cleaned

* https://bugs.opendaylight.org/show_bug.cgi?id=2167[BUG-2167] -
pcc-mock is not bindable to different source addresses

* https://bugs.opendaylight.org/show_bug.cgi?id=2201[BUG-2201] - routes
announced after initial synchronization not present in loc-rib

* https://bugs.opendaylight.org/show_bug.cgi?id=2171[BUG-2171] -
pcc-mock: enable logging level configuration

* https://bugs.opendaylight.org/show_bug.cgi?id=2204[BUG-2204] -
pcc-mock does not support mocking pcc with zero initial lsps

