[[major-features]]
=== Major Features

The Hydrogen release of BGP/LS and PCEP project delivers the baseline
support for the two protocols and applications which tie the protocols
to the controller's MD-SAL infrastructure.

[[bgp-support]]
==== BGP support

* Core Border Gateway Protocol
** https://tools.ietf.org/html/rfc4271[RFC4271] - A Border Gateway
Protocol 4 (BGP-4)
** https://tools.ietf.org/html/rfc4724[RFC4724] - Graceful Restart
Mechanism for BGP
** https://tools.ietf.org/html/rfc4760[RFC4760] - Multiprotocol
Extensions for BGP-4
** https://tools.ietf.org/html/rfc1997[RFC1997] - BGP Communities
Attribute
** https://tools.ietf.org/html/rfc4360[RFC4360] - BGP Extended
Communities Attribute
** https://tools.ietf.org/html/rfc6793[RFC6793] - BGP Support for
Four-Octet Autonomous System (AS) Number Space
* Extended AFI/SAFI support
**
https://tools.ietf.org/html/draft-ietf-idr-ls-distribution-04[draft-ietf-idr-ls-distribution-04]
- North-Bound Distribution of Link-State and TE Information using BGP

[[pcep-support]]
==== PCEP support

* Core Path Computation Element Protocol
** https://tools.ietf.org/html/rfc5440[RFC5440] - Path Computation
Element (PCE) Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5541[RFC5541] - Encoding of Objective
Functions in the Path Computation Element Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5455[RFC5455] - Diffserv-Aware
Class-Type Object for the Path Computation Element Communication
Protocol
** https://tools.ietf.org/html/rfc5521[RFC5521] - Extensions to the Path
Computation Element Communication Protocol (PCEP) for Route Exclusions
** https://tools.ietf.org/html/rfc5557[RFC5557] - Path Computation
Element Communication Protocol (PCEP) Requirements and Protocol
Extensions in Support of Global Concurrent Optimization
* Stateful extensions to the Patch Computation Element Protocol,
December 2012
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-02[draft-ietf-pce-stateful-pce-02]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-crabbe-pce-pce-initiated-lsp-00[draft-crabbe-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model
* Stateful extensions to the Patch Computation Element Protocol,
December 2013
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce-07]
- PCEP Extensions for Stateful PCE
**
https://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-00[draft-ietf-pce-pce-initiated-lsp-00]
- PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model

[[md-sal-applications]]
==== MD-SAL applications

* BGP Local Routing Information Base export
* Export of BGP/LS-sourced information to
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Level
3 (L3) Interior Gateway Protocol (IGP) Topology]
* Export of PCEP-sourced Label Switched Path information as a
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Network
Topology] and support for initiating them

[[programming-pipeline]]
==== Programming pipeline

* Proposal for a north-bound programming pipeline, which can perform
optimistic instruction scheduling and parallel execution. Used in the
PCEP initiation interface.

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

A Java 7-compliant runtime environment is sufficient to run the protocol
libraries. An MD-SAL enabled container, such as the OpenDaylight
Controller is required for operation of the MD-SAL application.

[[for-development]]
==== For Development

In order to participate on development, you will need some standard Java
development environment which supports Maven projects hosted in Git.
Core developers use Eclipse on Linux, but also plain console with
vim/mvn/git, so pretty anything you are comfortable should work
reasonably well.

[[known-issues-and-limitations]]
=== Known Issues and Limitations

This release focused on getting the basic protocol working, with BGP
getting more testing. The implementation has been tested to
inter-operate with one major router vendor and its topology export was
examined for consistency with underlying network topology. PCEP has only
been tested to establish a stateful connection with a single major
router vendor, but no further testing was done, so your mileage may
vary.

* The BGP stack cannot interoperate with OLD Speakers as defined by
RFC6793
* The BGP stack supports only active sessions, i.e. it no support for
listening on the BGP port is provided. This will be addressed in the
next major release.
* The BGP stack does not support disseminating routes, i.e. it can only
receive information. This will be addressed in the next major release.
* The BGP stack advertises the following AFI/SAFIs when establishing
session, without the ability for end-user to change it. This will be
addressed in the next bugfix release.
** IPv4/Unicast
** IPv6/Unicast
** Linkstate/Linkstate
* The BGP topology application produces inconsistent termination point
information. This will be addressed in the next bugfix release.
* The BGP topology application can present outdated node information.
This will be addressed in the next bugfix release.
* The PCEP topology application works only with the December 2013
Stateful extensions. This will be addressed in the next bugfix release.

