DRAFT VERSION, TO BE FINALIZED AT THE END OF LITHIUM RELEASE CYCLE

[[major-features]]
=== Major Features

Lithium release of BGPCEP project delivers the support for the two
protocols and applications which tie the protocols to the controller's
MD-SAL infrastructure.

[[bgp-support]]
==== BGP support

* Core Border Gateway Protocol
** https://tools.ietf.org/html/rfc4271[RFC4271] - A Border Gateway
Protocol 4 (BGP-4)
** https://tools.ietf.org/html/rfc4760[RFC4760] - Multiprotocol
Extensions for BGP-4
** https://tools.ietf.org/html/rfc1997[RFC1997] - BGP Communities
Attribute
** https://tools.ietf.org/html/rfc4360[RFC4360] - BGP Extended
Communities Attribute
** https://tools.ietf.org/html/rfc6793[RFC6793] - BGP Support for
Four-Octet Autonomous System (AS) Number Space
** https://tools.ietf.org/html/rfc4486[RFC4486] - Subcodes for BGP Cease
Notification Message
** https://tools.ietf.org/html/rfc5492[RFC5492] - Capabilities
Advertisement with BGP-4
** https://tools.ietf.org/html/rfc6286[RFC6286] - Autonomous-System-Wide
Unique BGP Identifier for BGP-4
** https://tools.ietf.org/html/rfc5575[RFC5575] - Dissemination of Flow
Specification Rules
** https://tools.ietf.org/html/rfc7311[RFC7311] - The Accumulated IGP
Metric Attribute for BGP

* Extended AFI/SAFI support
**
https://tools.ietf.org/html/draft-ietf-idr-ls-distribution-04[draft-ietf-idr-ls-distribution-04]
- North-Bound Distribution of Link-State and TE Information using BGP

[[pcep-support]]
==== PCEP support

* Core Path Computation Element Protocol
** https://tools.ietf.org/html/rfc5440[RFC5440] - Path Computation
Element (PCE) Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5455[RFC5455] - Diffserv-Aware
Class-Type Object for the Path Computation Element Communication
Protocol
** https://tools.ietf.org/html/rfc5521[RFC5521] - Extensions to the Path
Computation Element Communication Protocol (PCEP) for Route Exclusions
** https://tools.ietf.org/html/rfc5541[RFC5541] - Encoding of Objective
Functions in the Path Computation Element Communication Protocol (PCEP)
** https://tools.ietf.org/html/rfc5557[RFC5557] - Path Computation
Element Communication Protocol (PCEP) Requirements and Protocol
Extensions in Support of Global Concurrent Optimization
** https://tools.ietf.org/html/rfc5886[RFC5886] - A Set of Monitoring
Tools for Path Computation Element (PCE)-Based Architecture
* Stateful extensions to the Patch Computation Element Protocol,
December 2013
**
https://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce-07]
- PCEP Extensions for Stateful PCE
* Segment routing extension to the Path Computation Element Protocol,
April 2015
**
https://tools.ietf.org/html/draft-ietf-pce-segment-routing-01[draft-ietf-pce-segment-routing-01]
- PCEP Extension for segment routing
**
https://tools.ietf.org/html/draft-ietf-pce-lsp-setup-type-01[draft-ietf-pce-lsp-setup-type-01]
- PCEP Extension for path setup type
* Secure Transport for PCEP, March 2015
**
https://tools.ietf.org/html/draft-ietf-pce-pceps-03[draft-ietf-pce-pceps-03]
- Secure Transport for PCEP

[[md-sal-applications]]
==== MD-SAL applications

* BGP Local/Remote Routing Information Base export
* Export of BGP/LS-sourced information to
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Level
3 (L3) Interior Gateway Protocol (IGP) Topology]
* Export of PCEP-sourced Label Switched Path information as a
https://tools.ietf.org/html/draft-clemm-netmod-yang-network-topo-01[Network
Topology] and support for initiating them

[[programming-pipeline]]
==== Programming pipeline

* Proposal for a north-bound programming pipeline, which can perform
optimistic instruction scheduling and parallel execution. Used in the
PCEP initiation interface.

[[target-environment]]
=== Target Environment

[[for-execution]]
==== For Execution

[[for-development]]
==== For Development

[[known-issues-and-limitations]]
=== Known Issues and Limitations
