[[pcep]]
= PCEP

[[code-name]]
== Code Name

odl-bgpcep-pcep-all

[[description]]
== Description

* Overview:

South-bound plugin providing support for Path Computation Element
Protocol as a way to perform CRUD operations on MPLS tunnels in the
underlying network.

* Design Architecture:

BGP_LS_PCEP:PCEP

* Configuration:

BGP_LS_PCEP:User_Guide#PCEP

[[bundles]]
== Bundles

To Be Described Later due to internal module refactor pending on M4.

[[upstream-dependencies]]
== Upstream Dependencies

To Be Described Later due to internal module refactor pending on M4.

[[downstream-dependencies]]
== Downstream Dependencies

No downstream dependencies so far.

[[incompatibilities]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness]]
== Network Intrusiveness

None.

[[recommended-karaf-features]]
== Recommended Karaf features

* odl-restconf

[[how-to-test]]
== How to test

* How to setup feature test:

Start full integration Karaf build with only odl-restconf in
bootFeatures. Let Robot install additional feature(s) interactively.
pcc-mock: Robot would download recent version from Nexus and run it from
dynamic_mininet. No CDS, 1 ODL instance only.

* How to execute basic test cases to validate the feature's
functionality
1.  Download and install pcc-mock, install karaf features.
2.  Wait for empty pcep-topology to appear.
3.  Start pcc-mock: 1 pcc, 1 lsp. See it in pcep-topology.
4.  Update lsp, see updated data in pcep-topology.
5.  Try to remove the lsp, see error and no change in pcep-topology.
6.  Instantiate additional lsp, see it in pcep-topology.
7.  Update instantiated lsp, see changes in pcep-topology.
8.  Remove instantiated lsp, see it gone from pcep-topology.
9.  Kill pcc-mock, see empty pcep-topology.

 +
Details of test cases will be provided after Robot implementation
becomes ready.

[[performancescalability-concerns]]
== Performance/Scalability Concerns

Performance and scalability suites will come after basic suite is done.
Concerns will be raised only if available Releng setup proves
unsatisfactory.

[[bgp]]
= BGP

[[code-name-1]]
== Code Name

odl-bgpcep-bgp-all

[[description-1]]
== Description

* Overview:

South-bound plugin providing support for Border Gate Protocol (including
Linkstate Distribution) as a source of L3 topology information.

* Design Architecture:

BGP_LS_PCEP:BGP

* Configuration:

BGP_LS_PCEP:User_Guide#BGP

[[bundles-1]]
== Bundles

To Be Described Later due to internal module refactor pending on M4.

[[upstream-dependencies-1]]
== Upstream Dependencies

To Be Described Later due to internal module refactor pending on M4.

[[downstream-dependencies-1]]
== Downstream Dependencies

No downstream dependencies so far.

[[incompatibilities-1]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness-1]]
== Network Intrusiveness

None.

[[recommended-karaf-features-1]]
== Recommended Karaf features

* odl-restconf

[[how-to-test-1]]
== How to test

* How to setup feature test:

Start full integration Karaf build with only odl-restconf in
bootFeatures. Let Robot install additional feature(s) interactively.
Specific Python tool: Will be submitted when ready, will be run from
dynamic_mininet. No CDS, 1 ODL instance only.

* How to execute basic test cases to validate the feature's
functionality
1.  Install karaf features.
2.  Wait for empty example-ipv4-topology to appear.
3.  Use restconf to change BGP configuration (ODL to accept connections
from a known peer).
4.  Start tool to connect to ODL. See routes appear in
example-ipv4-topology.
5.  Kill tool, see empty example-ipv4-topology.
6.  Start tool in listen mode, example-ipv4-topology still empty.
7.  Use restconf to change BGP configuration (ODL to initiate connection
to peer).
8.  See routes appear in example-ipv4-topology.
9.  Change BGP configuration back to default, see empty
example-ipv4-topology, kill tool.

 +
Details of test cases will be provided after Robot implementation
becomes ready.

[[performancescalability-concerns-1]]
== Performance/Scalability Concerns

Performance and scalability suites will come after basic suite is done.
Concerns will be raised only if available Releng setup proves
unsatisfactory.

Category:Integration Group[Category:Integration Group]
