[cols="^",]
|=======================================================================
|'''BGP-LS PCEP Facts '''
a|
*Project Creation Date:* July 18th, 2013 *Lifecycle State:* Incubation +
*Primary Contacts:* +
* Dana Kutenicsova

* Robert Varga

*Project Lead:* Dana Kutenicsova  +
*Committers:* +
* Dana Kutenicsova

* Robert Varga

*Contributors:* +
* Milos Fabian

* Maros Marsalek
* Tony Tkacik
* Jan Medved  +

*IRC:* freenode.net #opendaylight +
*Mailing List:* bgpcep-dev@lists.opendaylight.org +

|=======================================================================

BGP/LS and PCEP project is an effort to bring two south-bound plugins
into the controller: one for supporting BGP Linkstate Distribution as a
source of L3 topology information, the other one to add support for Path
Computation Element Protocol as a way to instantiate paths into the
underlying network.

[[project-information]]
== Project Information

Project_Proposals:BGP_and_PCEP[ Project Proposal]

https://git.opendaylight.org/gerrit/#/q/project:bgpcep,n,z[Git patches
and reviews]

https://jenkins.opendaylight.org/bgpcep/[Jenkins]

[[hydrogen]]
=== Hydrogen

BGP-LS/PCEP:Hydrogen Release Plan[ Hydrogen Release Plan]

BGP_LS_PCEP:Hydrogen_Release_Review[ Hydrogen Release Review]

BGP-LS/PCEP:Release Notes 2013[ Hydrogen Release Notes]

BGP-LS/PCEP:User Guide HYDROGEN[ User Guide]

[[helium]]
=== Helium

BGP-LS/PCEP:Helium Release Plan[ Helium Release Plan]

[[getting-started-for-users]]
== Getting started for users

This is the right place to start when using the BGP and/or PCEP protocol
implemented in OpenDaylight.

The *BGP LS PCEP:User Guide[ User Guide]* will navigate you through the
configuration needed for both protocols to connect to their peers.

If you are done with configuration, let's view the connections and data
already received, through *BGP_LS_PCEP:Restconf[ RESTCONF]*.

For advanced PCEP users, this *BGP LS PCEP:Programmer Guide[ Programmer
Guide]* will tell you how to manipulate LSPs (tunnels) using the PCE
protocol.

Let's not forget about security, both PCEP and BGP protocols support
MD5. This *BGP LS PCEP:TCP MD5 Guide[ TCP MD5 Guide]* explains how to
enable and configure it.

Problems? Questions? *BGP LS PCEP:Troubleshooting[Troubleshooting]*
lists common problems reported by BGPCEP users. If you don't find the
answer to your question here, contact
_bgpcep-users@lists.opendaylight.org_ .

[[information-for-developers]]
== Information for developers

These links should be helpful for developers who want to use BGPCEP APIs
to create their own components:

*BGP LS PCEP:Component Map[Component Map]* is a map listing all the
components with a short description and other useful information for
each component in both protocols.

If you introduce new PCE messages, objects or TLVs, or if you have a new
BGP AFI and SAFI, this *BGP LS PCEP:Developer Guide[Developer Guide]* is
exactly what you need to link your components with BGPCEP APIs without
modifying existing code.

*BGP LS PCEP:Models[ YANG Models List]* let's you inspect all the YANG
models for both BGP and PCEP in one place.

[[list-of-all-subpages]]
== List of all subpages
