BGP/LS and PCEP project is an effort to bring two south-bound plugins
into the controller: one for supporting BGP Linkstate Distribution as a
source of L3 topology information, the other one to add support for Path
Computation Element Protocol as a way to instantiate paths into the
underlying network.

[[project-information]]
== Project Information

CONFIGURATION FILES ARE INCOMPATIBLE BETWEEN VERSIONS. PORTING CONFIG
FILES FROM OLD RELEASE TO NEWER RELEASE WON'T WORK.

Check the user guide for each release.

Project_Proposals:BGP_and_PCEP[ Project Proposal]

[cols=",,,,,,,,",options="header",]
|=======================================================================
|Release |Release Plan |Release Notes |Release Review |Installation
Guide |User Guide |Developer Guide |Operations Guide |How-To's/Tutorials
|Hydrogen |BGP-LS/PCEP:Hydrogen Release Plan[ Release Plan]
|BGP_LS_PCEP:Hydrogen_Release_Notes[ Release Notes]
|BGP_LS_PCEP:Hydrogen_Release_Review[ Release Review] |-
|BGP-LS/PCEP:User Guide HYDROGEN[ User Guide] |- |- |-

|Helium |BGP-LS/PCEP:Helium_Release_Plan[Release Plan]
|BGP_LS_PCEP:Helium_Release_Notes[ Release Notes]
|BGP_LS_PCEP:Helium_Release_Review[ Release Review]
|BGP_LS_PCEP:Helium_Installation_Guide[ Installation Guide]
|BGP_LS_PCEP:Helium_User_Guide[ User Guide]
|BGP_LS_PCEP:Helium_Developer_Guide[ Developer Guide]
|BGP_LS_PCEP:Helium_Operations_Guide[ Operations Guide]
|BGP_LS_PCEP:Helium_How-To's/Tutorials[ How-To's/Tutorials]

|Lithium |BGP-LS/PCEP:Lithium_Release_Plan[Release Plan]
|BGP_LS_PCEP:Lithium_Release_Notes[ Release Notes] |-
|BGP_LS_PCEP:Lithium_Installation_Guide[ Installation Guide]
|BGP_LS_PCEP:Lithium_User_Guide[ User Guide]
|BGP_LS_PCEP:Lithium_Developer_Guide[ Developer Guide]
|BGP_LS_PCEP:Lithium_Operations_Guide[ Operations Guide]
|BGP_LS_PCEP:Lithium_How-To's/Tutorials[ How-To's/Tutorials]
|=======================================================================

The documentation to each release can be found in the table. The
documentation in following paragraphs is for SNAPSHOTs and it's updated
immediately after the changes hit the upstream.

[[getting-started-for-users]]
== Getting started for users

This is the right place to start when using the BGP and/or PCEP protocol
implemented in OpenDaylight.

The *BGP LS PCEP:User Guide[ User Guide]* will navigate you through the
configuration needed for both protocols to connect to their peers.

If you are done with configuration, let's view the connections and data
already received, through Restconf, here is a *BGP_LS_PCEP:Restconf[
Tutorial]*.

For advanced users, this *BGP LS PCEP:Programmer Guide[ Operations
Guide]* will tell you how to manipulate LSPs (tunnels) using the PCE
protocol and how to add routes to BGP RIB.

Let's not forget about security, both PCEP and BGP protocols support
MD5. This *BGP LS PCEP:TCP MD5 Guide[ TCP MD5 Guide]* explains how to
enable and configure it.

Problems? Questions? *BGP LS PCEP:Troubleshooting[Troubleshooting]*
lists common problems reported by BGPCEP users. If you don't find the
answer to your question here, contact
_bgpcep-users@lists.opendaylight.org_ .

[[information-for-developers]]
== Information for developers

These links should be helpful for developers who want to use BGPCEP APIs
to create their own components:

*BGP_LS_PCEP:Developer Guide[Developer guide]* should be your start and
mandatory reading if you want to know how BGP and PCEP are implemented
in detail.

*BGP LS PCEP:Component Map[Component Map]* is a map listing all the
components with a short description and other useful information for
each component in both protocols.

*BGP_LS_PCEP:Lithium_Feature_Tree[Feature Tree]* of BGP and PCEP.

If you introduce new PCE messages, objects or TLVs, or if you have a new
BGP AFI and SAFI, this
*BGP_LS_PCEP:How-To's/Tutorials#Writing_protocol_extensions[Tutorial]*
is exactly what you need to link your components with BGPCEP APIs
without modifying existing code.

*BGP LS PCEP:Models[ YANG Models List]* let's you inspect all the YANG
models for both BGP and PCEP in one place. There are several compoments
that can be used to test your work, or BGPCEP project itself. Their
how-to is summarized in page *BGP_LS_PCEP:Testing_components[Testing
Components]*.

[[list-of-all-subpages]]
== List of all subpages
