This subpage illustrates what changes were made in PCEP
http://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce]
and
http://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-00[draft-ietf-pce-pce-initiated-lsp]
since implemented versions : draft-ietf-pce-stateful-pce-07 and
draft-ietf-pce-pce-initiated-lsp-00 along with a proposed timeline of
updating current code to reflect actual state of the drafts.

[[draft-ietf-pce-stateful-pce-08]]
== draft-ietf-pce-stateful-pce-08

_Reference_:
http://tools.ietf.org/html/draft-ietf-pce-stateful-pce-08[draft-ietf-pce-stateful-pce-08]

\1. The *SYMBOLIC-PATH-NAME TLV* MAY be included in *LSP* Object's TLVs.
In stateful-pce-07 the TLV MAY appear also in *LSPA* and *SRP* objects.

\2. The *LSP* object body format changed: *FLAGS* shrank to 5 bits (6
bits length before) and *O* (operational) extended to 3 bits in size (2
bits before)

\3. Added new behavior at negotiation: If the PCEP Speaker on the PCE
supports the extensions of this draft but did not advertise this
capability, then upon receipt of a PCRpt message from the PCC, it SHOULD
generate a PCErr with error-type 19 (Invalid Operation), error-value 5
(Attempted LSP State Report if active stateful PCE capability was not
advertised) and it will terminate the PCEP session. New *Error-value=5*
(Attempted LSP State Report if active stateful PCE capability was not
advertised.) defined in Error-type=19.

\4. *PLSP-ID*: The PCC will advertise the same PLSP-ID on all PCEP
sessions it maintains at given times.

[[draft-ietf-pce-stateful-pce-09]]
== draft-ietf-pce-stateful-pce-09

_Reference_:
http://tools.ietf.org/html/draft-ietf-pce-stateful-pce-09[draft-ietf-pce-stateful-pce-09]

\1. The end of synchronization marker (PCRpt message) includes an *empty
ERO* in its path.

\2. If the path setup fails due to an RSVP signaling error, the error is
reported to the PCE. The PCC will not attempt to resignal the path until
it is prompted again by the PCE with a subsequent PCUpd message.

\3. A PCC MAY include the *LSP object* in the *PCReq message* if the
stateful PCE capability has been negotiated on a PCEP session between
the PCC and a PCE. The definition of the PCReq message from [RFC5440] is
extended to optionally include the LSP object after the END-POINTS
object.

\4. A PCE MAY include the *LSP object* in the *PCRep message* if the
stateful PCE capability has been negotiated on a PCEP session between
the PCC and the PCE and the LSP object was included in the corresponding
PCReq message from the PCC. The definition of the PCRep message from
[RFC5440] is extended to optionally include the LSP object after the RP
object.

\5. The *SYMBOLIC-PATH-NAME TLV* MAY appear as a TLV in the *SRP
Object*.

\6. In case of SRP-ID wrapping the last SRP-ID before the wrapping MUST
be explicitly acknowledged, to avoid a situation where SRP-IDs remain
unacknowledged after the wrap. This means that the PCC may need to issue
two PCUpd messages on detecting a wrap.

[[draft-ietf-pce-pce-initiated-lsp-01]]
== draft-ietf-pce-pce-initiated-lsp-01

_Reference_:
http://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-01[draft-ietf-pce-pce-initiated-lsp-01]

No significant changes.

[[draft-sivabalan-pce-segment-routing-03]]
== draft-sivabalan-pce-segment-routing-03

_Reference_:
http://tools.ietf.org/html/draft-sivabalan-pce-segment-routing-03[draft-sivabalan-pce-segment-routing-03]

\1. *No* message (PCReq, PCRep, PCUpdt, PCRpt, PCInitiate) format
changes required.

\2. PATH-SETUP-TYPE TLV with PST=1 (SR-TE) *MUST* be included in RP/SRP
objects.

\3. New *SR-RRO subobject* - almost identical to SR-ERO subobject except
of L , C and M flags (not included).

\4. New Error-Type:10 *Error-values 6* and *7* - Both SID and NAI are
absent in ERO/RRO subobject.
