[[introduction]]
== Introduction

The Secure Network Bootstrapping Infrastructure (SNBI) project securely
and automatically brings up an integrated set of network devices and
controllers. Key distribution in a scaled network has always been a
challenge, as part of the SNBI project we intend to simplify the process
of bootstrapping network devices with the keys required for secure
communication. SNBI enables not only boot strapping devices with the
required keys, but enables connectivity to the network devices by
assigning unique IPv6 addresses. Admission control of devices into a
specific domain is achieved using the combination of Black/white list of
authorized devices and the device IEEE802.1 AR certificates.

[[features]]
== Features

* Neighbour Discovery.
* Registrar for device authentication.
* Device Bootstrap with device domain Certificates.

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

* link:SNBI_Architecture_and_Design[Architecture Overview.]
* link:SNBI User Guide.[SNBI User Guide.]
* link:SNBI Developers Guide.[SNBI Developers Guide.]

[[architectural-issues]]
== Architectural Issues

None known

[[security-issues]]
== Security Issues

For Helium only the device UDI is used to validate the devices, this is
because not all devices have IEEE802.1 AR certificates embedded.

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

* All testing has been verified on RC2 Karaf image.
* JUNIT Automated API testing.
* Manual Testing providing around 90% code coverage have been performed.
The following areas have been tested extensively. Refer
https://wiki.opendaylight.org/view/SNBI_Helium_Test_plan[here] for the
test plan.
** Northbound APIs.
** Certificate Management APIs.
** Neighbour Discovery.
** Registrar Functionality.
** Device BootStrapping with device domain Certificate.
* Two outstanding bugs which are planned for the next commit have been
identified.
* No blocking issues identified as yet.

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

This is the first release for SNBI, so no APIs have been deprecated as
yet.

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

https://bugs.opendaylight.org/buglist.cgi?bug_status=__open__&list_id=17560&order=relevance%20desc&product=snbi&query_format=specific[List
of Open Bugs]

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

IETF RFC -
https://tools.ietf.org/html/draft-irtf-nmrg-autonomic-network-definitions-03[Autonomic
Networking - Definitions and Design Goals].

IETF RFC -
https://tools.ietf.org/html/draft-pritikin-bootstrapping-keyinfrastructures-00[Bootstrapping
Key Infrastructures].

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)

All controller features scheduled for Helium release were delivered.
Certificate management -- renewal and revocation of certificates, was
planned for this release with a technical oversight but later realised
that it had a dependency on later milestones. So had to move this to the
next release. Forwarding Element will be released based on a docker
image.
