Welcome to the "Secure Network Bootstrapping Infrastructure" project
page!

[[introduction]]
= Introduction

The Secure Network Bootstrapping Infrastructure (SNBI) project securely
and automatically brings up an integrated set of network devices and
controllers. Typically, operators must perform some manual key
distribution process before secure communication is possible between a
set of network devices. Instead, SNBI uses a zero-touch approach to
bootstrapping that leverages manufacturer-installed IEEE 802.1AR
certificates to secure even the initial communications. SNBI devices and
controllers automatically discover each other, get an IP-address
assigned, and establish secure IP connectivity. In addition, this
discovery process reveals the physical topology of the network, exposes
each type of a device (i.e. whether it is a regular network device or a
controller), and assigns the domain for each device. This device type
and domain information can also be used for initiating controller
federation processes. As part of the SNBI project a basic infrastructure
to host, run, and lifecycle-manage multiple network components/functions
within a network device is created. These components/functions can
include individual network element services, such as performance
measurement, traffic-sniffing functionality, or traffic transformation
functionality.

[[snbi-architecture-and-design]]
= SNBI Architecture and Design

* link:SNBI Architecture and Design[SNBI Architecture and Design]
* Project_Proposals:Secure_Network_Bootstrapping_Infrastructure[Project
Proposal]

[[release-plan]]
= Release Plan

* SecureNetworkBootstrapping:ReleasePlan[ Release Plan ]
* SecureNetworkBootstrapping:HeliumReleaseReview[ Helium Release Review]
* SecureNetworkBootstrapping:HeliumReleaseNotes[ Helium Release Note]
* SecureNEtworkBoostrapping:LithiumItems[ Lithium Items]
* SecureNetworkBootstrapping:LithiumReleasePlan[ Lithium Release Plan]

[[communication-weekly-snbi-meeting-open-to-all-irc-channel-mailing-list]]
= Communication: Weekly SNBI meeting (Open to All), IRC channel,
Mailing-list

* Weekly SNBI meeting on Wednesday's 9:00-10:00 PST/PDT | 17:00-18:00
GMT

Go To: https://cisco.webex.com/cisco/j.php?J=204045408&PW=NMjE3M2ZmYmNm

Meeting Password ----- welcome +
Meeting Number ----- 204 045 408

------------------------------------------------------- To join the
teleconference only
------------------------------------------------------- 1. Dial into
WebEx (view all Global Access Numbers at
http://cisco.com/en/US/about/doing_business/conferencing/index.html

\2. Follow the prompts to enter the Meeting Number (listed above) or
Access Code followed by the # sign.

* San Jose, CA: +1.408.525.6800 RTP: +1.919.392.3330
* US/Canada: +1.866.432.9903 United Kingdom: +44.20.8824.0117
* India: +91.80.4350.1111 Germany: +49.619.6773.9002
* Japan: +81.3.5763.9394 China: +86.10.8515.5666

* IRC channel: #opendaylight-snbi on freenode.net. Just pick a nickname
and join #opendaylight-snbi:
http://webchat.freenode.net/?channels=opendaylight-snbi.
* Mailing list: snbi-dev@lists.opendaylight.org (subscribe at:
https://lists.opendaylight.org/mailman/listinfo/snbi-dev)

[[presentations]]
= Presentations

[cols=",,,,,",options="header",]
|=======================================================================
|Event |Date |Theme |Presenter |Deck |Notes
|SNBI Overview |May/15/2014 |SNBI overview for the TSC |Frank Brockners
, IRC: brockners, Balaji B L
|https://wiki.opendaylight.org/images/e/e2/SNBI_TSC_review_15May2014.ppt[SNBI
overview deck] |

|SNBI round 2 discussion |02/2015 |Design targets for ODL/FE |Toerless
Eckert , IRC: tte
|https://wiki.opendaylight.org/images/c/cd/Snbi-arch-2015-rev3-public.pdf[SNBI
Round 2 design] |

|SNBI External CA integration |April/1/2015 |SNBI External CA
integration status |Vijay Anand R , IRC:vjanandr
|https://wiki.opendaylight.org/images/f/f0/ODL_SNBI_containersummit_5Jun2014.pptx[SNBI
External CA integration] |
|=======================================================================

