[[basic-principle]]
= Basic principle

In order to use extensions it is needed to augment existing model and
register new (de)serializers.

*Augmenting the model:* +
1. Create new augmentation +
 *Register (de)serializers:* +
1. Create your (de)serializer +
2. Let it implement OFDeserializer<> / OFSerializer<> +
- in case the structure you are (de)serializing needs to be used in
Multipart TableFeatures messages, let it implement HeaderDeserializer<>
/ HeaderSerializer +
3. Implement prescribed methods +
4. Register your deserializer under appropriate key (in our case
ExperimenterActionDeserializerKey) +
5. Register your serializer under appropriate key (in our case
ExperimenterActionSerializerKey) +
6. Done, test your implementation +
 *NOTE:* +
If you don't know what key should be used with your (de)serializer
implementation, please visit
Openflow Protocol Library:Openflow Protocol Library's extensibility:Registration keys[
Registration keys] page.

[[example]]
= Example

Let's say we have vendor / experimenter action represented by this
structure:

`struct foo_action {` +
`    uint16_t type;` +
`    uint16_t length;` +
`    uint32_t experimenter;` +
`    uint16_t first;` +
`    uint16_t second;` +
`    uint8_t  pad[4];` +
`}`

First, we have to augment existing model. We create new module, which
imports "openflow-types.yang" (don't forget to update your pom.xml with
api dependency). Now we create foo action identity:

`import openflow-types {prefix oft;}` +
`identity foo {` +
`    description "Foo action description";` +
`    base oft:action-base;` +
`}`

This will be used as type in our structure. Now we must augment existing
action structure, so that we will have the desired fields first and
second. In order to create new augmentation, our module has to import
"openflow-action.yang". The augment should look like this:

`import openflow-action {prefix ofaction;}` +
`augment "/ofaction:actions-container/ofaction:action" {` +
`    ext:augment-identifier "foo-action";` +
`        leaf first {` +
`            type uint16;` +
`        }` +
`        leaf second {` +
`            type uint16;` +
`        }` +
`    }`

We are finished with model changes. Run mvn clean compile to generate
sources. After generation is done, we need to implement our
(de)serializer.

Deserializer:

`public class FooActionDeserializer extends OFDeserializer`` {` +
`   @Override` +
`   public Action deserialize(ByteBuf input) {` +
`       ActionBuilder builder = new ActionBuilder();` +
`       input.skipBytes(SIZE_OF_SHORT_IN_BYTES); `*`//` `we` `know`
`the` `type` `of` `action`* +
`       builder.setType(Foo.class);` +
`       input.skipBytes(SIZE_OF_SHORT_IN_BYTES); `*`//` `we` `don't`
`need` `length`* +
`       `*`//` `now` `create` `experimenterIdAugmentation` `-` `so`
`that` `openflowplugin` `can` `differentiate` `correct` `vendor`
`codec`* +
`       ExperimenterIdActionBuilder expIdBuilder = new ExperimenterIdActionBuilder();` +
`       expIdBuilder.setExperimenter(new ExperimenterId(input.readUnsignedInt()));` +
`       builder.addAugmentation(ExperimenterIdAction.class, expIdBuilder.build());` +
`       FooActionBuilder fooBuilder = new FooActionBuilder();        ` +
`       fooBuilder.setFirst(input.readUnsignedShort());` +
`       fooBuilder.setSecond(input.readUnsignedShort());` +
`       builder.addAugmentation(FooAction.class, fooBuilder.build());` +
`       input.skipBytes(4); `*`//` `padding`* +
`       return builder.build();` +
`   }` +
`}`

Serializer:

`public class FooActionSerializer extends OFSerializer`` {` +
`   @Override` +
`   public void serialize(Action action, ByteBuf outBuffer) {` +
`       outBuffer.writeShort(FOO_CODE);` +
`       outBuffer.writeShort(16);` +
`       `*`//` `we` `don't` `have` `to` `check` `for`
`ExperimenterIdAction` `augmentation` `-` `our` `serializer`* +
`       `*`//` `was` `called` `based` `on` `the` `vendor` `/`
`experimenter` `ID,` `so` `we` `simply` `write` `it` `to` `buffer`* +
`       outBuffer.writeInt(VENDOR / EXPERIMENTER ID);` +
`       FooAction foo = action.getAugmentation(FooAction.class);` +
`       outBuffer.writeShort(foo.getFirst());` +
`       outBuffer.writeShort(foo.getSecond());` +
`       outBuffer.writeZero(4); //write padding        ` +
`   }` +
`}`

Register both deserializer and serializer: +
SwitchConnectionProvider.registerDeserializer(new
ExperimenterActionDeserializerKey(0x04, VENDOR / EXPERIMENTER ID), new
FooActionDeserializer()); +
SwitchConnectionProvider.registerSerializer(new
ExperimenterActionSerializerKey(0x04, VENDOR / EXPERIMENTER ID), new
FooActionSerializer()); +
 We are ready to test our implementation.

NOTE: Vendor / Experimenter structures define only vendor / experimenter
ID as common distinguisher (besides action type). Vendor / Experimenter
ID is unique for all vendor messages - that's why vendor is able to
register only one class under ExperimenterAction(De)SerializerKey. And
that's why vendor has to switch / choose between his subclasses /
subtypes on his own.
