[[compiling-yang-model-into-java-class-representation]]
== Compiling YANG model into Java class representation

[[prerequisites]]
=== Prerequisites

* Maven 3
*
https://wiki.opendaylight.org/view/YANG_Tools:Installation_Guide[Installation
Guide]
* YANG model to be compiled

[[configuring-plugin]]
=== Configuring Plugin

To generate code from yang models you need to specify one or more
CodeGenerator implementations, sample bellow contains configuration for
Java YANG Binding which is mostly used by MD-SAL Binding-Aware
Applications.

`           ` +
`               ``org.opendaylight.yangtools` +
`               ``yang-maven-plugin` +
`               ``0.6.2-Helium` +
`               ` +
`                   ` +
`                       ` +
`                           ``generate-sources` +
`                       ` +
`                       ` +
`                           <!-- directory containing yang files to parse and generate code -->` +
`                           ``src/main/yang` +
`                           ` +
`                               ` +
`                                   ` +
`                                       org.opendaylight.yangtools.maven.sal.api.gen.plugin.CodeGeneratorImpl` +
`                                   ` +
`                                   <!-- directory into which generated files will be placed -->` +
`                                   ` +
`                                       target/generated-sources/sal` +
`                                   ` +
`                               ` +
`                           ` +
`                           <!-- if true, plugin will search for yang files also in dependent projects -->` +
`                           ``true` +
`                       ` +
`                   ` +
`               ` +
`               ` +
`                   ` +
`                       ``org.opendaylight.yangtools` +
`                       ``maven-sal-api-gen-plugin` +
`                       ``0.6.1-SNAPSHOT` +
`                       ``jar` +
`                   ` +
`               ` +
`           `

[[required-dependencies]]
=== Required Dependencies

The generated APIs refers to common supertypes defined in
org.opendaylight.yangtools:yang-binding and
org.opendaylight.yangtools:yang-common projects.

You need to add these as dependencies to your project:

`   ` +
`       ` +
`           ``org.opendaylight.yangtools` +
`           ``yang-binding` +
`           ``0.6.2-Helium` +
`       ` +
`   `

[[building]]
=== Building

The code is generated in generate-sources phase. To generate code run
following command on your project:

`  mvn generate-sources`

[[eclipse-integration-m2e]]
=== Eclipse Integration (m2e)

In order to integrate with Eclipse maven connector and Eclipse it is
recommended to update your plugin management section and use
*build-helper-maven-plugin* plugin for importing folders with generated
classes.

[[warnings-by-m2e]]
==== Warnings by m2e

If you are using Eclipse you may want to add following snippet to your
pom.xml to supress warning from m2e:

`   ` +
`       ` +
`           ` +
`               ` +
`               ` +
`                   ``org.eclipse.m2e` +
`                   ``lifecycle-mapping` +
`                   ``1.0.0` +
`                   ` +
`                       ` +
`                           ` +
`                               ` +
`                                   ` +
`                                       ` +
`                                           org.opendaylight.controller` +
`                                       ` +
`                                       ` +
`                                           yang-maven-plugin` +
`                                       ` +
`                                       ` +
`                                           [0.5,)` +
`                                       ` +
`                                       ` +
`                                           ` +
`                                               generate-sources` +
`                                           ` +
`                                       ` +
`                                   ` +
`                                   ` +
`                                       ` +
`                                   ` +
`                               ` +
`                           ` +
`                       ` +
`                   ` +
`               ` +
`           ` +
`       ` +
`   `

[[source-folder-discovery]]
==== Source folder discovery

If the generated files are not imported in the eclipse you may want to
add mojo-build-helper-plugin to your build.

`           ` +
`               ``org.codehaus.mojo` +
`               ``build-helper-maven-plugin` +
`               ``1.7` +
`               ` +
`                   ` +
`                       ``generate-sources` +
`                       ` +
`                           ``add-source` +
`                       ` +
`                       ` +
`                           ` +
`                               <source>target/generated-sources/sal</source>` +
`                           ` +
`                       ` +
`                   ` +
`               ` +
`           `
