OpenFlow is an open standard that enables researchers to run
experimental protocols in the campus networks we use every day. OpenFlow
is added as a feature to commercial Ethernet switches, routers and
wireless access points – and provides a standardized hook to allow
researchers to run experiments, without requiring vendors to expose the
internal workings of their network devices. OpenFlow is currently being
implemented by major vendors, with OpenFlow-enabled switches now
commercially available.

More details about OpenFlow can be found in
http://archive.openflow.org/wk/index.php/OpenFlow_Wiki[OpenFlow wiki].

[[configuration]]
=== Configuration

OpenFlow switch specification may be found on the
https://www.opennetworking.org/sdn-resources/onf-specifications/openflow[Open
Networking Foundation] website.

[[tutorials]]
=== Tutorials

OpenFlow tutorials can be found
http://archive.openflow.org/wk/index.php/OpenFlow_Tutorial[here].

[[help]]
=== Help

For more information, sign up for
https://mailman.stanford.edu/mailman/listinfo/openflow-discuss[openflow-discuss]
mailing list.

Click link:Release/Hydrogen/Base/User Guide[here] to return to the main
Base Edition User Guide page.
