[[links]]
= Links

* Project_Proposals:Topology Processing Framework[Topology Processing
Framework Proposal]
* Topology Processing Framework:LITHIUM Release Plan[LITHIUM Release
Plan]
* Topology Processing Framework:Possible future progress[Future
progress]

[[list-of-possible-correlations]]
= List of possible correlations

* Node ID's
+
::
  Same node with multiple uncoordinated mgmt-protocol (different plugins
  for the same node) produces:
  +
  Different nodes in inventory
  +
  nodes with different ids in uncorrelated network topology plane or
  planes (for example ospf and isis topologies)
  +
  In this cases id’s are different, but in common they can have
  +
  - an attribute (for example te-router-id is unique, an administrative
  name or label, system-id, mac address, bridge id, part number…)
  +
  - a value in a set (for example router-id can be multiple for a node)

* Termination-points
+
::
  represented in different topology planes that are on the same
  node-connector in order to identify client server relationship.

* Customer edge ports
+
::
  as termination-point in network-topology

* Functionality / feature
+
::
  e.g. node supporting special actions, matches, features

[[mlmt-module]]
= MLMT Module

The aim of the Multi-Layer and Multi-Technology (MLMT) module in TPF
project is to augment the network topology model currently in use inside
OpenDaylight architecture in order to represent all technologies and
layers managed by the SDN Controller in a single topological plane
providing a normalized view.

* Topology Processing Framework:MLMT[Description]

[[developer-guide]]
= Developer Guide

* Topology Processing Framework:Developer Guide[Developer Guide]

