[[introduction]]
== Introduction

The OVSDB Plugin project is an overlay Network Virtualization project
that leverages other critical open source projects, OpenStack and Open
vSwitch and integrates into them producing a controller driven framework
for policy instantiation and operational management.

[[release-deliverables]]
== Release Deliverables

[cols=",",options="header",]
|=======================================================================
|Name |Description
|OVSDB Plugin Library: Redesigned OVSDB Library |The library can be used
separately by any Java OVSDB implementation to help serve as a reference
implementation.

|Implement a strong CI framework |Avoid developer downtime, reduce
software bugs and increase the quality of the final deliverable

|OVSDB plugin/Neutron: Implement various NXM extensions: |Upstream
extensions Openflowlibrary project in order to leverage necessary
extension to develop OpenStack services in the OVSDB Neutron
integration.

|Integrate OpenStack Security Groups and Rules |First of many OpenStack
Neutron service integration. This will consolidate Port security
functionality into the OVS network forwarding pipeline rather then the
IP Tables Linux daemon.

|Integrate OpenStack Neutron FWaaS |Integrate Firewall As a Service

|Integrate OpenStack Neutron LBaaS |Integrate LoadBalancer As a Service

|ARP Responding/Handling |L3 East/West forwarding distributed to the
hypervisor

|VLAN Support |To facilitate traditional non-overlay fabric integration.

|Persitance OpenFlow v1.3 Storage Across Controller Reloads |Recover
from a controller failure and restore consistency with OpenStack and
Open vSwitch without interuption to existing provisioned resources.

|Continue to be a Community Driven Project. |Ensure the Community made
up of open source developers and network operators and engineers always
have as much input and decision making in the spirit of Open Source
Software.
|=======================================================================

[[release-milestones]]
== Release Milestones

[cols=",,",options="header",]
|=======================================================================
|Milestone |Offset 0 Date |Deliverables
|M1 |5/12/2014 a|
[cols=",",options="header",]
|====================================
|Name |Description
|Release Plan |Candidate Release Plan
|====================================

|M2 |6/09/2014 a|
[cols=",,",options="header",]
|=======================================================================
|Name |Description |Progress
|OVSDB Plugin Library: Redesigned OVSDB Library |Merge initial cut at
the redesign into master. |Good progress tracked in the
https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git;a=shortlog;h=refs/heads/topic/schema[Topic
Branch]

|Implement a strong CI framework |Establish the basic workflow in
Jenkins and Pax Exam |OVSDB plugin library IT/SI in parallel in library
https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git;a=shortlog;h=refs/heads/topic/schema[topic
branch], initial Pax Exam
https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git;a=commit;h=a254814d330edc91788ac99f764db2773ceb730b[complete],
OF tests next up]]

|OVSDB plugin/Neutron: Implement various NXM extensions: |Commit
extensions upstream and implement in the Neutron Integration |Progress:
Leverage the existing SetField Match/Action/Instructions with NXM types.
Done: Basic TCP Sec State / Pending: Tunnel IPv4 Src/Dst
https://git.opendaylight.org/gerrit/#/c/7634/[model commit]

|Integrate OpenStack Security Groups and Rules |Commit the Neutron APIs
in the NB-API and along with ML2 Neutron Integration |API and OS work
https://git.opendaylight.org/gerrit/#/c/7369/[done]

|ARP Responding/Handling |Get ARP responder working and the required
Nicira extensions to do so upstream. |Extensions which do not use
SetField matching will be
https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin:Helium_Release_Plan[dependent
on openflowplugin being extensible]. Topic in OFPlugin
https://wiki.opendaylight.org/view/Weekly_Project_Meeting_List[weekly
meeting] Monday 6/16

|VLAN Support || Facilitate traditional non-overlay OVS/Openstack fabric
integration.
|https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git&a=search&h=HEAD&st=commit&s=vlan[Done]

|Persitance OpenFlow v1.3 Storage Across Controller Reloads |MD_SAL Data
Store Dependent (in it's release plan) |Slipping until MD_SAL
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Helium_Release_Plan[Data
Store implementation completes]

|Gateway Support |Investigate the needs (if any) for any additional work
needed for the OpenStack gateway we have from OpenStack currently.
Continue to support hardware vendors ODL OVSDB plugin integration.
|https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git;a=commit;h=7ef684d4307e99c988a95f548ba03864541e2845[OpenStack
network node gateway complete] Continue to support community with HW
gateway solutions which implement the
https://datatracker.ietf.org/doc/rfc7047/[OVSDB protocol] as they show
interest.
|=======================================================================

|M3 |7/07/2014 a|
[cols=",,",options="header",]
|=======================================================================
|Name |Description |Progress
|OVSDB Plugin Library: Redesigned OVSDB Library |Verify the
implementation through the newly added test coverage and community
feedback |Topic branch will be merged into master on 07/10/2014. Strong
initial CI. OVS HW schema pending.

|Implement a strong CI framework |Additional coverage and community
documentation |OVSDB Coverage is looking excellent. OF coverage is not
at all. There is zero OpenFlow Java API IT in ODL. This is currently a
focus. See the
https://jenkins.opendaylight.org/ovsdb/job/ovsdb-ovs-integration-unstable-topic-schema/[ODL/OVSDB
plugin Jenkins configuration].

|OVSDB plugin/Neutron: Implement various NXM/NX_Action/SubAction
extensions: |Continue to add as services demand and add test coverage to
the dependancy from OpenflowPlugin |Extensiblity is still not available
but we have included the NXMs we need in the project. The last immediate
NXM need is awaiting merge in
https://git.opendaylight.org/gerrit/#/c/7722/[Patch #7722] NXAST (NX
Actions) can not be done via SetField NXMs so require functioning
extensiblity from OpenFlowJava, OpenFlowPlugin and Controller.

|Integrate OpenStack Security Groups and Rules |Finish OVSDB flowmod
integration + QA at some scale to verify scale. |Was on hold for the new
OVSDB plugin Schema/Library work. This has slipped as we are focusing on
redoing how we consume and instantiate OF flowmods. This is a focus in
coming weeks along with OF IT.

|ARP Responding/Handling |Get ARP responder working and the required
Nicira extensions to do so upstream. |On hold until NX Actions are
implemented or extended in OpenflowPlugin/OpenFlowJava.
|=======================================================================

|M4 |8/04/2014 a|
[cols=",",options="header",]
|=======================================================================
|Name |Description
|API Freeze

|OVSDB Plugin Library: Redesigned OVSDB Library |Final Validation,
Documentation and Coverage

|Implement a strong CI framework |Continue to validate and include new
services as the develop

|OVSDB plugin/Neutron: Implement various NXM extensions: |Finish any bug
fixes and last minute needs upstream before code freeze.

|Integrate OpenStack Security Groups and Rules |Focus on Test Coverage

|Integrate OpenStack Security Groups and Rules |First of many OpenStack
Neutron service integration.

|Persitance OpenFlow v1.3 Storage Across Controller Reloads |(unknown)
MD_SAL Data Store Dependant

|VLAN Support |To facilitate traditional non-overlay fabric integration.
|=======================================================================

|M5 |9/1/2014 a|
[cols=",",options="header",]
|=======================================================================
|Name |Description
|Code Freeze |

|MD-SAL: Clustering: Automated Integration testing of Clustered Data
Store |Run the Automated Integration testing of Clustered Data Store
from build system |

|Performance Testing |Test performance and interoperability with
OpenStack and Open vSwitch of both OpenFlow and OVSDB protocols.
|=======================================================================

|RC0 |9/9/2014 a|
[cols=",",options="header",]
|=======================================
|Name |Description
|RC0 Bugfixes |Bugfixes intended for RC0
|=======================================

|RC1 |9/15/2014 a|
[cols=",",options="header",]
|=======================================
|Name |Description
|RC1 Bugfixes |Bugfixes intended for RC1
|=======================================

|RC2 |9/22/2014 a|
[cols=",",options="header",]
|==========================================
|Name |Description
|Release Review |Release Review Description
|Deliverable Name |Deliverable Description
|==========================================

|Formal Release |9/29/2014 a|
[cols=",",options="header",]
|=========================================
|Name |Description
|Deliverable Name |Deliverable Description
|=========================================

|=======================================================================

[[expected-dependencies-on-other-projects]]
== Expected Dependencies on Other Projects

[cols=",,,",options="header",]
|=======================================================================
|Depends On |Dependency Description |Needed By |Is in Other Project
Release Plan
|Openflowplugin/ Openflowjava/ Controller Yang Models |OpenFlow v1.3
Support for selected NXM and MF Extensions |M2 and M3 depending on the
field |No

|MD_SAL Data Store |Durable Configuration Storage |M3/M4 |Yes
|=======================================================================

[[compatibility-with-previous-releases]]
== Compatibility with Previous Releases

[[themes-and-priorities]]
== Themes and Priorities

1.  Community
2.  Performance
3.  Robust Scale
4.  Innovation
5.  Solve Real World OpenStack Problems
6.  Kittens

