[[ovsdb]]
= OVSDB

[[code-name]]
== Code Name

Ovsdb:

* odl-ovsdb-library
* odl-ovsdb-plugin
* odl-ovsdb-northbound
* odl-ovsdb-compatibility-layer
* odl-ovsdb-openstack

Southbound:

* odl-ovsdb-southbound-api
* odl-ovsdb-southbound-impl
* odl-ovsdb-southbound-impl-rest
* odl-ovsdb-southbound-impl-ui

[[description]]
== Description

OVSDB_Integration:Main[OVSDB_Integration]

[[bundles]]
== Bundles

https://git.opendaylight.org/gerrit/gitweb?p=ovsdb.git;a=blob;f=features/ovsdb/src/main/resources/features.xml;h=8304ffac5017479799d842ba953bd6f6956b832c;hb=HEAD[features.xml]

[[upstream-dependencies]]
== Upstream Dependencies

Ovsdb: odl-adsal-core odl-adsal-northbound
odl-openflowplugin-flow-services odl-openflowplugin-nsf-services
odl-openflowplugin-nxm-extensions odl-openflowplugin-southbound
odl-neutron-service

Southbound: odl-mdsal-broker odl-mdsal-apidocs odl-mdsal-xsql
odl-restconf

[[downstream-dependents]]
== Downstream Dependents

sfc vtn

[[incompatibilities]]
== Incompatibilities

These 2 ovsdb features cannot be installed at the same time:
odl-ovsdb-plugin and odl-ovsdb-southbound-impl that is so, because they
will instantiate their own ovsdb-library, which listens on port 6640 (by
default).

When odl-ovsdb-openstack is used, it assumes no other application in odl
is managing network-virt. In other words, it is assumed that if ovsdb is
using odl-neutron-service, no other feature in odl is providing the same
net-virt service.

[[network-intrusiveness]]
== Network Intrusiveness

By default, ovsdb library will listen on port 6640.

[[recommended-karaf-features]]
== Recommended Karaf features

- For net-virt: odl-ovsdb-openstack - For northbound:
odl-ovsdb-northbound - For using legacy (ad-sal) api:
odl-ovsdb-compatibility-layer

- For southbound: odl-ovsdb-southbound-impl - Same, with rest interface:
odl-ovsdb-southbound-impl-rest - Same, with rest and ui/xsql:
odl-ovsdb-southbound-impl-ui

[[how-to-test]]
== How to test

In this section, provide details about:

- For deploying OVSDB with Openstack:

` - `https://github.com/mestery/odl-openstack-ci-1[`Vagrant` `to`
`bring` `up` `openstack` `and` `tempest`] +
` `https://etherpad.openstack.org/p/odl-virtual-ci-hackfest[`Details`
`on` `running` `tempest` `tests`]` `

` - `https://github.com/flavio-fernandes/devstack-nodes[`Vagrant` `to`
`bring` `up` `multi-openstack` `nodes` `and` `connect` `to` `odl` `via`
`ml2`] +
` `https://lists.opendaylight.org/pipermail/ovsdb-dev/2015-February/001132.html[`More`
`info` `on` `deploying` `Openstack` `with` `ODL`]

` - `https://github.com/opendaylight/releng-builder/blob/master/jjb/ovsdb/ovsdb-full-integration.yaml[`jjb`
`in` `opendaylight` `that` `tests` `ovsdb` `against` `various`
`versions` `of` `OVS`]

` - `https://github.com/opendaylight/releng-builder/blob/master/jjb/ovsdb/ovsdb-openstack.yaml[`jjb`
`used` `as` `ci` `for` `openstack` `project,` `as` `well` `as`
`networking-odl` `plugin`]

` - Daniel F is working with Luis to leverage test harness being used for testing ODL/ovsdb for ONF. ***TODO: add more info here***`

[[performancescalability-concerns]]
== Performance/Scalability Concerns

In this section, provide any concerns related to performance and
scalability

Category:Integration Group[Category:Integration Group]
