PLEASE NOTE: This is the old version of the Lithium release plan that
was maintained during the Helium release. The actual Lithium release
plan can be found here:
Simultaneous Release:Lithium Release Plan[Simultaneous Release:Lithium
Release Plan]

[[introduction]]
== Introduction

This is a Simultaneous Release Plan for OpenDaylight. Projects may
choose to participate or not based upon their readiness and desire to
join the Simultaneous Release. This plan is structured as laid out in
the http://www.opendaylight.org/project-lifecycle-releases[Project
Lifecycle]

[[requirements-for-participation]]
== Requirements for Participation

1.  Planning
1.  Projects must declare their intent to participate in the
Simultaneous Release by M1.
2.  Participating projects must publish a candidate Release Plan by M1
and declare their Release Plan by M2
1.  Participating project Release Plans must contain Milestones that
minimally line up with the Simultaneous Release Plan Milestones
2.  Modularity
1.  Modules that are not intended to interface with the controller via
REST/other rpc mechanism must be OSGI bundles
2.  OSGI bundles should be reasonably granular
3.  Quality
1.  No later than M4, each project must have a Jenkins Job which
rebuilds and retests to an appropriate level when a project it depends
on publishes new artifacts (*Continuous Integration Test Start*)
2.  No later than M2 as part of the Gerrit/Jenkins merge process
participating projects must push their binary artifacts to the Nexus
repo.
4.  Code Hygiene
1.  No uses of System.out.println in non testcase code.
2.  No dependencies on 3rd party (non-ODL) snapshot versions

[[assumptions-aspirations-and-intentions]]
== Assumptions, Aspirations and Intentions

Assumption - The Helium Release will occurr as planned on September
29th, 2014 +
 Add overall goals/asperations for the Lithium Release here as we
encounter them during the execution of the Helium release.

[[milestones-release-candidates-and-service-releases]]
== Milestones, Release Candidates, and Service Releases

Milestones are spaced roughly 4 weeks apart taking into account
significant holidays such as Thanksgiving and Christmas (are there
others that should impact the schedule?)

Release Candidates (RC) are spaced 1 week apart

Service Releases are roughly 6 weeks and 12 weeks after the Formal
Lithium Release.

This is a DRAFT SCHEDULE. This is a DRAFT SCHEDULE. This is a DRAFT
SCHEDULE.

[[schedule]]
=== Schedule

[cols=",,",options="header",]
|=======================================================================
|Milestone |Date |Events
|M0 |10/6/2014 |Simultaneous Release Open

|Last call for new projects eligible to join |10/23/2014 |This is the
latest date a project proposal can be brought and still have the two
week public comment period before its project creation review at the
last TSC meeting (on 11/6) before it needs to declare its intent to join
the Simultaneous Release at M1.

|M1 |11/6/2014 a|
1.  Projects must have declared intent to participate in Simultaneous
Release
2.  Participating Projects must have published a candidate Release Plan
for public comment (
Simultaneous Release:Release Plan 2013 Template[Release Plan Template] )
3.  TSC commits to initiate public discussion of Beryllium Simultaneous
Release Plan

|M2 |12/12/2014 a|
1.  Participating Projects must have declared their final Release Plan
2.  TSC commits to finalize basic dates and Milestones for the Lithium
Simultaneous Release Plan (some details of requirements and Milestone
contents may be decided later).
3.  TSC commits to initiate public discussion of Release Vehicles

|M3 |1/23/2015 a|
1.  Latest possible Continuous Integration Test Start
2.  TSC commits to decide on Final Release Vehicles Defined
3.  Latest possible date for commencing Documentation

|M4 |2/20/2015 a|
1.  API Freeze
2.  Latest possible Continuous System Test Start
3.  TSC commits to begin public discussion of Stable Update Expectations

|M5 |3/23/2015 a|
1.  Code Freeze (bug fixes only from here)
2.  String Freeze (all internationalizable strings frozen to allow for
translation)
3.  TSC commits to have finalized Stable Update Expectations

|RC0 |3/30/2015 |

|RC1 |4/6/2015 |

|RC2 |4/13/2015 |Participating Projects must hold their Release Reviews,
including User Facing Documentation.

|Formal Lithium Release |4/20/2015 a|
1.  Formal Lithium Release
2.  Latest possible date for each project to add a stable/Lithium branch

|SU1 (Stable Update 1 aka Lithium.1) |6/1/2015 |First Stable Update for
Lithium. See
Simultaneous_Release:Lithium_Release_Plan#Service_Release_Expectations[
Stable Update] section. NOTE: This date is provisional, but will not
move earlier. Please note, event based Updates (security/critical bugs)
are distinct and may occur at any point.

|SU2 (Stable Update 2 aka Lithium.2) |7/13/2015 |Second Stable Update
for Lithium. See
Simultaneous_Release:Lithium_Release_Plan#Service_Release_Expectations[
Stable Update] section. NOTE: This date is provisional, but will not
move earlier. Please note, event based Updates (security/critical bugs)
are distinct and may occur at any point.
|=======================================================================

Please note that the TSC reserves the right to allow projects to enter
the Simultaneous Release for a reasonable period of time after the M1
date.

For example, the TSC may allow additional time if a project is delayed
by the IPR Review process.

Please also note that projects that may be splitting into logical parts
may have those logical parts join the Simultaneous Release at any point
prior to M3 provided their Release Plans are apportioned between the
projects they split into.

[[participating-projects]]
== Participating Projects

* TBD

Participating projects should list themselves here prior to M1, with a
link to their Project wiki page and their Release Plan.

[[communication-channels]]
== Communication Channels

[[mailing-list]]
=== Mailing List

discuss@lists.opendaylight.org is the formal channel for communication
about the Simultaneous Release.

[[per-project-simultaneous-release-contact]]
=== Per project Simultaneous Release Contact

Each project participating in the Simultaneous Release should designate
a committer to be the contact for that project for that Simultaneous
Release

[[cross-project-milestone-and-release-candidate-reporting]]
=== Cross Project Milestone and Release Candidate Reporting

Negative status needs to be reported promptly. If a project is under
threat of, or does miss an element on its Release Plan, it should report
that as soon as it becomes aware.

Positive Status need to be reported by each project at each Milestone
Reporting status for that Milestone or Release Candidate. Information
would include things like pointers to continuous integration Jenkins
Jobs, etc.

It is the responsibility of each projects Simultaneous Release Contact
to report both positive and negative statuses.

[[simultaneous-release-developer-meetings]]
=== Simultaneous Release Developer Meetings

One week prior to each Milestone or Release Candidate starting at M1, an
IRC meeting for developer interested in the Simultaneous Release should
be organized for real time coordination and checkin. The Simultaneous
Release Contact for each project (or their delegate) should minimally be
in attendance.

[[bugs]]
=== Bugs

Bugs should be filed in https://bugs.opendaylight.org/[Bugzilla]

[[service-release-expectations]]
== Service Release Expectations

Please see link:Lithium Service Release Expectations[Lithium Service
Release Expectations] for information about branch naming, patch
criteria, service release criteria.

[[addendum]]
== Addendum

Google docs spread sheet for tracking goes here

[[lessons-from-hydrogenhelium-that-should-be-applied]]
== Lessons from Hydrogen/Helium that Should be Applied

https://docs.google.com/spreadsheets/d/1tOcLOrcab3tlYiIkewQ9dIxTDTcQaGFWmTQZ5kkMNuI/edit?usp=sharing[Link
to these in GoogleDoc form]

* Update wiki to categorize release etc it pertains to: Keith
* The Release plan doesn't take into account project dependencies. e.g.
M4 API Freeze. If a project is waiting on API freeze for a project it is
dependent on, then that reduces the amount of time the "dependee" has to
execute. - alagalah (Keith)
** We had offsets in Hydrogen, spaced at 2 days. We need 2-3 weeks
between offsets for them to make sense,
** With 6 offsets 2 weeks each we need additional 10 weeks to reach RC0
on all projects,
** Which means lower-offset projects can (and need) to start their
next-release while the SR process is finishing
* We need a Feature Freeze milestone before the API freeze
** It should occur at M3 with beta-quality APIs, so downstream projects
can start consuming
* We're using release@lists.opendaylight.org instead of discuss
* We should make it easy for projects to convey and understand what APIs
they are intending to make available vs. which ones are intended to be
internal
* We should make it clear that participation in Service Releases is not
optional
* We should make it clear what we expect in terms of timely responses
from project primary contacts for a release
** This involves identifying what mails that people should pay attention
to, e.g., ones sent to release@lists.opendaylight.org with "PLEASE
RESPOND" in the subject
** It also involves identifying a time frame in which they should
respond, e.g., two business days
*** One concrete stab at making this formal would be: "Technically, two
business days will be defined as 48 hours not counting 2a UTC on Friday
until 2a UTC on Sunday. This corresponds to 48 hours starting at 4p on
Friday in the furthest ahead time zone (UTC+14). Note that this means if
you want a response *this* week, you must send it before 2a UTC on
Wednesday. That’s 6/7p pacific time on Tuesday in the Pacific time
zone."
* We need a longer time between code freeze and release candidates
because developers don't focus on tests (especially system and
integration tests) until after code freeze
* Status reports for each milestone should include more than a Boolean
for tests
** In general, the templates for status reports should probably be
developed more in advance.
* We need to make it clear what tasks need to be done for docs, where
and when
** Understanding the kinds of documentation we want to generate and who
the audience is for each kind is going to be critical
*** _e.g., one person's user is likely another's developer_
** The same is true about tests.
* We really need somebody who groks the things that need to be
accomplished at each milestone and can take a glance at the code and
jenkins jobs for each project to get an idea of whether they're on track
or not.
* Requirements to meet at different stages (and especially RCs) should
be set and enforced with clearly explained consequences for missing them
** Release throttle branch needs to be cut at RC0 at the latest
* We need a standard way to track blocking issues:
** One suggestion is to treat them as bugs in bugzilla for easy tracking
and querying
*** Projects would file bugs with severity as "critical", "blocker" with
the target milestone being appropriate
*** Appropriate milestones are sometimes annoying, but generally, it
should be "anything but the next release"
* We need to pre-declare when RCs and final release artifacts will be
cut (both dates and times for clarity)
* Need to add an EOL-plans section to release plan to understand user
impact of EOLed features/components/APIs at the start of a development
cycle
** What requirements do we want to place on projects? e.g., deprecated
in one release and can remove in another?
** plans for dealing with EOLed features should be incorporated into the
release plan
* We should reconsider when we set a release date
** Especially to the press, but also in other environments
** For example, do we want to have a booked event giving us effectively
zero wiggle room on the back end?
*** Maybe, because hard deadlines help get things done, but they also
make for sub-optimal
* We could use more automated release processes
** For example, the auto-release is really, really nice as compared to
spending 14+ hours on IRC cutting everything.
** A similar process for post-release branch cutting and version bumping
would be very helpful, e.g., take a 10+ day process and turn it into one
that takes a few hours.
** One problem is figuring out how to do this w/o requiring involvement
from every project (at least on the critical path).
*** Solutions are (i) allowing for some scripts to commit changes to
projects, which is likely bad, or (ii) automatically pushing patches for
projects to review
*** Another solution is to switch to continuous delivery
* We should avoid scheduling any major events, e.g., a design forum or
summit, immediately after the release so that we can have some room for
slippage without having to pull many developers out of the event into a
"war" room.
* More automated features testing
** to really test things, we need to blow away the m2 repo before
testing every features.xml file
* Cyclic dependencies
** We need to decide if we want to allow them, and if so what kind to
allow
** We need to provide documentation (or ideally scripts) that show how
to build the code despite the circular dependencies (if we allow them)
** We need tests to check for circular dependencies (either at all or
new ones) so that we know about them
*** The simplest way to do this would be to have an offline auto-release
which first clone all the repos and then tried to build them linearly
without access to the nexus repos.

