[[introduction]]
== Introduction

This is a Simultaneous Release Plan for OpenDaylight. Projects may
choose to participate or not based upon their readiness and desire to
join the Simultaneous Release. This plan is structured as laid out in
the http://www.opendaylight.org/project-lifecycle-releases[Project
Lifecycle]

[[requirements-for-participation]]
== Requirements for Participation

1.  Planning
1.  Projects must declare their intent to participate in the
Simultaneous Release by M1.
2.  Participating projects must publish a candidate Release Plan by M1
and declare their Release Plan by M2
1.  Participating project Release Plans must contain Milestones that
minimally line up with the Simultaneous Release Plan Milestones
2.  Modularity
1.  Modules that are not intended to interface with the controller via
REST/other rpc mechanism must be OSGI bundles
2.  OSGI bundles should be reasonably granular
3.  Quality
1.  No later than M4, each project must have a Jenkins Job which
rebuilds and retests to an appropriate level when a project it depends
on publishes new artifacts (*Continuous Integration Test Start*)
2.  No later than M2 as part of the Gerrit/Jenkins merge process
participating projects must push their binary artifacts to the Nexus
repo.
4.  Code Hygiene
1.  No uses of System.out.println in non testcase code.
2.  No dependencies on 3rd party (non-ODL) snapshot versions

[[assumptions-aspirations-and-intentions]]
== Assumptions, Aspirations and Intentions

Assumption - The Helium Release will occurr as planned on September
29th, 2014 +
 Add overall goals/asperations for the Lithium Release here as we
encounter them during the execution of the Helium release.

[[milestones-release-candidates-and-service-releases]]
== Milestones, Release Candidates, and Service Releases

Milestones are spaced roughly 4 weeks apart taking into account
significant holidays such as Thanksgiving and Christmas (are there
others that should impact the schedule?)

Release Candidates (RC) are spaced 1 week apart

Service Releases are roughly 6 weeks and 12 weeks after the Formal
Lithium Release.

This is a DRAFT SCHEDULE. This is a DRAFT SCHEDULE. This is a DRAFT
SCHEDULE.

[[schedule]]
=== Schedule

[cols=",,",options="header",]
|=======================================================================
|Milestone |Date |Events
|M0 |10/6/2014 |Simultaneous Release Open

|Last call for new projects eligible to join |10/17/2014 |This is the
latest date a project proposal can be brought and still have the two
week public comment period before its project creation review at the
last TSC meeting before it needs to declare its intent to join the
Simultaneous Release at M1.

|M1 |11/6/2014 a|
1.  Projects must have declared intent to participate in Simultaneous
Release
2.  Participating Projects must have published a candidate Release Plan
for public comment (
Simultaneous Release:Release Plan 2013 Template[Release Plan Template] )
3.  TSC commits to initiate public discussion of Beryllium Simultaneous
Release Plan

|M2 |12/12/2014 a|
1.  Participating Projects must have declared their final Release Plan
2.  TSC commits to finalize basic dates and Milestones for the Lithium
Simultaneous Release Plan (some details of requirements and Milestone
contents may be decided later).
3.  TSC commits to initiate public discussion of Release Vehicles

|M3 |1/23/2015 a|
1.  Latest possible Continuous Integration Test Start
2.  TSC commits to decide on Final Release Vehicles Defined
3.  Latest possible date for commencing Documentation

|M4 |2/20/2015 a|
1.  API Freeze
2.  Latest possible Continuous System Test Start
3.  TSC commits to begin public discussion of Stable Update Expectations

|M5 |3/23/2015 a|
1.  Code Freeze (bug fixes only from here)
2.  String Freeze (all internationalizable strings frozen to allow for
translation)
3.  TSC commits to have finalized Stable Update Expectations

|RC0 |3/30/2015 |

|RC1 |4/6/2015 |

|RC2 |4/13/2015 |Participating Projects must hold their Release Reviews,
including User Facing Documentation.

|Formal Lithium Release |4/20/2015 a|
1.  Formal Lithium Release
2.  Latest possible date for each project to add a stable/Lithium branch

|SU1 (Stable Update 1 aka Lithium.1) |6/1/2015 |First Stable Update for
Lithium. See
Simultaneous_Release:Lithium_Release_Plan#Service_Release_Expectations[
Stable Update] section. NOTE: This date is provisional, but will not
move earlier. Please note, event based Updates (security/critical bugs)
are distinct and may occur at any point.

|SU2 (Stable Update 2 aka Lithium.2) |7/13/2015 |Second Stable Update
for Lithium. See
Simultaneous_Release:Lithium_Release_Plan#Service_Release_Expectations[
Stable Update] section. NOTE: This date is provisional, but will not
move earlier. Please note, event based Updates (security/critical bugs)
are distinct and may occur at any point.
|=======================================================================

Please note that the TSC reserves the right to allow projects to enter
the Simultaneous Release for a reasonable period of time after the M1
date.

For example, the TSC may allow additional time if a project is delayed
by the IPR Review process.

Please also note that projects that may be splitting into logical parts
may have those logical parts join the Simultaneous Release at any point
prior to M3 provided their Release Plans are apportioned between the
projects they split into.

[[participating-projects]]
== Participating Projects

* TBD

Participating projects should list themselves here prior to M1, with a
link to their Project wiki page and their Release Plan.

[[communication-channels]]
== Communication Channels

[[mailing-list]]
=== Mailing List

discuss@lists.opendaylight.org is the formal channel for communication
about the Simultaneous Release.

[[per-project-simultaneous-release-contact]]
=== Per project Simultaneous Release Contact

Each project participating in the Simultaneous Release should designate
a committer to be the contact for that project for that Simultaneous
Release

[[cross-project-milestone-and-release-candidate-reporting]]
=== Cross Project Milestone and Release Candidate Reporting

Negative status needs to be reported promptly. If a project is under
threat of, or does miss an element on its Release Plan, it should report
that as soon as it becomes aware.

Positive Status need to be reported by each project at each Milestone
Reporting status for that Milestone or Release Candidate. Information
would include things like pointers to continuous integration Jenkins
Jobs, etc.

It is the responsibility of each projects Simultaneous Release Contact
to report both positive and negative statuses.

[[simultaneous-release-developer-meetings]]
=== Simultaneous Release Developer Meetings

One week prior to each Milestone or Release Candidate starting at M1, an
IRC meeting for developer interested in the Simultaneous Release should
be organized for real time coordination and checkin. The Simultaneous
Release Contact for each project (or their delegate) should minimally be
in attendance.

[[bugs]]
=== Bugs

Bugs should be filed in https://bugs.opendaylight.org/[Bugzilla]

[[service-release-expectations]]
== Service Release Expectations

Please see link:Lithium Service Release Expectations[Lithium Service
Release Expectations] for information about branch naming, patch
criteria, service release criteria.

[[addendum]]
== Addendum

Google docs spread sheet for tracking goes here
