*Back to Reservation:Main[ main Reservation Project page]*

[[meetings]]
== Meetings

*PLEASE NOTE:* Our meeting day is changing. We are finding a time that
works best with the regular attendees. Please check back for the new
schedule.

Please join us every week for this meeting. We meet using IRC on
Freenode at #opendaylight-reservation and on Google Hangouts using the
following connection information:

Link:

Meeting Password ----- odl

Meeting Number ----- 201 282 272

[[agendas-and-minutes]]
== Agendas and Minutes

[[thursday-710-1200-amusa-pacific]]
=== Thursday, 7/10, 12:00 AM(USA Pacific)

Tentative agenda

* Previous actions
* Project status
** Assignments
* Other agenda items

Location:

* WebEx:
* IRC: freenode.net #opendaylight-reservation

Minutes:
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_10_reservation_meeting/opendaylight-reservation-2014_07_10_reservation_meeting.2014-07-10-18.59.html
Minutes (text):
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_10_reservation_meeting/opendaylight-reservation-2014_07_10_reservation_meeting.2014-07-10-18.59.txt
Log:
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_10_reservation_meeting/opendaylight-reservation-2014_07_10_reservation_meeting.2014-07-10-18.59.log.html

[[thursday-73-1130-amusa-pacific]]
=== Thursday, 7/3, 11:30 AM(USA Pacific)

Tentative agenda

* Previous actions
* Project status
** Assignments
* Other agenda items

Location:

* WebEx:
* IRC: freenode.net #opendaylight-reservation

MeetBot Minutes:

*
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_03_m3_update_meeting/opendaylight-reservation-2014_07_03_m3_update_meeting.2014-07-03-18.55.html[Meeting
Minutes]
*
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_03_m3_update_meeting/opendaylight-reservation-2014_07_03_m3_update_meeting.2014-07-03-18.55.txt[Meeting
Text]
*
http://meetings.opendaylight.org/opendaylight-reservation/2014/2014_07_03_m3_update_meeting/opendaylight-reservation-2014_07_03_m3_update_meeting.2014-07-03-18.55.log.html[Meeting
Log]

[[thursday-626-1130-amusa-pacific]]
=== Thursday, 6/26, 11:30 AM(USA Pacific)

Tentative agenda

* Previous actions
* Project status
** Assignments
* Other agenda items

Location:

* WebEx:
* IRC: freenode.net #opendaylight-reservation

MeetBot Minutes: Coming Soon

[[participants]]
== Participants

The below people have participated in one or more meetings:

* Mathieu Lemay
* Paul Hudgins

(Sorted alpha by first name)
