In enterprise networks, more and more controller and network management
systems are being deployed remotely, such as in the cloud. Additionally,
enterprise networks are becoming more heterogeneous - branch, IoT,
wireless (including cloud access control). Enterprise customers want a
converged network controller and management system solution.

The documentation to each release can be found under it's own heading.
The documentation in Getting started paragraphs is for SNAPSHOTs and
it's updated immediately after the changes hit the upstream.

[[project-information]]
== Project Information

CONFIGURATION FILES ARE INCOMPATIBLE BETWEEN VERSIONS. PORTING CONFIG
FILES FROM OLD RELEASE TO NEWER RELEASE WON'T WORK.

Check the user guide for each release.

Project_Proposals:USC[ Project Proposal]

https://git.opendaylight.org/gerrit/#/q/project:usc,n,z[Git patches and
reviews]

https://jenkins.opendaylight.org/usc/[Jenkins]

[cols=",,,,,,,,",options="header",]
|=======================================================================
|Release |Release Plan |Release Notes |Release Review |Installation
Guide |User Guide |Developer Guide |Operations Guide |How-To's/Tutorials
|Lithium |USC:Lithium:Release_Plan[Release Plan] |- |- |- |- |- |- |-
|=======================================================================

[[getting-started-for-users]]
== Getting started for users

[[information-for-developers]]
== Information for developers

[[list-of-all-subpages]]
== List of all subpages
