[[netconf-md-sal]]
= NETCONF MD-SAL

[[code-name]]
== Code Name

odl-netconf-mdsal

[[description]]
== Description

Netconf northbound interface tied to MD-SAL (Very similar to restconf).
Allows for remote access to MD-SAL's datastore, rpcs and notifications
using NETCONF protocol.

* Overview & Design Architecture:

OpenDaylight_Controller:Netconf:Design[Overview & Design]

* Configuration:

OpenDaylight_Controller:Config:Examples:Netconf:Mdsal[Configuration]

[[bundles]]
== Bundles

* org.opendaylight.controller/netconf-ssh
* org.opendaylight.controller/mdsal-netconf-connector
* org.opendaylight.controller/mdsal-netconf-monitoring
* org.opendaylight.controller/netconf-config-dispatcher

[[upstream-dependencies]]
== Upstream Dependencies

* odl-config-all
* odl-netconf-all
* odl-mdsal-broker

[[downstream-dependencies]]
== Downstream Dependencies

No downstream dependencies so far.

[[incompatibilities]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness]]
== Network Intrusiveness

None.

[[recommended-karaf-features]]
== Recommended Karaf features

Recommended features for karaf testing:

* odl-netconf-connector-all
* odl-restconf-all

[[how-to-test]]
== How to test

This feature deploys a netconf interface on top of the MD-SAL. The tests
have to include:

* Successful connection over SSH using any SSH capable client(or
possibly netconf cli)
* Successful CRUD operations for a chosen model using any SSH capable
client(or possibly netconf cli) with verification using Restconf
* Successful RPC invocation for a chosen rpc using any SSH capable
client (or possibly netconf cli)
* Successful notification subscription using any SSH capable client(or
possibly netconf cli)
* Verification of ietf-netconf-state data presence from both netconf and
restconf interface
* Verification of ietf-netconf-notifications/streams presence data from
both netconf and restconf interface
* Successful loopback connection to mdsal's netconf interface using
sal-netconf-connector with verification of CRUD and RPCs over Restconf

 +
With the test cases above, we will confirm that the netconf interface
conforms to the Netconf RFC and that it also conforms to
sal-netconf-connector.

[[performancescalability-concerns]]
== Performance/Scalability Concerns

Since the feature is brand new, its performance(how many and how fast
are the request processed) might be lower than expected.

[[netconf-connector]]
= NETCONF Connector

[[code-name-1]]
== Code Name

odl-netconf-connector-all

[[description-1]]
== Description

Netconf southbound connector plugged into MD-SAL. Allows for remote
management and monitoring of netconf devices using MD-SAL apis and
Restconf.

* Overview & Design Architecture:

OpenDaylight_Controller:Netconf:Design[Overview & Design]

* Configuration:

OpenDaylight_Controller:Config:Examples:Netconf[Configuration] +
OpenDaylight_Controller:Netconf:Testtool[Testtool]

[[bundles-1]]
== Bundles

[[upstream-dependencies-1]]
== Upstream Dependencies

[[downstream-dependencies-1]]
== Downstream Dependencies

No downstream dependencies so far.

[[incompatibilities-1]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness-1]]
== Network Intrusiveness

None without explicit configuration.

[[recommended-karaf-features-1]]
== Recommended Karaf features

Recommended features for karaf testing:

* odl-restconf-all

[[how-to-test-1]]
== How to test

This feature deploys a netconf interface on top of the MD-SAL. The tests
have to include:

* Successful connection to remote netconf devices
* Successful CRUD and RPCs towards mounted device for a chosed device
specific model using the loopback controller-config mountpoint (also
loopback for md-sal's netconf) or netconf-testtool or any other
available netconf devices e.g. Mininet
* Successful Reconnect when remote device closes connection unexpectedly
* Verification of state data present in MD-SAL for mounted devices
* Successful detection and handling of capability-changed notification
coming from remote device(the controller-config loopback mount supports
these notification so it is sufficient only to install any ODL feature
after the loopback connection was spawned).

* Performance tests over Restconf(testing the entire pipeline in ODL)
using netconf-testtool
* Scale tests over Restconf(used just for verification and time
measuring) using netconf-testtool

 +
With the test cases above, we will confirm that the netconf connector
conforms as a client to the Netconf RFC. The CRUD and RPC tests aimed at
the loopback netconf tied to config subsystem will test also the netconf
northbound server.

[[performancescalability-concerns-1]]
== Performance/Scalability Concerns

The scale testing should aim at 10k devices spawned by the
netconf-testtool. For this, both the testtool and the ODL should run
with 8G of RAM on machines that allow for 10k connections between them.

Category:Integration Group[Category:Integration Group]
Category:Integration Group[Category:Integration Group]
