Welcome to the SNMP Plugin project page!

[[introduction]]
= Introduction

* Project_Proposals:SNMP Plugin[Project Proposal]
* SNMP_Plugin:Working_with_MIBs[Working with MIBs]
* SNMP_Plugin:Getting_Started[Getting Started]
* SNMP_Plugin:SNMP_Simulator[SNMP Simulator]
* Trello Board: https://trello.com/b/OU9S9hIy/opendaylight-snmp-plugin
* Bugzilla:
https://bugs.opendaylight.org/buglist.cgi?component=General&list_id=29216&product=snmp

[[lithium-wip]]
= Lithium (WIP)

* SNMP Plugin:Lithium[Project Release Plan]

[[meetings-open-to-all]]
= Meetings (open to all)

For impromptu meetings, use
https://plus.google.com/hangouts/_/event/cqpjp7haq1vps00g6sco21ac4a8[Google
Hangout meeting].

SNMP Plugin Weekly Meeting

* Time: 10:00am PST
* Topic: ODL - Weekly SNMP Plugin Project meeting
* Date: Starting 1/21/2015
* Meeting Number: 199 379 022
* Meeting Password: This meeting does not require a password

1.  1. Go to
https://meetings.webex.com/collabs/meetings/join?uuid=M9CIDR1B0LHMEK224U9I2BH19A-9VIB
2.  2. Log in to your account.
3.  3. Click "Start Now".
4.  4. Follow the instructions that appear on your screen.

---------------------------------------------------------------- ALERT –
PLEASE READ: DO NOT DIAL THE TOLL FREE NUMBERS FROM WITHIN THE (408) OR
(919) AREA CODES
---------------------------------------------------------------- Please
dial the local access number for your area from the list below: - San
Jose/Milpitas (408) area: 525-6800 - RTP (919) area: 392-3330

Dialing the WebEx toll free numbers from within 408 or 919 area codes is
not enabled. “ If you dial the toll-free numbers within the 408 or 919
area codes you will be instructed to hang up and dial the local access
number.” Please use the call-back option whenever possible and otherwise
dial local numbers only. The affected toll free numbers are: (866)
432-9903 for the San Jose/Milpitas area and (866) 349-3520 for the RTP
area.

------------------------------------------------------- To join the
teleconference only
------------------------------------------------------- 1. Dial into
Cisco WebEx (view all Global Access Numbers at
http://cisco.com/en/US/about/doing_business/conferencing/index.html 2.
Follow the prompts to enter the Meeting Number (listed above) or Access
Code followed by the # sign.

San Jose, CA: +1.408.525.6800 RTP: +1.919.392.3330

US/Canada: +1.866.432.9903 United Kingdom: +44.20.8824.0117

India: +91.80.4350.1111 Germany: +49.619.6773.9002

Japan: +81.3.5763.9394 China: +86.10.8515.5666

[[meeting-minutes]]
= Meeting Minutes

https://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-04-15-17.01.html[4/15/15]

https://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-04-29-17.00.html[4/29/15]

https://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-05-06-16.58.html[5/6/15]

http://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-05-13-17.37.html[5/13/15]

http://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-05-20-17.29.html[5/20/15]

https://meetings.opendaylight.org/opendaylight-snmp/2015/snmp_weekly/opendaylight-snmp-snmp_weekly.2015-05-27-17.35.html[5/27/15]

[[all-subpages]]
= All subpages
