[[introduction]]
= Introduction

A guide to getting an SNMP simulator running for testing the SNMP Plugin

[[installation]]
= Installation

We'll be using http://snmpsim.sourceforge.net/download.html[snmpsim],
which can be installed using easy_install:

`
    sudo easy_install snmpsim
`

[[running]]
= Running

The snmp simulator uses a python script "snmpsimd.py" to run. To start a
basic SNMP server:

`
   sudo snmpsimd.py --agent-udpv4-endpoint=127.0.0.1:161 --process-user=adierken --process-group=adierken
`

We need root privileges to bind to port 161. Make sure to replace
"process user" and "process group" with the appropriate values.

[[testing]]
= Testing

Once the simulator is running, it comes with some pre-existing mibs
which can be queried, using either the SNMP plugin, or another client.

`
    snmpwalk -v2c -c recorded/linksys-system localhost:161 1.3.6
`

Which outputs:

`
    SNMPv2-MIB::sysDescr.0 = STRING: BEFSX41
    SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.3955.1.1
    DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (638239) 1:46:22.39
    SNMPv2-MIB::sysContact.0 = STRING: Linksys
    SNMPv2-MIB::sysName.0 = STRING: isp-gw
    SNMPv2-MIB::sysLocation.0 = STRING: 4, Petersburger strasse, Berlin, Germany
    SNMPv2-MIB::sysORLastChange.0 = Timeticks: (4) 0:00:00.04
    SNMPv2-MIB::sysORLastChange.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
`

Check the project's http://snmpsim.sourceforge.net/intro.html[homepage]
for some more examples, and how to add custom mibs
