Welcome to the Discovery project page!

[[introduction]]
= Introduction

*
https://wiki.opendaylight.org/view/Project_Proposals:Discovery|Project[Proposal]

[[helium]]
= Helium

*TBD*

[[meetings-open-to-all]]
= Meetings (open to all)

See WebEx details for weekly meetings...

Please contact hosts in case of any issues.

* Time: Tuesdays 10am-11am PST (starting December 16, 2014)

2014-12-16 - Agenda

* Litium
** Project Lead Vote
** Release Plan
* Design Changes (upcoming)
* Other Business

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Host: David Bainbridge

Topic: "Discovery Weekly Status Update and Planning"

Date & Time: Every Tuesday, from Tuesday, December 16, 2014 to no end
date at 10:00 am, Pacific Standard Time (San Francisco, GMT-08:00)

Meeting password: discovery (please note passwords are case sensitive)

Meeting number: 687 434 100

Teleconference: Provide your phone number when you join the meeting to
receive a call back. Alternatively, you can call: Call-in toll-free
number: 1-855-215-5891 (US) Call-in number: 1-443-863-6577 (US) Show
global numbers:
https://www.tcconline.com/offSite/OffSiteController.jpf?cc=2153369354
Leader PIN: 6727 Conference Code: 215 336 9354

To view, edit, or start your web meeting click here:
https://ciena.webex.com/ciena/j.php?MTID=m0718637dc9def0a87ab945b8a73b9571.
** DO NOT FORWARD THIS URL TO ANYONE - IT IS JUST FOR YOU THE HOST **

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

To add this meeting to your calendar click the following link, or copy
the link and paste it into your Web browser:
https://ciena.webex.com/ciena/j.php?MTID=mce97b634924781b628ac7b43826522b2

To check whether you have the appropriate players installed for UCF
(Universal Communications Format) rich media files, go to
https://ciena.webex.com/ciena/systemdiagnosis.php.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[[all-subpages]]
= All subpages
