[[checkout-stable-branch]]
== Checkout Stable branch

* Helium Stable Update Release 2
+
::
-------------------------------
git checkout release/helium-sr2
-------------------------------

[[build-tips]]
== Build Tips

[[skipping-all-tests]]
=== Skipping all tests

To skip running the tests, set the *skipTests* property to true.

-----------------------------
cd {vtn-git-repo}
cd manager
mvn clean install -DskipTests
-----------------------------

[[skipping-karaf-features-test]]
=== Skipping Karaf features test

The Karaf features test requires large amounts of memory, and takes a
lot of time. To skip the Karaf features during build, set the
*vtn.karaf.skip* property to true.

----------------------------------
cd {vtn-git-repo}
cd manager
mvn clean install -Dvtn.karaf.skip
----------------------------------

The *vtn.karaf.skip* property is available after the following patch is
merged. It means that this does not work on stable/hydrogen and
stable/helium branches.

https://git.opendaylight.org/gerrit/#/c/13422/

[[running-all-tests]]
=== Running all tests

In the current Maven configuration of VTN project, all slow tests are
skipped by default. To run all tests including the slow tests, set the
*integrationtests* property to true.

------------------------------------
cd {vtn-git-repo}
cd manager
mvn clean install -Pintegrationtests
------------------------------------

It is recommended to run "mvn -Pintegrationtests -Pstrictcheck clean
install" before you push a patch to Gerrit.

[[running-strict-coding-style-check]]
=== Running strict coding style check

To run *strict* coding style check for the code of VTN Manager, set the
*strictcheck* property to true.

-------------------------------
cd {vtn-git-repo}
cd manager
mvn clean install -Pstrictcheck
-------------------------------

It is recommended to run "mvn -Pintegrationtests -Pstrictcheck clean
install" before you push a patch to Gerrit.

[[findbugs]]
== FindBugs

FindBugs has been activated in the master branch of VTN Git repository
since Helium is released. Project Documentation which is generated by
"mvn site" shows the bug analysis report generated by FindBugs.

For example, to show the bug analysis report for VTN Manager Neutron
bundle, please execute "mvn compile site" for the pom.xml of the Neutron
bundle.

----------------------
cd {vtn-git-repo}
cd manager/neutron
mvn clean compile site
----------------------

It generates the report "target/site/findbugs.html" on the neutron
directory. You can find the link to this report "findbugs.html" as
"FindBugs Report" under "Project Reports" in the index page of Project
Documentation "target/site/index.thml".

[[log]]
== Log

In order to change log level of VTN Manager to TRACE, execute the
following command in Karaf console.

------------------------------------------
log:set TRACE org.opendaylight.vtn.manager
------------------------------------------

[[bundles]]
== Bundles

To see if VTN Manager bundles is installed, execute the following
command in Karaf console.

----------------------
bundle:list | grep vtn
----------------------

VTN Manager bundles can be found by this command after the following
patch is merged. Since the patch is merged after Helium release, this
does not work on stable/hydrogen and stable/helium branches.

https://git.opendaylight.org/gerrit/#/c/13053/

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
