[[vtn-manager]]
= VTN Manager

[[code-name]]
== Code Name

odl-vtn-manager,odl-vtn-manager-rest,odl-vtn-manager-neutron

[[description]]
== Description

The VTN Manager provides a way to configure virtual networks on OpenFlow
switches.

It provides three Karaf features.

* odl-vtn-manager
** This feature provides VTN Manager's JAVA API.
* odl-vtn-manager-rest
** This feature provides VTN Manager's REST API.
* odl-vtn-manager-neutron
** This feature provides the integration with Neutron interface.

The detailed specification is available in the following page:
https://wiki.opendaylight.org/view/OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Manager:Specification

[[bundles]]
== Bundles

Please see the following file in the vtn.git.

------------------------------------------------
manager/features/src/main/resources/features.xml
------------------------------------------------

[[upstream-dependencies]]
== Upstream Dependencies

Please see the following file in the vtn.git.

------------------------------------------------
manager/features/src/main/resources/features.xml
------------------------------------------------

[[downstream-dependents]]
== Downstream Dependents

No project depends on VTN Manager's features so far.

[[incompatibilities]]
== Incompatibilities

The VTN Manager feature is not compatible with other flow programming
features, and not compatible with other OpenStack Neutron features.

[[network-intrusiveness]]
== Network Intrusiveness

The VTN Manager feature programs OpenFlow devices via OpenFlow protocol
only when users configures virtual networks via the REST API provided by
the VTN Manager.

[[recommended-karaf-features]]
== Recommended Karaf features

* odl-vtn-manager-rest
* odl-vtn-manager-neutron

[[how-to-test]]
== How to test

To test the VTN manager feature, just install the VTN Manager feature by
executing the following command in Karaf console:

------------------------------------
feature:install odl-vtn-manager-rest
------------------------------------

The robot scripts for testing the VTN Manager feature is available in
the following directory of the integration.git.

--------------------
test/csit/suites/vtn
--------------------

[[performancescalability-concerns]]
== Performance/Scalability Concerns

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
