[[presentation-materials]]
== Presentation materials

Presentation materials related to VTN project:

[cols=",,,,,",options="header",]
|=======================================================================
|Event |Date |Theme |Presenter |Deck |Notes
|CloudOpen Japan 2014 |May 20, 2014 |OpenDaylight Network Virtualization
and its Future Direction |Masashi Kudo, Hideyuki Tai ||
Media:ODL-MiniSummit-Virt-Final.pdf[Talk slides],
Media:Using_OpenStack_with_OpenDaylight_VTN.pdf[Live Demo slides] ||

|Hackfest (Mar. 2014) |March 28, 2014 |Enhancement of OpenStack Neutron
Support |Hideyuki Tai |Media:Vtn_demo_hackfest_2014_march.pdf[Live Demo
slides] |

|OpenDaylight Summit 2014 |February 4, 2014 |VTN at OpenDaylight |Su-Hun
Yun, Hideyuki Tai ||
http://www.youtube.com/watch?v=HMqO7phctAY[Presentation video (on
YouTube)], Media:Vtn_demo_ods_2014_0204.pdf[Live Demo slides] ||

|Hackfest (Sep. 2013) |September 10, 2013 |VTN Demo (VTN Coordinator)
|Hideyuki Tai |Media:NEC_VTN_Demo_0910.pdf[Live Demo slides] |

|Hackfest (Jul. 2013) |July 22, 2013 |VTN Demo (VTN Manager) |Hideyuki
Tai |Media:NEC_VTN_Demo_0722.pdf[Live Demo slides] |

|Hackfest (Jun. 2013) |JUne 6, 2013 |Deep Dive on VTN Proposal a|
Masashi Kudo, Hideyuki Tai,

Sarath Babu G

 a|
| Media:NEC VTN Model 0606.pdf[Overview of the VTN Proposal],
Media:NEC VTN Demo 0606.pdf[Live Demo slides],

Media:NEC VTN Implementation 0606.pdf[VTN Implementation]

 ||
|=======================================================================

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
