[[vtn-running-configuration-vtn-client---application]]
= VTN RUNNING CONFIGURATION (VTN Client - Application)

[[overview]]
== Overview

This application acts as a client to get all the information about the
VTN present under a single container. The output is saved as a User
readable json file. This application is designed as a user friendly
application ,with simple commands we can get the whole VTN data, which
saves lot of time for the users on giving individual curl commands for
each data. Testing is made easier in this tool as the output is
generated as user friendly json file.

This application is developed purely as a Java application. The Rest
Response(s) from VTN Manager will be processed by JSON parser in VTN
Client to an output file *runConfig_output.json*

[[prerequisites]]
== Prerequisites

* A controller must be UP and running.

* To set up a Controller,

Please visit
https://wiki.opendaylight.org/view/Release/Helium/VTN/User_Guide/OpenStack_Support
for more info

[[how-to-use-this-application]]
== How To Use This Application

* Download the VTN Source code from git.

`git clone `https://git.opendaylight.org/gerrit/p/vtn.git[`https://git.opendaylight.org/gerrit/p/vtn.git`]

* Navigate to application folder:

` cd vtn/application/` +
`    `

* Build the source code under the application folder with:

` mvn clean install ` +
`   `

* After Build Success, Please Navigate to the target folder with
following command:

`cd vtn_running_app/target/`

* List the files in the target directory with the following command::

` ls ` +
`  `

* VTNRESTClient.jar will be present.

* Execute the jar file with the following command:

` java -jar VTNRESTClient.jar` +
` `

* It will prompt for controller IP Address, where we need to give the IP
Address and press enter .

* On a valid IP Address it will prompt for a port address of Controller,
provide a valid port name and press enter.

* Finally it will prompt for the container name.Provide the container
name from which the VTN running configuration needs to be fetched.

* This will generate a user readable and well formatted JSON file
"runConfig_output.json" ,in the current directory itself.

[[illustration]]
== Illustration

Please find the below example on how to run this Application.

`[root@u12 target]# java -jar VTNRESTClient.jar` +
`Please Enter the VTN Server IP Address:` +
`10.106.138.192` +
`Please Enter the Port to communicate:` +
`8080` +
`Please enter the username of the Controller:` +
`admin` +
`Please enter the password of the Controller:` +
`admin` +
`Please Enter the Container Name:` +
`default` +
`Loading, please wait...` +
`Process completed...` +
`Creating output file - runConfig_output.json` +
`Finished`
