Model-Driven SAL (MD-SAL) is a set of infrastructure services aimed at
providing common and generic support to application and plugin
developers.

MD-SAL currently provides infrastructure services for:

* Data Store
* RPC / Service routing
* Notification subscription and publish services

This common model-driven infrastructure allows developers of
applications and plugins to develop against one set of APIs that are
derived from a single model: Java generated APIs, DOM APIs, and REST
APIs.

Read more about MD-SAL Architecture
OpenDaylight_Controller:MD-SAL:Architecture.

[[developers-documentation]]
== Developer's Documentation

* OpenDaylight Controller:MD-SAL:Component Map[ List of MD-SAL
Components, short description, their APIs and experts for code base]
* OpenDaylight Controller:MD-SAL:Plugin Types[Plugin Types]
*
OpenDaylight Controller:MD-SAL:Southbound Plugin Development Guide[Southbound
Plugin Development Guide]
* OpenDaylight_Controller:MD-SAL:FAQ[ Model-Driven SAL FAQ]
* OpenDaylight_Controller:Config:Main[ Controller Configuration
Subsystem]
* OpenDaylight_Controller:Config:Model Reference[ OpenDaylight Model
Reference]
* Data Stores:
** OpenDaylight_Controller:MD-SAL:Architecture:DOM_DataStore[DOM
In-Memory Data Store Prototype]
** OpenDaylight_Controller:MD-SAL:The_Infinispan_Data_Store[ Infinispan
In-Memory Data Store Prototype]
* OpenDaylight Controller:MD-SAL:Restconf[MD-SAL Restconf]
* OpenDaylight_Controller:MD-SAL:Restconf_API_Explorer[MD-SAL Restconf
API Explorer]
* OpenDaylight Controller:RESTCONF Northbound APIs[Available MD-SAL
Northbound APIs]

* link:What is preventing you from using MD-SAL?[What is preventing you
from using MD-SAL?]
*
OpenDaylight_Controller:MD-SAL:EverythingYouWantedtoKNowaboutOnDataChange_butWasAfraidToAsk[Everything
you wanted to know about 'OnDataChange' but was afraid to ask]

[[tutorials]]
== Tutorials

[[documentation-review-task]]
=== Documentation Review Task

* OpenDaylight Controller:MD-SAL:MD-SAL Document Review[Document Review
WIP]

[[md-sal-weekly-call]]
== MD-SAL Weekly Call

See link:MD-SAL Weekly Call[MD-SAL Weekly Call] for meeting link, agenda
and updated minutes.

[[meeting-minutes]]
=== Meeting Minutes:

[[may-6-2014-infinispan-in-memory-data-store-prototype]]
==== May 6, 2014: Infinispan In-Memory Data Store Prototype

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_weekly_meeting/opendaylight-meeting-md_sal_weekly_meeting.2014-05-06-16.13.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=ee9b23edb5fd449da213d7f3a83e2042[WebExRecording]
* OpenDaylight_Controller:MD-SAL:The Infinispan Data Store[Prototype
wiki]
* https://git.opendaylight.org/gerrit/#/c/5900/[Prototype code]

[[april-29-2014-inocybe-dat-store-update-md-sal-archetype-resctonf-tool]]
==== April 29, 2014: Inocybe dat store update, MD-SAL Archetype,
RESCTONF Tool

*
https:///cisco.webex.com/ciscosales/lsr.php?RCID=0e025c295c004d238f3c3a016b8c3318[WebEx
Recording]

[[april-22-2014-karaf-container]]
==== April 22, 2014: Karaf Container

*
https://cisco.webex.com/ciscosales/lsr.php?RCID=ea008e89723b4f0fa64204d78d5a5146[WebEx
Recording]

[[april-15-2014-apic-presentation-part-ii]]
==== April 15, 2014: APIC Presentation Part II

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-15-16.07.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=108032230c024db6b4d037f6d1fda5e1[WebEx
Recording]
* *Notes from Part I (TWS Call on April 4, 2014):*
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.txt[Minutes
(text)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-14-17.07.log.html[Log]
* *Presentation*:
image:APIC Presentation 04-13-2014.pdf[APIC Presentation 04-13-2014.pdf,title="fig:APIC Presentation 04-13-2014.pdf"]

[[april-8-2014-md-sal-akka-prototype]]
==== April 8, 2014: MD-SAL Akka Prototype

* *Minutes*:
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.html[Minutes]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.txt[Minutes(txt)]
**
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-04-08-16.09.log.html[Minutes(raw)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=8a19ade66f0f49daaae57886e3305af2[WebEx
Recording]
* *Presentation*:
image:MD-SAL Akka Prototype.pdf[MD-SAL Akka Prototype.pdf,title="fig:MD-SAL Akka Prototype.pdf"]

[[april-1-2014-data-store-performance-improvements-demo]]
==== April 1, 2014: Data Store Performance Improvements Demo

*
https://cisco.webex.com/ciscosales/lsr.php?RCID=43af95c195404d10bba1f57a63049f1a%20[WebEx
recording]

[[md-sal-hackers-weekly-call]]
== MD-SAL Hackers Weekly Call

*Time and Location*

* 08:00am Pacific, Mondays.
* IRC: #opendaylight-meeting
*
https://meetings.webex.com/collabs/#/meetings/detail?uuid=MCT85SFEJTE5WAJSEMK35OXSR9-9VIB&rnd=134434.93272[WebEx
link]

*Agenda:* *Monday, February 9, 2015*

* maven archetype experiences

[[information-from-past-meetings]]
=== Information From Past Meetings

*Monday, February 2, 2015*

*
http://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_hackers/opendaylight-meeting-md_sal_hackers.2015-02-02-16.01.html[Minutes
(HTML)]

*Monday, January 12, 2015*

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_hackers/opendaylight-meeting-md_sal_hackers.2015-01-12-16.00.html[Minutes
(HTML)]

*Monday, January 5, 2015*

*
https://meetings.opendaylight.org/opendaylight-meeting/2015/md_sal_hackers/opendaylight-meeting-md_sal_hackers.2015-01-05-16.02.html[Minutes
(HTML)]

*Monday, October 20, 2014*

*
http://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_hackers/opendaylight-meeting-md_sal_hackers.2014-10-20-15.07.html[Minutes
(HTML)]

Action items

* alagalah
** says that he’ll take his recommmendations/links from last weeks, and
stuff from tpatellis, and publish a list of concrete things that need to
happen using bugzilla
** to come up with his list of adoption pain points by next meeting
** to take what he has done so far on the documentation front and break
it into chunks
** send out a list of things to do; if people have cycles, pick up the
item on the list a nd run with it
* colindixon
** to send e-mail noting his pain points: (1) it’s hard to figure out
how to take the yang file for the config subsystem and translate it into
an XML file, and (2) the config yang file is compiled in a different way
than yangtools does
* jmedved
** to start background architecture wiki using keith’s documentation
** start architecture section for config subsystem on wiki

*Monday, October 13, 2014*

*
https://meetings.opendaylight.org/opendaylight-meeting/2014/md_sal_hackers_meeting/opendaylight-meeting-md_sal_hackers_meeting.2014-10-13-15.08.html[Minutes
(HTML)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=f234c4a69f894d32bd9f9b2f0aaf4f48[WebEx
recording]

Action items

* alagalah to set up meeting with Devin, Tom, John Burns, Maros, and
whoever wants to join, to walk through the links in the "how tos", with
a consistent template style structure, incorporating alagalah's
recommendations + other's input

*Monday, October 6, 2014*

*
https://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-10-06-15.06.html[Minutes
(HTML)]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=f234c4a69f894d32bd9f9b2f0aaf4f48[WebEx
recording]

Action items

* colindixon to help try and convert this page into a step-by-step gude:
https://wiki.opendaylight.org/view/OpenDaylight_Controller:Config:Examples:Sample_Project
* Everyone learn config subsystem :)
* alagalah to be guinea pig to go through documentation linked in this
meetbot to see if its useful for a noob to learn config subsystem...
target: 10/13
* rovarga to provide examples of how to to live reconfiguration to
devinavery (and probably the controller-dev list)

[[all-subpages]]
== All Subpages:

OpenDaylight_Controller:MD-SAL:Work Item Candidates[ Work Item
Candidates]
