[[bug-reports]]
== Bug Reports

[https://bugs.opendaylight.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=IN_PROGRESS&bug_status=WAITING_FOR_REVIEW&component=mdsal&f1=cf_target_milestone&list_id=18387&o1=equals&product=controller&query_format=advanced&resolution=---&short_desc=Clustering&short_desc_type=casesubstring
All clustering bugs/enhancements]

[https://bugs.opendaylight.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=IN_PROGRESS&bug_status=WAITING_FOR_REVIEW&component=mdsal&f1=cf_target_milestone&list_id=18387&o1=equals&product=controller&query_format=advanced&resolution=---&short_desc=Clustering&short_desc_type=casesubstring&v1=Lithium
Clustering bugs/enhancements for the current release (Lithium)]

[[hackers-meeting]]
== Hackers Meeting

https://meetings.webex.com/collabs/meetings/join?uuid=MALTOMIMY5WPSZORCBFJSNI22V-9VIB[WebEx
Link]

[[regular-agenda]]
=== Regular Agenda

* Open reviews
* Bugs
* Topic of the Week

[[meeting-notes]]
=== Meeting Notes

[[section]]
==== 10/14/2014

* Went through outstanding gerrits
* Went through Helium-1 Bugs and got them all assigned
* Went through Lithium Bugs and added a few missing ones
* Short discussion on 2-Node cluster, Bug created.
* Short discussion on "What should an application do when availability
is lost?", Bug created.
* Decided on Agenda

[[action-items]]
===== Action items

* Luis will get single-node cluster testing enabled in Build environment
* Luis/Jan to do performance testing of single node cluster for
baselining
* Topic for next week : 2 Node Clustering

[[irc-notes]]
===== IRC Notes

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/hackers_call/opendaylight-clustering-hackers_call.2014-10-14-16.57.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/hackers_call/opendaylight-clustering-hackers_call.2014-10-14-16.57.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/hackers_call/opendaylight-clustering-hackers_call.2014-10-14-16.57.log.html

[[section-1]]
==== 10/21/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-10-21-15.06.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-10-21-15.06.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-10-21-15.06.log.html

[[section-2]]
==== 10/28/2014

[[clustering-hackers-call]]
===== Clustering Hackers Call

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_call_/opendaylight-clustering-_clustering_hackers_call_.2014-10-28-15.00.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_call_/opendaylight-clustering-_clustering_hackers_call_.2014-10-28-15.00.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_call_/opendaylight-clustering-_clustering_hackers_call_.2014-10-28-15.00.log.html

[[normalized-node-streaming-changes-call]]
===== Normalized Node Streaming changes Call

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_streaming_design_/opendaylight-clustering-_streaming_design_.2014-10-28-17.18.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_streaming_design_/opendaylight-clustering-_streaming_design_.2014-10-28-17.18.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_streaming_design_/opendaylight-clustering-_streaming_design_.2014-10-28-17.18.log.html

[[section-3]]
==== 11/04/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-04-16.01.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-04-16.01.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-04-16.01.log.html

Other action items which may not be in the transcript

* rovarga : Document the clustered datastore NormalizedNode custom
serialization format
* rovarga asked a question about impact of finer grained sharding on the
clustered datastore. moizr's response a lot of Raft activity. colindixon
suggests we could reduce Raft activity by decoupling Raft from the
stateful actors. moizr thinks this is probably going to be more work and
maybe transporting data across shards may be one way to achieve data
locality without very fine grained sharding.

[[section-4]]
==== 11/11/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-11-16.06.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-11-16.06.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clustering_hackers_/opendaylight-clustering-_clustering_hackers_.2014-11-11-16.06.log.html

*
https://wiki.opendaylight.org/images/d/d5/2-Node_Clustering.pptx[2-Node
Clustering Presentation (Work In Progress)]

[[section-5]]
==== 11/17/2014

[[node-strategy-meeting]]
===== 2-Node Strategy Meeting

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_2node_strategy_/opendaylight-clustering-_2node_strategy_.2014-11-17-21.19.html
* Minutes
(text):http://meetings.opendaylight.org/opendaylight-clustering/2014/_2node_strategy_/opendaylight-clustering-_2node_strategy_.2014-11-17-21.19.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_2node_strategy_/opendaylight-clustering-_2node_strategy_.2014-11-17-21.19.log.html

[[hackers-call]]
===== Hackers call

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-11-18-16.06.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-11-18-16.06.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-11-18-16.06.log.html

[[section-6]]
==== 11/25/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-11-25-16.02.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-11-25-16.02.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-11-25-16.02.log.html

[[section-7]]
==== 12/2/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-12-02-16.00.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-12-02-16.00.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/clustering_hackers/opendaylight-clustering-clustering_hackers.2014-12-02-16.00.log.html

[[section-8]]
==== 12/9/2014

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-12-09-16.01.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-12-09-16.01.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2014/_clusteringhackers_/opendaylight-clustering-_clusteringhackers_.2014-12-09-16.01.log.html

[[section-9]]
==== 12/16/2014

Meeting cancelled

[[section-10]]
==== 12/23/2014

Meeting cancelled

[[section-11]]
==== 12/30/2014

Meeting cancelled

[[section-12]]
==== 01/06/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/hackers/opendaylight-clustering-hackers.2015-01-06-16.00.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/hackers/opendaylight-clustering-hackers.2015-01-06-16.00.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/hackers/opendaylight-clustering-hackers.2015-01-06-16.00.log.html

[[section-13]]
==== 01/13/2015

Meeting cancelled. There was a snafu due to expiration of the previous
webex meeting. A new webex link has been added.

[[section-14]]
==== 02/03/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-03-16.02.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-03-16.02.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-03-16.02.log.html

[[section-15]]
==== 02/10/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-10-15.59.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-10-15.59.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-10-15.59.log.html

[[section-16]]
==== 02/17/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-17-16.00.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-17-16.00.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-17-16.00.log.html

[[section-17]]
==== 02/24/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-24-15.58.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-24-15.58.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-02-24-15.58.log.html

[[section-18]]
==== 03/3/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-03-15.57.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-03-15.57.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-03-15.57.log.html

[[section-19]]
==== 03/10/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-10-16.05.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-10-16.05.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-10-16.05.log.html

[[section-20]]
==== 03/17/2015

Cancelled

[[section-21]]
==== 03/24/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-24-15.04.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-24-15.04.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-24-15.04.log.html

[[section-22]]
==== 03/31/2015

* Minutes:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-31-14.58.html
* Minutes (text):
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-31-14.58.txt
* Log:
http://meetings.opendaylight.org/opendaylight-clustering/2015/clustering_hackers/opendaylight-clustering-clustering_hackers.2015-03-31-14.58.log.html

