[cols="^",]
|=======================================================================
|*Guide Contents*

|OpenDaylight Controller:Overview[OpenDaylight Controller Overview] +
OpenDaylight Controller:Architectural Framework[Architectural
Framework] +
OpenDaylight Controller:Development Infrastructure Overview[Development
Infrastructure Overview] +
OpenDaylight Controller:Pulling, Hacking, and Pushing the Code from the CLI[Pulling,
Hacking, and Pushing the Code from the CLI] +
OpenDaylight Controller:Pulling, Hacking, and Pushing the Code from Eclipse[Pulling,
Hacking, and Pushing the Code from Eclipse] +
OpenDaylight Controller:Sample Applications[Sample Applications] +
OpenDaylight Controller:Library Descriptions[Library Descriptions] +
OpenDaylight Controller:REST Reference and Authentication[REST Reference
and Authentication] +
OpenDaylight Controller:Java API Reference[Java API Reference] +
OpenDaylight Controller:Topologies[Topologies] +
OpenDaylight Controller:Main[Top Level Contents]
|=======================================================================

[[eclipse-setup]]
== Eclipse Setup

Set up Eclipse to import from CLI-pulled code without errors:
GettingStarted: Eclipse[GettingStarted: Eclipse]

[[pull-code-in-eclipse]]
== Pull Code in Eclipse

Get eclipse working with Gerrit, Jenkins, etc:
OpenDaylight Controller:Eclipse Setup[Setup Eclipse]

[[importing-opendaylight-controller-into-eclipse]]
== Importing OpenDaylight Controller into Eclipse

Many thanks to Brent Salisbury for contributing
OpenDaylight Controller:Importing OpenDaylight Controller into Eclipse[Importing
OpenDaylight Controller into Eclipse].

Category:OpenDaylight Controller[Category:OpenDaylight Controller]
