[cols="^",]
|=======================================================================
|*Guide Contents*

|OpenDaylight Controller:Overview[OpenDaylight Controller Overview] +
OpenDaylight Controller:Architectural Framework[Architectural
Framework] +
OpenDaylight Controller:Development Infrastructure Overview[Development
Infrastructure Overview] +
OpenDaylight Controller:Pulling, Hacking, and Pushing the Code from the CLI[Pulling,
Hacking, and Pushing the Code from the CLI] +
OpenDaylight Controller:Pulling, Hacking, and Pushing the Code from Eclipse[Pulling,
Hacking, and Pushing the Code from Eclipse] +
OpenDaylight Controller:Sample Applications[Sample Applications] +
OpenDaylight Controller:Library Descriptions[Library Descriptions] +
OpenDaylight Controller:REST Reference and Authentication[REST Reference
and Authentication] +
OpenDaylight Controller:Java API Reference[Java API Reference] +
OpenDaylight Controller:Topologies[Topologies] +
OpenDaylight Controller:Main[Top Level Contents]
|=======================================================================

[[rest-reference]]
== REST Reference

You can locate the REST API reference information for each of the
modules by navigating to the northbound module directories in your
installation. The OpenDaylight Controller REST API contains the
following modules. The associated module directory for the API reference
content is listed:

*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/topology/target/site/wsdocs/index.html[Topology
REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/hosttracker/target/site/wsdocs/index.html[Host
Tracker REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/flowprogrammer/target/site/wsdocs/index.html[Flow
Programmer REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/staticrouting/target/site/wsdocs/index.html[Static
Routing REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/statistics/target/site/wsdocs/index.html[Statistics
REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/subnets/target/site/wsdocs/index.html[Subnets
REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/switchmanager/target/site/wsdocs/index.html[Switch
Manager REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/usermanager/target/site/wsdocs/index.html[User
Manager REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/containermanager/target/site/wsdocs/index.html[Container
Manager REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/connectionmanager/target/site/wsdocs/index.html[Connection
Manager REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/networkconfiguration/bridgedomain/target/site/wsdocs/index.html[Bridge
Domain REST APIs]
*
https://jenkins.opendaylight.org/controller/job/controlller-merge-hydrogen-stable/lastSuccessfulBuild/artifact/opendaylight/northbound/networkconfiguration/neutron/target/site/wsdocs/index.html[Neutron
ML2 / Network Configuration APIs]

In each case you will find the detailed information about the module's
REST resources and their verbs (description, URI, parameters, responses,
and status codes), schemas, example XML, example JSON, as well as
programming examples.

[[rest-authentication]]
== REST Authentication

The OpenDaylight Controller provides HTTP Digest authentication for
Local users created on the Controller. The Local user creation can only
be done via the web graphical user interface and these users can be
given authorization to handle one or more slices. The username/password
created for an individual user on the web graphical user interface can
be used over the REST API to access relevant resources.

HTTPS support is available as of March, 2013, and the controller REST
APIs will migrate from HTTP Digest mechanism to HTTP Basic.

[[current-rest-convention]]
== Current REST Convention

* Please refer to :
https://wiki.opendaylight.org/view/OpenDaylight_Controller:REST_Reference_and_Authentication:Convention[Current
Convention] for a detailed discussion on the Current Convention that is
being used and the proposed alternatives.
* Also, we have a discussion scheduled on 11/07. Webex details in the
above URL.

Category:OpenDaylight Controller[Category:OpenDaylight Controller]
Category:AD-SAL
