`   Purpose`

`   Describe the base services provided by SAL, SAL will try to abstract all the commonalities among different SDN technologies and will provide interfaces for them, here is a schema of the SAL building blocks.`

---------------------------------------------------------------
+---------+
|         |              +--------+            +--------+
| ARP     |              |        |            |        |
|Handler  |              |Topology|            | Switch |
+---+-----+              |Manager |            | Manager| 
    |                    |        |            |        |
    |                    +-+------+            +---+----+
    \                      |                       |
     |                     /                       |
     |     +---------+    |                       /
     |     |         |    |                      |
     |     | FRM     |    /                      |
     \     |         |   |                       |
      |    +---+--+--+   /                       /
      |        |   \    |                       |   
  +---+--------+----`.--+-----------------------+------------+
  | +-+----++--+---++-+-+--+        +------++---+--++------+ |
  | |Data  ||Flow  ||Topol.|        |Stats ||Inven.||Resou | |
  | |Packet||Progr.||Serv. |        |      ||Serv. ||Serv. | |
  | +------++------++------+        +------++------++------+ |
  |                _____         _                           |
  |               / ____|  /\   | |                          |
  |              | (___   /  \  | |                          |
  |               \___ \ / /\ \ | |                          |
  |               ____) / ____ \| |____                      |
  |              |_____/_/    \_\______|                     |
  |                                                          |
  | +------------------------------------------------------+ |
  | |                                                      | |
  | |    SOUTHBOUND HOOKS                                  | |
  | |                                                      | |
  | +------------------------------------------------------+ |
  +--+---^----------------+---^----------------+---^---------+
     |   |                |   |                |   |
  +--v---+----------+  +--v---+----------+  +--v---+----------+
  |  glue logic     |  |  glue logic     |  |  glue logic     |
  | +-------------+ |  | +-------------+ |  | +-------------+ |
  | | OPENFLOW    | |  | | ONEPK       | |  | | PCEP        | |
  | |             | |  | |             | |  | |             | |
  | +-------------+ |  | +-------------+ |  | +-------------+ |
  +-----------------+  +-----------------+  +-----------------+
---------------------------------------------------------------

`   Overview`

`   SAL is not a simple stiching layer but need to contain business logic in order to adapt to the different southbound technologies:`

*
`       Topology Service is a set of services that allow to convey topology informations like a new node a new link has been discovered and so on.`
*
`       Data Packet services, in summary the possibility to deliver to applications the packets coming from the agents, if any.`
*
`       Flow Programming service is supposed to provide the necessary logic to program in the different agents a Match/Actions rule.`
*
`       Statistics service,  will export API to be able to collect statistics at least per:` +
`       `
** `               Flow`
** `               Node Connector (port)`
** `               Queue`
*
`       Inventory service will provide APIs for returning inventory information about the node and node connectors for example`
*
`       Resource service is a placeholder to query resource status, for now the idea there is still fuzzy`

