[[architecture-sub-group]]
== Architecture Sub-Group

*Leader:*

* Mickey Spiegel

*Members:*

* Mike Dvorkin
* Keith Burns
* Dan Conde
* Sanjay Agrawal
* Ryan Moats
* Uyen Chau
* Rob Adams
* Allyn Romanow
* Jan Medved
* Rex Pugh
* Chris Price
* Daljeet Singh

[[charterpurpose]]
== Charter/Purpose

[[documents]]
== Documents

https://wiki.opendaylight.org/images/6/68/Service_Function_Chaining_and_Traffic_Steering_Use_cases.pdf[Service
Function Chaining Use Cases]

https://wiki.opendaylight.org/images/d/db/PAULQUINN_SFC_DISCUSSION.pptx[Diagrams
from Paul Quinn's SFC presentation on 8/1/2014]

https://wiki.opendaylight.org/images/3/36/SLBS%2BChains.pptx[Use Cases
7/21/2014]

https://wiki.opendaylight.org/images/6/6a/SLBS%2BChains_and_other_stuff.pptx[Architecture
7/28/2014]

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 10am Pacific, Friday.
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.
* WebEx:
https://cisco.webex.com/ciscosales/j.php?MTID=mdfede3d482ceede44a93acdcca9f0e2e[WebEx]

*Agenda: Fri August 1*

* Documentation Discussion

* **
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:Helium_Installation[Proposed
Helium Installation Guide Template]
*** We currently have a small wiki page on building and running Group
Policy
**
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:Helium_User_Guide[Proposed
Helium User Guide Template]
*** Need to write new User Guide content and/or crib from Dave Lenrow's
Policy for Dummies document
**
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:Helium_Developer_Guide[Proposed
Helium Developer Guide Template]
*** Note: Reading the Docs wiki, there is considerable confusion over
what the Developer Guide is. Some of the content refers to Programming,
but the outline refers to use cases, architecture, getting started,
archetypes, config subsystem, exploring code, sounds like the kitchen
sink. Need to clarify to what extent architecture belongs in Developer
Guide or Operations Guide
** Operations Guide
*** Architecture write up (including textual description of model)
already exists
*** Note: In at least one place, under Operations Guide they linked the
architecture wikis, which currently includes the Group Policy
Architecture write up
*** Do we want to describe model in text? UML? Mike's pseudo-CLI? Yang?
** How To's/Tutorials
*** Overlap with User Guide?
** API References
*** Auto-generated?
** Everything needs to be converted to
http://powerman.name/doc/asciidoc[ascii doc] format and submitted as
patches using new
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:Tools[documentation
tools]

[[information-from-past-meetings]]
== Information From Past Meetings

*Fri Aug 1*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-08-01-16.59.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-08-01-16.59.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-08-01-16.59.log.html[Log
(HTML)]

*Mon July 28 (swapped with requirements meeting for this week)*

Agenda

* Discuss proposed model for SFC and traffic steering intent: detailed
syntax and semantics including "connector" or "interface" definition
* Discuss SFC behavior across a load balancer with VIPs, including the
question regarding which contract applies on either side of the load
balancer, and whether there is a notion of "hopping" between contracts /
service graphs in case the VIPs and the servers are not in the same
endpoint group

http://meetings.opendaylight.org/opendaylight-group-policy/2014/requirements_and_arch_carry_over/opendaylight-group-policy-requirements_and_arch_carry_over.2014-07-28-19.59.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/requirements_and_arch_carry_over/opendaylight-group-policy-requirements_and_arch_carry_over.2014-07-28-19.59.txt[(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/requirements_and_arch_carry_over/opendaylight-group-policy-requirements_and_arch_carry_over.2014-07-28-19.59.log.html[Log
(HTML)]

*Fri July 18*

Agenda

* Discuss proposed GBP extensions for SFC and traffic steering
* Analyse versus use cases

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-18-17.01.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-18-17.01.txt[(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-18-17.01.log.html[Log
(HTML)]

*Fri July 11*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-11-17.01.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-11-17.01.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-07-11-17.01.log.html[Log
(HTML)]

*Fri June 27*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-06-27-18.03.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-06-27-18.03.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch/opendaylight-group-policy-gbp_arch.2014-06-27-18.03.log.html[Log
(HTML)]

*Fri June 20*

https://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_arch/opendaylight-group-policy-odl_gbp_arch.2014-06-20-18.03.html

*Fri June 13*

https://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_arch/opendaylight-group-policy-odl_gbp_arch.2014-06-13-17.59.html

*Fri May 23*

Agenda

* Tenant discussion from opendaylight mailing lists: Any specific
implications or requirements with regard to group-based policy?
* NB API discussion: REST vs RESTConf, Neutron Group Policy plugin, any
other language bindings required?
* Subscription: Does MD-SAL support subscription based on match of child
object or grandchild object? For example, all contracts with quality foo
directly or quality foo under some target.

* Action items

* ** Mickey/Rob by May23 to build up a list of specific parts of the UML
model that the MD-SAL has to support subscription services for

http://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_arch/opendaylight-group-policy-odl_gbp_arch.2014-05-23-18.06.html[Minutes]

*Fri May 9*

Agenda

* Policy repository/subscription responsibilities versus renderer
responsibilities
* Continue discussion of subscription use cases and flows

* Action items

* ** we need to handoff to DATASTORE subgroup to have more detailed
requirements. jmedved
** to modeling group to deal with directionality.
** is for readams and dvorkinista

*
http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_arch_may9/opendaylight-group-policy-gbp_arch_may9.2014-05-09-18.22.html[Minutes]
*
https://cisco.webex.com/ciscosales/lsr.php?RCID=f6d15e83382b4fc291f5f52c04370888[WebEx
recording]

*Friday May 2*

Agenda:

* Subscription: impact of policy models and renderers, leading to
definition of renderer common code (further material to be provided on
the morning of May 2)
* Purpose of Data Services Engine (DSE) (note: just discussing what in
this meeting, how will be discussed later)

*Impact of Policy Models on Subscription* +
The intent is that most of the discussion at this meeting will be about
subscription, in particular the impact of the proposed policy models.
This should help determine the content of the Renderer Common block from
the
https://docs.google.com/drawings/d/1S0TJ_roOijBaWwFiIlvr7s7IAdshA4xznKtRHpHs-CU/edit?usp=sharing[architecture
diagram] introduced at yesterday's status meeting.

Many relationships in the policy model are parent-child. MD-SAL
subscription directly addresses these relationships through the notion
of subscription to a subtree. Two examples:

1.  Subscription to the subtree under a particular contract will return
all of the clauses, subjects, rules, classifier scopes, actions,
targets, and qualities under that contract.
2.  Subscription to the subtree under a particular endpoint group will
return all of the selection relators, quality matchers, capabilities,
conditions, and roles under that endpoint group.

Many relationships in the policy model are not parent-child, primarily
direct and indirect references. This includes the relationships between:

1.  endpoint group and contract through selection relators
2.  clause and subject
3.  classifier scope and classifier
4.  endpoint group or endpoint and score
5.  endpoint group or endpoint and circumstance
6.  The relationship between endpoint group and network domain
7.  The relationship between subnet and forwarding context
8.  The relationship between L2 flooding domain context and L2 broadcast
domain context
9.  The relationship between L2 context and L3 context

Which of these relationships do renderers need to follow from the point
of view of subscription? +
Are the mechanisms to follow these relationships and subscribe to
corresponding subtrees the responsibility of the Renderer Common
block? +
What do you subscribe to in order to catch new subtrees coming into
scope? For example, a new contract is defined which comes into the scope
of a selection relator for a particular endpoint group. +
 The impact of inheritance on subscription also needs to be
investigated.

*Subscription Requirements of Renderers* +
In terms of what kinds of subscription renderers require, there seem to
be two extreme cases:

* If there is a centralized, stateful, all knowing renderer that keeps
its own models of all policy-related things, then it just needs to
subscribe to all policy-related subtrees. Any time a new or modified
policy object comes down, the impact on relationships to other policy
objects is captured through that renderer's specific models.
* A relatively stateless renderer that simply provides model
transformations between policy models and the models for southbound
protocol plugins, for example a native renderer to OpFlex. The renderer
subscribes to policy objects and classes on behalf of devices below,
only keeping track of which subscriptions are on behalf of which
devices. The renderer relies on MD-SAL subscription to drive down new
and modified policy objects according to its subscriptions. Any
subscription chain of interest to any device below must be supported
through the combination of the renderer and MD-SAL subscription / policy
repository.

In reality there will probably need to be some mix of behaviors between
these two extreme cases.

Somewhat related to this is the distinction between proactive and
reactive subscription to policy objects. Proactive and reactive are not
overarching concepts, but need to be considered in the context of
particular relationships in the policy model. Each renderer can
implement its own combination of proactive and reactive behaviors,
requiring subscription chains following different relationships between
policy objects as listed above. Some examples:

1.  A virtual switch on a server is likely to pull policies relating to
endpoint groups in a reactive manner, when the first endpoint appears on
that virtual switch belonging to a particular endpoint group. Otherwise
all virtual switches pull down all endpoint groups, which is not
scalable.
2.  Should that virtual switch pull down all contracts provided by that
endpoint group, before it knows who that endpoint communicates with?
3.  Should that virtual switch pull down all contracts consumed by that
endpoint group, before it knows who that endpoint communicates with?
4.  Should that virtual switch pull down all endpoint groups consuming
the contracts that this endpoint group provides, in order to resolve
clauses, before it knows who that endpoint communicates with?
5.  Should that virtual switch pull down all endpoints in the endpoint
groups consuming the contracts that this endpoint group provides?
According to the current model, the relationship between endpoint and
endpoint group is unidirectional, so this is not supported.

Note that even with reactive behavior, subscription is necessary. New
policy objects can come into scope long after subscription is triggered.

https://meetings.opendaylight.org/opendaylight-group-policy/2014/arch/opendaylight-group-policy-arch.2014-05-02-18.02.html[Minutes]

*Friday April 25*

Agenda

Primary Goals

* Provide a clear picture of the Group-Based Policy Components where
MD-SAL plays a significant role, from the point of view of
messaging/routing. The conversation will probably touch on the data
store aspects to some extent since this is related to messaging/routing,
but we should attempt to focus primarily on messaging/routing.
* Describe the high-level flow between these Group-Based Policy
Components.

There is likely to be a fair amount of whiteboarding going on, so for
those in the South Bay area, you might prefer to attend the meeting in
person at the Noiro Networks Sunnyvale office.

*Current Architecture (Pre-MD-SAL) Configuration Flow*

* OpenStack Group-Based Policy Plugin
* RESTCONF NB API
* Contract Composer/Policy Repository Endpoint Registry
* Subscription Interface
* Renderer (one of Native/OpFlex, ACI, OpenDOVE, OVSDB Network
Virtualization, OpenFlow, etc)

*Current Architecture (Pre-MD-SAL) Operational Flow*

Events and status flow back up from the Renderer to the Enforcement
Exception Database and Operational State components, which will then
have northbound interactions with users

*High-Level Flow Steps*

1.  NB API to Policy Repository and Endpoint Registry
2.  Subscription Interface between Renderers and Policy Repository
3.  Events and status from Renderers back up to Enforcement Exception
Database and Operational State
4.  Enforcement Exception Database and Operational State up to users

For each of these steps, we need to begin to gather requirements on
MD-SAL messaging/routing.

For example, for step 2, in case of a native renderer, there are likely
to be devices below that need everything related to a particular
endpoint group. How does subscription grab all the contracts provided by
that endpoint group, all the contracts consumed by that endpoint group,
and everything underneath? If some contract is added and that endpoint
group provides that contract, anything that subscribed to that endpoint
group needs to get that contract in an event-driven manner. Whether that
happens directly, or something notifies it that a contract came into
scope and then it subscribes to that contract, we need to figure that
out.

* From Dave Lenrow:
* Service chaining for NFV and similar using policy (previously
presented proposals to ODL TWS for doing this with Affinity) and wanted
to discuss how we plan to support this in GBP

Minutes

*
https://meetings.opendaylight.org/opendaylight-group-policy/2014/policyarch_mickey_s_notes/opendaylight-group-policy-policyarch_mickey_s_notes.2014-04-26-14.49.html[Fri
Apr25]

*Friday April 18*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/opendaylight-group-policy.2014-04-18-18.02.html[Minutes]
