[[datastore-subgroup]]
== DataStore SubGroup

*Leader:*

* Ryan Moats

*Members:*

* Mike Dvorkin
* Keith Burns
* Liem Nguyen
* Rob Dolin
* Stephen Wong
* Hemanth Ravi
* Rob Adams
* Jan Medved
* Rex Pugh

[[charterpurpose]]
== Charter/Purpose

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 7am Pacific, Mondays.
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.

*Monday May12*

Agenda:

* Jan et al to present clustered datastore model based on Akka/APIC

* Action items
** alagalah to ensure that these minutes are linked to Renderer
sub-group page and ARCH page and in ARCH agenda
** alagalah to add whiteboard usecases to ARCH agenda

[[information-from-past-meetings]]
== Information From Past Meetings

*Monday May5*

Agenda:

\1. Keith/Rob to MD-SAL team: Can MD-SAL able to handle indexing/queries
that we need for the Contract/Policy repository? (this is a followon
from the ARCH team meeting 5/2)

https://meetings.opendaylight.org/opendaylight-group-policy/2014/datastore/opendaylight-group-policy-datastore.2014-05-05-14.01.html[Minutes]

*Mon Apr28*

Agenda

* Who is contributing and what time can you devote?
* Who is missing from this list?
https://wiki.opendaylight.org/view/Project_Proposals:Group_Based_Policy_Plugin#Resources_Committed_.28developers_committed_to_working.29[Resources]
* Follow up on the YANG discussion from last Friday
* How we test DataStore performance

http://meetings.opendaylight.org/opendaylight-group-policy/2014/datastore_4_28/opendaylight-group-policy-datastore_4_28.2014-04-28-14.01.html[Minutes]

*Mon Apr21*

Agenda

http://meetings.opendaylight.org/opendaylight-group-policy/2014/opendaylight-group-policy.2014-04-21-14.03.html[Minutes]
