[[model-meeting]]
== Model Meeting

*Leader:*

* Mike Dvorkin

*Members:*

* Keith Burns
* Ryan Moats
* Dave Lenrow
* Sanjay Agrawal
* Rob Dolin
* Stephen Wong
* Uyen Chau
* Derick Winkworth
* Mickey Spiegel
* Prasad Vellanki
* Rob Adams
* Allyn Romanow
* Jan Medved
* Louis Fourie

[[charterpurpose]]
== Charter/Purpose

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 10am Pacific, Fridays.
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.
* Hangout:
https://plus.google.com/hangouts/_/calendar/ZHZvcmtpbkBub2lyb25ldHdvcmtzLmNvbQ.6msm68t31c5fdn152g721o09ks?authuser=1

*Fri May16*

Agenda

* Action items

* ** alagalah to take whiteboard diagram of 3tier app with UML
representations (pic to come) and turn into JSON over the weekend
** alagalah to instead of writing whitepaper or annotating the UML to
write a PPT with animations that describes the UML model with
annotations.
** dvorkinista to restruct model in structure, definition use - has not
had time.
** alagalah regXboi edwarnicke to discuss service chaining, specifically
their datastore/subscription requirements and how they are planning on
addressing this with MD-SAL etc
** alagalah meeting with Uyen, Rex, Dave Lenrow, regXboi to discuss
Use-Case -> UML -> JSON "conversion" ... 14:30 Pac Fri May5
** alagalah meeting with Uyen, Rex, Dave Lenrow, regXboi to discuss
Use-Case -> UML -> JSON "conversion" ... 14:30 Pac Fri May9
** alagalah/readams to record a YouTube video going through the YANG
model sometime before May16 (next Fri MODEL meeting)
** readams to start working on ARCHITECTURE documentation / Functional
Spec starting next week. We will do the YouTube video post that
** readams to investigate if the YANG model can be changed to support a
clause referencing multiple subjects ( #info Clause then references a
particular subject in the YANG but in the UML it references multiple
subjects)
** alagalah to have a stab at seeing if there is a graphical way of
representing policy.yang (ie tree of this yang)

[[information-from-past-meetings]]
== Information From Past Meetings

*Fri June 27*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_model/opendaylight-group-policy-gbp_model.2014-06-27-17.04.html[Minutes
(HTML)]

[http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_model/opendaylight-group-policy-gbp_model.2014-06-27-17.04.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_model/opendaylight-group-policy-gbp_model.2014-06-27-17.04.log.html[Log
(HTML)]

*Fri June 20*

https://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_model/opendaylight-group-policy-odl_gbp_model.2014-06-20-17.10.html

*Fri June 13*

Minutes:
http://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_model/opendaylight-group-policy-odl_gbp_model.2014-06-13-17.08.html

*Fri June 6*

Minutes:
https://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_model/opendaylight-group-policy-gbp_model.2014-06-06-17.04.html

*Fri May9*

* Review of JSON derived from Wed May7 whiteboard session (pic to come)
* Whiteboard use cases from DATASTORE team meeting (will link minutes
from that meeting).

* Action items

* ** we need to handoff to DATASTORE subgroup to have more detailed
requirements. jmedved
** to modeling group to deal with directionality.
** is for readams and dvorkinista
* Action items
** dvorkinista (Mike D) to modify Matcher logic to be either ANDs, ORs,
with Label EXCLUDE for negation. This will be a single level ie (A AND B
AND C), (A OR B OR C), EXCLUDE (A AND B)
** alagalah will write a whitepaper that describes the UML model.
** we will annotate UML instead -- alagalah
** dvorkinista to restruct model in structure, definition use
** alagalah will talk w/ ed warnicke regarding service chaining.

*
http://meetings.opendaylight.org/opendaylight-group-policy/2014/model/opendaylight-group-policy-model.2014-05-09-17.04.html[Minutes]

*Fri May2*

Agenda

* Rob Adams update on UML -> YANG Model work
* Readout of discussion between Mike D, Rob A, Keith and Jan re:
creation of YANG (related to above)
* MikeD: Potential changes we may need to make to model to accommodate
YANG/MD-SAL implementation (hopefully minor)

https://meetings.opendaylight.org/opendaylight-group-policy/2014/model/opendaylight-group-policy-model.2014-05-02-17.05.html[1]

*Meeting Fri Apr25*

Agenda

* How does notion of tenant fit with model? (Mickey)
* Keith questions on model and changes between 0.96 and 0.97

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_model/opendaylight-group-policy-gbp_model.2014-04-25-17.06.html[Minutes]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/friapr25_model___mickey_s_notes/opendaylight-group-policy-friapr25_model___mickey_s_notes.2014-04-26-15.11.html[Mickey
Spiegel's Notes]

*Meeting Fri Apr18*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/opendaylight-group-policy.2014-04-18-17.07.html[Minutes]
