[[operational-state-subgroup]]
== Operational State SubGroup

*Leader:*

* Keith Burns

*Members:*

* Mike Dvorkin
* Raghurama Bhat
* Chris Price
* Rob Adams

[[charterpurpose]]
== Charter/Purpose

More than stats and counters. It is normalization of the capacity
constraints, utilization, etc.

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 1:30pm Pacific, Wednesdays.
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.

*Wed May21*

Agenda

* YANG model draft/discussion for Operational State functionality -
Keith.

*Wed May14*

Post-poned due to OpenStack conference

[[information-from-past-meetings]]
== Information From Past Meetings

*Wed May7*

Agenda None Minutes: None - still awaiting SCORE algorithms from Cisco
team as a reference. Model to be built.

*Wed Apr30*

Agenda

* Who is contributing and what time can you devote?
* Who is missing from this list?
https://wiki.opendaylight.org/view/Project_Proposals:Group_Based_Policy_Plugin#Resources_Committed_.28developers_committed_to_working.29[Resources]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/operational_state/opendaylight-group-policy-operational_state.2014-04-30-20.33.html[minutes]

*Wed Apr23*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/operational_state/opendaylight-group-policy-operational_state.2014-04-23-21.38.html[Minutes]
