[[requirements-sub-group]]
== Requirements Sub-Group

*Leader:*

* Dave Lenrow

*Members:*

IRC nicknames & Email address

* Dave Lenrow
* Mike Cohen
* Mickey Spiegel
* Prasad Vellanki
* Uyen Chau
* Sanjay Agrawal
* Bhushan Kanekar
* Kiran Yedavilli
* Dan Conde
* Thomas Bachman
* Christopher Price
* Yi Yang

[[charterpurpose]]
== Charter/Purpose

* Identify requirements to assist the definition of the GBP Model. This
will be based on customer use cases as much as possible.

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 1 pm Pacific, Monday. (Commence June 2, 2014)
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.

[[webex]]
== Webex

No meeting on Mon Aug18 as per our agreement on Monday.

Where:
https://cisco.webex.com/cisco/j.php?MTID=m73e1482e50d2c414dfcf28c1c55b959a
Meeting number: 205433908 Password: odlgbp Host key: 379230 (Use this
key in the meeting if you have made someone else the host and then want
to reclaim the host role.)

Audio Connection 1-855-244-8681 Call-in toll-free number (US/Canada)
1-650-479-3207 Call-in toll number (US/Canada) Meeting Number: 205 433
908 Need more numbers or information? Check out toll-free calling
restrictions.

[[google-hangout-backup]]
== Google Hangout (backup)

* If/When we have small numbers of attendees we may move to
* Hangout: TBD; previous link didn't work.

[[documents]]
== Documents

*Docs to inform discussion regarding ODL AAA, domains and GBP*

https://wiki.opendaylight.org/images/e/e3/OS-ODL_Mapping.pdf

https://wiki.opendaylight.org/images/a/a0/TWS-ODL-tenancy-preso-2014-06-02.pdf

*Doc describing Intent based NBI approach*

https://wiki.opendaylight.org/view/File:Extending_SDN_WP.docx

*Enterprise Access use cases* Enterprise Access, Dynamic Policy Use
cases https://wiki.opendaylight.org/view/File:Policy_Usecases.pptx

*Few use cases that need to be closed*
https://wiki.opendaylight.org/view/File:Priority_within_clause_rules.pptx

[[agenda]]
== Agenda

*Agenda: Monday, September 15, 2014*

Given no agenda Meeting on Monday Sep 15, 2014 cancelled.

[[information-from-past-meetings]]
== Information From Past Meetings

*Mon, September 8*

Given no agenda Meeting on Monday Sep 8, 2014 cancelled.

*Mon July 21*

Agenda

Mike Dvorkin to propose syntax & model extensions for
SFC/traffic-steering

http://meetings.opendaylight.org/opendaylight-group-policy/2014/usecase_discussion/opendaylight-group-policy-usecase_discussion.2014-07-21-20.02.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/usecase_discussion/opendaylight-group-policy-usecase_discussion.2014-07-21-20.02.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/usecase_discussion/opendaylight-group-policy-usecase_discussion.2014-07-21-20.02.log.html[log
(HTML)]

*Mon July 14*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_usecase/opendaylight-group-policy-gbp_usecase.2014-07-14-20.03.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_usecase/opendaylight-group-policy-gbp_usecase.2014-07-14-20.03.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_usecase/opendaylight-group-policy-gbp_usecase.2014-07-14-20.03.log.html[log
(HTML)]

*Mon July 7*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_usecases/opendaylight-group-policy-odl_usecases.2014-07-07-20.07.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_usecases/opendaylight-group-policy-odl_usecases.2014-07-07-20.07.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_usecases/opendaylight-group-policy-odl_usecases.2014-07-07-20.07.log.html[log
(HTML)]

*Mon June 30*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_requirements/opendaylight-group-policy-gbp_requirements.2014-06-30-20.00.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_requirements/opendaylight-group-policy-gbp_requirements.2014-06-30-20.00.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2014/gbp_requirements/opendaylight-group-policy-gbp_requirements.2014-06-30-20.00.log.html[log
(HTML)]

*Mon June 23*

http://meetings.opendaylight.org/opendaylight-group-policy/2014/usecases/opendaylight-group-policy-usecases.2014-06-23-20.05.html[Minutes
(HTML)]

*Mon June 16*

Minutes: 6/16/2014

https://meetings.opendaylight.org/opendaylight-group-policy/2014/group_policy_requirements/opendaylight-group-policy-group_policy_requirements.2014-06-16-20.08.html

Presentation 6/16/2014

https://wiki.opendaylight.org/images/f/fc/GBP_Requirements_Weekly_Meeting_6-16-2014.pdf

*Mon June 2*

https://meetings.opendaylight.org/opendaylight-group-policy/2014/odl_gbp_requirements/opendaylight-group-policy-odl_gbp_requirements.2014-06-02-20.01.html

Presentation:
https://wiki.opendaylight.org/images/c/c9/GBP_Requirements_Weekly_Meeting_6-2-2014.pdf
