[[status-meeting]]
== Status Meeting

*Leader:*

* Mike Dvorkin

*Members:*

* Keith Burns
* Thomas Bachman
* Rob Adams
* Dan Conde
* Stephen Wong
* Ryan Moats
* Daljeet Singh
* Mickey Spiegel
* Dave Lenrow
* Liem Nguyen
* Uyen Chau
* Rex Pugh
* Chris Price
* Raghurama Bhat
* Allyn Romanow
* Jan Medved
* Rob Dolin
* Sanjay Agrawal
* Derick Winkworth
* Prasad Vellanki
* Hemanth Ravi
* Yapeng Wu

[[charterpurpose]]
== Charter/Purpose

General review of sub-groups, general business, project tracking.

[[team-meeting]]
== Team Meeting

*Time and Location:*

* 10:00am Pacific, Friday.
* IRC: #opendaylight-group-policy
* Join and email
mailto:groupbasedpolicy-dev@lists.opendaylight.org[Group Policy Dev] for
a Calendar invite.
* WebEx:
https://meetings.webex.com/collabs/meetings/join?uuid=M4PO9GTADM5ZZWKPF30D5WC98O-9VIB
Meeting number: 191 387 614; Host key: 621809

*Agenda:* *Friday, May 29 2015*

* Alpha UI Demo
*
https://trello.com/b/yc0xHFlv/opendaylight-groupbasedpolicy-lithium[Trello]
* Other Items

[[information-from-past-meetings]]
== Information From Past Meetings

*Friday May 29*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-05-29-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-05-29-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-05-29-17.00.log.html[Log
(HTML)]

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=16119061&meetingInstanceID=I30SOYNL2KWICI5WHKSEE1KH85-9VIB[Webex
recording]

*Friday April 10*

*
http://meetings.opendaylight.org/opendaylight-meeting/2015/gbp_status_arch/opendaylight-meeting-gbp_status_arch.2015-04-10-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-meeting/2015/gbp_status_arch/opendaylight-meeting-gbp_status_arch.2015-04-10-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-meeting/2015/gbp_status_arch/opendaylight-meeting-gbp_status_arch.2015-04-10-17.00.log.html[Log
(HTML)]

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=15298741&meetingInstanceID=I2FOS9OXCPS0KWZEH9QHRW7Q07-9VIB[Webex
recording]

*Friday April 3*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-04-03-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-04-03-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-04-03-17.00.log.html[Log
(HTML)]

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=15298741&meetingInstanceID=I2FOS9OXCPS0KWZEH9QHRW7Q07-9VIB[Webex
recording]

*Friday March 27*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-27-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-27-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-27-17.00.log.html[Log
(HTML)]

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=15197141&meetingInstanceID=I2D1Z5E3ACD2KYIL2D0MAWAYE2-9VIB[Webex
recording]

*Friday March 20*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-20-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-20-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-20-17.00.log.html[Log
(HTML)]

*Friday March 13*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-13-17.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-13-17.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-03-13-17.00.log.html[Log
(HTML)]

*Friday Feb 27*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-27-18.02.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-27-18.02.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-27-18.02.log.html[Log
(HTML)]

*Friday Feb 20*

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-20-18.00.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-20-18.00.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-20-18.00.log.html[Log
(HTML)]

*Friday Feb 13*

*
https://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-13-18.00.html[Minutes
(HTML)]

*
https://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-13-18.00.txt[Minutes
(text)]

*
https://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-02-13-18.00.log.html[Log
(HTML)]

*Friday Feb 6*

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=14433636&meetingInstanceID=I3RF8SUSATNXF89CT7CW0PWB30-9VIB[2015-02-05,
Reinaldo SFC demo, webex recording]
*
https://meetings.webex.com/collabs/url/VvVrUGAbeDLYPAxlPgmw5TlduQHGLb1gjk5_E1rxDum00000[2015-02-05,
Reinaldo SFC demo, webex recording, alternate URL for non-US accounts]
*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_150206/opendaylight-group-policy-gbp_150206.2015-02-06-17.58.html[Minutes
(HTML)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_150206/opendaylight-group-policy-gbp_150206.2015-02-06-17.58.txt[Minutes
(text)]

*
http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_150206/opendaylight-group-policy-gbp_150206.2015-02-06-17.58.log.html[Log
(HTML)]
*
https://wiki.opendaylight.org/view/Service_Function_Chaining:Group_Based_Policy_Integration[SFC+GBP
Integration proposal]

*Friday Jan 30*

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_arch_status/opendaylight-group-policy-gbp_arch_status.2015-01-30-18.00.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_arch_status/opendaylight-group-policy-gbp_arch_status.2015-01-30-18.00.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_arch_status/opendaylight-group-policy-gbp_arch_status.2015-01-30-18.00.log.html[Log
(HTML)]

*Friday Jan 23*

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-23-18.00.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-23-18.00.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-23-18.00.log.html[Log
(HTML)]

https://cisco.webex.com/ciscosales/lsr.php?RCID=a82fcc9887cc4b1192afa82de20639c8[WebEx
Recording]

https://docs.google.com/presentation/d/1AO47EYrDMuTAypcpYbL3XOKFggZXu9x00XpGVwJLr9o/edit?usp=sharing[Neutron
presentation]

*Friday Jan 02*

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-02-18.00.html[Minutes
(HTML)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-02-18.00.txt[Minutes
(text)]

http://meetings.opendaylight.org/opendaylight-group-policy/2015/gbp_status_arch/opendaylight-group-policy-gbp_status_arch.2015-01-02-18.00.log.html[Log
(HTML)]

* link:Meeting Archives - 2014[Meeting Archives - 2014]

