[[vpn-service]]
= VPN Service

[[code-name]]
== Code Name

odl-vpnservice-core

[[description]]
== Description

The VPN Service will add an NSF to support L3 VPN service. This also
defines the YANG model to offer the L3 VPN service configuration. In
Lithium release it support creation of the BGP-MPLS L3 VPNs.

[[overview-design-architecture]]
=== Overview & Design Architecture:

 +
 Project_Proposals:VPN_Service[ Overview and Architecture]

[[test-topology]]
=== Test Topology:

File:VP-Topology.jpeg[framedless|center]

 +

[[configuration]]
=== Configuration:

Note: CLIs and REST API details will be added latteer

1.  Install the Quagga package inside the CSIT VM [URL to download to be
added]
2.  Install another instance of Quagga (to work as your DC-Gateway) in
another VM with reachablity to the CSIT VM
3.  Manually configure the BGP neighborship with the DC-GW
4.  Manage DPNs in ODL
5.  Create the Interfaces on the DPNS
6.  Manually configure the tunnel to the DC-GW
7.  Manually configure the tunnels between the DPNs
8.  Now user the REST to configure the VPN instance and associate the
Ports

 +

[[bundles]]
== Bundles

* odl-vpnservice-api
* odl-vpnservice-impl
* odl-vpnservice-impl-rest
* odl-vpnservice-impl-ui

[[upstream-dependencies]]
== Upstream Dependencies

The quagga routing stack to be installed running.

[[downstream-dependencies]]
== Downstream Dependencies

No downstream dependencies so far.

[[incompatibilities]]
== Incompatibilities

No incompatibilities detected so far.

[[network-intrusiveness]]
== Network Intrusiveness

None without explicit configuration.

[[recommended-karaf-features]]
== Recommended Karaf features

Recommended features for karaf testing:

* odl-vpnservice-core

[[how-to-test]]
== How to test

This feature provides REST NBI to configure the VPN instance, Interface,
nextHop and vpn_interface. The IODT tunnels and the Tunnel to the
Gateway to be configured manually.

The tests have to include:

* Successful installation of the VPN Service feature and the
dependencies
* Successful Creattion ot the IODT and the tunnel to the Gateway
* Successful CRUD operation for VPN instance, Interface, nextHop and
vpn_interface using the REST APIs
* Verification of state data present in ODL data store
* Successful ping between the VMs

 +
With the test cases above, we will confirm that the netconf connector
conforms as a client to the Netconf RFC. The CRUD and RPC tests aimed at
the loopback netconf tied to config subsystem will test also the netconf
northbound server.

Detailed Test Plan: To be updated

[[performancescalability-concerns]]
== Performance/Scalability Concerns

Category:Integration Group[Category:Integration Group]
Category:Integration Group[Category:Integration Group]
