`   Overview`

`   [NOTE WELL] The interface here presented will only be dispatching Data Packets, not protocol packets which for example in the case of OF travel in the same channel. The interface is exclusively designed for data packet dispatching because they are a common pattern.`

`   In order to define the services exported by SAL for data packet handling and the architecture for it, let start from an high lever view of what we need to do and the constraints. The picture below shows the goal we want to achieve, basically we SAL packet services need to be delivered to every application in each container. Of course SAL doesn't generate or consume packets so those need to be dispatched in/from the ``"Protocol Plugins"``, ``the interfaces indicated in the graphic below with "@" shows the interfaces and who will export in order to achieve what.`

----------------------------------------------------------------------------------------------
LEGEND                       ACRONYMS
 @ indicates an interface      ILDP:     IListenDataPacket
   registered in the OSGi      IDPS:     IDataPacketService
   service registry            IPODPS:   IPluginOutDataPacketService
                               IPIDPS:   IPluginInDataPacketService


                             #                             #
  +--------+   +--------+    #  +--------+   +--------+    #   +--------+   +--------+
  | ARP    |   | APP    |    #  | ARP    |   | APP    |    #   | ARP    |   | APP    |
  | Handler|   |  X     |    #  | Handler|   |  X     |    #   | Handler|   |  X     |
  |        |   |        |    #  |        |   |        |    #   |        |   |        |
  +--@-----+   +--@-----+    #  +--@-----+   +--@-----+    #   +--@-----+   +--@-----+
      ILDP         ILDP      #      ILDP         ILDP      #       ILDP         ILDP
                             #                             #
                             #                             #
                             #                             #
      IDPS                   #      IDPS                   #       IDPS
  +--@-------------------+   #  +--@-------------------+   #   +--@-------------------+
  |       SAL            |   #  |       SAL            |   #   |       SAL            |
  |                      |   #  |                      |   #   |                      |
  +.---.-@---------------+   #  +------@---------------+   #   +------@---------------+
   | \  \ IPODPS    CONTAINER#          IPODPS    CONTAINER#           IPODPS    CONTAINER
   |  \  +--._           RED #                         BLUE#                         GREEN
###|##&#39;#######`.##########################################################################
   |    --._    `-.
   |        ``-.._ `-..._
   |              `-.._  `&#39;`--..._
   |                   `--._      `&#39;`--..._
   |                        ``.            `&#39;`--..__
   |                           \                    `&#39;`--..__
   , IPIDPS IPIDPS IPIDPS       `. IPIDPS IPIDPS IPIDPS      `&#39;. IPIDPS IPIDPS IPIDPS
    -.RED)  (BLUE) (GREEN)        ._RED)  (BLUE) (GREEN)        `.RED)  (BLUE) (GREEN)
  +---@-----@------@-------+    +---@-----@------@-------+    +---@-----@------@-------+
  |   \     |      -       |    |                        |    |                        |
  |    `.   |     /        |    |                        |    |                        |
  | +----+--+----+-------+ |    |                        |    |                        |
  | | Packet Dispatcher  | |    |                        |    |                        |
  | |                    | |    |                        |    |                        |
  | +---^--------+-------+ |    |                        |    |                        |
  |     |        |         |    |                        |    |                        |
  | +---+--------v-------+ |    | +--------------------+ |    | +--------------------+ |
  | | OPENFLOW LIBRARY   | |    | | Protocol library P1| |    | | Protocol library P2| |
  | |                    | |    | |                    | |    | |                    | |
  | +--------------------+ |    | +--------------------+ |    | +--------------------+ |
  +------------------------+    +------------------------+    +------------------------+
   OpenFlow Protocol Plugin         P1 Protocol Plugin           P2 Protocol Plugin
----------------------------------------------------------------------------------------------

`   Interface details`

`   Lets start to expand every single interface as seen in the graphic above:`

*
`       ``IListenDataPacket``: this interface is supposed to be implemented by Application/Functional module bundles that want to receive data packets. Given we live in OSGi environment the interface will be registered in the service registry and certain optional property can be attached to the service as:` +
`       `
**
`               ConsumerName: which will define a unique name for the consumer of the packet, a reverse dns notation can help in making the naming unique`
**
`               ReceiveAfter: defines a comma separated list of ConsumerName that should see the packet before`
**
`               Filter: define a filter for the packet, the syntax is TBD.`
*
`           ``IDataPacketService``: this interface is supposed to be implemented by the SAL and are the services that SAL offer to the application, the main one is when an application wants to send out a packet toward the agent. Also this is a service that will be registered in the OSGi service registry so application can retrieve it.`
*
`           ``IPluginOutDataPacketService``: this interface is supposed to be exported by SAL when a ``Protocol plugin ``wants to deliver a packet toward the application layer when was received by the agent.`
*
`           ``IPluginInDataPacketService``: this interface is supposed to be exported by the ``Protocol plugin`` ``and is used to send out the frames from app through SAL toward the agent.`

`   Now lets show some of these interfaces in action based on a regular execution path:`

1. 
`       Lets say that the ``Protocol Plugin`` Openflow receives an 802.1x packet that need to be dispatched to applications.`
2. 
`       Openflow ``Protocol Plugin ``will classify the packet on belonging to a given container, assuming Openflow could be supporting the container concept else all will be assigned to the default container as fallback. Now the ``Protocol Plugin`` will call the interface ``IPluginOutDataPacketService ``to let the packet travel toward SAL. The service will be fetched from the OSGi service registry selecting among the several ones based on the container name.`
3. 
`       SAL will receive the packet and based on how has registered the ``IListenDataPacket ``will dispatch the packets to the app receiving it. The gist there is that the several listener if they didn't expressed constraints will receive a copy of the same packet in parallel so noone can override the other component from seeing the packet all of them will. If there is a need for a component to see a packet after someone else has done processing then he can express that in the service registration. In this way noone can preempt another component from receiving a packet, but one component can, express the desire to see the packet after another module has processed it, maybe simply because wants to get some extra information or wants extra filtering done.`
4.  `       The packet can be processed now by the application.`

`   Another regular path is when the packet is sent out from the application in that case the flow goes like this:`

1. 
`       The application create the packet and call the interface ``IDataPacketService ``provided by SAL to send out the packet, of course the destination node must be provided in the API, but for detailed API signature refer to the code.`
2. 
`       SAL will now call the ``IPluginInDataPacketService ``interface for a given ``Protocol Plugin ``based on the destination chosen. The service selected will be on a container base, so not to intermix traffic belonging to different containers.`
3. 
`       Protocol plugin will ship the packet toward the network element based based on the specific methodology of the plugin.`

