[[opendaylight-toolkit]]
= OpenDaylight Toolkit

OpenDaylight Toolkit is a framework to enabled developers to easily
develop applications on top of the OpenDaylight controller. Our goal is
to be infrastructure independent and allow developers to develop
application on top of multiple platforms.

Objectives:

* Repository of Archetypes for various use-cases. The use-cases may
include app development, infrastructure component development,
southbound plugin development, Custom distribution, user interface,
northbound APIs, apps using northbound REST APIs, etc.
* Provide the Archetypes catalog for OpenDaylight
* In addition to the code and related resources, these Archetype
templates can also include necessary development toolkits such as
eclipse launchers, debug helpers, etc.

[[project-information]]
== Project Information

* Project_Proposals:OpenDaylight_Toolkit[Project Proposal]
* Toolkit:Helium Release Plan[Release Plan (2014)]

[[project-backlog]]
=== Project Backlog

*
http://agilefant-opendaylight.rhcloud.com/ROIteration.action?readonlyToken=391383827832404875810158160784062621886[Sprint
6] *06/26 - 07/17*
* http://agilefant-opendaylight.rhcloud.com/[agilefant]

[[project-repo]]
=== Project Repo

*
https://git.opendaylight.org/gerrit/gitweb?p=toolkit.git;a=summary[gitweb]
* https://pad.opendaylight.org/p/toolkit[etherpad]
* http://webchat.freenode.net/?channels=opendaylight-toolkit[WebIRC]
* *git clone https://git.opendaylight.org/gerrit/p/toolkit.git*

[[getting-started]]
== Getting Started

[[draft-getting-started-on-linux]]
=== [Draft] Getting Started on Linux

The project comes with a sample simple application and a tool directory
where the web development environment is located. Here are the
instructions to run this setup:

1.  git clone https://git.opendaylight.org/gerrit/p/toolkit.git
2.  *mvn clean install* within the root directory
3.  *mvn clean install* within the samples/simple directory
4.  Start the controller under
_main/target/main-osgipackage/opendaylight_ and *./run.sh -console*
5.  Provision your CORS filter, under kit/provision run the provision.js
node application
6.  Then start the server *node server.js* within the tool/node
directory

Go to :8000 to start developing your simple web application. The simple
web application will access the northbound APIs of your simple
application at :8080

[[getting-started-on-mac-windows]]
=== Getting Started on Mac / Windows

* [[OpenDaylight_Toolkit:Main:Mac|[Draft] Getting Started on Mac]]
* OpenDaylight_Toolkit:Main:Windows[Getting Started on Windows]

[[sample-apps]]
=== Sample Apps

* OpenDaylight_Toolkit:Main:Sample:Simple[Simple App]
* TBD

