The IoTDM project is about developing a data-centric middleware that
will act as a oneM2M compliant IoT Data Broker (IOTDM) and enable
authorized applications to retrieve IoT data uploaded by any device.

[[project-information]]
== Project Information

Project_Proposals:Internet_of_Things_Data_Management_(IOTDM)[ Project
Proposal]

https://git.opendaylight.org/gerrit/#/q/project:iotdm,n,z[Git patches
and reviews]

https://jenkins.opendaylight.org/iotdm/[Jenkins]

link:IoTDM Overview[ Overview]

[cols=",,,,,,,,",options="header",]
|=======================================================================
|Release |Release Plan |Release Notes |Release Review |Installation
Guide |User Guide |Developer Guide |Operations Guide |How-To's/Tutorials
|Lithium |iotdm:Lithium_Release_Plan[Release Plan] |- |- |- |- |- |- |-
|=======================================================================

[[meeting-schedule-and-logistics]]
== Meeting Schedule and Logistics

IOTDM meetings are held bi-weekly for one hour on Wednesday afternoons
at 4:00pm (Pacific). The first meeting will be held on Jan 14, 2015 at
4:00p (Pacific) Meetings are held using WebEx for screen sharing and
audio.

* Meeting URL:
https://cisco.webex.com/cisco/j.php?MTID=me4eaae4a355195f93752224c7bdf95cf

* Access Information
** Meeting number: 203 492 617
** Meeting password: 123456

link:IoTDM Meeting Minutes[ Meeting Minutes]

[[getting-started-for-users]]
== Getting started for users

* There are several ways to use IoTDM. You may want to just send CRUD to
it, you may want to install it locally and CRUD to it, or you may want
to access the code and develop modules for it.

* If you want to download IoTDM and exercise the APIs, then follow the
following procedure:

* 1. Create a local directory and download the tar file distribution
from
https://www.dropbox.com/s/pef5wygdzsrz0xs/onem2m-karaf-0.0.1-SNAPSHOT.tar.gz?dl=0[here]
* 2. rename your file to onem2m-karaf-0.0.1-SNAPSHOT.tar.gz
* 3. cd to that directory and type

`tar –xvf onem2m-karaf-0.0.1-SNAPSHOT.tar.gz`

* 4 cd into onem2m-karaf-0.0.1-SNAPSHOT/bin
* 5. Launch IoTDM

./karaf

* 6. Prompt changes to opendaylight-user@root>
* 7. Wait for the karaf features to load
* 8. Verify oneM2M modules are active

opendaylight-user@root>list | grep onem2m

256 | Active | 80 | 0.0.1.SNAPSHOT | onem2m-api

257 | Active | 80 | 0.0.1.SNAPSHOT | onem2m-core

259 | Active | 80 | 0.0.1.SNAPSHOT | onem2m-notifier

261 | Active | 80 | 0.0.1.SNAPSHOT | onem2m-protocol-coap

262 | Active | 80 | 0.0.1.SNAPSHOT | onem2m-protocol-http

* 9. IoTDM is now running on port 8181 and 8282
* 10. Initialize the resource tree (if prompted for a username/password
type admin/admin).

* Send a POST to :

localhost:8181/restconf/operations/onem2m:onem2m-cse-provisioning

Headers Content-Type application/json Accept application/json

JSON Body \{ "input": \{

`       "onem2m-primitive": [` +
`          {` +
`               "name": "CSE_ID",` +
`               "value": "ODL-oneM2M-Cse"` +
`           },` +
`           {` +
`               "name": "CSE_TYPE",` +
`               "value": "IN-CSE"` +
`           }` +
`       ]` +
`   }`

}

* This will create a tree called ODL-oneM2M-Cse. You are ready to
exercise the CRUDs. See API examples
https://wiki.opendaylight.org/images/9/93/API_Calls_Examples.pdf[here]

[[information-for-developers]]
== Information for developers

* If you are unfamiliar with OpenDaylight development see the
Controller_Core_Functionality_Tutorials:Main[core tutorials] project.
* Make sure your development environment is
GettingStarted:Development_Environment_Setup[setup]:
* Getting the iotdm code from the repository:

`git clone `https://git.opendaylight.org/gerrit/p/iotdm.git[`https://git.opendaylight.org/gerrit/p/iotdm.git`] +
`cd iotdm`

* Build the code:

`mvn clean install`

* To bring up the iotdm onem2m features in karaf, if you have a
successful build,

`cd onem2m/onem2m-karaf/target/assembly/bin` +
`./karaf`

* TODO: more instructions to come on how to interact with karaf ...

[[externally-consumable-apis]]
== Externally Consumable APIs

* *IOTDM OneM2M feature*
** This feature enables access to the OneM2M resource tree via the HTTP
and CoAP protocols.
** RESTconf is also supported but it is a non-oneM2M standard method for
accessing the tree.
** Bundles providing the API: odl-iotdm-onem2m
** REST API commands include:
*** onem2m-request-primitive for CRUDN
** Examples of CRUDN calls and JSON formats are available
https://wiki.opendaylight.org/images/9/93/API_Calls_Examples.pdf[here]

[[list-of-all-subpages]]
== List of all subpages
