[[project-name]]
== Project Name

Defense4All

[[features]]
== Features

Defense4All is an SDN application for detecting and mitigating DDoS
attacks. It communicates with OpenDaylight Controller via the ODC
north-bound REST API to:

1.  Monitor behavior of protected traffic - the application sets flow
entries in selected network locations to read traffic statistics for
each of the PNs (aggregating statistics collected for a given PN from
multiple locations).
2.  Divert attacked traffic to selected AMSs – the application set flow
entries in selected network locations to divert traffic to selected
AMSs. When an attack is over the application removes these flow entries,
thus returning to normal operation and traffic monitoring.

Defense4All can optionally dynamically configure defined AMSs, monitor
them or collect and act upon attack statistics from them. It contains a
reference implementation pluggable driver to communicate with Radware’s
DefensePro AMS. Defense4All presents its north-bound REST and CLI APIs
to:

1.  Control and configure the application (runtime parameters, ODC
connectivity, AMSs in domain, PNs, etc.).
2.  Obtain reporting data – operational or security, current or
historical, unified from Defense4All and other sources (like ODC, AMSs).

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

* Installation Guide(s) - Defense4All:Installation_Guide[Installation
Guide]
* User Guide(s) - Defense4All:User Guide[User Guide]
* Developer Guide(s) - Defense4All:REST[Developer Guide ] (link to REST
API)

[[issues-to-be-fixed]]
== Issues to be fixed

* See Defense4All:Release_Notes[Release Notes] for known Issues and
Limitations.

[[security-considerations]]
== Security Considerations

Defense4All REST API presently does not check for credentials. Nor does
it define user roles according to which usage of certain REST APIs is
allowed/restricted.

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

Unit tests cover communications with ODC (integration test), usage of
Cassandra, and selective set of operations. Additional testcases for
functional coverage are planned for next release. Robustness is
accomplished via complementary means, such as extensive error handling
path, HealthTracker, restartability, etc. Please refer to Continuity
section in Defense4All:Tutorial[Tutorial / How-To] for more details.

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

No known bugs.

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)
