[[welcome-to-the-google-summer-of-code-ideas-page-for-opendaylight]]
= Welcome to the Google Summer of Code Ideas Page for OpenDaylight

This page is meant to connect OpenDaylight Projects and their Mentors
with students interested in working on OpenDaylight as part of the
Google Summer of Code (GSoC).

[[for-projects-and-mentors]]
== For Projects and Mentors

* Read the GSoC Mentor's guide to become familiar with what it means to
mentor a student as part of the GSoC program -
http://en.flossmanuals.net/GSoCMentoring[Link To GSoC Mentor's Guide]
* Each project proposed must have two Mentors identified. Mentors are
expected to spend around 10 hours per week mentoring their student
participants.
* Provide the Mentor's Names, Project Title, and a General Description
of the project you would like to have a student perform below in the
"Ideas" section. Each "Project" should be able to be completed in about
12 weeks. Students will use this description to decide if they want to
apply to work with you and OpenDaylight on the project you propose. If
you wish, you can also list a "blue-sky" project where the Student can
come up with the project idea and you will help mentor them through
task's design and implementation.

[[for-students]]
== For Students

* Please review the ideas below and if something sounds interesting,
please apply to participate with us.

[[ideas]]
== Ideas

The following are running ideas for GSoC Projects

[[automated-cluster-testing]]
=== Automated Cluster Testing

* *Mentors:* Mathieu Lemay
* *Title:* Enhance current testing automation to add testing of various
multinode cluster configurations.
* *Description:* Working with the integration testing group, write
automated devops test for a variety of different cluster and deployment
configurations (1-N nodes) which includes a variety of
OpenStack+OpenDaylight configurations.

[[tr-069-southbound-protocol]]
=== TR-069 Southbound Protocol

* *Mentors:* Mathieu Lemay
* *Title:* Implement a Southbound TR-069 protocol server used to
initially provision legacy CPE devices
* *Description:* Many DSL or FTTH CPE which are using IP are using
TR-069 for provisioning. Use the TR-069 Southbound will allow to
provision some legacy CPE that are not OpenFlow based.

[[of-config-southbound-protocol-tests]]
=== OF Config Southbound Protocol Tests

* *Mentors:* Mathieu Lemay
* *Title:* Implement good provisioning interactions via OF Config as an
alternative for OVSDB in some current scenarios
* *Description:* Working with the LINC, provision logical switches and
proper configuration using OFConfig southbound.

'''Not sure about the state of OF Config support in Hydrogen, please
correct if wrong '''

[[consistencyclustering]]
=== Consistency/Clustering

* *Mentors:* Colin Dixon
* *Title:* Enhance OpenDaylight's Consistency/Clustering APIs and
Implementation
* *Description:* Explore options for providing enhanced scale-out,
clustering, and consistency features and implement them. At a high
level, this involves replacing or improving the Infinispan-based
solution we currently have.

[[sample]]
=== Sample

* *Mentors:* John Doe , Jane Smith
* *Title:* Testing the REST API Of OpenDaylight Hydrogen
* *Description:* Using Robot and other automated testing tools, complete
the buildout of full combinatorial coverage of all REST APIs in
existance within OpenDaylight's Hydrogen release.

