[[developer-events]]
== Developer Events

[[opendaylight-hackfest---santa-clara-ca-april-15th16th-2015]]
=== OpenDaylight Hackfest - Santa Clara, CA April 15th/16th 2015

We look forward to welcoming you to the OpenDaylight Hackfest 2015 in
Santa Clara, CA on Wednesday, April 15 and Thursday, April 16. Below,
please find all logistical details you may need to prepare for your
arrival. +

[[agenda-topics-for-the-afternoon-of-april-15th]]
=== Agenda Topics for the Afternoon of April 15th

* Integration
* GBP
* NIC
* Persistence
* DIDM & Manual Discovery
* OVSDB
* Beryllium Planning

[[agenda-topics-for-the-morning-of-april-15th]]
=== Agenda Topics for the Morning of April 15th

* Integration
* SFC
* NIC
* GBP
* OVSDB

[[event-venue]]
==== Event Venue

Santa Clara Marriott 2700 Mission College Blvd Santa Clara, CA 95054

[[registration-badge-pick-up]]
==== Registration & Badge Pick-up

Registration is located in the Hall of Cities Foyer of the Santa Clara
Marriott and will open at 8:00am on Wednesday, April 15 and Thursday,
April 16.

[[hackfest-schedule]]
==== Hackfest Schedule

The hackfest will be located in the Hall of Cities Ballroom and is an
unconference format with breakout topics being determined each morning.
The schedule is outlined below.

*Wednesday, April 15* +
* 8:00am - 9:00am - Registration & Continental Breakfast

* 9:00am - 5:00pm - Hackfest
* 5:00pm - 7:00pm - Happy Hour

*Thursday, April 16* +
* 8:00am - 9:00am - Registration & Continental Breakfast

* 9:00am - 5:00pm - Hackfest

Continental breakfast, am/pm breaks and lunch will be provided on both
days.

Please join attendees for Happy Hour, with food & drinks included,
immediately following the hackfest on Wednesday evening.

[[parking]]
==== Parking

On-site self parking is available at the Marriott at a discounted rate
of $6/day.

[[code-of-conduct-for-collaboration]]
==== Code of Conduct for Collaboration

We ask for attendees to follow the general philosophy below when
interacting with one another: be considerate, respectful, and
collaborative community building is core to success open by default

[[questions-additional-information]]
==== Questions & Additional Information

If you need any assistance or have any questions, please do not hesitate
to visit the Registration Desk on-site or contact the OpenDaylight
events team at events@opendaylight.org prior to the event.

[[hackfests]]
=== HackFests

OpenDaylight HackFests are official events that are organized,
sponsored, and run by OpenDaylight. HackFests are key to the mission of
OpenDaylight with the purpose of bringing the technical community
together to write code, make decisions, onboard new and interested
developers, and generally move the project forward.

* Proposed mini-HackFest for MD-SAL developer and activity work areas:
April 22-24 in San Jose or Slovakia Europe.

* Upcoming HackFests

* Past HackFests
**
HackFestAgenda#HackFest_Agenda:_October_13.2C_2014_.28Dusseldorf.2C_Germany.29[
October 13th, 2014 in Dusseldorf, Germany]
**
HackFestAgenda#HackFest_Agenda:_October_29.2C_2014_.28Toyko.2C_Japan.29[October
29th, 2014 in Tokyo, Japan]
** HackFests:vHackFest Sept 19 2013[vHackFest Sept 19 2013]
** HackFestAgenda#HackFest_Agenda:_September_10-11[HackFest Sept 10-11
2013]
** HackFest July 22 2013:Main[HackFest July 22-23 2013]
** HackFest June 6 2013:Main[HackFest June 6-7 2013]
** HackFest April 10 2013:Main[HackFest April 10 2013]
** HackFestAgenda#HackFest_Agenda:_March_26th_-_28th[HackFest March 26th
- 28th 2014 in Napa Valley]

[[opendaylight-user-groups-odlug]]
=== OpenDaylight User Groups (ODLUG)

OpenDaylight User Groups (ODLUG) are regional, self-organized, informal
associations that meet globally to discuss OpenDaylight. The
participants in these groups share knowledge, recruit and onboard new
developers, discuss best practices and technical challenges, as well as
create awareness. ODLUG hold meetups, run small hackathons, and host
social events.
[http://www.opendaylight.org/software/opendaylight-user-groups-odlug#
Learn more].
