[[developer-events]]
== Developer Events

[[opendaylight-developer-design-forum-september-29-30-2014-santa-clara-ca]]
=== OpenDaylight Developer Design Forum, September 29 & 30, 2014, Santa
Clara, CA

The OpenDaylight Developer Design Forum is an event for the developer
community to engage in a range of hot topics geared towards networking.
Additionally the Forum will help set the stage for future OpenDaylight
releases. The OpenDaylight Developer Design Forum is an invitation only
event. If you are interested in attending this event, please
http://events.linuxfoundation.org/events/opendaylight-developer-design-forum/attend/invitation[request
an invitation here].

The Forum will be held at the
http://www.marriott.com/hotels/travel/sjcga-santa-clara-marriott/[Santa
Clara Marriott], Santa Clara, CA.

[[hackfests]]
=== HackFests

OpenDaylight HackFests are official events that are organized,
sponsored, and run by OpenDaylight. HackFests are key to the mission of
OpenDaylight with the purpose of bringing the technical community
together to write code, make decisions, onboard new and interested
developers, and generally move the project forward.

* Proposed mini-HackFest for MD-SAL developer and activity work areas:
April 22-24 in San Jose or Slovakia Europe.
* The next OpenDaylight HackFest is scheduled for October 13th, 2014 -
HackFestAgenda#HackFest_Agenda:_October_13.2C_2014_.28Dusseldorf.2C_Germany.29[HackFest
October 13th, 2014 in Dusseldorf]

* Past HackFests
** HackFests:vHackFest Sept 19 2013[vHackFest Sept 19 2013]
** HackFestAgenda#HackFest_Agenda:_September_10-11[HackFest Sept 10-11
2013]
** HackFest July 22 2013:Main[HackFest July 22-23 2013]
** HackFest June 6 2013:Main[HackFest June 6-7 2013]
** HackFest April 10 2013:Main[HackFest April 10 2013]
** HackFestAgenda#HackFest_Agenda:_March_26th_-_28th[HackFest March 26th
- 28th 2014 in Napa Valley]

[[opendaylight-user-groups-odlug]]
=== OpenDaylight User Groups (ODLUG)

OpenDaylight User Groups (ODLUG) are regional, self-organized, informal
associations that meet globally to discuss OpenDaylight. The
participants in these groups share knowledge, recruit and onboard new
developers, discuss best practices and technical challenges, as well as
create awareness. ODLUG hold meetups, run small hackathons, and host
social events.
[http://www.opendaylight.org/software/opendaylight-user-groups-odlug#
Learn more].
