[[project-name]]
== Project Name

sfc

[[features]]
== Features

* Yang models for expressing service function chains
* SFC Basic Provider to receive such expressions of intent through REST
and RPCs
* Openflow renderer
* LISP renderer
* SFC UI

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

Your project / feature should be included in the appropriate
link:Release/Hydrogen[Hydrogen Release Guides and Documentation]:

* Installation Guide(s)

git clone ssh://$\{ODL_USERNAME}@git.opendaylight.org:29418/sfc.git

Build SFC distribution. SFC distribution pull and build entire ODL
distribution and includes all necessary software

* User Guide(s)
* Developer Guide(s)

Status: In-Progress

[[architectural-issues]]
== Architectural Issues

N/A

[[security-considerations]]
== Security Considerations

We do not believe SFC introduced any new security considerations in ODL

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

SFC Provider uses Junit and Python unit test. Tests are added
continuously.

For SFC-UI unit testing we are using test runner called Karma
(http://karma-runner.github.io/). Karma is developed to work well with
AngularJS which is the main framework used in Dlux.

For test coverage, we are using extension of Karma called
Karma-coverage. This extension utilizes JS code coverage tool called
Istanbul (http://gotwarlost.github.io/istanbul/).

The unit tests are in different folders located in directory
sfc-ui/src/main/resources/pages/ in files ending with .spec.js
extension. These are written according to Jasmine framework
(http://jasmine.github.io/1.3/introduction.html).

Several changes in SFC-UI module were required to simplify test
execution. They are located in this commit:
https://git.opendaylight.org/gerrit/#/c/11572/ and are waiting for
review.

Step by step guide for test execution is located in sfc-ui/README.md

[Reinaldo] People keep me asking about Sonar and I keep asking how to
get SFC into Sonar....and nobody can tell me how to get SFC into Sonar.
Vicious cycle

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

N/A

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

https://bugs.opendaylight.org/buglist.cgi?list_id=17763&product=sfc&query_format=advanced&resolution=---

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

https://tools.ietf.org/html/draft-ietf-sfc-architecture-02

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)
