Service Function Chaining provides the ability to define an ordered list
of a network services (e.g. firewalls, load balancers). These service
are then "stitched" together in the network to create a service chain.
This project provides the infrastructure (chaining logic, APIs) needed
for ODL to provision a service chain in the network and an end-user
application for defining such chains.

[[project-documents]]
== Project Documents

* Project Information Documentation
** Project_Proposals:Service Function Chaining[Project Proposal]
** link:IETF Drafts[IETF Drafts]
** Service_Function_Chaining:Presentations[Presentations]

* Project Release Documentation
** Service_Function_Chaining:Lithium Release Plan[Lithium Release Plan]
** Service_Function_Chaining:Lithium_User_Facing_Features[ Lithium User
Facing Features]
**
https://wiki.opendaylight.org/view/Service_Function_Chaining:Main#Downloading.2C_Building.2C_and_Viewing_the_SFC_User_Guides[Lithium
ODL User and Dev guides]
** Service_Function_Chaining:Helium Release Plan[Helium Release Plan]
** Service_Function_Chaining:Helium Release Review[ Helium Release
Review]
** Service_Function_Chaining:Helium Release Notes[ Helium Release Notes]

[[sfc-sonar]]
== SFC Sonar

Sonar is a static analysis tool that finds bugs and provides suggestions
on how to make the code cleaner.

https://sonar.opendaylight.org/dashboard/index/19574[SFC Master Sonar]

[[sfc-tasks]]
== SFC TASKS

We are now (as of March 13, 2015) using Trello to track and monitor
tasks.

https://trello.com/opendaylightsfc[SFC organization Trello boards]

https://trello.com/b/a3lpAhHs/sfc-lithium[SFC Lithium Trello board]

The following lists are now deprecated, and are only kept for reference.
Soon only the finished items will remain, and any pending items will be
migrated to Trello.

[[helium-and-preivous]]
=== Helium and preivous

* _(Done)_ Integrate the config file bootstrap so the code is fully self
healing (High Priority)
* _(Done)_Iron out the JSON object to provision a SFF (see point below).
This will most likely be similar to SFF Yang model.
* _(Done)_ Implement REST API to communicate southbound with switch
front-end. This API will send the JSON object to the server that will
communicate with switches
* _(Done)_ Integrate with dlux UI
* _(Done)_ Integrate the distribution POMs
* _(Done)_ At some point move to the new DataBroker APIs. Hopefully
somebody else will weed out the bugs.
* _(Done)_ Integrate with LISP service
* _(Done)_ Python regression tests
* _(Done)_ Fix windows line terminators
* _(Done)_ Logback configuration for tracing messages
* _(Done)_ SFF should be decoupled from path ID

[[lithium]]
=== Lithium

* Finish the RPC interface (SfcProviderRPC)
** Today it is limited in scope and which elements it exercises
* SFF load-balancer functionality
** link:SFF_Load_Balance_Feature_Proposal[SFF Load Balance Feature
Proposal]
* Creat tests in sfc_dcloud_regression.py that exercise NSH Metadata,
ACLs, Classifiers. Today there is no coverage. (Reinaldo)
* _(Done)_ SouthBound REST Listener (Konstantin)
* Classifier Control and Data Plane Implementation (Reinaldo, Andrej,
Paul)
** https://datatracker.ietf.org/doc/draft-ietf-sfc-architecture/
* Harden the code
* SFC Sonar :
https://sonar.opendaylight.org/dashboard/index/org.opendaylight.sfc:sfc-parent
** (Brady) I would like to try to reduce the issues to ZERO, then cause
Jenkins to fail if new issues are introduced.
*** As of Dec 18: 258 Major, 232 Minor Issues
* GBP+SFC Integration Proof Of Concept
**
https://wiki.opendaylight.org/view/Service_Function_Chaining:Group_Based_Policy_Integration[Functional
Specification]
**
https://docs.google.com/document/d/1ZnLHuSiyOmVFR0pW65K4enB7QcYbLL18yzxYgmK_iDo/edit[Brainstorming,
Phased approach]
* The class org.opendaylight.controller.sal.common.util.Rpcs has been
depracated (March 9) and needs to be refactored

[[future-releases]]
=== Future Releases

* Integration with Netconf
* Move all listeners to a separate package
* Change the Yang models to use leafrefs, identity refs and others when
we are confident it will not cause Data Deserialization errors.
** done for Service Types
* Test and produce a reference Open switch topology and configuration
** Need more context on this one
* (done) Python Agent (sff_rest.py) need to process SB REST messages for
CRUD of SFs. It needs to creates and kill SFs much like it does for SFFs
today.
* Service Function Type should be moved from configuration to
operational data store. Code needs to check accordingly
* Junit tests need to cover Rendered Service Paths, NSH Metadata, ACLs,
Classifiers.
* Junit, Python stress tests.
* What to do with LISP plug-in?
** Is anybody using it?
** Future unknown…
* OF SFC Plug-in uses its own API instead of provider API

[[building-sfc]]
== Building SFC

This is the recommended way to use SFC.

1.  Clone the git repository: link:GIT_Cheat_Sheet[(ODL GIT Cheat
Sheet)]

-------------------------------------------------------------
git clone https://git.opendaylight.org/gerrit/p/sfc.git
  -- OR --
git clone ssh://<username>@git.opendaylight.org:29418/sfc.git
-------------------------------------------------------------

1.  setup your local settings.xml file

--------------------------------------------------------------------------------------------------------------
cp -n ~/.m2/settings.xml{,.orig}

If the command above fails it is okay. It means you do not have a settings.xml, probably it is 
the first time you are trying to use ODL.

wget -q -O - https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml > ~/.m2/settings.xml
--------------------------------------------------------------------------------------------------------------

1.  export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
2.  mvn clean install –DskipTests
3.  Run SFC: ./sfc-karaf/target/assembly/bin/karaf

At this point you can try the RESTConf API
(http://localhost:8181/apidoc/explorer/index.html) explorer or UI
(http://localhost:8181/sfc/index.html)

These are the reasons I do _not_ suggest you install and test SFC with
Helium regular distribution:

* If you download the regular Helium release you will not get the latest
bug fixes
* If you download the regular Helium release you will need to install
features, and debug other start-up issues. This is generic problem with
ODL karaf that it is not worth discussing here.
* You will not get the SFC-UI ready to go. I strongly recommend trying
the SFC-UI.
* You will not get bootstrap configuration files functionality from the
start.

[[downloading-building-and-viewing-the-sfc-user-guides]]
=== Downloading, Building, and Viewing the SFC User Guides

The following steps explain how to download, build, and view the ODL
User and Development Guides.

* Download the ODL documentation git repo
** git clone https://git.opendaylight.org/gerrit/p/docs.git

* Build the repo
** Change into the docs directory and build it as follows
** mvn clean install

* Viewing the documentation
** Open the browser of your choice and navigate to one of the following
URLs:
*** User Guide:
file:////docs/manuals/user-guide/target/docbkx/webhelp/bk-user-guide/content/_getting_started_with_opendaylight.html
*** Development Guide:
file:////docs/manuals/developer-guide/target/docbkx/webhelp/bk-developers-guide/content/_overview.html

[[shielding-yourself-from-controller-build-breaks]]
=== Shielding yourself from Controller build breaks

Controller build and functionality breaks are unpredictable and happen
all the time. If you have a working personal clone/sandbox I suggest you
to use offline builds so that new artifacts are not downloaded, unless
you actually have a reason to need the new artifacts.

I consulted Thanh and he gave this suggestion:

-----------------------------------------------------------------------------------------------------
A good way to do this is by using what's called an offline build with Maven by passing the 
parameter (-o). For example:

    mvn clean install -o

With  this method Maven will not even attempt to check online for new artifacts. However for this to 
work you must already have all the artifacts you need to build available in your Maven Local repo. A 
good way to prime your repo for offline builds is to use the dependency plugin's "go-offline" goal. 
For example:

    mvn dependency:go-offline

Or you you can just run a regular build successfully once and use offline mode after that.
-----------------------------------------------------------------------------------------------------

[[sfc-101]]
== SFC 101

https://docs.google.com/document/d/1w_bbDT7YXW9aOJ8OKfB-yTSZ5_ArEPx6t7BRdjzqesQ/edit?usp=sharing[SFC
101]

[[sfc-configuration-files]]
=== SFC Configuration Files

You can use the SFC start-up configuration file feature. SFC allows you
to create your own start-up configuration files that are loaded when SFC
is started. Therefore testing and recovery is very easy. The bootstrap
configuration files are found in the directory below. Feel free to
modify them for your deployment.

repenno$ ls sfc-jsonconfig/src/main/resources/bootstrap/

` service-function-chains.json`

` service-functions.json`

` service-function-forwarders.json`

` service-nodes.json`

[[sfc-ui]]
=== SFC UI

After running SFC distribution you can access the SFC-UI at
http://localhost:8181/sfc/index.html

[[meetings]]
== Meetings

2015-05-28, General Status

*
https://lists.opendaylight.org/pipermail/sfc-dev/2015-May/001245.html[2015-05-28] +

2015-05-14, M5 details

*
https://lists.opendaylight.org/pipermail/sfc-dev/2015-May/001223.html[2015-05-14] +

2015-05-07, General status

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-05-07-16.01.html[2015-05-07] +

2015-04-09, General status, M4 preparation

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-04-09-16.00.html[2015-04-09
IRC] +

2015-04-01 Meeting Cancelled +
2015-03-26, General status

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-03-26-16.00.html[2015-03-26
IRC] +

2015-03-19, General status, and M3 complete

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-03-19-16.03.html[2015-03-19
IRC] +
*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=15068491&meetingInstanceID=I2A1DIYSCQFUU2TI9HF9CBF7V6-9VIB[2015-03-19
WebEx recording] +

2015-03-12, Discussions about exceptions in Unit Tests, then Chris Price
talked about integrating SFC into OPNFV

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-03-12-16.00.html[2015-03-12
IRC] +

2015-03-05, General status, then discussions about integrating Load
Balancing

*
http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-03-05-17.01.html[2015-03-05
IRC] +

http://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-02-19-17.00.html[2015-02-19,
IRC] +
2015-02-12, Continued GBP+SFC integration discussions

*
https://meetings.webex.com/collabs/url/8Rbm2LrCyU5pzLsmhOoDj0yJZPpI0jb53VzcEpoFeVG00000[2015-02-12,
Webex recording]
*
https://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-02-12-17.00.html[2015-02-12,
IRC]

2015-02-05, Reinaldo SFC demo

*
https://meetings.webex.com/collabs/meetings/playRecording?recordID=14433636&meetingInstanceID=I3RF8SUSATNXF89CT7CW0PWB30-9VIB[2015-02-05,
Reinaldo SFC demo, webex recording] +
*
https://meetings.webex.com/collabs/url/VvVrUGAbeDLYPAxlPgmw5TlduQHGLb1gjk5_E1rxDum00000[2015-02-05,
Reinaldo SFC demo, webex recording, alternate URL for non-US accounts] +
*
https://meetings.opendaylight.org/opendaylight-sfc/2015/sfc_weekly/opendaylight-sfc-sfc_weekly.2015-02-05-17.00.html[2015-02-05,
IRC minutes]

https://lists.opendaylight.org/pipermail/sfc-dev/2015-January/000812.html[2015-01-29] +
https://lists.opendaylight.org/pipermail/sfc-dev/2015-January/000776.html[2015-01-22] +
https://lists.opendaylight.org/pipermail/sfc-dev/2015-January/000702.html[2015-01-15] +
https://lists.opendaylight.org/pipermail/sfc-dev/2015-January/000660.html[2015-01-08] +
2015-01-01 No meeting, Happy New Year +
2014-12-25 No meeting, Merry Christmas +
https://lists.opendaylight.org/pipermail/sfc-dev/2014-December/000636.html[2014-12-18] +
https://lists.opendaylight.org/pipermail/sfc-dev/2014-December/000612.html[2014-12-11] +
https://drive.google.com/file/d/0BzS_qWNqsnQbd2dzclRyaXlSOXM/view?usp=sharing[2014-12-04] +

