<< PacketCablePCMM:Main[ Main]

<< PacketCablePCMM:Release_Plan_Helium[ Release Plan]

<< PacketCablePCMM:ReleaseNotes[ Release Notes]

<< PacketCablePCMM:Documentation[ Documentation]

[[packetcable-pcmm-release-review]]
== PacketCable PCMM Release Review

[[features]]
== Features

Enable flow-based dynamic QoS for the DOCSIS infrastructure

[[non-code-aspects]]
== Non-Code Aspects

Asciidocs drafts of the User Guide and Developer Guide have been
submitted

https://git.opendaylight.org/gerrit/#/c/11354/

* User Guide
* PacketCablePCMM:Documentation[ Developer Guide ]
* PacketCablePCMM:ReleaseNotes[ Release Notes ]

The submitted asciidocs are a cleaned derivative of this wiki
PacketCablePCMM:Documentation[ documentation]

Awaiting feedback from docs team with merge instructions, format
suggestions, and location of release notes template.

[[architectural-issues]]
== Architectural Issues

While Helium focused exclusively on an MD-SAL augmentation of flow and
nodes, we have users still using the AD-SAL based prototype. Abandon or
embrace?

[[security-considerations]]
== Security Considerations

In addition to RESTCONF basic authentication this project could better
align with the Group Policy initiative to address some of the security
concerns i.e. who is allowed to create and delete flows on what devices.

[[quality-assurance]]
== Quality Assurance

We do not have the adequate test coverage to warrant pulling the project
out of yellow. We continue to test and fix towards the next release
target. The foundation for tests developed for this project are derived
from what has already been done for the Openflow plugin and adapted for
PacketCable. This should eventually and seamlessly fold into the
integration team's test harness.

[[end-of-life]]
== End-of-life

There are no EOL APIs nor features in this release.

[[bugzilla]]
== Bugzilla

[https://bugs.opendaylight.org/buglist.cgi?bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial&bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=IN_PROGRESS&bug_status=WAITING_FOR_REVIEW&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_target_milestone&f1=cf_target_milestone&list_id=15952&n1=1&o1=substring&product=packetcable&query_based_on=&query_format=advanced&resolution=---&v1=Lithium
All packetcable Helium Bugs]

[[standards]]
== Standards

http://www.cablelabs.com/wp-content/uploads/specdocs/PKT-SP-MM-I05-091029.pdf[PacketCable™
Specification Multimedia Specification PKT-SP-MM-I05-091029]

http://tools.ietf.org/html/rfc2748[The COPS (Common Open Policy Service)
Protocol]

[[schedule]]
== Schedule

The project lost committed resources shortly after project creation. The
scope of cross project requirements were not clear at the beginning of
the feature development process and at M4 we began slipping. The project
now has settled in, recovered, and return to testing the integrated
functionality.
