__NOTOC__

[[documentation]]
== Documentation

[[whitepapers]]
== Whitepapers

Group_Policy_beta:Main:Model:Theory[Whitepapers/Theory]

[[historyevolution]]
== History/Evolution

Policy is a passion of https://www.linkedin.com/in/dvorkin[Mike
Dvorkin].

Mike has been implementing policy for over 2 decades. Some examples:

* product (company)
* product (company)
* Cisco UCSM (Cisco)
* Cisco APIC (Cisco)
* Group Based Policy (OpenDaylight, OpenStack, OpenVSwitch).

Group Based Policy is the most recent iteration of this vision.

[[model]]
=== Model

The original version of the model submitted to the community as the
basis for Group Based Policy was presented on March 6, 2014.

After creation, the GBP project organized into "sub-projects" focusing
on:

* Architecture (lead: Mickey Spiegel - IBM)
* Use-Cases (lead: Dave Lenrow - HP)
* Model (lead: Mike Dvorkin - Noiro)
* General Status (lead: Keith Burns - Noiro)

The project held community facing meetings at least *3 times a week
starting in April 2014*.

Helium API Freeze was August 4, 2014, which was the effective lock-down
date for the model for Helium.

In that period, at least 36 separate community facing meetings were held
where the model was discussed. (Sub-groups:
Group_Policy:Sub-Groups:ARCH#Information_From_Past_Meetings[Architecture],
Group_Policy:Sub-Groups:REQUIREMENTS#Information_From_Past_Meetings[Requirements],
Group_Policy:Sub-Groups:STATUS#Information_From_Past_Meetings[Status])

Folks who attended a majority of these meetings were:

* Noiro: Mike Dvorkin, Keith Burns, Thomas Bachman, Rob Adams.
* HP: Dave Lenrow, Uyen Chau, Rex Pugh
* Midokura: Dan Conde, Steven Wong
* OneConvergance: Prasad Vellanki, Hemanth Ravi
* IBM: Mickey Spiegel, Ryan Moats
* Cisco: Sanjay Agrawal, Rhagurama Bhat
* Ericsson: Chris Price

Folks who attended meetings regularly but not as consistently as the
above:

* Cisco: Paul Quinn/Reinaldo Penno (SFC)
* Ericsson: Joel Halpern
* Plexxi: Derrick Winkworth

Over this period, the community evolved the model 14 times until the
Group_Policy:link_to_model[model implemented in Helium].

The model is continually being assessed for ways it can be modified to
simplify use and expand applicable use-cases.

Please see the status of current
Group_Policy:proposed_model_changes[proposed model changes].
