[cols="^",]
|=======================================================================
|*Related Pages*

a|
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi[Introduction] +
* OpenDaylight Virtual Tenant Network (VTN):Main[VTN Main] +
* OpenDaylight Virtual Tenant Network (VTN):VTN Manager[VTN Manager
Main] +
* OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator[VTN
Coordinator Main] +
*
OpenDaylight Virtual Tenant Network (VTN):Installation:VTN Coordinator[VTN
Coordinator Installation Guide] +
*
OpenDaylight Virtual Tenant Network (VTN):Installation:Virtualization Edition[Virtualization
Edition Guide] +

|=======================================================================

[[vtn-coordinator-rest-api-contents]]
= VTN Coordinator REST API Contents

Note:

::
  In Hydrogen Release, VTN Coordinator runs on TCP port *8080* by
  default.
  +
  In post Hydrogen Release, VTN Coordinator runs on TCP port *8083* by
  default.

*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:API Version Function[API
Version function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: Coordinator Version Functions[Coordinator
Version Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Flow List Functions[Flow
List functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:Flow List Entry Functions[Flow
List Entry functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:VTN Station Functions[VTN
Station functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: VTN Functions[VTN
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:VTN Mapping Functions[VTN
Mapping Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Controller Data Flow function[Controller
Data Flow Function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Data Flow function[Data
Flow Function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:VTN Data Flows Functions[VTN
Data Flows Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:VTN Flow Filter Functions[VTN
Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:VTN Flow Filter Entry functions[VTN
Flow Filter Entry functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Functions[vBridge
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Host Address Functions[Host
Address functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:L2 Domain Function[L2
Domain function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:MAC Entry Function[MAC
Entry function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: VLAN Map Functions[VLAN
Map Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Flow Filter Functions[vBridge
Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Flow Filter Entry Functions[vBridge
Flow Filter Entry functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Interface Functions[vBridge
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: vBridge Interface Port Map Functions[vBridge
Interface Port Map functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Interface Flow Filter Functions[vBridge
Interface Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBridge Interface Flow Filter Entry Functions[vBridge
Interface Flow Filter Entry Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vTerminal Functions[vTerminal
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vTerminal Interface Functions[
vTerminal Interface Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vTerminal Interface Port Map Functions[vTerminal
Interface Port Map Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vTerminal Interface Flow Filter Functions[vTerminal
Interface Flow Filter Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vTerminal Interface Flow Filter Entry Functions[vTerminal
Interface Flow Filter Entry Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vRouter functions[vRouter
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:Static IP Route Functions[Static
IP Route functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:IP Routes Function[IP
Routes function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:ARP Entry Functions[ARP
Entry functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:DHCP Relay Status Functions[DHCP
Relay Status functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:DHCP Relay Interface Functions[DHCP
Relay Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:DHCP Relay Server Functions[DHCP
Relay Server functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vRouter Interface Functions[vRouter
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vRouter Interface Flow Filter functions[vRouter
Interface Flow Filter functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vRouter Interface Flow Filter Entry functions[vRouter
Interface Flow Filter Entry functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBypass Functions[vBypass
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:vBypass Interface Functions[vBypass
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTep Functions[vTep
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTep Interface Functions[vTep
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTep Interface Port Map Functions[vTep
Interface Port Map functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTep Group Functions[vTep
Group functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTunnel Functions[vTunnel
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTunnel Interface Functions[vTunnel
Interface functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vTunnel Interface Port Map functions[vTunnel
Interface Port Map functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:vLink Functions[vLink
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: Physical Controller Functions[Controller
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Switch Functions[Switch
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Port Functions[Physical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:Physical Link Function[Physical
Link function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Domain Functions[Domain
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Logical Port Function[Logical
Port function] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Physical Boundary Functions[Boundary
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTNCoordinator:RestApi:Alarm Functions[Alarm
Functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Configuration Functions[Configuration
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: Session Functions[Session
functions] +
*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi: User Function[User
function] +

[[flow-filter-function]]
= Flow-filter Function

*
OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:Flow filter Function[Flow
filter function] +

Category:OpenDaylight Virtual Tenant Network[Category:OpenDaylight
Virtual Tenant Network]
