[[supported-platforms]]
= Supported Platforms

This page will explain the supported platforms and packages for building
and executing VTN Coordinator. VTN Coordinator is only supported in 64
bit machines.

[[virtualization-edition-supported-platforms]]
== Virtualization Edition Supported Platforms

Virtualization Edition is supported in the following platforms:

* RHEL 6.1 and RHEL 6.4
* CentOS 6.1 /6.4

[cols=",,",]
|=======================================================================
|*Supported Platform* |*Java Version* |*Packages for Installation*

|RHEL 6.1 (64-Bit)/Centos 6.1 (64-Bit)
|`  Download Oracle JDK 7 from the following page, and install it. ` +
`  `http://www.oracle.com/technetwork/java/javase/downloads/index.html[`http://www.oracle.com/technetwork/java/javase/downloads/index.html`]` ` +
`  Set JAVA_HOME to the location of the JDK. ` +
`  e.g.) export JAVA_HOME=/usr/java/default` a|
|

* yum install make glibc-devel gcc gcc-c++ boost-devel openssl-devel \

`    ant perl-ExtUtils-MakeMaker unixODBC-devel perl-Digest-SHA uuid libxslt libcurl libcurl-devel git`

* Install gtest-devel, json-c libraries

`wget `http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm[`http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm`] +
` rpm -Uvh epel-release-6-8.noarch.rpm` +
` yum install gtest-devel json-c json-c-devel`

|RHEL 6.4 (64-Bit)/Centos 6.4 (64-Bit) |` Install OpenJDK 7. ` +
`yum install java-1.7.0-openjdk-devel ` +
`Set JAVA_HOME to the location of the JDK. ` +
`e.g.) export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk.x86_64 ` a|
|

* yum install make glibc-devel gcc gcc-c++ boost-devel openssl-devel \

`    ant perl-ExtUtils-MakeMaker unixODBC-devel perl-Digest-SHA uuid libxslt libcurl libcurl-devel git`

* Install gtest-devel, json-c libraries

`wget `http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm[`http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm`] +
` rpm -Uvh epel-release-6-8.noarch.rpm` +
` yum install gtest-devel json-c json-c-devel`

|=======================================================================

[[source-supported-platforms]]
== Source Supported Platforms

VTN Coordinator source is supported in following platforms:

* RHEL 6.1/6.4
* CentOS 6.1/6.4
* Fedora (17/19/20)
* Ubuntu (12.04/12.10/13.04)
* Ubuntu 14.04
** Note:Please refer the changes to be done for Postgres 9.3 in
https://wiki.opendaylight.org/view/OpenDaylight_Virtual_Tenant_Network_(VTN):Installation:Troubleshooting[VTN
Troubleshooting page]

[[supported-platforms-1]]
== Supported Platforms

[cols=",,",]
|=======================================================================
|*Supported Platform* |*Necessary packages* |"Preparation for Execution"

|Fedora a|
* yum install make glibc-devel gcc gcc-c++ boost-devel openssl-devel \

`    ant perl-ExtUtils-MakeMaker unixODBC-devel perl-Digest-SHA uuid libxslt libcurl libcurl-devel git`

* Install gtest-devel, json-c libraries

` wget `http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm[`http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm`] +
` rpm -Uvh epel-release-6-8.noarch.rpm` +
` yum install gtest-devel json-c json-c-devel`

 || Download the following PostgreSQL 9.1 files (latest versions) from
http://yum.postgresql.org/9.1/redhat/rhel-6.4-x86_64/ (RHEL 6.4) or
http://yum.postgresql.org/9.1/redhat/rhel-6.1-x86_64/ (RHEL 6.1)and
install. postgresql91-libs postgresql91 postgresql91server
postgresql91-contrib postgresql91-odbc

|Ubuntu (13.10) a|
* apt-get install pkg-config gcc make ant g++ maven git libboost-dev
libcurl4-openssl-dev \

`  libjson0-dev libssl-dev openjdk-7-jdk unixodbc-dev xmlstarlet`

* Install gtest-devel, json-c libraries

` apt-get install cmake libgtest-dev` +
` cp -R /usr/src/gtest gtest-work` +
` cd gtest-work` +
` cmake CMakeLists.txt` +
` make` +
` sudo cp *.a /usr/lib` +
` cd ..` +
` rm -rf gtest-work `

 || apt-get install postgresql-9.1 postgresql-client-9.1
postgresql-client-common postgresql-contrib-9.1 odbc-postgresql

|Ubuntu(12.04) a|
* apt-get install pkg-config gcc make ant g++ maven git libboost-dev
libcurl4-openssl-dev \

`  libssl-dev openjdk-7-jdk unixodbc-dev`

* Install gtest-devel, json-c libraries

` apt-get install cmake libgtest-dev` +
` cp -R /usr/src/gtest gtest-work` +
` cd gtest-work` +
` cmake CMakeLists.txt` +
` make` +
` sudo cp *.a /usr/lib` +
` cd ..` +
` rm -rf gtest-work`

 || apt-get install postgresql-9.1 postgresql-client-9.1
postgresql-client-common postgresql-contrib-9.1 odbc-postgresql
|=======================================================================

