[[intro]]
== Intro

THIS PAGE HAS NO FORMAL STANDING!

It is just a landing spot for folks to put their Helium Release Vehicle
proposals as subpages. The *actual* Release Vehicles will be decided by
the TSC, but the community needs to give them a helping hand by
collecting proposals.

[[suggested-ground-rules]]
== Suggested Ground Rules

It is very helpful when putting together a Release Vehicle Proposal that
we consider how to get all
Simultaneous_Release:Helium_Release_Plan#Participating_Projects[Helium
Participating Projects] into at least one Release Vehicle that they feel
happy about being in. If you can't do this, your input is still helpful,
but please mark your proposed Release Vehicle Plan as (INCOMPLETE) so we
know its not a complete plan, and maybe we can take ideas from some of
the INCOMPLETE plans to get a complete one :)

(feel free to suggest other helpful suggested ground rules here).

[[proposed-helium-release-vehicle-plans]]
== Proposed Helium Release Vehicle Plans

* CrossProject:Helium Release Vehicle Brainstorming:Pure Karaf[ Pure
Karaf]
* Simultaneous_Release:Helium_Release_Plan#Proposed_Release_Vehicles[
Initial "stake in the ground" proposals]

