__TOC__

[[introduction]]
== Introduction

We have a variety of blocking and tackling work that needs to be done to
get the Hydrogen Release out the door.

That work is being tracked in a google doc spreadsheet
https://docs.google.com/spreadsheet/ccc?key=0AoSzir1BfjyWdDQyVElWNG9mcWxhblREckZjbjFxUVE#gid=1[here].

Please consult (and update) the spreadsheet for Activity tracking.

[[recommendations-and-templates]]
== Recommendations and Templates

* Draft_Syslog_Level_Settings +
*
Simultaneous_Release:Simultaneous_Release_Plan_2014:ReleaseRecommendations[Release_Readiness_Branching_Recommendations]
* Simultaneous_Release:Simultaneous_Release_Plan_2013/plaform_matrix[
Qualification testing matrix]
*
Simultaneous_Release:Simultaneous_Release_Plan_2014:DependencyConvergence[
Per-Project Dependency Convergence ToDo]
**
https://docs.google.com/spreadsheet/ccc?key=0Anypq0z_rOtOdE1YOUFSejQ0TGk0TkFhbVdEZ0d0VHc#gid=0[Spreadsheet
for tracing dependency version convergence]
* link:Sample_User_Guide[ User Guide Template (Draft)]
* link:Sample_Developer_Guide[ Developer Guide Template (Draft)]
* link:Sample_Release_Notes[ Release Notes Template (Draft)]
* link:Sample Release Review[Release Review Document]
* link:General_Style_Guidelines[ General Style Guidelines (Draft)]
*
Simultaneous_Release:Simultaneous_Release_Plan_2014:DownloadableReleaseArtifacts[Downloadable
Release Artifacts]

[[daily-cadence-meeting]]
== Daily Cadence Meeting

Daily Cadence meetings are happening on the #opendaylight-meeting
channel on FreeNode IRC at:

9:00am PST and 5:45pm PST

You are only expected to attend one of them, not necessarily both. We
have two to accommodate global timezones.

[[minutes]]
=== Minutes

* *1/17/2014 9:00am PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-17.00.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-17.00.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-17.00.log.html[full
logs]
* *1/16/2014 5:45p PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-01.45.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-01.45.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-17-01.45.log.html[full
logs]
* *1/16/2014 9:00a PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-17.00.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-17.00.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-17.00.log.html[full
logs]
* *1/15/2014 5:45p PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-01.46.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-01.46.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-16-01.46.log.html[full
logs]
* *1/15/2014 9:00a PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-17.00.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-17.00.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-17.00.log.html[full
logs]
* *1/14/2014 5:45a PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-01.45.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-01.45.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-15-01.45.log.html[full
logs]
* *1/14/2014 9:00a PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-17.01.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-17.01.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-17.01.log.html[full
logs]
* *1/13/2014 5:45p PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-01.56.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-01.56.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-14-01.56.log.html[full
logs]
* *1/13/2014 9:45a PST:*
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-13-17.46.html[summary
(html)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-13-17.46.txt[summary
(txt)],
http://meetings.opendaylight.org/opendaylight-meeting/2014/opendaylight-meeting.2014-01-13-17.46.log.html[full
logs]

