[cols="^",]
|======================================================================
|'''AAA Facts '''
a|
*Project Creation Date:* May 15th, 2014 *Lifecycle State:* Incubation +
*Primary Contact:* Liem Nguyen  +
*Project Lead:* N/A +
*Committers:* +
* Liem Nguyen

* Peter Mellquist
* Wojciech Dec
* Lakshman Mukkamalla
* Arash Eghtesadi
* John Dennis  +

*IRC:* freenode.net #opendaylight-aaa (no meetbot yet!) +
*Dev Mailing List*: aaa-dev@lists.opendaylight.org +
*Mailing List Topic:* aaa (link:Communication[Instructions]) +

|======================================================================

Welcome to the AAA project page!

[[introduction]]
= Introduction

* Project_Proposals:AAA Service[Project Proposal]
*
https://drive.google.com/file/d/0B1KtwIIbDsZXSDdpZjFQWDJUWXc/edit?usp=sharing[AAA
Overview]
*
https://drive.google.com/file/d/0B2IWJPwtf67LeDd5a0JrZkpNaHc/edit?usp=sharing[AAA
Design Blueprint]

[[helium]]
= Helium

* AAA:Helium[Project Release Plan]
* https://trello.com/b/ehBCSGY3/opendaylight-aaa[Project Tracking]

* AAA:Hacking[Hacking]
* AAA:Design[Design]

[[meetings-open-to-all]]
= Meetings (open to all)

See WebEx details for weekly meetings... For impromptu meetings, use
https://plus.google.com/hangouts/_/event/cqpjp7haq1vps00g6sco21ac4a8[Google
Hangout meeting].

Please contact hosts in case of any issues.

* Time: Thursdays 9am-10am PST (starting May 22, 2014)

* Topic: ODL - Weekly AAA Project meeting
* Date: Every Thursday, from Thursday, June 5, 2014 to no end date
* Meeting Number: 201 443 156
* Meeting Password: 111111
* Host(s): Wojciech Dec (wdec@cisco.com), Liem Nguyen
(liem_m_nguyen@hp.com).

------------------------------------------------------- To start the
online meeting -------------------------------------------------------

1.  1. Go to
https://cisco.webex.com/ciscosales/j.php?MTID=m0238db0ef3f1365344c735af15ecdbbb
2.  2. Log in to your account.
3.  3. Click "Start Now".
4.  4. Follow the instructions that appear on your screen.

---------------------------------------------------------------- ALERT –
PLEASE READ: DO NOT DIAL THE TOLL FREE NUMBERS FROM WITHIN THE (408) OR
(919) AREA CODES
---------------------------------------------------------------- Please
dial the local access number for your area from the list below: - San
Jose/Milpitas (408) area: 525-6800 - RTP (919) area: 392-3330

Dialing the WebEx toll free numbers from within 408 or 919 area codes is
not enabled. “ If you dial the toll-free numbers within the 408 or 919
area codes you will be instructed to hang up and dial the local access
number.” Please use the call-back option whenever possible and otherwise
dial local numbers only. The affected toll free numbers are: (866)
432-9903 for the San Jose/Milpitas area and (866) 349-3520 for the RTP
area.

------------------------------------------------------- To join the
teleconference only
------------------------------------------------------- 1. Dial into
Cisco WebEx (view all Global Access Numbers at
http://cisco.com/en/US/about/doing_business/conferencing/index.html 2.
Follow the prompts to enter the Meeting Number (listed above) or Access
Code followed by the # sign.

San Jose, CA: +1.408.525.6800 RTP: +1.919.392.3330

US/Canada: +1.866.432.9903 United Kingdom: +44.20.8824.0117

India: +91.80.4350.1111 Germany: +49.619.6773.9002

Japan: +81.3.5763.9394 China: +86.10.8515.5666

[[meeting-minutes]]
= Meeting Minutes

[[section]]
== 7/29/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=0516bb0d3f3949589be23a136fb1b236

[[section-1]]
== 7/24/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=fa918fd61acd4a97ab51abfcfd25d2eb

[[section-2]]
== 7/10/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=50fefbf3a2dc4a98aa12eea4398487a3

[[section-3]]
== 7/3/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=afe8f9c6236b403a84af1b143442d358

[[section-4]]
== 6/17/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=a5e97b036ac54fa5a13500b8f7d882bf

[[section-5]]
== 6/12/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=ff7f52696326442c9ab56ee0e49a287a

[[section-6]]
== 6/10/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=671b47fae6b04057ad47d899a64e181e

[[section-7]]
== 6/5/2014

Recording:
https://cisco.webex.com/ciscosales/lsr.php?RCID=2b78ee05190b4864b4e165c4d74a89cf
