Welcome to the AAA project page!

[[introduction]]
= Introduction

* Project_Proposals:AAA Service[Project Proposal]
*
https://drive.google.com/file/d/0B1KtwIIbDsZXSDdpZjFQWDJUWXc/edit?usp=sharing[AAA
Overview]
*
https://drive.google.com/file/d/0B2IWJPwtf67LeDd5a0JrZkpNaHc/edit?usp=sharing[AAA
Design Blueprint]

[[helium]]
= Helium

* AAA:Helium[Project Release Plan]
* https://trello.com/b/ehBCSGY3/opendaylight-aaa[Project Tracking]

* AAA:Hacking[Hacking]
* AAA:Design[Design]
*
https://drive.google.com/file/d/0B1KtwIIbDsZXY3dRUVVqMG9KNDg/view?usp=sharing[Test
Plan (WIP)]
*
https://drive.google.com/file/d/0B1KtwIIbDsZXbHp0NkQ1LVhxVHc/edit?usp=sharing[Design
Summit 2014 Slides]

[[lithium-wip]]
= Lithium (WIP)

* AAA:Lithium[Project Release Plan]
* https://trello.com/b/9gVlPYM9/opendaylight-aaa-lithium[Project
Tracking]
*
https://drive.google.com/open?id=0B1KtwIIbDsZXeTJjYm4zOFUzOHM&authuser=0[IdM
Entity model]
* https://wiki.opendaylight.org/images/0/00/AAA_Test_Plan.docx[AAA Test
plan doc]

[[meetings-open-to-all]]
= Meetings (open to all)

See WebEx details for weekly meetings... For impromptu meetings, use
https://plus.google.com/hangouts/_/event/cqpjp7haq1vps00g6sco21ac4a8[Google
Hangout meeting].

Trello is used to track deliverables: https://trello.com/b/9gVlPYM9

Please contact hosts in case of any issues.

* Time: Thursdays 9am-10am PST (starting May 22, 2014)
* Topic: ODL - Weekly AAA Project meeting
* Date: Every Thursday, from Thursday, June 5, 2014 to no end date
* Meeting Number: 305004126
* Meeting Password: 111111
* Host(s): Wojciech Dec (wdec@cisco.com), Liem Nguyen
(liem_m_nguyen@hp.com).

------------------------------------------------------- To start the
online meeting - VoIP ONLY!
-------------------------------------------------------

1.  1. Go to
https://cisco.webex.com/cisco/j.php?MTID=m8c9760bd2a68fa805ba2103821e5ee75
2.  2. Log in to your account.
3.  3. Click "Start Now".
4.  4. Follow the instructions that appear on your screen.

[[meeting-minutes]]
= Meeting Minutes

[[section]]
== 30/4/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=c85f2ac09b19467a8e294609c74ea880

[[section-1]]
== 23/4/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=87afa46d667d43389185a450b5f9fb45

[[section-2]]
== 2/4/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=8e24c9ad955d47d495fe8fcbe23bcb64

[[section-3]]
== 26/3/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=1c3e82e9fa4f43838fac03fd5913925f

[[section-4]]
== 19/2/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=3f62a6daf4174a3fa05f7a2c5d71c105

[[section-5]]
== 12/2/2015

https://cisco.webex.com/ciscosales/lsr.php?RCID=4fb2a4d099a24fb7bc3de0720cfcb812

[[section-6]]
== 8/21/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=b2585a8107c144b4940b6549dac81aee

[[section-7]]
== 8/04/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=706631bc5b44444cbf9f42c02561f29f

[[section-8]]
== 7/29/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=0516bb0d3f3949589be23a136fb1b236

[[section-9]]
== 7/24/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=fa918fd61acd4a97ab51abfcfd25d2eb

[[section-10]]
== 7/10/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=50fefbf3a2dc4a98aa12eea4398487a3

[[section-11]]
== 7/3/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=afe8f9c6236b403a84af1b143442d358

[[section-12]]
== 6/17/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=a5e97b036ac54fa5a13500b8f7d882bf

[[section-13]]
== 6/12/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=ff7f52696326442c9ab56ee0e49a287a

[[section-14]]
== 6/10/2014

https://cisco.webex.com/ciscosales/lsr.php?RCID=671b47fae6b04057ad47d899a64e181e

[[section-15]]
== 6/5/2014

Recording:
https://cisco.webex.com/ciscosales/lsr.php?RCID=2b78ee05190b4864b4e165c4d74a89cf

[[all-subpages]]
= All subpages
