[[getting-started-as-a-writer-for-opendaylight]]
== Getting started as a writer for OpenDaylight

Documentation for OpenDaylight requires a good grasp of technical
writing, and some acumen to understand the product or technology you are
writing about. This document explains how you can contribute to
documentation.

The document presents the following topics:

* Overview of OpenDaylight documentation
* Setting up your documentation tools
* Deciding if your project requires documentation
* Authoring your first document
* Documentation review process
* Publishing your documentation

[[overview-of-opendaylight-documentation]]
== Overview of Opendaylight documentation

Opendaylight documentation includes the following:

\1. Project Specific Documentation: This is technical content that the
project teams develop. It is preferable that project teams also own
documentation. Documentation can help edit content before publishing.
The project teams decide if the project requires documentation and
defines a documentation contact for a release during the M2 milestone.
The documentation contact is preferably, the person working on the
project, understand the feature and is responsible for completing the
documentation by the release.

\2. Project Agnostic Documentation: This is content that helps the wider
community and not specific to a particular project. Some examples are:

* Preferred way to install controller for security
* run karaf
* Security recommendations

[[setting-up-your-documentation-tools]]
== Setting up your documentation tools

The Opendaylight project uses the following tools:

* ASCIIDOC: This is the authoring tool. For more information, see the
relevant sections below.
* Gerrit: This is the content repository for all ASCIIDOC topics. The
repository address is
https://git.opendaylight.org/gerrit/p/docs.git[Gerrit Doc Repo].
* Git and Git Review: These are the change management tools used to
version the content stored in Gerrit.
* Maven: This is the tool for building the documentation and publishing
it as PDFs.

To set up the work environment for your OpenDaylight authoring, see
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:Tools[Setting
up OpenDaylight authoring tools].

[[authoring-your-first-document]]
== Authoring your first document

If you are a documentation contact for a project:

* Decide the documentation types required for your project. The
documentation types will include installation instructions, user guide,
deployment guide, how-to tutorials, and so on.
* Use the templates to update content. The templates are provided in
CrossProject:Documentation_Group:Docs_and_Structure#Recommended_Documentation_Structures[Recommended
Documentation Structures].
* Check-in files to appropriate docs repo.

[[documentation-review-process]]
== Documentation review process

[To be filled in]

[[publishing-your-documentation]]
== Publishing your documentation

[To be filled in]

[[importance-of-asciidoc-for-your-project]]
=== Importance of ASCIIDOC for your project

If you are a developer and want your information classified and
protected under different releases and version controlled, it is
imperative that you use ASCIIDOC to author your content and use Git and
Gerrit to maintain the content management system for OpenDaylight
documentation projects. A wiki, such as this one, does not have version
control capabilities and is vulnerable to frequent non-scrutinized
changes.

[[the-content-deliverables-for-an-opendaylight-project]]
== The content deliverables for an OpenDaylight project

If you are new to the concept of creating content, here is a sample
workflow to aid you to produce OpenDaylight documentation. See the
https://wiki.opendaylight.org/view/CrossProject:Documentation_Group:How_To[document
workflow chart].
