*Back to CrossProject:Documentation_Group[ main Documentation Group
page]*

'''Back to the CrossProject:Documentation Group:Helium Content[ Helium
Content page] for the complete list. '''

Please add a structure for Developer Guide chapters here.

[[contributing-to-the-opendaylight-project]]
== Contributing to the OpenDaylight Project

[[introducing-opendaylight]]
=== Introducing OpenDaylight

* Overview
* Audience
* OpenDaylight Architecture

[[opendaylight-module-descriptions-and-javadoc]]
=== OpenDaylight Module Descriptions and Javadoc

[[getting-started]]
=== Getting Started

* Initiating a project
* OpenDaylight Development Infrastructure
* Installing the tools required

[[development-process-lifecyle]]
=== Development Process Lifecyle

* Submitting a Patch
* Writing Test Cases
* Filing a Bug or a Feature Request

[[developers-guide-for]]
=== Developer’s Guide for

Feature here refers to a sub feature that contributes to the high level
feature. For example ODL Controller has features such as Openflow,
Virtual Tenant Network and so on.

* UseCase Overview
* Architecture
* Getting started

Define Archetypes

* Config Subsystem

Introduce Config Subsystem used in this Feature.

* Exploring the Code

`    This section should include information such as:` +
`    * Information about InstanceIdentifiers, Builders, Transactions, Generated code, NSFs and so on.` +
`    * How to look for an XBuilder, if you’re trying to get a type X?` +
`    * Notify users about multiple classes or interfaces with the same name.` +
`    * Information about interfaces that is used with multiple functionality.` +
`    * How to figure out the correct package to import once you find an interface?`

[[developers-guide-for-1]]
=== Developer’s Guide for

*
*

[[developers-guide-for-2]]
=== Developer’s Guide for

*
*

[[tutorials]]
=== Tutorials
