Please add a structure for Installation Guide chapters here.

[[feature-installation-guide]]
== *< Feature >* Installation Guide

This is a template for installing a feature or a project developed in
the ODL project. The *feature* could be interfaces, protocol plug-ins,
or applications.

[[title]]
=== Title

Add chapter title. For example Installing **

[[overview]]
=== Overview

Add overview of the product. Include Architecture diagram and the
positioning of this feature in overall controller architecture.
Highlighting the feature in a different color within the overall
architecture must help. Include information to describe if the project
is within ODL installation package or to be installed seperately.

[[pre-requisites-for-installing-or-downloading-the-controller-distribution]]
=== Pre Requisites for Installing or Downloading the Controller
Distribution

* Hardware Requirements
* Software Requirements
* Platform Requirements

[[preparing-for-installation]]
=== Preparing for Installation

Include any pre configuration, database, or other software downloads
required to install **.

[[installing-the]]
=== Installing the **

Include if you have separate procedures for Windows and Linux

[[verifying-your-installation]]
=== Verifying your Installation

[[post-installation-configuration]]
=== Post Installation Configuration

`Post Installation Configuration section must include some basic (must-do) procedures if any, to get started.`

Mandatory instructions to get started with the product.

* Logging in
* Getting Started
* Integration points with controller

[[upgrading-from-a-previous-release]]
=== Upgrading From a Previous Release

[[uninstalling-the]]
=== Uninstalling the **

[[troubleshooting-scenario]]
=== Troubleshooting Scenario

[[related-documentation]]
=== Related Documentation
