*Back to CrossProject:Documentation_Group[ main Documentation Group
page]*

[[opendaylight-doc-tools]]
= OpenDaylight Doc Tools

The following tools are used to author and manage OpenDaylight
documentation deliverables:

* _AsciiDoc_, which is a lightweight markup language that offers writers
a plain-text format to author the necessary documentation for their
project. It also provides a toolchain that translates AsciiDoc documents
into other formats such as HTML and PDF.
* _Git_, which is an open source distributed version control system that
OpenDaylight uses to manage its source code and documentation files.
* _Gerrit_, which is a web-based code review system that integrates
nicely with Git. It facilitates doc reviews by allowing reviewers to
compare two versions of a doc side by side and add inline comments.
* _git-review_, which is a command-line tool that makes it easier to
work with Git and Gerrit.
* _Maven_, which is used to create and manage OpenDaylight builds.

The following sections cover how to set up these tools and describe
common workflows you will employ while you author your project’s
documentation.

[[before-you-get-started]]
== Before You Get Started

We recommend you do the following before you install OpenDaylight’s doc
tools and begin authoring:

* Watch this http://youtu.be/EcGptvuKy0w[video], which summarizes the
doc tools setup process and provides an overview of the doc repository.
* Read the http://asciidoc.org/userguide.html[AsciiDoc User Guide] to
learn the basics of authoring in the AsciiDoc format. If time is of the
essence and you need to get started quickly, view the
http://powerman.name/doc/asciidoc[AsciiDoc Cheatsheet] instead.

Note that the following procedures were written with Mac OS X clients in
mind. Hopefully someone from the community can document Windows-specific
procedures.

[[installing-and-configuring-doc-tools]]
== Installing and Configuring Doc Tools

1.  Install Maven. +
You can download the latest version (currently 3.3.3) and view the
installation instructions https://maven.apache.org/download.cgi[here].
2.  Install Git: +
• To access the main Git download page, click
http://www.git-scm.com/downloads[here]. +
• To view Git installation instructions, click
http://www.git-scm.com/book/en/v2/Getting-Started-Installing-Git[here].
3.  Create a Gerrit user account by completing the procedure described
OpenDaylight_Controller:Gerrit_Setup#Setting_up_a_Gerrit_account[here].
4.  Set up the SSH key that will be used to secure your communications
with the doc repository:
1.  Generate an SSH key for your system by completing the procedure
described
OpenDaylight_Controller:Gerrit_Setup#Generating_SSH_keys_for_your_system[here].
2.  Register your SSH key with Gerrit by completing the procedure
described
OpenDaylight_Controller:Gerrit_Setup#Registering_your_SSH_key_with_Gerrit[here].
5.  Clone a copy of the OpenDaylight doc repository to your system: +
*git clone https://git.opendaylight.org/gerrit/docs*
6.  Set up git-review:
1.  Install git-review by completing the procedure specific to your
operating system. +
Instructions are available
http://www.mediawiki.org/wiki/Gerrit/git-review#Installation[here].
2.  Configure the commit message hook and default push location: +
*cd docs* +
*scp -p -P 29418 @git.opendaylight.org:hooks/commit-msg .git/hooks/* +
*chmod 755 .git/hooks/commit-msg* +
*git config remote.origin.push HEAD:refs/for/master*
3.  Finalize the git-review connection: +
*git review -s*
7.  Configure your name, email address, and default text editor: +
• *git config --global user.name "_firstname lastname_"* +
• *git config --global user.email "_email address_"* +
• *git config --global core.editor "_text editor name_"*

[[common-doc-tasks]]
== Common Doc Tasks

The following sections describe the most common tasks you will need to
complete while authoring your project’s documentation.

[[submitting-a-new-patch]]
=== Submitting a New Patch

1.  On your machine, open a shell and switch to the docs directory: +
*cd docs*
2.  To remove any dependencies on other files you are working on, check
out the master branch: +
*git checkout master*
3.  Get a copy of the latest master files from the server: +
*git pull*
4.  Create a new branch for your work: +
'''git checkout -b _*'' +
*Note:_' Spaces are not allowed in the branch name.
5.  Create new files or edit existing files, as needed.
6.  Commit the files you have worked on:
1.  To commit new files, run *git add __*
2.  To commit existing files you edited, run *git commit --as* +
Your default text editor opens. +
*Note:* The --as options instruct Git to commit all of the files you
have edited (a) and sign your commit request with your email address and
name (s).
3.  Add a brief description of the changes you have made to the
beginning of the commit request and then save the request.
7.  Submit your files for review: +
*git review* +
You will receive 2 emails from Gerrit Code Review: The first indicating
that a build to incorporate your changes has started; and the second
indicating whether the build was created successfully.
8.  Determine your patch’s change number:
1.  Open either of the emails you received after submitting your files
for review.
2.  Locate the following line: To view, visit __ +
The number at the end of this URL is your patch’s change number. You
will need this in order to make updates to the patch later.

[[updating-an-existing-patch]]
=== Updating an Existing Patch

1.  On your machine, open a shell and switch to the docs directory: *cd
docs*
2.  Download the patch you want to update: *git review -d __*
3.  (Optional) View information on the latest changes made to that
patch: +
To view the files that were edited, run *git show* +
To view a listing of the files that were edited and the number of lines
in those files that were edited, run *git show --stat*
4.  Make the necessary changes to the patch’s files.
5.  Commit your changes:
1.  To commit a patch you originally authored, run *git commit -a
–amend*
2.  To commit a patch authored by another writer (for example, after you
reviewed someone else’s files and provided feedback), run +
*git commit -as --amend --author="Firstname Lastname __"* +
Your default text editor opens.
3.  Update the current patch description and then save the commit
request. +
If you are updating another writer’s patch, be sure to give that writer
credit in the description so people will know who originally authored
the files in question.
6.  Submit your files for review: +
*git review*

You will receive 2 emails from Gerrit Code Review: the first indicating
that a build to incorporate your changes has started; and the second
indicating whether the build was created successfully.

[[generating-documentation]]
=== Generating Documentation

1.  Open a shell and switch to the main directory for the documentation
deliverable you want to generate. +
For example, if you want to generate a user guide, you would run the
following command: *cd docs/manuals/user-guide*
2.  Run the following command to generate the deliverable: *mvn
install* +
By default, 2 versions of your deliverable are generated: an HTML
version and a PDF version. You can access them from the following
folder: +
docs/manuals/deliverable-name/target/docbkx/webhelp/deliverable-filename/.

To view a page that describes common AsciiDoc errors and how to deal
with them, click
CrossProject:Documentation_Group:Tools:AsciiDoc_Tips[here].
