[[project-name]]
== Project Name

dlux

[[features]]
== Features

All features are mentioned under New Features heading of release notes
at OpenDaylight dlux:Release Notes Helium[dlux helium release notes]

[[non-code-aspects-user-docs-examples-tutorials-articles]]
== Non-Code Aspects (user docs, examples, tutorials, articles)

For setup, development and user guide. click at following link:
OpenDaylight dlux:Getting started[Getting started with dlux]

https://git.opendaylight.org/gerrit/#/c/11562/[Developer doc gerrit
commit]

User guide ascii document is in progress.

[[architectural-issues]]
== Architectural Issues

[[security-considerations]]
== Security Considerations

dlux use controller provided authentication. If restconf does not have
authentication enabled, user can access dlux ui without any checks.

[[quality-assurance-test-coverage-etc]]
== Quality Assurance (test coverage, etc)

Being pure javascript based application, dlux has javascript based test
cases, but they can't be included into maven and sonar.

[[end-of-life-apifeatures-eoled-in-release]]
== End-of-life (API/Features EOLed in Release)

[[bugzilla-summary-of-bug-situation]]
== Bugzilla (summary of bug situation)

No blocker is pending, All open defects are mentioned under open defects
heading at OpenDaylight dlux:Release Notes Helium[dlux Release Notes
Helium]

[[standards-summary-of-standard-compliance]]
== Standards (summary of standard compliance)

[[schedule-initial-schedule-and-changes-over-the-release-cycle]]
== Schedule (initial schedule and changes over the release cycle)
