This section describes how to setup the latest OpenDaylight Dlux UI
project and run it for development purpose. Dlux is also available as
Karaf feature. If you just want to play with Dlux UI, you can enable
Dlux feature in Karaf distribution. to do so, refer to page
OpenDaylight_dlux:Dlux_Karaf_Feature[ Enable Dlux Karaf Feature]. The
latest (current) version uses a JavaScript based Single-Page-Application
using AngularJS, running on NodeJS.

[[required-technology-stack]]
== Required Technology Stack

* NodeJS (Http Server, http://www.nodejs.org)
* Bower (JavaScript Package Manager, http://bower.io)
* GruntJS (JavaScript Task Runner, http://gruntjs.com)
* AngularJS (JavaScript client-side framework, http://www.angularjs.org)
* Karma (JavaScript Test Runner, http://karma-runner.github.io/)
* Other AngularJS/Third-party JS libraries

[[get-latest-dlux-code-from-git]]
== Get latest DLUX code from git

Anonymous clone:

----------------------------------------------------
$ git clone https://git.opendaylight.org/gerrit/dlux
----------------------------------------------------

If you have a opendaylight.org account:

----------------------------------------------------------------
$ git clone ssh://<username>@git.opendaylight.org:29418/dlux.git
----------------------------------------------------------------

If you want to create a new account with opendaylight.org, see
link:WSO2 Identity server[https://identity.opendaylight.org/carbon/admin/index.jsp?loginStatus=true]

[[build-dlux-code-with-karaf-feature-and-distribution]]
== Build DLUX code with Karaf feature and distribution

All necessary modules mentioned above such as nodesjs, bower etc. will
be installed automatically, when you run the dlux build for first time.
Run following command at dlux home directory /dlux to build dlux feature
and distribution along with code. Once successful, It will make dlux
feature available to install and also create dlux karaf distribution.
You can find karaf distribution at dlux/distribution-dlux.

--------------------
$  mvn clean install
--------------------

*NOTE*: Some people reported about node related error while maven build.
Those errors are usually environment related, mostly happens because of
the permission issues or node is not installed properly. Try to
reinstall node manually.

[[install-nodejs-manually-if-needed]]
== Install NodeJS manually if needed

*For Windows and Mac without brew:*

. Go to http://www.nodejs.org . Download and install NodeJS

*For Mac with brew installed:*

`$ brew update` +
`$ brew install node`

*Verify NodeJS is installed:*

----------------
 $ npm --version
----------------

[[install-nodejs-dependencies]]
== Install NodeJS dependencies

To build DLUX from git, also install these via npm:

----------------------------------------------------------------------------------------------------------------------------
npm install grunt esprima ng-annotate simple-fmt simple-is alter ordered-ast-traverse source-map stable stringmap stringset 
----------------------------------------------------------------------------------------------------------------------------

[[run-dlux-in-karaf-distribution]]
== Run DLUX in karaf distribution

Once you have dlux distribution or you have karaf distribution from
integration repository. You can turn on the dlux feature to access the
UI. We will take example of dlux distribution here. Navigate to
directory dlux/distribution-dlux/target/assembly/bin and start the karaf
via following command -

-------
./karaf
-------

On the karaf shell, install dlux core feature via running following
command -

-----------------------------
feature:install odl-dlux-core
-----------------------------

It will internally install odl-restconf and dlux topology application
along with core dlux components. once this feature is successfully
installed. Access the dlux UI at http://localhost:8181/index.html.
Default credentials are admin/admin for login.

All the applications in dlux are now karaf features. You can install
other dlux applications such as nodes, yang-ui from karaf console using
commands such as

-------------------------------
feature:install odl-dlux-node

feature:install odl-dlux-yangui
-------------------------------

[[run-the-dlux-code-in-developer-mode-against-the-controller]]
== Run the DLUX code in developer mode against the controller

*Note: Following way of development is not recommended for anyone who is
not familiar with dlux code.*

Start karaf distribution with installed md-sal features(Karaf starts at
port 8181). For more information on running the controller see
[[OpenDaylight Controller
Installation|https://wiki.opendaylight.org/view/OpenDaylight_Controller:Installation]

* Goto mininet VM and create a topology for the controller

Based on where you controller is running, Update baseUrl in file
dlux/dlux-web/config/development.json.

Uncomment following code in app.module.js located at
modules/loader-resources/src/main/resources/app

----------------------------------------------

/*
var module = [
  'angularAMD',
  'app/core/core.module',
  'angular-translate',
  'angular-translate-loader-static-files',
  'angular-ui-router',
  'ocLazyLoad',
  'angular-css-injector',
  'app/node/nodes.module',
  'app/topology/topology.module',
  'common/login/login.module',
  'app/yangui/yangui.module',
  'common/navigation/navigation.module',
  'common/topbar/topbar.module',
  'common/layout/layout.module',
  'common/config/env.module']; //needed module

// The name of all angularjs module
var e = [
  'ui.router',
  'oc.lazyLoad',
  'pascalprecht.translate',
  'angular.css.injector',
  'app.nodes',
  'app.topology',
  'app.common.login',
  'app.yangui',
  'app.common.nav',
  'app.common.topbar',
  'app.common.layout'];
//--------------------\\

*/
----------------------------------------------

Build your module/loader-resources by running mvn clean install.

Navigate to directory, dlux/dlux-web, type

------------
$ grunt live
------------

Open a browser and goto http://localhost:9000

This should bring up the DLUX UI and pull data from the controller. Use
admin/admin credentials to access the UI
