This section describes how to setup the latest OpenDaylight Dlux UI
project and run it.

*Note*

* The older version of dlux used Python/Django framework for UX.
* The latest (current) version uses a JavaScript based
Single-Page-Application using AngularJS, running on NodeJS.
* This document describes the latest setup. This may eventually replace
the documentation about Python-based UX.

[[required-technology-stack]]
== Required Technology Stack

* NodeJS (Http Server, http://www.nodejs.org)
* Bower (JavaScript Package Manager, http://bower.io)
* GruntJS (JavaScript Task Runner, http://gruntjs.com)
* AngularJS (JavaScript client-side framework, http://www.angularjs.org)
* Karma (JavaScript Test Runner, http://karma-runner.github.io/)
* Other AngularJS/Third-party JS libraries

[[install-nodejs]]
== Install NodeJS

For Mac, if you have *brew*:

-------------------
* brew update
* brew install node
-------------------

For Windows and Mac without brew:

* Goto http://www.nodejs.org
* Download and install the NodeJS

Verify nodeJS is installed

---------------
$ npm --version
---------------

[[install-required-node-libraries]]
== Install required Node libraries

Install the following node components using npm. For Mac, you may have
to use "sudo"

-------------------------------
$ sudo npm -g install grunt-cli
$ sudo npm -g install bower
$ sudo npm -g install karma
$ sudo npm -g install karma-cli
-------------------------------

[[get-latest-dlux-code-from-git]]
== Get latest DLUX code from git

Anonymous clone:

---------------------------------------------------------
$ git clone http://git.opendaylight.org/gerrit/p/dlux.git
---------------------------------------------------------

If you have a opendaylight.org account:

----------------------------------------------------------------
$ git clone ssh://<username>@git.opendaylight.org:29418/dlux.git
----------------------------------------------------------------

If you want to create a new account with opendaylight.org, see
link:WSO2 Identity server[https://identity.opendaylight.org/carbon/admin/index.jsp?loginStatus=true]

[[build-the-dlux-code]]
== Build the DLUX code

--------------------------------------------------------------------------------------------------------
$ cd dlux

#installs the necessary NodeJS related components for the project - will create a node_modules directory
$ sudo npm install  

#installs necessary components provided by power
$ bower install 

# run the unit tests and start karma test runner
# this will open up the default browser pointing to karma test running and run the unit tests
$ grunt watch
--------------------------------------------------------------------------------------------------------

Hit Ctrl-C to quit

[[run-the-dlux-code-against-the-controller]]
== Run the DLUX code against the controller

* Start the ODL Controller using run.sh (run.bat in Windows) with
defaults (ie start on 8080 port). For more information on running the
controller see [[OpenDaylight Controller
Installation|https://wiki.opendaylight.org/view/OpenDaylight_Controller:Installation]
* Goto mininet VM and create a topology for the controller

Back in the DLUX terminal, type

------------
$ grunt live
------------

Open a browser and goto http://localhost:9000

This should bring up the DLUX UI and pull data from the controller
