__TOC__

[[getting-started-overall]]
== Getting Started Overall

1.  Getting help and general link:Communication[communication]
2.  Look into link:Weekly_Project_Meeting_List[ Weekly Project Meetings]
3.  GettingStarted:Development Environment Setup[Set Up your Development
Environment (OS, Development Tools etc)]
4. 
GettingStarted:Pulling,_Hacking,_and_Pushing_All_the_Code_from_the_CLI[Pulling
Hacking and Pushing All the Code from the CLI]
* link:GIT Cheat Sheet[GIT Cheat Sheet] - A quick reference guide for
common GIT commands and possible workflows.
5.  GettingStarted: Eclipse[GettingStarted: Eclipse] - Walks through how
to get Eclipse set up. Presently focuses on the controller source as an
example.
6.  GettingStarted:PushAndFix[ Push + fix scenario]
* link:Developer Best Practices[Developer Best Practices (In Progress)]
7.  link:Life Cycle of a Bug[Life Cycle of a Bug] - Provides an overview
of the life cycle of a bug and how it passes through various systems
etc.
8.  link:Example Code[Example Code] - Check out these examples of
various code that will introduce you to the controller and other
projects / functionality.
* OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step[Toaster Tutorial]
- Provides a simple walk through of the "Toaster" application which uses
the MD-SAL framework.
9.  OpenDaylight_Controller:MD-SAL:Startup Project Archetype[Startup
Project Archetype] - How to use the simple MD-SAL startup archetype
* OpenDaylight_Toolkit:MD-SAL-Simple_Archetype[MD-SAL Archetype] - Walks
through using a maven archetype to quickly generate some starter
projects based on the MD-SAL framework.
10. Getting hooked into the link:GPG[GPG Web of Trust]

[[javadoc-documentation]]
=== JavaDoc Documentation

* For the controller project, the latest javadoc can be found here:
**
https://jenkins.opendaylight.org/controller/job/controller-merge/lastSuccessfulBuild/artifact/target/apidocs/index.html[https://jenkins.opendaylight.org/controller/job/controller-merge/lastSuccessfulBuild/artifact/target/apidocs/index.html]
* For other projects, the documentation can be found at:
**
https://jenkins.opendaylight.org/<project>/job/<project>-merge/lastSuccessfulBuild/artifact/target/apidocs/index.html
** fill in the project's git repo name in place of

[[tasks-that-need-work]]
=== Tasks that need work

GettingStarted:Tasks that Need Work[Tasks that Need Work]

[[helpful-tips-and-tricks]]
== Helpful Tips and Tricks

[[osgi]]
=== OSGI

* GettingStarted:Executing Methods from the OSGI Console[Executing
Methods from the OSGI Console] - This is an awesome trick to allow you
to execute methods in your bundle directly by typing in the OSGI
console... very helpful during development :)
*
http://isurues.wordpress.com/2009/01/01/useful-equinox-osgi-commands/[Useful
Equinox OSGI Commands] - a very useful list of commonly used OSGI
commands

[[maven-archetypes]]
=== Maven Archetypes

Maven Archetypes are sort of like 'templates' for maven projects.
Currently for OpenDaylight we have the following archetypes:

* Maven Archetypes:odl-model-project[odl-model-project] - A maven
archetype to create a yang model project that will generate java code
from .yang files

[[md-sal-cliff-notes]]
=== MD-SAL Cliff Notes

* OpenDaylight_Controller:MD-SAL:CliffNotes[MD-SAL Cliff Notes]

[[getting-started-by-project]]
== Getting Started by Project

[[controller]]
=== Controller

Sign up for
https://lists.opendaylight.org/mailman/listinfo/controller-dev[controller-dev]
mailing list.

*
OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_the_CLI[
Pulling Hacking and Pushing Code from the CLI]

* OpenDaylight_Controller:Building_from_CLI[ Building from the CLI]

*
OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_Eclipse[
Pulling Hacking and Pushing Code from Eclipse]

[[vtn]]
=== OpenDaylight_Virtual_Tenant_Network_(VTN):Main[ VTN]

Sign up for
https://lists.opendaylight.org/mailman/listinfo/vtn-dev[vtn-dev] mailing
list.

* OpenDaylight_Virtual_Tenant_Network_(VTN):Main[ VTN Project Main page]
* OpenDaylight_Virtual_Tenant_Network_(VTN):Manager:Hacking[ Hacking VTN
Manager]

[[ovsdb]]
=== OVSDB

Jump on the IRC Channel #opendaylight-ovsdb on irc.freenode.net

* OVSDB:Installation_Guide[Installation Guide]

* OVSDB:User_Guide[User Guide]

* OVSDB:Developer_Guide[Developer Guide]

[[snmp4sdn]]
=== SNMP4SDN

Sign up for
https://lists.opendaylight.org/mailman/listinfo/snmp4sdn-dev[snmp4sdn-dev]
mailing list.

* SNMP4SDN:Installation_Guide[Installation Guide]

* SNMP4SDN:User_Guide[User Guide]

* SNMP4SDN:Developer_Guide[Developer Guide]

[[bgpcep]]
=== BGPCEP

Sign up for
https://lists.opendaylight.org/mailman/listinfo/bgpcep-dev[bgpcep-dev]
mailing list.

* BGP LS PCEP:User Guide[BGP LS PCEP:User Guide]

* BGP LS PCEP:Developer Guide[BGP LS PCEP:Developer Guide]

[[troubleshooting]]
== Troubleshooting

It may also be useful to look at the
OpenDaylight_Controller:Installation#Troubleshooting[controller
installation troubleshooting page].

[[build-issues]]
=== Build Issues

There are some common recurring issues in building OpenDaylight which
largely relate to the build environment and the occasional maven failing
to fetching a given file.

Also, in general, it's very difficult to debug an error if you only
include the one line of maven output which says it failed. It helps a
lot to run maven with the `-e` flag and then try to find the lines of
code where the actual error occurs.

[[java-version]]
==== Java Version

OpenDaylight assumes that you are building with Java 1.7. Make sure the
output of `java -version` matches that. Something like this:

` $ java -version` +
` java version "1.7.0_17"` +
` Java(TM) SE Runtime Environment (build 1.7.0_17-b02)` +
` Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)`

[[maven-version]]
==== Maven Version

OpenDaylight assumes the use of Maven 3.1.1 or newer. Make sure the
output of `mvn -v` matches that. Something like this:

` $ mvn -v` +
` Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)` +
` Maven home: /usr/local/maven` +
` Java version: 1.7.0_72, vendor: Oracle Corporation` +
` Java home: /opt/oracle-jdk-bin-1.7.0.72/jre` +
` Default locale: en_US, platform encoding: UTF-8` +
` OS name: "linux", version: "3.17.2-gentoo", arch: "amd64", family: "unix"`

[[errors-fetching-a-pom-or-jar-file]]
==== Errors fetching a pom or jar file

We're working on this, but for whatever reason, fetching artifacts and
pom files from nexus seems to occasionally run into issues where it will
either fail to download a necessary file, give you a version with zero
size or otherwise hiccup.

Often merely running the build again will fix the issue.

Other times, merely deleting the ~/.m2/ directories contents and then
rebuilding will fix the problem.

In rare cases, you may have to resort to actually finding the file that
isn't being copied and manually copying it down as described in this
https://lists.opendaylight.org/pipermail/controller-dev/2013-October/001496.html[mailing
list post].

[[out-of-memory-error-permgen-space]]
==== Out of memory error / PermGen space

If you run into an out of memory error while building either just a
normal out of memory error or one complaining about PermGen space, the
easiest way to fix this is to adjust your maven options as explained
here.

Increase the amount of memory by changing the "MAVEN_OPTS" ENV variable.
An example for a Bash shell is as follows:

` export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"` +
` syntax for setting varies on the OS used by the build machine. */`

You can verify the variable is set with the following in a Bash shell.

` $ export | grep MAVEN_OPTS` +
` declare -x MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"`

An example on a Linux based machine or a Mac you simply put "export"
before the variable. e.g. export MAVEN_OPTS="-Xmx1024m
-XX:MaxPermSize=1024m" (parentheses around the value after the equals
sign). That ENV variable is not persistent unless you put it into a
shell startup script. In Linux for example the ~/.bashrc file and Mac
the ~/.bash_profile file.

[[skipping-tests]]
==== Skipping Tests

While the various tests run during build are huge at helping to find
bugs and they have to pass for a patch to be accepted, sometimes they
get in the way of finding the root cause of a build error. You can
disable them by adding `-DskipTests` to the end of your build command.
So something like this:

` mvn clean install -DskipTests`
