__TOC__

[[overview]]
= Overview

This page is intended to help developers get started on setting up their
development environment, specifically links to operating systems, tools
and utilities that prove useful during development.

[[quick-start]]
= Quick Start

If you are looking for a quick start, consider downloading one of the
Fedora VMs located on the
http://www.opendaylight.org/software/downloads[downloads] page of the
OpenDaylight project, specifically the Techtorial Fedora VM.

[[manual-set-up]]
= Manual Set Up

The remainder of this guide discusses how to set up the development
environment using Fedora (linux) environment.

1.  Download and Install https://fedoraproject.org/[Fedora]
2.  Download and install the Java JDK (version 1.7 seems to be the
supported version for ODL at this point).
3.  Download and install http://maven.apache.org/download.cgi[maven]
* Once you have downloaded and unzipped maven, I found it handy to
create a symbolic link to mvn from the /usr/bin directory so mvn can be
found in your path without having to modify the path variable. To set
the symbolic link you can use this command: +
 ln -s /opt/maven/bin/mvn /usr/bin/mvn +
 _Assumes maven was extracted to /opt/_
* Edit your .bashrc file to set default maven options to increase the
amount of memory used for compiling.
1.  vi ~/.bashrc
2.  Add export MAVEN_OPTS='-Xmx1048m -XX:MaxPermSize=512m' +
_Note, you can increase the heap space, the -Xmx setting, to greater
that 1G if memory is available. When building in maven, the max memory
reached will be displayed at the end of the build. You can use this as a
guide to determine if more memory would help decrease build times._
4.  Install GIT. One of the great advantages of using linux is yum
(supported by some linux distributions, such as Fedora) :). To install
GIT, run the following YUM command:
* yum install curl-devel expat-devel gettext-developenssl-devel
zlib-devel
5.  Install wireshark - Wireshark is utility use for capturing
individual packets between devices. Again, using yum, install wireshark:
* yum install wireshark-gnome
6.  Finally, continue your environment set up by following the next
steps outline on the GettingStarted:Developer Main[Getting Started]
page.

_Note: If you find there are missing tools or utilities that are
required for a develop to get started, please add them to the list!_
