[[introduction]]
== Introduction

[[taking-advantage-of-project-infrastructure]]
== Taking Advantage of Project Infrastructure

There is a detailed overview of the
OpenDaylight_Controller:Development_Infrastructure_Overview[ Development
Infrastructure] that will give you a good conceptual framework. Most of
what is written here is about concrete getting things done stuff :)

[[jenkins-setup]]
=== Jenkins Setup

Each project in OpenDaylight has it's own Jenkins instance which can be
found at http://jenkins.opendaylight.org/repo name/ (where repo_name is
the name of your repo, for example controller, or vtn, or ovsdb). or
linked off of http://jenkins.opendaylight.org

Each project can decide for itself how it wants to structure its
Continuous Integration with Jenkins, but a useful pattern is to have the
following Jobs:

1.  *-verify :* - A Job to run against each patch submitted to Gerrit to
automatically 'Verify' that patch prior to code review and consideration
for submission. This Job runs the build and tests to make sure the patch
can build and pass existing tests.
GettingStarted:Jenkins Verify Job Setup[Jenkins Verify Job Setup]
2.  *-merge:* - A Job to run against master (or some other repo branch)
just after a new patch is merged. This Job reruns the build and tests
and publishes artifacts to Nexus.
GettingStarted:Jenkins Merge Job Setup[Jenkins Merge Job Setup]
3.  *--integration* - A Job to run whenever a project you depend on
updates its artifacts (ie, it merged a change). For example, controller
depends on yangtools, and so has a controller-yangtools-intergration
Job. GettingStarted:Jenkins Integration Job Setup[Jenkins Integration
Job Setup]

