[[description]]
== Description

The yangtools allows a simple model to be written in yang and a lot of
useful Java code to be generated from it. It would be helpful to have

`a simple starter project into which folks could simply copy into their git repos and copy in their yang files and get going.`

[[deliverables]]
== Deliverables

1.  A 'modelstarter/' maven project that could be copied into folks git
repo, renamed, and edited slightly to get going with a yang model
2.  A wiki page describing how to adapt model starter for use to start a
new model maven project.

[[pointers]]
== Pointers

1.  Start by checking out yang tools with
+
::
-------------------------------------------------------------------
git clone ssh://<username>@git.opendaylight.org:29418/yangtools.git
-------------------------------------------------------------------
2.  Build it with
+
::
-----------------
mvn clean install
-----------------
3.  Look at code-generator/samples/modeling-sample as a simple example
project
4.  Use it as as starting point to create a new modelstarter project.
1.  Note: The existing modeling-sample depends on building the whole
yangtools from the top level

so you will need to break it off to build independently.
