[[description]]
== Description

Every OpenDaylight project is likely to need two kinds of starter maven
projects:

1.  *A parent pom project* - to house the common 'parent' pom.xml file
that is read in for common data like repositories and shared
dependencies for other maven projects and to build all of the modules
from one place
2.  *A distribution directory* - to allow each project to have a
'distribution' directory that rolls up its own local version of the
controller for use in development, allowing the exclusion of or addition
of modules

[[deliverables]]
== Deliverables

1.  A 'starter' 'commons/parent' and 'distribution/' directories
suitable for ODL projects to copy into the top level of their git repo
2.  A wiki page explaining how to do so and modify them for their
project, including:
1.  Adding new modules to be built to the 'commons/parent/pom.xml'
2.  Including/excluding modules in the 'distribution/pom.xml'
3.  How to use both to build

[[pointers]]
== Pointers

We have some examples to start from in:

https://git.opendaylight.org/gerrit/#/c/390/[Gerrit 390] and the
combination of https://git.opendaylight.org/gerrit/#/c/784/[Gerrit 784]
and https://git.opendaylight.org/gerrit/#/c/785/[Gerrit 785].

[[notes]]
== Notes:

1.  The commons/parent directory should *not* have the
commons.opendaylight directory as it's parent pom (as it does in the
examples for OVSDB Gerrits 784 and 785)
2.  Please feel free to push these directories into a directory
'starters/' in the controller project
3.  Please look into things like
http://stackoverflow.com/questions/160608/how-to-do-a-git-export-like-svn-export[git
archive] to provide instructions to folks on how to pull the freshest
starter in a way that allows them to drop it cleanly into their own git
repo.

[[mentor]]
== Mentor

This task is mentored by Ed Warnicke, you can reach him most easily on
IRC on Freenode with handle edwarnicke, but email to eaw@cisco.com also
works :)
