[[intro]]
== Intro

This page is a tabulation of known Tasks that Need Work. Please try to
drop anything that comes to mind here. When listing a Task please
provide a subpage giving a sketch as to how to do the task, and list
yourself as Mentor. When picking up a Task, please list yourself with
the Volunteers and update the Date Started. If someone else has picked
up a task, please feel free to contribute as well, but contact them to
coordinate :)

[[tasks]]
== Tasks

[cols=",,,,,",options="header",]
|=======================================================================
|Task Name |Task Page |Mentor |Volunteer(s) |Date Started |ETA
|Starter Parent and Distribution Projects
|GettingStarted:Starter Parent and Distribution Projects[Starter Parent
and Distribution Projects] |Ed Warnicke IRC handle: edwarnicke | | |

|Starter Model Project |GettingStarted:Starter Model Projects[Starter
Model Projects] |Ed Warnicke IRC handle: edwarnicke |Ed Warnicke IRC
handle: edwarnicke |Maven_Archetypes:odl-model-project[Done] |

|Starter OSGI Bundle Project
|GettingStarted:Starter OSGI Bundle Projects[Starter OSGI Bundle
Project] |Ed Warnicke IRC handle: edwarnicke | | |

|Improve Consistency APIs |link:New Consistency and Clustering[New
Consistency and Clustering] |Colin Dixon (IRC: colindixon) and others |
| |

|Performance Integration Tests
|GettingStarted:Performance Integration Tests[Performance Integration
Tests] |Colin Dixon IRC handle: colindixon +
Muthukumaran Kothandaraman | | |

|Debug Exceptions in Performance Branch
|GettingStarted:Debug Performance Branch[Debug Performance Branch]
|Colin Dixon IRC handle: colindixon +
Muthukumaran Kothandaraman | | |

|Better Host Tracker |D-E_Proposal:Host_Tracker_Plan[Host Tracker Plan]
|Colin Dixon IRC handle: colindixon +
Kalvin Hom | | |

|Durable State (aka configuration)
|GettinStarted:Durable State Plan[Durable State Plan] |Colin Dixon IRC
handle: colindixon +
Madhu Venugopal IRC handle: madhu +
Ed Warnicke IRC handle: edwarnicke +
 Giovanni Meo IRC handle: GiovanniMeo | | |

|Virtual Network Statistics (VTN Project) |TBD |Tomohisa Yamabe
(t-yaabe@bp.jp.nec.com) +
 Shigeru Yasuda (s-yasuda@da.jp.nec.com) +
 Hideyuki Tai (Hideyuki.Tai@necam.com) IRC handle: hideyuki | | |

|vRouter (VTN Project) |TBD |Tomohisa Yamabe (t-yaabe@bp.jp.nec.com) +
 Shigeru Yasuda (s-yasuda@da.jp.nec.com) +
 Hideyuki Tai (Hideyuki.Tai@necam.com) IRC handle: hideyuki | | |

|CIT Java |GettingStarted:Integration_CIT_Java[Integration CIT Java]
|Moiz Raja IRC Handle : moizer +
 Guangpeng Li IRC handle: GuangpengLi |Swaraj Vinjapuri |09/23/2013 |

|Test Tools |GettingStarted:Integration_Test_Tools[Integration Test
Tools] |Carol Sanders  +
 Huang Denghui |Punal Patel  +
 Baohua Yang IRC handle: baohua |09/23/2013 |

|Release Features
|GettingStarted:Integration_Release_Features[Integration Release
Features] |Punal Patel  +
 Baohua Yang IRC handle: baohua |Carol Sanders  +
 Guangpeng Li IRC handle: GuangpengLi |09/23/2013 |

|CSIT Test Plan |GettingStarted:Integration_CSIT_Test_Plan[Integration
CSIT Test Plan] |Luis Gomez IRC handle: LuisGomez +
 Baohua Yang IRC handle: baohua | |10/25/2013 |
|=======================================================================

