[[fixes]]
= Fixes

* OpenDaylight OpenFlow Plugin:Backlog:Node Status Reconciliation[Node
Status reconciliation between controller/switch on switch reconnect, fix
datastore lifecycle]
* Urgent: Fix adapters to not have race condition
* Check for and sort out any lingering OF10 issues in OFplugin
*
OpenDaylight OpenFlow Plugin:Backlog:Statistics collection performance improvements[Statistics
collection performance improvements]
* Revisit & cleanup the OF yang models

[[new-features]]
= New Features

* Migrate the OF Plugin onto the Configuration Subsystem -
OpenDaylight_OpenFlow_Plugin::Config_Subsystem[done]
** Implement changes to allow
OpenDaylight_OpenFlow_Plugin:Backlog:Extensibility[extensibility] in OF
Library and OF Plugin (registers, ...)
* Plugin internal stats - add more, make stats accessible through the
config subsystem
* Handle reserve ports as actual named things (and fix adapters around
that) (note: OF10 and OF13 have different port numbers for the same
logical reserve ports... adapters should also be fixed to handle)
* Make topology initially aggressive then very calm
*
OpenDaylight_OpenFlow_Plugin:Backlog:Threading Model and Packet Handling Priority[Threading
Model and Packet Handling Priority]
* OpenDaylight_OpenFlow_Plugin:_TLS_Support[TLS support]
* Table config and capabilities learning .
* Port config.
* Queue config.
* DTLS based connection establishment not supported.
* Role request not supported.
* Make the OpenDaylight GUI 1.3 aware (not exactly plugin specific
feature - just capturing here anyway). Example: to be able to configure
1.3 style flows, meters and groups.
* OpenDaylight_OpenFlow_Plugin:Backlog:FlowCookieLifecycle[move/merge
flow.id (model) to flow.cookie (protocol) = flowCookie lifecycle]

*
OpenDaylight_OpenFlow_Plugin:Backlog:Overload Protection and Event Dampening[Overload
Protection and Event Dampening]
*
OpenDaylight_OpenFlow_Plugin:Backlog:MultiControllerAndArbiterDesign[Multi-controller
and Arbiter]

[[testing]]
= Testing

* Implement regression testing during Jenkins builds ('integration
testing VM for the OF plugin')
* Performance & scale testing:
** Mininet & cbench
** Real hardware topologies
* Convert existing python regression tests to roboto framework and make
it part of integration project and their automated testing framework.

