[[requirements]]
== Requirements

* linux
* xsltproc
* graphviz

[[environment-setup]]
== Environment setup

`git clone `https://gist.github.com/01c3c92aab67c2bc813e.git[`https://gist.github.com/01c3c92aab67c2bc813e.git`]` karafFeatureTree` +
`ln -s karafFeatureTree/analyzeFeatures.sh` +
`ln -s `` myProject`

[[generate-tree-graph]]
== Generate tree graph

[[two-steps]]
=== Two steps

`# prepare feature tree data (step 1/2)` +
`./analyzeFeatures.sh myProject/ > fxDeps.dot` +
`# generate graph from prepared .dot file into png file (step 2/2)` +
`dot fxDeps.dot -O -T png -Gsize="20,20" -Efontsize=10 -Nshape=record -Estyle=dashed -Earrowhead=open`

[[all-in-one-step]]
=== All in one step

*Preview*

`# generate graph from direct pipe input into x11 window` +
`./analyzeFeatures.sh myProject/ | dot -O -T x11 -Gsize="17,17" -Efontsize=10 -Nshape=record -Estyle=dashed -Earrowhead=open`

*To png file*

`# generate graph from direct pipe input into file` +
`./analyzeFeatures.sh myProject/ | dot -o fxDeps.dot.png -T png -Gsize="17,17" -Efontsize=10 -Nshape=record -Estyle=dashed -Earrowhead=open`
