[[fixes]]
= Fixes

*
OpenDaylight OpenFlow Plugin:Backlog:Statistics collection performance improvements[Statistics
collection performance improvements] - any further optimizations??
* Revisit & cleanup the OF yang models

[[features]]
= Features

* Handle reserve ports as actual named things (and fix adapters around
that) (note: OF10 and OF13 have different port numbers for the same
logical reserve ports... adapters should also be fixed to handle) -
STATUS: check with Kamal for any remaining TODOs
* Make topology initially aggressive then very calm - STATUS: . –
topology works but may be sending too many LLDP packets & probably
should use the node connector notifications when change in the network
(in steady state); needs redesign / review / optimizations (look into
HP’s proposal as well). Optimizations should be done after the
clustering design is in place.
*
OpenDaylight_OpenFlow_Plugin:Backlog:Threading Model and Packet Handling Priority[Threading
Model and Packet Handling Priority]
* Port config.
* Queue config.
* Role request (Multi controller feature).
* Make the OpenDaylight GUI 1.3 aware (not exactly plugin specific
feature - just capturing here anyway). Example: to be able to configure
1.3 style flows, meters and groups.

*
OpenDaylight_OpenFlow_Plugin:Backlog:MultiControllerAndArbiterDesign[Multi-controller
and Arbiter]

[[obsolete-feature-sign-up-sheet]]
== OBSOLETE (Feature Sign Up Sheet)

Obsoleted by Trello (kept for reference): The sheet for signing up for
features is at
https://docs.google.com/spreadsheets/d/1BePeDvDIEgHf7A0hP-jgEY0sRmgT4FbjtZIVqZQOXXk/edit#gid=0[GoogleDoc
Spreadsheet].

[[testing]]
= Testing
