[[what-to-build]]
== What to build

The lithium design proposal related code resides at the master of
ofPlugin and coexists with current implementation (utilized in Helium).
The plan is to have two features for starting Li or He version.

So first step is to simply build the master from root of openflowplugin
project:

`mvn clean install -DskipTests`

[[how-to-start]]
== How to start

There are all helium features (from features-openflowplugin) duplicated
into features-openflowplugin-li. The duplicates got suffix *'-li*' and
provide Lithium codebase functionality.

These are most used:

* odl-openflowplugin-app-lldp-speaker-li
* odl-openflowplugin-flow-services-rest-li
* odl-openflowplugin-drop-test-li

In case topology is required then the first one should be installed.

`feature:install odl-openflowplugin-app-lldp-speaker-li`

The Li-southbound currently provides:

* flow management
* group management
* meter management
* statistics polling

[[what-to-log]]
== What to log

In order to see really low level messages enter these in karaf console:

`log:set TRACE org.opendaylight.openflowplugin.openflow.md.core` +
`log:set TRACE org.opendaylight.openflowplugin.impl`

[[extra-for-topology]]
== Extra for topology

In order for topology to work (fill dataStore/operational with links)
there must be LLDP responses delivered back to controller. This requires
table-miss-entries. Table-miss-entry is a flow in table.id=0 with low
priority, empty match and one output action = send to controller. Having
this flow installed on every node will enable for gathering and
exporting links between nodes into dataStore/operational

 +
`   ``false` +
`   ``54` +
`   ``SEND_FLOW_REM` +
`   ``FooXf54` +
`   ``0` +
`   ``4242` +
`   ``0` +
`   ``false` +
`   ` +
`       ` +
`           ` +
`               ` +
`                   ` +
`                       ``65535` +
`                       ``CONTROLLER` +
`                   ` +
`                   ``0` +
`               ` +
`           ` +
`           ``0` +
`       ` +
`   ` +
`   ` +
`   ``0` +
`   ``false` +
`   ``0` +

