[[meeting-logs]]
= Meeting Logs

[[webex-recordings-of-infodiscussion-sessions]]
== Webex Recordings of info/discussion sessions

* OpenFlow Plugin Connection Handling by Michal Rehak
**
https://cisco.webex.com/ciscosales/lsr.php?RCID=b7f653bc0cb2442eb445990e041af76b[Session
1, March 17, 2014]
**
https://cisco.webex.com/ciscosales/lsr.php?RCID=db7e270cbff94abb89f1c63cb53bedd7[Session
2, March 18, 2014]
***
[https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin::Sequence_Diagrams
Sequence Diagrams used for the session]
* Feedback of using OpenFlow 1.3 by Brent Salisbury - OpenFlow plugin
meeting, May 19, 2014
**
https://meetings.webex.com/collabs/files/viewRecording?encryptData=1_0ED4CB11B5D7C3A3117C2BF1728A47F60FB860EBD430F3ED7B500F38468AA3B0EB5662D929D90689EF584D3EAA46F854600788AE4A0616B0CD58FC2F91E2ADF6523721F97E967D64C300C1F04BB46674_E89EF8DCEBFEDB355C44D01ED10FD351E9F519F8[Webex
Recording]
***
https://www.dropbox.com/s/ojd6uooyx69gjn6/OF13-Feedback-Slides.pdf[Slides]
* OpenFlow Experimenter Framework Session
**
https://meetings.webex.com/collabs/url/_NC4R-gxWwy245KgV4yTQTH8qN4ijJ5jksPZH2kOMYW00000[June
16, 2014 Session by Prasanna Huddar]
***
https://wiki.opendaylight.org/view/OpenDaylight_OpenFlow_Plugin:Helium_Design[Slides]
**
https://meetings.webex.com/collabs/url/jwSDLWB1PFjmN1t-UlMs0jTkN4CrUmCn1CaAvPQm5VC00000[July
8, 2014 Session by Michal Rehak with an alternate design]
*** OpenDaylight_OpenFlow_Plugin:Backlog:Extensibility[Info]
**
https://meetings.webex.com/collabs/url/Nm9ykAvgCMWfT9UYi87IDWhZ0ctN9m7qEK3_xmE_g3u00000[July
22, 2014 Session/demo by Michal Rehak]
* OpenFlow HP Plugin
**
https://meetings.webex.com/collabs/url/nGnPaKEdg5oc-4ZY2MDM7DIovz0K8dEE_rae4_fNjE000000[July
15 Session by HP]
**
https://meetings.webex.com/collabs/url/WL474cYgfhtroa2Mybg86jwhkuudayiZQ8xnwA-k4-q00000[Aug
26 Session by HP to OpenFlow Plugin committers doing the code review]

 +

[[irc-logs-meeting-minutes]]
== IRC Logs / Meeting Minutes

* Daily Scrum 8/18/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/openflow_plugin_daily_scrum/opendaylight-openflowplugin-openflow_plugin_daily_scrum.2014-08-18-14.01.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/openflow_plugin_daily_scrum/opendaylight-openflowplugin-openflow_plugin_daily_scrum.2014-08-18-14.01.log.html[Log]
* Daily Scrum 8/15/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum/opendaylight-openflowplugin-of_plugin_daily_scrum.2014-08-15-14.01.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum/opendaylight-openflowplugin-of_plugin_daily_scrum.2014-08-15-14.01.log.html[Log]
* Daily Scrum 8/14/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum_aug_14/opendaylight-openflowplugin-of_plugin_daily_scrum_aug_14.2014-08-14-14.01.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum_aug_14/opendaylight-openflowplugin-of_plugin_daily_scrum_aug_14.2014-08-14-14.01.log.html[Log]
* Daily Scrum 8/11/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily/opendaylight-openflowplugin-ofplugin_daily.2014-08-11-14.01.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily/opendaylight-openflowplugin-ofplugin_daily.2014-08-11-14.01.log.html[Log]
* Daily Scrum 8/8/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum_aug_8/opendaylight-openflowplugin-of_plugin_daily_scrum_aug_8.2014-08-08-14.10.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/of_plugin_daily_scrum_aug_8/opendaylight-openflowplugin-of_plugin_daily_scrum_aug_8.2014-08-08-14.10.log.html[Log]
* Daily Scrum 8/7/2014
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily/opendaylight-openflowplugin-ofplugin_daily.2014-08-07-14.06.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily/opendaylight-openflowplugin-ofplugin_daily.2014-08-07-14.06.log.html[Log]
* Daily Scrum 8/6/2014
https://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily_scrum/opendaylight-openflowplugin-ofplugin_daily_scrum.2014-08-06-14.08.html[Minutes]
http://meetings.opendaylight.org/opendaylight-openflowplugin/2014/ofplugin_daily_scrum/opendaylight-openflowplugin-ofplugin_daily_scrum.2014-08-06-14.08.log.html[Log]

Category:OpenDaylight OpenFlow Plugin[Category:OpenDaylight OpenFlow
Plugin]
