[[opendaylight-controller-plugin-options]]
== Opendaylight Controller Plugin Options

[[to-run-the-opendaylight-controller-with-the-new-openflow-1.01.3-new-plugin]]
=== To run the OpenDaylight controller with the new OpenFlow 1.0/1.3
(new) plugin

There are 2 ways. In integration project the plugin version is
controlled by startup parameter. Or there is distribution build
available directly in openflowplugin project.

1.  use *integration/distributions/base* project
* download and unzip latest build from
http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distributions-base
+
::
  `cd opendaylight`
* or clone and build *integration* project:
+
::
  `git clone https://git.opendaylight.org/gerrit/p/integration.git`
  +
  `cd integration/distributions/base`
  +
  `mvn clean install`
  +
  `cd target/distributions-base-???-SNAPSHOT-osgipackage/opendaylight`
* and finally run
+
::
--------------
./run.sh -of13
--------------
2.  use *openflowplugin* project
* download and unzip latest build from
http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/openflowplugin/distributions-openflowplugin-base
+
::
  `cd opendaylight`
* or clone and build *openflowplugin* project:
+
::
  `git clone https://git.opendaylight.org/gerrit/p/openflowplugin.git`
  +
  `cd openflowplugin`
  +
  `mvn clean install`
  +
  `cd distribution/base/target/distributions-openflowplugin-base-???-SNAPSHOT-osgipackage/opendaylight/`
* and finally run (there is no version specific option - because the
1.0-only (old) plugin is not present here at all)
+
::
--------
./run.sh
--------

[[to-run-the-opendaylight-controller-with-the-old-openflow-1.0-only-old-plugin]]
=== To run the OpenDaylight controller with the old OpenFlow 1.0-only
(old) plugin

There are 2 ways. In integration project the plugin version is
controlled by startup parameter. Or there is distribution build
available directly in controller project.

1.  use *integration/distributions/base* project
* use the instructions from
OpenDaylight_OpenFlow_Plugin::Running_controller_with_the_new_OF_plugin#To_run_the_OpenDaylight_controller_with_the_new_OpenFlow_1.0/1.3_(new)_plugin[
1.0/1.3 plugin], but skip the plugin version parameter:
+
::
--------
./run.sh
--------
2.  use *controller/distribution/opendaylight* project
* download and unzip latest build from
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/controller/distribution.opendaylight/
+
::
  `cd opendaylight`
* or clone and build *controller* project:
+
::
  `git clone https://git.opendaylight.org/gerrit/p/controller.git`
  +
  `cd controller/opendaylight/distribution/opendaylight`
  +
  `mvn clean install`
  +
  `cd target/distribution.opendaylight-osgipackage/opendaylight`
* and finally run (there is no version specific option, because the
1.0/1.3 (new) plugin is not available here at all)
+
::
--------
./run.sh
--------

*Give it a minute to come up :)*
