 The OpenFlow renderer is based on the
Group_Policy:Architecture/OVS Overlay[OVS Overlay] design and implements
a network virtualization solution for virtualized compute environments
using Open vSwitch, OpenFlow and OVSDB remotely from the controller.

[[renderer-architecture]]
== Renderer Architecture

[[switch-manager]]
=== Switch Manager

Manage connected switch configuration using OVSDB. Maintain overlay
tunnels.

[[endpoint-manager]]
=== Endpoint Manager

Optionally learn endpoints based on simple rules that map interfaces to
endpoint groups. Can add additional rules in the future. Keep endpoint
registry up to date. If disabled, then an orchestration system must
program all endpoints and endpoint mappings.

[[arp-and-dhcp-manager]]
=== ARP and DHCP Manager

convert ARP and DHCP into unicast

[[policy-manager]]
=== Policy Manager

subscribe to renderer common infrastructure, and switch and endpoint
manager. Manage the state of the flow tables in OVS.

[[configuration]]
== Configuration

XXX - TODO

* Mapping of interfaces to endpoint groups
* Mapping of endpoint groups to vnids/classes

