 The OpFlex renderer is based on the
Group_Policy:Architecture/OVS Overlay[OVS Overlay] design and implements
a network virtualization solution for virtualized compute environments
by communicating with the OpFlex Agent.

[[renderer-architecture]]
== Renderer Architecture

XXX - TODO Main pieces:

* Agent Manager: Manage connected agents using OpFlex.
* RPC Library: Manage serialization/deserialization of JSON RPC with
Policy Elements
* OpFlex Messaging: Provides definition of OpFlex messages and
serialization/deserialization into Managed Objects
* Endpoint manager: Optionally learn endpoints based on simple rules
that map interfaces to endpoint groups. Can add additional rules in the
future. Keep endpoint registry up to date. If disabled, then an
orchestration system must program all endpoints and endpoint mappings.
* Policy manager: subscribe to renderer common infrastructure and
endpoint registry and provide normalized policy to agents

[[configuration]]
== Configuration

XXX - TODO

* Mapping of interfaces to endpoint groups
* Configuration of Policy Repository, Endpoint Registry, and Observer
addressing

