 The renderers have available to them some service and libraries that
collectively make up the _renderer common framework._ These are not
actually required to implement a renderer, but where convenient
functionality that would be generally useful should be placed here.

[[inheritanceutils]]
== `InheritanceUtils`

This class provides a convenient utility to resolve all the complex
inheritance rules into a normalized view of the policy for a tenant. `
    /**
     * Fully resolve the specified {@link Tenant}, returning a tenant with all 
     * items fully normalized.  This means that no items will have parent/child 
     * relationships and can be interpreted simply without regard to inheritance
     * rules 
     * @param tenantId the {@link TenantId} of the {@link Tenant}
     * @param transaction a {@link DataModificationTransaction} to use for 
     * reading the data from the policy store
     * @return the fully-resolved {@link Tenant}
     */
    public static Tenant resolveTenant(TenantId tenantId,
                                       DataModificationTransaction transaction)
`

[[policyresolverservice]]
== `PolicyResolverService`

The policy resolver service resolves the policy model into a
representation suitable for rendering to an underlying network. It will
run through the contract resolution and

The policy resolver is a utility for renderers to help in resolving
group-based policy into a form that is easier to apply to the actual
network.

For any pair of endpoint groups, there is a set of rules that could
apply to the endpoints on that group based on the policy configuration.
The exact list of rules that apply to a given pair of endpoints depends
on the conditions that are active on the endpoints.

In a more formal sense: Let there be endpoint groups _G~n~_, and for
each _G~n~_ a set of conditions _C~n~_ that can apply to endpoints in
_G~n~_. Further, let _S_ be the set of lists of rules defined in the
policy. Our policy can be represented as a function _F_: (_G~n~_,
2^_C~n~_^, _G~m~_, 2^_C~m~_^) -> _S_, where 2^_C~n~_^ represents the
power set of _C~m~_. In other words, we want to map all the possible
tuples of pairs of endpoints along with their active conditions onto the
right list of rules to apply.

We need to be able to query against this policy model, enumerate the
relevant classes of traffic and endpoints, and notify renderers when
there are changes to policy as it applies to active sets of endpoints
and endpoint groups.

The policy resolver will maintain the necessary state for all tenants in
its control domain, which is the set of tenants for which policy
listeners have been registered.
