Application-Layer Traffic Optimization (ALTO) is an IETF protocol to
provide network information to applications. The ALTO project in
OpenDayLight is an effort to implement ALTO in OpenDayLight. In addition
to implementing the ALTO base protocol (RFC7285), the project leverages
OpenDayLight to introduce a provisioning interface for ALTO.

[[project-information]]
== Project Information

* Although OpenDayLight already provides a topology service, it focuses
more on detailed network topology (i.e., raw topology) that can be too
detailed for applications and/or reveal too much network details to
violate network privacy. The ALTO Protocol (RFC 7285) defines
abstractions and services to provide simplified network views and
network services to guide application usage of network resources. In
particular, the ALTO Protocol defines the Network and Cost Map Service,
Filtered Map Service, Endpoint Property Service, and Endpoint Cost
Service. The details of the services can be found in
https://tools.ietf.org/html/rfc7285[RFC7285]. The objective of this
project is to implement these services as Northbound APIs in ODL for
others to use.

* ALTO:LithiumReleaseNotes[Lithium Release Notes]
* ALTO:LithiumReleasePlan[Lithium Release Plan]
* Project_Proposals:Alto[Lithium Project Proposal]

[[getting-started-for-users]]
== Getting Started for Users

This is the right place to start when using ALTO. Since this is the
initial release of ALTO in OpenDaylight, the focus is on providing basic
functions, leaving more advanced features to the next release.

The *ALTO:Lithium_Installation_Guide[ ALTO Installation Guide]* will
navigate you through the steps to install ALTO.

The *ALTO:Lithium_User_Guide[ ALTO User Guide]* will navigate you
through the steps to use ALTO.

Problems? Questions? Please contact _alto-users@lists.opendaylight.org_
.

[[information-for-developers]]
== Information for Developers

The *ALTO:Lithium_Developer_Guide[ ALTO Developer Guide]* should be your
start reading if you want to know the implementation components of ALTO
to implement additional features.

[[meetings-open-to-all]]
=== Meetings (open to all)

* Topic: ODL - Weekly ALTO Project meeting using Skype
* Date/Time: Tuesday's at 9 AM PST
* Host(s): Y. Richard Yang (yry@cs.yale.edu).

Please contact hosts to join the Skype meetings.

[[clustering-support]]
=== Clustering Support

* The ALTO project will work in a cluster configuration, and as an
MD-SAL application, it does not require special code to operate in a
clustered configuration.

Problems? Questions? Please contact alto-dev@lists.opendaylight.org .

[[list-of-all-subpages]]
== List of All Subpages
